### ISSUE TITLE
Monitor.Models.LogToMetricAction not available in nuget Package Microsoft.Azure.Management.Monitor 0.20.1-preview

### ISSUE THREAD

**Issue by ajaygit158-zz** [Azure/azure-sdk-for-net#4853] opened 2018-10-10 09:31 UTC
The issue is related to the Swagger spec for ScheduledQueryRules API
https://github.com/Azure/azure-rest-api-specs/blob/master/specification/monitor/resource-manager/microsoft.insights/stable/2018-04-16/scheduledQueryRule_API.json

One of the class "LogToMetricAction" does not exist in the 0.20.1-preview version of Nuget package Microsoft.Azure.Management.Monitor. The LogToMetricAction.cs should have got generated https://github.com/Azure/azure-sdk-for-net/tree/psSdkJson6/src/SDKs/Monitor/Management.Monitor/Generated/Models
Locally building using generate.cmd generates this class.

**Comment by msvijayn** [comment] 2019-06-28 13:06
Thank you for reporting the issue. Azure Monitor Alerts team is investigating the report and we'll revert back to you shortly.

**Comment by msvijayn** [comment] 2019-07-08 06:59
@snehithm - can you please assign this to @abver

**Comment by abver** [comment] 2019-07-17 13:09
SDK is automatically generated from swagger spec. This needs to be investigated from SDK team. @msvijayn please assign accordingly.

**Comment by msvijayn** [comment] 2019-07-17 15:13
@snehithm - can you please reassign this to Azure SDK team based on comment from @abver .
I believe owners for Azure .NET SDK are @shahabhijeet and @kurtzeborn

**Comment by msvijayn** [comment] 2019-07-17 15:37
@shahabhijeet - assigning the issue to you as indicated by @abver the issue is apparently emanating by SDK team.

**Comment by jsquire** [comment] 2020-10-12 20:51
Closing this out as this refers to a legacy version of the library and there has been no recent engagement.  Please feel free to reopen or file a new issue if this remains a problem with the current version of the library.

**Closed by jsquire** 2020-10-12 20:51 UTC
Labels: Monitor - Alerts, bug, customer-reported, needs-team-attention
