### ISSUE TITLE
[BUG] List database error: The requested operation requires an element of type 'Number', but the target element has type 'String'

### ISSUE THREAD

**Issue by zhiweiv** [Azure/azure-sdk-for-net#28597] opened 2022-05-08 04:51 UTC
### Library name and version

Azure.ResourceManager.Sql 1.0.0-beta.4

### Describe the bug

When list database, I got following error
```
System.InvalidOperationException: The requested operation requires an element of type 'Number', but the target element has type 'String'.
   at System.Text.Json.JsonDocument.TryGetValue(Int32 index, Int64& value)
   at System.Text.Json.JsonElement.GetInt64()
   at Azure.ResourceManager.Sql.SqlDatabaseData.DeserializeSqlDatabaseData(JsonElement element)
   at Azure.ResourceManager.Sql.Models.DatabaseListResult.DeserializeDatabaseListResult(JsonElement element)
   at Azure.ResourceManager.Sql.DatabasesRestOperations.ListByElasticPool(String subscriptionId, String resourceGroupName, String serverName, String elasticPoolName, CancellationToken cancellationToken)
```

From fiddler, the list request uses api version **2014-04-01**, the maxSizeBytes in response is string instead of number.

### Expected behavior

If I use following code to force the latest api version, the list request works fine.
```
var armOpt = new ArmClientOptions();
armOpt.SetApiVersion(SqlDatabaseResource.ResourceType, "2021-11-01-preview");
var armClient = new ArmClient(new DefaultAzureCredential(), null, armOpt);
```

This library should use correct api version by default to make everything work.

### Reproduction Steps

```
var armClient = new ArmClient();
var resId = "/subscriptions/xxx/resourceGroups/xxx/providers/Microsoft.Sql/servers/xxx/elasticPools/xxx";
var pools = armClient.GetElasticPoolResource(new ResourceIdentifier(resId)).GetDatabases().Count();
```

### Environment

.net 6.0 console app

**Comment by zhiweiv** [comment] 2022-05-08 06:28
Seems the api and model are generated by latest api version, but the request uses the oldest(2014-04-01), I found other apis return invalid data too.

**Comment by jsquire** [comment] 2022-05-08 13:46
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by fengzhou-msft** [comment] 2022-05-11 07:05
Duplicate of #28387. The fix will be released in the next beta version this month.

**Closed by fengzhou-msft** 2022-05-11 07:05 UTC
Labels: Mgmt, customer-reported, question, Network - Front Door, needs-team-attention
