### ISSUE TITLE
TableClient should expose a Uri property similar to BlobClient

### ISSUE THREAD

**Issue by PaulCheng** [Azure/azure-sdk-for-net#25949] opened 2021-12-15 09:21 UTC
### Library name

azure.data.tables

### Please describe the feature.

az powershell needs to display table uri

**Comment by jsquire** [comment] 2021-12-15 14:13
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by christothes** [comment] 2021-12-15 14:56
duplicate of #24415

**Closed by christothes** 2021-12-15 14:56 UTC
Labels: Client, Tables, needs-team-attention
