### ISSUE TITLE
Microsoft.WindowsAzure.Storage.StorageException: 'Requested value 'DELETE,GET,HEAD,MERGE,POST,OPTIONS,PUT,PATCH' was not found.'[BUG]

### ISSUE THREAD

**Issue by lakshmanraog** [Azure/azure-sdk-for-net#22366] opened 2021-07-01 08:05 UTC
Exceptions:
1.Microsoft.WindowsAzure.Storage.StorageException: 'Requested value 'DELETE,GET,HEAD,MERGE,POST,OPTIONS,PUT,PATCH' was not found.'[BUG]
2. System.InvalidOperationException: 'Invalid storage account '**accountname**'. Please make sure your credentials are correct.'

Reproduce Steps 
-----------------------------
Select the Azure Storage Account => 
Resource Sharing(CORS) =>
![image](https://user-images.githubusercontent.com/19513002/124087961-2234a580-da70-11eb-8be1-316f22268bd3.png)

Set the CORS LIKE ,

Then After Create Sample WEB JOB PROJECT in VS 2019,

WRITE CODE LIKE 

in PROGRAM.cs

CloudStorageAccount storageAccount = CloudStorageAccount.Parse(ConfigurationManager.ConnectionStrings["AzureWebJobsStorage"].ToString());

            var blobClient = storageAccount.CreateCloudBlobClient();
            var serviceProperties = blobClient.GetServiceProperties(); -----> Getting Exception  (1)
            var cors = new CorsRule();
            cors.AllowedOrigins.Add("*");
            cors.AllowedMethods = CorsHttpMethods.Get;
            cors.MaxAgeInSeconds = 360000;
            serviceProperties.Cors.CorsRules.Add(cors);
            blobClient.SetServiceProperties(serviceProperties);

            var config = new JobHostConfiguration();

            if (config.IsDevelopment)
            {
                config.UseDevelopmentSettings();
            }
            var host = new JobHost(config);
            config.UseTimers();
            // The following code ensures that the WebJob will be running continuously
            host.RunAndBlock(); ----> Getting Exception (2)

![image](https://user-images.githubusercontent.com/19513002/124088853-fc5bd080-da70-11eb-9572-53c38359972a.png)

**Comment by kasobol-msft** [comment] 2021-07-02 16:33
This is duplicate of https://github.com/Azure/azure-storage-net/issues/916 .
However, per [support statement](https://github.com/Azure/azure-storage-net#support-statement) we won't be fixing that anysoon, please upgrade to V12 .

**Closed by kasobol-msft** 2021-07-02 16:33 UTC
Labels: Client, Service Attention, Storage, customer-reported, needs-team-attention, question
