### ISSUE TITLE
[BUG] Azure.Messaging.ServiceBus SendMessage MessageSizeExeeded in Azure - Regression

### ISSUE THREAD

**Issue by Stabzs** [Azure/azure-sdk-for-net#33636] opened 2023-01-23 15:51 UTC
### Library name and version

Azure.Messaging.ServiceBus v7.12.0

### Describe the bug

When sending batches of messages that are relatively small (sub 1k), to a standard SKU Service Bus, with the following trivialized implementation:

``` CSharp
private ServiceBusSender _sender;

public async Task EnqueueBatchAsync<T>(List<T> messages, string correlationId)
{
	var count = 0;

	while (count < messages.Count)
	{
		using var messageBatch = await _sender.CreateMessageBatchAsync();

		while (count < messages.Count)
		{
			var message = messages[count];
			var serializedMessage = JsonConvert.SerializeObject(message);

			var serviceBusMessage = new ServiceBusMessage(serializedMessage)
			{
				ContentType = "application/json",
				MessageId = Guid.NewGuid().ToString(),
				CorrelationId = correlationId
			};
			
			if (messageBatch.TryAddMessage(serviceBusMessage))
			{
				count++;
				continue;
			}
			else
			{
				break;
			}
		}

		await _sender.SendMessagesAsync(messageBatch);
	}
}
```

even though the TryAddMessage attempt fails as expected before the batch is full, the batch fails to send with the following error message:

>  {"The message (id:15939002, size:265268 bytes) is larger than is currently allowed (262144 bytes). (MessageSizeExceeded). For troubleshooting information, see https://aka.ms/azsdk/net/servicebus/exceptions/troubleshoot."}

This appears to be a regression of https://github.com/Azure/azure-sdk-for-net/issues/19053 and downgrading from 7.12.0 to 7.11.1 fixes the issue.

### Expected behavior

All metadata associated with the message should be included in the size calculation of `TryAddMessage`, ensuring that the batch can be sent.

### Actual behavior

The total size is inaccurate, resulting in the batch not being sent.

### Reproduction Steps

See above.

### Environment

.NET 7 on Windows 10.

**Comment by JoshLove-msft** [comment] 2023-01-23 19:08
Hi @Stabzs,
I've attempted to set up a repro using the code you provided along with enabling App Insights to ensure that the messages are instrumented. However, I have not been able to reproduce - the batches always send without errors. Are you able to send a complete E2E repro that I can run after specifying my own Service Bus namespace/App Insights instrumentation key? Notably, 7.12.0 does not have any changes related to the sender path as compared to 7.11.1.

**Comment by Stabzs** [comment] 2023-01-24 05:17
I actually struggled initially to reproduce the issue in a standalone example running from Linqpad. However, I was able to create a console application that demonstrates the issue. Interestingly enough, I saw the same issue with 7.11.1 as well as 7.12.0. 

[TestQueueImplementation.zip](https://github.com/Azure/azure-sdk-for-net/files/10486527/TestQueueImplementation.zip)

**Comment by JoshLove-msft** [comment] 2023-01-24 05:44
Still not seeing any issues. I added this line to the main method to enable logging:
```c#
using var logger = AzureEventSourceListener.CreateConsoleLogger();
```

Here is the output:
```
[Informational] Azure-Messaging-ServiceBus: debugtest-9e3bf391-3d50-457b-85b7-6c689ea3a803: CreateBatchAsync start.
[Informational] Azure-Messaging-ServiceBus: Creating send link for Identifier: debugtest-9e3bf391-3d50-457b-85b7-6c689ea3a803.
[Informational] Azure-Messaging-ServiceBus: Send link created for Identifier: debugtest-9e3bf391-3d50-457b-85b7-6c689ea3a803.
[Informational] Azure-Messaging-ServiceBus: debugtest-9e3bf391-3d50-457b-85b7-6c689ea3a803: CreateBatchAsync done.
[Informational] Azure-Messaging-ServiceBus: debugtest-9e3bf391-3d50-457b-85b7-6c689ea3a803: SendAsync start. MessageCount = 232
[Informational] Azure-Messaging-ServiceBus: debugtest-9e3bf391-3d50-457b-85b7-6c689ea3a803: SendAsync done.
[Informational] Azure-Messaging-ServiceBus: debugtest-9e3bf391-3d50-457b-85b7-6c689ea3a803: CreateBatchAsync start.
[Informational] Azure-Messaging-ServiceBus: debugtest-9e3bf391-3d50-457b-85b7-6c689ea3a803: CreateBatchAsync done.
[Informational] Azure-Messaging-ServiceBus: debugtest-9e3bf391-3d50-457b-85b7-6c689ea3a803: SendAsync start. MessageCount = 232
[Informational] Azure-Messaging-ServiceBus: debugtest-9e3bf391-3d50-457b-85b7-6c689ea3a803: SendAsync done.
[Informational] Azure-Messaging-ServiceBus: debugtest-9e3bf391-3d50-457b-85b7-6c689ea3a803: CreateBatchAsync start.
[Informational] Azure-Messaging-ServiceBus: debugtest-9e3bf391-3d50-457b-85b7-6c689ea3a803: CreateBatchAsync done.
[Informational] Azure-Messaging-ServiceBus: debugtest-9e3bf391-3d50-457b-85b7-6c689ea3a803: SendAsync start. MessageCount = 232
[Informational] Azure-Messaging-ServiceBus: debugtest-9e3bf391-3d50-457b-85b7-6c689ea3a803: SendAsync done.
[Informational] Azure-Messaging-ServiceBus: debugtest-9e3bf391-3d50-457b-85b7-6c689ea3a803: CreateBatchAsync start.
[Informational] Azure-Messaging-ServiceBus: debugtest-9e3bf391-3d50-457b-85b7-6c689ea3a803: CreateBatchAsync done.
[Informational] Azure-Messaging-ServiceBus: debugtest-9e3bf391-3d50-457b-85b7-6c689ea3a803: SendAsync start. MessageCount = 232
[Informational] Azure-Messaging-ServiceBus: debugtest-9e3bf391-3d50-457b-85b7-6c689ea3a803: SendAsync done.
[Informational] Azure-Messaging-ServiceBus: debugtest-9e3bf391-3d50-457b-85b7-6c689ea3a803: CreateBatchAsync start.
[Informational] Azure-Messaging-ServiceBus: debugtest-9e3bf391-3d50-457b-85b7-6c689ea3a803: CreateBatchAsync done.
[Informational] Azure-Messaging-ServiceBus: debugtest-9e3bf391-3d50-457b-85b7-6c689ea3a803: SendAsync start. MessageCount = 232
[Informational] Azure-Messaging-ServiceBus: debugtest-9e3bf391-3d50-457b-85b7-6c689ea3a803: SendAsync done.
[Informational] Azure-Messaging-ServiceBus: debugtest-9e3bf391-3d50-457b-85b7-6c689ea3a803: CreateBatchAsync start.
[Informational] Azure-Messaging-ServiceBus: debugtest-9e3bf391-3d50-457b-85b7-6c689ea3a803: CreateBatchAsync done.
[Informational] Azure-Messaging-ServiceBus: debugtest-9e3bf391-3d50-457b-85b7-6c689ea3a803: SendAsync start. MessageCount = 232
[Informational] Azure-Messaging-ServiceBus: debugtest-9e3bf391-3d50-457b-85b7-6c689ea3a803: SendAsync done.
[Informational] Azure-Messaging-ServiceBus: debugtest-9e3bf391-3d50-457b-85b7-6c689ea3a803: CreateBatchAsync start.
[Informational] Azure-Messaging-ServiceBus: debugtest-9e3bf391-3d50-457b-85b7-6c689ea3a803: CreateBatchAsync done.
[Informational] Azure-Messaging-ServiceBus: debugtest-9e3bf391-3d50-457b-85b7-6c689ea3a803: SendAsync start. MessageCount = 232
[Informational] Azure-Messaging-ServiceBus: debugtest-9e3bf391-3d50-457b-85b7-6c689ea3a803: SendAsync done.
[Informational] Azure-Messaging-ServiceBus: debugtest-9e3bf391-3d50-457b-85b7-6c689ea3a803: CreateBatchAsync start.
[Informational] Azure-Messaging-ServiceBus: debugtest-9e3bf391-3d50-457b-85b7-6c689ea3a803: CreateBatchAsync done.
[Informational] Azure-Messaging-ServiceBus: debugtest-9e3bf391-3d50-457b-85b7-6c689ea3a803: SendAsync start. MessageCount = 232
[Informational] Azure-Messaging-ServiceBus: debugtest-9e3bf391-3d50-457b-85b7-6c689ea3a803: SendAsync done.
[Informational] Azure-Messaging-ServiceBus: debugtest-9e3bf391-3d50-457b-85b7-6c689ea3a803: CreateBatchAsync start.
[Informational] Azure-Messaging-ServiceBus: debugtest-9e3bf391-3d50-457b-85b7-6c689ea3a803: CreateBatchAsync done.
[Informational] Azure-Messaging-ServiceBus: debugtest-9e3bf391-3d50-457b-85b7-6c689ea3a803: SendAsync start. MessageCount = 232
[Informational] Azure-Messaging-ServiceBus: debugtest-9e3bf391-3d50-457b-85b7-6c689ea3a803: SendAsync done.
[Informational] Azure-Messaging-ServiceBus: debugtest-9e3bf391-3d50-457b-85b7-6c689ea3a803: CreateBatchAsync start.
[Informational] Azure-Messaging-ServiceBus: debugtest-9e3bf391-3d50-457b-85b7-6c689ea3a803: CreateBatchAsync done.
[Informational] Azure-Messaging-ServiceBus: debugtest-9e3bf391-3d50-457b-85b7-6c689ea3a803: SendAsync start. MessageCount = 162
[Informational] Azure-Messaging-ServiceBus: debugtest-9e3bf391-3d50-457b-85b7-6c689ea3a803: SendAsync done.
```

**Comment by Stabzs** [comment] 2023-01-24 13:56
Have you tried stepping through with a debugger without a logger attached?

**Comment by JoshLove-msft** [comment] 2023-01-24 18:58
Still no luck. If you able to reproduce this, can you please try including SDK logs (as demonstrated above) so we can further investigate what is going on?

**Comment by Stabzs** [comment] 2023-01-25 02:40
Absolutely. Here is what I got from the SDK logging:

```
[Informational] Azure-Messaging-ServiceBus: topic-1ccd7990-f962-433b-9791-975107c55dd6: CreateBatchAsync start.
[Informational] Azure-Messaging-ServiceBus: Creating send link for Identifier: topic-1ccd7990-f962-433b-9791-975107c55dd6.
[Informational] Azure-Messaging-ServiceBus: Send link created for Identifier: topic-1ccd7990-f962-433b-9791-975107c55dd6.
[Informational] Azure-Messaging-ServiceBus: topic-1ccd7990-f962-433b-9791-975107c55dd6: CreateBatchAsync done.
[Informational] Azure-Messaging-ServiceBus: topic-1ccd7990-f962-433b-9791-975107c55dd6: SendAsync start. MessageCount = 232
[Error] Azure-Messaging-ServiceBus: topic-1ccd7990-f962-433b-9791-975107c55dd6: SendAsync Exception: Azure.Messaging.ServiceBus.ServiceBusException: The message (id:23749772, size:263150 bytes) is larger than is currently allowed (262144 bytes). (MessageSizeExceeded). For troubleshooting information, see https://aka.ms/azsdk/net/servicebus/exceptions/troubleshoot.
   at Azure.Messaging.ServiceBus.Amqp.AmqpSender.SendBatchInternalAsync(AmqpMessage batchMessage, TimeSpan timeout, CancellationToken cancellationToken)
   at Azure.Messaging.ServiceBus.Amqp.AmqpSender.SendBatchInternalAsync(AmqpMessage batchMessage, TimeSpan timeout, CancellationToken cancellationToken)
   at Azure.Messaging.ServiceBus.Amqp.AmqpSender.SendBatchInternalAsync(IReadOnlyCollection`1 messages, TimeSpan timeout, CancellationToken cancellationToken)
   at Azure.Messaging.ServiceBus.Amqp.AmqpSender.<>c.<<SendBatchAsync>b__21_0>d.MoveNext()
--- End of stack trace from previous location ---
   at Azure.Messaging.ServiceBus.ServiceBusRetryPolicy.<>c__22`1.<<RunOperation>b__22_0>d.MoveNext()
--- End of stack trace from previous location ---
   at Azure.Messaging.ServiceBus.ServiceBusRetryPolicy.RunOperation[T1,TResult](Func`4 operation, T1 t1, TransportConnectionScope scope, CancellationToken cancellationToken, Boolean logTimeoutRetriesAsVerbose)
   at Azure.Messaging.ServiceBus.ServiceBusRetryPolicy.RunOperation[T1,TResult](Func`4 operation, T1 t1, TransportConnectionScope scope, CancellationToken cancellationToken, Boolean logTimeoutRetriesAsVerbose)
   at Azure.Messaging.ServiceBus.ServiceBusRetryPolicy.RunOperation[T1](Func`4 operation, T1 t1, TransportConnectionScope scope, CancellationToken cancellationToken)
   at Azure.Messaging.ServiceBus.Amqp.AmqpSender.SendBatchAsync(ServiceBusMessageBatch messageBatch, CancellationToken cancellationToken)
   at Azure.Messaging.ServiceBus.ServiceBusSender.SendMessagesAsync(ServiceBusMessageBatch messageBatch, CancellationToken cancellationToken).
```

**Comment by JoshLove-msft** [comment] 2023-01-25 05:14
So whenever I run the app you sent, I get batches of size 232 just like in your logs. But the size for each batch is always 261,758 bytes (as I saw from stepping through the code). I don't really understand how this would be different between our test runs assuming that you are running the exact code that you shared in the TestQueueImplementation.zip. The message size should be deterministic. Can you confirm that you are seeing the above error when running the code that you shared?

**Comment by Stabzs** [comment] 2023-01-25 07:44
Correct, this is from running the exact same code that I zipped up, against a standard SKU Azure Service Bus topic. It only includes the two NuGet packages to minimize any additional dependencies.

**Comment by JoshLove-msft** [comment] 2023-01-26 00:34
At this point, since this doesn't appear to be reproducible on my end, I'd suggest opening a support ticket via the Portal so that we can engage further and potentially bring in the service folks as needed.

**Comment by DavidAtImpactCubed** [comment] 2023-01-26 12:12
Hi @JoshLove-msft, we seem to be hitting a similar issue with TryAddMessage using 7.11.1.  Our code is similar to the above example, but we add application properties to the messages as well:
![image](https://user-images.githubusercontent.com/87976740/214829393-8fdd2d39-a52e-44a0-983a-885f2559ada7.png)

Here's a weird thing:
If we stick a breakpoint on a try / catch, we can inspect both the exception message and the batch object, and they give us different numbers:

Exception: claims the batch is 262145 bytes
![image](https://user-images.githubusercontent.com/87976740/214831990-f2ba5140-ad26-450b-8167-b536a5a80d67.png)

Batch object: claims the batch is 262144 bytes
![image](https://user-images.githubusercontent.com/87976740/214832008-9518eb01-83dc-4fdf-9747-aa211619cc7f.png)

A 1 byte difference that pushes us over the brink. 

I will try to reproduce using the zip file provided by @Stabzs.

**Comment by DavidAtImpactCubed** [comment] 2023-01-26 14:55
I'm not able to reproduce using the zip file attached by @Stabzs. I'm really confused!

I tried to create a variant of Stabzs program, one which adds a message property and also (by trial and error) gets the batch size to equal exactly 262144 bytes. I'm still not able to reproduce. :(

I can't tell what is making the difference between the failing code and this sample. 

[TestQueueImplementation-DF.zip](https://github.com/Azure/azure-sdk-for-net/files/10510454/TestQueueImplementation-DF.zip)

**Comment by DavidAtImpactCubed** [comment] 2023-01-26 14:56
@Stabzs I  would be very interested to know if, when you reproduce this error, the SizeInBytes property of your message batch differs from the size given in the exception message.

**Comment by Stabzs** [comment] 2023-01-26 15:17
@DavidAtImpactCubed this is _exactly_ the same behavior I am seeing. The client batch is under the threshold

![image](https://user-images.githubusercontent.com/11450848/214873552-7989a660-e927-41eb-95cb-1b22c2929ba1.png)

but the server is rejecting the batch:

> The message (id:30189679, size:263150 bytes) is larger than is currently allowed (262144 bytes). (MessageSizeExceeded). For troubleshooting information, see https://aka.ms/azsdk/net/servicebus/exceptions/troubleshoot.

@JoshLove-msft this either seems to be a mismatch between how the SDK and the service bus server are calculating size, or there is a bug in one or the other. Is it possible to escalate the issue internally?

**Comment by JoshLove-msft** [comment] 2023-01-26 18:04
@DavidAtImpactCubed - do you have a repro that you can share?

**Comment by JoshLove-msft** [comment] 2023-01-26 19:53
The size calculation that triggers the exception actually still comes from the client. messageBatch.SizeInBytes is calculated as you add individual messages, but when sending, we  recalculate the size of the batch message that is about to go over the wire. The only time these could be different (outside of a bug) would be if the message body was mutated after adding to the batch.

**Comment by JoshLove-msft** [comment] 2023-01-26 21:15
One thing that would be great to confirm - does the issue repro on versions prior to 7.11.0?

**Comment by Stabzs** [comment] 2023-01-26 22:11
@JoshLove-msft I just downgraded to 7.10.0 and could not reproduce the issue. I then upgraded to 7.11.0 and ran into the issue on the first attempt.

**Comment by DavidAtImpactCubed** [comment] 2023-01-26 23:20
> @DavidAtImpactCubed - do you have a repro that you can share?

I'm struggling to put together a consistently reproducible example, but I think I might have something that might help:

Running the attached code, I put two breakpoints, one in Program.cs, where I check the messageBatch SizeInBytes:
![image](https://user-images.githubusercontent.com/87976740/214971323-85f55b1a-8662-4d5e-81f3-34ec8865b2ec.png)

And one in Azure.Messaging.ServiceBus.Amqp.AmqpSender on line 274, where the AmqpDataMessage size is checked:
![image](https://user-images.githubusercontent.com/87976740/214971461-0de75002-c9de-46cd-bf3e-1d564e768ee8.png)

As you can see, the AmqpDataMessage is a byte bigger for some reason. 

The max message size is the same in both cases: 262144
[TestQueueImplementation-DF2.zip](https://github.com/Azure/azure-sdk-for-net/files/10514198/TestQueueImplementation-DF2.zip)

This seems to be consistently a 1 byte difference, which isn't the same as what @Stabzs was seeing, where the difference was much bigger, but maybe it gives a hint as to where the difference is creeping in? Not sure if this helps, but figured I might as well share...

**Comment by JoshLove-msft** [comment] 2023-01-26 23:34
@DavidAtImpactCubed can you repro in 7.10.0?

**Comment by DavidAtImpactCubed** [comment] 2023-01-26 23:42
Repro the difference in size? I'll have a go. 

In the meantime, I messed around with trying adding different properties of different lengths to try to find an example as close to the max bytes as possible.

I managed to hack things until I have a messageBatch that claims to be right on the threshold:
![image](https://user-images.githubusercontent.com/87976740/214974613-7c6802f1-b85c-4da6-b978-88cdfe6e34f6.png)

But strangely, when the size is calculated as part of SendMessageAsync, it is two bytes smaller!
![image](https://user-images.githubusercontent.com/87976740/214974690-a85166e2-cf4f-43d9-9892-556c979e9673.png)

Wherever the discrepancy is coming in, it isn't consistent, and seems to depend on the content/properties of the messages being sent.

I'll try with 7.10.0 now.

**Comment by JoshLove-msft** [comment] 2023-01-26 23:44
Not necessarily the difference in size (I'm seeing that too where the message batch is two bytes larger than when we send), but the issue where we hit an exception due to the batch being larger than MaxMessageSize.

**Comment by JoshLove-msft** [comment] 2023-01-26 23:51
@DavidAtImpactCubed I updated your post that was sharing the second example as it was not sanitized.

**Comment by DavidAtImpactCubed** [comment] 2023-01-26 23:52
Thanks, it's a test SB instance only and I'll roll the keys just in case.

**Comment by DavidAtImpactCubed** [comment] 2023-01-26 23:54
I'm afraid I can't prove anything about 7.10.0 right now because I can't reproduce anything at the moment, not sure what has changed 😕 

I've run out of time for today, I will take another look tomorrow.

**Comment by JoshLove-msft** [comment] 2023-01-27 06:31
So I was finally able to reproduce this, but only while debugging. It seems that the SerializedMessageSize is changed after looking at the AmqpMessage under the debugger. What seems to be happening is that several properties of AmqpMessage are initialized in their getters, so when looking at the properties in the debugger, the getters are invoked triggering the initialization, and increasing the size of the message - e.g. [ApplicationProperties](https://github.com/Azure/azure-amqp/blob/master/src/AmqpMessage.cs#L184).

I will file an issue in the AMQP repo to consider adding the DebuggerBrowsableAttribute to the properties that are lazily initialized.

Given that this is a side-effect of attaching the debugger, and not a production issue, I will mark this issue as addressed. Thanks for working through this one with me @stabzs and @DavidAtImpactCubed!

**Comment by Stabzs** [comment] 2023-01-27 06:39
@JoshLove-msft I may have been able to isolate behavior that is contributing to the inconsistency in reproducing the issue. In an effort to determine if `messageBatch.SizeInBytes` would diverge from the actual message batch, I tried creating a batch with just two items. 

I noticed that [here](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/servicebus/Azure.Messaging.ServiceBus/src/Amqp/AmqpMessageConverter.cs#L104):

```
var data = new List<Data>(source.Count);

foreach (var message in source)
{
    message.Batchable = true;
    using var messageStream = message.ToStream();
    data.Add(new Data { Value = ReadStreamToArraySegment(messageStream) });
}
batchEnvelope = AmqpMessage.Create(data);
batchEnvelope.MessageFormat = AmqpConstants.AmqpBatchedMessageFormat;
```

when inspecting `batchEnvelop.SerializedMessageSize`, the byte size would seemingly randomly change between two different sizes (1184 and 1217 bytes) even though the data was exactly the same for the message payload every single test run.

When digging into the `.ToStream()` call to `AmqpBufferedMessage`, it calls `this.Initialize()` which in turn gets the encode size based off of local fields. https://github.com/Azure/azure-amqp/blob/facbd01daed6bf9c71c495035326bf4d9d914c94/Microsoft.Azure.Amqp/Amqp/AmqpMessage.cs#L460

```
int encodeSize = this.GetSectionSize(this.header) +
                    this.GetSectionSize(this.deliveryAnnotations) +
                    this.GetSectionSize(this.messageAnnotations) +
                    this.GetSectionSize(this.properties) +
                    this.GetSectionSize(this.applicationProperties) +
                    this.GetBodySize() +
                    this.GetSectionSize(this.footer);
```

It seems that (at least in debug mode), there is an inherent race condition between the population of the private fields via the public properties, and the call to get the encode size, resulting in some of the fields not getting rolled up properly.

I haven't been able to identify yet why this might have only cropped up in 7.11.0, and greater, but it is possible that is also a red herring. While extremely ugly, updating the [following](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/servicebus/Azure.Messaging.ServiceBus/src/Amqp/AmqpMessageConverter.cs#L174) completely fixes the issue for me:

``` CSharp
public virtual AmqpMessage SBMessageToAmqpMessage(ServiceBusMessage sbMessage)
{
    // body
    var amqpMessage = sbMessage.ToAmqpMessage();

    // reference the properties to force the private fields to be set
    var header = amqpMessage.Header;
    var deliveryAnnotations = amqpMessage.DeliveryAnnotations;
    var messageAnnotations = amqpMessage.MessageAnnotations;
    var properties = amqpMessage.Properties;
    var applicationProperties = amqpMessage.ApplicationProperties;
    var footer = amqpMessage.Footer;

    // properties
    amqpMessage.Properties.MessageId = sbMessage.MessageId;
    amqpMessage.Properties.CorrelationId = sbMessage.CorrelationId;
```

**Comment by Stabzs** [comment] 2023-01-27 06:44
@JoshLove-msft ah, I didn't see you had also found the issue while I was typing up the novel :). Thanks for continuing to research this!

Is there absolutely no way that there would be a race condition based on what I detailed above? I'll have to test further under release builds, but it seems that the lazily-initialized properties could still inaccurately report size if accessed at the wrong time in the library, which isn't very reassuring.

**Comment by JoshLove-msft** [comment] 2023-01-27 06:46
Haha yes! We arrived at the same conclusion. I will take another look as there could be some change that was made that causes us to only initialize some of these properties when sending rather than when initially adding to the batch. But have you ever seen the issue without a debugger attached?

**Comment by JoshLove-msft** [comment] 2023-01-27 06:50
> I'll have to test further under release builds, but it seems that the lazily-initialized properties could still inaccurately report size if accessed at the wrong time in the library, which isn't very reassuring.

Good point - the library does provide a means to check if the properties are set without accessing them via the Sections section of AmqpMessage. This does seem like a new issue as of 7.11.0 because previously we didn't use the AmqpMessage properties, but rather the higher level ServiceBusMessage properties which was _not_ backed by the AmqpMessage properties. So we should at least fix that. But still I'm not seeing how that would cause the discrepancy as we checked these properties before building the batch. I'll take another look in the morning.

**Comment by Stabzs** [comment] 2023-01-27 06:51
I just ran the scenario above with the "hack" in and out in release build with the debugger detached. Without the hack, I hit the same issue. With the hack, the batch sends successfully.

I'm definitely curious to hear your analysis, but I believe at first glance that a pre-initialization may be necessary for those fields, if they're needed to send successfully in any way.

**Comment by JoshLove-msft** [comment] 2023-01-27 06:53
Yeah, I have no doubt that there is an issue when the debugger is attached, but pre-initializing isn't what we would want as it leads to larger payloads than necessary. Instead we need to update to use the Sections property. With this fix, you'd still see the weird behavior when using the debugger until we can get the DebuggerBrowsable attribute added in the AMQP library.

**Comment by Stabzs** [comment] 2023-01-27 07:03
Absolutely. That was only to easily demonstrate the cause. Appropriate message sizes sounds ideal :)

**Comment by JoshLove-msft** [comment] 2023-01-27 07:05
Yep, unfortunately the debugger issue will persist with this approach though. Have you ever hit this issue without a debugger attached?

**Comment by DavidAtImpactCubed** [comment] 2023-01-27 08:02
> I just ran the scenario above with the "hack" both in and out, in release build, with the debugger detached. Without the hack, I hit the same issue. With the hack, the batch sends successfully.
> 
> I'm definitely curious to hear your analysis, but I believe at first glance that a pre-initialization may be necessary for those fields, if they're needed to send successfully in any way.

Here mentions running in a release build and hitting the  (an?) error.

**Comment by Stabzs** [comment] 2023-01-27 14:49
> > I just ran the scenario above with the "hack" both in and out, in release build, with the debugger detached. Without the hack, I hit the same issue. With the hack, the batch sends successfully.
> > I'm definitely curious to hear your analysis, but I believe at first glance that a pre-initialization may be necessary for those fields, if they're needed to send successfully in any way.
> 
> Here mentions running in a release build and hitting the (an?) error.

There were a lot of messages last night and I'm sure it was just missed.

To confirm, I just ran another test in Release with no debugger attached, with the Azure.Messaging.ServiceBus project included, and I consistently reproduced the issue.

However, after removing the project and using the nuget package, I could no longer reproduce the issue, so it is quite possible that I am building the sdk source incorrectly or I accidentally left a modification in somewhere.

Since the test finally passes in release build, it seems like it is most likely a debug-only issue. I'll continue to do some testing today.

**Comment by JoshLove-msft** [comment] 2023-01-27 23:56
Thanks for the update. I looked through the code again and although there is a potential issue involving inflating the message size due to the initialization of empty sections, I don't see anything that could cause the batch to fail sending. Since this is a debug-only issue related to side-effects caused by the debugger, I will close it out.

**Closed by JoshLove-msft** 2023-01-27 23:56 UTC
Labels: Service Bus, Client, customer-reported, question, issue-addressed
