### ISSUE TITLE
[BUG] Tags property on ResourceGroup is read only

### ISSUE THREAD

**Issue by KalyanChanumolu-MSFT** [Azure/azure-sdk-for-net#15791] opened 2020-10-08 16:33 UTC
**Describe the bug**
Unable to create a ResourceGroup with code provided in the [documentation](https://github.com/Azure/azure-sdk-for-net/blob/master/doc/mgmt_preview_quickstart.md#example-managing-resource-groups)

![image](https://user-images.githubusercontent.com/8835012/95484895-a7da6780-09ae-11eb-8a19-232c19320756.png)

I am getting an error
Property or indexer 'ResourceGroup.Tags' cannot be assigned to -- it is read only

**Expected behavior**
Tags property should not be readonly

**Actual behavior (include Exception or Stack Trace)**

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0200	Property or indexer 'ResourceGroup.Tags' cannot be assigned to -- it is read only	ManageResourceGroup	

**To Reproduce**
Steps to reproduce the behavior (include a code snippet, screenshot, or any additional information that might help us reproduce the issue)

1. Use the code on the [documentation](https://github.com/Azure/azure-sdk-for-net/blob/master/doc/mgmt_preview_quickstart.md#example-managing-resource-groups) page for creating a resource group
OR
2. Use the code sample [here](https://github.com/Azure-Samples/azure-samples-net-management/tree/master/samples/resources/manage-resource-group)

**Environment:**
 - Name and version of the Library package used: 

Azure.ResourceManager.Resources 1.0.0-preview.2

 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects):
.NET SDK (reflecting any global.json):
 Version:   5.0.100-rc.1.20452.10
 Commit:    473d1b592e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.20226
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.100-rc.1.20452.10\

Host (useful for support):
  Version: 5.0.0-rc.1.20451.14
  Commit:  38017c3935

.NET SDKs installed:
  5.0.100-rc.1.20452.10 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0-rc.1.20451.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-rc.1.20451.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0-rc.1.20452.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

 - IDE and version : [e.g. Visual Studio 16.3]

**Comment by jsquire** [comment] 2020-10-08 19:43
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by allenjzhang** [comment] 2020-10-08 23:46
This is by design. SDK team has decided to make collections readonly to reduce many of the null reference exceptions we have been seeing. The change is/will be in all management and data plane SDKs.

**Closed by allenjzhang** 2020-10-08 23:46 UTC
Labels: ARM, Mgmt, needs-team-triage

**Comment by josefehse** [comment] 2020-10-26 18:18
What is/will be the right way to set new/update tags then? The sample code provided doesn't work as of now.
Thank you

JF

**Comment by KalyanChanumolu-MSFT** [comment] 2020-11-06 09:00
You need to add items to the collection one by one.
This is pseudo code but you can optimize as per your requirement.

```cs
public async Task TagResourceGroupAsync(string resourceGroupName, IDictionary<string, string> tags)
        {
            try
            {
                _resourceGroupsOperationsClient = GetAuthenticatedResourceGroupOperationsClient();
                var resourceGroup = await _resourceGroupsOperationsClient.GetAsync(resourceGroupName);

                var resourceGroupParameters = new ResourceGroup(resourceGroup.Value.Location);

                foreach (var tag in tags)
                {
                    resourceGroupParameters.Tags.Add(tag);
                }

                await _resourceGroupsOperationsClient.CreateOrUpdateAsync(resourceGroupName, resourceGroupParameters);
            }
            catch (Exception ex)
            {
                Console.WriteLine($"TagResourceGroupAsync failed while adding tags to ResourceGroup: {resourceGroupName} with Exception -  {ex.Message}");
                //throw new Exception($"TagResourceGroupAsync failed while adding tags to resource: {resourceId} with Exception -  {ex.Message}", ex);
            }
        }

```
