### ISSUE TITLE
[QUERY] Clarification with Document Intelligence Capabilities for Documents Types

### ISSUE THREAD

**Issue by dccrain** [Azure/azure-sdk-for-net#46650] opened 2024-10-16 00:15 UTC
### Library name and version

Azure.AI.DocumentIntelligence 1.0.0-beta.3

### Query/Question

Hello, I am trying to understand the limits of the SDK for Documents Intelligence resource. 
According to the [documentation](https://learn.microsoft.com/en-us/azure/ai-services/document-intelligence/concept-read?view=doc-intel-4.0.0&tabs=sample-code#input-requirements), the Read and Layout Models should support processing PDFs, Image, Microsoft Office docs (docx, xlsx, pptx), and HTML. I am able to upload these kinds of files to the Documents Intelligence Studio and analyze them using the Read and Layout models.

However, uploading documents for analysis through the following code snippet using the SDK package
![Image](https://github.com/user-attachments/assets/ca8accd0-65c9-4541-b40f-2febed649f43)

I get the following error when handling Microsoft Office document formats. I have success when handling PDF documents.

```
Error processing file: Invalid request.
Status: 400 (Bad Request)
ErrorCode: InvalidRequest

Content:
{"error":{"code":"InvalidRequest","message":"Invalid request.","innererror":{"code":"InvalidContent","message":"The file is corrupted or format is unsupported. Refer to documentation for the list of supported formats."}}}
```
I am seeking some clarification on the usage, and whether or not the way I am trying to handle the documents is correct. 
Thanks

**Comment by jsquire** [comment] 2024-10-16 17:35
Hi @dccrain.   Thanks for reaching out and we regret that you're experiencing difficulties.   The v1.0.0-beta.3 package supports version `2024-07-31-preview` of the Document Intelligence service with full support any features and functionality that service version provides.  _(see: [DocumentIntelligenceClientOptions+Service](https://learn.microsoft.com/dotnet/api/azure.ai.documentintelligence.documentintelligenceclientoptions.serviceversion?view=azure-dotnet-preview))_  

The maintainers of the Azure SDK have no insight nor influence for Document Intelligence Studio, and we cannot speak to what service version it may be using. The error that your seeing was generated by the service, and the client has no insight into the cause.  It may be that Document Intelligence Studio is using a newer service version or there may be another cause.   Unfortunately, this is something that we'll need insight from the Document Intelligence service team to understand.  They do not monitor issues in the Azure SDK repository and have a different support path that we're unable to transfer to on your behalf.

To ensure that the right team has visibility and can help, your best path forward for would be to [open an Azure support request](https://docs.microsoft.com/azure/azure-portal/supportability/how-to-create-azure-support-request) or inquire on the [Microsoft Q&A site](https://learn.microsoft.com/answers/questions/).   

I'm going to close this out; if I've misunderstood what you're describing, please let us know in a comment and we'd be happy to assist as we're able.

**Closed by jsquire** 2024-10-16 17:35 UTC
Labels: Client, customer-reported, question, Cognitive - Form Recognizer
