### ISSUE TITLE
Can we expose ProcessMessageEventArgs's Receiver a readonly property?

### ISSUE THREAD

**Issue by sgarshol** [Azure/azure-sdk-for-net#18109] opened 2021-01-21 13:24 UTC
Regarding Azure.Messaging.ServiceBus, ProcessMessageEventArgs

You can call the `CompleteMessageAsync` method on the `ProcessMessageEventArgs` class as described here:

https://docs.microsoft.com/en-us/dotnet/api/azure.messaging.servicebus.processmessageeventargs.completemessageasync?view=azure-dotnet

The caveat: "This operation can only be performed on a message that was received by this receiver when `ReceiveMode` is set to `PeekLock`."

So you if you aren't always sure to use a specific `ReceiveMode` you should take care to check on that condition before calling the `CompleteMessageAsync()` method.

```
if (isReceiverModePeekLock)
{
    await args.CompleteMessageAsync(args.Message);
}
```

This is a bit awkward: In the context of processing a message using the `ServiceBusProcessor`'s `ProcessMessageAsync`event, you have access to the `ProcessMessageEventArgs` argument. This contains a object reference to the `ServiceBusReceiver` as a private member, which in turn has a public property `ReceiverMode`  that can tell us if the we are using `PeekLock` or not.

I feel it would be convenient to be able to do this:

```
var isReceiverModePeekLock = args.Receiver.ReceiverMode == ServiceBusReceiveMode.PeekLock
```

Would it be possible to get access to the `_receiver` member as a public readonly property?

Regards
Sigurd Garshol

**Comment by jsquire** [comment] 2021-01-21 16:47
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by JoshLove-msft** [comment] 2021-01-22 02:37
Hi @sgarshol, thanks for submitting the issue. Would you be able to use the ReceiveMode property that is on the processor? All receivers used by a processor would have the same ReceiveMode.

**Comment by sgarshol** [comment] 2021-01-22 11:42
@JoshLove-msft I indeed have a work-around where I reference the `ServiceBusProcessor` instance, and that solves the immediate issue.

I have a worry that the developers that are going to use this project may end up referencing the wrong instance and get things messed up, but that is pretty minor - they can just not do that and things will work fine! :)

It is just irksome that the Receiver is lying there, within the event argument, so close but still out of reach!

**Comment by JoshLove-msft** [comment] 2021-01-22 20:38
> @JoshLove-msft I indeed have a work-around where I reference the `ServiceBusProcessor` instance, and that solves the immediate issue.
> 
> I have a worry that the developers that are going to use this project may end up referencing the wrong instance and get things messed up, but that is pretty minor - they can just not do that and things will work fine! :)
> 
> It is just irksome that the Receiver is lying there, within the event argument, so close but still out of reach!

Well this is actually by design, as we didn't want to expose all operations from the receiver within the callback and wanted to present a simple interface that exposed the operations that make sense within the context of the user event handler.

**Comment by sgarshol** [comment] 2021-01-23 16:57
You make a good point, and I agree that keeping  the receiver object wrapped away makes sense in this context, the handling of the received messages.  However, with my workaround I am nevertheless using the Processor object. This amounts to the same thing, just with extra steps.

But I don't really need to or want to deal with the Receiver or Processor at this point - I certainly do not want to make changes to them. I want to be able to determine if it is appropriate and safe to call the methods to complete, defer, abandon or "kill" the message (move it to the dead letter list), and the information I need to make that determination is currently not available on the eventArgs object.

Would it be possible to add operations on the event args object that evaluates if the message and receiver is in a state that allows us to call `CompleteMessageAsync` et.al.? E.g. `CanCompleteMessage(Message)`?  

Would it be possible to add to the eventArgs object the options settings that were applied when initializing the Receiver or Processor, e.g. `AutoComplete` and `ReceiveMode`, etc., as readonly properties?

- methods that evaluate the message and Receiver can be Completed etc., e.g. `CanCompleteMessage(Message)`
- the options used to initiate the receiver as readonly properies on the , e.g. `ReceiveMode` and `AutoComplete`

-S

**Comment by JoshLove-msft** [comment] 2021-01-25 23:12
The part that I'm not fully understanding is why it would be cumbersome to get access to the processor when constructing your event handler. In order to set the event handler, you need access to the processor. So I imagine that you could have something like:
```cs
processor.ProcessMessageAsync += async args =>
{
    if (processor.ReceiveMode == ServiceBusReceiveMode.PeekLock)
   {
    ...
   }
}
```

**Comment by JoshLove-msft** [comment] 2021-05-07 05:00
Hi @sgarshol I'm going to close this issue. Please feel free to reopen if you would like to discuss this further.

**Closed by JoshLove-msft** 2021-05-07 05:00 UTC
Labels: Client, Service Bus, customer-reported, needs-team-attention, question
