### ISSUE TITLE
Search SDK: [SerializePropertyNamesAsCamelCase] not converting property names to camel case while indexing documents.

### ISSUE THREAD

**Issue by abishekreddy** [Azure/azure-sdk-for-net#4087] opened 2018-02-22 06:37 UTC
Hi,

While indexing an upload batch using the `SearchIndexClient`, I am getting the following exception:
```The request is invalid. Details: parameters : The property '**Keywords**' does not exist on type 'search.documentFields'. Make sure to only use property names that are defined by the type.```

The problem is that its looking for "**K**eywords" when it should be looking for "**k**eywords". 

Note: 
1) The class that was used to define the index (using `FieldBuilder`) is being used to create the documents. This class has the `[SerializePropertyNamesAsCamelCase]` attribute.
2) I was able to create the index successfully. The index fields are in camel case (Checked it on the Azure portal).
3) I was able to index the documents by manually changing the class properties names of the class to  camel case and running the code again after the index was created.
4) I'm using version "3.0.5" of the Microsoft.Azure.Search nuget.

Is this a known bug or am I missing something?

Thanks.

**Comment by brjohnstmsft** [comment] 2018-02-22 20:44
@abishekreddy Thanks for reporting this; we'll investigate. In the meantime, would it be possible for you to share a minimal repro of the issue?

**Comment by brjohnstmsft** [comment] 2018-02-23 01:16
@abishekreddy It might also be relevant to know what version of `Newtonsoft.Json` your application is using.

**Comment by brjohnstmsft** [comment] 2018-02-27 23:13
@abishekreddy I'm unable to reproduce this issue. Can you please let me know what version of `Newtonsoft.Json` you're using, or even better, provide a minimal amount of code to demonstrate the issue?

**Comment by brjohnstmsft** [comment] 2018-03-06 22:20
@abishekreddy Since I can't reproduce this and I haven't heard from you in over a week, I'm closing this issue.

**Comment by abishekreddy** [comment] 2018-03-07 11:16
**Code Snippet:**
```
public abstract class AzureSearchDocument
{
	[Key]
        [IsFilterable]
        public string Id { get; set; }
}

[SerializePropertyNamesAsCamelCase]
public class Article: AzureSearchDocument
{
        [IsSearchable, IsFilterable]
        public string[] Keywords { get; set; }
}

var definition = new Index()
{
	Name = indexName,
        Fields = FieldBuilder.BuildForType<Article>()
};
var serviceClient = new SearchServiceClient(serviceName, new SearchCredentials(adminApiKey));
await serviceClient.Indexes.CreateAsync(definition).ConfigureAwait(false);

var documents = new List<Article>();
foreach(var article in articles){
	var document = new Article();
	document.Id = article.Id;
	document.Keywords = article.Keyworkds;
	documents.Add(document);
}
var batch = IndexBatch.Upload(documents);
var indexClient = new SearchIndexClient(serviceName, indexName, new SearchCredentials(queryApiKey));
indexClient.Documents.Index(batch);
```
**Newtonsoft nuget version:** 10.0.3

**Comment by brjohnstmsft** [comment] 2018-03-07 22:18
Thanks @abishekreddy. Re-opening the issue.

**Comment by abishekreddy** [comment] 2018-03-10 12:40
The issue was that the [SerializePropertyNamesAsCamelCase] attribute wasn't on the AzureSearchDocument class whereas the method that had the batch index and upload calls was expecting an IEnumerable<AzureSearchDocument>.

**Comment by brjohnstmsft** [comment] 2018-03-12 15:39
@abishekreddy Ah, that makes sense. Thanks for following up. Closing this issue.

**Closed by brjohnstmsft** 2018-03-12 15:39 UTC
Labels: Search
