### ISSUE TITLE
[BUG] Cannot filter on Timestamp using Azure.Data.Tables

### ISSUE THREAD

**Issue by DanClifford00** [Azure/azure-sdk-for-net#40549] opened 2023-12-04 17:15 UTC
### Library name and version

Azure.Data.Tables

### Describe the bug

The Azure.Data.Tables package seems to block the ability to filter my queries using the Timestamp property. I am migrating from Microsoft.Azure.Cosmos.Table to Azure.Data.Tables, I need to query my Cosmos DB using the Timestamp in the following way...

_tableClient.Query<Entity>(TableClient.CreateQueryFilter<Entity>(e => e.Timestamp >= datetimeValue));

However after implementing the Azure.Data.Tables package, I no longer get any results back. I have read this is a known issue and it looks like its been closed for some reason, but its still not resolved [https://github.com/Azure/azure-sdk-for-net/issues/32468](url). Are there any updates on a fix for this? Thanks.

### Expected behavior

My query should be filtered by the Timestamp property and return results from my Cosmos DB which match the condition above.

### Actual behavior

An empty collection is returned. No exception is thrown. 

There are elements that should satisfy the query and by using the deprecated Cosmos package or Azure Portal I am able to retrieve these expected results back.

### Reproduction Steps

var dateFilter = TableClient.CreateQueryFilter<Entity>(e => e.Timestamp >= date);
Console.WriteLine(_tableClient.Query<Entity>(dateFilter).Count());

### Environment

Microsoft.NET.Sdk.Web 
net8.0
Console App

**Comment by christothes** [comment] 2023-12-04 17:47
Hi @DanClifford00 
This is a known limitation of the Cosmos backend for Tables and is documented [here](https://learn.microsoft.com/azure/cosmos-db/table/tutorial-query#query-by-using-an-odata-filter). The service team is aware of it, but I don't think there are any plans to change this behavior currently. 

( duplicate of #32468)

**Closed** 2023-12-04 21:10 UTC
Labels: Client, customer-reported, question, Tables, issue-addressed

**Comment by DanClifford00** [comment] 2023-12-04 21:11
@christothes Thanks for the reply. Hopefully it will be something that is resolved in the near future as its not feasible using the workaround in my situation.
