### ISSUE TITLE
[QUERY] How do I create a role assignment using Azure.ResourceManager?

### ISSUE THREAD

**Issue by andrei-faber** [Azure/azure-sdk-for-net#26110] opened 2021-12-28 23:02 UTC
### Library name and version

Azure.ResourceManager 1.0.0-beta.7

### Query/Question

How do I create a role assignment using Azure.ResourceManager? There are some samples for this functionality, but they all use the Microsoft.Azure.Management package which is supposed to be phased out. Any way to do this using the new package?

**Comment by jsquire** [comment] 2021-12-29 09:48
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by archerzz** [comment] 2022-01-17 07:51
@andrei-faber We don't have any sample yet. For now you can refer to the scenario test for details:

- Policy Definition: https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/resourcemanager/Azure.ResourceManager/tests/Scenario/PolicyDefinitionCollectionTests.cs
- Policy Assignment: https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/resourcemanager/Azure.ResourceManager/tests/Scenario/PolicyAssignmentCollectionTests.cs

**Comment by kszicsillag** [comment] 2022-03-08 12:29
@archerzz looks like the tests you linked are about [policy definitions](https://docs.microsoft.com/en-us/azure/governance/policy/concepts/definition-structure), but the OP asked about [RBAC role assignments](https://docs.microsoft.com/en-us/azure/role-based-access-control/overview#role-assignments).
Is there any successor to the [Microsoft.Azure.Management.Authorization library](https://www.nuget.org/packages/Microsoft.Azure.Management.Authorization/)?

**Comment by archerzz** [comment] 2022-03-11 11:26
Thanks @kszicsillag for kind reminding.

@andrei-faber `Azure.ResourceManager.Authorization` (a replacement of `Microsoft.Azure.Management.Authorization`) is not published yet. I think it will take some time. So I recommended to use `Microsoft.Azure.Management.Authorization` for now.

**Comment by ealsur** [comment] 2022-04-12 23:26
@archerzz
Is there any ETA on the release? `Azure.ResourceManager` has now been released out of beta but there is no Authorization module? There are Authorization modules for Java, JS, Python, even Go, but no C#?

Is the team really expecting users to maintain multiple clients (`Azure.ResourceManager.ArmClient` and `AuthorizationManagementClient`)?

**Comment by archerzz** [comment] 2022-04-24 03:57
@ealsur We're rolling out the track2 SDKs gradually. I cannot gaurantee the target date for `Azure.ResourceManager.Authorization`, but I can confirm that it's on the list.

**Comment by chinarosesz** [comment] 2022-05-04 21:15
I'm also waiting for the Authorization package from Azure.ResourceManager and not having to maintain both clients in the same codebase.

**Comment by ealsur** [comment] 2022-07-25 18:58
The new Azure.ResourceManager.Authorization nuget is released. With it, you can do RBAC like so:

Assuming you have an `ArmResource` you want to do RBAC to:

```
ArmResource theResource = ...;
string roleId = "the role id you want to add";
string principalId = "....";
RoleAssignmentProperties roleAssignmentProperties = new RoleAssignmentProperties(
                    roleDefinitionId: string.Concat("/subscriptions/", theResource.Id.SubscriptionId, "/providers/Microsoft.Authorization/roleDefinitions/", roleId),
                    principalId: principalId);

await armResource.GetRoleAssignments().CreateOrUpdateAsync(
                        WaitUntil.Completed,
                        "some assignment Id",
                        new RoleAssignmentCreateOrUpdateContent(roleAssignmentProperties));
```

**Comment by archerzz** [comment] 2022-08-01 01:55
Thanks @ealsur 

@andrei-faber FYI

I'm closing this issue. Feel free to open new issue if there is any further question. Thanks.

**Closed by archerzz** 2022-08-01 01:55 UTC
Labels: ARM, Mgmt, customer-reported, question, Docs, needs-team-attention
