### ISSUE TITLE
[FEATURE REQ]Azure.Identity should handle token caching and refreshing when calling .GetTokenAsync just like AppAuthentication does

### ISSUE THREAD

**Issue by felinepc** [Azure/azure-sdk-for-net#20011] opened 2021-03-31 23:21 UTC
I was reading [this documentation](https://docs.microsoft.com/en-us/dotnet/api/overview/azure/app-auth-migration) and getting ready to migrate from `AppAuthentication` to `Azure.Identity`.

While the new library surely works amazingly well with the new Azure client SDKs, I soon found out that the method to directly obtain access token, `TokenCredential.GetTokenAsync`, has the following warning:

```
// This method is called automatically by Azure SDK client libraries. You may call
// this method directly, but you must also handle token caching and token refreshing.
```
There are plenty of use cases where a managed identity access token needs to be explicitly retrieved. For example, using Entity Framework Core with either Azure SQL or Azure PostgreSQL with managed identity requires that the actual tokens to be passed to the EF provider. Same with authenticating against a custom Azure AD enterprise application via standard `HttpClient`. 

These scenarios are unlikely to get native integration with `Azure.Identity` anytime soon.

The older library's `AzureServiceTokenProvider.GetAccessTokenAsync` has built-in token caching and refreshing which works fairly well. It would be great if `Azure.Identity` can implement the same. Only then it will become a viable full replacement for `AppAuthentication`.

In the meantime, I believe this difference should be noted in the migration documentation under the "Access token retrieval" section.

**Comment by Mohit-Chakraborty** [comment] 2021-04-01 04:44
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by leidegre** [comment] 2021-04-08 13:34
Uhm. There's caching but it's slow. It adds 10 milliseconds. That's a lot when you target is sub 100 milliseconds per request.

![image](https://user-images.githubusercontent.com/63085/114035097-15dcea00-987f-11eb-81de-4842661d0c86.png)

I wrote this simple in-memory cache which takes less than 10 microseconds as long as the token is valid.

The problem though is that the token I get back has a validity that I have no control over.

So if the token `ExpiresOn`  goes outside of the tolerance there's no guarantee that I'll get a fresh token back now. More precisely. I cannot ensure that I get a token that has at least 15 minutes of validity at the moment of request.

I currently have two issues:

- The cache is crazy slow, it adds 10 milliseconds for each request.
- I cannot stipulate a minimum access token validity period when I ask for the token.

```cs
class TokenRequestContextEqualityComparer : IEqualityComparer<TokenRequestContext>
{
    static readonly string[] Empty = new string[] { };

    public bool Equals(TokenRequestContext x, TokenRequestContext y)
    {
        var a = x.Scopes ?? Empty;
        var b = y.Scopes ?? Empty;

        if (a.Length != b.Length)
        {
            return false;
        }
        for (int i = 0; i < a.Length; i++)
        {
            if (a[i] != b[i])
            {
                return false;
            }
        }
        return true;
    }

    public int GetHashCode(TokenRequestContext obj)
    {
        var scopes = obj.Scopes ?? Empty;

        int hashCode = 0;
        for (int i = 0; i < scopes.Length; i++)
        {
            hashCode ^= scopes[i].GetHashCode();
        }
        return hashCode;
    }
}

class CachedAzureCredential : DefaultAzureCredential
{
    private readonly ConcurrentDictionary<TokenRequestContext, AccessToken> _cache = new ConcurrentDictionary<TokenRequestContext, AccessToken>(new TokenRequestContextEqualityComparer());

    public override AccessToken GetToken(TokenRequestContext requestContext, CancellationToken cancellationToken = default)
    {
        AccessToken cached;
        if (_cache.TryGetValue(requestContext, out cached) && DateTimeOffset.UtcNow.AddMinutes(15) < cached.ExpiresOn)
        {
            return cached;
        }
        var accessToken = base.GetToken(requestContext, cancellationToken);
        _cache[requestContext] = accessToken;
        return accessToken;
    }

    public override async ValueTask<AccessToken> GetTokenAsync(TokenRequestContext requestContext, CancellationToken cancellationToken = default)
    {
        AccessToken cached;
        if (_cache.TryGetValue(requestContext, out cached) && DateTimeOffset.UtcNow.AddMinutes(15) < cached.ExpiresOn)
        {
            return cached;
        }
        var accessToken = await base.GetTokenAsync(requestContext, cancellationToken);
        _cache[requestContext] = accessToken;
        return accessToken;
    }
}
```

**Comment by felinepc** [comment] 2021-04-08 15:56
@leidegre For EF, `DbContext` is not the only way to inject the token. It can be done via `DbConnectionInterceptor`. See [this ](https://github.com/dotnet/efcore/issues/21043) (this example actually uses `Azure.Identity`) and [this](https://stackoverflow.com/questions/54187241/ef-core-connection-to-azure-sql-with-managed-identity) (this example in romar's answer uses `AppAuthentication`).

My issue is with the fact that the old `AppAuthentication` package takes care of refreshing and caching internally on the `GetAccessTokenAsync`  call so that anytime we use it, we are guaranteed to get a fresh token without worrying about any caching/refreshing logic.  It'd be nice if we can simply have the exact implementation with `Azure.Identity`.

**Comment by leidegre** [comment] 2021-04-08 16:23
I'm currently not on .NET Core, is there anything similar to the `DbConnectionInterceptor` in EF6?

I don't use refresh tokens but the code I've provided will help with the token acquisition.

**Comment by felinepc** [comment] 2021-04-08 16:37
@leidegre Sorry I started with EF Core and never used EF6, but it does appear to have `IDbConnectionInterceptor`?  See [this](https://docs.microsoft.com/en-us/dotnet/api/system.data.entity.infrastructure.interception.idbconnectioninterceptor?view=entity-framework-6.2.0) and [this](https://stackoverflow.com/questions/59933773/with-ef6-how-do-i-globally-set-connection-properties-such-as-transaction-isolat).

Yeah I know a simple in-memory cache and refresh logic wouldn't take more than a few lines of code, but I just felt that the new package should have this built-in because the old one had it, and I generally trust MS's internal implementation on this sort of things more than my own.

**Comment by felinepc** [comment] 2021-10-03 23:04
Dear awesome Microsoft engineers, by any chance we can give this a higher priority? I just did a search for "cache" on this repo and saw a long list of requests asking more or less the same thing:
<img width="742" alt="cache_request" src="https://user-images.githubusercontent.com/58534088/135773969-eba4464e-6a8b-4841-bff6-596ae45aba2d.png">

Identity is a huge issue and we do NOT want to stick to the old library. `Azure.Identity` is not going to create libraries anytime soon for things like Azure SQL/Azure PostgreSQL/Azure App Service Microsoft Authentication, so we need to access this access token for the time being.

The old `Azure.Services.AppAuthentication` package works very reliably for this and has all the beautiful Microsoft-written caching logic built in. But as we're coming closer and closer to the Microsoft Identity Platform 1.0 EOL deadline, we'd really love to move to `Azure.Identity`, as Microsoft strongly suggested themselves. But we really do need this key feature implemented.

**Comment by christothes** [comment] 2021-11-17 15:59
duplicate of #25361

**Closed by christothes** 2021-11-17 15:59 UTC
Labels: Client, Azure.Identity, customer-reported, feature-request
