### ISSUE TITLE
[FEATURE REQ] Add support for extracting multiple configuration keys for a single secret

### ISSUE THREAD

**Issue by pwiens** [Azure/azure-sdk-for-net#16577] opened 2020-11-04 18:34 UTC
**Library or service name.**
What library or service is this request related to?
Azure.Extensions.AspNetCore.Configuration.Secrets
 
**Is your feature request related to a problem? Please describe.**
What feature would you like to get added? What problem is it solving?
We have a legacy code base that has configuration files that look like so:
```
{
  "service-one" : {
       "baseUrl": "https://contoso.com/api1"
       "clientId": "some-id",
       "clientSecret" : "AKeyVaultSecretName"
  },
  "service-two" : {
       "baseUrl": "https://contoso.com/api2"
       "clientId": "some-id",
       "clientSecret" : "AKeyVaultSecretName"
  }
}
```

Currently we have custom configuration loader and we are trying to move to aspnet core with minimal changes to our infrastructure provisioning code. It would be convenient to have `KeyVaultSecretManager` support GetKeys in addition to GetKey. I have working implementation that I hope we can get merged.

**Comment by jsquire** [comment] 2020-11-04 21:21
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by pakrym** [comment] 2021-03-13 00:09
Duplicate of https://github.com/Azure/azure-sdk-for-net/issues/11943

**Closed by pakrym** 2021-03-13 00:09 UTC
Labels: Client, Extensions, customer-reported, needs-team-attention, no-recent-activity, question
