### ISSUE TITLE
[BUG] Resource provider 'Microsoft.Compute' failed to return collection response for type 'virtualMachines'

### ISSUE THREAD

**Issue by ppanchal-mobiz** [Azure/azure-sdk-for-net#38625] opened 2023-09-12 13:47 UTC
### Library name and version

Azure.ResourceManager.Compute 1.1.0

### Describe the bug

Facing the error `Resource provider 'Microsoft.Compute' failed to return collection response for type 'virtualMachines'` while using `SubscriptionResource.GetVirtualMachines()` to get a list of VMs in the subscription. Complete error is given below:
```
Resource provider 'Microsoft.Compute' failed to return collection response for type 'virtualMachines'.
Status: 502 (Bad Gateway)
ErrorCode: ProviderError

Content:
{"error":{"code":"ProviderError","message":"Resource provider 'Microsoft.Compute' failed to return collection response for type 'virtualMachines'."}}

Headers:
Cache-Control: no-cache
Pragma: no-cache
x-ms-failure-cause: REDACTED
x-ms-request-id: 52b33d75-94fb-429a-b166-ea4b005534da
x-ms-correlation-request-id: REDACTED
x-ms-routing-request-id: REDACTED
Strict-Transport-Security: REDACTED
X-Content-Type-Options: REDACTED
Date: Tue, 12 Sep 2023 12:36:00 GMT
Connection: close
Content-Type: application/json; charset=utf-8
Expires: -1
Content-Length: 149
```

### Expected behavior

Get a list of VMs in the subscription

### Actual behavior

Fails to get the list of VMs and errors out with message `Resource provider 'Microsoft.Compute' failed to return collection response for type 'virtualMachines'.`

### Reproduction Steps

```
ArmClient armClient = new ArmClient
(
	new DefaultAzureCredential
	(
		new DefaultAzureCredentialOptions { ManagedIdentityClientId = azureClientId }
	)
);
IEnumerable<SubscriptionResource> subscriptions = armClient.GetSubscriptions().ToList();
foreach (SubscriptionResource subscription in subscriptions)
{
	IEnumerable<VirtualMachineResource> virtualMachineResources = subscription.GetVirtualMachines()
		.Where(vm => vm.Data.Tags.ContainsKey("<some tag here>"));

	foreach (VirtualMachineResource virtualMachineResource in virtualMachineResources)
	{
		...
		...
	}
}
```

### Environment

Hosting platform: Azure Function
OS: Windows
Runtime version: 4.25.2.21138

**Comment by ppanchal-mobiz** [comment] 2023-09-12 22:13
Further investigation revealed that the issue is only with one subscription. The `Get-AzVM` command is also failing for this subscription.
![image](https://github.com/Azure/azure-sdk-for-net/assets/104440431/46b786eb-43c1-4b37-b023-205dce521e7b)

**Comment by aravindhghosh** [comment] 2023-09-13 06:57
We facing the same issue.

**Comment by techiexie** [comment] 2023-09-13 08:52
I have the same issue on some India subscription

**Comment by enuguris** [comment] 2023-09-13 10:33
I am also facing the issue

**Comment by IcarusSPF40** [comment] 2023-09-13 16:31
Same issue here as well. 

What's curious is that some of the resource groups in our subscription work just fine, i.e., 
Running "Get-AzVm -ResourceGroupName 'group 1' " works just fine while 
Running "Get-AzVm -ResourceGroupName 'group 2' " returns:
  Get-AzVM: Resource provider 'Microsoft.Compute' failed to return collection response for type 'virtualMachines'.
  ErrorCode: ProviderError
  ErrorMessage: Resource provider 'Microsoft.Compute' failed to return collection response for type 'virtualMachines'.
  ErrorTarget: 
  StatusCode: 502
  ReasonPhrase: Bad Gateway
  OperationID : 5d7c2945-98da-4e31-9169-0e603b50678a

**Comment by enuguris** [comment] 2023-09-13 17:11
https://github.com/Azure/azure-sdk-for-net/issues/38665

**Comment by San1500** [comment] 2023-09-14 08:01
we also facing the same issue. Unable to perform any operations.

**Comment by NISAR5535** [comment] 2023-09-14 08:13
Facing the same issue . can we know the ETA

**Comment by ppanchal-mobiz** [comment] 2023-09-14 12:53
Our issue was resolved by **re-registering** the Microsoft.Compute resource provider for the concerned subscription. I am not sure though why it did not work earlier as Microsoft.Compute was already registered previously as well.

**Comment by corey-blais-shift** [comment] 2023-09-14 13:51
This has started working again without action this morning.

**Comment by ArthurMa1978** [comment] 2023-09-19 09:31
Hey @ppanchal-mobiz, thank you for reaching out to us about the Azure SDK for .NET and figoured out the root cause of this issue. As this issue is related to the service side and not the SDK side, so we are not able to help you with it. Therefore, we are closing this issue for now. If you need more assistance, please [open an Azure support request](https://docs.microsoft.com/azure/azure-portal/supportability/how-to-create-azure-support-request). We apologize for any inconvenience this may cause you.

We value your feedback and we want to make sure that your problem is solved. If you think that we have misunderstood your issue or closed it incorrectly, please feel free to comment on this thread and reopen the issue. We will be happy to assist you further. Thank you for your understanding and cooperation.

**Closed by ArthurMa1978** 2023-09-19 09:31 UTC
Labels: Compute, Mgmt, customer-reported, question, needs-team-attention
