### ISSUE TITLE
[FEATURE REQ] Enable LiveMetrics without using .UseAzureMonitor()

### ISSUE THREAD

**Issue by adeliab** [Azure/azure-sdk-for-net#47423] opened 2024-12-05 10:37 UTC
### Library name

Azure.Monitor.OpenTelemetry.AspNetCore

### Please describe the feature.

Initially we migrated to OpenTelemetry by using .UseAzureMonitor() and later found out that this autogenerate metrics that we don't need and there is no way to filter them out (at least not in .NET 8).

Because of this, we reverted to configure OTel without using .UseAzureMonitor() - but now it seems that I can't enable LiveMetrics anymore.
I saw the Azure.Monitor.OpenTelemetry.LiveMetrics package is deprecated, and the classes that .UseAzureMonitor() uses to enable live metrics are internal class.

Is there a way to enable LiveMetrics for OpenTelemetry without using .UseAzureMonitor()?

**Comment by TimothyMothra** [comment] 2024-12-05 17:38
Hi @adeliab, 
I'm going to close this as a duplicate of https://github.com/Azure/azure-sdk-for-net/issues/46098
When you get a chance, please upvote that other issue.

I can confirm this is on our backlog, but I don't have any ETA to share.

**Comment by TimothyMothra** [comment] 2024-12-05 17:38
Curious, what metrics are you struggling to filter out?

**Closed by TimothyMothra** 2024-12-05 17:38 UTC
Labels: Service Attention, Client, customer-reported, question, needs-team-attention, Monitor - Distro

**Comment by adeliab** [comment] 2024-12-06 08:22
Hi @TimothyMothra , I saw #46098 but didn't consider that to be a duplicate because our application is an ASP.NET Core application (not Console app) and we are using the `[Azure.Monitor.OpenTelemetry.AspNetCore](https://www.nuget.org/packages/Azure.Monitor.OpenTelemetry.AspNetCore)` package. Just not setting it up with .UseAzureMonitor()

You mentioned in that issue as a workaround, they could use AspNetCore package in the worker service app. Do you mean that they would have to use the .UseAzureMonitor() too? I thought using the `[Azure.Monitor.OpenTelemetry.AspNetCore](https://www.nuget.org/packages/Azure.Monitor.OpenTelemetry.AspNetCore)` would allow access to some classes that I can use to setup LiveMetrics without .UseAzureMonitor()

Regarding the metrics we want to filter out, I noticed that .UseAzureMonitor() adds System.Net.Http hosting and Microsoft.AspNetCore.Hosting metrics to the customMetrics table. if there would be a way to only enable a certain metric for example http.client.request.time_in_queue, it would be useful so we can only collect the metrics we need. But it seems there is no way to configure the metric selections at all, either on namespace or metric levels. These metrics will add too much extra cost for us and therefore we revert to the .UseTracing() method so we can skip the .UseMetrics() and not have these metrics sent.

I'm curious, why is it not possible to opt-in, opt-out or filter this functionality? Is there a convention from OpenTelemetry to always record these metrics?

**Comment by adeliab** [comment] 2024-12-06 08:30
Oh @TimothyMothra i just saw that there's a functionality to [drop a metric](https://github.com/Azure/azure-sdk-for-net/blob/Azure.Monitor.OpenTelemetry.AspNetCore_1.2.0/sdk/monitor/Azure.Monitor.OpenTelemetry.AspNetCore/README.md#drop-a-metrics-instrument)

I will give this a try. if this works then, we can continue using .UseAzureMonitor() and get the live metrics back :)

**Comment by virtualcca** [comment] 2025-01-08 04:14
￼If I have more than one exporter, for example, I only want to send my metrics to Prometheus but not to appinsights’ custom metrics, so I only want to remove appinsights’ exporter for metrics, but since there are too many content bound to the current use Azure Monitor, especially the manager class in livemetrics is internal, so even if I copy the code in use Azure Monitor, it won’t work. But since the current use Azure Monitor is bound to too much content, especially the Manager class in livemetrics is internal, so even if I copy the code in the use Azure Monitor, I can’t use it. If each module is independent, the use Azure Monitor is just a convenient initialization function, and I can customize the code in the use Azure Monitor according to my needs. If each module is independent, use Azure Monitor is just a convenient initialization function, and I can customize the functions in use Azure Monitor according to my own needs, then it would be better (instead of binding the livemetrics streams in it like now).
￼If you remove the indicator directly, there will be no data in Prometheus.
