### ISSUE TITLE
[BUG] Semantic configuration properties for prioritized keyword fields not accepting string subfields of type Collection(Edm.ComplextType)

### ISSUE THREAD

**Issue by Debro012** [Azure/azure-sdk-for-net#44676] opened 2024-06-20 16:30 UTC
### Library name and version

All versions

### Describe the bug

Semantic configuration properties for prioritized keyword fields not accepting string subfields of type Collection(Edm.ComplextType). Even though this is stated as supported in [MS documentation](https://learn.microsoft.com/en-us/azure/search/semantic-how-to-configure?tabs=rest):

> Across all semantic configuration properties, the fields you assign must be:
-Attributed as searchable and retrievable
-Strings of type Edm.String, Collection(Edm.String), string subfields of Collection(Edm.ComplexType)

### Expected behavior

strings subfields of type Collection(Edm.ComplexType) being accepted as semantic configuration properties of prioritized keyword fields.

### Actual behavior

`{
    "error": {
        "code": "InvalidRequestParameter",
        "message": "The request is invalid. Details: definition : Semantic configurations support fields of type Edm.String and Collection(Edm.String). Subfields of Edm.ComplexType can be used but subfields of Collection(Edm.ComplexType) are not supported. Please visit https://aka.ms/SemanticConfiguration for more info.",
        "details": [
            {
                "code": "InvalidSemanticConfiguration",
                "message": "Semantic configurations support fields of type Edm.String and Collection(Edm.String). Subfields of Edm.ComplexType can be used but subfields of Collection(Edm.ComplexType) are not supported. Please visit https://aka.ms/SemanticConfiguration for more info. Parameters: definition"
            }
        ]
    }
}`

### Reproduction Steps

Pass a payload to the Azure AI Search service instance for index creation:

```
{
	"name": "indexName",
	"fields": [
		{
			"name": "title",
			"type": "Edm.String",
			"searchable": true,
			"filterable": true,
			"retrievable": true,
			"sortable": false,
			"facetable": false,
			"key": false,
			"indexAnalyzer": null,
			"searchAnalyzer": null,
			"analyzer": null,
			"dimensions": null,
			"vectorSearchProfile": null,
			"synonymMaps": []
		},
		{
			"name": "metadata_spo_item_path",
			"type": "Edm.String",
			"key": false,
			"searchable": false,
			"filterable": false,
			"sortable": false,
			"facetable": false
		},
		{
			"name": "metadata_spo_item_content_type",
			"type": "Edm.String",
			"key": false,
			"searchable": false,
			"filterable": true,
			"sortable": false,
			"facetable": true
		},
		{
			"name": "metadata_spo_item_last_modified",
			"type": "Edm.DateTimeOffset",
			"key": false,
			"searchable": false,
			"filterable": false,
			"sortable": true,
			"facetable": false
		},
		{
			"name": "metadata_spo_item_size",
			"type": "Edm.Int64",
			"key": false,
			"searchable": false,
			"filterable": false,
			"sortable": false,
			"facetable": false
		},
		{
			"name": "people",
			"type": "Collection(Edm.ComplexType)",
			"fields": [
				{
					"name": "LookupId",
					"type": "Edm.Int32",
					"searchable": false,
					"filterable": true,
					"sortable": false,
					"facetable": false
				},
				{
					"name": "LookupValue",
					"type": "Edm.String",
					"searchable": true,
					"filterable": true,
					"sortable": false,
					"facetable": false,
					"retrievable": true
				},
				{
					"name": "Email",
					"type": "Edm.String",
					"searchable": true,
					"filterable": true,
					"sortable": false,
					"facetable": false,
					"retrievable": true
				}
			]
		}
	],
	"scoringProfiles": [],
	"corsOptions": null,
	"suggesters": [],
	"analyzers": [],
	"tokenizers": [],
	"tokenFilters": [],
	"charFilters": [],
	"similarity": {
		"@odata.type": "#Microsoft.Azure.Search.BM25Similarity",
		"k1": null,
		"b": null
	},
	"semantic": {
		"defaultConfiguration": "config-name",
		"configurations": [
			{
				"name": "config-name",
				"prioritizedFields": {
					"titleField": {
						"fieldName": "title"
					},
					"prioritizedContentFields": [
						{
							"fieldName": "chunk"
						}
					],
					"prioritizedKeywordsFields": [
						{
							"fieldName": "topic"
						},
						{
							"fieldName": "people/LookupValue"
						},
						{
							"fieldName": "people/Email"
						}
					]
				}
			}
		]
	},
	"vectorSearch": {
		"algorithms": [
			{
				"name": "alg-name",
				"kind": "hnsw",
				"hnswParameters": {
					"metric": "cosine",
					"m": 4,
					"efConstruction": 400,
					"efSearch": 500
				},
				"exhaustiveKnnParameters": null
			}
		],
		"profiles": [
			{
				"name": "profile-name",
				"algorithm": "alg-name"
			}
		]
	}
}
```

**Comment by JonathanCrd** [comment] 2024-06-24 20:13
This issue seems to be related to `Azure.Search.Documents` and not to `Azure.Data.Tables`.
I'm assigning it to the proper team.

**Comment by ShivangiReja** [comment] 2024-06-25 14:46
Thanks for reaching out and we regret that you're experiencing difficulties.   The Azure SDK packages do not have insight nor influence over an operation failure, they just surface the HTTP error returned by the Search service.  As a result, this is not an issue that the Azure SDK team can assist with.   You will need assistance from the Azure Search service team.

To ensure that the right team has visibility and can help, your best path forward for would be to [open an Azure support request](https://docs.microsoft.com/azure/azure-portal/supportability/how-to-create-azure-support-request) or inquire on the [Microsoft Q&A site](https://learn.microsoft.com/answers/questions/) or [Azure Search · Community](https://feedback.azure.com/d365community/forum/9325d19e-0225-ec11-b6e6-000d3a4f07b8).

CC: @mattgotteiner

**Comment by mattgotteiner** [comment] 2024-06-26 23:34
I can reproduce the problem. Here's another payload:

```
PUT https://{{service}}.search.windows.net/indexes/testsemantic?api-version=2024-03-01-preview
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "testsemantic",
    "fields": [
        { "name": "id", "type": "Edm.String", "key": true },
        { "name": "content", "type": "Collection(Edm.ComplexType)", "fields": [ { "name": "str", "type": "Edm.String" } ] }
    ],
    "semantic": {
        "configurations": [
            {
                "name": "config",
                "prioritizedFields": {
                    "prioritizedKeywordsFields": [
                        { "fieldName": "content/str" }
                    ]
                }
            }
        ]
    }
}
```

**Comment by mattgotteiner** [comment] 2024-06-26 23:37
We will check to determine if we can update the documentation here

**Closed** 2024-07-04 04:34 UTC
Labels: Search, Client, customer-reported, question, Service, issue-addressed
