### ISSUE TITLE
[BUG] Sas token doesn't work when blob name has / (202106022025467114_Test_6/2/2021_8:25:14PM_valid.blob)

### ISSUE THREAD

**Issue by issacnitin** [Azure/azure-sdk-for-net#21525] opened 2021-06-02 19:02 UTC
**Describe the bug**
Please provide the description of issue you're seeing.
The sas token generated when the blob is in nested directory is not valid

**Expected behavior**
What is the expected behavior?
Sas token should work

**Actual behavior (include Exception or Stack Trace)**
What is the actual behavior?
Sas token gives "Authorization header missing"

**To Reproduce**
Steps to reproduce the behavior (include a code snippet, screenshot, or any additional information that might help us reproduce the issue)

1. Create a directory structure in blob storage
2. BlobSasBuilder sasBuilder = new BlobSasBuilder()
            {
                BlobContainerName = containerName,
                BlobName = blobName,
                ExpiresOn = DateTimeOffset.UtcNow.AddMinutes(validTimeInMinutes),
                Resource = "b"
            };
3. blobClient.GenerateSasUri(sasBuilder)

**Environment:**
 - Name and version of the Library package used: [e.g. Azure.Storage.Blobs 12.2.0]  12.8.4
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): [e.g. Azure AppService or Windows 10 .NET Framework 4.8] App Service
 - IDE and version : [e.g. Visual Studio 16.3]  Visual Studio 16.10

**Comment by amnguye** [comment] 2021-06-10 21:27
1. You should be providing Permissions in your SAS token, you should use the constructor that requires parameters for a better idea on what a SAS requires. e.g.
```
BlobSasBuilder sasBuilder = new BlobSasBuilder(permissions, expiresOn)
{
BlobContainerName = containerName,
BlobName = blobName,
Resource = "b"
};
```

2. Which API are you calling with the SAS token you generated? Please provide a code snippet with that as well.

3. Just to comment on the blob name you have in the title, those slashes would make the storage think that there's virtual directories with each slash. Please see https://docs.microsoft.com/en-us/rest/api/storageservices/naming-and-referencing-containers--blobs--and-metadata#blob-names
![image](https://user-images.githubusercontent.com/48961492/121599162-85926100-c9f7-11eb-97d3-d097a059cb2a.png)
Unless that's you're intention to have your blob path to look like
202106022025467114_Test_6 -> 2 -> 2021_8:25:14PM_valid.blob

**Comment by issacnitin** [comment] 2021-06-11 18:03
> 1. You should be providing Permissions in your SAS token, you should use the constructor that requires parameters for a better idea on what a SAS requires. e.g.
> 
> ```
> BlobSasBuilder sasBuilder = new BlobSasBuilder(permissions, expiresOn)
> {
> BlobContainerName = containerName,
> BlobName = blobName,
> Resource = "b"
> };
> ```
> 
> 1. Which API are you calling with the SAS token you generated? Please provide a code snippet with that as well.
> 2. Just to comment on the blob name you have in the title, those slashes would make the storage think that there's virtual directories with each slash. Please see https://docs.microsoft.com/en-us/rest/api/storageservices/naming-and-referencing-containers--blobs--and-metadata#blob-names
>    ![image](https://user-images.githubusercontent.com/48961492/121599162-85926100-c9f7-11eb-97d3-d097a059cb2a.png)
>    Unless that's you're intention to have your blob path to look like
>    202106022025467114_Test_6 -> 2 -> 2021_8:25:14PM_valid.blob

@amnguye Thanks for the response!
1. Yes we provide permissions, we're able to download the generated sas token along with blob URL if blob name doesn't have special characters
2. I tried directly downloading the blob by pointing browser to the generated SAS url
3. Yes I understand, I thought that was the issue as well! I tried converting %2F to / in filename in URL, that didn't work either with the SAS token generated..

**Comment by issacnitin** [comment] 2021-06-11 18:04
We need to allow as many characters for the blob Url as possible. forward slash in this case represents a date-time, which is a potential use case for our service

**Comment by issacnitin** [comment] 2021-06-14 09:50
Hi @amnguye I saw you renamed the heading, the SAS token does work when generated from portal when filename has /. When we use GetBlobSasReadUri  from .net core SDK, it doesn't work

**Comment by amnguye** [comment] 2021-06-14 16:46
Regarding 2, you did not provide the API name you are calling along with the code snippet, please reply with that information. Without out I cannot further reproduce your issue and help you. Also please send the code snippet with how you are sending the permissions as well that you referred to in 1, because I did not see that in your original code snippet.

I tried to reproduce your issue with the same exact blob name but I was able to generate a SAS using the SDK correctly and upload and download using that SAS using the SDK as well.

>I saw you renamed the heading, the SAS token does work when generated from portal when filename has /. When we use GetBlobSasReadUri from .net core SDK, it doesn't work

There's no API method called GetBlobSasReadUri. If someone was searching through our issues for issues related to SAS they would definitely never find this one.

Also if you opened this issue against in this repo, where all issues are related to the SDK, not to any of our storage services. If you wanted to open an issue regarding SAS against all of the storage tools and the service itself, go to Azure Community Support.

**Comment by issacnitin** [comment] 2021-06-15 11:34
Hi @amnguye We're internal Microsoft team, would it be possible to schedule a call to go over the issue? I feel it'd help us connect better and resolve the issue faster without lots of to-and-fro. Could you share your corp id? Alternatively you can ping me on teams, my corp id is nijoy (Will be redacted later)

**Comment by issacnitin** [comment] 2021-06-15 11:36
Oops sorry, I should've mentioned GenerateSasUri in the header instead

**Comment by amnguye** [comment] 2021-08-05 20:16
Closing issue as this was resolved offline.

**Closed by amnguye** 2021-08-05 20:16 UTC
Labels: Storage, Service Attention, Client, customer-reported, question, needs-team-attention
