### ISSUE TITLE
[BUG] System.ObjectDisposedException with message "Cannot access a closed Stream." - when calling QueueClient#UpdateMessageAsync

### ISSUE THREAD

**Issue by dxynnez** [Azure/azure-sdk-for-net#23862] opened 2021-09-08 07:31 UTC
<pre>
 System.ObjectDisposedException : Cannot access a closed Stream.
     at System.IO.MemoryStream.Write(ReadOnlySpan`1 buffer)
     at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
     at System.IO.StreamWriter.Dispose(Boolean disposing)
     at System.IO.TextWriter.Dispose()
     at System.Xml.XmlTextWriter.Close()
     at System.Xml.XmlWriter.Dispose(Boolean disposing)
     at System.Xml.XmlWriter.Dispose()
     at Azure.Core.XmlWriterContent.Dispose()
     at Azure.Core.Pipeline.HttpClientTransport.PipelineRequest.Dispose()
     at Azure.Core.HttpMessage.Dispose()
     at Azure.Storage.Queues.MessageIdRestClient.UpdateAsync(String messageid, String popReceipt, Int32 visibilitytimeout, Nullable`1 timeout, QueueMessage queueMessage, CancellationToken cancellationToken)
     at Azure.Storage.Queues.QueueClient.UpdateMessageInternal(BinaryData message, String messageId, String popReceipt, TimeSpan visibilityTimeout, Boolean async, CancellationToken cancellationToken, String operationName)
     at Azure.Storage.Queues.QueueClient.UpdateMessageAsync(String messageId, String popReceipt, String messageText, TimeSpan visibilityTimeout, CancellationToken cancellationToken)
</pre>

See https://github.com/Azure/autorest.csharp/issues/1402 for details

May I know when would the new version of the queue sdk get released with the above fix?

**Environment:**
 - Name and version of the Library package used: Azure.Storage.Queues 12.7.0

**Comment by dxynnez** [comment] 2021-09-08 07:51
Note:

In normal case I didn't get this exception - I only got it in my UT where I added a HttpPipelinePolicy with Task.Delay to force the request to timeout (set in CancellationTokenSource#CancelAfter).  Looking at the stacktrace it seems like the ObjectDisposedException should always get thrown. Could someone also help me to understand this behavior?

**Comment by kasobol-msft** [comment] 2021-09-08 20:29
@dxynnez The issue was fixed here https://github.com/Azure/autorest.csharp/issues/1402 . However the Queues SDK hasn't been yet released with the fix. The fix should be part of 12.8.0 release which is coming very soon.

**Comment by dxynnez** [comment] 2021-09-10 12:07
> @dxynnez The issue was fixed here [Azure/autorest.csharp#1402](https://github.com/Azure/autorest.csharp/issues/1402) . However the Queues SDK hasn't been yet released with the fix. The fix should be part of 12.8.0 release which is coming very soon.

Thanks @kasobol-msft . Do you have an ETA for that? We are removing ADAL dependencies in our code base but until the bug is fixed we can't really adapt the new storage SDK.

**Comment by kasobol-msft** [comment] 2021-09-10 14:04
The [Azure.Storage.Queues 12.8.0](https://www.nuget.org/packages/Azure.Storage.Queues/12.8.0) shipped this week. Please give it a try and let us know if the issue is resolved.

**Comment by dxynnez** [comment] 2021-09-10 14:23
> The [Azure.Storage.Queues 12.8.0](https://www.nuget.org/packages/Azure.Storage.Queues/12.8.0) shipped this week. Please give it a try and let us know if the issue is resolved.

wow that was quick! My tests are now passing. Thanks so much @kasobol-msft !

**Comment by kasobol-msft** [comment] 2021-09-10 14:56
Great to hear that. I'm closing the issue.

**Closed by kasobol-msft** 2021-09-10 14:56 UTC
Labels: Storage, Service Attention, Client, customer-reported, question, needs-team-attention
