### ISSUE TITLE
[BUG] BCL AsyncInterfaces runtime error on upgrade - Azure.Monitor.OpenTelemetry.AspNetCore 1.1.0

### ISSUE THREAD

**Issue by BC89** [Azure/azure-sdk-for-net#41747] opened 2024-02-02 13:58 UTC
### Library name and version

Azure.Monitor.OpenTelemetry.AspNetCore 1.1.0

### Describe the bug

Running .Net 8 version 1.0.0 of Azure.Monitor.OpenTelemetry.AspNetCore and pulling down the latest version, 1.1.0 throws an error at runtime, Minimal WebAPI. 

Docker - Linux 

```
  <ItemGroup>
    <PackageReference Include="AsyncFixer" Version="1.6.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="12.0.1" />
    <PackageReference Include="Azure.Identity" Version="1.10.4" />
    <PackageReference Include="Azure.Security.KeyVault.Secrets" Version="4.5.0" />
    <PackageReference Include="Azure.Storage.Blobs" Version="12.20.0-beta.1" />
    <PackageReference Include="Azure.Storage.Files.Shares" Version="12.18.0-beta.1" />
    <PackageReference Include="Bogus" Version="35.4.0" />
    <PackageReference Include="Dapr.AspNetCore" Version="1.12.0" />
    <PackageReference Include="Dapr.Extensions.Configuration" Version="1.12.0" />
    <PackageReference Include="Magick.NET-Q16-AnyCPU" Version="13.5.0" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Features" Version="6.0.0-preview.4.21253.5" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Graph" Version="5.41.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="SimpleDateTimeProvider" Version="2024.2.1.79" />
    <PackageReference Include="Stripe.net" Version="43.11.0" />
    <PackageReference Include="System.Linq.Dynamic.Core" Version="1.3.8" />
    <PackageReference Include="QuestPDF" Version="2023.12.4" />
    <PackageReference Include="HarfBuzzSharp.NativeAssets.Linux" Version="7.3.0.1" />
    <PackageReference Include="SkiaSharp.NativeAssets.Linux.NoDependencies" Version="2.88.7" />
  </ItemGroup>
```

### Expected behavior

Upgrade to 1.1.0 without issue.

### Actual behavior

Runtime error.

System.Reflection.ReflectionTypeLoadException
  HResult=0x80131602
  Message=Unable to load one or more of the requested types.
Could not load file or assembly 'Microsoft.Bcl.AsyncInterfaces, Version=8.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.

Could not load file or assembly 'Microsoft.Bcl.AsyncInterfaces, Version=8.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.

Could not load file or assembly 'Microsoft.Bcl.AsyncInterfaces, Version=8.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.

Could not load file or assembly 'Microsoft.Bcl.AsyncInterfaces, Version=8.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.

Could not load file or assembly 'Microsoft.Bcl.AsyncInterfaces, Version=8.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.

  Source=System.Private.CoreLib
 

### Reproduction Steps

Run api.

### Environment

Microsoft Visual Studio Professional 2022 (64-bit) - Preview
Version 17.9.0 Preview 5.0

Installed Version: Professional

Visual C++ 2022   00483-10050-37560-AA595
Microsoft Visual C++ 2022

ADL Tools Service Provider   1.0
This package contains services used by Data Lake tools

ASA Service Provider   1.0

ASP.NET and Web Tools   17.9.195.45391
ASP.NET and Web Tools

Azure App Service Tools v3.0.0   17.9.195.45391
Azure App Service Tools v3.0.0

Azure Data Lake Tools for Visual Studio   2.6.5000.0
Microsoft Azure Data Lake Tools for Visual Studio

Azure Functions and Web Jobs Tools   17.9.195.45391
Azure Functions and Web Jobs Tools

Azure Stream Analytics Tools for Visual Studio   2.6.5000.0
Microsoft Azure Stream Analytics Tools for Visual Studio

C# Tools   4.9.0-3.24073.3+d460b277f7dc6c563ace0d5558c3acfde9f2c1ff
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Cookiecutter   17.0.24002.3
Provides tools for finding, instantiating and customizing templates in cookiecutter format.

Entity Framework Core Power Tools   2.6
Adds useful design-time EF Core DbContext features to the Visual Studio Solution Explorer context menu.

Microsoft Azure Hive Query Language Service   2.6.5000.0
Language service for Hive query

Microsoft Azure Stream Analytics Language Service   2.6.5000.0
Language service for Azure Stream Analytics

Microsoft Azure Tools for Visual Studio   2.9
Support for Azure Cloud Services projects

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Node.js Tools   1.5.50908.1 Commit Hash:c294679b821c4b8f7f9c6db3827b7655db80fc28
Adds support for developing and debugging Node.js apps in Visual Studio

NuGet Package Manager   6.9.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

Office Developer Tools for Visual Studio   17.6.34328.02
Microsoft Office Developer Tools for Visual Studio

Python - Django support   17.0.24002.3
Provides templates and integration for the Django web framework.

Python - Profiling support   17.0.24002.3
Profiling support for Python projects.

Python with Pylance   17.0.24002.3
Provides IntelliSense, projects, templates, debugging, interactive windows, and other support for Python developers.

Razor (ASP.NET Core)   17.9.2.2405304+df383360c34ada8889fdf18dc36d245f2938db66
Provides languages services for ASP.NET Core Razor.

SQL Server Data Tools   17.9.48.0
Microsoft SQL Server Data Tools

Test Adapter for Boost.Test   1.0
Enables Visual Studio's testing tools with unit tests written for Boost.Test.  The use terms and Third Party Notices are available in the extension installation directory.

Test Adapter for Google Test   1.0
Enables Visual Studio's testing tools with unit tests written for Google Test.  The use terms and Third Party Notices are available in the extension installation directory.

ToolWindowHostedEditor   1.0
Hosting json editor into a tool window

TypeScript Tools   17.0.30103.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   4.9.0-3.24073.3+d460b277f7dc6c563ace0d5558c3acfde9f2c1ff
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual C++ for Cross Platform Mobile Development (Android)   15.0.34511.75
Visual C++ for Cross Platform Mobile Development (Android)

Visual F# Tools   17.9.0-beta.23614.3+a521e1cd420beb56c15faf6836184fadd2b7937a
Microsoft Visual F# Tools

Visual Studio IntelliCode   2.2
AI-assisted development for Visual Studio.

Workflow Manager Tools 1.0   1.0
This package contains the necessary Visual Studio integration components for Workflow Manager.

**Comment by TimothyMothra** [comment] 2024-02-02 18:10
Hi @BC89, I'm not able to reproduce this.
Can you please share a minimal repro?

This is what I tried:
https://learn.microsoft.com/aspnet/core/tutorials/min-web-api

csproj
```
<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Azure.Monitor.OpenTelemetry.AspNetCore" Version="1.1.0" />
  </ItemGroup>
</Project>
```
Program.cs
```
namespace WebApplication4
{
    using Azure.Monitor.OpenTelemetry.AspNetCore;

    public class Program
    {
        public static void Main(string[] args)
        {
            var builder = WebApplication.CreateBuilder(args);
            builder.Services.AddOpenTelemetry().UseAzureMonitor(x => x.ConnectionString = "...");
            var app = builder.Build();

            app.MapGet("/", () => "Hello World!");

            app.Run();
        }
    }
}

```

**Comment by TimothyMothra** [comment] 2024-02-07 21:11
Hi @BC89,
Can you please share what cmd you're using to publish your application? (`dotnet publish`) ?
We're curious if you're trimming your application.

**Comment by BC89** [comment] 2024-02-09 14:34
With visual studio I'm simply F5ing to launch my docker compose which then spins up all the individual docker files. Do you see the list of other nugets I'm pulling in. Feels like there may be a conflict somewhere within the tree.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Timothy Mothra ***@***.***>
Sent: Wednesday, February 7, 2024 4:11:23 PM
To: Azure/azure-sdk-for-net ***@***.***>
Cc: Brendan Carroll ***@***.***>; Mention ***@***.***>
Subject: [External Email] Re: [Azure/azure-sdk-for-net] [BUG] BCL AsyncInterfaces runtime error on upgrade - Azure.Monitor.OpenTelemetry.AspNetCore 1.1.0 (Issue #41747)


***From ***@***.*** 410-316-7820 *** This is an External Email from outside of KCI.***
________________________________
Hi @BC89<https://github.com/BC89>,
Can you please share what cmd you're using to publish your application? (dotnet publish) ?
We're curious if you're trimming your application.

**Comment by TimothyMothra** [comment] 2024-02-09 19:18
Sorry, I don't see the list of nugets. If you can share a minimal repro that would help investigate. If that's too large to share, you can create a new github repo to host a sample app.

**Comment by nschoenberg** [comment] 2024-02-12 07:44
I have the same Issue in my azure web app that is running on a windows plan using .NET 8 stack. Other healthchecks like postgres database check are working fine

`Could not load file or assembly 'Microsoft.Bcl.AsyncInterfaces, Version=8.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.`

**Comment by BC89** [comment] 2024-02-20 15:18
My suspicion is this is related to a conflict with AutoMapper's depedencies but here is the nugs:



  <ItemGroup>
    <PackageReference Include="AsyncFixer" Version="1.6.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="AutoMapper" Version="13.0.1" />
    <PackageReference Include="Azure.Identity" Version="1.10.4" />
    <PackageReference Include="Azure.Security.KeyVault.Secrets" Version="4.6.0" />
    <PackageReference Include="Azure.Storage.Blobs" Version="12.20.0-beta.1" />
    <PackageReference Include="Azure.Storage.Files.Shares" Version="12.18.0-beta.1" />
    <PackageReference Include="Bogus" Version="35.4.0" />
    <PackageReference Include="Dapr.AspNetCore" Version="1.12.0" />
    <PackageReference Include="Dapr.Extensions.Configuration" Version="1.12.0" />
    <PackageReference Include="Magick.NET-Q16-AnyCPU" Version="13.6.0" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Features" Version="6.0.0-preview.4.21253.5" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.2">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Graph" Version="5.42.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="SimpleDateTimeProvider" Version="2024.2.1.79" />
    <PackageReference Include="Stripe.net" Version="43.11.0" />
    <PackageReference Include="System.Linq.Dynamic.Core" Version="1.3.8" />
    <PackageReference Include="QuestPDF" Version="2023.12.5" />
    <PackageReference Include="HarfBuzzSharp.NativeAssets.Linux" Version="7.3.0.1" />
    <PackageReference Include="SkiaSharp.NativeAssets.Linux.NoDependencies" Version="2.88.7" />
  </ItemGroup>

**Comment by TimothyMothra** [comment] 2024-03-13 20:50
We released a new beta version of Azure.Monitor.OpenTelemetry.AspNetCore which we believe will address this issue.
https://www.nuget.org/packages/Azure.Monitor.OpenTelemetry.AspNetCore/1.2.0-beta.2

I'm going to close this Issue. If you have any more problems, please respond.

**Closed by TimothyMothra** 2024-03-13 20:50 UTC
Labels: Service Attention, Client, customer-reported, question, needs-team-attention, Monitor - Distro

**Comment by TimothyMothra** [comment] 2024-03-14 16:58
Hi @BC89, that's a separate issue.
You should open a new issue to get support with Azure.Identity.
