### ISSUE TITLE
[BUG] ClientDiagnostics.GetResourceProviderNamespace allocations

### ISSUE THREAD

**Issue by Tornhoof** [Azure/azure-sdk-for-net#38984] opened 2023-09-27 09:17 UTC
### Library name and version

Azure.Storage.Files.DataLake 12.16.0

### Describe the bug

In a recent memory profiling session to find memory leaks (not related), one of the major  string allocations was the following (this is only a short run, to demonstrate the problem).

detail:
![grafik](https://github.com/Azure/azure-sdk-for-net/assets/7989549/a50ed523-f046-4f6c-b488-0e7581226e38)
total:
![grafik](https://github.com/Azure/azure-sdk-for-net/assets/7989549/2e736505-e296-4bb8-ab8a-a5e3e42ae414)

An instance of the ClientDiagnostics Type is created for each BlobContainerClient (and probably others too).
https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/Azure.Core/src/Shared/ClientDiagnostics.cs
In the ctor it calls a method, which reads some namespace via assembly attributes
https://github.com/Azure/azure-sdk-for-net/blob/9b7a0f4fee2d49cb1eb78412e2150dff88390a70/sdk/core/Azure.Core/src/Shared/ClientDiagnostics.cs#L31-L37

and that method:
https://github.com/Azure/azure-sdk-for-net/blob/9b7a0f4fee2d49cb1eb78412e2150dff88390a70/sdk/core/Azure.Core/src/Shared/ClientDiagnostics.cs#L63-L75

parses the assembly attributes and reads a value via reflection, which is then responsible for the above stacktrace.

Aren't there better ways to do that?
Cache it in a concurrentdictionary by Assembly?

### Expected behavior

Less allocations

### Actual behavior

many allocations

### Reproduction Steps

Code Analysis after Memory profiling

### Environment

.NET 7

**Comment by jsquire** [comment] 2023-09-27 13:27
Storage team:  I'm triaging this as a storage issue because the design of `ClientDiagnostics` is based the expectation that an instance is created once for a long-lived client instance.  The behavior reported in this issue seems to stem from a pattern of using ephemeral clients, each of which creates a unique diagnostics instance.  

//fyi: @schaabs

**Comment by Tornhoof** [comment] 2023-09-29 10:09
I tracked down the issue in our code base and it apparently was an oversight (hard to tell the relevant code is a few years old and the original included the same issue). Changing the code to cache the ``DatalakeFileSystemClient`` indeed reduces the allocations as the originally mentioned ``ClientDiagnostics`` instance is reused.

I expect this can be closed, if the usage pattern is to use to use long-living client instances.

**Comment by jsquire** [comment] 2023-09-29 14:26
> I expect this can be closed, if the usage pattern is to use to use long-living client instances.

Thanks for the update, @Tornhoof, and I'm glad that you were able to find the root cause.   The guidance for all Azure SDK clients is indeed to treat them as long-lived and, ideally, singletons.   Documentation can be found in [Thread safety and client lifetime management for Azure SDK objects](https://learn.microsoft.com/dotnet/azure/sdk/thread-safety#client-lifetime) and [Lifetime management for Azure SDK .NET clients](https://devblogs.microsoft.com/azure-sdk/lifetime-management-and-thread-safety-guarantees-of-azure-sdk-net-clients/).

I'm going to close this out, but please feel free to unresolve if you'd like to continue the discussion.

**Closed** 2023-09-29 14:26 UTC
Labels: Storage, Service Attention, Client, customer-reported, question, issue-addressed
