### ISSUE TITLE
[BUG] Invalid operation exception while sending batched messages to Service Bus Standard tier

### ISSUE THREAD

**Issue by arunprakashn** [Azure/azure-sdk-for-net#27067] opened 2022-02-17 03:26 UTC
### Library name and version

Azure.Messaging.Servicebus 7.5.1

### Describe the bug

I was sending batched messages to Azure Service Standard and encountered the following exception. Note that this exception is not reproducible consistently. My observation is that when the load on the ASB Standard is close to getting it throttled, this happens.

```
System.AggregateException: One or more errors occurred. ---> System.InvalidOperationException: Cannot open log for source 'Microsoft.ServiceBus'. You may not have write access.
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Azure.Messaging.ServiceBus.Amqp.AmqpSender.<SendBatchInternalAsync>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azure.Messaging.ServiceBus.Amqp.AmqpSender.<>c.<<SendBatchAsync>b__18_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azure.Messaging.ServiceBus.ServiceBusRetryPolicy.<>c__20`1.<<RunOperation>b__20_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Azure.Messaging.ServiceBus.ServiceBusRetryPolicy.<RunOperation>d__21`2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Azure.Messaging.ServiceBus.ServiceBusRetryPolicy.<RunOperation>d__21`2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azure.Messaging.ServiceBus.ServiceBusRetryPolicy.<RunOperation>d__20`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azure.Messaging.ServiceBus.Amqp.AmqpSender.<SendBatchAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azure.Messaging.ServiceBus.ServiceBusSender.<SendMessagesAsync>d__30.MoveNext()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.InvalidOperationException: Cannot open log for source 'Microsoft.ServiceBus'. You may not have write access.
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Azure.Messaging.ServiceBus.Amqp.AmqpSender.<SendBatchInternalAsync>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azure.Messaging.ServiceBus.Amqp.AmqpSender.<>c.<<SendBatchAsync>b__18_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azure.Messaging.ServiceBus.ServiceBusRetryPolicy.<>c__20`1.<<RunOperation>b__20_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Azure.Messaging.ServiceBus.ServiceBusRetryPolicy.<RunOperation>d__21`2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Azure.Messaging.ServiceBus.ServiceBusRetryPolicy.<RunOperation>d__21`2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azure.Messaging.ServiceBus.ServiceBusRetryPolicy.<RunOperation>d__20`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azure.Messaging.ServiceBus.Amqp.AmqpSender.<SendBatchAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azure.Messaging.ServiceBus.ServiceBusSender.<SendMessagesAsync>d__30.MoveNext()<---
```

### Expected behavior

There should not be any exceptions.

### Actual behavior

Exception occured
```
System.AggregateException: One or more errors occurred. ---> System.InvalidOperationException: Cannot open log for source 'Microsoft.ServiceBus'. You may not have write access.
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Azure.Messaging.ServiceBus.Amqp.AmqpSender.<SendBatchInternalAsync>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azure.Messaging.ServiceBus.Amqp.AmqpSender.<>c.<<SendBatchAsync>b__18_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azure.Messaging.ServiceBus.ServiceBusRetryPolicy.<>c__20`1.<<RunOperation>b__20_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Azure.Messaging.ServiceBus.ServiceBusRetryPolicy.<RunOperation>d__21`2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Azure.Messaging.ServiceBus.ServiceBusRetryPolicy.<RunOperation>d__21`2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azure.Messaging.ServiceBus.ServiceBusRetryPolicy.<RunOperation>d__20`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azure.Messaging.ServiceBus.Amqp.AmqpSender.<SendBatchAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azure.Messaging.ServiceBus.ServiceBusSender.<SendMessagesAsync>d__30.MoveNext()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.InvalidOperationException: Cannot open log for source 'Microsoft.ServiceBus'. You may not have write access.
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Azure.Messaging.ServiceBus.Amqp.AmqpSender.<SendBatchInternalAsync>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azure.Messaging.ServiceBus.Amqp.AmqpSender.<>c.<<SendBatchAsync>b__18_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azure.Messaging.ServiceBus.ServiceBusRetryPolicy.<>c__20`1.<<RunOperation>b__20_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Azure.Messaging.ServiceBus.ServiceBusRetryPolicy.<RunOperation>d__21`2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Azure.Messaging.ServiceBus.ServiceBusRetryPolicy.<RunOperation>d__21`2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azure.Messaging.ServiceBus.ServiceBusRetryPolicy.<RunOperation>d__20`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azure.Messaging.ServiceBus.Amqp.AmqpSender.<SendBatchAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azure.Messaging.ServiceBus.ServiceBusSender.<SendMessagesAsync>d__30.MoveNext()<---
```

### Reproduction Steps

Used .net SDK to continuously send batched messages to ASB standard

### Environment

.net 4.8

**Comment by srivathsanvlb** [comment] 2022-02-17 07:17
I am from the same team as the author of this thread. We have throttled requests. According to the documentation we have not received the message "The request was terminated because the entity is being throttled. Error code: 50009. Please wait 2 seconds and try again". We are checking on that.

Also, MessagingErrorSubCode  should have some value as said in the metrics documentation, but no value is found for it.

<img width="955" alt="Throttle Metrics" src="https://user-images.githubusercontent.com/35536827/154424816-cd658ba0-2d9e-4768-9b42-0aa495c3c052.png">

**Comment by jsquire** [comment] 2022-02-17 13:38
@EldertGrootenboer:  Based on the message, stack trace, and source of an inner exception, this appears to be generated by the service.   Would you be so kind as to raise this for investigation?

**Comment by jsquire** [comment] 2022-02-17 13:38
@arunprakashn: Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by srivathsanvlb** [comment] 2022-02-18 07:17
Thank you @jsquire. Appreciate your work.

**Comment by shankarsama** [comment] 2022-03-04 00:07
This error "_Cannot open log for source 'Microsoft.ServiceBus'. You may not have write access._" is not originated from Service Bus service. It's purely local exception. It looks like it fails to write an event into event source called 'Microsoft.ServiceBus' when Service Bus service returns an error. So actual Service Bus exception is hidden by this local exception.

The reason why it happens intermittently is because it happens only when Service Bus service throws an exception due to throttling or some other exception.

Solution:
Make your .Net application has permission to write to event source.

**Comment by srivathsanvlb** [comment] 2022-03-04 04:29
@shankarsama Thanks for your reply.

But according to Microsoft documentation, when throttling happens we are supposed to get the error message ""The request was terminated because the entity is being throttled. Error code: 50009. Please wait 2 seconds and try again".  (**Reference** : https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-throttling#how-will-i-know-that-im-being-throttled). But we didn't get that message even though there were messages that were throttled. Is there any reason for the same?

Also I have attached a screenshot above in which the Metrics shows that MessagingErrorSubCode has value **unknown**. Can you please explain what it means?

**Comment by arunprakashn** [comment] 2022-03-04 05:19
Hi @jsquire : @shankarsama  is of the opinion that this exception is purely a local exception but you observed that it had originated from Azure service. Could you please check with @shankarsama  and confirm ?

@shankarsama : we already have enabled write access to the events. If other events are getting written then how does all of a sudden it loses write privileges. It is unlikely.
It seems there is another team that got this exception in Python SDK too.  
https://github.com/Azure/azure-sdk-for-python/issues/21789

**Comment by jsquire** [comment] 2022-03-04 15:18
@arunprakashn:  Apologies for the confusion.   I do not believe this is a local exception in your application or in the SDK.   I'll follow-up with @shankarsama offline for discussion.

**Comment by jsquire** [comment] 2022-03-08 17:28
Hi @arunprakashn.  We've discussed internally and agree that this appears to be an error triggered by the service.  It is currently under investigation.

**Comment by krishnasankarv** [comment] 2022-05-24 04:13
Any update on this issue. We are also seeing this issue .

**Comment by jsquire** [comment] 2022-05-24 14:06
Hi @krishnasankarv.   Unfortunately, I do not have insight; we'll need to ask @yvgopal and @shankarsama.

**Comment by vsinghal-symplr** [comment] 2022-07-18 09:23
@jsquire, @yvgopal, @shankarsama, Any update on this issue ...
Thanks

**Comment by yvgopal** [comment] 2022-07-18 17:49
Throttling exception (ServerBusy) is totally different from the original exception. Throttling is caused by clients pushing too much load.

Cannot open log for source 'Microsoft.ServiceBus' is also coming from service bus service. I found it in our logs after some digging. But it was coming only from one of the front-end nodes in only one cluster so far. It has got to do with the way the Azure VM is created or bootstrapped. We haven't yet fixed it. If it happens again, we will just re-image that one VM.

I am closing it as it is not an SDK issue. Let me know if you keep running into this issue, we will reimage the affected VM in the service.

**Closed by yvgopal** 2022-07-18 17:49 UTC
Labels: Service Bus, Service Attention, customer-reported, question, needs-team-attention, Service
