### ISSUE TITLE
[Text Analytics] AnalyzeOperationWithErrorTest failing in nightly runs

### ISSUE THREAD

**Issue by Menghua1** [Azure/azure-sdk-for-net#34980] opened 2023-03-17 07:38 UTC
Text Analytics nightly test runs are failing with:

> Error message
> Expected string length 21 but was 3. Strings differ at index 0.
> Expected: "InvalidParameterValue"
> But was:  "401"
> -----------^
> 
> 
> Stack trace
>    at Azure.AI.TextAnalytics.Tests.AnalyzeOperationTests.AnalyzeOperationWithErrorTest() in /mnt/vss/_work/1/s/sdk/textanalytics/Azure.AI.TextAnalytics/tests/AnalyzeOperationTests.cs:line 502
> 
> 1)    at Azure.AI.TextAnalytics.Tests.AnalyzeOperationTests.AnalyzeOperationWithErrorTest() in /mnt/vss/_work/1/s/sdk/textanalytics/Azure.AI.TextAnalytics/tests/AnalyzeOperationTests.cs:line 502
> 

For more details check here:

- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2636774&view=results

@jsquire for notification.

**Comment by joseharriaga** [comment] 2023-04-10 16:33
This is a duplicate of https://github.com/Azure/azure-sdk-for-net/issues/35452.

**Closed by joseharriaga** 2023-04-10 16:33 UTC
Labels: Client, Cognitive - Text Analytics, test-reliability
