### ISSUE TITLE
[QUERY] Download blobs into Upload blob from zip stream

### ISSUE THREAD

**Issue by ScottKane** [Azure/azure-sdk-for-net#9999] opened 2020-02-15 03:41 UTC
### Which service(blob, file, queue, table) does this issue concern?
Blob

### Which version of the SDK was used?
Azure.Storage.Blobs:12.0.0 - Nuget

### Which platform are you using? (ex: .NET Core 2.1)
NET Core 3.1

### What problem was encountered?
containerClient.UploadBlobAsync fails to upload zip stream into blob

### How can we reproduce the problem in the simplest way?

        static async Task Main()
        {
            await ZipAzureBlob("testblob");
        }

        static async Task ZipAzureBlob(string containerName)
        {
            var blobServiceClient = new BlobServiceClient("");
            var containerClient = blobServiceClient.GetBlobContainerClient(containerName);
            using (MemoryStream zipStream = new MemoryStream())
            {
                using (ZipArchive zip = new ZipArchive(zipStream, ZipArchiveMode.Create, true))
                {
                    await foreach (BlobItem blobItem in containerClient.GetBlobsAsync())
                    {
                        ZipArchiveEntry entry = zip.CreateEntry(blobItem.Name);
                        using (Stream entryStream = entry.Open())
                        {
                            var blobClient = containerClient.GetBlobClient(blobItem.Name);
                            Console.WriteLine($"Adding file to zip archive: {blobItem.Name}");
                            await blobClient.DownloadToAsync(entryStream);
                        }
                    }
                }
                Console.WriteLine($"Uploading zip archive {containerName}.zip to {containerName}");
                await containerClient.UploadBlobAsync($"{containerName}.zip", zipStream);
            }
        }

### Have you found a mitigation/solution?
No

### Comments

Is there any way I can get an OpenWrite stream to directly upload the zip stream into a container?

e.g:
From:
`using (MemoryStream zipStream = new MemoryStream())`
To:
`using (MemoryStream zipStream = containerClient.OpenWrite())` or similar.

**Comment by jsquire** [comment] 2020-02-16 16:23
//cc: @tg-msft

**Comment by amnguye** [comment] 2020-02-19 00:36
Hi Scott,

(I'm assuming when you created the BlobServiceClient, in the quotations you specified the storage account where the existing container exists)

When you say "containerClient.UploadBlobAsync" fails, do you have logs or the call stack for this failure?

"Is there any way I can get an OpenWrite stream to directly upload the zip stream into a container?"
No, there's no method to open a stream to a blob in a container.

**Comment by wantedfast** [comment] 2020-02-19 09:31
Hi, @ScottKane 
This is caused by [reusing MemoryStream](https://stackoverflow.com/a/5769575/12301879).  ​
please set "zipStream.Position = 0;" before upload.

@jongio

**Comment by ScottKane** [comment] 2020-02-19 21:22
@amnguye Yes all of the resources exist in Azure, I don't have access to the machine I was working on this from at the moment so will have to get some logs when I'm back at the machine. Also I'm sure the .NET full implementation has the ability to open a stream directly into a container? (https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.storage.blob.cloudblockblob.openwrite?view=azure-dotnet-legacy)

@wantedfast I will try setting the stream position to 0 to see if that was the problem.

Thanks for the suggestions

**Comment by seanmcc-msft** [comment] 2020-02-19 21:50
@ScottKane, the API you referenced is to write to a Block Blob, not a Container.  It's not possible to write directly to a Container, only to Blobs.  A Container is similar to a folder in a file system.

**Comment by wantedfast** [comment] 2020-02-24 02:04
Hi @ScottKane
Any feedback from your side ? Does this workaround(zipStream.Position=0;) works for you ?

**Comment by tzhanl** [comment] 2020-03-06 02:04
We are going to close this issue because we haven’t heard from you in a few days, but please re-open it if the issue still persists.

**Closed by tzhanl** 2020-03-06 02:04 UTC
Labels: Client, Question, Storage, customer-reported
