### ISSUE TITLE
Regenerate the Search SDK to pick up any new authoring

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-for-net#14588] opened 2020-08-26 18:53 UTC
The following issue should already be in the SDK, but there has been discussion about other recent swagger changes that are coming soon. We should make sure we pick up the authoring and either do a servicing release or plan on a patch release along our normal release schedule.

> Yes. Thanks for the reminder. I'll open a separate issue to make sure we re-generate the track 2 SDK.
>
> _Originally posted by @heaths in https://github.com/Azure/azure-rest-api-specs/issues/9160#issuecomment-681059785_

**Comment by heaths** [comment] 2020-09-18 20:49
As of 2020-09-18 a regeneration yielded no code changes.

**Comment by AlexGhiondea** [comment] 2020-10-01 20:49
Dupe of #12374.

**Closed by AlexGhiondea** 2020-10-01 20:49 UTC
Labels: Client, Search
