### ISSUE TITLE
[BUG] EventHubProducerClient.CreateBatchAsync() never returns if offline when called

### ISSUE THREAD

**Issue by BenHagueLucidity** [Azure/azure-sdk-for-net#10310] opened 2020-03-05 04:51 UTC
If I attempt to create an EventDataBatch via   
```
  EventHubProducerClientOptions clientOptions = new EventHubProducerClientOptions
            {
                RetryOptions = new EventHubsRetryOptions
                {
                    MaximumRetries = 10,
                    Delay = TimeSpan.FromSeconds(5),
                    MaximumDelay = TimeSpan.FromSeconds(10),
                    Mode = EventHubsRetryMode.Fixed,
                    TryTimeout = TimeSpan.FromSeconds(1)
                }

            };
await using var producerClient = new EventHubProducerClient(connectionString, eventHubName, clientOptions);
            using EventDataBatch eventBatch = await producerClient.CreateBatchAsync();
```
Then if the PC is offline when this is called then the call to CreateBatchAsync never returns. Using the debugger I can see it reach this point but it never trips the breakpoint on the next line. Even if the PC goes online again it does not continue.

I would have expected it to retry based on the retry options.

This is using Azure.Messaging.EventHubs 5.0.1 in Visual Studio Community Version 16.3.3 with Microsoft .Net Framework 4.8.03752 on Windows 10 18363.657

**Comment by jsquire** [comment] 2020-03-05 14:14
Hi @BenHagueLucidity.   We're sorry that you're experiencing difficulties and appreciate you reaching out to let us know.

You're correct in that batch creation should fail when the Event Hubs service is unreachable and that the retry policy should be respected.   At a glance, the code snippet that you've shared looks correct to me.   We'll start investigating and update this issue with our findings or any questions.

To start, can you confirm that I'm understanding you correctly in that:

- The machine was able to reach the Event Hubs service when the producer client was created.

- After creating the producer, the machine was disconnected from the network.   At the point of disconnection, the producer had been created and the constructor call had already returned.

- The call to `CreateBatchAsync` was made with the machine disconnected from the network _(and, thus, unable to reach the Event Hubs service)_

- The call to `CreateBatchAsync` was started, but you never saw that method return.

**Comment by jsquire** [comment] 2020-03-05 15:29
Hi @BenHagueLucidity.   I've been unable to reproduce thus far using a test bed based on the code that you shared and the assumptions that I had mentioned above.   The snippet that was using can be found below.

The behavior that I'm seeing in my attempts is what I would expect:

- When the producer is created and no operation is performed before creating the batch, the host is unable to be resolved when attempting to make the connection;  this is expected because the connection to the Event Hubs service won't be opened until an operation the requires it is invoked, in this case `CreateBatchAsync`

- If I interject an operation between creation of the producer and creation of the batch, allow it to execute, and then disconnect from the network, I'm seeing the expected timeout (via task cancellation exception).   This is expected because the connection had been previously established, but there was a need to query the Event Hubs service for the maximum size allowed for a message.  The request to the service could not be made, and the operation was cancelled after the requested retries were exhausted.

At this point, I'm not sure how to establish a deterministic reproduction of the issue that you're describing.  Any additional context around the code/application that you're working with, the host environment and network, and the configuration of your Event Hubs namespace and resources may be helpful and would be greatly appreciated.


My test code:
```csharp
public async Task Main()
{
    var conn = "...";
    var hub = "...";

    var clientOptions = new EventHubProducerClientOptions
    {
        RetryOptions = new EventHubsRetryOptions
        {
            MaximumRetries = 10,
            Delay = TimeSpan.FromSeconds(5),
            MaximumDelay = TimeSpan.FromSeconds(10),
            Mode = EventHubsRetryMode.Fixed,
            TryTimeout = TimeSpan.FromSeconds(1)
        }

    };

    // Create the client; this will not establish the service connection since it is lazy.
    await using var producerClient = new EventHubProducerClient(conn, hub, clientOptions);

    // Force the service connection to be established without opening the publishing link.
    (await producerClient.GetEventHubPropertiesAsync()).Dump();

    // Create the batch; the first invocation will establish the publishing link to determine
    // the maximum message size.
    using EventDataBatch eventBatch = await producerClient.CreateBatchAsync();

    eventBatch.Dump();
    "Done".Dump();
}
```

**Comment by BenHagueLucidity** [comment] 2020-03-05 18:59
Hi,
I may be misunderstanding how it's supposed to work, but what I'm doing to test, using your test code is (with the GetEventHubPropertiesAsync commented out):
1) Start program with network disconnected.
2) Connect network during the CreateBatchAsync line
What I'd expect is that CreateBatchAsync could then recover and continue but it doesn't appear to. 

If instead I do:
1) Start program with network disconnected.
2) Connect network during the GetEventHubProperties line
then I do see the behaviour I'd expect with it retrying and continuing on.

It looks like I can get the behaviour I want by calling GetEventHubPropertiesAsync before CreateBatchAsync, i.e. if the network is done when trying to sent an event retry a few times before giving up, but I would like to know if this is a problem with my expectations or not? 

The event hub setup is pretty basic, a resource group just containing a single event hub namespace which just contains a single hub. I think it's all pretty much default settings.

**Comment by jsquire** [comment] 2020-03-05 19:43
Thank you for the clarification.   We definitely overlooked applying the retry policy to that operation, #10320 addresses that oversight.   Thank you for calling that out.

We also confirmed that the per-try timeout is being respected, so your statement about the call never returning concerns me.  We should see a task cancellation exception occur around the one second mark, which I am seeing consistently.  Based on the additional context, I'm wondering if I'm misinterpreting what you're describing.   When you cay that "it doesn't return",  do you mean that `the call hangs indefinitely and does not either throw an exception or return a value`,  or do you mean that `the call isn't recovering when the network connection is restored`?   

If the latter, then the fix for the retry policy should address it.  If the former, I suspect we may have a race condition of some sort in the underlying protocol library that I'd like to figure out how to get deterministic repro on so that I can ask the team that owns that library to investigate, and any other context or details that you are willing to share could be very helpful.

**Comment by BenHagueLucidity** [comment] 2020-03-09 00:36
Thanks for the fix. 
I was wrong about the call not returning, I was looking in the wrong place, when I looked in the right place it was throwing an exception.

**Comment by jsquire** [comment] 2020-03-09 14:30
Thank you for the additional context; that alleviates my concern.  The fix will be included in our next release, expected in April.   I'm going to close this out as resolved, but please feel free to reopen if there's anything that I overlooked.

**Closed by jsquire** 2020-03-09 14:30 UTC
Labels: Bug, Client, Event Hubs, customer-reported, needs-more-info
