### ISSUE TITLE
[BUG] Service bus refreshing AAD tokens a lot

### ISSUE THREAD

**Issue by Mortana89** [Azure/azure-sdk-for-net#22991] opened 2021-07-30 12:54 UTC
**Describe the bug**
Got a message that our AI daily quota, on our QA environment, has been reached.
Upon investigation I noticed there's A LOT of AAD requests happening under the bonnet by the service bus SDK.
I don't know if this is normal behavior, I would expect this to be cached perhaps?

**Expected behavior**
The token to only be refreshed when it is expired, is it cached?

**Actual behavior (include Exception or Stack Trace)**
This is a screenshot of our AI instance, showing requests for past 30minutes;
![image](https://user-images.githubusercontent.com/45714001/127655668-17d2bad2-c547-4193-904f-6b5d7200ffbf.png)
This is on a VMSS, having 23 ASP.NET services using ASB.

**Environment:**
 -  Azure.Messaging.ServiceBus v7.1.2
 - ASP.NET Core 3.1, Azure Service Fabric 8.0

**Comment by jsquire** [comment] 2021-07-30 13:44
//fyi: @JoshLove-msft

**Comment by jsquire** [comment] 2021-07-30 13:48
Hi @Mortana89.   Thank you for reaching out and we regret that you're experiencing difficulties.  Because the credential is self-managing, any refresh requests would be triggered by it and not the Service Bus client library.   I've looped in our `Azure.Identity` experts, as they're best able to assist.

**Comment by christothes** [comment] 2021-07-30 16:09
The ServiceBusClient appears to not be doing any token caching. @JoshLove-msft - it looks like only `ServiceBusAdministrationClient` uses `BearerTokenAuthenticationPolicy`, which would cache tokens - Is there a reason it isn't used in the other clients?

**Comment by jsquire** [comment] 2021-07-30 16:17
@christothes:  The AMQP connection is persistent and authorization isn't sent with every network request.   The token is only sent once when a connection/link is established and then not again until a background timer refreshes it slightly before it expires.   

_([example](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/servicebus/Azure.Messaging.ServiceBus/src/Amqp/AmqpConnectionScope.cs#L652))_

**Comment by christothes** [comment] 2021-07-30 16:21
It sounds like we need to investigate this from the ServiceBus perspective to determine why GetToken is being called so much. The credential won't ever call on its own.

**Comment by Mortana89** [comment] 2021-07-30 16:24
I see this is happening per session? We have many unique session IDs as we use this to have FIFO per entity ID (like customer id). This could be the issue perhaps? Shouldn't the AMQP connection be shared, or am I reading the code wrong 🧐

**Comment by jsquire** [comment] 2021-07-30 16:25
My understanding was that the credential was expiration-aware and would only perform an active request when `GetToken` was called and the token was within an interval close to its expiration.   To clarify, are we saying that's not the case?   

Assuming my understanding is flawed, then yes... this would likely indicate an issue where the AMQP connection/link is either dropping frequently or Service Bus is needing to create new links for some reason.

**Comment by jsquire** [comment] 2021-07-30 16:28
@JoshLove-msft:  Is Service Bus opening a new link for each session?   If so, and @christothes confirms the token makes an active request for every `GetToken` call,  it sounds like we'll need to add another layer of caching around it.

**Comment by christothes** [comment] 2021-07-30 16:28
> My understanding was that the credential was expiration-aware and would only perform an active request when `GetToken` was called and the token was within an interval close to its expiration. To clarify, are we saying that's not the case?

It's actually `BearerTokenAuthenticationPolicy` that typically handles token expiration and caching. I don't believe any of our credentials handle expiration automatically, although some handle caching via the underlying MSAL client.

**Comment by jsquire** [comment] 2021-07-30 16:29
@christothes.  Thanks.  It seems that we've got a gap based on our misunderstanding.    That puts this firmly back in Service Bus territory.

**Comment by jsquire** [comment] 2021-07-30 16:47
> Shouldn't the AMQP connection be shared, or am I reading the code wrong 🧐

Thanks, @Mortana89.  That is helpful context;  the connection is shared, but I suspect that each session needs a dedicated link.  Since authorization exists at the link level, if I'm correct, and you're moving through sessions, then the client will be closing/opening links frequently - effectively working around the timer-based mechanism that manages refreshes.

**Comment by JoshLove-msft** [comment] 2021-07-30 17:15
> @JoshLove-msft: Is Service Bus opening a new link for each session? If so, and @christothes confirms the token makes an active request for every `GetToken` call, it sounds like we'll need to add another layer of caching around it.

Yes, each unique session would have its own receive link.

**Comment by JoshLove-msft** [comment] 2021-07-30 17:45
I don't think this is specific to sessions, or even Service Bus for that matter (should apply to Event Hubs as well), but it is just more likely to be noticed when using and switching between many sessions. The root cause seems to be that we do not cache across links for the same AMQP connection.

**Comment by jsquire** [comment] 2021-07-30 18:42
> The root cause seems to be that we do not cache across links for the same AMQP connection.

Agreed;  It's pretty clear that we do need to look at a different approach to caching in Service Bus if the link use is expected.  That said, if Service Bus is not closing/opening links frequently as an expected side-effect of sessions, then something else seems to be off and we should understand why link use is unstable.

**Comment by JoshLove-msft** [comment] 2021-07-30 18:55
> > The root cause seems to be that we do not cache across links for the same AMQP connection.
> 
> Agreed; It's pretty clear that we do need to look at a different approach to caching in Service Bus if the link use is expected. That said, if Service Bus is not closing/opening links frequently as an expected side-effect of sessions, then something else seems to be off and we should understand why link use is unstable.

Yep, this is certainly expected for some use cases with sessions. My point was just that we may want to fix this across the board rather than special casing sessions.

**Comment by jsquire** [comment] 2021-07-30 18:58
> Yep, this is certainly expected for some use cases with sessions.

Sorry;  I overlooked your earlier comment that said exactly that.  😄 

> My point was just that we may want to fix this across the board rather than special casing sessions.

Agreed.

> Imagine someone is just creating a ton of EH producer clients with the same connection - should we reuse tokens in that case?

Likely; though that's an unusual scenario since each Event Hubs client type has it's own connection by default.

**Comment by JoshLove-msft** [comment] 2021-07-30 19:00
> Likely; though that's an unusual scenario since each Event Hubs client type has it's own connection by default.

Fair point, but from a maintenance perspective I would sleep easier at night if we had a common strategy here between both services - it would help surface bugs quicker and avoid forking our behavior.

**Comment by Mortana89** [comment] 2021-07-30 19:04
For what it's worth, I've collected the relevant pieces of code (skipped some stuff), perhaps it might have to do with how we do stuff, so thought I'd share;
https://gist.github.com/Mortana89/407ccef8ffc429989a097391be660270

**Comment by jsquire** [comment] 2021-07-30 19:16
> Fair point, but from a maintenance perspective I would sleep easier at night if we had a common strategy here between both services - it would help surface bugs quicker and avoid forking our behavior.

Also fair.   It should be a small surface area and low-risk fix.   I'll take a peek at it early next week for both.

**Comment by jsquire** [comment] 2021-07-30 19:16
> For what it's worth, I've collected the relevant pieces of code (skipped some stuff), perhaps it might have to do with how we do stuff, so thought I'd share;
> https://gist.github.com/Mortana89/407ccef8ffc429989a097391be660270

Thanks, @Mortana89!

**Comment by Mortana89** [comment] 2021-08-06 09:22
Hi, is there any ETA for this?
It's blocking our production release as it causes our instances to max process 5 unique sessions in total per second, while we have 20+ instances processing easily 100 sessions each in parallel. As a result, most of the messages will go to the deadletter with a max delivery count of 10.
As a last resort we could revert to using a connection string authentication, but I like to prevent this if possible for compliance reasons.

Thanks!

**Comment by jsquire** [comment] 2021-08-06 13:25
Hi @Mortana89.   We've got an approach that we're comfortable with and the changes are in-progress.   Because this impacts a critical path of the SDK, we'll need to do a full validation pass of long-running stress tests before releasing.  

This won't be complete in time for our August release cycle.  For Service Bus, I'll defer to @JoshLove-msft on potential release timing.  For Event Hubs, these changes will be part of our September release.

**Comment by JoshLove-msft** [comment] 2021-08-06 17:13
> This won't be complete in time for our August release cycle. For Service Bus, I'll defer to @JoshLove-msft on potential release timing. For Event Hubs, these changes will be part of our September release.

I think we will do the same for Service Bus.

**Comment by jsquire** [comment] 2021-08-16 19:20
Closing this out;  the fix has been merged in and will be included in the next release cycle.

**Closed by jsquire** 2021-08-16 19:20 UTC
Labels: Service Bus, Client, customer-reported, bug, needs-team-attention
