### ISSUE TITLE
[BUG][STORAGE]BlobSasBuilder does not handle signed identifiers correctly.

### ISSUE THREAD

**Issue by richard-zang** [Azure/azure-sdk-for-net#8725] opened 2019-11-11 16:54 UTC
**Describe the bug**
BlobSasBuilder states "[This field must be omitted if it has been specified in an associated stored access policy.](https://docs.microsoft.com/en-us/dotnet/api/azure.storage.sas.blobsasbuilder?view=azure-dotnet)" If I do not specify the ExpiresOn parameter, I get an exception "SAS is missing required parameter: ExpiresOn"

***Exception or Stack Trace***
System.InvalidOperationException
  HResult=0x80131509
  Message=SAS is missing required parameter: ExpiresOn
  Source=Azure.Storage.Blobs
  StackTrace:
   at Azure.Storage.Sas.BlobSasBuilder.EnsureState()
   at Azure.Storage.Sas.BlobSasBuilder.ToSasQueryParameters(StorageSharedKeyCredential sharedKeyCredential)
   at ConsoleApp5.Program.Main(String[] args) in C:\Users\rizang\source\repos\ConsoleApp5\ConsoleApp5\Program.cs:line 27

**To Reproduce**
Create BlobSasBuilder object.
Fill in the required information and attempt to generate a sas.

***Code Snippet***
var builder = new BlobSasBuilder
            {
                Identifier = "backup",
                BlobContainerName = "richard",
                Protocol = SasProtocol.Https,
                //ExpiresOn = DateTimeOffset.MaxValue,
                Resource = "c",
                Version = "2019-07-07"
            };
builder.SetPermissions(BlobAccountSasPermissions.Read | BlobAccountSasPermissions.Write);
string sas = builder.ToSasQueryParameters(cred).ToString();

**Expected behavior**
No exception should be thrown if the Identifier parameter is specified. It should generate the sas using the signed identifier and exclude the Expiration info.

**Screenshots**

**Setup (please complete the following information):**
 - OS: Windows
 - IDE : Visual Studio 2019
 - Version of the Library used : 12

**Additional context**
n/a

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by dwnz1** [comment] 2020-01-07 22:06
Are there any workarounds for this? The BlobSasBuilder doesn't not appear to be using the Identifier from what I can see (if I specify an ExpiresOn value to prevent the reported error, it is using the specified ExpiresOn value, and not the expiry date from the policy specified in the Identifier value).

**Comment by seanmcc-msft** [comment] 2020-01-10 22:31
Duplicate of https://github.com/Azure/azure-sdk-for-net/issues/8840.  We'll address this soon.

**Closed by seanmcc-msft** 2020-01-10 22:31 UTC
Labels: Client, Storage, customer-reported
