### ISSUE TITLE
[Flaky test] ReceiverCannotReadWhenClosed

### ISSUE THREAD

**Issue by pakrym** [Azure/azure-sdk-for-net#17180] opened 2020-11-24 17:48 UTC
```
Error message
Expected: instance of <Azure.Messaging.EventHubs.EventHubsException> and property Reason equal to ClientClosed
But was:  no exception thrown


Stack trace
   at Azure.Messaging.EventHubs.Tests.PartitionReceiverLiveTests.ReceiverCannotReadWhenClosed() in D:\a\1\s\sdk\eventhub\Azure.Messaging.EventHubs\tests\Primitives\PartitionReceiverLiveTests.cs:line 893
```

**Comment by jsquire** [comment] 2020-11-24 20:45
Fix for this is part of the set in [#17115](https://github.com/Azure/azure-sdk-for-net/pull/17115) that'll be moved over once I uncover the root cause of the unrelated hang.

**Comment by jsquire** [comment] 2020-12-03 21:08
There was a fix for this included in #17261

**Closed** 2020-12-03 21:07 UTC
Labels: Client, Event Hubs, test-reliability
