### ISSUE TITLE
[AppConfig] Support for configuration snapshot

### ISSUE THREAD

**Issue by ronniegeraghty** [Azure/azure-sdk-for-net#32042] opened 2022-10-26 20:32 UTC
### Library name

Azure.Data.AppConfiguration

### Please describe the feature.

App Config customers can use SDK to use the new configuration snapshot feature.

**Comment by jsquire** [comment] 2022-10-26 21:27
Duplicate of #32008

**Closed by jsquire** 2022-10-26 21:27 UTC
Labels: Client, App Configuration
