### ISSUE TITLE
GetWindowsVersionStringInternal  Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by ngcdev** [Azure/azure-sdk-for-net#26368] opened 2022-01-14 20:55 UTC
Hello,

I was following the instructions here https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/identity/Azure.Identity/README.md to use Azure Key Vault in my program, particularly using the "Service Principal with Secret". I got everything setup (registered the app, got a secret, granted access in key vault to the app, setup the environment variables), but when I run my code:
```
string keyVaultUrl = ".... key vault URL here ...";
var client = new SecretClient(new Uri(keyVaultUrl), new DefaultAzureCredential());
var kvresult = await Client.GetSecretAsync("secretname");
```
I get the following error (I'm running under Ubuntu with Mono and using .NET Framework 4.8 in my project, because that's the version of the system where I need to implement this):
```
Azure.Identity.AuthenticationFailedException: ClientSecretCredential authentication failed: Object reference not set to an instance of an object ---> System.NullReferenceException: Object reference not set to an instance of an object
  at Microsoft.Identity.Client.Platforms.Features.DesktopOs.DesktopOsHelper.GetWindowsVersionStringInternal () [0x0000f] in <bf76092abc204c3b87b8ffb18ff15aa1>:0 
  at Microsoft.Identity.Client.Platforms.Features.DesktopOs.DesktopOsHelper+<>c.<.cctor>b__16_2 () [0x00000] in <bf76092abc204c3b87b8ffb18ff15aa1>:0 
  at System.Lazy`1[T].ViaFactory (System.Threading.LazyThreadSafetyMode mode) [0x00043] in <533173d24dae460899d2b10975534bb0>:0 
  at System.Lazy`1[T].ExecutionAndPublication (System.LazyHelper executionAndPublication, System.Boolean useDefaultConstructor) [0x00022] in <533173d24dae460899d2b10975534bb0>:0 
  at System.Lazy`1[T].CreateValue () [0x00074] in <533173d24dae460899d2b10975534bb0>:0 
  at System.Lazy`1[T].get_Value () [0x0000a] in <533173d24dae460899d2b10975534bb0>:0 
  at Microsoft.Identity.Client.Platforms.Features.DesktopOs.DesktopOsHelper.GetWindowsVersionString () [0x00000] in <bf76092abc204c3b87b8ffb18ff15aa1>:0 
  at Microsoft.Identity.Client.Platforms.net45.NetDesktopPlatformProxy.InternalGetOperatingSystem () [0x00000] in <bf76092abc204c3b87b8ffb18ff15aa1>:0 
  at System.Lazy`1[T].ViaFactory (System.Threading.LazyThreadSafetyMode mode) [0x00043] in <533173d24dae460899d2b10975534bb0>:0 
  at System.Lazy`1[T].ExecutionAndPublication (System.LazyHelper executionAndPublication, System.Boolean useDefaultConstructor) [0x00022] in <533173d24dae460899d2b10975534bb0>:0 
  at System.Lazy`1[T].CreateValue () [0x00074] in <533173d24dae460899d2b10975534bb0>:0 
  at System.Lazy`1[T].get_Value () [0x0000a] in <533173d24dae460899d2b10975534bb0>:0 
  at Microsoft.Identity.Client.PlatformsCommon.Shared.AbstractPlatformProxy.GetOperatingSystem () [0x00000] in <bf76092abc204c3b87b8ffb18ff15aa1>:0 
  at Microsoft.Identity.Client.Internal.MsalIdHelper.GetMsalIdParameters (Microsoft.Identity.Client.Core.ICoreLogger logger) [0x00057] in <bf76092abc204c3b87b8ffb18ff15aa1>:0 
  at Microsoft.Identity.Client.Internal.Logger.MsalLogger+<>c.<.cctor>b__44_2 () [0x00000] in <bf76092abc204c3b87b8ffb18ff15aa1>:0 
  at System.Lazy`1[T].ViaFactory (System.Threading.LazyThreadSafetyMode mode) [0x00043] in <533173d24dae460899d2b10975534bb0>:0 
  at System.Lazy`1[T].ExecutionAndPublication (System.LazyHelper executionAndPublication, System.Boolean useDefaultConstructor) [0x00022] in <533173d24dae460899d2b10975534bb0>:0 
  at System.Lazy`1[T].CreateValue () [0x00074] in <533173d24dae460899d2b10975534bb0>:0 
  at System.Lazy`1[T].get_Value () [0x0000a] in <533173d24dae460899d2b10975534bb0>:0 
  at Microsoft.Identity.Client.Internal.Logger.MsalLogger.Log (Microsoft.Identity.Client.LogLevel logLevel, System.String messageWithPii, System.String messageScrubbed) [0x00057] in <bf76092abc204c3b87b8ffb18ff15aa1>:0 
  at Microsoft.Identity.Client.Internal.Logger.MsalLogger.Info (System.String messageScrubbed) [0x00000] in <bf76092abc204c3b87b8ffb18ff15aa1>:0 
  at Microsoft.Identity.Client.ApiConfig.Executors.AbstractExecutor.CreateRequestContextAndLogVersionInfo (System.Guid correlationId, System.Threading.CancellationToken userCancellationToken) [0x00043] in <bf76092abc204c3b87b8ffb18ff15aa1>:0 
  at Microsoft.Identity.Client.ApiConfig.Executors.ConfidentialClientExecutor.ExecuteAsync (Microsoft.Identity.Client.ApiConfig.Parameters.AcquireTokenCommonParameters commonParameters, Microsoft.Identity.Client.ApiConfig.Parameters.AcquireTokenForClientParameters clientParameters, System.Threading.CancellationToken cancellationToken) [0x00020] in <bf76092abc204c3b87b8ffb18ff15aa1>:0 
  at Azure.Identity.AbstractAcquireTokenParameterBuilderExtensions.ExecuteAsync[T] (Microsoft.Identity.Client.AbstractAcquireTokenParameterBuilder`1[T] builder, System.Boolean async, System.Threading.CancellationToken cancellationToken) [0x00078] in <b1ff7d3abac2485b914a6579d21f78c2>:0 
  at Azure.Identity.MsalConfidentialClient.AcquireTokenForClientAsync (System.String[] scopes, System.String tenantId, System.Boolean async, System.Threading.CancellationToken cancellationToken) [0x00140] in <b1ff7d3abac2485b914a6579d21f78c2>:0 
  at Azure.Identity.ClientSecretCredential.GetTokenAsync (Azure.Core.TokenRequestContext requestContext, System.Threading.CancellationToken cancellationToken) [0x000c3] in <b1ff7d3abac2485b914a6579d21f78c2>:0 
   --- End of inner exception stack trace ---
  at Azure.Identity.CredentialDiagnosticScope.FailWrapAndThrow (System.Exception ex, System.String additionalMessage) [0x0001d] in <b1ff7d3abac2485b914a6579d21f78c2>:0 
  at Azure.Identity.ClientSecretCredential.GetTokenAsync (Azure.Core.TokenRequestContext requestContext, System.Threading.CancellationToken cancellationToken) [0x000ef] in <b1ff7d3abac2485b914a6579d21f78c2>:0 
  at Azure.Identity.EnvironmentCredential.GetTokenImplAsync (System.Boolean async, Azure.Core.TokenRequestContext requestContext, System.Threading.CancellationToken cancellationToken) [0x000d5] in <b1ff7d3abac2485b914a6579d21f78c2>:0 
  at Azure.Identity.CredentialDiagnosticScope.FailWrapAndThrow (System.Exception ex, System.String additionalMessage) [0x00018] in <b1ff7d3abac2485b914a6579d21f78c2>:0 
  at Azure.Identity.EnvironmentCredential.GetTokenImplAsync (System.Boolean async, Azure.Core.TokenRequestContext requestContext, System.Threading.CancellationToken cancellationToken) [0x0010d] in <b1ff7d3abac2485b914a6579d21f78c2>:0 
  at Azure.Identity.EnvironmentCredential.GetTokenAsync (Azure.Core.TokenRequestContext requestContext, System.Threading.CancellationToken cancellationToken) [0x0007d] in <b1ff7d3abac2485b914a6579d21f78c2>:0 
  at Azure.Identity.DefaultAzureCredential.GetTokenFromSourcesAsync (Azure.Core.TokenCredential[] sources, Azure.Core.TokenRequestContext requestContext, System.Boolean async, System.Threading.CancellationToken cancellationToken) [0x000aa] in <b1ff7d3abac2485b914a6579d21f78c2>:0 
  at Azure.Identity.DefaultAzureCredential.GetTokenImplAsync (System.Boolean async, Azure.Core.TokenRequestContext requestContext, System.Threading.CancellationToken cancellationToken) [0x001ed] in <b1ff7d3abac2485b914a6579d21f78c2>:0 
  at Azure.Identity.CredentialDiagnosticScope.FailWrapAndThrow (System.Exception ex, System.String additionalMessage) [0x00018] in <b1ff7d3abac2485b914a6579d21f78c2>:0 
  at Azure.Identity.DefaultAzureCredential.GetTokenImplAsync (System.Boolean async, Azure.Core.TokenRequestContext requestContext, System.Threading.CancellationToken cancellationToken) [0x00253] in <b1ff7d3abac2485b914a6579d21f78c2>:0 
  at Azure.Identity.DefaultAzureCredential.GetTokenAsync (Azure.Core.TokenRequestContext requestContext, System.Threading.CancellationToken cancellationToken) [0x0007d] in <b1ff7d3abac2485b914a6579d21f78c2>:0 
  at Azure.Core.Pipeline.BearerTokenAuthenticationPolicy+AccessTokenCache.GetHeaderValueFromCredentialAsync (Azure.Core.TokenRequestContext context, System.Boolean async, System.Threading.CancellationToken cancellationToken) [0x00092] in <056f6eea93f94d71966248c0a1937819>:0 
  at Azure.Core.Pipeline.BearerTokenAuthenticationPolicy+AccessTokenCache.GetHeaderValueAsync (Azure.Core.HttpMessage message, Azure.Core.TokenRequestContext context, System.Boolean async) [0x0024f] in <056f6eea93f94d71966248c0a1937819>:0 
  at Azure.Core.Pipeline.BearerTokenAuthenticationPolicy+AccessTokenCache.GetHeaderValueAsync (Azure.Core.HttpMessage message, Azure.Core.TokenRequestContext context, System.Boolean async) [0x003d0] in <056f6eea93f94d71966248c0a1937819>:0 
  at Azure.Core.Pipeline.BearerTokenAuthenticationPolicy.AuthenticateAndAuthorizeRequestAsync (Azure.Core.HttpMessage message, Azure.Core.TokenRequestContext context) [0x00082] in <056f6eea93f94d71966248c0a1937819>:0 
  at Azure.Security.KeyVault.ChallengeBasedAuthenticationPolicy.AuthorizeRequestOnChallengeAsyncInternal (Azure.Core.HttpMessage message, System.Boolean async) [0x0018b] in <cf13f41e36fd4a94b87ece865a0bbfd5>:0 
  at Azure.Core.Pipeline.BearerTokenAuthenticationPolicy.ProcessAsync (Azure.Core.HttpMessage message, System.ReadOnlyMemory`1[T] pipeline, System.Boolean async) [0x0020e] in <056f6eea93f94d71966248c0a1937819>:0 
  at Azure.Core.Pipeline.RedirectPolicy.ProcessAsync (Azure.Core.HttpMessage message, System.ReadOnlyMemory`1[T] pipeline, System.Boolean async) [0x00090] in <056f6eea93f94d71966248c0a1937819>:0 
  at Azure.Core.Pipeline.RetryPolicy.ProcessAsync (Azure.Core.HttpMessage message, System.ReadOnlyMemory`1[T] pipeline, System.Boolean async) [0x000b4] in <056f6eea93f94d71966248c0a1937819>:0 
  at Azure.Core.Pipeline.RetryPolicy.ProcessAsync (Azure.Core.HttpMessage message, System.ReadOnlyMemory`1[T] pipeline, System.Boolean async) [0x00193] in <056f6eea93f94d71966248c0a1937819>:0 
  at Azure.Core.Pipeline.HttpPipeline.SendRequestAsync (Azure.Core.Request request, System.Threading.CancellationToken cancellationToken) [0x00093] in <056f6eea93f94d71966248c0a1937819>:0 
  at Azure.Security.KeyVault.KeyVaultPipeline.SendRequestAsync (Azure.Core.Request request, System.Threading.CancellationToken cancellationToken) [0x0008e] in <cf13f41e36fd4a94b87ece865a0bbfd5>:0 
  at Azure.Security.KeyVault.KeyVaultPipeline.SendRequestAsync[TResult] (Azure.Core.RequestMethod method, System.Func`1[TResult] resultFactory, System.Threading.CancellationToken cancellationToken, System.String[] path) [0x0009a] in <cf13f41e36fd4a94b87ece865a0bbfd5>:0 
  at Azure.Security.KeyVault.Secrets.SecretClient.GetSecretAsync (System.String name, System.String version, System.Threading.CancellationToken cancellationToken) [0x00131] in <cf13f41e36fd4a94b87ece865a0bbfd5>:0
```
Any help will be appreciated.
Thanks!

**Comment by jsquire** [comment] 2022-01-14 21:06
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by christothes** [comment] 2022-01-14 21:20
Hi @ngcdev 
What versions of `Azure.Identity` and `Azure.Security.KeyVault.Secrets` are you using? Does it reproduce with the latest versions if you are not already using them?

**Comment by ngcdev** [comment] 2022-01-18 14:01
Hello @christothes 
I'm using version 4.2.0 (I believe that's the latest at this time)
Thanks

**Comment by christothes** [comment] 2022-01-20 22:17
Are you able to reproduce this consistently in a stand-alone simple application? The sample code in the description is a common scenario, and we've never seen this specific issue before.

**Comment by ngcdev** [comment] 2022-01-20 22:43
Thanks @christothes  for responding. Yes, I can replicate it in a simple application. I'm pasting the exact code that I'm using below.

Notice: I'm running under Ubuntu, using Mono and .Net Framework 4.8. It seems like the problem happens when this method:
`Microsoft.Identity.Client.Platforms.net45.NetDesktopPlatformProxy.InternalGetOperatingSystem` is trying to figure out the OS (Since I'm running in Linux, that could be a problem)

In production this will run under Windows, but the for integration tests, we will be running them with NUnit-console under Linux, and that's why I'm testing it in Ubuntu.

Actual code that I'm using:
```
using System;
using Azure.Security.KeyVault.Secrets;
using Azure.Identity;
using System.Threading.Tasks;

namespace TestSecrets
{
	class MainClass
	{
		public static void Main(string[] args)
		{
			MainRun().GetAwaiter().GetResult();
		}

		public static async Task MainRun()
		{
			string keyVaultUrl = "https://<account here>.vault.azure.net/";

			// Using DeafultAzureCredentials with env vars for:
			// AZURE_CLIENT_ID, AZURE_TENANT_ID and AZURE_CLIENT_SECRET 
			var client = new SecretClient(new Uri(keyVaultUrl), new DefaultAzureCredential());

			var kvresult = await client.GetSecretAsync("abc-secret");

			Console.WriteLine(kvresult.Value);
		}
	}
}
```

**Comment by christothes** [comment] 2022-01-20 23:03
OK, thanks. This seems like it could be an issue with the underlying MSAL library. I'll do some investigation and update the issue when I have some more information.

**Comment by bgavrilMS** [comment] 2022-01-21 09:55
Oh, MONO is a bit of a pain :(. Is it possible to run via .NET Core which natively supports Mac and Linux?

**Comment by ngcdev** [comment] 2022-01-21 14:33
Ah that's a good idea. I only need the integration tests to be executed under Linux, and I know I can use the .Net Framework 4.8 libraries from core. I can give that a try. I will just make sure that the current efforts do work in Windows (I'm almost 99.9% certain they will)
Yes, regarding Mono. In the past, I had to re-implement some deep down properties or methods that were missing in Mono (related to  SQL transactions and handling of table parameters), because we needed them for the testing portion of it. Using .net core for testing seems like a better approach.

**Comment by christothes** [comment] 2022-01-21 15:14
@ngcdev would you mind creating an issue for this over in the MSAL repo here?: 

https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues

**Comment by ngcdev** [comment] 2022-01-21 15:15
Will do!

**Comment by christothes** [comment] 2022-01-21 15:18
Thanks - please reference this issue when you do so that they will be linked. I'm going to close this issue for now, since there appears to be nothing more we can do from the Azure.Identity perspective.

**Closed by christothes** 2022-01-21 15:18 UTC
Labels: Client, Azure.Identity, customer-reported, question, needs-team-attention

**Comment by ngcdev** [comment] 2022-01-21 17:47
Final comment: Did the integration test in .Net Core (5.0) and everything worked fine from an Ubuntu machine. Thanks for the quick responses!
