### ISSUE TITLE
[Text Analytics]AnalyzeHealthcareEntitiesPagination failing in nightly runs

### ISSUE THREAD

**Issue by Menghua1** [Azure/azure-sdk-for-net#34529] opened 2023-02-24 06:40 UTC
Text Analytics nightly test runs are failing with:

> Error message
> Azure.RequestFailedException : Failed to process task after several retry
> Status: 200 (OK)
> ErrorCode: InternalServerError
> 
> Additional Information:
> Target: #/tasks/items/0
> error-0: InternalServerError: Failed to process task after several retry
> 
> Content:
> {"jobId":"33819e2d-6d67-473a-aa85-5ebaaabed9e5","lastUpdatedDateTime":"2023-02-24T03:01:14Z","createdDateTime":"2023-02-24T03:01:11Z","expirationDateTime":"2023-02-25T03:01:11Z","status":"failed","errors":[{"code":"InternalServerError","message":"Failed to process task after several retry","target":"#/tasks/items/0"}],"tasks":{"completed":0,"failed":1,"inProgress":0,"total":1,"items":[{"kind":"HealthcareLROResults","lastUpdateDateTime":"2023-02-24T03:01:14.6783737Z","status":"failed"}]}}
> 
> Headers:
> x-envoy-upstream-service-time: 13
> apim-request-id: 0e031e6e-e06e-467e-81f1-7fcf598ace30
> Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
> X-Content-Type-Options: nosniff
> x-ms-region: REDACTED
> Date: Fri, 24 Feb 2023 03:01:14 GMT
> Content-Length: 492
> Content-Type: application/json; charset=utf-8
> 
> Data:
> Target: #/tasks/items/0
> error-0: InternalServerError: Failed to process task after several retry
> 
> 
> Stack trace
>    at Azure.Core.OperationInternal`1.GetResponseFromState(OperationState`1 state) in /Users/runner/work/1/s/sdk/core/Azure.Core/src/Shared/OperationInternalOfT.cs:line 289
>    at Azure.Core.OperationInternal`1.UpdateStatusAsync(Boolean async, CancellationToken cancellationToken)
>    at Azure.Core.OperationInternalBase.UpdateStatusAsync(CancellationToken cancellationToken) in /Users/runner/work/1/s/sdk/core/Azure.Core/src/Shared/OperationInternalBase.cs:line 87
>    at Azure.Core.OperationPoller.WaitForCompletionAsync(Boolean async, OperationInternalBase operation, Nullable`1 suggestedInterval, CancellationToken cancellationToken) in /Users/runner/work/1/s/sdk/core/Azure.Core/src/Shared/OperationPoller.cs:line 79
>    at Azure.Core.OperationInternalBase.WaitForCompletionResponseAsync(Boolean async, Nullable`1 pollingInterval, String scopeName, CancellationToken cancellationToken) in /Users/runner/work/1/s/sdk/core/Azure.Core/src/Shared/OperationInternalBase.cs:line 202
>    at Azure.Core.OperationInternal`1.WaitForCompletionAsync(Boolean async, Nullable`1 pollingInterval, CancellationToken cancellationToken) in /Users/runner/work/1/s/sdk/core/Azure.Core/src/Shared/OperationInternalOfT.cs:line 242
>    at Azure.Core.OperationInternal`1.WaitForCompletionAsync(CancellationToken cancellationToken) in /Users/runner/work/1/s/sdk/core/Azure.Core/src/Shared/OperationInternalOfT.cs:line 177
>    at Azure.AI.TextAnalytics.AnalyzeHealthcareEntitiesOperation.WaitForCompletionAsync(CancellationToken cancellationToken) in /Users/runner/work/1/s/sdk/textanalytics/Azure.AI.TextAnalytics/src/AnalyzeHealthcareEntitiesOperation.cs:line 186
>    at Azure.AI.TextAnalytics.Tests.AnalyzeHealthcareEntitiesTests.AnalyzeHealthcareEntitiesPagination() in /Users/runner/work/1/s/sdk/textanalytics/Azure.AI.TextAnalytics/tests/AnalyzeHealthcareEntitiesTests.cs:line 432
>    at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.BlockUntilCompleted()
>    at NUnit.Framework.Internal.MessagePumpStrategy.NoMessagePumpStrategy.WaitForCompletion(AwaitAdapter awaiter)
>    at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.<>c__DisplayClass1_0.<Execute>b__0()
>    at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.RunTestMethodInThreadAbortSafeZone(TestExecutionContext context, Action action)

For more details check here:

- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2587040&view=results

@jsquire for notification.

**Comment by joseharriaga** [comment] 2023-03-16 22:57
This is a duplicate of https://github.com/Azure/azure-sdk-for-net/issues/34970.

**Closed by joseharriaga** 2023-03-16 22:57 UTC
Labels: Client, Cognitive - Text Analytics, test-reliability
