### ISSUE TITLE
First paragraph overlaps

### ISSUE THREAD

**Issue by DARKinVADER** [Azure/azure-sdk-for-net#21219] opened 2021-05-20 05:58 UTC
The 1st paragraph might overlap with the right hand side menu on certain resolution.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 49ef87ea-4734-448d-1552-a996e5583c2c
* Version Independent ID: 8438093a-13c2-33c4-dede-9086c4fdf28c
* Content: [EventProcessorClient Class (Azure.Messaging.EventHubs) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/azure.messaging.eventhubs.eventprocessorclient?view=azure-dotnet)
* Content Source: [xml/Azure.Messaging.EventHubs/EventProcessorClient.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Azure.Messaging.EventHubs/EventProcessorClient.xml)
* Service: **azure**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jsquire** [comment] 2021-05-20 13:09
Hi @DARKinVADER.   Thank you for reaching out and we regret that you're experiencing difficulties.  Because this issue is related to rendering for the MS Docs site and not the API documentation content, I've transferred this over to the MS Docs repository as [#75621](https://github.com/MicrosoftDocs/azure-docs/issues/75621) so the folks best able to help are aware.

As a side note, I wasn't able to reproduce the behavior that you're experiencing.   You may want to consider updating the MS Docs issue with some additional context such as the browser/device that you're using and what resolution you're seeing this with.

I'm going to go ahead and close this out; please feel free to reopen if you believe it was transferred in error.

**Closed by jsquire** 2021-05-20 13:09 UTC
Labels: customer-reported, needs-triage, question
