### ISSUE TITLE
[Flaky test] Azure.Storage.Blobs.Test.BlobClientTests(True,V2019_12_12).UploadStreamAsync_SmallBlobs(30720)

### ISSUE THREAD

**Issue by pakrym** [Azure/azure-sdk-for-net#13415] opened 2020-07-13 16:51 UTC
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=455838&view=ms.vss-test-web.build-test-results-tab&runId=11938288&resultId=110864&paneView=debug

```
Error message
System.InvalidOperationException : Collection was modified; enumeration operation may not execute.


Stack trace
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at System.Linq.Enumerable.Sum[TSource](IEnumerable`1 source, Func`2 selector)
   at Azure.Storage.PartitionedUploader`2.UploadInParallelAsync(Stream content, Nullable`1 contentLength, Int64 blockSize, TServiceSpecificArgs args, IProgress`1 progressHandler, CancellationToken cancellationToken) in D:\a\1\s\sdk\storage\Azure.Storage.Common\src\Shared\PartitionedUploader.cs:line 372
   at Azure.Storage.PartitionedUploader`2.UploadInParallelAsync(Stream content, Nullable`1 contentLength, Int64 blockSize, TServiceSpecificArgs args, IProgress`1 progressHandler, CancellationToken cancellationToken) in D:\a\1\s\sdk\storage\Azure.Storage.Common\src\Shared\PartitionedUploader.cs:line 353
   at Azure.Storage.PartitionedUploader`2.UploadInternal(Stream content, TServiceSpecificArgs args, IProgress`1 progressHandler, Boolean async, CancellationToken cancellationToken)
   at Azure.Storage.Blobs.BlobClient.StagedUploadInternal(Stream content, BlobUploadOptions options, Boolean async, CancellationToken cancellationToken) in D:\a\1\s\sdk\storage\Azure.Storage.Blobs\src\BlobClient.cs:line 1196
   at Azure.Storage.Blobs.Test.BlobClientTests.UploadStreamAndVerify(Int64 size, StorageTransferOptions transferOptions) in D:\a\1\s\sdk\storage\Azure.Storage.Blobs\tests\BlobClientTests.cs:line 591
   at Azure.Storage.Blobs.Test.BlobClientTests.UploadStreamAndVerify(Int64 size, StorageTransferOptions transferOptions) in D:\a\1\s\sdk\storage\Azure.Storage.Blobs\tests\BlobClientTests.cs:line 599
   at Azure.Storage.Blobs.Test.BlobClientTests.UploadStreamAsync_SmallBlobs(Int64 size) in D:\a\1\s\sdk\storage\Azure.Storage.Blobs\tests\BlobClientTests.cs:line 685
   at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.GetResult() in D:\a\1\s\src\NUnitFramework\framework\Internal\TaskAwaitAdapter.cs:line 99
   at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke) in D:\a\1\s\src\NUnitFramework\framework\Internal\AsyncToSyncAdapter.cs:line 60
   at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context) in D:\a\1\s\src\NUnitFramework\framework\Internal\Commands\TestMethodCommand.cs:line 64
   at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.<>c__DisplayClass1_0.<Execute>b__0() in D:\a\1\s\src\NUnitFramework\framework\Internal\Commands\BeforeAndAfterTestCommand.cs:line 58
   at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.RunTestMethodInThreadAbortSafeZone(TestExecutionContext context, Action action) in D:\a\1\s\src\NUnitFramework\framework\Internal\Commands\BeforeAndAfterTestCommand.cs:line 73

```

**Comment by tg-msft** [comment] 2020-07-13 22:16
This is a duplicate of https://github.com/Azure/azure-sdk-for-net/issues/13221.

**Closed by tg-msft** 2020-07-13 22:16 UTC
Labels: Storage, Test Debt
