### ISSUE TITLE
Microsoft.Azure.Management.Storage CloudException: The 'Authorization' header is missing

### ISSUE THREAD

**Issue by tyjen** [Azure/azure-sdk-for-net#4103] opened 2018-03-02 23:52 UTC
I'm trying to create storage accounts programatically using the Microsoft.Azure.Management.Storage package along with a subscription management certificate, however I'm getting strange issues with authentication that leads me to believe the package is broken.

Here's how I'm trying to create the account:
```
var storageClient = new StorageManagementClient(new CertificateCloudCredentials(subscriptionId, managementCert));

var storageParams = new StorageAccountCreateParameters(accountType, location);
var createResult = await storageClient.StorageAccounts.CreateAsync(resourceGroup, accountName, storageParams);
```

I get the following error: **Hyak.Common.CloudException: AuthenticationFailed: Authentication failed. The 'Authorization' header is missing.**

StackTrace:
```
"One or more errors occurred." ---> System.AggregateException: One or more errors occurred. ---> Hyak.Common.CloudException: AuthenticationFailed: Authentication failed. The 'Authorization' header is missing.
   at Microsoft.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at Microsoft.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccess(Task task)
   at Microsoft.Azure.Management.Storage.StorageAccountOperations.<CreateAsync>d__29.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
```

I've triple checked that my management cert is the correct one. Any ideas as to why I'm getting this? I would expect if I used the incorrect certificate I would get an access denied error. The error above leads me to believe the SDK didn't even include an auth header for some reason.

**Comment by blueww** [comment] 2018-05-25 02:41
@tyjen 

Which version of SDK do you use? 

Do you might to upgrade toe the latest version of SDK and try again? https://www.nuget.org/packages/Microsoft.Azure.Management.Storage/7.2.0-preview

**Comment by Porges** [comment] 2018-07-02 05:11
I also got this error. I then updated to the latest SDK (8.0-preview) and got a very similar error:

```
Microsoft.Rest.Azure.CloudException: 'Authentication failed. The 'Authorization' header is missing.'
```

**Comment by Porges** [comment] 2018-07-04 00:09
Turns out this isn't meant to work. The error message could be greatly improved...

**Comment by joymon** [comment] 2018-07-31 17:52
@Porges ,@tyjen
You may try obtaining a token based cloud credentials from the certificate. We are using AD App to do operations which has certificate associated. Below goes the code for HDInsightManagementClient. It may work for your scenario too.
`        internal static async Task<HDInsightManagementClient> Get(string subscriptionGuid)
        {
            string token = await TokenFactory.GetAccessTokenUsingADAppCertificate("https://management.core.windows.net/");
            TokenCloudCredentials tcc = new TokenCloudCredentials(subscriptionGuid, token);
            return new HDInsightManagementClient(tcc);
        }
internal class TokenFactory
    {
        private static AuthenticationContext context = new AuthenticationContext($"https://login.windows.net/{Configurations.TenantId}"); //Tenant Id from portal
        private static Lazy<IClientAssertionCertificate> _certProvider = new Lazy<IClientAssertionCertificate>(() => GetClientAssertionCertificate(Configurations.AzureADApplicationId));
        internal static async Task<string> GetAccessTokenUsingADAppCertificate(string resource)
        {
            var result = await context.AcquireTokenAsync(resource, _certProvider.Value);
            return result.AccessToken;
        }
        internal static IClientAssertionCertificate GetClientAssertionCertificate(string clientId)
        {
            string certIssuerName = Configurations.GetConfigValueByKey("CertificateIssuerName");
            X509Certificate2 clientAssertionCertPfx = CertificateHelper.FindCertificateByIssuerName(certIssuerName);
            return new ClientAssertionCertificate(clientId, clientAssertionCertPfx);
        }
    }`

**Comment by blueww** [comment] 2018-10-08 06:31
@tyjen , @Porges 
Is your problem resolved? Do you still need any assistance from our team?

**Comment by Porges** [comment] 2018-10-08 19:42
Yes, I believe the library should error-out early with an informative message. Passing `CertificateCredentials` to the `StorageManagementClient` simply can't work.

**Comment by blueww** [comment] 2018-10-09 01:54
@Porges 
Thanks for the reply!
Would you please confirm if your problem is resolved by "obtaining a token based cloud credentials from the certificate" ?

And since the code is auto generated by autorest from swagger, I will contact autorest team to see if they have any idea on this kind of issue, after the root cause if confirmed.

**Comment by blueww** [comment] 2019-01-22 11:33
@Porges 
I will close the issue since not hear from you for a long time.
Feel free to contact us if you need more support.

**Comment by dsgouda** [comment] 2019-04-24 21:37
Closing per @blueww 's comments

**Closed by dsgouda** 2019-04-24 21:37 UTC
Labels: Service Attention, Storage
