### ISSUE TITLE
[BUG] Missing westus3 in Azure.Core.AzureLocation

### ISSUE THREAD

**Issue by jrcuff** [Azure/azure-sdk-for-net#32975] opened 2022-12-08 19:57 UTC
### Library name and version

Azure.ResourceManager 1.3.2

### Describe the bug

westus3 is missing from the `Azure.Core.AzureLocation` struct.

### Expected behavior

```csharp
/// <summary>
/// Public cloud location for West US 3.
/// </summary>
public static AzureLocation WestUS3 { get; } = CreateStaticReference("westus3", "West US 3");
```

### Actual behavior

The AzureLocation is missing.

### Reproduction Steps

No steps.

**Comment by jsquire** [comment] 2022-12-08 20:03
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by ArthurMa1978** [comment] 2022-12-14 08:46
@AlexanderSher can you add this new location?

**Comment by jnlycklama** [comment] 2023-02-21 23:42
+1 on this issue. `SwedenCentral` is missing as well. @AlexanderSher @ArthurMa1978 

We are trying to migrate off of Fluent SDK, which has been deprecated: https://www.nuget.org/packages/Microsoft.Azure.Management.ResourceManager.Fluent. Fluent supports WestUS3 and SwedenCentral https://learn.microsoft.com/en-us/dotnet/api/microsoft.azure.management.resourcemanager.fluent.core.region?view=azure-dotnet

**Comment by jsquire** [comment] 2023-11-20 20:17
This has been confirmed to have been added since this issue was last updated.  Resolving.

**Closed by jsquire** 2023-11-20 20:17 UTC
Labels: customer-reported, question, ARM - Core, needs-team-attention
