### ISSUE TITLE
[BUG] Azure.Storage.Blobs namespace conflicts with Microsoft.Azure.* packages.

### ISSUE THREAD

**Issue by nschuessler** [Azure/azure-sdk-for-net#20778] opened 2021-04-30 17:14 UTC
**Describe the bug**
When adding `Azure.Storage.Blobs` nuget to a project and adding 'using Azure.Storage.Blobs' it causes a build break.

**Expected behavior**
There should be no build break, and the IDE should be able to resolve the issue with the namespaces.

**Actual behavior (include Exception or Stack Trace)**
The IDE only suggests fully qualifying the type, which doesn't help (i.e. Azure.Storage.Blobs.BlobClient)

**To Reproduce**
Steps to reproduce the behavior (include a code snippet, screenshot, or any additional information that might help us reproduce the issue)

1. Create a new .Net 50 console app
2. Add Microsoft.Azure.Services.AppAuthentication
3. Add Azure.Storage.Blobs
4. Add 'using Azure.Storage.Blobs' somewhere in the project.

It won't build.
The fix: You have to put `using global::Azure.Storage.Blobs` to fix the problem. 
This not even close to obvious.

Feedback: This whole creating a nuget package that has a lifetime of a few months and obsoleting it and then coming up with a new design is very frustrating. We've moved from WindowsAzure.Storage to Microsoft.WIndowsAzure.Storage to Microsoft.Azure.Storage.Blobs and now Azure.Storage.blobs

This is just crazy.  Stick with a naming scheme and use the .net framework and dependencies to determine the compatibilities. Maybe increment the version number by 10 when there is breaking change. It would be a lot easier that tracking a long train of obsolete packages suggesting upgrading to another obsolete package.

Also if you type 'BlobClient' into the IDE it suggests using "WindowsAzure.Storage" which is the oldest most obsolete package available.

**Environment:**
 - Name and version of the Library package used: [e.g. Azure.Storage.Blobs 12.8.3] 
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): [e.g. Azure AppService or Windows 10 .NET Framework 4.8]
 - IDE and version : [e.g. Visual Studio 16.3]

dotnet 5.0

**Comment by kasobol-msft** [comment] 2021-05-03 15:43
Duplicate of https://github.com/Azure/azure-sdk-for-net/issues/8169 . Please see discussion there.

**Closed by kasobol-msft** 2021-05-03 15:43 UTC
Labels: Client, Service Attention, Storage, customer-reported, needs-team-attention, question
