### ISSUE TITLE
[BUG] The resource type 'locations/databaseOperationResults' could not be found in the namespace 'Microsoft.Sql' for api version '2022-09-01'

### ISSUE THREAD

**Issue by czjlorenz** [Azure/azure-sdk-for-net#39799] opened 2023-11-07 12:40 UTC
### Library name and version

Azure.ResourceManager 1.8.1 or 1.8.0

### Describe the bug

When adding a resource tag to a SQL Azure database I am getting an exception about an unknown API version. The tag is actually written because just the wait for the operation to complete fails. Nonetheless the exception is an exception interrupting the program flow.

### Expected behavior

The resource tag is written without exception.

### Actual behavior

Azure.RequestFailedException: "The resource type 'locations/databaseOperationResults' could not be found in the namespace 'Microsoft.Sql' for api version '2022-09-01'. The supported api-versions are '2017-03-01-preview,2017-10-01-preview,2018-06-01-preview,2019-06-01-preview,2020-02-02-preview,2020-08-01-preview,2020-11-01-preview,2021-02-01-preview,2021-05-01-preview,2021-08-01-preview,2021-11-01,2021-11-01-preview,2022-02-01-preview,2022-05-01-preview,2022-08-01-preview,2022-11-01-preview,2023-02-01-preview,2023-05-01-preview'.
Status: 404 (Not Found)
ErrorCode: InvalidResourceType

Content:
{"error":{"code":"InvalidResourceType","message":"The resource type 'locations/databaseOperationResults' could not be found in the namespace 'Microsoft.Sql' for api version '2022-09-01'. The supported api-versions are '2017-03-01-preview,2017-10-01-preview,2018-06-01-preview,2019-06-01-preview,2020-02-02-preview,2020-08-01-preview,2020-11-01-preview,2021-02-01-preview,2021-05-01-preview,2021-08-01-preview,2021-11-01,2021-11-01-preview,2022-02-01-preview,2022-05-01-preview,2022-08-01-preview,2022-11-01-preview,2023-02-01-preview,2023-05-01-preview'."}}

Headers:
Cache-Control: no-cache
Pragma: no-cache
x-ms-failure-cause: REDACTED
x-ms-ratelimit-remaining-subscription-reads: REDACTED
x-ms-request-id: cb1bf479-fee4-43fe-9bc6-b601404ce2e9
x-ms-correlation-request-id: REDACTED
x-ms-routing-request-id: REDACTED
Strict-Transport-Security: REDACTED
X-Content-Type-Options: REDACTED
Date: Tue, 07 Nov 2023 12:24:10 GMT
Content-Type: application/json; charset=utf-8
Expires: -1
Content-Length: 557
"

### Reproduction Steps

Create a new Azure subscription. Add a SQL Azure elastic pool with service tier = Standard, 100 eDTUs and location "West Europe". Add a SQL Azure database the elastic pool with 10GB max storage. (not sure if the elastic pool is required, my database is part of an elastic pool)

Create a new C# command line application. Add nugets Azure.Identity-1.10.3 and Azure.ResourceManager-1.8.1.

Setup authentication for Azure.Identity.

Use the following code in the command line application replacing the placeholders with the value from your subscription and database.

```
using Azure.Core;
using Azure.Identity;
using Azure.ResourceManager;

var armClient = new ArmClient(new DefaultAzureCredential(), "<subscription_id>");
var sqlDatabaseResourceIdentifier = new ResourceIdentifier("/subscriptions/<subscription_id>/resourceGroups/<resource_group_name>/providers/Microsoft.Sql/servers/<sql_server_name>/databases/<sql_database_name>");
var databaseResource = armClient.GetGenericResource(sqlDatabaseResourceIdentifier);
databaseResource = await databaseResource.GetAsync();
await databaseResource.AddTagAsync("TestKey", "TestValue");
```

Run the application. Observe the exception thrown by the last line.

### Environment

```
C:\>dotnet --info
.NET SDK:
 Version:   7.0.403
 Commit:    142776d834

Runtime:
 OS Name:     Windows
 OS Version:  10.0.19045
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.403\

Host:
  Version:      7.0.13
  Architecture: x64
  Commit:       3f73a2f186
```

Visual Studio Version 17.7.6

**Comment by Frankd4** [comment] 2023-11-07 23:49
Hi @m-redding,

I also have a CX report this issue, I could reproduce this as well.

 az tag update --resource-id /subscriptions/1s9d4-bc2a-0000-0000-4cb19853gh6/resourceGroups/RG/providers/Microsoft.Sql/servers/srv-01/databases/database --operation merge --tags ApplicationOwner='test'
 
(InvalidResourceType) The resource type 'locations/databaseOperationResults' could not be found in the namespace 'Microsoft.Sql' for api version '2022-09-01'. The supported api-versions are '2017-03-01-preview,2017-10-01-preview,2018-06-01-preview,2019-06-01-preview,2020-02-02-preview,2020-08-01-preview,2020-11-01-preview,2021-02-01-preview,2021-05-01-preview,2021-08-01-preview,2021-11-01,2021-11-01-preview,2022-02-01-preview,2022-05-01-preview,2022-08-01-preview,2022-11-01-preview,2023-02-01-preview,2023-05-01-preview'.
Code: InvalidResourceType
Message: The resource type 'locations/databaseOperationResults' could not be found in the namespace 'Microsoft.Sql' for api version '2022-09-01'. The supported api-versions are '2017-03-01-preview,2017-10-01-preview,2018-06-01-preview,2019-06-01-preview,2020-02-02-preview,2020-08-01-preview,2020-11-01-preview,2021-02-01-preview,2021-05-01-preview,2021-08-01-preview,2021-11-01,2021-11-01-preview,2022-02-01-preview,2022-05-01-preview,2022-08-01-preview,2022-11-01-preview,2023-02-01-preview,2023-05-01-preview'.

**Comment by artkat** [comment] 2023-11-08 03:43
I have the same issue.

**Comment by Frankd4** [comment] 2023-11-09 21:33
Hi @m-redding 

Do you have any update on this ?

**Comment by vndtcskxc** [comment] 2023-11-09 23:06
I am also looking for an update on this. Any ETA?

**Comment by m-redding** [comment] 2023-11-10 14:15
Hi @Frankd4, I'm sorry that this is not an issue I can help with, but I have assigned someone who will be able to help.
cc/ @ArthurMa1978

**Comment by Frankd4** [comment] 2023-11-11 01:31
Thank you @m-redding. I hope @ArthurMa1978 can share some update on this.

**Comment by czjlorenz** [comment] 2023-11-13 09:34
FYI: Azure.ResourceManager 1.8.0 is affected as well.

**Comment by archerzz** [comment] 2023-11-14 02:14
This is a general issue in ARM tags API endpoint. Multiple customers have reported it. We need ARM team to take a look at this issue.

Here is what happened.
1. When the client updates tags of a resource, it sends a request like below:
> https://management.azure.com/subscriptions/{subscription_id}/resourceGroups/{test_resource_group}/providers/Microsoft.Compute/disks/{test_disk}/providers/Microsoft.Resources/tags/default?api-version=2022-09-01

The `api-version` is ARM's API version, since it's sent to ARM endpoint.

2. Back-end service returns the polling URL through `Location` response header.
> https://management.azure.com/subscriptions/{subscription_id}/tagsoperationresults?api-version=2022-09-01&$originalLocation={hashed_value}

3. The client sends request to the given URL to poll the status. And the error returns.

You can try to replace the `api-version` with the value in the error messages, and it won't work because the API versions in the error message are for custom services (e.g. SQL, Compute,...), not for ARM. It will be rejected instantly.

So, there is no much we can do on SDK sides. We need to ask ARM team to fix the issue. ARM need to preserve the `api-version` mapping between custom services and itself for each request, so that later on the polling requests can be correctly handled.

**Comment by Frankd4** [comment] 2023-11-14 02:43
Thank you @archerzz

**Comment by archerzz** [comment] 2023-11-14 07:14
By the way, a work-around is using the `Update` method of a resource, instead of `AddTag` method. They use different API which should by-pass this issue.

**Comment by Frankd4** [comment] 2023-11-14 09:28
Thanks @archerzz. I will update the CX

**Comment by czjlorenz** [comment] 2023-11-14 10:29
@archerzz Thank you for the workaround. The following code works for me.

using Azure;
using Azure.Core;
using Azure.Identity;
using Azure.ResourceManager;

var armClient = new ArmClient(new DefaultAzureCredential(), "<subscription_id>");
var sqlDatabaseResourceIdentifier = new ResourceIdentifier("/subscriptions/<subscription_id>/resourceGroups/<resource_group_name>/providers/Microsoft.Sql/servers/<sql_server_name>/databases/<sql_database_name>");
var databaseResource = armClient.GetGenericResource(sqlDatabaseResourceIdentifier);
databaseResource = await databaseResource.GetAsync();
databaseResource.Data.Tags["TestKey"] = "TestValue";
databaseResource.Update(WaitUntil.Completed, databaseResource.Data);

**Comment by am8448** [comment] 2023-11-15 10:26
I'm having this issue as well, but within Azure Front Door. I'm creating FD as and adding the tag simultaneously:
` az network front-door create \
  name $(frontDoorName) \
  resource-group $(resourceGroup) \
  backend-address '$(functionAppHostName)' \
  protocol Https \
  accepted-protocols Https \
  forwarding-protocol HttpsOnly \
  tags AcceptedException_frontdoor-H-005=true \
`

I get the error later when running:
`  $fdId = "/subscriptions/$(subscriptionId)/resourceGroups/$(resourceGroup)/providers/Microsoft.Network/frontdoors/$(frontDoorName)"
   az tag update --operation Delete --resource-id $fdId --tags AcceptedException_frontdoor-H-005=true`

This is breaking our builds. When can we expect a fix?

**Comment by chrisbuttacavoliadec** [comment] 2023-12-07 19:45
I get this issue when I run the following command with Azure CLI on a brand new SQL server + database:

```powershell
az tag update --resource-id $resource.id --operation merge --tags $tags
```

**Comment by freezeeedos** [comment] 2023-12-22 13:58
Hello,

Still encountering this issue trying to apply tags to a mysql server:

`az resource tag --tags tag1=val1 tag2=val2 --resource-group *** --name *** --resource-type Microsoft.DBforMySQL/servers`

**Comment by archerzz** [comment] 2023-12-25 07:54
> Hello,
> 
> Still encountering this issue trying to apply tags to a mysql server:
> 
> `az resource tag --tags tag1=val1 tag2=val2 --resource-group *** --name *** --resource-type Microsoft.DBforMySQL/servers`

@freezeeedos Can you try again? I tried and the update was successful.
![image](https://github.com/Azure/azure-sdk-for-net/assets/4516/1f5ca946-7e2c-40dd-8b9a-b102eee1086e)

**Comment by freezeeedos** [comment] 2024-01-04 09:30
@archerzz Hi, I'm still getting the error. I don't think everyone is affected in the same way. Microsoft support tells me they have reproduced the issue, and to wait

**Comment by archerzz** [comment] 2024-01-10 07:14
I'm closing this issue, since the generally the initial problem should have been fixed. If the issue still exists, feel free to create a ticket through Microsoft support. It's a server-side issue, so there is not much we can do in SDK.

**Closed by archerzz** 2024-01-10 07:14 UTC
Labels: SQL, ARM, Mgmt, customer-reported, question, ARM - Tags, needs-team-attention
