### ISSUE TITLE
Duplicate H1s Conflict for microsoft.azure.core.spatial-readme

### ISSUE THREAD

**Issue by v-alje** [Azure/azure-sdk-for-net#29200] opened 2022-06-08 21:39 UTC
The following articles created from readme files are using the same H1 title header. Docs reports warnings when there are two articles with the same H1 text. This is happening because both the preview and release versions of the Docs articles were imported from the same readme: sdk/core/Microsoft.Azure.Core.Spatial/README.md

https://github.com/Azure/azure-docs-sdk-dotnet/blob/main/api/overview/azure/microsoft.azure.core.spatial-readme-pre.md
https://github.com/Azure/azure-docs-sdk-dotnet/blob/main/api/overview/azure/microsoft.azure.core.spatial-readme.md

One solution would be to append something like (Preview) to the end of the H1 for the preview topic when imported to Docs.

**Comment by jsquire** [comment] 2022-06-09 13:53
Closing as a duplicate of #29204.

**Comment by sima-zhu** [comment] 2022-06-10 16:35
Addressed the issue. Closed.

**Closed by sima-zhu** 2022-06-10 16:35 UTC
Labels: Docs, Central-EngSys
