### ISSUE TITLE
[QUERY] Getting InvalidOperationException("The current instance does not have data, you must call Get first.") on PostgreSqlServerAdministratorResource.Data when calling PostgreSqlServerResource.GetPostgreSqlServerAdministrator()

### ISSUE THREAD

**Issue by alwynjohnlim** [Azure/azure-sdk-for-net#40561] opened 2023-12-04 22:36 UTC
### Library name and version

Azure.ResourceManager.PostgreSql 1.1.1.0

### Query/Question

Hi,

I am getting exception error when calling PostgreSqlServerResource.GetPostgreSqlServerAdministrator() below.
Upon checking, this seems like a bug? Can someone verify please.
![image](https://github.com/Azure/azure-sdk-for-net/assets/36021444/aa2178c5-1d0f-4227-b84d-24994c48e107)

GetPostgreSqlServerAdministrator() in the library calls the code below within the library.
![image](https://github.com/Azure/azure-sdk-for-net/assets/36021444/43ac62ea-d600-4969-9321-83d0ca64f482)

And the highlighted internal constructor below that is used does not set the HasData and _data unlike the other internal constructor.
![image](https://github.com/Azure/azure-sdk-for-net/assets/36021444/339bc8bb-30dc-4a75-8d07-cfe96d01c433)

Thus causing this exception to trigger when getting Data, which makes sense.
![image](https://github.com/Azure/azure-sdk-for-net/assets/36021444/246eb5d7-c6ab-4326-9380-4170406f0654)

So it seems like I need to use the Get/GetAsync() to get the Data basing from the error, but this is giving me exceptions too about missing ResourceType.
![image](https://github.com/Azure/azure-sdk-for-net/assets/36021444/33bec891-fe8d-4088-bff1-690cb55941dd)

Any thoughts? How should I get the Data?

Regards,
Alwyn

**Comment by jsquire** [comment] 2023-12-05 14:42
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by HarveyLink** [comment] 2023-12-25 07:45
Hi @alwynjohnlim , Thank you for using Azure SDK for .NET.
For the first question, yes, you will need another get to get the actual data, it's by design.
For the second question, we believe this is a service issue, the return `type` value is not a proper rsource type: `PostgreSQL.Server.PAL`, add service attention.

**Comment by ArthurMa1978** [comment] 2024-01-04 08:20
Hey @alwynjohnlim, thank you for reaching out to us about the Azure SDK for .NET. Unfortunately, this issue is related to the service side and not the SDK side, so we are not able to help you with it. Therefore, we are closing this issue for now. If you need more assistance, please [open an Azure support request](https://docs.microsoft.com/azure/azure-portal/supportability/how-to-create-azure-support-request). We apologize for any inconvenience this may cause you.

We value your feedback and we want to make sure that your problem is solved. If you think that we have misunderstood your issue or closed it incorrectly, please feel free to comment on this thread and reopen the issue. We will be happy to assist you further. Thank you for your understanding and cooperation.

**Closed by ArthurMa1978** 2024-01-04 08:20 UTC
Labels: PostgreSQL, Service Attention, Mgmt, customer-reported, question, needs-team-attention
