### ISSUE TITLE
Missing .csproj files in sdk/template

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-for-net#28616] opened 2022-05-09 22:32 UTC
The new dotnet new templates should have .csproj files for projects that need them e.g., under "src" and "tests". Anything within them can also be replaced by the .template.config/template.json file as the previous sdk/template did. `dotnet new azsdkdpg` should generate a working template even without the wrapper script (which can do more than a template can still).

**Comment by chunyu3** [comment] 2022-05-10 01:25
Hi @heaths Which .csproj files are missing? thanks. 
This is the one I generated by `dotnet new` https://github.com/chunyu3/azure-sdk-for-net/tree/TemplateSample/sdk/sample. 

Would you please tell me the steps you did so that I can reproduce it on mysite? Thanks

**Comment by heaths** [comment] 2022-05-11 22:23
With all the renames the previous PR showed, I was confused. The plan was that sdk/template/Azure.Template was the output of a separate directory that contained the .template.config directory and all files. But what I see here is you effectively made sdk/template/Azure.Template the template, which is what I had before. Correct?

**Comment by chunyu3** [comment] 2022-05-12 08:00
The parent folder of '.template.config' will the be entry folder for `dotnet new`. so we will install template via `sdk\template`. ( dotnet new -i sdk\template).

All the files and folders under `sdk\template` should copied to the generated sdk package except '.template.config'. But we need some placeholder files which I put them under `.content` and exclude `.content` in the template.json (that is .content directory will not be in SDK package).
As a result, the generated package will only contain the `Azure.Template` directory and some files will be replaced by the one in .content.

**Comment by heaths** [comment] 2022-05-13 20:47
It can work, but was not the original plan. If we were just going to keep the template rooted in sdk/template we didn't need all the placeholder files. As discussed very early on, content within the existing files can (and was, to a lesser extent you needed) be filtered out. I only had unconditional sample code included for just that purpose: sample code. Now sdk/template contains duplicate source for quite a few files and is harder to understand / maintain, IMO. This could be simplified if you go back to what I had originally and just condition out the implementations you don't want.

**Comment by chunyu3** [comment] 2022-05-18 08:21
Hi @heaths I will investigate how to use flags(see following) in files under sdk/template/Azure.Template and eliminate the contents between the flags when generate the starter package via template.

#region Azure_Template_GetSecretAsync

......
# region

Is above solution the one we want? Thanks

**Comment by heaths** [comment] 2022-05-23 23:47
Could you clarify? I'm not sure what you're asking.

My point was that we should either keep a completely different set of template files - which was the last plan we had discussed with @weshaggard - or use the src/Azure.Template files with content we don't want filtered out like how I had it before. Mixing the two methods is very confusing, hence this bug. Future maintainers not directly involved in these past discussions will probably be more confused.

**Comment by pallavit** [comment] 2023-12-19 19:29
@chunyu3 do we still use the template folder to generate the DPG SDKs?

**Comment by chunyu3** [comment] 2023-12-20 02:26
@pallavit  Yes, we still use this script to help customer to create DPG SDK folders for new services. And I think the issue is resolved.
We can close this.

**Closed** 2024-01-03 00:46 UTC
Labels: Client, Azure.Template
