### ISSUE TITLE
Azure.Storage.Files.Shares Readme issue

### ISSUE THREAD

**Issue by Tianyun-G** [Azure/azure-sdk-for-net#13635] opened 2020-07-22 06:46 UTC
1.
Section [link](https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/storage/Azure.Storage.Files.Shares#troubleshooting)
![image](https://user-images.githubusercontent.com/65581162/88141425-29c7b980-cc26-11ea-8598-f2c10cbe5ced.png)

Reason:
There is a redundant space.
Suggestion:
Change it to `ErrorCodes`.

**Comment by v-xuto** [comment] 2020-07-22 10:15
@jongio for notification.

**Comment by tg-msft** [comment] 2020-08-04 18:40
Closing as by design.  `ErrorCode` is a property name/type suffix and we want that `formatted as code` without the 's'.

**Closed by tg-msft** 2020-08-04 18:40 UTC
Labels: Client, Docs, Storage, blocking-release, manual-test-pass, needs-team-attention
