### ISSUE TITLE
Add support for Azure resource with multiple managed identities

### ISSUE THREAD

**Issue by CBaud** [Azure/azure-sdk-for-net#4791] opened 2018-09-24 23:59 UTC
When the AppAuthentication library requests a token using the Azure Instance Metadata Service (IMDS) endpoint, it currently does not specify any values for the optional object_id or client_id query string parameters. In order for applications to request a token on a VM with multiple user-assigned managed identities, exactly one of those two parameters needs to be specified. It would be great for the AppAuthentication library to provide a way for applications to specify:

- A Guid representing the identity.
- An enumerated value that identifies whether the previous value is a Client ID or an Object ID.

**Comment by nonik0** [comment] 2018-11-02 21:44
Hi Chris, we will have this functionality in the next release of AppAuth that we are working on releasing now. We will also update our existing samples that will show how to use this new functionality shortly after.

**Comment by nonik0** [comment] 2018-11-19 21:14
Hi Chris, we have released AppAuth 1.2.0-preview, which contains the support for user-assigned identities. You can find the new release [here](https://github.com/Azure/azure-sdk-for-net/issues/4826).

As for how to use multiple managed identities, we have published minor updates for the following AppAuth VM samples that include instructions for how to specific a managed identity:
https://github.com/Azure-Samples/linuxvm-msi-keyvault-arm-dotnet
https://github.com/Azure-Samples/windowsvm-msi-arm-dotnet

Let us know if you have any feedback, thanks!

**Comment by gilknyaz** [comment] 2018-12-25 11:05
Hello,
I see in AzureServiceTokenProviderFactory that the tenantID is not used when using the client ID (AppID in the connection string).
However, it is still required and throws an exception if not provided.
Is this by design, or can it be changed?

**Comment by varunsh-msft** [comment] 2018-12-26 18:37
Hi @gilknyaz, what connection string did you use?

**Comment by gilknyaz** [comment] 2018-12-27 09:02
Initially I just tried "AppId=" + clientID, but got an error about missing RunAs.
Ok, makes sense. Tried "RunAs=App;AppId=" + clientID.
Got a missing TenantID error. Only "TenantId=123;RunAs=App;AppId=" + clientID worked.

I inspected the code of AzureServiceTokenProviderFactory, and I see that TenantID isn't actually used for this flow, so I can really place anything I want there.

**Comment by varunsh-msft** [comment] 2018-12-27 18:16
Ok, this looks like a bug. Tenant id is not required for user assigned MSI. We will get it fixed soon. Thanks for reporting!

**Comment by varunsh-msft** [comment] 2019-04-01 20:07
Tenant Id is not required anymore, as of preview2. @shahabhijeet , can you please close this issue? Thanks!

**Comment by varunsh-msft** [comment] 2019-04-06 07:06
Closing, this is done.

**Closed by varunsh-msft** 2019-04-06 07:06 UTC
Labels: AppAuthentication
