### ISSUE TITLE
Does specifying MaximumWaitTime in EventProcessorClient block StopProcessingAsync?

### ISSUE THREAD

**Issue by rnarayana** [Azure/azure-sdk-for-net#16177] opened 2020-10-22 17:26 UTC
**Query/Question**
I have implemented EventProcessorClient from within a IHostedService. Once I run this, I press Ctrl-C to signal the service to shut down. Whenever I specify the MaximumWaitTime, the StopProcessingAsync call blocks until this timer fires (which could be anywhere from 0-MaximumWaitTime). I am using MaxWaitTime = 5 minutes, so as to perform checkpointing in that interval.

Is this the expected behavior? Is there way to make StopProcessingAsync() not depend on this 'null' event?

The code from the hosted service class:

```
public class EventProcessorHostedService : IHostedService
{
	private readonly EventProcessorClient eventProcessorClient;
	private IDriverEventProcessor driverEventProcessor;
	private readonly Container container; //SimpleInjector

	public EventProcessorHostedService(IConfiguration configuration, Container container)
	{
		var eventHubConnectionString = configuration["App:DriverEventHubListenConnectionString"];
		var storageContainerName = configuration["App:StorageContainerName"];
		var storageConnectionString = configuration["App:DataStorageConnectionString"];
		this.eventProcessorClient = new EventProcessorClient(
			new BlobContainerClient(storageConnectionString, storageContainerName),
			EventHubConsumerClient.DefaultConsumerGroupName,
			eventHubConnectionString,
			new EventProcessorClientOptions
			{
				MaximumWaitTime = TimeSpan.FromSeconds(300)
			});
		this.container = container;
	}

	public async Task StartAsync(CancellationToken cancellationToken)
	{
		using (AsyncScopedLifestyle.BeginScope(this.container))
		{
			this.driverEventProcessor = this.container.GetInstance<IDriverEventProcessor>();

			this.eventProcessorClient.ProcessEventAsync += this.driverEventProcessor.EventHandler;
			this.eventProcessorClient.ProcessErrorAsync += this.driverEventProcessor.ErrorHandler;
			this.eventProcessorClient.PartitionInitializingAsync +=	this.driverEventProcessor.PartitionInitializingHandler;
			this.eventProcessorClient.PartitionClosingAsync += this.driverEventProcessor.PartitionClosingHandler;

			await this.eventProcessorClient.StartProcessingAsync(cancellationToken);
		}
	}

	public async Task StopAsync(CancellationToken cancellationToken)
	{
		try
		{
			// <<---------------- Call blocks here   --------------------->>
			await this.eventProcessorClient.StopProcessingAsync(cancellationToken);
		}
		finally
		{
			this.eventProcessorClient.ProcessEventAsync -= this.driverEventProcessor.EventHandler;
			this.eventProcessorClient.ProcessErrorAsync -= this.driverEventProcessor.ErrorHandler;
			this.eventProcessorClient.PartitionClosingAsync -= this.driverEventProcessor.PartitionClosingHandler;
		}
	}
}
```

**Environment:**
 - Azure.Messaging.EventHubs.Processor 5.2.0
 - .NET Core 3.1
 - Running locally on Windows 10 from VS2019

**Comment by jsquire** [comment] 2020-10-22 20:52
The short version is that this is expected behavior and there is no recommended way to opt out of it.   _(there is no significance to the empty event emitted)_

When stopping, the processor will attempt to gracefully shut down the tasks responsible for processing each of the owned partitions.  A large part of partition processing involves making a call to the Event Hubs service to read events.   Unfortunately, the service communication uses a timeout-based transport which does not honor cancellation.   When the `MaximumWaitTime` is specified, that value is used to control the timeout; otherwise the `TryTimeout` from the retry options is used, which has a default of 60 seconds.

Though the processor itself will honor the cancellation token that a stop request signals, stopping may take up to the service operation timeout depending on where in the flow of logic each partition processing task is when the stop is requested.  Because of the lack of cancellation support at the transport level, there is no way to provide a clean shutdown without waiting for outstanding service calls to return.  

If you are intending to use the same processor instance again after it is stopped, it is important to allow stopping to complete.   If you are planning to discard the processor instance and are confident in the checkpoints that you've captured, you can choose to terminate the host for the processor.   If needed, your event handler can key on the cancellation token in the `EventArgs` instance that it is passed to understand that the corresponding partition processing has been cancelled.

This is certainly not an ideal scenario nor is it the experience that we'd like to provide for the SDK.  Unfortunately, in the short term, we're bound by the limitations of the transport.  The long term solution will be working with the service team to migrate to a new AMQP transport that has better support for concerns like cancellation.

It's also fair to call out that our documentation around this behavior is currently lacking;  we've recently made some updates to it which offer more context and try to better establish expectations.  This will be available to intellisense and the MS docs references with our next release in early November.

**Comment by rnarayana** [comment] 2020-10-23 07:48
Thanks @jsquire I'll not be reusing the processor, so I'll go with setting MaximumWaitTime to 60s for now.

**Comment by jsquire** [comment] 2020-10-23 12:51
Glad that the context was helpful.   I'm going to close this out, but please feel free to reopen if you would like to discuss further.

**Closed by jsquire** 2020-10-23 12:51 UTC
Labels: Client, Event Hubs, customer-reported, needs-team-attention, question
