### ISSUE TITLE
[BUG] ArgumentException 'stream must be seekable' when calling ReplaceContentRunbookDraftAsync.

### ISSUE THREAD

**Issue by davecader** [Azure/azure-sdk-for-net#33275] opened 2023-01-03 11:55 UTC
### Library name and version

Azure.ResourceManager.Automation 1.0.0

### Describe the bug

We are consistently observing an ArgumentException 'stream must be seekable' when calling ReplaceContentRunbookDraftAsync to upload a runbook to Azure Automation. The runbook content was converted to a buffer of UTF encoded bytes and which was then used to create a MemoryStream. We have confirmed that the stream that is being bassed to ReplaceContentRunbookDraftAsync  is indeed seekable.

### Expected behavior

The runbook content should be uploaded to Azure Automation without error.

### Actual behavior

Fails with ArgumentException 'stream must be seekable'.

### Reproduction Steps

public async Task UploadRunbookContent(ResourceIdentifier runbookIdentifier, string content)
{
    var options = new InteractiveBrowserCredentialOptions
    {
        TenantId = "<Your Tenant ID>"
        ClientId = "<Your Cliend ID>"		
        RedirectUri = new Uri("<Your Redirect URI>")
    };

    var credential = new InteractiveBrowserCredential(options);
    var armClient = new ArmClient(credential);	
    AutomationRunbookResource resource = armClient.GetAutomationRunbookResource(runbookIdentifier);

    using (var stream = new MemoryStream(Encoding.UTF8.GetBytes(content)))
    {
        await resource.ReplaceContentRunbookDraftAsync(WaitUntil.Completed, stream);
    }
}

**Comment by davecader** [comment] 2023-01-03 12:17
StackTrace	"   at Azure.Core.RequestContent.StreamContent..ctor(Stream stream)\r\n   at Azure.ResourceManager.Automation.RunbookDraftRestOperations.CreateReplaceContentRequest(String subscriptionId, String resourceGroupName, String automationAccountName, String runbookName, Stream runbookContent)\r\n   at Azure.ResourceManager.Automation.AutomationRunbookResource.<ReplaceContentRunbookDraftAsync>d__28.MoveNext()\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()\r\n   at Kelverion.RunbookStudio.Cloud.Client.AutomationRunbookCollectionClient.<DoUpdateAsync>d__9.MoveNext() in C:\\Users\\DavidCader\\source\\repos\\app-automation-console\\Src\\Kelverion.RunbookStudio.Cloud\\Client\\AutomationRunbookCollectionClient.cs:line 134\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()\r\n   at Kelverion.RunbookStudio.Cloud.Client.AutomationCollectionClientBase`1.<UpdateAsync>d__13.MoveNext() in C:\\Users\\DavidCader\\source\\repos\\app-automation-console\\Src\\Kelverion.RunbookStudio.Cloud\\Client\\AutomationCollectionClientBase.cs:line 121"	string

**Comment by davecader** [comment] 2023-01-03 12:50
I thought the problem might have been due to disposing the stream explicitly. However, when I updated the code so that the stream was not disposed the same exception was still observed. This is a major blocking issue for us.

**Comment by jsquire** [comment] 2023-01-03 13:37
Thank you for your feedback.  Tagging and routing to the team member best able to assist.  Please expect delayed responses due to the US holidays.

**Comment by davecader** [comment] 2023-01-05 14:48
It looks like the stream is being disposed, but our code is not explicitly doing so. Investigating further, but now struggling with an Azure.Identity authentication failure.

**Comment by davecader** [comment] 2023-01-05 15:13
It looks like the stream is being disposed, but our code is not explicitly doing so. Investigating further, but now struggling with an Azure.Identity authentication failure.

**Comment by Yao725** [comment] 2023-01-10 08:35
Thanks for reaching out to us, will try to reproduce this issue.

**Comment by ArtificialErmine** [comment] 2023-01-13 18:49
I've noticed this bug as well when working on a prototype runBook for my team, which is effectively blocked without a fix for this - both on async and non-async variants of the `ReplaceContentRunbookDraft` method. It definitely is the case that the stream is being disposed - based on my debugging it appears that it's between `_runbookDraftRestClient.ReplaceContentAsync` and the subsequent call to `AutomationArmOperation` that the dispose occurs, but I'm not 100% sure if that's accurate or just how things appear to be.

**Comment by wrharper** [comment] 2023-01-31 13:38
I have been getting the same error, but now I can't get the code to get into Azure at all. When the error first happened, the code was still in Azure, so it was ok and just a false positive.

**Comment by Yao725** [comment] 2023-02-06 06:59
This issue is reproduced and confirmed, opened #33907 to fix it.

**Comment by Yao725** [comment] 2023-02-08 07:39
Close this issue as the fix is merged, we will release a new version for automation soon.

**Closed** 2023-02-08 07:38 UTC
Labels: Automation, Mgmt, customer-reported, question, needs-team-attention

**Comment by Yao725** [comment] 2023-02-16 02:25
Have released a new version with the fix of this problem: https://www.nuget.org/packages/Azure.ResourceManager.Automation/1.0.1

**Comment by Yao725** [comment] 2023-02-17 05:50
It's correct that the stream that is being passed to ReplaceContentRunbookDraft has to be seekable. Here what I fixed is that we shouldn't get the exception `stream must be seekable` with a seekable stream. And back to the question about changing the type of this parameter to string, our SDK is based on the API spec, so please open an issue [here](https://github.com/Azure/azure-rest-api-specs) to let the service team know this need.
