### ISSUE TITLE
[BUG] Unable to update replication status on Gallery Image Version

### ISSUE THREAD

**Issue by chrisalexander** [Azure/azure-sdk-for-net#10011] opened 2020-02-17 16:52 UTC
**Describe the bug**
Calling the Update API on a Gallery Image Version to change the replication does not work.

**Expected behavior**
Able to update replication.

**Actual behavior (include Exception or Stack Trace)**
ValidationException: Id cannot be null
![image](https://user-images.githubusercontent.com/50909/74672680-b963ca80-51a5-11ea-81e3-76cf5997423c.png)

**To Reproduce**
Steps to reproduce the behavior (include a code snippet, screenshot, or any additional information that might help us reproduce the issue)

    IAzure azure = ...;
    var galleryClient = azure.GalleryImageVersions;
    var version = await galleryClient.GetByGalleryImageAsync("ValidResourceGroupName", "ValidGalleryName", "ValidImageName", "ValidImageVersion");
    await version.Update().WithRegionAvailability(Region.UAENorth, 1).ApplyAsync();

**Environment:**
 - Name and version of the Library package used: Microsoft.Azure.Management.Fluent 1.30.0
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): Azure Functions v3 runtime (.NET Core 3.0)
 - IDE and version : Visual Studio 16.4.5 (2019)

**Comment by jsquire** [comment] 2020-02-18 15:51
//cc: @yaohaizh

**Comment by chrisalexander** [comment] 2020-03-04 14:56
Hi folks, any chance on an ETA for this one? Here or on the open ticket fine.

**Comment by xccc-msft** [comment] 2020-03-05 11:45
@chrisalexander For this, we will need service team to explain if any changes required from their side.
The current behavior can be found in the [example with response](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/compute/resource-manager/Microsoft.Compute/stable/2019-07-01/examples/CreateOrUpdateASimpleGalleryImageVersion.json) after resource creation, which ids are not returned for `osDiskImage` and `dataDiskImages`. But in the service definition, the source ids are required as per [definition of GalleryDiskImage](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/compute/resource-manager/Microsoft.Compute/stable/2019-07-01/gallery.json#L2278-L2280) and [definition of GalleryArtifactVersionSource](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/compute/resource-manager/Microsoft.Compute/stable/2019-07-01/gallery.json#L2226-L2228).

For now, you can have workaround as below:
```csharp
var version = await computeManager.Inner.GalleryImageVersions.GetAsync("ValidResourceGroupName", "ValidGalleryName", "ValidImageName", "ValidImageVersion", ReplicationStatusTypes.ReplicationStatus);
version.Inner.StorageProfile.OsDiskImage.Source = new GalleryArtifactVersionSource(version.StorageProfile.Source.Id);
foreach (var item in version.Inner.StorageProfile.DataDiskImages) {
    item.Source = new GalleryArtifactVersionSource(version.StorageProfile.Source.Id);
};
await version.Update().WithRegionAvailability(Region.UAENorth, 1).ApplyAsync();
```

**Comment by chrisalexander** [comment] 2020-03-05 12:26
Thanks for providing the workaround, I will try that but would rather not go to production until we have the standard calls working correctly

**Comment by Drewm3** [comment] 2020-03-05 18:08
@axayjo, could you take a look at this issue?

**Comment by chrisalexander** [comment] 2020-03-12 14:03
We have our other fix in this area checked in, is it possible to get an update on where this one is please?

**Comment by xccc-msft** [comment] 2020-03-13 05:06
@axayjo Can you please share any update from your end?

**Comment by axayjo** [comment] 2020-03-13 07:24
@xccc-msft, The service itself doesn't require users to pass any of the source IDs (StorageProfile.OsDiskImage.Source.id, StorageProfile.DataDiskImages[i].Source.id, StorageProfile.source.id) in their Update Image Version calls. This must be an SDK issue. Adding @hyonholee here to take a look.

**Comment by xccc-msft** [comment] 2020-03-14 06:54
@axayjo Thanks for explaining the behavior of service.
@hyonholee Please help check the swagger and revise the conflicts between the service definition and implementation. Thanks.

**Comment by chrisalexander** [comment] 2020-04-15 08:28
Hi folks, looks like this missed the April SDK release, any chance it might make the May one? Thanks

**Comment by xccc-msft** [comment] 2020-04-15 09:54
@chrisalexander We are still waiting for updates from service end. If they decide to revise the swagger, then we could regenerate the code based on updated swagger.

**Comment by chrisalexander** [comment] 2020-04-15 10:35
OK thanks, will see if I can get hold of them

**Comment by KshitijAgrawal** [comment] 2020-04-16 20:05
Hi, the parent source/ falleryosdiskimage etc themselves are optional. so can we fix this on SDK side?

**Comment by chrisalexander** [comment] 2020-04-20 16:25
@xccc-msft Hello, please see reply above from product team. If you drop me an e-mail I can link you up if required.

**Comment by xccc-msft** [comment] 2020-04-21 02:40
@chrisalexander @KshitijAgrawal The generated code is from swagger. I understand the parameters might be optional in server's behavior, but the root cause here is that the service team set them mandatory in [swagger definition](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/compute/resource-manager/Microsoft.Compute/stable/2019-07-01/gallery.json#L2226-L2228). I don't think it would be good to fix manually before it gets fixed by swagger.

cc: @yungezz

**Comment by jerryc3** [comment] 2020-04-28 18:50
Hi @xccc-msft, The service team will fix this in the swagger definition. In the meantime, can you please fix this on your side in parallel? This is affecting customers and we want to unblock them in a timely fashion.

**Comment by KshitijAgrawal** [comment] 2020-04-28 18:51
> @chrisalexander @KshitijAgrawal The generated code is from swagger. I understand the parameters might be optional in server's behavior, but the root cause here is that the service team set them mandatory in [swagger definition](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/compute/resource-manager/Microsoft.Compute/stable/2019-07-01/gallery.json#L2226-L2228). I don't think it would be good to fix manually before it gets fixed by swagger.
> 
> cc: @yungezz

Hey,

I meant to say the source.id is required, but "source" itself if optional in the swagger. I am not talking about service side. The problem is if someone provides source we expect them to provide id because that is the only property in the source. But the source itself is marked optional in swagger, so why is that not getting skipped?

Is it because we are source, but not id in GET?

Thanks!
Kshitij

**Comment by xccc-msft** [comment] 2020-04-29 02:56
@KshitijAgrawal For your question, it is because the code generator will create empty source without id inside, which can be found in [.NET SDK](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/compute/Microsoft.Azure.Management.Compute/src/Generated/Models/GalleryImageVersionStorageProfile.cs#L37) and [Fluent .NET SDK]( https://github.com/Azure/azure-libraries-for-net/blob/master/src/ResourceManagement/Compute/Generated/Models/GalleryImageVersionStorageProfile.cs#L35).

@jerryc3 Sure, I will start to fix according to the swagger changes.

**Closed** 2020-05-15 04:32 UTC
Labels: Compute - Images, Mgmt, Service Attention, customer-reported

**Comment by chrisalexander** [comment] 2020-05-27 10:02
Thanks all!
