### ISSUE TITLE
[EventHub Track 2] Checkpoint should use exclusive not inclusive offset

### ISSUE THREAD

**Issue by ellismg** [Azure/azure-sdk-for-net#9158] opened 2019-12-16 23:21 UTC
**Describe the bug**
When interpreting the `Offset` field in a partition's checkpoint metadata, we use `EventPosition.FromOffset()` to build a position from the given offset. However, `EventPosition.FromOffset(long)` returns an **inclusive** offset, so we end up reprocessing the last checkpointed event each time the processor restarts.

**To Reproduce**
1. Push a bunch of events into EventHub, and then stop the producer.
2. Use EventProcessorClient to read all the events checkpointing after each event.  Once you've processed all the events, terminate.
3. Re-run your program from step (2).  You'll see the last event from each partition is reprocessed.

**Expected behavior**
Upon resuming, we should move "beyond" the last processed event we checkpointed.  This is the same behavior as Track 1.

**Additional context**
The semantics of EventPosition.FromOffset(long) have changed from Track 1 to Track 2.  In Track 1 this builds an an exclusive position and in Track 2 it builds an inclusive one.  Unlike Track 1 there is no way in Track 2 to create an EventPosition from an offset which is not inclusive.  In Track 1 there is an overload for doing this.

**Comment by jsquire** [comment] 2019-12-17 14:22
The use of inclusive offset is by design, and was the result of some... lively... discussions during board reviews.  That said, the processor should be smart enough to account for that and shift the checkpoint offset value by 1 to force movement to the next offset.   We'll get that fixed up.

//cc: @kinelski

**Comment by jsquire** [comment] 2019-12-17 14:24
@kinelski - We should also ensure that we have a test validating the behavior, post-fix.

**Comment by jsquire** [comment] 2019-12-18 19:09
This should be fixed by #9166, which as merged.

**Closed by jsquire** 2019-12-18 19:09 UTC
Labels: Bug, Client, Event Hubs
