### ISSUE TITLE
v5.0.3. Could not load file or assembly 'Microsoft.Azure.Search.Service'...

### ISSUE THREAD

**Issue by matthewrwilliams** [Azure/azure-sdk-for-net#5003] opened 2018-11-06 00:43 UTC
I am upgrading the following from 5.0.2 to 5.0.3 using NuGet and getting into the error mentioned in the title.  Backing out the update resolves the issue.  All dll's are appearing in the bin directory, and this will error in Debug or Release, both local and deployed.

- Microsoft.Azure.Search
- Microsoft.Azure.Search.Common
- Microsoft.Azure.Search.Data
- Microsoft.Azure.Search.Service

For clarification, this is using a ASP.NET (not Core) app.

Full error:
`Could not load file or assembly 'Microsoft.Azure.Search.Service, Version=5.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.`

Please let me know if I can provide any further information.

**Comment by brjohnstmsft** [comment] 2018-11-07 00:54
@matthewrwilliams Does this error happening when updating via NuGet, or does it happen at run-time after you've deployed your application? I've tried updating some of our samples locally via NuGet and it works fine for me.

**Comment by matthewrwilliams** [comment] 2018-11-07 21:32
@brjohnstmsft The error occurs during runtime.  I spent some more time on this today... I cleaned the solution, restarted VS, and a handful of other things to only get the same response.  As a last straw, I restarted and that cleared the issue.  I am not sure how this would fix the issue, but I can replicate it by backing out the change and reinstalling it.  I'm past the issue as of this minute, so this can be closed.

Thanks

**Comment by brjohnstmsft** [comment] 2018-11-13 20:18
Given that we can't repro the problem and other folks seem to be able to upgrade to 5.0.3 just fine, it looks like the problem is specific to your environment. I would suggest using [Fuslogvw](https://docs.microsoft.com/dotnet/framework/tools/fuslogvw-exe-assembly-binding-log-viewer) to debug the assembly loading process to find out what's missing.

**Comment by matthewrwilliams** [comment] 2018-11-15 15:54
No worries Bruce.  Incidentally, I tried the upgrade again today and it worked.  The difference was the "Microsoft.Rest.ClientRuntime" also updated from v2.3.17 to v2.3.18.  I am no longer having issues.

**Comment by brjohnstmsft** [comment] 2018-11-15 17:48
@matthewrwilliams Thanks for confirming. Closing this issue.

**Closed by brjohnstmsft** 2018-11-15 17:48 UTC
