### ISSUE TITLE
[Form Recognizer] CopyModel(False) failing in nightly runs

### ISSUE THREAD

**Issue by v-yilinhu** [Azure/azure-sdk-for-net#26524] opened 2022-01-21 06:45 UTC
Form Recognizer runs are failing with:

> Error message
> Azure.RequestFailedException : Resource not found.
> Status: 404 (Not Found)
> ErrorCode: NotFound
> 
> Content:
> {
> "error": {
> "code": "NotFound",
> "message": "Resource not found.",
> "innererror": {
> "code": "OperationNotFound",
> "message": "The requested operation was not found. The identifier may be invalid or the operation may have expired."
> }
> }
> }
> 
> Headers:
> Transfer-Encoding: chunked
> x-envoy-upstream-service-time: 18
> apim-request-id: e2ea941f-0bbb-4158-9f4f-3d937080079d
> Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
> X-Content-Type-Options: nosniff
> Date: Fri, 21 Jan 2022 05:02:15 GMT
> Content-Type: application/json
> 
> 
> Stack trace
>    at Azure.AI.FormRecognizer.DocumentAnalysis.DocumentAnalysisRestClient.GetOperationAsync(String operationId, CancellationToken cancellationToken) in /mnt/vss/_work/1/s/sdk/formrecognizer/Azure.AI.FormRecognizer/src/Generated/DocumentAnalysisRestClient.cs:line 674
>    at Azure.AI.FormRecognizer.DocumentAnalysis.BuildModelOperation.Azure.Core.IOperation<Azure.AI.FormRecognizer.DocumentAnalysis.DocumentModel>.UpdateStateAsync(Boolean async, CancellationToken cancellationToken) in /mnt/vss/_work/1/s/sdk/formrecognizer/Azure.AI.FormRecognizer/src/BuildModelOperation.cs:line 157
>    at Azure.Core.OperationInternal`1.UpdateStateAsync(Boolean async, CancellationToken cancellationToken) in /mnt/vss/_work/1/s/sdk/core/Azure.Core/src/Shared/OperationInternalOfT.cs:line 186
>    at Azure.Core.OperationInternalBase.UpdateStatusAsync(Boolean async, CancellationToken cancellationToken) in /mnt/vss/_work/1/s/sdk/core/Azure.Core/src/Shared/OperationInternalBase.cs:line 173
>    at Azure.Core.OperationInternalBase.UpdateStatusAsync(CancellationToken cancellationToken) in /mnt/vss/_work/1/s/sdk/core/Azure.Core/src/Shared/OperationInternalBase.cs:line 80
>    at Azure.Core.OperationInternalBase.WaitForCompletionResponseAsync(TimeSpan pollingInterval, CancellationToken cancellationToken) in /mnt/vss/_work/1/s/sdk/core/Azure.Core/src/Shared/OperationInternalBase.cs:line 142
>    at Azure.Core.OperationInternal`1.WaitForCompletionAsync(TimeSpan pollingInterval, CancellationToken cancellationToken) in /mnt/vss/_work/1/s/sdk/core/Azure.Core/src/Shared/OperationInternalOfT.cs:line 167
>    at Azure.Core.OperationInternal`1.WaitForCompletionAsync(CancellationToken cancellationToken) in /mnt/vss/_work/1/s/sdk/core/Azure.Core/src/Shared/OperationInternalOfT.cs:line 145
>    at Azure.AI.FormRecognizer.DocumentAnalysis.BuildModelOperation.WaitForCompletionAsync(CancellationToken cancellationToken) in /mnt/vss/_work/1/s/sdk/formrecognizer/Azure.AI.FormRecognizer/src/BuildModelOperation.cs:line 78
>    at Azure.AI.FormRecognizer.DocumentAnalysis.Tests.DisposableBuildModel.BuildModelAsync(DocumentModelAdministrationClient adminClient, Uri trainingFilesUri, String modelId) in /mnt/vss/_work/1/s/sdk/formrecognizer/Azure.AI.FormRecognizer/tests/Infrastructure/DisposableBuildModel.cs:line 54
>    at Azure.AI.FormRecognizer.DocumentAnalysis.Tests.DocumentAnalysisLiveTestBase.CreateDisposableBuildModelAsync(String modelId, ContainerType containerType) in /mnt/vss/_work/1/s/sdk/formrecognizer/Azure.AI.FormRecognizer/tests/Infrastructure/DocumentAnalysisLiveTestBase.cs:line 119
>    at Azure.AI.FormRecognizer.DocumentAnalysis.Tests.DocumentModelAdministrationClientLiveTests.CopyModel(Boolean useTokenCredential) in /mnt/vss/_work/1/s/sdk/formrecognizer/Azure.AI.FormRecognizer/tests/DocumentModelAdministrationClient/DocumentModelAdministrationClientLiveTests.cs:line 221
>    at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.BlockUntilCompleted()
>    at NUnit.Framework.Internal.MessagePumpStrategy.NoMessagePumpStrategy.WaitForCompletion(AwaitAdapter awaiter)
>    at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.<>c__DisplayClass1_0.<Execute>b__0()
>    at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.RunTestMethodInThreadAbortSafeZone(TestExecutionContext context, Action action)

For more details check here:

- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1317623&view=results
- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1314894&view=results
- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1312168&view=results

@jsquire for notification.

**Comment by jsquire** [comment] 2022-01-21 14:17
Closing as a duplicate of #26523;  I've added the additional test run examples to the existing issue for this test.

**Closed by jsquire** 2022-01-21 14:17 UTC
Labels: Client, needs-team-triage, Cognitive - Form Recognizer
