### ISSUE TITLE
[TextAnalytics] AnalyzeSentimentTest failing in nightly runs

### ISSUE THREAD

**Issue by Menghua1** [Azure/azure-sdk-for-net#34065] opened 2023-02-10 09:05 UTC
TextAnalytics nightly test runs are failing with:

> Error message
> Azure.RequestFailedException : Access denied due to invalid subscription key or wrong API endpoint. Make sure to provide a valid key for an active subscription and use a correct regional API endpoint for your resource.
> Status: 401 (PermissionDenied)
> ErrorCode: 401
> 
> Content:
> {"error":{"code":"401","message":"Access denied due to invalid subscription key or wrong API endpoint. Make sure to provide a valid key for an active subscription and use a correct regional API endpoint for your resource."}}
> 
> Headers:
> apim-request-id: 08d4f957-9236-4a57-9a05-ff26414a7ecf
> Date: Fri, 10 Feb 2023 02:55:09 GMT
> Content-Length: 224
> Content-Type: application/json
> 
> 
> Stack trace
>    at Azure.AI.TextAnalytics.MicrosoftCognitiveLanguageServiceTextAnalysisRestClient.AnalyzeAsync(AnalyzeTextTask body, Nullable`1 showStats, CancellationToken cancellationToken) in /mnt/vss/_work/1/s/sdk/textanalytics/Azure.AI.TextAnalytics/src/Generated/MicrosoftCognitiveLanguageServiceTextAnalysisRestClient.cs:line 90
>    at Azure.AI.TextAnalytics.ServiceClients.LanguageServiceClient.AnalyzeSentimentAsync(String document, String language, AnalyzeSentimentOptions options, CancellationToken cancellationToken) in /mnt/vss/_work/1/s/sdk/textanalytics/Azure.AI.TextAnalytics/src/ServiceClients/LanguageServiceClient.cs:line 785
>    at Azure.AI.TextAnalytics.TextAnalyticsClient.AnalyzeSentimentAsync(String document, String language, AnalyzeSentimentOptions options, CancellationToken cancellationToken) in /mnt/vss/_work/1/s/sdk/textanalytics/Azure.AI.TextAnalytics/src/TextAnalyticsClient.cs:line 940
>    at Azure.Core.TestFramework.DiagnosticScopeValidatingInterceptor.<>c__DisplayClass4_0`1.<<WrapAsyncResultCore>g__Await|0>d.MoveNext() in /mnt/vss/_work/1/s/sdk/core/Azure.Core.TestFramework/src/Instrumentation/DiagnosticScopeValidatingInterceptor.cs:line 120
> --- End of stack trace from previous location ---
>    at Azure.Core.TestFramework.DiagnosticScopeValidatingInterceptor.<>c__DisplayClass5_0`1.<<ValidateDiagnosticScopeInterceptor>b__0>d.MoveNext() in /mnt/vss/_work/1/s/sdk/core/Azure.Core.TestFramework/src/Instrumentation/DiagnosticScopeValidatingInterceptor.cs:line 171
> --- End of stack trace from previous location ---
>    at Azure.Core.TestFramework.DiagnosticScopeValidatingInterceptor.ValidateDiagnosticScope[T](Func`1 action, MethodInfo methodInfo, String source) in /mnt/vss/_work/1/s/sdk/core/Azure.Core.TestFramework/src/Instrumentation/DiagnosticScopeValidatingInterceptor.cs:line 201
>    at Azure.AI.TextAnalytics.Tests.AnalyzeSentimentTests.AnalyzeSentimentTest() in /mnt/vss/_work/1/s/sdk/textanalytics/Azure.AI.TextAnalytics/tests/AnalyzeSentimentTests.cs:line 60
>    at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.BlockUntilCompleted()
>    at NUnit.Framework.Internal.MessagePumpStrategy.NoMessagePumpStrategy.WaitForCompletion(AwaitAdapter awaiter)
>    at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.<>c__DisplayClass1_0.<Execute>b__0()
>    at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.RunTestMethodInThreadAbortSafeZone(TestExecutionContext context, Action action)

For more details check here:

- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2177526&view=results

@jsquire for notification.

**Comment by joseharriaga** [comment] 2023-04-10 16:33
This is a duplicate of https://github.com/Azure/azure-sdk-for-net/issues/35452.

**Closed by joseharriaga** 2023-04-10 16:33 UTC
Labels: Client, Cognitive - Text Analytics, test-reliability
