### ISSUE TITLE
[Metrics Advisor] CanDeleteRepository failing in nightly runs

### ISSUE THREAD

**Issue by v-yilinhu** [Azure/azure-sdk-for-net#23603] opened 2021-08-27 08:41 UTC
Metrics Advisor nightly test runs are failing with:

> Error message
> Azure.RequestFailedException : Service request failed.
> Status: 400 (Bad Request)
> 
> Content:
> {"code":"Bad Request","message":"Invalid parameter. alerting configuration count should be less than or equal to 100. TraceId: 9b20eba2-36f5-4958-8657-7a27ed70a84b"}
> 
> Headers:
> X-Request-ID: 5608e202-3877-474d-99f0-aa8e4d81b1a8
> x-envoy-upstream-service-time: 231
> apim-request-id: 5608e202-3877-474d-99f0-aa8e4d81b1a8
> Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
> X-Content-Type-Options: nosniff
> Date: Wed, 25 Aug 2021 12:55:40 GMT
> Content-Length: 165
> Content-Type: application/json; charset=utf-8
> 
> 
> Stack trace
>    at Azure.AI.MetricsAdvisor.MicrosoftAzureMetricsAdvisorRestAPIOpenAPIV2RestClient.CreateAnomalyAlertingConfigurationAsync(AnomalyAlertConfiguration body, CancellationToken cancellationToken) in /_/sdk/metricsadvisor/Azure.AI.MetricsAdvisor/src/Generated/MicrosoftAzureMetricsAdvisorRestAPIOpenAPIV2RestClient.cs:line 308
>    at Azure.AI.MetricsAdvisor.Administration.MetricsAdvisorAdministrationClient.CreateAlertConfigurationAsync(AnomalyAlertConfiguration alertConfiguration, CancellationToken cancellationToken) in /_/sdk/metricsadvisor/Azure.AI.MetricsAdvisor/src/MetricsAdvisorAdministrationClient.cs:line 1145
>    at Azure.AI.MetricsAdvisor.Samples.MetricsAdvisorSamples.CreateAndDeleteAlertConfigurationAsync() in /Users/runner/work/1/s/sdk/metricsadvisor/Azure.AI.MetricsAdvisor/tests/Samples/Sample06_AlertConfigurationCrudOperations.cs:line 49
>    at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.BlockUntilCompleted()
>    at NUnit.Framework.Internal.MessagePumpStrategy.NoMessagePumpStrategy.WaitForCompletion(AwaitAdapter awaiter)
>    at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
>    at NUnit.Framework.Internal.Execution.SimpleWorkItem.<>c__DisplayClass4_0.<PerformWork>b__0()
>    at NUnit.Framework.Internal.ContextUtils.<>c__DisplayClass1_0`1.<DoIsolated>b__0(Object _)
>    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
> --- End of stack trace from previous location ---
>    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
>    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
>    at NUnit.Framework.Internal.ContextUtils.DoIsolated(ContextCallback callback, Object state)
>    at NUnit.Framework.Internal.ContextUtils.DoIsolated[T](Func`1 func)
>    at NUnit.Framework.Internal.Execution.SimpleWorkItem.PerformWork()

For more details check here:

- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1065146&view=results
- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1067393&view=results

**Comment by kinelski** [comment] 2021-09-14 17:25
Ignored test in https://github.com/Azure/azure-sdk-for-net/pull/23982. The cause of the issue is already known and shared with other failures, so closing this and tracking it with https://github.com/Azure/azure-sdk-for-net/issues/22575.

**Closed by kinelski** 2021-09-14 17:25 UTC
Labels: Client, test-reliability, Cognitive - Metrics Advisor
