### ISSUE TITLE
[BUG] Azure.Identity 1.5.0 freezes up ChainedTokenCredential with ManagedIdentityCredential listed first in local dev

### ISSUE THREAD

**Issue by mikequ-taggysoft** [Azure/azure-sdk-for-net#24767] opened 2021-10-16 20:35 UTC
**Describe the bug**

Immediately after upgrading `Azure.Identity` from 1.4.1 to 1.5.0, I noticed all my web projects freeze up at startup in local dev (VS Kestrel).

In my host builder inside Program.cs, I have  

```csharp
var tokenCred = new ChainedTokenCredential(new ManagedIdentityCredential(), new AzureCliCredential());

var secretClient = new SecretClient(
                        new Uri($"https://my-keyvault.vault.azure.net/"),
                        tokenCred);

var certificatesClient = new CertificateClient(
                        new Uri($"https://my-keyvault.vault.azure.net/"),
                            tokenCred);

config.AddAzureKeyVault(secretClient, new KeyVaultSecretManager());

...//load some necessary secret/certs etc
```

Note that I use `ChainedTokenCredential` with `ManagedIdentityCredential` listed first, followed by `AzureCliCredential`. This would ensure that when the project runs in Azure, managed identity is immediately used. In local dev, managed identity is attempted first which would fail quickly, then `AzureCliCredential` is successfully used next.

**Expected behavior**

Normally, the `ManagedIdentityCredential` should fail quickly (within a second or so) when running in local dev environment, which allows the chained credential to fall through to the next available credential.

**Actual behavior**

Something changed in `Azure.Identity` 1.5.0, which makes the program freeze up at `ManagedIdentityCredential` in local dev for a minute+. No exception/error messages (except Kestrel would time out, saying host is unable to start). But eventually, `AzureCliCredential` hits and code flows through.  Maybe the timetout on `ManagedIdentityCredential` was misconfigured in the newer package.

**Environment:**
 - Azure.Identity 1.5.0
 - Visual Studio 2022 RC1 
 - ASP.NET Core Web API and Razor projects set to start up via Kestrel

**Comment by jsquire** [comment] 2021-10-16 21:44
Thank you for your feedback.  Tagging and routing to the team members best able to assist.

**Comment by christothes** [comment] 2021-10-19 18:00
> BTW, the only reason I'm using `ChainedTokenCredential` over `DefaultAzureCredential` is because the latter places `VisualStudioCredential` in a higher priority, and back then I found it to be very slow. `AzureCliCredential` on the other hand is always very fast.

You can also skip the VisualStudioCredential with DefaultAzureCredential by setting this to true: https://github.com/Azure/azure-sdk-for-net/blob/f993f9d5a6062a04feedd7a72ac71dcb0c7ce77f/sdk/identity/Azure.Identity/src/DefaultAzureCredentialOptions.cs#L98
 
> Now after seeing your post, I did test the `VisualStudioCredential` again (running VS 2022 RC1) and it appears fast so far. Has the performance of this credential been tuned and can be expected to be consistently speedy nowadays?

There have been no changes in the SDK but perhaps there were some improvements shipped with VS's token utility.

**Comment by schaabs** [comment] 2021-10-19 20:40
@mikequ-taggysoft

> are you basically suggesting that ManagedIdentityCredential can sometimes have a longer latency (potentially >= 1s) while running inside Azure, despite it using Microsoft-managed private network?

No, a 1 second timeout should be safe since the managed identity endpoint is generally a non-addressable local endpoint. We did some extensive performance benchmarking on various managed identity hosts and found this to be an acceptable limit. What I was trying to suggest is that setting `NetworkTimeout` to a considerably shorter amount of time, say 300ms, will further speed up your `ChainedTokenCredential` in your development enviornment, but depending on the host and your application you might see some artificial timeouts when deployed. Sorry for the confusion.

**Comment by Christoba** [comment] 2021-10-21 15:30
I'm having a similar experience to @mikequ-taggysoft. When using `DefaultAzureCredential` (and not chained) there are still multiple, long-running timeouts with managed identity connection attempts (something like 8 or 9 by default). We've rolled back to 1.4.1 and are worried about "trusting" credential auto-resolution as has been provided by the Default and Chained credential wrappers.

I've reviewed the changelog with 1.5.0 and it implies that managed identity credentials could have a use case locally (for kubernetes integration?) and that environment credential also received some updates.

In our scenario, we currently employ the following:

* Managed Identity Credential (for azure-hosted services only). My expectation would be an immediate (e.g. low ms) skip of this credential when not running in an azure hosted service. If this is configurable in the api - great, otherwise, we'd look at auto-detection.

* Environment Credential (for CI/Azure Pipelines, and for potential overriding in azure or locally)

* VisualStudioCredential (integration tests only, so we can specify tenant id)

* Az Cli Credential (for locally authenticating to various tenants and running tests/apps locally)

Resolving and employing the correct credential to use has been a < 1s action in 1.4.1. This is now multi-second to even half-minute with no code changes just by updating to 1.5.0

**Comment by hugoqribeiro** [comment] 2021-11-29 18:09
I have the same issue with version 1.5.0.

One given operation on KV used to take 3 secs using `ChainedTokenCredential` and `ManagedIdentityCredential` in v1.4.1.
In v1.5.0 it timeouts after 90 secs.
If I apply the "hack" of setting the `NetworkTimeout` to 1 sec, the same operation still takes 21 secs.

I'm reverting back to v1.4.1. Please fix this.

**Comment by iqoOopi** [comment] 2022-01-28 19:42
Hi there, 
I'm also having issue with ChainedTokenCredential

var credential = new ChainedTokenCredential(new ClientCertificateCredential(tenantId, clientId, certificate), new VisualStudioCredential());

If I chain ClientCertificateCredential with VisualStudioCredential. It will throw if the certificate is null instead of trying the second method. Usually the certificate is only for prod and it should be null when debug locally.

**Comment by NeilMacMullen** [comment] 2022-01-31 15:33
Out of interest, is there any downside for _deployed_ clients in reversing the order of the chain?  So 

`var tokenCred = new ChainedTokenCredential(new AzureCliCredential(),new ManagedIdentityCredential(), );`

instead of 

`var tokenCred = new ChainedTokenCredential(new ManagedIdentityCredential(), new AzureCliCredential());`

This seems like a reasonable workaround but I'm a bit paranoid about deployed clients somehow picking up a valid but incorrect AzureCliCrential rather than the expected ManagedIdentityCredential.

**Comment by christothes** [comment] 2022-01-31 15:38
It really depends on how confident you are that the CLI isn't available on the host with a logged in credential. But another workaround would be to dynamically build up the chain based on the presence of an environment variable or other configuration settings that is only present when deployed. Ideally, `ManagedIdentityCredential` would work this way internally, but unfortunately there is no reliable way to confirm that a managed Identity is available without probing for the presence of the endpoint.

**Comment by NeilMacMullen** [comment] 2022-01-31 15:53
>another workaround would be to dynamically build up the chain

Yes, seems more prudent just to get the local application to "opt in" to skipping ManagedIdentity through some environmental clue for now.

**Comment by mabster** [comment] 2022-08-18 23:08
Just struck this issue when I upgraded our .NET 6 Web API project to Microsoft.Data.SqlClient v5. Until now, we haven't had a dependency on Azure.Identity v1.5 or later, so we haven't seen this issue.

Just a heads-up that you might get a few more people seeing this now that SqlClient depends on Azure.Identity 1.6.0.

Luckily we're using a ClientSecretCredential if we're running locally so we can use that as the environmental "clue" to skip the managed identity check.

**Comment by heldersousa-planetpayment** [comment] 2022-09-14 08:38
We are facing this issue as well. 
We are not sure why 1 second is not enough to get a response from AD, whilst running everything in azure (our app is running in a pod in AKS) but the 10 seconds delay is explained by the fact that the default implementation is doing an incremental cooldown period between calls (empty spaces between the blue bars) shown in this image:
![image](https://user-images.githubusercontent.com/107053506/190103558-a49f24b3-adeb-4db2-91ae-40dce4380955.png)

**Comment by christothes** [comment] 2022-09-14 14:52
Hi @heldersousa-planetpayment - The 1 second timeout *should* be enough. However, if you are expecting a response from the IMDS endpoint and it is not able to respond within the timeout, it can be configured via the [InitialImdsConnectionTimeout](https://github.com/Azure/azure-sdk-for-net/blob/18bc4896f5c20d1060e99197da84397593585fad/sdk/identity/Azure.Identity/src/ManagedIdentityClientOptions.cs#L19) . If it still does not respond after setting a longer timeout, there could be something else going on that is preventing the response.

**Comment by heldersousa-planetpayment** [comment] 2022-09-14 17:12
@christothes yes, I agree that the 1 second timeout should be enough. I posted the image to try to explain the 10 seconds delay, even with a default timeout of 1 second. It was not clear to me (maybe I missed something in docs) that the implementation would try multiple times with a bigger cooldown period on each time.

Regarding the 1 second timeout, I found the problem in my specific use case. My app is running in AKS pod and configured to use MSI (using Azure.Identity 1.6.1)
My code looks like something like this.

```c#
services.AddSingleton(new CosmosClientBuilder(cosmosDbSettings.EndpointUrl, new DefaultAzureCredential())
    .WithConnectionModeGateway()
    .Build());
services.AddSingleton(new ServiceBusClient(serviceBusSettings.ConnectionString, new DefaultAzureCredential()));
```
When the app starts, it is connecting to both CosmosDB (7 containers) and Azure Service Bus (4 topics), and I can see 15 requests to `http://169.254.169.254:80/metadata/identity/oauth2/token` at pretty much the same time in parallel.

As part of the stacktrace that most people with this problem already know, we can see the following
```log
    --- End of inner exception stack trace ---
    at Azure.Identity.ImdsManagedIdentitySource.AuthenticateAsync(Boolean async, TokenRequestContext context, CancellationToken cancellationToken)
    at Azure.Identity.ManagedIdentityClient.AuthenticateAsync(Boolean async, TokenRequestContext context, CancellationToken cancellationToken)
```
After a bit of research on `ImdsManagedIdentitySource`, I found this page: https://docs.microsoft.com/en-us/azure/virtual-machines/windows/instance-metadata-service?tabs=windows#rate-limiting

> Rate limiting
In general, requests to IMDS are limited to 5 requests per second (on a per VM basis). Requests exceeding this threshold will be rejected with 429 responses. Requests to the [Managed Identity](https://docs.microsoft.com/en-us/azure/virtual-machines/windows/instance-metadata-service?tabs=windows#managed-identity) category are limited to 20 requests per second and 5 concurrent requests.

It looks like we are getting the 1 second timeouts in this specific case because "Instance Metadata Service" is throttling the requests when it sees 15 requests in parallel.

I changed the code to the following, to reuse the credential object in both connections and the problem is gone.
```c#
            var credential = new DefaultAzureCredential();
            services.AddSingleton(new CosmosClientBuilder(cosmosDbSettings.EndpointUrl, credential)
                .WithConnectionModeGateway()
                .WithCustomSerializer(new CustomCosmosSerializer())
                .Build());
            services.AddSingleton(new ServiceBusClient(serviceBusSettings.ConnectionString, credential));
```

On a side note, I tried Azure.Identity version 1.7.0-beta.1, but the improved caching mechanism is not prepared for this use case with so many parallel connections, and it ended with the same 1 second timeout issue.

**Comment by christothes** [comment] 2022-09-14 17:22
> On a side note, I tried Azure.Identity version 1.7.0-beta.1, but the improved caching mechanism is not prepared for this use case with so many parallel connections, and it ended with the same 1 second timeout issue.

Is this true only before reusing the same credential instance?

**Comment by heldersousa-planetpayment** [comment] 2022-09-14 23:20
@christothes 
Actually, reusing the credential object doesn't fully work. It reduced the number of calls to IMDS and sometimes it gets the token before flooding IMDS with more requests, but from time to time it still causes the same issue.

Given the limits of the IMDS regarding the number of calls per second, maybe it would make sense to create a `Semaphore` matching those limits or synchronize the method `AuthenticateAsync` in `ImdsManagedIdentitySource.cs` to make sure there is just one thread doing the call to IMDS at a time.
https://github.com/Azure/azure-sdk-for-net/blob/e5e03d7c40813ca178a92dd2d37bb9917570e510/sdk/identity/Azure.Identity/src/ImdsManagedIdentitySource.cs#L87

Something like:

```c#
[MethodImpl(MethodImplOptions.Synchronized)]
public async override ValueTask<AccessToken> AuthenticateAsync(bool async, TokenRequestContext context, CancellationToken cancellationToken)
{
    //(...)
}
```

**Comment by heldersousa-planetpayment** [comment] 2022-09-16 07:14
@christothes 

Actually, this code works fine:

```c#
services.AddSingleton(new CosmosClientBuilder(cosmosDbSettings.EndpointUrl, new DefaultAzureCredential())
    .WithConnectionModeGateway()
    .Build());
services.AddSingleton(new ServiceBusClient(serviceBusSettings.ConnectionString, new DefaultAzureCredential()));
```

I will still document my findings here in case someone is going through a similar issue.

I implemented a synchronized version of DefaultAzureCredential to make sure there were no parallel calls to fetch the token and I could still see the calls timing out after 1 second (my logs confirmed that there were no parallel calls to IMDS)

After some more research, in my specific use case, I believe the issue is caused by the way the pod is deleted and not by logic in `DefaultAzureCredential`. 
I use K9S (a great tool to manage Kubernetes clusters!) and there is a `kill (ctrl+k)` command and a `delete (ctrl+d)` command with some options like this:
![image](https://user-images.githubusercontent.com/107053506/190576480-c3a804c3-0c27-4414-9550-81db114e74e7.png)

If I use `kill` every time, I never see the problem happening. But if I use the `delete` option the issue happens pretty much every time. It looks like it is related to the way resources are deleted and finalizers are executed by Kubernetes (https://kubernetes.io/blog/2021/05/14/using-finalizers-to-control-deletion). I can't fully understand what is happening with IMDS in this case, but those timeouts are very noticeable.

**Comment by heldersousa-planetpayment** [comment] 2022-09-16 07:15
@christothes 

Actually, this code works fine:

```c#
services.AddSingleton(new CosmosClientBuilder(cosmosDbSettings.EndpointUrl, new DefaultAzureCredential())
    .WithConnectionModeGateway()
    .Build());
services.AddSingleton(new ServiceBusClient(serviceBusSettings.ConnectionString, new DefaultAzureCredential()));
```

I will still document my findings here in case someone is going through similar issue.

I implemented a synchronized version of DefaultAzureCredential to make sure there were no parallel calls to fetch the token and I could still see the calls timing out after 1 second (my logs confirmed that there were no parallel calls to IMDS)

After some more research, in my specific use case, I believe the issue is caused by the way the pod is deleted and not by logic in `DefaultAzureCredential`. 
I use K9S (a great tool to manage Kubernetes clusters!) and there is a `kill (ctrl+k)` command and a `delete (ctrl+d)` command with some options like this:
![image](https://user-images.githubusercontent.com/107053506/190576480-c3a804c3-0c27-4414-9550-81db114e74e7.png)

If I use `kill` every time, I never see the problem happening. But if I use the `delete` option the issue happens pretty much every time. It looks like it is related to the way resources are deleted and finalizers are executed by Kubernetes (https://kubernetes.io/blog/2021/05/14/using-finalizers-to-control-deletion). I can't fully understand what is happening with IMDS in this case, but those timeouts are very noticeable .

**Comment by christothes** [comment] 2022-10-18 17:02
We're trying to collect more information about the environments that experience excessive delays due to the `ManagedIdentityCredential` retry behavior in `DefaultAzureCredential`. Could any of the participants in this issue that are affected please provide your OS version, version of .NET, and execution environment (ex. local, Azure App Service, etc.)?

**Comment by heldersousa-planetpayment** [comment] 2022-10-18 23:56
Hi @christothes 

I can provide my details. 

My service is using `DefaultAzureCredential` without any other options and running the code on my laptop (local development), using VS 2022. 

I've done `az login` in the command line to cache my personal credentials to access Azure Resources. If I run it from the command line using `dotnet run` (not using VS 2022 at all), I get the same behaviour.

I observed the delay with connections to Azure Key Vault and Azure Service Bus. 

Following is sample code connecting to KeyVault. You can see from the logs that it takes 10 seconds when `ManagedIdentityCredential` is not excluded vs 3 seconds when `ManagedIdentityCredential` is excluded.

Sample code 1
```c#
using Azure.Identity;
using Azure.Security.KeyVault.Secrets;

Console.WriteLine($"{DateTime.Now} Creating client for key vault");
var secretClient = new SecretClient(new Uri("https://mykeyvault.vault.azure.net/"), new DefaultAzureCredential());
Console.WriteLine($"{DateTime.Now} Getting entry from key vault");
var v1 = secretClient.GetSecretAsync("key1").Result.Value;
Console.WriteLine($"{DateTime.Now} Done");
Console.WriteLine($"{DateTime.Now} Getting another entry from key vault");
var v2 = secretClient.GetSecretAsync("key2").Result.Value;
Console.WriteLine($"{DateTime.Now} Done");
```

Logs (10 seconds to get the first key)::
```
19/10/2022 00:37:41 Creating client for key vault
19/10/2022 00:37:41 Getting entry from key vault
19/10/2022 00:37:51 Done
19/10/2022 00:37:51 Getting another entry from key vault
19/10/2022 00:37:51 Done
````

Sample code 2 (`ExcludeManagedIdentityCredential = true`)
```c#
using Azure.Identity;
using Azure.Security.KeyVault.Secrets;

Console.WriteLine($"{DateTime.Now} Creating client for key vault");
var secretClient = new SecretClient(new Uri("https://mykeyvault.vault.azure.net/"), new DefaultAzureCredential(
    new DefaultAzureCredentialOptions()
    {
        ExcludeManagedIdentityCredential = true
    }));
Console.WriteLine($"{DateTime.Now} Getting entry from key vault");
var v1 = secretClient.GetSecretAsync("key1").Result.Value;
Console.WriteLine($"{DateTime.Now} Done");
Console.WriteLine($"{DateTime.Now} Getting another entry from key vault");
var v2 = secretClient.GetSecretAsync("key2").Result.Value;
Console.WriteLine($"{DateTime.Now} Done");
```

Logs (3 seconds to get first key):
```
19/10/2022 00:40:26 Creating client for key vault
19/10/2022 00:40:26 Getting entry from key vault
19/10/2022 00:40:29 Done
19/10/2022 00:40:29 Getting another entry from key vault
19/10/2022 00:40:29 Done
````


Packages in my project (same behaviour with Azure.Identity 1.8.0-beta.1 and 1.9.0-beta.1):
```
    <PackageReference Include="Azure.Identity" Version="1.7.0" />
    <PackageReference Include="Azure.Security.KeyVault.Secrets" Version="4.4.0" />
```

System Info
```
C:\Users\helder.sousa>dotnet --version
6.0.400

C:\Users\helder.sousa>systeminfo
OS Name:                   Microsoft Windows 10 Enterprise
OS Version:                10.0.19044 N/A Build 19044
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Member Workstation
OS Build Type:             Multiprocessor Free
System Manufacturer:       Dell Inc.
System Model:              Latitude 5420
System Type:               x64-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: Intel64 Family 6 Model 140 Stepping 1 GenuineIntel ~1805 Mhz
BIOS Version:              Dell Inc. 1.19.0, 16/06/2022
Windows Directory:         C:\WINDOWS
System Directory:          C:\WINDOWS\system32
Boot Device:               \Device\HarddiskVolume1
Total Physical Memory:     32,497 MB
Available Physical Memory: 8,189 MB
Virtual Memory: Max Size:  46,833 MB
Virtual Memory: Available: 14,541 MB
Virtual Memory: In Use:    32,292 MB
Hotfix(s):                 20 Hotfix(s) Installed.
                           [01]: KB5017022
                           [02]: KB4562830
                           [03]: KB4570334
                           [04]: KB4577266
                           [05]: KB4577586
                           [06]: KB4580325
                           [07]: KB5000736
                           [08]: KB5003791
                           [09]: KB5012170
                           [10]: KB5017308
                           [11]: KB5006753
                           [12]: KB5007273
                           [13]: KB5011352
                           [14]: KB5011651
                           [15]: KB5014032
                           [16]: KB5014035
                           [17]: KB5014671
                           [18]: KB5015895
                           [19]: KB5016705
                           [20]: KB5005699


C:\Users\helder.sousa> wmic cpu get caption, name, deviceid, numberofcores, maxclockspeed, status
Caption                                DeviceID  MaxClockSpeed  Name                                            NumberOfCores  Status
Intel64 Family 6 Model 140 Stepping 1  CPU0      1805           11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz  4              OK

```

**Comment by christothes** [comment] 2022-11-28 20:17
tracking this in #29471

**Closed by christothes** 2022-11-28 20:17 UTC
Labels: Client, Azure.Identity, customer-reported, question, needs-team-attention
