### ISSUE TITLE
[QUERY] [EventHub] Is it possible that the same event being sent by the EventHubBufferedProducerClient multiple times?

### ISSUE THREAD

**Issue by dxynnez** [Azure/azure-sdk-for-net#38332] opened 2023-08-23 10:51 UTC
### Library name and version

Azure.Messaging.EventHubs 5.7.5

### Query/Question

We are using the EventHubBufferedProducerClient to send events to eventhub asynchronously. And in the SendEventBatchSucceededAsync callbacks we record the number of messages that were successfully sent by the EventHubBufferedProducerClient . We also record the number of events that have been enqueued into the buffer, before calling the EventHubBufferedProducerClient #EnqueueEventsAsync.

However, the 2 number doesn't align and the number of the enqueued events turns out to be smaller than the events successfully sent out by the EventHubBufferedProducerClient . Is it possible that the EventHubBufferedProducerClient is sending the same event multiple times (hence the total SendEventBatchSucceededEventArgs#EventBatch.Count > the count of the enqueued events)?

**Comment by jsquire** [comment] 2023-08-23 13:11
Hi @dxynnez.  Thank you for reaching out and we regret that you're experiencing difficulties.  If I understand the scenario that you're describing, it does not indicate that an event was published multiple times.  The authoritative answer to "was this event published" is it appearing in the `SendEventBatchSucceededAsync` event.  Likewise, failures in the failure handler.  The buffer length - both per partition and the total - should not be interpreted as an exact measure.  

The buffer counts are mainly intended to answer the questions like "why does my enqueue call take so long to finish", "should I be seeing my handlers be called", and "is it safe to shut down my application".  They represent the point-in-time state of the client and will change frequently (and sometimes unpredictably) as batching and publishing take place in the background.  There will be operations in-flight, where the handlers have not yet been called but those events are no longer in the buffers.  Likewise, we may rebalance buffers while working, which will see the buffer count change unpredictably.

While uncommon, it is possible that an event will be published multiple times.  If a service operation fails or times out, it is implicitly retried.  In a small number of those scenarios, the service has received the batch of events, but the service acknowledgment was not seen by the client.  When retried, the same batch of events would have been sent and seen by the service as two distinct batches.

**Comment by dxynnez** [comment] 2023-08-24 05:14
> Hi @dxynnez. Thank you for reaching out and we regret that you're experiencing difficulties. If I understand the scenario that you're describing, it does not indicate that an event was published multiple times. The authoritative answer to "was this event published" is it appearing in the `SendEventBatchSucceededAsync` event. Likewise, failures in the failure handler. The buffer length - both per partition and the total - should not be interpreted as an exact measure.
> 
> The buffer counts are mainly intended to answer the questions like "why does my enqueue call take so long to finish", "should I be seeing my handlers be called", and "is it safe to shut down my application". They represent the point-in-time state of the client and will change frequently (and sometimes unpredictably) as batching and publishing take place in the background. There will be operations in-flight, where the handlers have not yet been called but those events are no longer in the buffers. Likewise, we may rebalance buffers while working, which will see the buffer count change unpredictably.
> 
> While uncommon, it is possible that an event will be published multiple times. If a service operation fails or times out, it is implicitly retried. In a small number of those scenarios, the service has received the batch of events, but the service acknowledgment was not seen by the client. When retried, the same batch of events would have been sent and seen by the service as two distinct batches.

Thanks for the promote response @jsquire ! Just to clarify, we never rely on the TotalBufferedEventCount, we use the EventBatch.Count of the EventBatchSendEventBatchFailedEventArgs & SendEventBatchSucceededEventArgs to get the count of the events that have been processed (either success or fail) by the producer.

Per my understanding, the SendEventBatchFailedAsync / the SendEventBatchSucceededAsync would always get fired when the producer is done with each batch (unless the program shutdown unexpectedly), are you saying that's not the case?

We also don't rely on the TotalBufferedEventCount to count the total events that have been enqueued - we record the number of events for each EnqueueEventsAsync call so it should have nothing to do with the dynamic buffer.

We totally understand the semantic of at least once delivery for eventhub. We are just wondering if the duplicates would surface to the callback handler as it's a bit weird that we only enqueue x events but somehow the callback is reporting back that x+y events have been processed.

**Comment by jsquire** [comment] 2023-08-24 11:52
Hi @dxynnez.  Thank you for the clarification - that changes things.  The handlers are fired only once, after the final state of the operation is known.  The items in those batches reflect those in the actual batch used for the service operation - they should reflect both the state of the Event Hub and client exactly.  This is something that we have tests at multiple levels verifying, and both the short and long run periods look clean.

The one thing that I'd note is that the version of the library that you've mentioned, 5.6.2, does not appear correct.  The buffered producer was not introduced until 5.7.0.  Can you confirm the version that you're using?

 I've been unable to reproduce the behavior that you're describing using the latest package- is there anything that you can share that may help do so?  ICollecting SDK logs during the behavior would help us to see what the internals of the producer are doing and may help to understand the scenario.  If you're willing, a 5-minute slice of verbose logs filtered to the set below would be very much appreciated.  Discussion of how to capture SDK logs can be found [here](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/eventhub/Azure.Messaging.EventHubs/samples/Sample10_AzureEventSourceListener.md).

**Log Source:  Azure-Messaging-EventHubs**

- All Errors
- All Warnings
- Id: 3 (Event Publish Start)
- Id: 4 (Event Publish Complete)
- Id: 5 (Event Publish Error)
- Id: 70 (Buffered Producer Background Publishing Start)
- Id: 71 (Buffered Producer Background Publishing Start Complete)
- Id: 72 (Buffered Producer Background Publishing Start Error)
- Id: 73 (Buffered Producer Background Publishing Stop)
- Id: 74 (Buffered Producer Background Publishing Stop Complete)
- Id: 75 (Buffered Producer Background Publishing Stop Error)
- Id: 80 (Buffered Producer Enqueued)
- Id: 81 (Buffered Producer Publishing Task Start)
- Id: 82 (Buffered Producer Publishing Task Restart)
- Id: 83 (Buffered Producer Publishing Task Error)
- Id: 88 (Buffered Producer Publish Batch Start)
- Id: 89 (Buffered Producer Publish Batch Complete)
- Id: 90 (Buffered Producer Publish Batch Error)
- Id: 94 (Buffered Producer OnSuccess Invoke)
- Id: 95 (Buffered Producer OnSuccess Invoke Complete)
- Id: 96 (Buffered Producer OnSuccess Invoke Error)
- Id: 97 (Buffered Producer  OnFailure Invoke)
- Id: 98 (Buffered Producer OnFailure Invoke Complete)
- Id: 99 (Buffered Producer OnFailure Invoke Error)

**Comment by dxynnez** [comment] 2023-08-28 04:52
> Hi @dxynnez. Thank you for the clarification - that changes things. The handlers are fired only once, after the final state of the operation is known. The items in those batches reflect those in the actual batch used for the service operation - they should reflect both the state of the Event Hub and client exactly. This is something that we have tests at multiple levels verifying, and both the short and long run periods look clean.
> 
> I've been unable to reproduce the behavior that you're describing using the latest package- is there anything that you can share that may help do so? ICollecting SDK logs during the behavior would help us to see what the internals of the producer are doing and may help to understand the scenario. If you're willing, a 5-minute slice of verbose logs filtered to the set below would be very much appreciated. Discussion of how to capture SDK logs can be found [here](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/eventhub/Azure.Messaging.EventHubs/samples/Sample10_AzureEventSourceListener.md).
> 
> The one thing that I'd note is that the version of the library that you've mentioned, 5.6.2, does not appear correct. The buffered producer was not introduced until 5.7.0. Can you confirm the version that you're using?
> 
> **Log Source: Azure-Messaging-EventHubs**
> 
> * All Errors
> * All Warnings
> * Id: 3 (Event Publish Start)
> * Id: 4 (Event Publish Complete)
> * Id: 5 (Event Publish Error)
> * Id: 70 (Buffered Producer Background Publishing Start)
> * Id: 71 (Buffered Producer Background Publishing Start Complete)
> * Id: 72 (Buffered Producer Background Publishing Start Error)
> * Id: 73 (Buffered Producer Background Publishing Stop)
> * Id: 74 (Buffered Producer Background Publishing Stop Complete)
> * Id: 75 (Buffered Producer Background Publishing Stop Error)
> * Id: 80 (Buffered Producer Enqueued)
> * Id: 81 (Buffered Producer Publishing Task Start)
> * Id: 82 (Buffered Producer Publishing Task Restart)
> * Id: 83 (Buffered Producer Publishing Task Error)
> * Id: 88 (Buffered Producer Publish Batch Start)
> * Id: 89 (Buffered Producer Publish Batch Complete)
> * Id: 90 (Buffered Producer Publish Batch Error)
> * Id: 94 (Buffered Producer OnSuccess Invoke)
> * Id: 95 (Buffered Producer OnSuccess Invoke Complete)
> * Id: 96 (Buffered Producer OnSuccess Invoke Error)
> * Id: 97 (Buffered Producer  OnFailure Invoke)
> * Id: 98 (Buffered Producer OnFailure Invoke Complete)
> * Id: 99 (Buffered Producer OnFailure Invoke Error)

I just double-checked - you are right we are using the 5.7.5 version.

As much as I would love to provide the logs, I don't know at which exact time point the behavior happened - in our production, I am only seeing small deviations out of 6000+ events, and it's not happening every day. With my test app which sends out synthetic events every 5 mins I also can't get it to reproduce.

Any other way to look into this further?

**Comment by dxynnez** [comment] 2023-08-28 05:50
I just realized that we have another code path is using the same producer so the deviations might come from that part.

So just to clarify, the total events that have been enqueued should be greater than or equals to the number of events signaled by the handler (through the SendEventBatchSucceededEventArgs#EventBatch.Count & SendEventBatchFailedEventArgs#EventBatch.Count), as the handlers would only be fired once as far as the enqueued events are concerned - is this a true statement?

**Comment by jsquire** [comment] 2023-08-28 14:42
> Any other way to look into this further?

The only other way would be a self-contained repro.   It looks like neither of us has been able to come up with a way to repro what you're seeing on demand.

> So just to clarify, at any given point, the total number of events signaled by the handler (through the SendEventBatchSucceededEventArgs#EventBatch.Count & SendEventBatchFailedEventArgs#EventBatch.Count) should be less than or equals to the total events that have been enqueued so far, as the handlers would only be fired once as far as the enqueued events are concerned - is this a true statement?

Yes, this is correct.  The totals from the batch counts in the success and failure handlers should equal the number of events accepted when enqueuing.

**Comment by jsquire** [comment] 2023-08-28 14:44
I'm going to leave this open and tagged for more information, in case logs become available or you find a way to repro.  Automation will close this out in a couple of weeks if we continue to be stalled, but we can reopen should repro/logs become available.

**Closed** 2023-09-06 13:29 UTC
Labels: Event Hubs, Client, needs-author-feedback, customer-reported, question, no-recent-activity
