### ISSUE TITLE
[BUG] KustoDatabaseCollection CreateOrUpdateAsync returning ResourceNotFound - false failure

### ISSUE THREAD

**Issue by adelKhatib** [Azure/azure-sdk-for-net#35594] opened 2023-04-16 13:09 UTC
### Library name and version

Azure.ResourceManager.Kusto 1.3.0

### Describe the bug

when calling the KustoDatabaseCollection.CreateOrUpdateAsync  with **WaitUntil.Completed** we are getting this exception:
The resource with identifier '/subscriptions/\*\*/resourceGroups/\*\*/providers/Microsoft.Kusto/Clusters/\*\*/Databases/\*\*' is not found.
Status: 404 (Not Found)
ErrorCode: ResourceNotFound

   at Azure.Core.OperationInternal`1.GetResponseFromState(OperationState`1 state)
   at Azure.Core.OperationInternal`1.<UpdateStatusAsync>d__20.MoveNext()
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Azure.Core.OperationInternalBase.<UpdateStatusAsync>d__13.MoveNext()
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Azure.Core.OperationPoller.<WaitForCompletionAsync>d__11.MoveNext()
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Azure.Core.OperationInternalBase.<WaitForCompletionResponseAsync>d__19.MoveNext()
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Azure.Core.OperationInternal`1.<WaitForCompletionAsync>d__19.MoveNext()
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Azure.Core.OperationInternal`1.<WaitForCompletionAsync>d__15.MoveNext()
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Azure.ResourceManager.Kusto.KustoDatabaseCollection.<CreateOrUpdateAsync>d__7.MoveNext()
   
   **but after waiting 1 minute, the database was actually successfully created!**

### Expected behavior

when **WaitUntil.Completed** is provided, the operation is expected to be awaited until the long-running operation has completed without unexpected errors.

### Actual behavior

exception is thrown, but the operation is actually succeeded after waiting up to one additional minute.

### Reproduction Steps

initialize ArmClient with token credentials and define the cluster resource identifier then :
`
var kustoClusterResource = new ArmClient(tokenCredentials).GetKustoClusterResource(clusterResourceIdentifier);  
await kustoClusterResource.GetKustoDatabases().CreateOrUpdateAsync(WaitUntil.Completed,databaseName,databaseData);
`

**Comment by jsquire** [comment] 2023-04-16 14:24
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by adelKhatib** [comment] 2023-04-18 21:02
@jsquire @ArthurMa1978 , Any updates? 
Thanks!

**Comment by msSameerEd** [comment] 2023-04-22 10:51
I am experiencing the exact same issue where an exception of "not found" is always thrown when attempting to create a Kusto database. However, upon retrying (after couple of minutes) the creation process, it eventually succeeds. Therefore, I fully concur with @adelKhatib 's assertion that **WaitUntil.Completed** does not function as anticipated. @ArthurMa1978 , what is your opinion on this matter? This issue is currently preventing me from proceeding with the release. @jsquire

**Comment by ArthurMa1978** [comment] 2023-04-24 07:53
Thank you for your feedback, we're working on it.

**Comment by live1206** [comment] 2023-04-24 10:07
We have a [test](https://github.com/Azure/azure-sdk-for-net/blob/e8455f06988a841b362d0c066a296c4b075865fe/sdk/kusto/Azure.ResourceManager.Kusto/tests/Scenario/KustoDatabaseTests.cs#L32) to cover Kusto database creation, it works as expected. And also, I tried to create a Kusto database lively, it works as expected as well.

@adelKhatib Does this happen randomly?
@msSameerEd As you mentioned it always returns 404 and succeeded after waiting for some time, did you try to create a new database after the waiting? Then, it seems random failure from server side, not SDK error.

**Comment by adelKhatib** [comment] 2023-04-24 13:13
@live1206 , this happen consistently on the first try, the issue is obviously related to the status polling, the exception of “Not found” prevent the thread from waiting until completion of the creation, despite that the creation process is still in progress.
Can you please try to create a database (lively) with a name that you never tried.

**Comment by live1206** [comment] 2023-04-25 09:13
> @live1206 , this happen consistently on the first try, the issue is obviously related to the status polling, the exception of “Not found” prevent the thread from waiting until completion of the creation, despite that the creation process is still in progress. Can you please try to create a database (lively) with a name that you never tried.

@adelKhatib I don't think it always returns 404 on the first try since I managed to create a Kusto database with the SDK. And as I mentioned there is an existing [test](https://github.com/Azure/azure-sdk-for-net/blob/e8455f06988a841b362d0c066a296c4b075865fe/sdk/kusto/Azure.ResourceManager.Kusto/tests/Scenario/KustoDatabaseTests.cs#L32) for this case successfully running. With the [recorded service response](https://github.com/Azure/azure-sdk-for-net/blob/e8455f06988a841b362d0c066a296c4b075865fe/sdk/kusto/Azure.ResourceManager.Kusto/tests/SessionRecords/KustoDatabaseTests/DatabaseTests()Async.json) in place, the test could pass with SDK.

I tried to create a database for 4 times, always got 200
```
            var db = await Cluster.GetKustoDatabases().CreateOrUpdateAsync(WaitUntil.Completed, databaseName, databaseDataCreate);
            var response = db.GetRawResponse();
```
![image](https://user-images.githubusercontent.com/5196139/234230634-8165dd6a-4bb8-4ade-a342-b48f244109a9.png)

> the issue is obviously related to the status polling

This is not accurate, the implementation for long-running operations is generated by [autorest.csharp](https://github.com/Azure/autorest.csharp/blob/feature/v3/src/AutoRest.CSharp/Mgmt/Generation/MgmtLongRunningInterimOperationWriter.cs), the status polling mechanism is the same for all services & operations.

Please let me know if I am missing any information from you to reproduce this error.

**Comment by live1206** [comment] 2023-04-25 09:41
@adelKhatib As offline discussed, please try to get the traffic log of service response while you get 404 during creation, so that we can figure out the next step.

**Comment by live1206** [comment] 2023-04-25 10:33
The root cause is from service response.

LRO is working like this:
- Keep polling to get completed status of the operation
- Get the created resource

From the log of @adelKhatib, it keeps polling of the operation status until it's completed. 
And when it tries to get the created database back, it returns 404 from server side, which is not expected.

**Comment by msSameerEd** [comment] 2023-04-28 20:11
@live1206, @ilayrn, and @orhasban, I am experiencing a persistent issue that is incredibly frustrating. This problem has caused a significant delay in implementing a crucial feature in my project, and I am counting on your prompt assistance in resolving it. I would greatly appreciate it if you could resolve this matter as soon as possible.
 
@live1206 , regarding your last response, I'm a bit confused about what you mean by 'server side', which team is responsible for it?, Can you explain? Also, any ideas on how I can figure out what's going on with this issue? Like, can I get some log traces or something? By the way, do you know of any quick fixes to help me deal with this?

**Comment by michaelshikh07** [comment] 2023-05-03 11:29
Hi everyone,
This was an error on the Kusto backend side (unrelated to c# SDK client)
Mostly affecting internal Microsoft consumers.

We are deploying a HF  by the end of the week, fixing the issue

**Closed** 2023-05-10 16:36 UTC
Labels: Service Attention, Mgmt, customer-reported, question, Kusto, issue-addressed
