### ISSUE TITLE
AmbiguousMatchException at SearchServiceClient

### ISSUE THREAD

**Issue by ahmettaha** [Azure/azure-sdk-for-net#2516] opened 2016-11-01 01:03 UTC
On the latest search preview, I'm trying to create a new SearchServiceClient like below

`new SearchServiceClient(searchServiceName, new SearchCredentials(apiKey));`

then I get the following error. However, this is only on the server. What is the problem?

```
[AmbiguousMatchException: Multiple custom attributes of the same type found.]
   System.Attribute.GetCustomAttribute(Assembly element, Type attributeType, Boolean inherit) +122
   Microsoft.Rest.ServiceClient`1.get_FrameworkVersion() +103
   Microsoft.Rest.ServiceClient`1.SetDefaultUserAgentInfo() +177
   Microsoft.Rest.ServiceClient`1.SetUserAgent(String productName, String version) +50
   Microsoft.Azure.Search.SearchServiceClient..ctor(String searchServiceName, SearchCredentials credentials) +79
```

**Comment by brjohnstmsft** [comment] 2016-11-01 01:21
@ahmettaha This looks like an issue with the Microsoft.Rest.ClientRuntime library. Are you able to reproduce the problem with any other Azure SDKs that take a dependency on the same version of Microsoft.Rest.ClientRuntime that the Search SDK does?

@shahabhijeet Digging through the history, I see that you're the author of `ServiceClient.FrameworkVersion`. Any idea what the problem could be?

**Comment by ahmettaha** [comment] 2016-11-01 01:23
I dont use ClientRuntime for anything else. Also, this error does not happen on my local compute simulator. It happens on azure cloud service deploy. I'm not sure if it means anything.

**Comment by ahmettaha** [comment] 2016-11-01 01:36
ok. BotFramework is also using it apperantly, and I got the same error when using it.

**Comment by ahmettaha** [comment] 2016-11-01 02:07
ok. got it fixed. I downgraded Microsoft.Rest.ClientRuntime from 2.3.3 to 2.3.2.

**Comment by brjohnstmsft** [comment] 2016-12-01 16:34
Possibly related: https://github.com/Azure/autorest/issues/1542

**Comment by jeradrose** [comment] 2016-12-07 00:34
I was not able to downgrade Microsoft.Rest.ClientRuntime from 2.3.4 to 2.3.2 due to Microsoft.Azure.Search 3.0.1 having a dependency on 2.3.4. So I had to downgrade Microsoft.Azure.Search to 1.1.3.

**Comment by brjohnstmsft** [comment] 2016-12-08 02:07
@jeradrose Are you also using Application Insights by any chance?

**Comment by jeradrose** [comment] 2016-12-08 02:34
On Azure, and client-side, yes. But not server-side (SDK).

**Comment by rarobe** [comment] 2016-12-08 11:39
Also receiving AmbiguousMatchException when initializing SearchServiceClient after upgrading to Microsoft.Azure.Search 3.0.1.

Application Insights is configured on my WebRole properties to send diagnostic data to App Insights - and I can confirm that when I disabled Application Insights on my web role properties I no longer receive the AmbiguousMatchException (App Insights SDK is still installed in my web project and collecting requests but not sending additional diagnostic data).

**Comment by brjohnstmsft** [comment] 2016-12-08 19:17
@jeradrose

> On Azure, and client-side, yes. But not server-side (SDK).

And you observe the `AmbiguousMatchException` in all three cases...?

**Comment by brjohnstmsft** [comment] 2016-12-08 21:08
The Application Insights team [are working on a fix](https://github.com/Azure/autorest/issues/1542#issuecomment-265832668):

> We know the root cause and working on a fix. We expect the fix shipped next week. Meanwhile the work around is to disable Application Insights Azure WebSite extension or StatusMonitor. Please escalate using CSS channel if you need a hotfix sooner.

**Comment by markcowl** [comment] 2017-01-20 18:49
@brjohnstmsft Assignign to you to resolve when the root issue is resolved.  Please reassign if appropriate.

**Comment by wagsousa** [comment] 2017-01-23 16:42
Updating the App Service - Application Insights extension to the latest version solves the issue.
Azure Portal > App Service > Extensions > click on Application Insights > click on Update

**Comment by brjohnstmsft** [comment] 2017-02-08 19:30
The root issue has been resolved. See [the related issue](https://github.com/Azure/autorest/issues/1542) for details on how to deploy the fix.

**Closed by brjohnstmsft** 2017-02-08 19:30 UTC
Labels: Search
