### ISSUE TITLE
Error when using VS 2015 as remote debugger

### ISSUE THREAD

**Issue by lkempf** [Azure/azure-sdk-for-net#1255] opened 2015-07-14 20:33 UTC
Using WebsiteManagementClient.GetSiteWithCache() on a WebApp with remote debugging with VS 2015 causes an error. I had this problem with azure-powershell but since the azure-powershell team chose to ignore the bug (or didn't want to update it) I tracked it down to this lib myself. This is coming from https://github.com/Azure/azure-powershell/issues/462.
This can probably be fixed be regenerating the code for using Websites.

**Comment by markcowl** [comment] 2015-08-18 18:51
@FuUuUuUoO Can you please provide more detail?  What is the error that you are getting?  Without more information, we cannot track this down.

**Comment by storafrid** [comment] 2015-10-28 13:43
The issue is probably that this line fails:
https://github.com/Azure/azure-sdk-for-net/blob/master/src/ServiceManagement/WebSite/WebSiteManagement/Generated/WebSiteOperations.cs#L3673

It does so due to the enum not containing a value for `VS2015` I believe (see https://github.com/Azure/azure-sdk-for-net/blob/21db6e5490e66af39a9c6dbf0ad10650d9ca037b/src/ResourceManagement/WebSite/WebSiteManagement/Generated/Models/RemoteDebuggingVersion.cs for the enum).

This issue is probably currently the reason why a lot of people think that Visual Studio Online sucks. By default the web app deployment agent task doesn't work if you are working from VS 2105. That's why I have made an effort trying to pin this down.

I suggest adding VS2016 while you are at it... it will be released eventually too.

**Comment by ielcoro** [comment] 2015-12-13 19:27
This is a huge annoying issue to us, 

We need to remeber to disable remote debugging when using VS2015 (enabling first a known value like VS2013 and then disabling it all together) so we can publish our sites from powershell.

When using VSTS build, if a developer does a remote debugging session with VS2015, most of the time breaks the continuous integration build we have setup.

It's December now, VS is on Update 1, and this is open since 14 Jul... at least, include the enum value an release and update...

**Comment by andybatescc** [comment] 2016-01-06 13:16
Also came across this for a site where I had dabbled with remote profiling from VS2015
https://azure.microsoft.com/en-gb/blog/remote-profiling-support-in-azure-app-service/

**Comment by andybatescc** [comment] 2016-01-22 10:57
As remote profiling is now being promoted more this increases the likelihood of this occurring. Really needs to be fixed.

**Comment by DovydasNavickas** [comment] 2016-01-22 20:53
Had this yesterday during a critical moment with our production app lagging behind, because in Dev environment we enabled Remote Debugging and didn't dare to promote it to production, while CI was failing.

Solution described [here](http://www.brandonmartinez.com/2015/07/14/resolve-a-requested-value-vs2015-was-not-found-get-azurewebsite-error-in-powershell/) helped, but it is even more outrageous.

I guess Azure developers nowadays have to have been participating in Hogwarts School of Witchcraft and Wizardry with this kind of magic solutions needed.

Please fix it ASAP :clap:

**Comment by markcowl** [comment] 2016-02-16 18:02
@DovydasNavickas @lkempf @storafrid @ielcoro @andybatescc  Hi all, this is a very simple issue that should have been fixed long ago.  Unfortunately, since this impacts the RDFE (and not the ARM) client, it looks like it has been deprioritized by the feature team.  We'll work to get a fix out ASAP.

**Comment by DovydasNavickas** [comment] 2016-02-16 18:29
Good to hear. We're the ones who already found out the issue and know the cure, so it's not that painful anymore. But for people who are still to find this out... It should be prioritized at the top, if it's a small and simplr issue :+1:

I guess there should be more involvement from RDFE team in this GitHub repository issues list.
Also, is there a separate place to report issues for RDFE specifically? Can't seem to find it...

**Comment by markcowl** [comment] 2016-02-25 02:16
Fix was just checked in to master, released on nugget version 4.5.0 (https://www.nuget.org/packages/Microsoft.WindowsAzure.Management.WebSites/4.5.0-prerelease ) and checked into powershell (finally)

**Closed by markcowl** 2016-02-25 02:16 UTC
Labels: Websites
