### ISSUE TITLE
readme.md issues in AzConfig

### ISSUE THREAD

**Issue by AlexanderSher** [Azure/azure-sdk-for-net#8431] opened 2019-10-25 06:22 UTC
- [x] [Introduction](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/appconfiguration/Azure.Data.AppConfiguration/README.md#azure-app-configuration-client-library-for-net): list of the things client library can used for can have references to documentation pages
- [x] [Introduction](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/appconfiguration/Azure.Data.AppConfiguration/README.md#azure-app-configuration-client-library-for-net): missing "Source Code", "API reference documentation" and "Samples" links
- [x] [Getting started / Prerequisites](https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/appconfiguration/Azure.Data.AppConfiguration#install-the-package): Need to have list-formatted prerequisites and correct headers (see [KeyVault.Keys](https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/keyvault/Azure.Security.KeyVault.Keys#prerequisites))
- [x] [Key concepts / Configuration setting](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/appconfiguration/Azure.Data.AppConfiguration/README.md#configuration-setting): `Label` property in the second paragraph needs a link to the reference page
- [x] [Key concepts / Configuration setting](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/appconfiguration/Azure.Data.AppConfiguration/README.md#configuration-setting): List of properties should be either formatted as C# or as a list of links to the reference pages.
- [x] [Troubleshooting / General](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/appconfiguration/Azure.Data.AppConfiguration/README.md#general): **General** is the only subsection here, maybe it isn't needed?
- [x] [Next Steps / Project-to-project references](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/appconfiguration/Azure.Data.AppConfiguration/README.md#project-to-project-references): Do we use `UseProjectReferenceToAzureBase` anywhere in master?
- [x] No **Contributing** section

**Comment by AlexGhiondea** [comment] 2019-10-25 17:44
@annelo-msft and @AlexanderSher can you please work through these issues?

**Comment by annelo-msft** [comment] 2019-10-25 18:15
On it.

**Comment by annelo-msft** [comment] 2019-10-25 18:18
Contributing, dupe of #7227.

**Closed** 2019-10-25 21:52 UTC
Labels: AzConfig, Client
