### ISSUE TITLE
Memory Leak in RetryDelegatingHandler.cs

### ISSUE THREAD

**Issue by Sanchia** [Azure/azure-sdk-for-net#2593] opened 2016-11-29 12:07 UTC
Hi, 

I have a Windows service app that throws an OutOfMemoryException. After some debugging I found the issue to be an ever growing array of objects, which is RetryingPolicy.Retrying._invocationList as shown in the screen grabs:

![image2016-11-28 17-33-59](https://cloud.githubusercontent.com/assets/24245343/20708665/ba81e10a-b639-11e6-9f1a-42dfe67dcd6b.png)
![image2016-11-28 17-35-13](https://cloud.githubusercontent.com/assets/24245343/20708664/ba80a07e-b639-11e6-9250-005fcfbd6a28.png)

These appear to be troublesome lines of code: 

    protected override async Task<HttpResponseMessage> SendAsync(HttpRequestMessage request,
	CancellationToken cancellationToken)
    {
      RetryPolicy.Retrying += (sender, args) =>
      {
        if (Retrying != null)
        {
          Retrying(sender, args);
        }
      };
    .
    .
    .

I see some attempts to fix this problem have been made in a recent version of the code (version 2.3.4 released 22-11-2016), in the form of a finally block here:

    finally
    {
      if (Retrying != null)
      {
        foreach (EventHandler<RetryingEventArgs> d in Retrying.GetInvocationList())
        {
          Retrying -= d;
        }
      }
    }

However this still does not work, I think the check should be RetryPolicy.Retrying != null.
Instead of Retrying != null. Or since an event handler is always added on entry to the method, simply assume that RetryPolicy.Retrying is not null.

Thanks,
Sanchia.

**Comment by markcowl** [comment] 2016-12-02 18:33
### Description
- [ ] Reproduce issue and add test to catch
- [ ] Determine P0 stress scenarios to cover for client runtime
- [ ] File issues for fix and for additional stress scenarios

### Cost: 4

**Comment by MarkusGeigerITD** [comment] 2018-02-09 12:22
We suffer from the same problem.
From what I've seen in some memory dumps our team got back from production servers, the leak is not in the **RetryDelegatingHandler.Retrying** event (b/c the finally block quoted by @Sanchia in the original post seems to work), but in the **RetryPolicy.Retrying** event.

An anonymous handler to this event is (again, as @Sanchia already noted) added with each roundtrip, but never removed.

My question is: Since the RetryDelegatingHandler and the RetryPolicy are in a one-to-one relationship why is **RetryPolicy.Retrying** an multicast delegate (aka event) in the first place?
Wouldn't it be sufficient to have a regular (singlecast) delegate for **RetryPolicy.Retrying**?

In fact, I have removed the _event_ keyword from **RetryPolicy.Retrying** as follows

`
        /// <summary>
        /// An instance of a callback delegate that will be invoked whenever a retry condition is encountered.
        /// </summary>
        public EventHandler<RetryingEventArgs> Retrying;
`

and added the following lines to the top of **RetryDelegatingHandler.SendAsync()**

`
       protected override async Task<HttpResponseMessage> SendAsync(HttpRequestMessage request,
            CancellationToken cancellationToken)
        {
          if (RetryPolicy.Retrying == null)
          {
            RetryPolicy.Retrying = (sender, args) =>
            {
              if (Retrying != null)
              {
                Retrying(sender, args);
              }
            };
          }
`

and the memory leak went away. 
Could anyone please review and comment on this suggestion?
Thanks a lot!
Markus

**Comment by shraboin** [comment] 2018-09-23 21:34
@shahabhijeet I have a support case  where a customer believes they are still facing this issue. I tried looking you up on skype. Could you please reach out to me through Teams/Skype? Thanks,
Shane

**Comment by shahabhijeet** [comment] 2018-10-01 17:39
This has been [fixed](https://github.com/Azure/azure-sdk-for-net/pull/4775) and released, you will need the following version to get the fix
- https://www.nuget.org/packages/Microsoft.Rest.ClientRuntime/2.3.14
- https://www.nuget.org/packages/Microsoft.Rest.ClientRuntime.Azure/3.3.16

**Closed by shahabhijeet** 2018-10-01 17:39 UTC
Labels: Investigate, Sprint Candidate, Team
