### ISSUE TITLE
[BUG] Azure.Monitor.OpenTelemetry.AspNetCore 1.0.0-beta.6 does not work

### ISSUE THREAD

**Issue by lmolkova** [Azure/azure-sdk-for-net#38687] opened 2023-09-13 23:46 UTC
### Library name and version

Azure.Monitor.OpenTelemetry.AspNetCore 1.0.0-beta.6

### Describe the bug

When using Azure.Monitor.OpenTelemetry.AspNetCore 1.0.0-beta.6 in .NET 7 minimal API ASP.NET Core app running on localhost, my application does not start within ~30 sec.

It works perfectly fine with Azure.Monitor.OpenTelemetry.AspNetCore 1.0.0-beta.5.

If I debug the application, I can see a bunch of `HttpRequestException` potentially trying to resolve resources

<img width="508" alt="image" src="https://github.com/Azure/azure-sdk-for-net/assets/2347409/cef8fffd-4ffd-4d32-9655-9a02f576f9a4">

### Expected behavior

Application starts and reports telemetry

### Actual behavior

Application does not start

### Reproduction Steps

app:

```csharp
using Azure.Monitor.OpenTelemetry.AspNetCore;
var builder = WebApplication.CreateBuilder(args);

builder.Services.AddOpenTelemetry()
    .UseAzureMonitor(o => o.ConnectionString = "...");

var app = builder.Build();
app.MapGet("/ping", async () =>
{
    await new HttpClient().GetStringAsync("https://microsoft.com");
    return new { message = "hello"};
});

app.Run();
```

```xml
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Monitor.OpenTelemetry.AspNetCore" Version="1.0.0-beta.6" />
  </ItemGroup>

</Project>
```

**Comment by cijothomas** [comment] 2023-09-14 14:25
Is the app not starting at all (i.e crashes with exception), or it starts and works fine, but takes much longer time?

**Comment by lmolkova** [comment] 2023-09-14 14:50
it does not crash, I assume it'll eventually start after it exhausted all retries and timeouts trying to get IMDS from VM, but I did not wait long enough.

Either way, it seems VM resource detector is blocking and needs way smaller timeout and no retries.

**Comment by cijothomas** [comment] 2023-09-14 15:03
Since Resource must be added before building the Providers, this is going to be an issue. Any Detector taking time will add to the startup time.... (Azure/AWS all should have same challenges..)
Don't think there is any retry logic, so it must be purely the timeout waiting for the response.

Some possible (not perfect) mitigations:

It might be possible for the distro to detect that its is running in appservice (env var check), [and then do not add VM detectors](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/monitor/Azure.Monitor.OpenTelemetry.AspNetCore/src/OpenTelemetryBuilderExtensions.cs#L98-L99).

Or modify the AzureVM detector itself to quickly bail out, similar to what [legacy sdks ](https://github.com/microsoft/ApplicationInsights-dotnet/blob/main/WEB/Src/WindowsServer/WindowsServer/AzureRoleEnvironmentTelemetryInitializer.cs#L27-L30)do.

**Comment by vishweshbankwar** [comment] 2023-09-14 15:40
https://github.com/open-telemetry/opentelemetry-dotnet-contrib/pull/1307
This change is not released yet. This should help but we are still looking for ways to further reduce the start up time.

**Comment by lmolkova** [comment] 2023-09-14 16:16
it seems there is no timeout set on that client https://github.com/open-telemetry/opentelemetry-dotnet-contrib/blob/main/src/OpenTelemetry.ResourceDetectors.Azure/AzureVmMetaDataRequestor.cs#L31  and the default value is [100 sec](https://learn.microsoft.com/en-us/dotnet/api/system.net.http.httpclient.timeout?view=net-7.0)! 

the IMDS endpoint is local, so it's really reliable. 1 sec would probably be enough.

It's something that would block onboarding and work in dev environment and has to be fixed.

**Comment by TimothyMothra** [comment] 2023-09-14 17:32
> [open-telemetry/opentelemetry-dotnet-contrib#1307](https://github.com/open-telemetry/opentelemetry-dotnet-contrib/pull/1307) This change is not released yet. This should help but we are still looking for ways to further reduce the start up time.

@vishweshbankwar That PR is from a month ago. Do you know when the next release will be?

**Comment by TimothyMothra** [comment] 2023-09-14 17:33
> it seems there is no timeout set on that client 

Thanks for investigating @lmolkova, would you be able to submit a PR for the quick fix?

**Comment by lmolkova** [comment] 2023-09-14 17:52
Not this week (and I'm OOf on the next one). The fix is short and simple, but the key part here is testing it - I wonder why it was not detected via automation.

**Comment by vishweshbankwar** [comment] 2023-09-14 18:00
> > it seems there is no timeout set on that client
> 
> Thanks for investigating @lmolkova, would you be able to submit a PR for the quick fix?

@TimothyMothra We can get the fix done and request for release next week.

**Comment by vishweshbankwar** [comment] 2023-09-14 18:02
@lmolkova - Distro should still work with delayed start up time, do you see different behavior? 

> I wonder why it was not detected via automation

Are you referring to tests?

**Comment by lmolkova** [comment] 2023-09-14 22:49
> @lmolkova - Distro should still work with delayed start up time, do you see different behavior?

I was not patient enough to wait and I assume it's unreasonable to expect production applications not running on app serivce of AzureVM start time to take 100 sec.

> Are you referring to tests?

Yep, do we have integration tests for distro? If so, why we didn't detect it?

**Comment by TimothyMothra** [comment] 2023-09-14 22:54
> Yep, do we have integration tests for distro? If so, why we didn't detect it?

The integration tests run in an Azure VM and don't have the delay.

**Comment by TimothyMothra** [comment] 2023-09-20 22:01
I believe this issue can be closed. The root cause was related to Timeouts for Azure VM Metadata service. This has been fixed in both the Exporter and ResourceDetector.

**Closed by TimothyMothra** 2023-09-20 22:01 UTC
Labels: Service Attention, Client, Monitor - Exporter
