### ISSUE TITLE
[FEATURE REQ] Storage: Better Stream support

### ISSUE THREAD

**Issue by yahorsi** [Azure/azure-sdk-for-net#13392] opened 2020-07-10 21:34 UTC
Hi Guys,

Using latest SDK: 12.4.4

We're migrating to the Azure and was a bit surprised the SDK does not have "full" Stream support.
Imagine we have following code that writes stream:

```CSharp
            using (var fileStream = fileProvider.CreateOutputStream(fullFilePath))
            using (var outputStream = new ZipOutputStream(fileStream))
            using (var writer = new StreamWriter(outputStream))
            {
                outputStream.PutNextEntry(new ZipEntry($"{reportTitle}.{FileExtensionConstant.CSV}"));
                new CommissionHistoryCsvExporter().ExportToCsv(selectQuery, queryParams, writer);
            }

```

In the code above, CreateOutputStream, creates file based stream.
With current API we cannot migrate to the Azure blob storage without significant code changes, currently to upload the blow there is only one method Upload that accepts stream that must "pre exists". In other words, you have to have a stream already, and in order to get one you must create it on the memory or file. Creating it on memory is not acceptable for us as files might be big, creating on the file system in not acceptable because of the load and space limitations.

Suggestions:
Add API to expose upload/download stream explicitly.
Like:
1. Stream .GetUploadStream()
2. Stream .GetDownloadStream()

This will fully enable Stream.CopyTo() functionality and will make integration with existing code way simpler.

Seems similar issues:
https://github.com/Azure/azure-sdk-for-net/issues/9607

**Comment by amnguye** [comment] 2020-07-13 04:44
@seanmcc-msft  is this a duplicate?

**Comment by yahorsi** [comment] 2020-07-13 15:19
Just FYI, in the V11 there is OpenWrite method that does exactly what we need.

**Comment by seanmcc-msft** [comment] 2020-07-13 16:24
Duplicate of https://github.com/Azure/azure-sdk-for-net/issues/9607.

We are actively working on this issue: https://github.com/Azure/azure-sdk-for-net/pull/12400, https://github.com/Azure/azure-sdk-for-net/pull/13344.

**Closed by seanmcc-msft** 2020-07-13 16:24 UTC
Labels: Client, Service Attention, Storage, customer-reported, feature-request, needs-team-attention
