### ISSUE TITLE
[BUG] EventHubBufferedProducerClient EnqueueEventAsync never times out - when the endpoint is invalid.

### ISSUE THREAD

**Issue by AJosephsen** [Azure/azure-sdk-for-net#40028] opened 2023-11-15 22:33 UTC
### Library name and version

Azure.Messaging.EventHubs 5.9.3

### Describe the bug

We experience very long hanging processes when we try to enqueue events for EventHub with the Buffered Producer Client
It seems to take more than 30 minutes to get a retry for such a simple case as an EventHub endpoint that can't be found.

And it seems to be caused by some retry mechanism with exponential  retry mode.

        public EventHubBufferedProducerClientOptions()
        {
            _retryOptions = new EventHubsRetryOptions
            {
                MaximumRetries = 15,
                TryTimeout = TimeSpan.FromMinutes(3),
            };
        }

### Expected behavior

Timeout within a minute or something reasonable?

### Actual behavior

Process hangs for more than 30 minutes.

### Reproduction Steps

    var connection = MyBadConnectionStringWithInvalidAddress
    var producerClient = new EventHubBufferedProducerClient(connection);
    await producerClient.EnqueueEventAsync(new EventData(payload), new EnqueueEventOptions { PartitionKey = "X"});

### Environment

Dotnet 7

**Comment by jsquire** [comment] 2023-11-16 16:26
Hi @AJosephsen.  Thank you for reaching out and we regret that you're experiencing difficulties.   I was able to reproduce this and track the source to an error in how we were considering retries socket-related errors.   For the first enqueued, the producer starts up it's background processing to publish events, which includes connecting to the service.  In this case, the connection attempted failed and should have been considered terminal and immediately surfaced, failing the `EnqueueEventAsync` call.

Instead, we considered it to be retriable as a socket-based error and immediately began retrying according to the configured policy.  Because retries are implicit, only logs are emitted during that time and no exception is surfaced until after the retry policy is exhausted.  As a result, the call appeared to hang for your application.   Due to the buffered producer being a long-running client that does its work in the background, our default retry policy is much more generous than makes sense for an interactive operation.

The retry policy error has been addressed by #40049, which will ensure that unreachable hosts are terminal.   I've also opened #40052 to track adding a timeout more suitable for an interactive operation should a transient failure occur during the initial startup to ensure that we don't appear to hang.

**Closed** 2023-11-24 16:35 UTC
Labels: Event Hubs, Client, customer-reported, bug, issue-addressed
