### ISSUE TITLE
[QUERY] How to use Azure.AI.Language.Conversations.QuestionAnsweringParameters to provide metadata for the Custom Question Answering service linked to an Orchestrator

### ISSUE THREAD

**Issue by rliberoff** [Azure/azure-sdk-for-net#28504] opened 2022-05-03 09:44 UTC
### Library name and version

Azure.AI.Language.Conversations 1.0.0-beta.3

### Query/Question

Hello!

My team is using the ConversationAnalysisClient to connect with an Orchestrator in Language Service connected to various projects, among other, a Custom Question Answering (CQA) project.

The Orchestrator is working correctly, returning the right intent and expected answer. Nonetheless, We still need to filter the answers using metadata key-value pairs.

We notice there is a class called «Azure.AI.Language.Conversations.QuestionAnsweringParameters» which according to documentation looks like the type We could use to pass metadata to the Conversation Analysis Client so it can use it when connecting with the target CQA.

However, We have been unable to use it. 

Could you please advise or show us how to use it?

Thank you!

### Environment

.NET 6
Visual Studio 17.1.6
Windows 10

**Comment by jsquire** [comment] 2022-05-03 12:34
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by heaths** [comment] 2022-05-05 20:28
@ChongTang looking at https://github.com/Azure/azure-rest-api-specs/blob/77b673c60d3efe1bc9cb30525db176e67b8d24dd/specification/cognitiveservices/data-plane/Language/preview/2021-11-01-preview/analyzeconversations.json#L253-L268 I don't see any schema that would be useful. Samples like https://github.com/Azure/azure-rest-api-specs/blob/77b673c60d3efe1bc9cb30525db176e67b8d24dd/specification/cognitiveservices/data-plane/Language/preview/2021-11-01-preview/examples/conversations/Orchestrator_direct_target.json#L12-L28 include data, but without a swagger schema we have no code-gen support.

/cc @rokulka @ZulaMostafa @mshaban-msft

**Comment by ChongTang** [comment] 2022-05-05 20:50
The parameter should be the same as one calls QuestionAnswering directly.

**Comment by heaths** [comment] 2022-05-05 20:56
What model would that be, though? Looking at the sample, QA defines no `isTest`, for example. But for the SDK, we need more than that. Why not refactor out whatever model is needed into _common.json_ so we can actually generate code for it (and related models)? Asking customers to serialize their own model classes - or manually format JSON - is not ideal for inference APIs.

**Comment by ChongTang** [comment] 2022-05-05 21:08
It should be this model. Instead of putting it in `common.json`, can we refer to `questionanswering.json` directly? It's a QuestionAnswering model, I think it's natural to keep it there. How do you think?

**Comment by ChongTang** [comment] 2022-05-05 21:14
https://github.com/Azure/azure-rest-api-specs/blob/aba14a982790cc7319f7636783ad5051f1a1ef16/specification/cognitiveservices/data-plane/Language/stable/2021-10-01/questionanswering.json#L116

**Comment by heaths** [comment] 2022-05-05 21:27
The problem is that CLU and QA don't always ship in the same API versions, and you shouldn't cross API versions. I'd highly recommend just putting it in _common.json_.

**Comment by ChongTang** [comment] 2022-05-05 21:32
Yes. I will update the example; it is from a previous version.

I agree with you on moving definitions to common.json. It will be a large number of models referred by the AnswerOptions and QnA's response model. We are OK with that, right?

**Comment by heaths** [comment] 2022-05-05 21:48
I don't see a problem. AutoRest will aggregate the data as if it was a single document. @rokulka?

**Comment by ChongTang** [comment] 2022-05-05 23:24
Since CLU and QuestionAnswering don't always ship in the same API versions, I am thinking about copying those definitions to the common.json or to analyzeconversations.json and leave questionanswering.json unchanged. How does that sound?

**Comment by heaths** [comment] 2022-05-06 18:21
I recommend putting them in _common.json_, yes, but we should update _questionanswering.json_ for the next version so it's ready and can be validated. @peytonfraser is working on a new directory based on my new process proposal spec and that would be a great place to make sure all services' swaggers are collected and updated accordingly.

But, for 2022-05-15-preview, I agree leave _questionanswering.json_ unchanged in the stable/2021-10-01 in which it last shipped. Generally, we want to make _common.json_ a living document *moving forward*. The new process will help ensure that.

/cc @annatisch

**Comment by ChongTang** [comment] 2022-05-12 19:03
@heaths Can we mark this resolved since those two PRs got merged?

**Comment by rliberoff** [comment] 2022-05-13 07:56
Hello @ChongTang  and @heaths,

If there is already some PRs merged, when can we expect a new version of the NuGet package with this changes available?

Thank you!!!

**Comment by heaths** [comment] 2022-05-13 22:14
We are working on the next ones now and should have them ready early June.

**Closed by heaths** 2022-05-13 22:14 UTC
Labels: Service Attention, Client, customer-reported, question, needs-team-attention, Cognitive - Language

**Comment by rliberoff** [comment] 2022-06-06 11:49
Hi @heaths, 

Do you have any new estimation when we could have a new version of the SDK with this fixed?

Thank you.

**Comment by KowsikRaviukumar** [comment] 2022-11-10 15:30
> 6/20

Hi @heaths,

Is the feature out?

Thanks
