### ISSUE TITLE
[BUG] Connection strings with explicit hostname endpoint does not resolve correctly

### ISSUE THREAD

**Issue by rmja** [Azure/azure-sdk-for-net#10539] opened 2020-03-11 14:38 UTC
**Describe the bug**
The connection string from [here](https://docs.microsoft.com/en-us/azure/storage/common/storage-use-emulator#connect-to-the-emulator-account-using-the-well-known-account-name-and-key) does not parse correctly if the endpoints are replaced with custom hostnames.

An example is the connection string 

```
DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://host.docker.internal:10000/devstoreaccount1;TableEndpoint=http://host.docker.internal:10002/devstoreaccount1;QueueEndpoint=http://host.docker.internal:10001/devstoreaccount1;
```
This previously worked in M.A.S.B v. 11. This is used to let docker containers connect to the storage emulator running on the host.

**Expected behavior**
The connection string should parse correctly and set the account name to `devstoreaccount1`.

**Actual behavior (include Exception or Stack Trace)**
The generated Uri in `BlobUriBuilder` does not correctly include the account name.

**To Reproduce**

This test in `ContainerClientTests.cs` does not pass:

```
        [Test]
        [ServiceVersion(Min = BlobClientOptions.ServiceVersion.V2019_02_02)]
        public void Ctor_ConnectionString_ReferenceDevelopmentStorage_WithCustomHostnameEndpoints()
        {
            // From https://docs.microsoft.com/en-us/azure/storage/common/storage-use-emulator#connect-to-the-emulator-account-using-the-well-known-account-name-and-key
            // but with hostnames instead of IP's in endpoint specification
            var connectionString = @"DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://host.docker.internal:10000/devstoreaccount1;TableEndpoint=http://host.docker.internal:10002/devstoreaccount1;QueueEndpoint=http://host.docker.internal:10001/devstoreaccount1;";

            var containerName = "containername";

            BlobContainerClient container = InstrumentClient(new BlobContainerClient(connectionString, containerName));

            var builder = new BlobUriBuilder(container.Uri);

            Assert.AreEqual(containerName, builder.BlobContainerName);
            Assert.AreEqual("", builder.BlobName);
            Assert.AreEqual("devstoreaccount1", builder.AccountName);
        }
```

**Environment:**
 - Azure.Storage.Blobs, master
 - Windows 10 .NET Core 3.1
 - Visual Studio 16.5

**Comment by amnguye** [comment] 2020-05-26 21:27
Hi,

I was able to reproduce your issue. Looks like we were not able to parse the string properly. We will look to get in a fix soon.

----

Error Stack Trace
```
  Message: 
      Expected string length 12 but was 0. Strings differ at index 0.
      Expected: "storageaccount"
      But was:  <string.Empty>
      -----------^
    
  Stack Trace: 
    ContainerClientTests.Ctor_ConnectionString_ReferenceDevelopmentStorage_WithCustomHostnameEndpoints() line 241
```

**Comment by amnguye** [comment] 2020-09-10 21:04
Resolved by https://github.com/Azure/azure-sdk-for-net/pull/13124

**Closed by amnguye** 2020-09-10 21:04 UTC
Labels: Client, Service Attention, Storage, bug, customer-reported, needs-team-attention
