### ISSUE TITLE
Duplicate H1s Conflict for microsoft.batch

### ISSUE THREAD

**Issue by v-alje** [Azure/azure-sdk-for-net#29204] opened 2022-06-08 21:51 UTC
The following articles created from readme files are using the same H1 title header. Docs reports warnings when there are two articles with the same H1 text. This is happening because both the preview and release versions of the Docs articles were imported from the same readme: sdk/batch/Microsoft.Azure.Batch/README.md

https://github.com/Azure/azure-docs-sdk-dotnet/blob/main/api/overview/azure/microsoft.batch-readme.md
https://github.com/Azure/azure-docs-sdk-dotnet/blob/main/api/overview/azure/microsoft.azure.batch-readme.md

The topic H1s need to be uniquely differentiated when imported to Docs.

**Comment by jsquire** [comment] 2022-06-09 13:54
Closing as a duplicate of #29199

**Comment by sima-zhu** [comment] 2022-06-10 16:14
Addressed the problem.

**Closed by sima-zhu** 2022-06-10 16:14 UTC
Labels: Docs, Central-EngSys
