### ISSUE TITLE
Unify AsyncPageable/Pageable helper classes

### ISSUE THREAD

**Issue by pakrym** [Azure/azure-sdk-for-net#9896] opened 2020-02-11 05:35 UTC
Now we have two versions: used by hand-written and generated SDKs

**Comment by annelo-msft** [comment] 2020-08-10 15:25
When this is addressed, update Paging tutorial in the Azure SDK Development Training program repo:

common-patterns/paging.md

https://github.com/Azure/azure-sdk-pr/pull/267/files

**Comment by annelo-msft** [comment] 2023-08-02 20:58
Closing as duplicate of https://github.com/Azure/azure-sdk-for-net/issues/32006

**Closed by annelo-msft** 2023-08-02 20:58 UTC
Labels: Client, Azure.Core
