### ISSUE TITLE
[Question] EventProcessorClient is very slow to initialize each partition

### ISSUE THREAD

**Issue by TaffarelJr** [Azure/azure-sdk-for-net#10550] opened 2020-03-12 00:30 UTC
**Describe the bug**
When starting an `EventProcessorClient`, it takes approximately 10 seconds to connect to each partition in the EventHub. In our case, we have 30 partitions, which means it takes ~300 seconds for the client to start up.

**Expected behavior**
In the v4 version of the client, it connected to all 30 partitions in under a second. The v5 version seems to be a huge step down in terms of startup performance. I'm hoping it's just some setting we can configure ...

**Actual behavior (include Exception or Stack Trace)**
Notice the timestamps:
![image](https://user-images.githubusercontent.com/5290662/76474007-dadc5e80-63bf-11ea-876b-dffea86e0ebd.png)

**To Reproduce**
```csharp
var blobClient = new BlobContainerClient("<SA connection string>", "<container name>");
var eventHubclient = new EventProcessorClient(blobClient, "<consumer group>", "<EH connection string>");

eventHubclient.StartProcessingAsync();
```

**Environment:**
 - Azure.Messaging.EventHubs.Processor 5.0.1
 - Windows 10.0.18363 (1909)
- .NET 3.1.101
 - Visual Studio 16.4.5

**Comment by jsquire** [comment] 2020-03-12 13:58
Hi @TaffarelJr, thank you for reaching out with feedback.   The current load balancing implementation for the processor is tuned for helping multiple processors share the load without a high degree of contention for each partition, which results in partitions "bouncing" between processors as they are added/removed, causing processing for those partitions to slow down.

We recognize that there are scenarios where this isn't an ideal design and those using fewer processors with a higher partition count would see a slower initialization, such as you are.  I'm happy to say that we're currently working through a plan to expose the ability to tune configuration of the load balancer to allow for more aggressive claiming of partitions and an adjustable lease duration.  

It is our hope that these additional options should allow you more control over load balancing so that you can find the right balance for your scenario.  Unfortunately, I don't have any dates that I can share at the moment, but I can confirm that this is something we would like to release in the near-term and are actively working on.

**Comment by jsquire** [comment] 2020-03-17 17:15
It looks like the discussion here has tapered off.   I'm going to close this out to reflect that.  Please feel free to reopen if there's additional insight that we can provide.

**Closed by jsquire** 2020-03-17 17:15 UTC
Labels: Client, Event Hubs, Question
