### ISSUE TITLE
Issuer validation failed. Issuer did not match.

### ISSUE THREAD

**Issue by woutervs** [Azure/azure-sdk-for-net#10529] opened 2020-03-11 09:01 UTC
**Describe the bug**
When trying retrieve blob data from the azure storage I get an error

**Expected behavior**
Being authenticated and retrieving data

**Actual behavior (include Exception or Stack Trace)**
Status: 403 (Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.)
ErrorCode: AuthenticationFailed

In fiddler I can see: **Issuer validation failed. Issuer did not match.**

**To Reproduce**
Steps to reproduce the behavior (include a code snippet, screenshot, or any additional information that might help us reproduce the issue)

environment variable:
AZURE_USERNAME: {my azure ad account logged into visualstudio that does work for sqlconnections for example}

```
new BlobServiceClient(new Uri(configuration.GetConnectionString("AzureStorage")), new DefaultAzureCredential());

var container = blobServiceClient.GetBlobContainerClient("apk");
            

            foreach (var blob in container.GetBlobs()) //fails at .GetBlobs()
```

![image](https://user-images.githubusercontent.com/5603059/76399306-b0b67c80-637e-11ea-892c-5ca6633677b7.png)

**Environment:**
 - Name and version of the Library package used: 
   - Azure.Identity 1.1.1
   - Azure.Storage.Blobs 12.3.0
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects):
Windows 10 
![image](https://user-images.githubusercontent.com/5603059/76399610-30444b80-637f-11ea-97b7-316be95a7999.png)
 - IDE and version : [e.g. Visual Studio 16.3]
![image](https://user-images.githubusercontent.com/5603059/76399630-3afee080-637f-11ea-9b21-6ab1f54681b2.png)

**Comment by amnguye** [comment] 2020-03-13 18:14
Hi,

Your AAD identity might not have the rights to read the blobs. So you may be able to authenticate to sqlconnections but if your ad account might not have access to storage account or read rights. Please recheck if you've given the rights to the storage account to the aad user.

**Comment by woutervs** [comment] 2020-03-16 13:57
Hi,

Sorry took a while to get back here.
The AAD identity definitely has rights since I can do this:
![image](https://user-images.githubusercontent.com/5603059/76765293-755ce900-6796-11ea-8909-3ae8e4ff44af.png)

**Comment by amnguye** [comment] 2020-03-17 18:49
Thanks for the confirmation.

Could you rerun this this again and provide the x-ms-request-id? I would use the request id that you originally screenshotted but unfortunately the backend logs for these are flushed every 2 days.

**Comment by woutervs** [comment] 2020-04-07 10:25
Hi Sorry for the super late reply, but with covid and everything I didn't get to it, the code also wasn't in sourcecontrol yet so...

Anyway the x-ms-request-id = 10f103cd-c01e-009b-2ec6-0ce6ad000000

**Comment by woutervs** [comment] 2020-04-07 10:27
Also just updated to 12.4.1.
Same issue: 4374cdfc-e01e-0040-3ec7-0c427b000000 x-ms-request-id

**Comment by amnguye** [comment] 2020-04-15 10:02
Sorry about this, could you re run this and get the request id again?

**Comment by woutervs** [comment] 2020-04-15 10:28
Definitely: 4e0a9657-d01e-0007-6510-139d10000000

**Comment by woutervs** [comment] 2020-04-27 14:30
Can I get a status update for this one? :)

**Comment by amnguye** [comment] 2020-05-01 18:16
Hi @woutervs, sorry for the delay and the repeated asking for client ids and not looking them up in time.

I tried to reproduce your issue but I just wanted to clarify a few things. Are you actually using new DefaultAzureCredential() in initalizing the BlobServiceClient?

This looks related to this issue (https://github.com/Azure/azure-sdk-for-net/issues/8658).

Is it possible for you to try the preview 1.2.0-preview of Azure.Identity package to see if that resolves your problem?

**Comment by woutervs** [comment] 2020-05-02 00:00
So I basically do this:

```
services.AddSingleton(s =>
            {
                var configuration = s.GetService<IConfiguration>();
                return new BlobServiceClient(new Uri(configuration.GetConnectionString("AzureStorage")), new DefaultAzureCredential());
            });
```

I've tried with the preview version but still the same error.
x-ms-request-id: fc011faa-401e-00ce-1114-200dda000000

**Comment by woutervs** [comment] 2020-05-02 00:15
So I first tried with 1.2.0-preview.2 that failed with the same error.
I then read in #8658 that some people had some success with the 1.2.0-preview.1 package -> I tried that too first getting this 
![image](https://user-images.githubusercontent.com/5603059/80850111-9da38880-8c1a-11ea-84f5-e3d48ca5ddd4.png)

Then I did an az login in powershell getting me a new token.
And at last I can retrieve data from storage.

Though only in the 1.2.0-preview.1 version.

**Comment by amnguye** [comment] 2020-05-02 22:23
Hi,

Thanks for providing the request id (I was able to confirm it's just an identity auth issue) and confirming that the Azure.Identity package v1.2.0-preview.1 is giving you a more helpful error to get a new token to access your storage container.

I'm going to relabel this with Azure.Identity and see if they can better help your issue, because that's strange that the newer version of the preview does not have the fix that preview.1 has.

**Comment by schaabs** [comment] 2020-07-21 16:54
@woutervs Thanks for including the full error and stack. It seems like what's going on here is that your falling back to authenticating with the `AzureCliCredential` which in the second error you posted is failing because the refresh token has expired and you would have to re-run `az login` to re-authenticate via the CLI. 

However, this doesn't explain why we failed to authenticate via the account logged into Visual Studio, which should supersede the Azure CLI. Could you possibly try this on our latest 1.2.0 preview? There have been several fixes to `DefaultAzureCredential` including the introduction of the `VisualStudioCredential` to provide more reliable authentication with Visual Studio. Also it would probably help to re-authenticate your Azure Service Account in VS to ensure it's up to date and the correct account.

**Comment by woutervs** [comment] 2020-08-03 08:30
I'll see if I can find some time to squeeze in another test. At some point I did manage to get it to work and from there I deployed to production as this is not a customer critical component, but an internal tool.

**Comment by mattosaurus** [comment] 2020-09-09 08:39
Hi, I am also encountering this issue when trying to authenticate a BlobCloudClient using MSI.

```
HTTP/1.1 401 Server failed to authenticate the request. Please refer to the information in the www-authenticate header.
Content-Length: 402
Content-Type: application/xml
Server: Microsoft-HTTPAPI/2.0
x-ms-request-id: 604a9acc-201e-006a-3382-86c184000000
x-ms-error-code: InvalidAuthenticationInfo
WWW-Authenticate: Bearer authorization_uri=https://login.microsoftonline.com/8dc638e2-f657-4a1c-bf43-6da5804f5f57/oauth2/authorize resource_id=https://storage.azure.com
Date: Wed, 09 Sep 2020 08:26:21 GMT

<?xml version="1.0" encoding="utf-8"?><Error><Code>InvalidAuthenticationInfo</Code><Message>Server failed to authenticate the request. Please refer to the information in the www-authenticate header.
RequestId:604a9acc-201e-006a-3382-86c184000000
Time:2020-09-09T08:26:22.3758046Z</Message><AuthenticationErrorDetail>Issuer validation failed. Issuer did not match.</AuthenticationErrorDetail></Error>
```

I am running this locally in Visual Studio and am logged in using an account that has been granted the contribuator role to the storage account. I am able to access the storage account as expected from Azure Storage Explorer.

My user account is in a CSP AAD and has been added as a guest to the tenant where the storage account exists. The tenant ID referenced in the WWW-authenticate header returned is that for the tenant where the storage account exists rather than for the CSP tenant where my user account exists if that makes any difference?

**Comment by lilyjma** [comment] 2021-01-13 21:58
@woutervs Is this still a problem for you?

**Comment by woutervs** [comment] 2021-01-13 22:17
I haven't developed on this project anymore as we launched in production (the issue was only local during development) I think it was resolved, or we used a version locally where it worked. So no idea if it still occurs in the latest version.

If you want I can allocate some time to try it again during work hours tomorrow.

**Comment by lilyjma** [comment] 2021-01-14 23:17
Thanks for the update @woutervs! I just wanted to make sure the issue has been resolved. 
@mattosaurus, are you still experiencing the problem?

**Comment by mattosaurus** [comment] 2021-01-15 09:51
Hi, I changed my code to access Azure blob storage using a SAS key rather than MSI so I'm unsure if this has been resolved or not.

**Comment by lilyjma** [comment] 2021-01-15 22:57
I see. Thanks for the updates! I'll close the issue for now. If there's more question regarding to the problems mentioned in the issue, please reopen.

**Closed by lilyjma** 2021-01-15 22:57 UTC
Labels: Azure.Identity, Client, Service Attention, customer-reported, needs-team-attention, question

**Comment by danielmackay** [comment] 2021-07-04 10:30
I see this ticket is closed, but is the issue actually resolved?

I am facing this now using:
- Azure.Identity 1.4.0
- Azure.Storage.Blobs (12.9.1)

I have tried setting my user both though VS -> Tools -> Options -> Azure Service Authentication, and via an AZURE_USERNAME environment variable, none of which has worked.  The error I am getting is:

```[2021-07-04T10:14:53.180Z] Host lock lease acquired by instance ID '000000000000000000000000524E791E'.
[2021-07-04T10:14:54.086Z] Executed 'ListFiles' (Failed, Id=554faeca-1e68-4f7d-b8e6-75ad6e76d03c, Duration=3565ms)
[2021-07-04T10:14:54.088Z] System.Private.CoreLib: Exception while executing function: ListFiles. Azure.Storage.Blobs: Server failed to authenticate the request. Please refer to the information in the www-authenticate header.
RequestId:bee61514-501e-00b7-29bd-700f62000000
Time:2021-07-04T10:15:12.7427965Z
[2021-07-04T10:14:54.089Z] Status: 401 (Server failed to authenticate the request. Please refer to the information in the www-authenticate header.)
[2021-07-04T10:14:54.092Z] ErrorCode: InvalidAuthenticationInfo
[2021-07-04T10:14:54.093Z]
[2021-07-04T10:14:54.093Z] Additional Information:
[2021-07-04T10:14:54.094Z] AuthenticationErrorDetail: Issuer validation failed. Issuer did not match.
[2021-07-04T10:14:54.095Z]
[2021-07-04T10:14:54.095Z] Content:
[2021-07-04T10:14:54.096Z] <?xml version="1.0" encoding="utf-8"?><Error><Code>InvalidAuthenticationInfo</Code><Message>Server failed to authenticate the request. Please refer to the information in the www-authenticate header.
RequestId:bee61514-501e-00b7-29bd-700f62000000
Time:2021-07-04T10:15:12.7427965Z</Message><AuthenticationErrorDetail>Issuer validation failed. Issuer did not match.</AuthenticationErrorDetail></Error>
[2021-07-04T10:14:54.097Z]
[2021-07-04T10:14:54.098Z] Headers:
[2021-07-04T10:14:54.099Z] Server: Microsoft-HTTPAPI/2.0
[2021-07-04T10:14:54.100Z] x-ms-request-id: bee61514-501e-00b7-29bd-700f62000000
[2021-07-04T10:14:54.101Z] x-ms-error-code: InvalidAuthenticationInfo
[2021-07-04T10:14:54.102Z] WWW-Authenticate: REDACTED
[2021-07-04T10:14:54.106Z] Date: Sun, 04 Jul 2021 10:15:12 GMT
[2021-07-04T10:14:54.107Z] Content-Length: 402
[2021-07-04T10:14:54.108Z] Content-Type: application/xml
[2021-07-04T10:14:54.109Z] .
```

Can we reopen this ticket or should I create a new one?

**Comment by Expecho** [comment] 2021-07-12 15:09
I have the same issue, @danielmackay did you open a new issue or not?

**Comment by danielmackay** [comment] 2021-07-12 23:41
@Expecho - I did not open a new issue, but I managed to solve the issue. 

In my case I was using a user who had access to multiple subscriptions/tenants.  I had the right user selected in Visual Studio, but I think it was defaulting to the wrong tenant.

I solved this by explicitly using the AzureCliCredential() and Azure CLI to login to the exact tenant.  You could probably also do something similar by using EnvironmentCredential()

**Comment by ascott18** [comment] 2022-01-13 19:25
@danielmackay I ended up with the same "Issuer does not match" error. I came across this issue via Google search for that error message. I was able to solve this by specifying the tenantId to the options of DefaultAzureCredential:

``` c#
new DefaultAzureCredential(new DefaultAzureCredentialOptions
        {
            VisualStudioTenantId = "7e5a038c-dd78-4130-b562-f0ea12548732"
        })
```

There are similar options for TenantId for other auth mechanisms. Unfortunately, there's no overarching generic TenantId option, so it must be specified for each potential auth mechanism.

**Comment by danielmackay** [comment] 2022-01-14 07:54
Good to know we can lock in the tenant that way. Thanks for the info!

**Comment by xperiandri** [comment] 2022-06-21 00:20
But for guest accounts, we still get this issue!

**Comment by xiaogangy** [comment] 2022-11-28 10:33
The weird thing is using "DefaultAzureCredential()" to do the authetication when retrieving Key Vault, it succeeds while for Azure blob storage, it shows "Issuer validation failed", do you have any clue?

**Comment by hirejohnloveland** [comment] 2023-01-05 22:35
I am running into this same issue today using an ASP.NET Core web app with .net version 6 and the latest Azure Identity and Azure blobs SDKs (1.8.0 and 12.14.1 respectively.

Here is my code to initialize the client

`            var credentials = new DefaultAzureCredential(includeInteractiveCredentials: true);
            var uri = new Uri(_Configuration["Azure:Blob:URI"]!);
            var client = new BlobServiceClient(uri, credentials);`

**Comment by danielmackay** [comment] 2023-01-06 03:29
@hirejohnloveland - Try using Azure CLI to login.  I've found I have a lot more control than when trying to leave the authentication up to visual studio.

By default the Azure CLI will not let you login to an tenant without a subscription (which is common if your tenant is only used for AAD).  In that case try logging on with

```ps1
az login -t myb2ctenant.onmicrosoft.com --allow-no-subscriptions
```

**Comment by hirejohnloveland** [comment] 2023-01-06 12:05
After logging out and clearing all VS account info and restarting, the CLI method is working for me.  I did also have to specify the AZURE_TENANT_ID with the tenant I am requesting for.  IMO this is a bug because the sdk should infer the requesting tenant from the uri of the storage account.  Or the SDK should allow you to turn on interactive credentials AND specify DefaultCredentialOptions with Tenant ID in the constructor. If I use the options, I can't turn on interactive credentials and I hit MFA issues.  If I turn on interactive credentials instead of putting the tenant in the options, I have to add the environmental variable.
