### ISSUE TITLE
[BUG] Could not load file or assembly 'System.Memory.Data, Version=6.0.0.0, Culture=neutral for virtualMachineResource.AddTag(tagName, tagValue);

### ISSUE THREAD

**Issue by PauCoda** [Azure/azure-sdk-for-net#46755] opened 2024-10-22 09:53 UTC
### Library name and version

Azure.ResourceManager.Compute 1.6.0 and older versions

### Describe the bug

Hello.

I'm running code virtualMachineResource.AddTag(tagName, tagValue); and getting:

[2024-10-22T08:23:47.919Z] Could not load file or assembly 'System.Memory.Data, Version=6.0.0.0, Culture=neutral, PublicKeyToken=...'. The system cannot find the file specified.

I used Azure.ResourceManager.Compute 1.6.0 and older versions and any version helps.

I run it using: 

`var credential = new DefaultAzureCredential();
var armClient = new ArmClient(credential);
var subscriptionid = "XXX";
var resourceGroupName = "YYY";
var vmName = "ZZZ";
var tagName = "GM";
var tagValue = "Disabled";

AddTagToVm(subscriptionid, resourceGroupName, vmName, tagName, tagValue, armClient);

        public static void AddTagToVm(string subscriptionid, string resourceGroupName, string vmName, string tagName, string tagValue, ArmClient armClient)
        {
            var cred = armClient;
            ResourceIdentifier vmIdentifier = VirtualMachineResource.CreateResourceIdentifier(subscriptionid, resourceGroupName, vmName);

            VirtualMachineResource virtualMachineResource = cred.GetVirtualMachineResource(vmIdentifier);

            // Call Get to retrieve the virtual machine data
            virtualMachineResource = virtualMachineResource.Get();
            // Get the current tags
            var currentTags = virtualMachineResource.Data.Tags ?? new Dictionary<string, string>();

            // Check if the tag already exists
            if (!currentTags.TryGetValue(tagName, out var existingValue) || existingValue != tagValue)
            {
                // Tag does not exist or has a different value, so add or update it
                virtualMachineResource.AddTag(tagName, tagValue);
            }
            else
            {
                // Tag already exists with the same value
                Console.WriteLine($"Tag for {vmName} already exists with value '{existingValue}'.");
            }

        }`
I set breakpoints and found the issue for virtualMachineResource.AddTag(tagName, tagValue);.

Earlier it was working properly, now I'm can't add the tag for virtual machine.

### Expected behavior

Tag should be added to Azure Virtual Machine.

### Actual behavior

[2024-10-22T08:23:47.919Z] Could not load file or assembly 'System.Memory.Data, Version=6.0.0.0, Culture=neutral, PublicKeyToken=...'. The system cannot find the file specified.

When running: 
 virtualMachineResource.AddTag(tagName, tagValue);

### Reproduction Steps

1. Create project in .net 8
2. Create the class and add code 
3. `var credential = new DefaultAzureCredential();
var armClient = new ArmClient(credential);
var subscriptionid = "XXX";
var resourceGroupName = "YYY";
var vmName = "ZZZ";
var tagName = "GM";
var tagValue = "Disabled";

AddTagToVm(subscriptionid, resourceGroupName, vmName, tagName, tagValue, armClient);

        public static void AddTagToVm(string subscriptionid, string resourceGroupName, string vmName, string tagName, string tagValue, ArmClient armClient)
        {
            var cred = armClient;
            ResourceIdentifier vmIdentifier = VirtualMachineResource.CreateResourceIdentifier(subscriptionid, resourceGroupName, vmName);

            VirtualMachineResource virtualMachineResource = cred.GetVirtualMachineResource(vmIdentifier);

            // Call Get to retrieve the virtual machine data
            virtualMachineResource = virtualMachineResource.Get();
            // Get the current tags
            var currentTags = virtualMachineResource.Data.Tags ?? new Dictionary<string, string>();

            // Check if the tag already exists
            if (!currentTags.TryGetValue(tagName, out var existingValue) || existingValue != tagValue)
            {
                // Tag does not exist or has a different value, so add or update it
                virtualMachineResource.AddTag(tagName, tagValue);
            }
            else
            {
                // Tag already exists with the same value
                Console.WriteLine($"Tag for {vmName} already exists with value '{existingValue}'.");
            }

        }`
4. Add all required libraries
I use for my project:
<PackageReference Include="Azure.Core" Version="1.44.1" />
<PackageReference Include="Azure.Identity" Version="1.13.0" />
<PackageReference Include="Azure.ResourceManager" Version="1.13.0" />
<PackageReference Include="Azure.ResourceManager.Compute" Version="1.6.0" />
<PackageReference Include="Microsoft.Azure.WebJobs.Extensions.Storage" Version="5.3.2" />
<PackageReference Include="Microsoft.Extensions.Logging" Version="8.0.1" />
6. Login using your Azure account in VS
7. Run it in vs

### Environment

Host:
  Version:      8.0.10
  Architecture: x64
Windows 10

.NET SDK:
 Version:           8.0.110

**Comment by jsquire** [comment] 2024-10-22 15:55
Hi @PauCoda.  Thanks for reaching out and we regret that you're experiencing difficulties.  Version 1.6.0 is a year old and several releases behind.  Please upgrade all Azure SDK packages in your project to the latest releases and confirm whether or not the behavior occurs.   If so, please try adding a direct reference to `System.Memory.Data` v6.0.0 in your project and confirm whether or not the behavior occurs.

**Comment by PauCoda** [comment] 2024-10-23 08:19
Hello @jsquire, for rest of libraries in my project I needed to use lower version of Microsoft.NET.Sdk.Functions and Microsoft.Azure.WebJobs.Extensions.Storage because the latest versions were not working because of similar error for System.Memory.Data Version= 6.0.0.0.

I also installed 6.0.0 for System.Memory.Data and it's not working, also for 8.0.0 and 8.0.1, there is the same error.

I'm having the same error: "[2024-10-23T08:08:22.443Z] Could not load file or assembly System.Memory.Data, Version=6.0.0.0, Culture=neutral, PublicKeyToken=..'. The system cannot find the file specified." when trying assign a tag to vm using Azure.ResourceManager.Compute library.

**Comment by jsquire** [comment] 2024-10-23 17:20
@PauCoda :  Is this something that you're hosting as an in-proc Azure Function?  Can you provide a small, stand-alone app that reproduces the behavior that you're seeing for analysis?

**Comment by jsquire** [comment] 2024-10-24 15:53
@PauCoda : The Functions in-process runtime with .NET 8 is going to override and control dependencies being loaded.  Any library required by the Functions infrastructure will be silently hoisted up to the version needed by the infrastructure and doesn't follow the standard path for .NET assembly resolution.   As the in-proc model is deprecated, we'd strongly recommend using the isolated model.

Because the root cause of the behavior that you're seeing is related to the Functions host infrastructure, the Azure SDK package has no insight nor influence over the assemblies being loaded.   This is an issue that the Azure Functions team will need to assist with.   I'll transfer this over to the Functions repository so that the folks who are able to assist have visibility.

**Comment by jsquire** [comment] 2024-10-24 16:12
This issue has been transferred to the Azure Functions host repository, as [#10567](https://github.com/Azure/azure-functions-host/issues/10567).

**Closed by jsquire** 2024-10-24 16:12 UTC
Labels: Compute, Mgmt, customer-reported, question, needs-team-attention

**Comment by PauCoda** [comment] 2024-10-25 08:31
Thank you @jsquire .
