### ISSUE TITLE
Azure App Configuration SDK: Support data plane API version

### ISSUE THREAD

**Issue by x9xu** [Azure/azure-sdk-for-net#7502] opened 2019-09-06 01:37 UTC
As required by Azure REST API Guidelines, we are adding **explicit** API Versioning. All requests **MUST** provide explicit API Version as query string parameter,

for example:

     "https://example.azconfig.io/kv?api-version=1.0"

User should be able to specify the Api version in through configuration properties.

**Comment by annelo-msft** [comment] 2019-09-11 16:43
Duplicate of https://github.com/Azure/azure-sdk-for-net/issues/6944

**Comment by annelo-msft** [comment] 2019-09-28 21:22
Implemented in #7619

**Closed by annelo-msft** 2019-09-28 21:22 UTC
Labels: AzConfig, Client
