### ISSUE TITLE
[BUG] TableClient SubmitTransactionAsync with action type UpdateMerge behaves like UpsertMerge

### ISSUE THREAD

**Issue by HansOlavS** [Azure/azure-sdk-for-net#32808] opened 2022-12-01 14:58 UTC
### Library name and version

Azure.Data.Tables 12.7.1

### Describe the bug

When calling SubmitTransactionAsync with an action type of UpdateMerge it behaves like UpsertMerge.
Here's a code example where I create an entity, delete it and then call SubmitTransactionAsync with an UpdateMerge action.

```C#
var storageConnectionString = "DefaultEndpointsProtocol=https;AccountName=[REDACTED];AccountKey=[REDACTED]";
var table = new TableClient(storageConnectionString, "temp");
await table.CreateAsync();
var entity = new TableEntity("1", "1");
entity["Data"] = "Hello world";
entity["Number"] = 1;
await table.AddEntityAsync(entity);
await table.DeleteEntityAsync("1", "1");
var mergeEntity = new TableEntity("1", "1") { ETag = Azure.ETag.All };
mergeEntity["Number"] = 2;
var action = new TableTransactionAction(TableTransactionActionType.UpdateMerge, mergeEntity);
// I expect 404 NotFound error here since the entity no longer exists and this is Update, not Upsert
// If I change this line with await table.UpdateEntityAsync(mergeEntity, Azure.ETag.All, TableUpdateMode.Merge)
// then I do get the expected 404 NotFound error.
await table.SubmitTransactionAsync(new[] { action });
await table.DeleteAsync();
```

### Expected behavior

that Azure.RequestFailedException is thrown with Status NotFound.

### Actual behavior

The entity is inserted.

### Reproduction Steps

```C#
var storageConnectionString = "DefaultEndpointsProtocol=https;AccountName=[REDACTED];AccountKey=[REDACTED]";
var table = new TableClient(storageConnectionString, "temp");
await table.CreateAsync();
var entity = new TableEntity("1", "1");
entity["Data"] = "Hello world";
entity["Number"] = 1;
await table.AddEntityAsync(entity);
await table.DeleteEntityAsync("1", "1");
var mergeEntity = new TableEntity("1", "1") { ETag = Azure.ETag.All };
mergeEntity["Number"] = 2;
var action = new TableTransactionAction(TableTransactionActionType.UpdateMerge, mergeEntity);
await table.SubmitTransactionAsync(new[] { action });
await table.DeleteAsync();
```

### Environment

* Windows 10
* .NET 6
* Visual Studio 17.4.2

**Comment by jsquire** [comment] 2022-12-01 17:31
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by christothes** [comment] 2022-12-02 20:04
Hi @HansOlavS 

The problem is that the ETag needs to be passed to the constructor of TableTransactionAction to be used.
When it is not supplied, Merge is treated like Upsert (this is just how the service differentiates the two operations)

```c#
var action = new TableTransactionAction(TableTransactionActionType.UpdateMerge, mergeEntity, ETag.All);
```

I think we should add some validation here to prevent this scenario.

**Comment by HansOlavS** [comment] 2022-12-03 23:41
Hi @christothes.

To be honest, I thought that ETag = default had the same meaning av ETag.All, but I see now that it is definitely not so.
I understand the problem, but I do think it's strange to haveType UpdateMerge and UpsertMerge and have the ETag parameter override the meaning in this particular case. It would be better to throw an exception here instead of ignoring the type parameter, IMO.

**Comment by christothes** [comment] 2022-12-05 16:26
The other consideration is to treat the default in this case as `ETag.All`. Throwing in this case could be a behavioral breaking change, but the default may be more appropriate since it would probably match expectations in most cases. What do you think?

**Comment by HansOlavS** [comment] 2022-12-14 20:50
Hi @christothes. I think the main problem is that a single UpdateEntity operation results in an exception with 404, while the exact same operation through a SubmitTranssaction operation behaves differently. Don't you agree?

**Comment by christothes** [comment] 2022-12-14 20:54
Yes - I think the right thing to do here may be to default to ETag.All when creating a `TableTransactionAction` of type `TableTransactionActionType.UpdateMerge`

**Comment by HansOlavS** [comment] 2022-12-14 20:59
@christothes To be clear, in my last comment I'm not mentioning the ETag default, and I'm not sure if changing this is really a good thing. I'm saying that I'd like think UpdateEntity and SubmitTransaction with type UpdateMerge should function semantically the same. And it's even more confusing since now UpdateMerge functions semantically like UpsertMerge.

**Comment by christothes** [comment] 2022-12-14 21:07
> @christothes To be clear, in my last comment I'm not mentioning the ETag default, and I'm not sure if changing this is really a good thing. I'm saying that I think that UpdateEntity and SubmitTransaction with type UpdateMerge should function semantically the same. And it's even more confusing since now UpdateMerge functions semantically like UpsertMerge.

Technically speaking, they do operate the same. The problem here is that when calling `UpdateEntity`, the `ETag` parameter is required, but creating a `TableTransactionAction` of type `TableTransactionActionType.UpdateMerge` does not enforce this in the same way. The side effect is an unfortunate implementation detail of the service which treats Update and Upsert as the same REST call with the only difference being whether or not an `if-match` header is supplied.

Do you have any suggestions on how this should be resolved via the API?

**Comment by HansOlavS** [comment] 2022-12-14 21:12
Ah, OK. I just tried to do it now with ETag.All and I did get the exact same response. I guess that closes this ticket from my end! :)

**Closed** 2022-12-14 23:13 UTC
Labels: Client, customer-reported, question, Tables, needs-team-attention
