### ISSUE TITLE
[BUG]Azure Key Vault - Azure.KeyVault client is not closing socket connections causing TCP connection exhaust

### ISSUE THREAD

**Issue by dalzhao** [Azure/azure-sdk-for-net#6326] opened 2019-05-17 23:43 UTC
**Describe the bug**
Customer has an Appservice running which gets a value from keyvault each 10 minutes (they cache the value for 10 minutes). The appservice is hosted on azure.
.net framework 4.6.1
Tthe Azure.KeyVault client is not closing socket connections.

***Exception or Stack Trace***
Add the exception log and stack trace if available

**To Reproduce**
They add the class below with a singleton interface. It is invoked each httprequest.

Instance | RemoteAddress | Established | TimeWait
-- | -- | -- | --
[xxxx] | 51.144.124.X:5671 | 4077 | 0

***Code Snippet***
```c#
public class KeyVaultUsernamePasswordChecker
    {
        private string _keyVaultSecretsBaseUri;
        private readonly AzureServiceTokenProvider _azureServiceTokenProvider;
        private readonly KeyVaultClient _keyVaultClient;
        private readonly ILogger<KeyVaultUsernamePasswordChecker> _logger;
        private readonly IMemoryCache _memoryCache;

        public KeyVaultUsernamePasswordChecker(IConfiguration configuration, ILogger<KeyVaultUsernamePasswordChecker> logger, IMemoryCache memoryCache)
        {
            _keyVaultSecretsBaseUri = configuration.GetValue<string>("AppSettings:KeyVaultSecretsBaseUri").TrimEnd('/');
            _azureServiceTokenProvider = new AzureServiceTokenProvider();
            _keyVaultClient = new KeyVaultClient(new KeyVaultClient.AuthenticationCallback(_azureServiceTokenProvider.KeyVaultTokenCallback));
            _logger = logger;
            _memoryCache = memoryCache;
        }

        public async Task<bool> IsValidUserAsync(string username, string password)
        {
            try
            {
                var secretKey = string.Concat(_keyVaultSecretsBaseUri, "/", username);
                var cachedSecretValue = string.Empty;
                var found = _memoryCache.TryGetValue(secretKey, out cachedSecretValue);

                if (found && cachedSecretValue == password) return true;

                var secret = await _keyVaultClient.GetSecretAsync(secretKey);

                _memoryCache.Set(secretKey, secret.Value, TimeSpan.FromMinutes(10));

                var result = secret.Value == password;

                if (result) return true;

                _logger.LogWarning($"Password for user '{username}' is incorrect");

                return false;
            }
            catch (KeyVaultErrorException ex)
            {
                _logger.LogWarning($"User '{username}' not found in KeyVault ('{ex.Message}')");

                return false;
            }
            catch (Exception ex)
            {
                _logger.LogError(new EventId(), ex, $"Unhandled exception while connecting to KeyVault for user/password validation");

                return false;
            }
        }
    }
```

**Expected behavior**

**Screenshots**

**Setup (please complete the following information):**
 - IDE : [e.g. IntelliJ]
 - Version of the Library used
.net framework 4.6.1

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by schaabs** [comment] 2019-05-17 23:57
Closing this as a duplicate of #6003.  We will continue to provide updates on that issue.

**Closed by schaabs** 2019-05-17 23:57 UTC
Labels: triage
