### ISSUE TITLE
[BUG] TraceHelper.AddPropertiesToTelemetry duplicate dictionary key exception when RemoteDependencyData is constructed and activity child/parent have duplicate baggage.

### ISSUE THREAD

**Issue by jakenuts** [Azure/azure-sdk-for-net#38418] opened 2023-08-29 18:22 UTC
### Library name and version

Azure.Monitor.OpenTelemetry.Exporter 1.0.0-beta.15

### Describe the bug

I've seen this in several cases but currently I'm unable to track HttpClient requests if activities that precede them contain duplicate baggage. Since I'm not entirely sure what the "root" activity of a process is I'm attaching a correlation id to several activities using `AddBaggage("correlation-id", "1234")` and when the exporter tries to convert an HttpClient activity that is in that activity lineage `OtelToAzureMonitorTrace` creates a `RemoteDependencyData` and it calls `TraceHelper.AddPropertiesToTelemetry()` the lack of any test before inserting baggage from the parents into the dictionary holding the properties to be transmitted causes a duplicate key exception and the activity is not sent.

### Expected behavior

Presume a set of aggregated keys/value paris defined by a caller, activitiy lineage and varying codepaths might contain duplicates and call TryAdd instead of Add on a dictionary.

### Actual behavior
```
Exception thrown: 'System.Net.Http.HttpRequestException' in System.Net.Http.dll
OpenTelemetry-AzureMonitor-Exporter - EventId: [16], EventName: [FailedToConvertActivity], Message: [Failed to convert Activity due to an exception. This telemetry item will be lost. ActivitySource: System.Net.Http. Activity: HTTP GET. System.ArgumentException: An item with the same key has already been added. Key: dv.correlation.id
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at Azure.Monitor.OpenTelemetry.Exporter.Models.RemoteDependencyData..ctor(Int32 version, Activity activity, ActivityTagsProcessor& activityTagsProcessor)
   at Azure.Monitor.OpenTelemetry.Exporter.Internals.TraceHelper.OtelToAzureMonitorTrace(Batch`1 batchActivity, AzureMonitorResource azureMonitorResource, String instrumentationKey, Single sampleRate)]
Exception thrown: 'System.Net.Http.HttpRequestException' in System.Private.CoreLib.dll
Exception thrown: 'System.ArgumentException' in System.Private.CoreLib.dll
```
### Reproduction Steps

Gah. This is hard. I'm not able to clearly track the exact activity/source that causes the error due to the delayed export and thousands of other activities flowing through that `AddPropertiesToTelemetry` call. I suspect it would involve a parent and child activity that have some duplication in tags/baggage and then using the http client instrumentation to generate a remote depenency event that flows into the exporter.

### Environment

Windows 11 Pro 22621.2215 64-bit 
Visual Studio 17.8.0 Preview 1.0
Net 7.0

**Comment by navba-MSFT** [comment] 2023-08-31 03:09
Adding Service team to look into this.

**Comment by TimothyMothra** [comment] 2023-08-31 17:31
Thanks for the detailed description. I'm investigating.

**Comment by TimothyMothra** [comment] 2023-10-11 18:06
@jakenuts, I've been unable to repro this. 
The baggage shouldn't matter, this isn't added to properties. And the Activity Tags themselves don't allow duplicates.

If you're able to share a minimal repro, that would help us to investigate.

**Comment by vishweshbankwar** [comment] 2023-11-30 18:00
most likely duplicate of https://github.com/Azure/azure-sdk-for-net/issues/40023 --This has been fixed.

@jakenuts FYI

**Closed by vishweshbankwar** 2023-11-30 18:00 UTC
Labels: Service Attention, Client, customer-reported, question, needs-team-attention, Monitor - Exporter
