### ISSUE TITLE
[Metrics Advisor] test failing in nightly runs

### ISSUE THREAD

**Issue by v-yilinhu** [Azure/azure-sdk-for-net#22042] opened 2021-06-22 08:51 UTC
Metrics Advisor nightly test runs are failing with:

> Error Message
> Azure.RequestFailedException : Service request failed.
> Status: 400 (Bad Request)
> 
> Content:
> {"code":"Bad Request","message":"Invalid parameter. scopes can NOT be empty. TraceId: 27be4393-58bd-4741-bee5-51130e7ba50f"}
> 
> Headers:
> X-Request-ID: bb1e275a-6a40-48d0-bca6-2118e0a26956
> x-envoy-upstream-service-time: 109
> apim-request-id: bb1e275a-6a40-48d0-bca6-2118e0a26956
> Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
> X-Content-Type-Options: nosniff
> Date: Fri, 11 Jun 2021 18:23:43 GMT
> Content-Length: 124
> Content-Type: application/json; charset=utf-8
> 
> Stack Trace
> at Azure.AI.MetricsAdvisor.MicrosoftAzureMetricsAdvisorRestAPIOpenAPIV2RestClient.GetAnomalyAlertingConfigurationsByAnomalyDetectionConfigurationAsync(Guid configurationId, Nullable`1 skip, Nullable`1 maxpagesize, CancellationToken cancellationToken) in /_/sdk/metricsadvisor/Azure.AI.MetricsAdvisor/src/Generated/MicrosoftAzureMetricsAdvisorRestAPIOpenAPIV2RestClient.cs:line 885
>    at Azure.AI.MetricsAdvisor.Administration.MetricsAdvisorAdministrationClient.<>c__DisplayClass42_0.<<GetAlertConfigurationsAsync>g__FirstPageFunc|0>d.MoveNext() in /_/sdk/metricsadvisor/Azure.AI.MetricsAdvisor/src/MetricsAdvisorAdministrationClient.cs:line 1358
> --- End of stack trace from previous location where exception was thrown ---
>    at Azure.Core.PageableHelpers.FuncAsyncPageable`1.AsPages(String continuationToken, Nullable`1 pageSizeHint) in /_1/microsoft.azure.autorest.csharp/3.0.0-beta.20210604.3/content/Generator.Shared/PageableHelpers.cs:line 56
>    at System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore`1.GetResult(Int16 token)
>    at Azure.Core.PageableHelpers.FuncAsyncPageable`1.AsPages(String continuationToken, Nullable`1 pageSizeHint)
>    at Azure.Core.TestFramework.DiagnosticScopeValidatingInterceptor.DiagnosticScopeValidatingAsyncEnumerable`1.<>c__DisplayClass5_0.<<AsPages>b__0>d.MoveNext() in D:\a\_work\1\s\sdk\core\Azure.Core.TestFramework\src\Instrumentation\DiagnosticScopeValidatingInterceptor.cs:line 255
> --- End of stack trace from previous location where exception was thrown ---
>    at Azure.Core.TestFramework.DiagnosticScopeValidatingInterceptor.ValidateDiagnosticScope[T](Func`1 action, MethodInfo methodInfo, String source) in D:\a\_work\1\s\sdk\core\Azure.Core.TestFramework\src\Instrumentation\DiagnosticScopeValidatingInterceptor.cs:line 165
>    at Azure.Core.TestFramework.DiagnosticScopeValidatingInterceptor.DiagnosticScopeValidatingAsyncEnumerable`1.AsPages(String continuationToken, Nullable`1 pageSizeHint) in D:\a\_work\1\s\sdk\core\Azure.Core.TestFramework\src\Instrumentation\DiagnosticScopeValidatingInterceptor.cs:line 253
>    at Azure.Core.TestFramework.DiagnosticScopeValidatingInterceptor.DiagnosticScopeValidatingAsyncEnumerable`1.AsPages(String continuationToken, Nullable`1 pageSizeHint) in D:\a\_work\1\s\sdk\core\Azure.Core.TestFramework\src\Instrumentation\DiagnosticScopeValidatingInterceptor.cs:line 253
>    at System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore`1.GetResult(Int16 token)
>    at Azure.Core.TestFramework.DiagnosticScopeValidatingInterceptor.DiagnosticScopeValidatingAsyncEnumerable`1.AsPages(String continuationToken, Nullable`1 pageSizeHint)
>    at Azure.AsyncPageable`1.GetAsyncEnumerator(CancellationToken cancellationToken)
>    at Azure.AsyncPageable`1.GetAsyncEnumerator(CancellationToken cancellationToken)
>    at System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore`1.GetResult(Int16 token)
>    at Azure.AI.MetricsAdvisor.Tests.AnomalyAlertConfigurationLiveTests.GetAlertConfigurations(Boolean useTokenCredential) in D:\a\_work\1\s\sdk\metricsadvisor\Azure.AI.MetricsAdvisor\tests\MetricsAdvisorAdministrationClient\AnomalyAlertConfigurationLiveTests.cs:line 868
>    at Azure.AI.MetricsAdvisor.Tests.AnomalyAlertConfigurationLiveTests.GetAlertConfigurations(Boolean useTokenCredential) in D:\a\_work\1\s\sdk\metricsadvisor\Azure.AI.MetricsAdvisor\tests\MetricsAdvisorAdministrationClient\AnomalyAlertConfigurationLiveTests.cs:line 868
>    at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.BlockUntilCompleted()
>    at NUnit.Framework.Internal.MessagePumpStrategy.NoMessagePumpStrategy.WaitForCompletion(AwaitAdapter awaiter)
>    at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.<>c__Displa

For more details check here:

- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=943871&view=results
- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=944035&view=results

**Comment by kinelski** [comment] 2021-06-22 19:59
Duplicate of https://github.com/Azure/azure-sdk-for-net/issues/18004.

**Closed by kinelski** 2021-06-22 19:59 UTC
Labels: Client, Cognitive - Metrics Advisor, test-reliability
