### ISSUE TITLE
[Core] Move Mocking Transport to Azure.Core

### ISSUE THREAD

**Issue by KrzysztofCwalina** [Azure/azure-sdk-for-net#28462] opened 2022-04-29 16:08 UTC
### API Change Needed

Yes

### Background and motivation

Currently Azure.Core request, response, and transport are all very abstract. Implementing a simple "mocking" or a custom transport (e.g. a transport that injects faults) requires a lot of boilerplate code. It would be great to have some simple subtypes of Request, Response, and possibly the transport in Azure.Core. 

We have such types in our testing framework, but they need to be cleaned up and the transport needs to be decoupled from recording framework. 

### API / Feature Proposal

```C#
namespace Azure.Core.Pipeline
{
    public class CoreResponse : Response
    {
    }
    public class CoreRequest : Request
    {
    }
}
```

### Time Constraints and Dependencies

No deadline

### Stakeholders

@annelo-msft

**Comment by JoshLove-msft** [comment] 2022-04-29 18:27
The MockTransport is not used by the recording framework anymore.

- [MockTransport](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/Azure.Core.TestFramework/src/MockTransport.cs)
- [MockRequest](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/Azure.Core.TestFramework/src/MockRequest.cs)
- [MockResponse](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/Azure.Core.TestFramework/src/MockResponse.cs)

**Comment by JoshLove-msft** [comment] 2022-09-29 21:21
Mocking responses is discussed here - https://devblogs.microsoft.com/azure-sdk/unit-testing-and-mocking/#response. This can be done already using Moq.

**Comment by heaths** [comment] 2022-09-29 22:57
But we could provide some useful testing framework for our users. Like our `MockResponse` factory that you can do with `MockTransport` is nice. Maybe not in Azure.Core, but what if we shipped some generalized parts of Azure.Core.TestFramework to the general public so they don't always have to themselves? I suppose backward compatibility would be a question - whether we guarantee it or not - so maybe that's a non-starter. I think it's worth consider, though.

For example, for writing GitHub CLI extensions, they broke out a separate `go-gh` project that I've also been helping with because it makes writing extensions easier using the same code (in some cases; working on increasing that) that the `gh` CLI uses because it also uses `go-gh`.

**Comment by JoshLove-msft** [comment] 2022-09-29 23:15
> But we could provide some useful testing framework for our users. Like our `MockResponse` factory that you can do with `MockTransport` is nice.

Hmm it would be good to have an example of what you can do with MockTransport in a test vs how/whether it is possible using only Moq.

**Comment by heaths** [comment] 2022-10-01 08:18
It's not whether it's doable in Moq or not, but how much easier it is to conditionally return responses e.g.,
```C#
new MockTransport((req, res) =>
{
  if (req.Uri.Path == "/foo/bar") return MockResponse(...);
  if (req.Uri.Path == "/baz" && req.Uri.QueryString.Contains("id=1")) return MockResponse(...);
});
```
Or, probably more common,
```C#
new MockTransport(new[]
{
  new MockResponse(401, ...),
  new MockResponse(200, ...),
});
```

**Comment by christothes** [comment] 2022-10-03 15:14
Wouldn't users of the SDK just mock the client directly rather than getting involved with the implementation details of the transport?

**Comment by heaths** [comment] 2022-10-03 17:56
🤔 That's a very good point.

**Comment by pallavit** [comment] 2023-10-16 22:38
Given the last conversation here. Can this issue be closed? We already have Mock types, samples and decoupling of transport from the Response and Request already done.

/cc: @annelo-msft , @JoshLove-msft , @heaths

**Comment by annelo-msft** [comment] 2023-10-23 15:17
@pallavit, I think it would be best if @KrzysztofCwalina could share his perspective regarding whether he feels like the higher-level intent of the issue has been met before closing it out.

**Comment by pallavit** [comment] 2023-10-23 16:27
> @pallavit, I think it would be best if @KrzysztofCwalina could share his perspective regarding whether he feels like the higher-level intent of the issue has been met before closing it out.

Sure. @KrzysztofCwalina let us know if the issue is still valid and if there are any open-items you would like us to address as part of this.

**Closed** 2024-04-29 18:04 UTC
Labels: Client, Azure.Core, feature-request, Azure.Core.TestFramework
