### ISSUE TITLE
[QUERY] How to Get Snapshot Information From Incomplete SnapshotCollection.CreateOrUpdateAsync

### ISSUE THREAD

**Issue by mwhouser** [Azure/azure-sdk-for-net#38429] opened 2023-08-30 16:48 UTC
### Library name and version

Azure.ResourceManager.Compute 1.1.0

### Query/Question

I am calling the following on `SnapshotCollection`:

```csharp
var response = await snapshots.CreateOrUpdateAsync(WaitUntil.Started, snapshotName, snapshot);
```

I do not want to wait for the snapshot to be complete, but I want to access the returned snapshot information.

Calling the following shows that snapshot JSON information is indeed returned:

```csharp
string json = response.GetRawResponse().Content;
```

But calling `response.Value` throws an exception because the operation is incomplete.

FYI, I am migrating from the old Fluent Azure API. I used to do the following:

```csharp
IComputeManagementClient client = ... ;
var response = await client.Snapshots.BeginCreateOrUpdateWithHttpMessagesAsync(resourceGroupName, snapshotName, snapshot);
// response.Body has the snapshot information
```

### Environment

.NET Framework 4.7.2
Visual Studio 2019
Windows 10 (on Windows Server)

**Comment by jsquire** [comment] 2023-08-31 13:27
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by HarveyLink** [comment] 2023-11-14 07:01
Hi @mwhouser ,Thank you for using Azure SDK for .NET.
Unfortunately there is no way to get the resource properties until the long running operation is complete. It's by design.

**Comment by mwhouser** [comment] 2023-11-14 15:19
@HarveyLink that is incorrect because:

1. The snapshot information IS being returned in the response body,
2. The old SDK parsed that information and made it available, and
3. I was able to do it manually as seen below.

```csharp
var response = await snapshots.CreateOrUpdateAsync(WaitUntil.Started, snapshotName, snapshot);

var rawResponse = response.GetRawResponse();
string json = rawResponse.Content.ToString();
var responseSnapshot = JsonSerializer.Deserialize<ForDeserialization.SnapshotData>(json, new JsonSerializerOptions()
{
	PropertyNameCaseInsensitive = true,
});
```

In my case, I am just interested in the provisioning state, which is present in the response, even if the snapshot is incomplete.

**Comment by mwhouser** [comment] 2023-11-14 15:22
@HarveyLink that is incorrect because:

1. The snapshot information IS being returned in the response body,
2. The old SDK parsed that information and made it available, and
3. I was able to do it manually as seen below.

```csharp
var response = await snapshots.CreateOrUpdateAsync(WaitUntil.Started, snapshotName, snapshot);

var rawResponse = response.GetRawResponse();
string json = rawResponse.Content.ToString();
var responseSnapshot = JsonSerializer.Deserialize<ForDeserialization.SnapshotData>(json, new JsonSerializerOptions()
{
	PropertyNameCaseInsensitive = true,
});
```

In my case, I am just interested in the provisioning state, which is present in the response, even if the snapshot is incomplete.

/unresolve

**Comment by mwhouser** [comment] 2023-11-14 15:44
And the Azure REST API documentation for creating disk snapshots includes snapshot information in the response: https://learn.microsoft.com/en-us/rest/api/compute/snapshots/create-or-update?view=rest-compute-2023-04-02&tabs=HTTP

**Comment by HarveyLink** [comment] 2024-03-12 09:48
Closed as it's by design that current SDK doesn't support get resource property in the middle of LRO.

**Closed by HarveyLink** 2024-03-12 09:48 UTC
Labels: Compute, Mgmt, customer-reported, question, needs-team-attention
