### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by vinagesh** [Azure/azure-sdk-for-net#14416] opened 2020-08-20 18:14 UTC
**Describe the bug**
Using the JsonPathSanitizer is not sanitizing the secrets the request body but it sanitizes the values in the response. My playback tests fail due to this. 

**Expected behavior**
Call API 1
User response value of API to call API 2

Expected behavior is the response of API1 and the request body in API2 have the same values.

**Actual behavior (include Exception or Stack Trace)**
The recorded json for API 1 response sanitizes the value passed to API2
The recorded json for API 2 call does not have this value sanitized

**To Reproduce**
Steps to reproduce the behavior (include a code snippet, screenshot, or any additional information that might help us reproduce the issue)

Please contact me and I can quickly help demonstrate it.
Branch with the json file - https://github.com/Azure/azure-sdk-for-net/pull/14414/files

Line 102 and 103 it got sanitized but not line 131 (primaryKey and secondaryKey)

**Environment:**
 - Azure.Iot.Hub.Service
 - IDE and version - Visual Studio 2019]

**Comment by vinagesh** [comment] 2020-08-20 18:14
@JoshLove-msft @maririos

**Comment by jsquire** [comment] 2020-08-20 19:57
Closing as a duplicate of #14415.

**Closed by jsquire** 2020-08-20 19:57 UTC
Labels: needs-triage
