### ISSUE TITLE
Eventhubs Sovereign test failure

### ISSUE THREAD

**Issue by tzhanl** [Azure/azure-sdk-for-net#17833] opened 2021-01-07 06:34 UTC
Use this issue to track Eventhubs sovereign test failures.

https://dev.azure.com/azure-sdk/internal/_build/results?buildId=677068&view=results

several tests not stable.

@danieljurek @benbp @jongio

**Comment by jsquire** [comment] 2021-01-07 15:19
There were three failures observed in the linked run, none specific to the sovereign clouds.   Two of the failures were known Track One test issues, tracked elsewhere and owned by the service team; the other was a timeout due to the service not responding in a reasonable amount of time.  

I've kicked off another run to see if there is any consistency with the timeout appearing in a specific region and values should be tweaked.   If not, then I'll close this out.

**Comment by jsquire** [comment] 2021-01-08 21:39
Confirmed.  I did a few runs and the only consistent failures that I'm seeing are the expected T1 flaky tests.    There have been some relevant changes in master that help offset as well.   I don't see any action that needs to be taken prior to running on sovereign clouds.   We'll continue to monitor and address any flaky behavior as it presents.

The thing that I did note is responsiveness of US Gov and (especially) China seems to be slower than the public clouds.  We should consider bumping up the timeout threshold for these clouds.   

@danieljurek, @benbp, and @weshaggard:  do any of you folks have a recommended means of detecting the current cloud within `testresources.json` to emit a different ENV variable or, maybe, to pass a unique parameter value to the template based on the target cloud?

**Comment by benbp** [comment] 2021-01-08 23:09
@jsquire we do have the cloud environment available at the New-TestResources.ps1 level when it calls the template. We've been doing most value switching and changes (like for secrets) at the pipeline variable level. Though if we wanted to embed formatting or other logic changes into the arm template, you could key it off a parameter/env variable that we could pass down. It would be helpful for me to understand some scenarios where this would be used, if you have them.

**Comment by jsquire** [comment] 2021-01-11 20:08
After discussing some options, I'm not going to make any further changes at this point; we'll continue to monitor for any flaky tests and/or environmental issues and address them as needed.

Please feel free to enable the sovereign clouds as desired for Event Hubs.

**Closed by jsquire** 2021-01-11 20:08 UTC
Labels: Client, Event Hubs, test-sovereign-cloud
