### ISSUE TITLE
[TextAnalytics] AnalyzeHealthcareEntitiesAsync failing in nightly runs

### ISSUE THREAD

**Issue by AFengKK** [Azure/azure-sdk-for-net#32990] opened 2022-12-09 07:49 UTC
TextAnalytics nightly test runs are failing with:
> 
> Error message
> Azure.RequestFailedException : Access denied due to invalid subscription key or wrong API endpoint. Make sure to provide a valid key for an active subscription and use a correct regional API endpoint for your resource.
> Status: 401 (PermissionDenied)
> ErrorCode: 401
> 
> Content:
> {"error":{"code":"401","message":"Access denied due to invalid subscription key or wrong API endpoint. Make sure to provide a valid key for an active subscription and use a correct regional API endpoint for your resource."}}
> 
> Headers:
> apim-request-id: 804c36e1-b511-490d-868e-2839554c411d
> Date: Wed, 07 Dec 2022 02:52:12 GMT
> Content-Length: 224
> Content-Type: application/json
> 
> 
> Stack trace
>    at Azure.AI.TextAnalytics.MicrosoftCognitiveLanguageServiceTextAnalysisRestClient.AnalyzeBatchSubmitJobAsync(AnalyzeTextJobsInput body, CancellationToken cancellationToken) in /mnt/vss/_work/1/s/sdk/textanalytics/Azure.AI.TextAnalytics/src/Generated/MicrosoftCognitiveLanguageServiceTextAnalysisRestClient.cs:line 162
>    at Azure.AI.TextAnalytics.ServiceClients.LanguageServiceClient.StartAnalyzeHealthcareEntitiesAsync(MultiLanguageAnalysisInput multiLanguageInput, AnalyzeHealthcareEntitiesOptions options, CancellationToken cancellationToken) in /mnt/vss/_work/1/s/sdk/textanalytics/Azure.AI.TextAnalytics/src/ServiceClients/LanguageServiceClient.cs:line 1439
>    at Azure.AI.TextAnalytics.ServiceClients.LanguageServiceClient.StartAnalyzeHealthcareEntitiesAsync(IEnumerable`1 documents, AnalyzeHealthcareEntitiesOptions options, CancellationToken cancellationToken) in /mnt/vss/_work/1/s/sdk/textanalytics/Azure.AI.TextAnalytics/src/ServiceClients/LanguageServiceClient.cs:line 1376
>    at Azure.AI.TextAnalytics.TextAnalyticsClient.StartAnalyzeHealthcareEntitiesAsync(IEnumerable`1 documents, AnalyzeHealthcareEntitiesOptions options, CancellationToken cancellationToken) in /mnt/vss/_work/1/s/sdk/textanalytics/Azure.AI.TextAnalytics/src/TextAnalyticsClient.cs:line 1686
>    at Azure.AI.TextAnalytics.Samples.TextAnalyticsSamples.AnalyzeHealthcareEntitiesAsync() in /mnt/vss/_work/1/s/sdk/textanalytics/Azure.AI.TextAnalytics/tests/samples/Sample7_AnalyzeHealthcareEntitiesAsync.cs:line 61
>    at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.BlockUntilCompleted()
>    at NUnit.Framework.Internal.MessagePumpStrategy.NoMessagePumpStrategy.WaitForCompletion(AwaitAdapter awaiter)
>    at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
>    at NUnit.Framework.Internal.Execution.SimpleWorkItem.<>c__DisplayClass4_0.<PerformWork>b__0()
>    at NUnit.Framework.Internal.ContextUtils.<>c__DisplayClass1_0`1.<DoIsolated>b__0(Object _)
>    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
> --- End of stack trace from previous location ---
>    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
>    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
>    at NUnit.Framework.Internal.ContextUtils.DoIsolated(ContextCallback callback, Object state)
>    at NUnit.Framework.Internal.ContextUtils.DoIsolated[T](Func`1 func)
>    at NUnit.Framework.Internal.Execution.SimpleWorkItem.PerformWork()
> 

For more details check here:

- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2037742&view=results

@jsquire for notification.

**Comment by joseharriaga** [comment] 2023-04-10 16:33
This is a duplicate of https://github.com/Azure/azure-sdk-for-net/issues/35452.

**Closed by joseharriaga** 2023-04-10 16:33 UTC
Labels: Client, Cognitive - Text Analytics, test-reliability
