### ISSUE TITLE
[BUG] 'authority' should be in Uri format when running in Docker container

### ISSUE THREAD

**Issue by profesor79** [Azure/azure-sdk-for-net#12266] opened 2020-05-22 13:12 UTC
**Describe the bug**
When running below snippet in 3.1 .net core SDK container:
               `  creds = await ApplicationTokenProvider.LoginSilentAsync(_domain, _clientId, _clientSecret, adSettings);`

When running on the host - no issues.
Container has access to network with no limits.

***Exception or Stack Trace***
"ClassName": "System.ArgumentException",
  "Message": "'authority' should be in Uri format",
  "Data": null,
  "InnerException": null,
  "HelpURL": null,
  "StackTraceString": "   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Instance.Authenticator.DetectAuthorityType(String authority)\n   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Instance.Authenticator.Init(String authority, Boolean validateAuthority)\n   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Instance.Authenticator..ctor(String authority, Boolean validateAuthority)\n   at Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext..ctor(IHttpManager httpManager, String authority, AuthorityValidationType validateAuthority, TokenCache tokenCache)\n   at Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext..ctor(String authority, Boolean validateAuthority, TokenCache tokenCache)\n   at Microsoft.Rest.Azure.Authentication.ApplicationTokenProvider.GetAuthenticationContext(String domain, ActiveDirectoryServiceSettings serviceSettings, TokenCache cache)\n   at Microsoft.Rest.Azure.Authentication.ApplicationTokenProvider.LoginSilentAsync(String domain, String clientId, IApplicationAuthenticationProvider authenticationProvider, ActiveDirectoryServiceSettings settings, TokenCache cache)\n   at Microsoft.Rest.Azure.Authentication.ApplicationTokenProvider.LoginSilentAsync(String domain, ClientCredential credential, ActiveDirectoryServiceSettings settings, TokenCache cache)\n   at Microsoft.Rest.Azure.Authentication.ApplicationTokenProvider.LoginSilentAsync(String domain, String clientId, String secret, ActiveDirectoryServiceSettings settings, TokenCache cache)\n   at Microsoft.Rest.Azure.Authentication.ApplicationTokenProvider.LoginSilentAsync(String domain, String clientId, String secret, ActiveDirectoryServiceSettings settings)\n   at ***AnalyticsReaderBase.HandleTimer(DateTime queryStartTime, Int32 retry, Guid requestId) in****AnalyticsReaderActorBase.cs:line 90",
  "RemoteStackTraceString": null,
  "RemoteStackIndex": 0,
  "ExceptionMethod": null,
  "HResult": -2147024809,
  "Source": "Microsoft.IdentityModel.Clients.ActiveDirectory",
  "WatsonBuckets": null,
  "ParamName": "authority"

**To Reproduce**
Create a snippet that is creating creds
Push code to container

***Code Snippet***
`creds = await ApplicationTokenProvider.LoginSilentAsync(_domain, _clientId, _clientSecret, adSettings);
`

**Expected behavior**
shall return creds handler

**Screenshots**
![image](https://user-images.githubusercontent.com/11340526/82678658-e19a1400-9c41-11ea-8651-021b53a0c3e8.png)

**Setup (please complete the following information):**
 - OS: docker .net Core SDK 3.1 container
 - IDE : n/a
 - Version of the Library used "Microsoft.Rest.ClientRuntime.Azure.Authentication" Version="2.4.0"

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ x] Bug Description Added
- [ x] Repro Steps Added
- [ x] Setup information Added

**Comment by yungezz** [comment] 2020-05-25 02:04
This is an issue in Track1 runtime auth lib. transfer it here.

**Comment by yungezz** [comment] 2020-06-09 02:48
this is an issue in Track1 runtime auth lib, hi @danielmarbach do  you know whos' right owner of Track1 Authlib now?

**Comment by danielmarbach** [comment] 2020-06-09 06:56
@yungezz not sure why I got pinged here, maybe because I contributed to the code? sorry I have not context other than being some rando from time to time contributing some code 👯‍♂️

**Comment by yungezz** [comment] 2020-06-09 07:00
> @yungezz not sure why I got pinged here, maybe because I contributed to the code? sorry I have not context other than being some rando from time to time contributing some code 👯‍♂️

sorry for ping.  Yes I found your contribution from history. 😊

**Comment by profesor79** [comment] 2020-06-17 22:23
Guys,
one important remark that could lead us to issue: Today I run my program as a daemon as a root on my centos vm and I got same issue. Can that be connected to an env variable?
```

[Unit]
Description=my program

[Service]
ExecStart=/data/software/run.sh
Restart=on-failure

[Install]
WantedBy=multi-user.target 
```

**Comment by yungezz** [comment] 2020-06-18 01:50
hi @AlexGhiondea I reassign the issue to you, the issue is about Track1 runtime auth lib. Pls help to redirect to correct owner. Thanks in advance.

**Comment by profesor79** [comment] 2020-08-20 10:57
any update on that?

**Comment by profesor79** [comment] 2020-12-09 09:03
??? any updates team on that?

**Comment by AlexGhiondea** [comment] 2021-10-01 17:29
@schaabs @christothes can you take a look at this?

**Comment by christothes** [comment] 2021-10-01 20:32
@profesor79 Are you able to upgrade to Azure.Identity for this scenario?

**Comment by profesor79** [comment] 2021-10-09 05:47
Hi guys,
Unfortunately I can't test it as I'm in a new company.

**Comment by AlexGhiondea** [comment] 2021-10-10 16:21
Thank you @profesor79. Closing for now.

**Closed by AlexGhiondea** 2021-10-10 16:21 UTC
Labels: Mgmt, customer-reported, question, Authentication, AutoRest Runtime, needs-team-attention
