### ISSUE TITLE
[BUG] Azure.Response's HasValue property always returns true, even when the underlying value is null

### ISSUE THREAD

**Issue by phleebagg** [Azure/azure-sdk-for-net#38723] opened 2023-09-14 21:09 UTC
### Library name and version

Azure.Storage.Queues 12.14.0

### Describe the bug

When calling QueueClient.ReceiveMessage() on an empty queue, Response.HasValue returns true even though the inner message is null. This is the case with either Azurite local queue or a live instance of Azure Storage.

Is this just my misunderstanding what the Azure.Response object is supposed to be?

Sample code:
```
var queueClient = new QueueClient(connectionString, queueName, new QueueClientOptions {
    MessageEncoding = QueueMessageEncoding.Base64
});

//set up test queue
queueClient.Create();

var response = queueClient.ReceiveMessage(); // no messages in fresh queue
Console.WriteLine(response.HasValue) // should be false, but is true

response.Value.Body; // NullReferenceException
```

### Expected behavior

Response.HasValue = false

### Actual behavior

Response.HasValue = true

### Reproduction Steps

See sample code above.

**Comment by navba-MSFT** [comment] 2023-09-22 04:09
@phleebagg Apologies for the late reply. Thanks for reaching out to us and reporting this issue. 

I am able to reproduce this issue at my end using the above code you had shared. I see that the API that is being called is [Get-Messages](https://learn.microsoft.com/en-us/rest/api/storageservices/get-messages) and the response received is below:

```
<?xml version="1.0" encoding="utf-8"?><QueueMessagesList />
```

I would have expected the `response.HasValue` to be false. 

@seanmcc-msft @amnguye Is this a bug ? Any pointers on this are much appreciated.

**Comment by navba-MSFT** [comment] 2023-09-27 07:51
@seanmcc-msft @amnguye A quick follow-up to check if you had a chance to look into this. Is this a bug ? Any pointers on this are much appreciated.

**Comment by amnguye** [comment] 2023-09-28 21:35
Hm. I think this may be a `Response<T>` issue.

If you look at the Azure.Core by default it will always return `true`.

https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/Azure.Core/src/ResponseOfT.cs#L23

So unrelated to the Storage `QueueClient.ReceiveMessages`, since by default `Response<QueueMessages[]>` which is the return object of `QueueClient.ReceiveMessages` will inherit that value automatically.

I probably don't have the best explanation to why it does this by default. Tagging Azure.Core to see if there's an explanation here.

**Comment by navba-MSFT** [comment] 2023-10-03 07:18
Service team is involved to look into this.

**Comment by seanmcc-msft** [comment] 2024-01-30 21:19
@jsquire this appears to be an issue on the Azure Core side.

**Comment by jsquire** [comment] 2024-01-30 22:06
Thanks for the redirect, @seanmcc-msft.   This is a duplicate of #35475 and got missed during triage.

**Closed** 2024-02-06 22:33 UTC
Labels: Client, Azure.Core, customer-reported, question, issue-addressed
