### ISSUE TITLE
Specifying Scope for publishing fails to publish scope specific projects/nugets

### ISSUE THREAD

**Issue by shahabhijeet** [Azure/azure-sdk-for-net#2549] opened 2016-11-17 00:12 UTC
Specifying Scope during publish or build fails to publish particular scope project if the scope specified has multiple projects.
Investigation:
1) We search for .sln files during build and hence once we find the sln file we move forward to start the build.
2) Nest projects in a scope is simply ignored.

**Comment by markcowl** [comment] 2016-12-02 18:23
Closing as duplicate of #2300

**Closed by markcowl** 2016-12-02 18:23 UTC
