### ISSUE TITLE
CloudConfigurationManager.GetSetting returns null after updating to 3.0.0

### ISSUE THREAD

**Issue by ellern** [Azure/azure-sdk-for-net#1006] opened 2015-03-19 14:05 UTC
CloudConfigurationManager.GetSetting("name") started to return null on worker roles after updating Microsoft.WindowsAzure.ConfigurationManager to version 3.0.0, which is the latest stable version available on NuGet.

**Comment by mleyb** [comment] 2015-03-19 14:09
I have the exact same problem. The 3.0.0 nuget version does not give back config values when deployed in the emulator or Azure. The problem seems to be that the Microsoft.Azure.ServiceRuntime assembly cannot be loaded in Microsoft.Azure.ApplicationSettings.GetServiceRuntimeAssembly() for some reason.

**Comment by awcab** [comment] 2015-03-19 17:31
I'm seeing this problem in web and worker roles.

**Comment by awcab** [comment] 2015-03-19 19:24
It seems that this is because of the namespace name change.  The ServiceRuntime that the 2.5 SDK provides is named Microsoft.WindowsAzure, but the assembly that ApplicationSettings is searching for is Microsoft.Azure.ServiceRuntime.  I'm taking this to mean that a new SDK is imminent and/or maybe the nuget deployment was premature.

**Comment by smithkl42** [comment] 2015-03-19 20:51
(Same here, FWIW - see http://stackoverflow.com/questions/29152382/cloudconfigurationmanager-getsetting-returns-null-with-azure-configuration-man.)

**Comment by ogail** [comment] 2015-03-19 22:24
Thanks folks, we are working on getting a fix for this

**Comment by awcab** [comment] 2015-03-19 23:33
Thanks for the update @ogail !

**Comment by ogail** [comment] 2015-03-19 23:46
@awcab here's the PR https://github.com/Azure/azure-sdk-for-net/pull/1008

**Comment by artfulhacker** [comment] 2015-03-20 00:22
@ogail did this just get released to nuget?

https://www.nuget.org/packages/Microsoft.WindowsAzure.ConfigurationManager/3.1.0

**Comment by awcab** [comment] 2015-03-20 00:28
@artfulhacker It did - I just pulled it down.

**Comment by awcab** [comment] 2015-03-20 00:33
@ogail This fixed it for me.  Thanks so much for the quick turnaround.

**Comment by artfulhacker** [comment] 2015-03-20 00:36
@awcab thanks for testing, @ogail also appreciate the quick turnaround

**Comment by ogail** [comment] 2015-03-20 01:01
Yes, it's released. Thanks for the testing! I will close this now, please create a new issue if you faced any issues.

**Comment by d-popov** [comment] 2015-05-26 17:02
I just updated to 3.1.0 via the NuGet package, and have the same problem? Any ideas? It was a part of the update to Azure SDK 2.6

**Comment by a11smiles** [comment] 2016-03-16 03:34
After upgrading from 3.1.0 to 3.2.1, `CloudConfigurationManager.GetSetting()` now throws a `MissingMethodException`

**Comment by justsayno** [comment] 2016-03-22 05:22
I am also experiencing this problem . I cannot get any sort of app setting using CloudConfigurationManager... Any Ideas on a work around (other than just getting it as an environment variable)

**Comment by markcowl** [comment] 2016-05-06 22:28
Closing as duplicate of #1276

**Closed by markcowl** 2016-05-06 22:28 UTC
Labels: Team
