### ISSUE TITLE
ManagedIdentityCredential has no token caching support

### ISSUE THREAD

**Issue by ncksol** [Azure/azure-sdk-for-net#24045] opened 2021-09-16 15:10 UTC
**Query/Question**
In the documentation about App Authentication (https://docs.microsoft.com/en-us/dotnet/api/overview/azure/service-to-service-authentication) it is mentioned that for any new application we should be using the new Azure.Identity library for authentication. Yet the new library doesn't cache tokens when requested using GetTokenAsync, while the "legacy" library does.
First of all, the lack of caching is not actually mentioned anywhere in [this update article](https://docs.microsoft.com/en-us/dotnet/api/overview/azure/app-auth-migration). We have found this out the hard way after migration. Should probably mention it?
But more importantly, what's the plan going forward? Is it expected that from now on we should be taking care of token caching ourselves? Or will internal cache be added to Azure.Identity at some point in the future?

**Comment by jsquire** [comment] 2021-09-16 16:10
Thank you for your feedback.  Tagging and routing to the team members best able to assist.

**Comment by christothes** [comment] 2021-09-16 17:41
Hi @ncksol - The reference documentation for GetToken does mention this ([example here](https://docs.microsoft.com/en-us/dotnet/api/azure.identity.interactivebrowsercredential.gettoken?view=azure-dotnet). 

In practice though, some credentials do cache because of the underlying implementation provided by MSAL. We also allow for some configuration of token cache for scenarios where you need to share cache across credential instances. See [this sample](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/identity/Azure.Identity/samples/TokenCache.md) for more information.

Which credential are you using where caching didn't seem to be available?

**Comment by ncksol** [comment] 2021-09-17 09:35
Hi @christothes. That example is not very relevant to my case. I am trying to connect to azure sql db using connection string that doesn't have credentials. For that purpose I am doing:
```
var tokenRequestContext = new TokenRequestContext(AzureSqlScopes);
var token = new DefaultAzureCredential().GetToken(tokenRequestContext);
sqlConnection.AccessToken = token.Token;
```
Previously we were using legacy library:
```
var tokenProvider = new AzureServiceTokenProvider();
var accessToken = await tokenProvider.GetAccessTokenAsync(ResourceId);
sqlConnection.AccessToken = accessToken .Token;
```
In the legacy scenario we've observed that token is being cached internally, while using new Azure.Identity approach we are spamming Azure with token requests.

**Comment by christothes** [comment] 2021-09-17 12:52
Sounds like you are using the Managed Identity credential. Since this is not a credential that is implemented with MSAL, there is no caching for this currently. It's possible that MSAL will implement some changes in the future that will allow us to use it for caching, but we have no plans to duplicate the caching logic implemented by the MSAL library.

**Comment by ncksol** [comment] 2021-09-17 13:19
@christothes so would you recommend us to continue using AzureServiceTokenProvider for the time being? Since it does seem to have the caching. We got thrown off by that documentation, I've linked, that recommended to use Azure.Identity.

**Comment by christothes** [comment] 2021-09-17 13:25
If built-in token caching for Managed Identity authorization is the most important feature for your scenario then yes.

**Comment by pakrym** [comment] 2021-09-17 15:47
Related https://github.com/Azure/azure-sdk-for-net/issues/24046

**Comment by christothes** [comment] 2021-11-17 17:03
duplicate of #25361

**Closed by christothes** 2021-11-17 17:03 UTC
Labels: Client, Azure.Identity, customer-reported, question, feature-request
