### ISSUE TITLE
[FEATURE REQ] Merge RawRequestUriBuilder into RequestUriBuilder

### ISSUE THREAD

**Issue by pakrym** [Azure/azure-sdk-for-net#26534] opened 2022-01-21 17:48 UTC
### Library name

Azure.Core

### Please describe the feature.

The RawRequestUriBuilder shared code hasn't changed for a long time and the feature it brings is pretty uncontroversial.

**Comment by annelo-msft** [comment] 2023-08-16 21:21
Closing as duplicate of https://github.com/Azure/azure-sdk-for-net/issues/32006

**Closed by annelo-msft** 2023-08-16 21:21 UTC
Labels: Client, Azure.Core, feature-request
