### ISSUE TITLE
NullReferenceException in Create method when specifying JobRecurrenceSchedule

### ISSUE THREAD

**Issue by jturinetti** [Azure/azure-sdk-for-net#735] opened 2014-07-23 19:47 UTC
I'm getting a NullReferenceException when calling the Create method to create a new Scheduler job.  

An unhandled exception of type 'System.NullReferenceException' occurred in Microsoft.Threading.Tasks.dll
Additional information: Object reference not set to an instance of an object.

This is occurring only when I specify one or more JobRecurrenceSchedule parameters.  Here is a code sample:

```
var jobCreateParams = new JobCreateParameters()
{
	Action = new JobAction()
	{
		ErrorAction = this.GenerateAzureJobErrorAction(newJobIdentifier),
		RetryPolicy = this.GenerateAzureRetryPolicy(),
		Type = Microsoft.WindowsAzure.Scheduler.Models.JobActionType.Https,
		Request = new JobHttpRequest()
		{                     
			Headers = requestHeaders.IncludeJsonHeaders(),                                              
			Method = HttpMethod.POST.ToString(),
			Uri = new Uri(SchedulerConfiguration.SchedulerBrokerEndpoint)
		}
	},
	Recurrence = new Microsoft.WindowsAzure.Scheduler.Models.JobRecurrence()
	{                    
		Frequency = (JobRecurrenceFrequency)request.JobRecurrence,                    
		Schedule = new Microsoft.WindowsAzure.Scheduler.Models.JobRecurrenceSchedule()
		{                        
			Days = new List() { Microsoft.WindowsAzure.Scheduler.Models.JobScheduleDay.Saturday }                        
		}
	},
	StartTime = request.StartTime                
};                        

var jobCreateResponse = client.Jobs.Create(jobCreateParams);
```

The last line throws the mentioned exception.  When I *remove* the JobRecurrenceSchedule parameter completely from my request, no exception is thrown.  However, in both cases, the job is successfully created in Azure.

I've followed the code in JobOperations.cs (CreateAsync method) and (unless I'm missing something) I don't believe the schedule collections are being initialized.  This would cause the null ref exception to be thrown when this line of code is executed as the Days collection would be null:

```
scheduleInstance.Days.Add(SchedulerClient.ParseJobScheduleDay(((string)weekDaysValue)));
```<p><a href="https://github.com/Azure/azure-sdk-for-net/issues/735">https://github.com/Azure/azure-sdk-for-net/issues/735</a></p>
<!---@tfsbridge:{"tfsId":2065910}-->

**Comment by markcowl** [comment] 2015-04-02 20:03
@jturinetti closing as the issue is resolved.  Please reopen if you see a recurrence

**Closed by markcowl** 2015-04-02 20:03 UTC
Labels: Scheduler
