### ISSUE TITLE
Legacy Storage: Error Code 407

### ISSUE THREAD

**Issue by srinivaspillalamarri** [Azure/azure-sdk-for-net#31390] opened 2022-09-23 09:01 UTC
Your documentation not covering error code 407, Why?

I'm getting following error while executing "`await blockBlob.UploadFromFileAsync(pFilePath);`" in my network, because my network configured with proxy.

**The proxy tunnel request to proxy '[http://ipaddress:port/' failed with status code '407'.**

But no where I saw the solution for it. Your HTTP Error Status code page also not shows 407 code. Why?
HttpClientHandler available for other HttpClient activities but nothing is available for CloudBlobClient why?

Complete code as following:

```
string blobstorageconnection = pConfig.AzuerBlobStorageConnectionString;
CloudStorageAccount cloudStorageAccount = CloudStorageAccount.Parse(blobstorageconnection);
CloudBlobClient? blobClient = null;
CloudBlockBlob? blockBlob = null;
blobClient = cloudStorageAccount.CreateCloudBlobClient();
CloudBlobContainer container = blobClient.GetContainerReference(pConfig.AzureStorageContainerName);
blockBlob = container.GetBlockBlobReference(pFileName);
await blockBlob.UploadFromFileAsync(pFilePath + @"\" + pFileName)
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 65f9c92f-459a-d316-9a17-096a44e02f5a
* Version Independent ID: eeaba0c8-8aba-e7ff-7555-a0a4fd00c4fc
* Content: [CloudStorageAccount Class (Microsoft.Azure.Storage) - Azure for .NET Developers](https://learn.microsoft.com/en-us/dotnet/api/microsoft.azure.storage.cloudstorageaccount?view=azure-dotnet)
* Content Source: [xml/Microsoft.Azure.Storage/CloudStorageAccount.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Storage/CloudStorageAccount.xml)
* Service: **storage**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by PramodValavala-MSFT** [comment] 2022-09-23 19:53
@srinivaspillalamarri [HTTP Error Code 407](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/407) is coming from your proxy rather than Azure Storage. Ensure you have the credentials set correctly for the proxy to work and try again.

**Comment by srinivaspillalamarri** [comment] 2022-09-24 07:15
> @srinivaspillalamarri [HTTP Error Code 407](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/407) is coming from your proxy rather than Azure Storage. Ensure you have the credentials set correctly for the proxy to work and try again.

**Please check my issue carefully.**
We use "**HttpClientHandler**" to configure the proxy settings for "**HttpClient**".
Similar kind of thing (**HttpClientHandler**) I want for "**CloudBlobClient**".

My issue not with Azure **my issue with proxy configuration** mechanism for "**CloudBlobClient**"

**Comment by PramodValavala-MSFT** [comment] 2022-09-26 21:16
@srinivaspillalamarri I believe there isn't a way to configure the underlying HTTP Client directly but for proxies, you could simply [set the required environment variable](https://learn.microsoft.com/en-us/dotnet/azure/sdk/azure-sdk-configure-proxy?tabs=cmd) for it work.

**Comment by srinivaspillalamarri** [comment] 2022-09-27 05:46
I already tried "set HTTPS_PROXY=http://username:password@10.10.1.10:1180" environment variable and there is no luck. Also tried **devenv config** setup but no luck in that too. That is the reason I posted this issue here.

Instead of these all work arounds why not you suggest me actually code like **"HttpClientHandler" to configure the proxy settings for "HttpClient"**. I can easily guess there should be a similar code for **CloudBlobClient**. If not, then there will be **big issue.............**

**Comment by amnguye** [comment] 2022-09-28 20:30
The Storage SDK version you're using is deprecated, please kindly upgrade to the latest version which is supported in this [repository ](https://www.nuget.org/packages/Azure.Storage.Blobs/12.13.1)

The deprecated version of the SDK you are using lives in this [repository](https://github.com/Azure/azure-storage-net).

The most similar issue and version of the SDK I can find to yours in regards to plugging in your own `HttpClientHandler` to set the `Proxy` is this github issue. 
https://github.com/Azure/azure-storage-net/issues/580
Looks like you have to pass your own `DelegatingHandler` to the client to get that done.
https://github.com/Azure/azure-storage-net/blob/master/Lib/Common/Blob/CloudBlobClient.Common.cs#L98
It will then grab the some form of the http client from here.

Apologies we can't help more due to the version being deprecated.

Closing github issue since the issue is regards to a deprecated SDK package.

**Comment by srinivaspillalamarri** [comment] 2022-09-29 05:25
**It is really ridiculous!** If you don't know something, then please **say NO!** but don't go around to escape from the issue. Current version of **Azure.Storage.Blob is 12.13.1** and I'm very well using it.

Simply I'm asking to handle the proxy setting!
How can I pass the proxy details (ip with credentials) in following code?

`string blobstorageconnection = pConfig.AzuerBlobStorageConnectionString;
CloudStorageAccount cloudStorageAccount = CloudStorageAccount.Parse(blobstorageconnection);
CloudBlobClient? blobClient = null;
CloudBlockBlob? blockBlob = null;
blobClient = cloudStorageAccount.CreateCloudBlobClient();
CloudBlobContainer container = blobClient.GetContainerReference(pConfig.AzureStorageContainerName);
blockBlob = container.GetBlockBlobReference(pFileName);
await blockBlob.UploadFromFileAsync(pFilePath + @"\" + pFileName)`

**No one able to answer to this simple question?
### Is that MS forgot to develop this?**

**Comment by amnguye** [comment] 2022-09-29 16:44
You're clearly using the v11 SDK, not the v12 SDK.

`CloudStorageAccount`, `CloudBlobClient` and any method that you call along with it (e.g. `GetContainerReference`, `GetBlockBlobReference`) belong to the v11 SDK, this well documented here.

https://learn.microsoft.com/en-us/dotnet/api/microsoft.azure.storage.blob.cloudblobclient?view=azure-dotnet-legacy
https://learn.microsoft.com/en-us/dotnet/api/microsoft.azure.storage.cloudstorageaccount?view=azure-dotnet

If you check these documentation pages they clearly say `Microsoft.Azure.Storage.Common v11.1.0` and `Microsoft.Azure.Storage.Blob v11.1.0`. Also `CloudStorageAccount`, `CloudBlobClient` do **not** exist in the v12 library. The v12 library has no APIs that have the word `Cloud` in it (e.g. we have `[BlobClient](https://learn.microsoft.com/en-us/dotnet/api/azure.storage.blobs.blobclient?view=azure-dotnet-preview)`, `[BlobBaseClient](https://learn.microsoft.com/en-us/dotnet/api/azure.storage.blobs.specialized.blobbaseclient?view=azure-dotnet-preview)`, and `CloudStorageAccount` no longer exists in the v12 library).

You even put your issue on a documentation page that clearly states the v11 namespace package of `CloudStorageAccount`
![image](https://user-images.githubusercontent.com/48961492/193087914-ba8c90a7-3b32-41ec-8771-958e054ee32c.png)

I would check over your code and dependencies if I were you.

On the proxy issue.

Clearly you haven't taken the time to look at the links I provided about using the `DelegatingHandler` when initializing the `CloudBlobClient` or else you can obviously see that you can pass the `HttpClientHandler` with the local `Proxy` you are looking for.

This documentation shows the CloudBlobClient [constructor ](https://learn.microsoft.com/en-us/dotnet/api/microsoft.azure.storage.blob.cloudblobclient?view=azure-dotnet-legacy#constructors)that accepts the `[DelegatingHandler](https://learn.microsoft.com/en-us/dotnet/api/system.net.http.delegatinghandler?view=net-6.0)`.

https://learn.microsoft.com/en-us/dotnet/api/microsoft.azure.storage.blob.cloudblobclient?view=azure-dotnet-legacy#constructors

If you actually googled the `DelegatingHandler` you can find that it inherits the `HttpMessageHandler`
So please attach a code sample with using the `DelegatingHandler` and how you intialized the `HttpClientHandler`.

This was linked in the github issue, I referenced in my last post, but since you missed it. This is our sample on how we initialized a `DelegatingHandler` and plugged in a `HttpClientHandler`.

https://github.com/Azure/azure-storage-net/blob/b0d47bfd4c1c0dcbe60eaf373e2977cd7405aa5f/Test/Common/TestBase.Common.cs#L251

You need to set your own proxy information in the `Proxy` property of the `HttpClientHandler`, (e.g. `HttpClientHandler handler = new HttpClientHandler(); handler.UseProxy = true;  handler.Proxy = new WebProxy("<proxy>", true);`)

Also I checked the solution to enable environment variables, which is the recommended way to enable proxy, because it allows the user to change the proxy information without changing the application. In the future case that the proxy information changes. The environment variable solution works, so I suggest that you check your environment variables again because `HttpClient` [defaults to using the environment variable information.](https://learn.microsoft.com/en-us/dotnet/api/system.net.http.httpclient?view=net-7.0#proxies)

We closed the issue cause clearly you're using the v11 SDK which is deprecated and this is the repository for the v12 library.

**Comment by srinivaspillalamarri** [comment] 2022-09-30 03:07
First of all, I'm using v12.13.1
You can check attached image for the same, which I captured from my project.

![image](https://user-images.githubusercontent.com/36758354/193177239-13ebc362-add7-489b-bded-8d4c411e89f5.png)

I want to say, your documentation is completely confusing this point.
From different versions I migrated my code and came to this stage.
Any only this one is working fine but same is not working with proxy.

https://learn.microsoft.com/en-us/dotnet/api/microsoft.azure.storage.blob.cloudblobclient?view=azure-dotnet-legacy
https://learn.microsoft.com/en-us/dotnet/api/microsoft.azure.storage.cloudstorageaccount?view=azure-dotnet

Above both the URLs are outdated in your case but for me those are working that one I got in my migrations.

Yes! I'm not replied to you on `DelegatingHandler`, I already tried that option too after that I started creation of issue.
That is the reason why not replied on it.

Coming to HttpClientHandler, I'm already using that in my case.

```

                HttpClientHandler clientHandler;

                if (_configuration.GetSection("ProxySettings:useProxy").Value == "1")
                {
                    string proxy = _configuration.GetSection("ProxySettings:proxy").Value;
                    string proxyUser = _configuration.GetSection("ProxySettings:proxyUser").Value;
                    string proxyPw = _configuration.GetSection("ProxySettings:proxyPw").Value;

                    WebProxy myProxy = new WebProxy(proxy, true) { Credentials = new NetworkCredential(proxyUser, proxyPw) };
                    if (myProxy.Address != null)
                    {
                        clientHandler = new HttpClientHandler()
                        {
                            Proxy = myProxy
                        };
                    }
                    else
                    {
                        clientHandler = new HttpClientHandler();
                    }
                }
                else
                {
                    clientHandler = new HttpClientHandler();
                }
                var client = new HttpClient(clientHandler);


```
Now check this URL, I followed this to migrate my code.

https://www.nuget.org/packages/WindowsAzure.Storage/9.3.3?_src=template
https://www.nuget.org/packages/Azure.Storage.Blobs/

![image](https://user-images.githubusercontent.com/36758354/193181493-c863fbba-211d-4efb-b4ed-ea63c7a7da02.png)


Again you roaming around HttpClient instead of focusing on BlobClient.
**Can you give any example on proxy with BlobClient?**
As I mentioned earlier, given example and document not supporting to me.

**Comment by amnguye** [comment] 2022-09-30 17:03
It doesn't look like you've fully migrated since you're still including the v9 SDK as a dependency

![image](https://user-images.githubusercontent.com/48961492/193320181-cab65630-bcf2-4728-9b6c-5cc40847a1e1.png)

Is there a reason why you have to hold on to the v9 SDK as a dependency? Have you not migrated the project fully?

Also again the v12 SDK deprecated the use of objects like `CloudBlobClient` and `CloudStorageAccount`, looking at your code snippet, it's only using objects from the v9 SDK. This can be easily confirmed if you remove the v12 SDK as a dependency and notice that your code will not have any syntax errors on the code snippet your provided.

e.g. this code snippet:
![image](https://user-images.githubusercontent.com/48961492/193320764-2867d30a-6e6c-40d9-83ec-e49e62be21d4.png)

**Comment by amnguye** [comment] 2022-09-30 17:34
Nevermind Jesse, I found it.

So here's a code snippet on how to do it in the v12
```
  var handler = new HttpClientHandler
  {
      DefaultProxyCredentials = CredentialCache.DefaultCredentials,
      Proxy = new WebProxy(new Uri("http://example.com"))
  };
  var options = new BlobClientOptions
  {
      Transport = new HttpClientTransport(handler)
  };
  BlobClient client = new BlobClient(
      new Uri("<storage account URL>"),
      options);
 ```
 
 So the code snippet I provided, you can change out `BlobClient` constructor authentication with any of the constructors in this documentation.
 https://learn.microsoft.com/en-us/dotnet/api/azure.storage.blobs.blobclient?view=azure-dotnet-preview
 
 All our Blob Clients in the v12 library take a `BlobClientOptions`, so if you decide to use `BlobContainerClient` instead you can still pass the same `BlobClientOptions`.

**Closed** 2022-11-01 08:04 UTC
Labels: Storage, Client, needs-author-feedback, customer-reported, question, no-recent-activity, CXP Attention
