### ISSUE TITLE
Internal processing error parsing response from Server

### ISSUE THREAD

**Issue by ArthurMa1978** [Azure/azure-sdk-for-net#46683] opened 2024-10-16 23:28 UTC
Webapp SDK internal processing error, this happens at Azure.ResourceManager.AppService.WebSiteResource.GetConnectionStringsAsync

sdk parse http response error

 

Error stack:

System.InvalidOperationException: The requested operation requires an element of type 'Object', but the target element has type 'Array'. at System.Text.Json.ThrowHelper.ThrowJsonElementWrongTypeException(JsonTokenType expectedType, JsonTokenType actualType) at Azure.ResourceManager.AppService.Models.ConnectionStringDictionary.DeserializeConnectionStringDictionary(JsonElement element) at Azure.ResourceManager.AppService.WebAppsRestOperations.ListConnectionStringsAsync(String subscriptionId, String resourceGroupName, String name, CancellationToken cancellationToken) at Azure.ResourceManager.AppService.WebSiteResource.GetConnectionStringsAsync(CancellationToken cancellationToken) 

 

SDK is  Azure.ResourceManager.AppService version 1.0.2

**Comment by HarveyLink** [comment] 2024-11-04 09:02
Cannot repro this issue with version 1.0.2 or latest main project. Please help to confim if this issue still exists.
Sample code and setting:
```
    var website = (await siteCollection.GetAsync("sdktest")).Value;
    var connectionString = (await website.GetConnectionStringsAsync()).Value;
    Console.WriteLine("Connection String" + connectionString.Properties.FirstOrDefault().Value.Value);
```
![Image](https://github.com/user-attachments/assets/48646967-e757-4642-bfcd-53bb382f256b)

**Comment by HarveyLink** [comment] 2024-11-07 09:15
Closed as not able to reproduce.

**Closed by HarveyLink** 2024-11-07 09:15 UTC
Labels: Mgmt

**Comment by wchigit** [comment] 2024-11-19 04:56
Run into same issue with Azure.ResourceManager.AppService version 1.0.2.

error message: Execution failed. The requested operation requires an element of type 'Object', but the target element has type 'Array'.. Exception: System.InvalidOperationException: The requested operation requires an element of type 'Object', but the target element has type 'Array'.
   at System.Text.Json.ThrowHelper.ThrowJsonElementWrongTypeException(JsonTokenType expectedType, JsonTokenType actualType)
   at Azure.ResourceManager.AppService.Models.ConnectionStringDictionary.DeserializeConnectionStringDictionary(JsonElement element)
   at Azure.ResourceManager.AppService.WebAppsRestOperations.ListConnectionStringsAsync(String subscriptionId, String resourceGroupName, String name, CancellationToken cancellationToken)
   at Azure.ResourceManager.AppService.WebSiteResource.GetConnectionStringsAsync(CancellationToken cancellationToken)
