### ISSUE TITLE
[QUERY] Can not run test project because ambiguous between Assert.That<TActual>(ActualValueDelegate<TActual>, IResolveConstraint)' and 'Assert.That<TActual>(TActual, IResolveConstraint)'

### ISSUE THREAD

**Issue by ibocon** [Azure/azure-sdk-for-net#24232] opened 2021-09-26 08:44 UTC
**Query/Question**
I can not run test project because of below ambiguous error.
> CS0121 The call is ambiguous between the following methods or properties: 'Assert.That<TActual>(ActualValueDelegate<TActual>, IResolveConstraint)' and 'Assert.That<TActual>(TActual, IResolveConstraint)'

![image](https://user-images.githubusercontent.com/9730869/134800404-652ce627-069e-411d-a530-9ba48bcfb5cd.png)

**Environment:**
 - Name and version of the Library package used: current main branch
![image](https://user-images.githubusercontent.com/9730869/134800494-5e7d75c2-0eb9-48bf-8626-848d3b81dd6f.png)

 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): 
![image](https://user-images.githubusercontent.com/9730869/134800528-6cf55241-7bbb-44a3-9c2b-e28d95e607b6.png)

- IDE
![image](https://user-images.githubusercontent.com/9730869/134800446-2c494388-81a0-42e2-8745-bc6404072d56.png)

**Comment by jsquire** [comment] 2021-09-27 12:25
Hi @ibocon.   Thank you for your feedback and we regret that you're experiencing difficulties.  It looks like you're hitting this issue using the .NET 6 SDK, which we're not officially supporting yet.    Would you be so kind as to see if this reproduces for you using the .NET SDK v5.0.301 or higher within the 5.0.* line, which is our [supported version](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md#prerequisites) at present?

**Comment by ibocon** [comment] 2021-09-27 14:24
Hi @jsquire. As you suggest it worked using .NET SDK v5.0.401. Thanks!

**Comment by jsquire** [comment] 2021-09-28 16:02
Glad to hear that resolved the issue in the short-term.   We'll be doing compatibility testing and adjusting our dependency versions at some point in the near future to support the .NET 6 SDK - the underlying cause for this will be investigated as part of those efforts if it persists.

Marking this as addressed but please feel free to use the "`/unresolve`" command if you'd like to discuss further.

**Closed** 2021-10-05 22:02 UTC
Labels: Client, EngSys, customer-reported, question, issue-addressed
