### ISSUE TITLE
[FEATURE REQ] ADF PipelineRunInvokedBy does not return parent PipelineRunId when the InvokedByType is PipelineActivity

### ISSUE THREAD

**Issue by tangdi** [Azure/azure-sdk-for-net#17655] opened 2020-12-21 05:56 UTC
**Library or service name.**
Azure.DataFactory 
**Is your feature request related to a problem? Please describe.**
I try to build a graph of pipeline runs. However, if a pipeline run is triggered by a parent pipeline run, it is hard to build this link using the SDK.
Using HTTP Rest API I can get the InvokedBy property like
   "invokedBy":{
      "id":"abc",
      "name":"abc",
      "invokedByType":"PipelineActivity",
      _"pipelineName":"Parent Pipeline Name",
      "pipelineRunId":"Parent pipeline run id"_
   },
However, the SDK does not include the parent pipelineRunId in the model.

**Potential solutions:**

- Add the explicit properties in the PipelineRunInvokedBy class and enrich the doc. 
- Add additional properties using JsonExtensionDataAttribute in the PipelineRunInvokedBy class and enrich the doc.

**Comment by jsquire** [comment] 2020-12-21 13:57
Thank you for your feedback.  Tagging and routing to the team best able to assist.  Please be aware that due to the holidays, responses may be delayed.

**Comment by shawnxzq** [comment] 2020-12-24 08:43
@LijuanZ Could you please help look into this issue? Thanks!

**Comment by tangdi** [comment] 2021-01-04 01:34
any feedback?

**Comment by LijuanZ** [comment] 2021-01-04 19:26
@shawnxzq @tangdi This is caused by the new properties (pipelineName and pipelineRunId) are not added to swagger spec yet. We've created a bug internally to track the fix.

**Comment by tangdi** [comment] 2021-01-28 02:18
any rollout to fix the Spec and SDK model?

**Comment by LijuanZ** [comment] 2021-02-01 22:52
@tangdi The bug is not fixed yet. I'll update here when it's done. While waiting for the fix, can you try use rest API as workaround? Sorry about the inconvenience.

**Comment by shawnxzq** [comment] 2021-03-05 15:48
@LijuanZ We can change the swagger now as it's unblocked, please help on this, thanks!

**Comment by LijuanZ** [comment] 2021-03-11 01:18
@shawnxzq yes, it's no longer blocked, we'll get to it based on priority

**Comment by shawnxzq** [comment] 2021-04-14 08:19
@LijuanZ Just a reminder, please share the status of the fix here, thanks!

**Comment by LijuanZ** [comment] 2021-05-18 23:20
@shawnxzq Thanks for the reminder, I'll update here when it's done.

**Comment by shawnxzq** [comment] 2021-06-29 03:14
@tangdi This is still being worked on, thanks for your patience on this.

**Comment by shawnxzq** [comment] 2021-08-05 03:20
@tangdi we are still working on this, and we will have a backlog item to track this, could you mind we can close the issue here? Thanks!

**Comment by shawnxzq** [comment] 2021-09-03 10:45
Still working one. 
@LijuanZ If we already created backlog items, let me know and we can close the issue here as well, otherwise we need to update the status here monthly, thanks!

**Comment by LijuanZ** [comment] 2021-09-03 18:14
@shawnxzq this work item is done, swagger change has been checked in for a while: https://github.com/Azure/azure-rest-api-specs/blob/master/specification/datafactory/resource-manager/Microsoft.DataFactory/stable/2018-06-01/datafactory.json#L5820

**Comment by shawnxzq** [comment] 2021-09-23 12:11
Close the issue now since swagger is checked in and it's already available rest API/SDK.

**Closed by shawnxzq** 2021-09-23 12:11 UTC
Labels: Data Factory, Service Attention, Client, customer-reported, question, needs-team-attention
