### ISSUE TITLE
Custom CheckpointManager for EventProcessorClient

### ISSUE THREAD

**Issue by lommez** [Azure/azure-sdk-for-net#13382] opened 2020-07-10 18:14 UTC
Why is not possibile anymore to create custom CheckpointManager for eventhub processors?
In older sdk versions that was possible.

Is there any workaround to not use Blob storage?

Or that feature is going to be implemented in the future?

**Comment by jsquire** [comment] 2020-07-10 20:17
Hi @lommez.   The functionality that you're looking for exists on the [`EventProcessor<TPartition>`](https://docs.microsoft.com/en-us/dotnet/api/azure.messaging.eventhubs.primitives.eventprocessor-1?view=azure-dotnet-preview&viewFallbackFrom=azure-dotnet) primitive. 

Generally speaking, `EventProcessorClient` was designed to provide a familiar API to that of the `EventHubConsumerClient` and offer an intuitive "step-up" experience for developers exploring Event Hubs as they move towards production scenarios.   For a large portion of our library users, that covers their needs well.   There's definitely a point, however, where your application requires more control to handle higher throughput or specialized needs that aren't shared by a large group - that's where the `EventProcessor<TPartition>` is intended to help.

The `EventProcessor<TPartition>` fills a similar role as the `EventProcessorClient`, but offers native batch processing, extension points utilizing different storage providers, more control over load balancing, and a lighter, less opinionated API.   The caveat is that this comes in the form of an abstract base, which needs to be extended and the core “handler” activities implemented via override.  More on the design and philosophy behind this can be found [[here]](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/eventhub/Azure.Messaging.EventHubs/design/event-processor%7BT%7D-proposal.md).

**Comment by lommez** [comment] 2020-07-13 12:12
Hi @jsquire 
Thanks so much for your detailed reply!

**Comment by jsquire** [comment] 2020-07-13 13:11
My pleasure.   If you decide to extend the `EventProcessor<TPartition>`,  we'd be very interested in your experience and feedback to help us refine any rough areas.   

I'm going to close this out, but please feel free to reopen if there was something further that you wanted to discuss in the context of this issue.

**Closed by jsquire** 2020-07-13 13:11 UTC
Labels: Client, Event Hubs, customer-reported, needs-team-attention, question
