### ISSUE TITLE
Parent class object nullifying child attributes in SDK function

### ISSUE THREAD

**Issue by pratimaupadhyay02** [Azure/azure-sdk-for-net#14535] opened 2020-08-25 06:06 UTC
**Describe the bug**

public async Task<AzureOperationResponse<VaultStorageConfigOperationResultResponse>> BeginGetWithHttpMessagesAsync

In the above function the parent class VaultStorageConfigOperationResultResponse is nullifying the child class(PrepareDataMoveResponse) attributes.
https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/recoveryservices-backup/Microsoft.Azure.Management.RecoveryServices.Backup/src/Generated/BMSPrepareDataMoveOperationResultOperations.cs

**Expected behavior**
 {"correlationId":"Mzg2NzU4MjUwOTY1Mjc1MTU5MztlMzgzMTI2Yi01ZjNmLTQyZmUtYTdjMC03NDA0MDk1NDgwNjM7UHVibGlj","sourceVaultProperties":null}

**Actual behavior (include Exception or Stack Trace)**
DEBUG: json:  {}
DEBUG: type: Microsoft.Azure.Management.RecoveryServices.Backup.Models.VaultStorageConfigOperationResultResponse

DEBUG: VaultStorageConfigOperationResultResponse

DEBUG:  {"correlationId":null,"sourceVaultProperties":null}
 
DEBUG: Caught exception, type: InvalidCastException

**To Reproduce**
Steps to reproduce the behavior (include a code snippet, screenshot, or any additional information that might help us reproduce the issue)

1. Clone the repo https://github.com/Azure/azure-powershell locally
2. Add reference of RecoveryServices-Backup 4.1.1 in https://github.com/Azure/azure-powershell/blob/master/src/RecoveryServices/RecoveryServices.Backup/RecoveryServices.Backup.csproj
3.  var prepareResponse = BmsAdapter.Client.BMSPrepareDataMoveOperationResult.BeginGetWithHttpMessagesAsync(
                                vaultName,
                                resourceGroupName,
                                operationId).Result.Body;
            
            var json = JsonConvert.SerializeObject(prepareResponse);
            Logger.Instance.WriteDebug("json:  " + json);
            Logger.Instance.WriteDebug("type: " + prepareResponse.GetType());

 

            if (prepareResponse is PrepareDataMoveResponse)
            {
                Logger.Instance.WriteDebug("PrepareDataMoveResponse");
            }
            if (prepareResponse is VaultStorageConfigOperationResultResponse)
            {
                Logger.Instance.WriteDebug("VaultStorageConfigOperationResultResponse");
            }

 

            PrepareDataMoveResponse derived = JsonConvert.DeserializeObject<PrepareDataMoveResponse>(json);
            Logger.Instance.WriteDebug(" " + JsonConvert.SerializeObject(derived));

 

            PrepareDataMoveResponse prepareDataMoveResponse = (PrepareDataMoveResponse)prepareResponse;
            Logger.Instance.WriteDebug("CorrelationId:  " + prepareDataMoveResponse.CorrelationId);
            return  derived;

**Environment:**
 - Name and version of the Library package used: [e.g.RecoveryServices-Backup 4.1.1] 
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): [e.g. Azure AppService or Windows 10 .NET Framework 4.8]
 - IDE and version : [e.g. Visual Studio 16.3]

**Comment by jsquire** [comment] 2020-08-25 13:18
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by m-nash** [comment] 2020-08-26 17:37
This is by design.

The way json deserialization works is if the json string has more parameters than the class it is being deserialized into the extra parameters will be discarded.

In this case the type VaultStorageConfigOperationResultResponse has zero properties so deserializing anything into that class will result in a loss of all data.

I am not sure if a pattern exists for this already, but I suppose we could return a type parameter in the json from the service and then have a switch statement based on that type to deserialize into the proper child class then still return it as the parent class.  In this case the user of the api could then recast it back to the child class and all data would be there.  This either already exists in autorest or would be a new feature request on autorest.

**Comment by jsquire** [comment] 2020-08-26 17:48
Looping in @pakrym for his expertise on AutoRest.

**Comment by pratimaupadhyay02** [comment] 2020-08-27 12:21
As discussed with @m-nash offline, we are already returning a parameter ObjectType from service which is used to deserialize into the proper child class.  We would expect a switch statement here in the autogenerated sdk code but its hardcoded to deserialize as the parent.

                try
                {
                    _result.Body = Rest.Serialization.SafeJsonConvert.DeserializeObject<VaultStorageConfigOperationResultResponse>(_responseContent, Client.DeserializationSettings);
                }

Somewhere between the swagger and the autorest code there is something missing that would generate the switch statement and deserialize the response to the proper child class.

@pakrym can you please help here to find whats missing.

**Comment by pakrym** [comment] 2020-08-27 16:44
Switch at that point is not required because polymorphic deserialization is handled by a converter that's registered in https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/recoveryservices-backup/Microsoft.Azure.Management.RecoveryServices.Backup/src/Generated/RecoveryServicesBackupClient.cs#L632

Currently checked in code is missing the following registration:
``` C#
 
            SerializationSettings.Converters.Add(new PolymorphicSerializeJsonConverter<VaultStorageConfigOperationResultResponse>("objectType"));
            DeserializationSettings.Converters.Add(new PolymorphicDeserializeJsonConverter<VaultStorageConfigOperationResultResponse>("objectType"));
```

Please re-generate the code and try again.

**Comment by pratimaupadhyay02** [comment] 2020-08-27 18:43
@pakrym I tried re-generating the code multiple times but somehow the above registration is not getting reflected in RecoveryServicesBackupClient. Is this some autorest related issue?

**Comment by allenjzhang** [comment] 2021-03-16 17:15
If you still have the issue, please advise back with the autorest version you used. BTW, I do see [PolymorphicSerializeJsonConverter](https://github.com/Azure/azure-sdk-for-net/blob/2b594335737a65cb8f36543ef817deaba5c43f4b/sdk/recoveryservices-siterecovery/Microsoft.Azure.Management.RecoveryServices.SiteRecovery/src/Generated/SiteRecoveryManagementClient.cs#L512) being generated in .NET SDKs. 

Closing this issue for now. Please feel free to reopen if you have additional information or follow-ups. Thanks!

**Closed by allenjzhang** 2021-03-16 17:15 UTC
Labels: AutoRest Runtime, Mgmt, customer-reported, needs-team-attention, question
