### ISSUE TITLE
[Azure Cognitive Search] [FEATURE REQ] Add DI helpers for Search library

### ISSUE THREAD

**Issue by brjohnstmsft** [Azure/azure-sdk-for-net#11514] opened 2020-04-22 22:07 UTC
Opening this on behalf of @xantari. See related issue: https://github.com/Azure-Samples/search-dotnet-getting-started/issues/43

**Library or service name.**
Azure.Search.Documents (new replacement for Microsoft.Azure.Search, a.k.a. Azure Cognitive Search).
 
**Is your feature request related to a problem? Please describe.**
The `Microsoft.Azure.Extensions` library provides handy extension methods for registering the blob storage clients. Why not the search clients?

@tg-msft @heaths @AlexGhiondea Is this something we're supporting for Track 2 libraries?

**Comment by heaths** [comment] 2020-04-23 00:02
Adding @pakrym who owns Extensions.

**Comment by tg-msft** [comment] 2020-04-23 00:22
Yes - this is a duplicate of https://github.com/Azure/azure-sdk-for-net/issues/10848.

**Closed by tg-msft** 2020-04-23 00:22 UTC
Labels: Client, Search, feature-request
