### ISSUE TITLE
Necessity of RunFilterParameters in Microsoft.Azure.Management.DataFactory.ActivityRunsOperationsExtensions.QueryByPipelineRun

### ISSUE THREAD

**Issue by shhafiz** [Azure/azure-sdk-for-net#18999] opened 2021-02-24 22:05 UTC
`public static ActivityRunsQueryResponse QueryByPipelineRun(this IActivityRunsOperations operations, string resourceGroupName, string factoryName, string runId, RunFilterParameters filterParameters);`

In the above signature, once we have a runId, shouldn't the filterParameters be redundant? As I understand, for a given resource, factory and runId, there will be exactly one response. The filterParameters don't seem to serve any purpose. In fact it can be a source of error when the parameter does not match the runId attributes.

**Comment by jsquire** [comment] 2021-02-24 22:41
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by nisha-bhatia** [comment] 2021-02-27 00:00
Thank you for your question, re-routing to a team member to assist.

**Comment by shawnxzq** [comment] 2021-03-04 00:15
@LijuanZ Please help on this, thanks!

**Comment by LijuanZ** [comment] 2021-03-11 01:26
@shhafiz @shawnxzq this is by design, note that it's to return ActivityRunsQueryResponse, this method is to list all activity runs for the provided pipeline run. The runId parameter is for pipeline run id, while the filterParameters is to provide further filters on activity runs. 1 pipeline run id is mapped to 1 pipeline run, but can contain multiple activity runs. Thanks!

**Comment by shawnxzq** [comment] 2021-03-12 17:36
@nisha-bhatia  Could you please help close this issue as I don't have permission? Thanks!

**Comment by shawnxzq** [comment] 2021-04-14 08:19
@nisha-bhatia @jsquire Please help close this, thanks!

**Closed** 2021-04-14 12:43 UTC
Labels: Data Factory, Mgmt, Service Attention, customer-reported, needs-team-attention, question
