### ISSUE TITLE
Consider an AppendBlobStream that takes an AppendBlobClient

### ISSUE THREAD

**Issue by tg-msft** [Azure/azure-sdk-for-net#8993] opened 2019-12-04 21:16 UTC
We should look into creating a higher level `AppendBlobStream` that takes an `AppendBlobClient` and periodically writes data using `AppendBlockClient.AppendBlock/Async`.  It would be helpful for users who just want to use `StreamWriter.WriteLine` and have that append blocks as needed without implementing all that logic themselves.

Customers could [previously use CloudBlobStream](https://github.com/Azure/azure-sdk-for-net/issues/8942) for this in v11.

**Comment by ab-cognassist** [comment] 2020-02-14 16:45
Hi,  Do we know when this will be release, Thanks

**Comment by tg-msft** [comment] 2020-02-18 16:14
There's no concrete plan for this work yet, but we'll update the issue if and when that happens.

**Comment by willdean** [comment] 2020-03-18 10:53
Can I put in a +1 for this, please.  We have a an application which adds groups of lines to an append block via a streamwriter, fed with data coming from a network stream.  It's a significant bit of work to try move this to the V12 api because one can't get a writeable stream.

**Comment by ab-cognassist** [comment] 2020-03-18 10:59
+1, we can't move to V12 (Azure.Storage.Blobs) and are still using V11 (Microsoft.Azure.Storage.Blob) as there isn't a relevant endpoint for us to use.

**Comment by seanmcc-msft** [comment] 2020-07-16 19:12
Duplicate of https://github.com/Azure/azure-sdk-for-net/issues/9607

**Closed by seanmcc-msft** 2020-07-16 19:12 UTC
Labels: Client, Storage
