### ISSUE TITLE
[QUERY] MapsSearchClient.SearchAddressAsync disappeared in V2 

### ISSUE THREAD

**Issue by MoeHamdan** [Azure/azure-sdk-for-net#45796] opened 2024-09-04 14:14 UTC
### Library name and version

Azure.Maps.Search 2.0.0-beta.2

### Query/Question

Where did MapsSearchClient.SearchAddressAsync go? I see the whole list of methods has been replace in the version 2.0.0. I need the search address and the fuzzy search functionalities, where I can find them in the new version?

**Comment by tuukkapuranen** [comment] 2024-10-17 12:46
I can see that the API version 1.0 [has these features](https://learn.microsoft.com/en-us/rest/api/maps/search/get-search-address-structured?view=rest-maps-1.0&tabs=HTTP), but starting from API version 2022-08-01, [the features are no longer present](https://learn.microsoft.com/en-us/rest/api/maps/search?view=rest-maps-2024-04-01). The [changelog](https://github.com/Azure/azure-sdk-for-net/blob/Azure.Maps.Search_2.0.0-beta.4/sdk/maps/Azure.Maps.Search/CHANGELOG.md) for the search API SDK 2.0.0-beta.1 states that 

> Support Search API 2023-06-01

but there is no mention of removing support for API 1.0.

Could someone clarify this? Has the API 1.0 support been removed from the SDK and is this a permanent state? What is the plan for supporting for example structured queries in the future, or are these REST APIs in the process of being deprecated?

**Comment by DevronTLA** [comment] 2024-10-17 22:10
I would also like to undersand this as I was looking to use fuzzy address search and confused as to why it's not there now

**Comment by dubiety** [comment] 2024-11-28 16:53
Hi @MoeHamdan , @tuukkapuranen  and @DevronTLA ,

Sorry for the late reply. Starting from Search API version 2023-06-01, we simplify our APIs. Actually, our new [Get Geocoding](https://learn.microsoft.com/en-us/rest/api/maps/search/get-geocoding?view=rest-maps-2024-04-01&tabs=HTTP) API can support both structured and unstructured search. 

Our v2.0.0 REST SDK only support API version 2023-06-01 or later version, while our v1.0.x REST SDK supports v1.0 REST API. `SearchAddress` will be replaced with `GetGeocoding` (same as `Async` methods) in the future. If you still want to use `SearchAddress` methods, you need to stick in v1.0.x, but our v1 SDK will not be maintained further. It's also in our roadmap to support more APIs like POI search. I'll also update our changelog to avoid misunderstanding. Sorry about the confusion.

**Comment by DevronTLA** [comment] 2024-12-02 03:55
It seems like in the simplification of API version 2023-06-01 that there is a lot of feature regression. For example, we use the Fuzzy Search to both correct user entered addresses with ranked results, and to get the all 'clean' address details back, including geocoding. The new API's don't seem to have any fuzzy search equivalent? Is the intention to improve/expand over time for feature parity?

**Comment by dubiety** [comment] 2024-12-05 02:39
The fuzzy search API is in our roadmap, it's under development, but there's no ETA for now. If you still need fuzzy search, please stick on V1 SDK for now. Thank you very much.

**Comment by dubiety** [comment] 2024-12-06 02:52
Close the issue since no further action item for now.

**Closed by dubiety** 2024-12-06 02:52 UTC
Labels: Client, customer-reported, question, needs-team-attention, Maps
