### ISSUE TITLE
[FEATURE REQ] Service Bus - Scoped renew token

### ISSUE THREAD

**Issue by shlomiassaf** [Azure/azure-sdk-for-net#29752] opened 2022-07-10 08:57 UTC
### Library name

Azure.Messaging.ServiceBus

### Please describe the feature.

Similar to `ServiceBusProcessorOptions.MaxAutoLockRenewalDuration`, we've developed an internal implementaiton for a scoped auto renew policy which uses `IAsyncDisposable` as the trigger to stop renewing the token.

While `MaxAutoLockRenewalDuration` will keep calling renew until the defined period ends (or the message handling ends), the scoped implementation will keep doing it until disposed or until the message handling ends.

It's very easy to implement as the implementation of both is almost identical.
Of course, if `MaxAutoLockRenewalDuration` is enabled (> 0) the user can't activate the scope.

This is very helpful for long running operations where the time it takes to finish is unknown.

I can create a PR if this feature looks reasonable for you.

The end user experience is something like this:

```c#
if (eventArgs.CanCreateRenewMessageLockScope())
{
    await using var _ = eventArgs.WithRenewMessageLockScope();
    // Do something long
}
```
Thanks!

**Comment by jsquire** [comment] 2022-07-11 12:41
Hi @shlomiassaf.   Thank you for your feedback.  I'd like to understand more about your scenario, if you're willing to share - specifically how the duration causes friction for your application.

My concern with the proposed scope pattern is that it can lead to unexpected behavior, very long delays, and potential data loss.  The intent of having a time limit is to guard against those scenarios.  For example, consider the following:

```csharp
if (eventArgs.CanCreateRenewMessageLockScope())
{
    await using var _ = eventArgs.WithRenewMessageLockScope();
    
    // This method is invoked without a timeout or cancellation awareness; there's a bug where it deadlocks and can never
    // make forward progress, so the call will never complete.
    await _service.DoSomethingWithMessage(message);
}
```

In the above, the message is locked indefinitely, until someone takes notice that this application instance is not making forward progress and terminates it.   In the extreme case, the message may be locked for longer than the retention period.  By the time the lock is released, the message is no longer available to be read and has been lost.

There are also less extreme cases where behavior would be potentially confusing.  For example, lock renewal takes place over a specific AMQP link that is different from the one where the message was received.   However, a message can only be completed on the AMQP link it was received from.  Every ~30 minutes, the service will force a reconnect (including new link).   As a result, locking the message for longer than that duration would create a scenario where the message has been processed, but cannot be completed.

**Comment by shlomiassaf** [comment] 2022-07-12 11:47
Thank you for the detailed response.

I was not familiar with the client AMQP link issue and did not think about the retention problem.

My assumptions were taken after readings the source code.
The issues above can occur in the current implementation, just by providing a big enough time for the auto renew property.

I did not see any protection, is this possible ?

**Comment by jsquire** [comment] 2022-07-15 15:07
> The issues above can occur in the current implementation, just by providing a big enough time for the auto renew property.

This is true; the fundamental challenge is that the service behavior is undocumented and could change.  The Azure SDK guidelines require that we delegate validation to the service which does not currently enforce that lock tokens being renewed are valid.  That said, I do intend to have a follow-up conversation around the client validating in this case due to the potential for unclear failure.

The main difference between an arbitrarily long renew time and the scope is expression of intent.  In the 80% case for renew times, default values are used.  It takes an explicit action to opt-into longer times and, hopefully, encourages consideration when selecting a value.  If a developer chooses to set a long renew time, it's a conscious choice expressing a clear intent.   

The scope is more convenient but comes with a greater potential to hide an issue where there's a stall or delay - which is unlikely to be clear.  The manifestation in most cases would potentially appear as a performance issue, which often starts with the question "why is Service Bus so slow in delivering messages."   Here, again, it's fair to say that this can also be an issue with a long renew time - but the intent of "I expect my code may take XX long to complete" is clear from the timeout specified.

> Side-note, about the call being deadlocked, that might happen, in any scenario, it's the developer's role here to take action.

This is also true.  However, I'm wary of offering an official pattern that can obscure this further and potentially introduce perceived (or real) data-loss.

> Now, if a process is deadlocked, would we want to process the message in a different machine/thread? When the token expire it will eventually end up being fired again.

From the client perspective, unequivocally yes.  The underlying guarantee of all of the Azure Messaging services is at-least-once delivery.  The client will always favor possible duplication over loss in every potential trade-off.

**Comment by JoshLove-msft** [comment] 2022-07-15 16:18
@shlomiassaf, can you explain why you would use this scoped token vs just setting the MaxAutoLockRenewalDuration to some extremely high value? If you are confident that your code will never just hang indefinitely, doing this will ensure that the lock renewal keeps happening while your callback is processing. Once your callback returns, the lock renewal will stop.

**Comment by jsquire** [comment] 2022-07-15 18:06
Josh has just kindly informed me that my understanding of the 30-minute connection refresh is incorrect; it applies to the other messaging services but not Service Bus.  So long as the lock is being actively renewed before the idle timeout, Service Bus will keep the link alive.

Apologies for the misinformation.

**Comment by shlomiassaf** [comment] 2022-07-18 02:28
@jsquire @JoshLove-msft 
Thank you for the detailed response.

It good news that the 30 minute limitation is not an issue, I was not aware of that and good thing it not really a "thing".

Now, I really understand the additional consideration that you must take as library authors and the API the has to be meticulously built to express intent and lead the way for users.

My issue with long auto renewal times is that while it does express intent, in a way, it is usually not bound to the code handling it. Setup is usually separate from usage where we define at startup but handle through DI somewhere in business code.

I believe a scope delivers intent more accurately. It explicitly defines the operation I need to do and the boundaries I need the token to live within.

Setting a time span which is big enough feels more like an abuse to me rather then setting an intent.

I do understand the issues it might raise with the majority of the users who might implement it with bugs that are later blamed on the library.

It's actually your call here I guess.

We can live with outlet internal implementation, no harm done.

Perhaps you can implements an auto renew extension request, since now it's not something possible in a clean way.
That is, for a specific message, and api call that will allow to extend the renew token with another call that will provide info on when it ends (since the auto renew value is absolute)

**Comment by JoshLove-msft** [comment] 2022-08-05 02:38
Thanks for the suggestion @shlomiassaf. I think we will probably wait for more feedback on this feature before we consider adding it to the library. I will move this to our backlog for now.

**Comment by jsquire** [comment] 2023-07-24 19:50
After further discussion, there does not seem to be enough developer interest in this feature to move forward at present.   We'll continue to monitor incoming feedback and are happy to reconsider if we see a large amount of developer interest.   For now, I'm going to close this out.

**Closed by jsquire** 2023-07-24 19:50 UTC
Labels: Service Bus, Client, customer-reported, feature-request
