### ISSUE TITLE
[BUG] ResourceManager.Network triggers an API version error

### ISSUE THREAD

**Issue by musicislife08** [Azure/azure-sdk-for-net#33898] opened 2023-02-04 15:55 UTC
### Library name and version

Azure.ResourceManager.Network 1.1.0

### Describe the bug

When editing a "WebApplicationFirewallPolicyResource" to add a new custom rule I am getting "ApplicationGatewayFirewallEnabledOverrideStateCannotBeConfiguredForApiVersion": "Specified api-version 2021-02-01 does not meet the minimum required api-version 2022-05-01 to have 'Enabled' override state in context {Resource Path Here}"

Perhaps i'm not doing something correctly but I dont see a way to change the api version for this call.  Here is the code block throwing the error

```csharp
private async Task UpdateCustomRule(WebApplicationFirewallPolicyResource waf, IEnumerable<string> googleIps)
    {
        // Create new rule
        var rule = new WebApplicationFirewallCustomRule(10, WebApplicationFirewallRuleType.MatchRule, new List<MatchCondition>()
            {
                new(new List<MatchVariable>(){new("RemoteAddr")}, WebApplicationFirewallOperator.IPMatch, googleIps)
            },
            WebApplicationFirewallAction.Allow);
        // Get the old rule
        var ruleToRemove = waf.Data.CustomRules.Single(x => x.Name == _config.GoogleBotCustomRuleName);
        // Remove the old rule from the list
        waf.Data.CustomRules.Remove(ruleToRemove);
        // Add the new rule to the list
        waf.Data.CustomRules.Add(rule);
        // Update the policy with the new rule
        var result= await waf.UpdateAsync(WaitUntil.Completed, waf.Data);
    }
    
```

### Expected behavior

Expected the api call to update the waf

### Actual behavior

Returns the following error

im not doing anything other than updating the custom rules in the data block.  

```json
Specified api-version 2021-02-01 does not meet the minimum required api-version 2022-05-01 to have 'Enabled' override state in context /subscriptions/{SubscriptionId}/resourceGroups/{ResourceGroupName}/providers/Microsoft.Network/ApplicationGatewayWebApplicationFirewallPolicies/{PolicyName}.
Status: 400 (Bad Request)
ErrorCode: ApplicationGatewayFirewallEnabledOverrideStateCannotBeConfiguredForApiVersion

Content:
{
  "error": {
    "code": "ApplicationGatewayFirewallEnabledOverrideStateCannotBeConfiguredForApiVersion",
    "message": "Specified api-version 2021-02-01 does not meet the minimum required api-version 2022-05-01 to have 'Enabled' override state in context /subscriptions/{SubscriptionId}/resourceGroups/{ResourceGroupName}/providers/Microsoft.Network/ApplicationGatewayWebApplicationFirewallPolicies/{PolicyName}.",
    "details": []
  }
}

Headers:
Cache-Control: no-cache
Pragma: no-cache
x-ms-request-id: REDACTED
x-ms-client-request-id: REDACTED
x-ms-correlation-request-id: REDACTED
x-ms-arm-service-request-id: REDACTED
Strict-Transport-Security: REDACTED
Server: Microsoft-HTTPAPI/2.0,Microsoft-HTTPAPI/2.0
x-ms-ratelimit-remaining-subscription-writes: REDACTED
x-ms-routing-request-id: REDACTED
X-Content-Type-Options: REDACTED
Date: Sat, 04 Feb 2023 15:37:57 GMT
Content-Length: 485
Content-Type: application/json; charset=utf-8
Expires: -1
```

### Reproduction Steps

use the below code to take in a waf policy resource and update the custom rules

```csharp
private async Task UpdateCustomRule(WebApplicationFirewallPolicyResource waf, IEnumerable<string> googleIps)
    {
        // Create new rule
        var rule = new WebApplicationFirewallCustomRule(10, WebApplicationFirewallRuleType.MatchRule, new List<MatchCondition>()
            {
                new(new List<MatchVariable>(){new("RemoteAddr")}, WebApplicationFirewallOperator.IPMatch, googleIps)
            },
            WebApplicationFirewallAction.Allow);
        // Get the old rule
        var ruleToRemove = waf.Data.CustomRules.Single(x => x.Name == _config.GoogleBotCustomRuleName);
        // Remove the old rule from the list
        waf.Data.CustomRules.Remove(ruleToRemove);
        // Add the new rule to the list
        waf.Data.CustomRules.Add(rule);
        // Update the policy with the new rule
        var result= await waf.UpdateAsync(WaitUntil.Completed, waf.Data);
    }
```

### Environment

.NET SDK:
 Version:   7.0.102
 Commit:    4bbdd14480

Runtime Environment:
 OS Name:     pop
 OS Version:  22.04
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /usr/share/dotnet/sdk/7.0.102/

Host:
  Version:      7.0.2
  Architecture: x64
  Commit:       d037e070eb

.NET SDKs installed:
  6.0.405 [/usr/share/dotnet/sdk]
  7.0.102 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 7.0.2 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 7.0.2 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

IDE: JetBrains Rider 2023.1 EAP 2

**Comment by jsquire** [comment] 2023-02-04 18:30
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by fengzhou-msft** [comment] 2023-02-06 02:19
@musicislife08 please try to add below options to `ArmClient` to override the API version:
``` C#
ArmClientOptions clientOptions = new();
clientOptions.SetApiVersion(new ResourceType("Microsoft.Network/ApplicationGatewayWebApplicationFirewallPolicies"), "2022-05-01");
```

**Comment by musicislife08** [comment] 2023-02-06 05:53
That worked.  I looked all over trying to see if there was a way to override the api version.  Is there any documentation on this feature?

**Comment by fengzhou-msft** [comment] 2023-02-06 06:21
I don't see one. @xboxeer our PM for awareness on doc improvement.

**Comment by fengzhou-msft** [comment] 2023-02-06 08:34
Close as the original problem was caused by service side check and is resolved with workaround on client side.

**Closed by fengzhou-msft** 2023-02-06 08:34 UTC
Labels: Network, Mgmt, customer-reported, question, needs-team-attention
