### ISSUE TITLE
[BUG] BlobContainerClient.CreateIfNotExistsAsync() returns null

### ISSUE THREAD

**Issue by elraikhm** [Azure/azure-sdk-for-net#17710] opened 2020-12-28 20:08 UTC
**Describe the bug**
Customer reported bug from HaTS survey
"Some very obvious issues that need to be fixed. For example, in the Blob Storage SDK, BlobContainerClient.CreateIfNotExistsAsync() returns null if the container already exists, causing a null reference exception if the result is assigned to a variable (Response is not null friendly). This somewhat defeats the purpose of the function."

**Expected behavior**
What is the expected behavior?

**Actual behavior (include Exception or Stack Trace)**
What is the actual behavior?

**To Reproduce**
Steps to reproduce the behavior (include a code snippet, screenshot, or any additional information that might help us reproduce the issue)

1.
2.

**Environment:**
 - Name and version of the Library package used: [e.g. Azure.Storage.Blobs 12.2.0] 
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): [e.g. Azure AppService or Windows 10 .NET Framework 4.8]
 - IDE and version : [e.g. Visual Studio 16.3]

**Comment by AlexGhiondea** [comment] 2020-12-28 21:24
I am able to reproduce this. It looks like the `CreateIfNotExistsInternal` will return a null object from the catch clause when the container already exists. /cc @tg-msft

**Comment by amnguye** [comment] 2021-01-06 23:44
This is a duplicate issue to this [one](https://github.com/Azure/azure-sdk-for-net/issues/9758). @tg-msft already discussed what it would take to resolve this issue which would contain a breaking change. We have some workaround for the customers that they can see in the issue I linked.

Closing this issue in preference to the already opened issue.

**Closed by amnguye** 2021-01-06 23:44 UTC
Labels: Client, Service Attention, Storage, needs-team-attention
