### ISSUE TITLE
ClientModel: Enable support for multipart/form-data content type end to end.

### ISSUE THREAD

**Issue by pallavit** [Azure/azure-sdk-for-net#42105] opened 2024-02-21 18:04 UTC
1. Cost to support it in our toolchain.
2. Exact understanding of what goes in System.ClientModel
3. What is needed on the generator side to make that happen.

**Comment by jsquire** [comment] 2024-04-29 14:45
Duplicate of #42674

**Closed by jsquire** 2024-04-29 14:45 UTC
Labels: Client, Azure.Core, OpenAI, System.ClientModel
