### ISSUE TITLE
Can't use ApplicationTokenProvider in KeyVaultClient

### ISSUE THREAD

**Issue by natelaff** [Azure/azure-sdk-for-net#9962] opened 2020-02-14 00:45 UTC
The following code does not work with KeyVaultClient. It always returns unauthorized.
    
```
var serviceCreds = await ApplicationTokenProvider.LoginSilentAsync(tenantId, clientId, clientSecret);
var keyVaultClient = new KeyVaultClient(serviceCreds);
```

Instead you have to use something like...

```
async Task<string> GetToken(string authority, string resource, string scope)
{
    var authContext = new AuthenticationContext(authority);
    ClientCredential clientCred = new ClientCredential(clientId, clientSecret);
    AuthenticationResult result = await authContext.AcquireTokenAsync(resource, clientCred);

    if (result == null)
        throw new InvalidOperationException("Failed to obtain the JWT token");
    return result.AccessToken;
}

var keyVaultClient = new KeyVaultClient(new KeyVaultClient.AuthenticationCallback(GetToken));
```

Why doesn't ApplicationTokenProvider work for KeyVaultClient? This pattern works for all my other clients such as SqlManagementClient, DnsManagementClient and StorageManagementClient.

All permissions for this client are set properly (the callback method works fine).

**Comment by jsquire** [comment] 2020-02-14 14:22
//cc: @heaths

**Comment by heaths** [comment] 2020-02-14 16:18
Key Vault used a different authentication scene for the service, necessitating the other code like you showed.

However, our newer Azure.Security.KeyVault.* packages - and the rest of the Azure.* packages - support much simpler authentication: just pass a new Azure.Identity.DefaultAzureCredential. These libraries are also faster and allocate less memory. The older packages will be getting critical fixes only, while active development continues on the newer ones. We recommend upgrading for a better experience.

**Comment by heaths** [comment] 2020-02-14 16:19
Closing as by design. The code sample you posted is required to authenticate to Key Vault.

**Closed by heaths** 2020-02-14 16:19 UTC
Labels: Client, KeyVault, Question, customer-reported
