### ISSUE TITLE
[QUERY] How to test local app using 'DefaultAzureCredential' to call a custom API?

### ISSUE THREAD

**Issue by julealgon** [Azure/azure-sdk-for-net#28563] opened 2022-05-05 21:08 UTC
### Library name and version

Azure.Identity 1.5.0

### Query/Question

I have a durable function that performs an authenticated `DELETE` call using `DurableHttpRequest` to a protected API hosted in AppServices. I'm getting a 403 response in the cloud environment even after I've already added the required app-role to the function's system-assigned managed identity using Powershell.

When trying to run this same function locally, I get a failure message during the token retrieval phase stating that I need to give consent for Visual Studio to access my application:

> Error, TS004: Unable to get access token. 'AADSTS65001: The user or administrator has not consented to use the application with ID '872cd9fa-d31f-45e0-9eab-6e460a02d1f1' named 'Visual Studio'. Send an interactive authorization request for this user and resource.

I tried manually calling the admin consent URL with this API and my resource:
`https://login.microsoftonline.com/{my_tenant_id}/adminconsent?client_id=872cd9fa-d31f-45e0-9eab-6e460a02d1f1&scope=api://{my_api_id}/.default`

This results in a dialog asking me if I'm trying to sign in to Visual Studio:
![image](https://user-images.githubusercontent.com/461579/167022521-aecc486c-7289-45d9-b349-21677d3cc38c.png)

Clicking on continue results in a redirection to `https://login.microsoftonline.com/appverify?...` with a blank page.

If I then try again to call my API while debugging the durable function, the exact same error occurs.

After investigating what the code in the durable functions extensions does, I created a sample console application that reproduces the exact same issue with just a few lines of code:
```csharp
using Azure.Core;
using Azure.Identity;

Console.WriteLine("Hello, World!");

const string myApiClientId = ....
var credential = new DefaultAzureCredential();
var context = new TokenRequestContext(scopes: new[] { $"api://{myApiClientId}/.default" });
var result = await credential.GetTokenAsync(context);
```
Using this code, I get the exact same error as what happens inside the function app locally. I made sure to add `Azure.Identity` v1.5.0 which is the same version being used by my function app through `Microsoft.Azure.WebJobs.Extensions.DurableTask` v2.7.0.

I feel like I'm missing something fundamental here, but every sample I find of Durable Functions calling into protected APIs using `DurableHttpRequest` are calling other Azure APIs, like management, instead of calling a custom one. I _assume_ Visual Studio has built-in permissions for those (or something?).

I also don't quite understand why I can't find any hint of a "Visual Studio" app registration in the portal anywhere: if I search either by text or by the ID `872cd9fa-d31f-45e0-9eab-6e460a02d1f1`, nothing comes up.

Could someone help me in how to get this working from local debugging? Is it even possible? Do I need to "give permissions to Visual Studio to access my API?" If so, how do I even do that considering I can't even find the "Visual Studio" app anywhere?

I also considered making a manual authorize/token call while "impersonating" the function's managed identity to double/triple check the token being returned, but I don't know how to do that either... I'm sure the token has _something_ in it, since prior to giving the function permissions, I got an exception in the API due to "lack of scopes and roles" in the JWT: now this has changed to a 403 which signals that "there should be a role in there" but it is somehow wrong. Durable functions itself doesn't persist the token used anywhere (which I imagine is done on purpose for security reasons) but then I can't also inspect the token from there. Similarly, logs in Application Insights for AspNetCore don't include any headers so I can see the token that is arriving in the API...

I've spend several hours trying to make this work today and I feel I haven't progressed much if at all 😢 Any help will be hugely appreciated.

### Environment

AppService, Windows 10, NET6
Visual Studio 17.1.4

**Comment by jsquire** [comment] 2022-05-05 22:46
//cc: @christothes

**Comment by jsquire** [comment] 2022-05-05 22:46
Thank you for your feedback.  Tagging and routing to the team members best able to assist.

**Comment by christothes** [comment] 2022-10-21 17:39
Hi @julealgon Does this issue still reproduce for you? If so, does it also reproduce when you use a different credential such as `AzureCliCredential`?

**Comment by julealgon** [comment] 2022-10-21 18:17
> Hi @julealgon Does this issue still reproduce for you? If so, does it also reproduce when you use a different credential such as `AzureCliCredential`?

I still get the exact same error as before @christothes , tested just now:

![image](https://user-images.githubusercontent.com/461579/197261893-b94140c0-3b1a-448d-8aeb-5e8e73bc20da.png)

> Process "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\CommonExtensions\Microsoft\Asal\TokenService\Microsoft.Asal.TokenService.exe" has failed with unexpected error: TS003: Error, TS004: Unable to get access token.  'AADSTS65001: The user or administrator has not consented to use the application with ID '04f0c124-f2bc-4f59-8241-bf6df9866bbd' named 'VS with native MSA'. Send an interactive authorization request for this user and resource.

I did notice however that even though the exception is the same, the clientID (and app name) for VS has now changed:
| | Previous | Current |
| -- | -- | -- |
| Name | Visual Studio | VS with native MSA |
| ClientId | 872cd9fa-d31f-45e0-9eab-6e460a02d1f1 | 04f0c124-f2bc-4f59-8241-bf6df9866bbd |

Do you want me to update any library and then try again? I'm now using VS 17.3.6

**Comment by christothes** [comment] 2022-10-21 19:13
Thanks for validating - could you also confirm whether or not the issue is isolated to the `VisualStudioCredential`? Could you try AzureCliCredential (which uses a different application Id to authenticate).

**Comment by schaabs** [comment] 2022-10-21 20:54
@julealgon As you noticed VS is moving to a new app id in their latest preview builds. Since VS is a first party app (developed by Microsoft), consent to Azure resources is handled via an internal pre-consent process. Most likely the issue you're running into here is the new application has not been pre-consented with the resource you are trying to access. Can you let us know what resource you're attempting to access, so we can ensure the new VS application has been properly pre-consented?

**Comment by julealgon** [comment] 2022-10-21 22:23
> Thanks for validating - could you also confirm whether or not the issue is isolated to the `VisualStudioCredential`? Could you try `AzureCliCredential` (which uses a different application Id to authenticate).

I'm actually not using `VisualStudioCredential` directly. This error comes from the fallback in `DefaultAzureCredential`, which is created automatically as part of the `ManagedIdentityTokenSource` I'm using to make a durable HTTP call. In this context, I don't even have the option to use my own credential value.

Though I _could_ change the credential in my repro sample, it would then not be representative of what is actually happening in the durable function anymore.

Do let me know if you still want me to perform that test, however.

**Comment by julealgon** [comment] 2022-11-25 16:58
@christothes 

Now that .NET7 is out, I'm giving a try to converting my durable function to isolated mode. Currently, durable tasks in the isolated mode don't support DurableHttp calls like the one I was using, so I now had to create my own activity function to make the HTTP request.

In doing so, I'm able to control exactly which credential I want to use.

After trying `AzureCliCredential`, this is what I'm getting:

![image](https://user-images.githubusercontent.com/461579/204028881-0c990794-f894-4c34-a55e-fafa1e32dff3.png)

> "Please run 'az login' to set up account"

I've attempted to run `az login` multiple times, both in a local console as well as from inside the terminal in Visual Studio, but nothing changes. The call works just fine, it redirects me to the browser, I pick my Azure account there, and then I am back on the console and can see all my subscriptions.

I also figured this could be related to running VS as admin, but after changing it back to run as local user, I still see the same error all the time.

I feel like I might be missing something obvious here, can you provide guidance? The only thread related to this that I found suggests setting the default subscription, and explicitly logging off first, which I did try to no effect:
- https://stackoverflow.com/a/70180991/1946412

**Comment by julealgon** [comment] 2022-11-25 17:24
After searching a bit more, found this issue here which appears relevant to me:
- https://github.com/Azure/azure-sdk-for-net/issues/26894

After testing with the following command:
`az login --scope api://{my_cliendId}/.default`

I get the following error page:

> Authentication failed
> invalid_client: AADSTS650057: Invalid resource. The client has requested access to a resource which is not listed in the requested permissions in the client's application registration. Client app ID: 04b07795-8ddb-461a-bbee-02f9e1bf7b46(Microsoft Azure CLI). Resource value from request: api://{my_cliendId}. Resource app ID: {my_cliendId}. List of valid resources from app registration: . Trace ID: 98ac8c3b-37ca-4fe9-944a-988bd10d6d01 Correlation ID: 6e3f16da-68a9-4918-bd28-eee6f18d0d85 Timestamp: 2022-11-25 17:20:24Z. ($error_uri)

>
> You can log an issue at [Azure CLI GitHub Repository](https://github.com/azure/azure-cli/issues) and we will assist you in resolving it.

This is not making much sense to me to be honest. If I try to manually add the permissions in the Azure portal inside my App Registration, these records for "Microsoft Azure CLI" do not exist anywhere there.

**Comment by kacperwojtyniak** [comment] 2022-12-14 13:52
I have run against the same issues. I am trying to get a token for my custom App Registration and receive the following error:

```
Azure.Identity.CredentialUnavailableException : DefaultAzureCredential failed to retrieve a token from the included credentials. See the troubleshooting guide for more information. https://aka.ms/azsdk/net/identity/defaultazurecredential/troubleshoot
- EnvironmentCredential authentication unavailable. Environment variables are not fully configured. See the troubleshooting guide for more information. https://aka.ms/azsdk/net/identity/environmentcredential/troubleshoot
- ManagedIdentityCredential authentication unavailable. Multiple attempts failed to obtain a token from the managed identity endpoint.
- Process "C:\Program Files\Microsoft Visual Studio\2022\Professional\Common7\IDE\CommonExtensions\Microsoft\Asal\TokenService\Microsoft.Asal.TokenService.exe" has failed with unexpected error: TS003: Error, TS004: Unable to get access token.  'AADSTS65001: The user or administrator has not consented to use the application with ID '04f0c124-f2bc-4f59-8241-bf6df9866bbd' named 'VS with native MSA'. Send an interactive authorization request for this user and resource.
```

My code looks like this:
```
var tokenCredential = new DefaultAzureCredential();
var accessToken = await tokenCredential.GetTokenAsync(new TokenRequestContext("api://guid/.default"));
```

I am using Azure.Identity package in version 1.7.0.

I was able to resolve the issue by going to my App Registration and in `Expose an API` add the GUID printed out in the error message, i.e. "04f0c124-f2bc-4f59-8241-bf6df9866bbd".

I cannot find any documentation about this. What this GUID represents, where to find it?

**Comment by julealgon** [comment] 2022-12-14 15:39
> I was able to resolve the issue by going to my App Registration and in `Expose an API` add the GUID printed out in the error message, i.e. "04f0c124-f2bc-4f59-8241-bf6df9866bbd".

Oh.... that's interesting! I might use your solution as well to make local testing easier over here.

The first time I saw that error I tried finding the API by name in the Azure Portal to grant permissions to it but it doesn't show up at all there, so I was confused.

**Comment by donnykwitty** [comment] 2022-12-19 19:53
I'm having very similar issues using DefaultAzureCredential. I'm trying to get a token.
Using just VisualStudioCredential as a test, when calling await new VisualStudioCredential().GetTokenAsync(...)
I get:
`Azure.Identity.CredentialUnavailableException : Process "C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\Asal\TokenService\Microsoft.Asal.TokenService.exe" has failed with unexpected error: TS003: Error, TS004: Unable to get access token.  'AADSTS50020: User account '{EmailHidden}' from identity provider 'live.com' does not exist in tenant 'Microsoft Services' and cannot access the application '04f0c124-f2bc-4f59-8241-bf6df9866bbd'(VS with native MSA) in that tenant. The account needs to be added as an external user in the tenant first. Sign out and sign in again with a different Azure Active Directory user account.`

**Comment by LockTar** [comment] 2023-03-09 19:58
I'm having the same issue as well. I'm trying to call the Microsoft Graph from Visual Studio 2022. 
I'm using the Microsoft graph net SDK v5. 

I'm getting the token as follow as described [here](https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/dev/docs/upgrade-to-v5.md#authentication) because I want to use MSI (and my application in the cloud as well):
```C#
var credential = new DefaultAzureCredential();
var tokenResult = await credential.GetTokenAsync(new Azure.Core.TokenRequestContext(new string[] { "https://graph.microsoft.com" }));

string token = tokenResult.Token;
```

The token only contains the following scopes:
`Application.ReadWrite.All Directory.Read.All email IdentityUserFlow.ReadWrite.All openid profile User.Read`.
I'm able to retrieve information that is related with those scopes.
I'm a global admin. 
How can I change the scopes?

I guess the problem is that AppId `04f0c124-f2bc-4f59-8241-bf6df9866bbd` is not added by Microsoft on the Microsoft Graph API app registration.

I'm using Azure.Identity version 1.8.2.

**Comment by christothes** [comment] 2023-03-09 21:03
@LockTar Does this only reproduce with VisualStudioCredential? If so, and you are on Visual Studio 2022 17.5.1 or later, it could be related to [this](https://github.com/Azure/azure-sdk-for-net/issues/34699#issuecomment-1456436480).

**Comment by LockTar** [comment] 2023-03-09 22:13
> @LockTar Does this only reproduce with VisualStudioCredential? 

@christothes not sure what you mean with this... I'm setting my account in the options of visual studio. I guess the guid above is then from VisualStudioCredential? The jwt token says as displayname 'VS with native MSA'.

> If so, and you are on Visual Studio 2022 17.5.1 or later, it could be related to this.

Yes I'm running the latest version of VS2022 17.5.1.

See my [issue on Microsoft Graph SDK repository](https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/1703) as well.

@christothes if this is the same issue as the event grid... I don't think it's solved when the event grid team enables it right? I think the Microsoft Graph team should do something as well? If so, could you add that information to my other issue? Thanks.

**Comment by christothes** [comment] 2023-03-09 22:47
> > @LockTar Does this only reproduce with VisualStudioCredential?
> 
> @christothes not sure what you mean with this... I'm setting my account in the options of visual studio. I guess the guid above is then from VisualStudioCredential? The jwt token says as displayname 'VS with native MSA'.

Yes, correct. What I meant was if you were to specify a different credential such as `AzureCliCredential`, either by using it explicitly or through configuration of `DefaultAzureCredentialOptions`, would you get a similar error?

> > If so, and you are on Visual Studio 2022 17.5.1 or later, it could be related to this.
> 
> Yes I'm running the latest version of VS2022 17.5.1.
> 
> See my [issue on Microsoft Graph SDK repository](https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/1703) as well.
> 
> @christothes if this is the same issue as the event grid... I don't think it's solved when the event grid team enables it right? I think the Microsoft Graph team should do something as well? If so, could you add that information to my other issue? Thanks.

Yes - I'll confirm whether the Graph service needs to be added as well.

**Comment by christothes** [comment] 2023-03-09 23:07
Apparently Graph, in general, is already pre-authorized. However, this is not true for all scopes. Which scopes in particular did you need?

Note: It may not be possible to get them all pre-authorized.

**Comment by LockTar** [comment] 2023-03-09 23:19
> Apparently Graph, in general, is already pre-authorized. However, this is not true for all scopes. Which scopes in particular did you need?

At the moment I'm trying to manage Azure ad groups and members but I need a lot more scopes in the future. 
Curious why you can't set the scopes that you need.

**Comment by christothes** [comment] 2023-03-09 23:54
You can pre-authorize any scopes you want using a custom application. This is just a matter of which are pre-authorized for the app used by VIsual Studio's token auth functionality.

**Comment by LockTar** [comment] 2023-03-10 21:36
> You can pre-authorize any scopes you want using a custom application. 

@christothes 
For a custom app or Managed Identity of an Azure resource like function app it's not a problem. I've done this before with a script like this:
https://learn.microsoft.com/en-us/azure/app-service/scenario-secure-app-access-microsoft-graph-as-app?tabs=azure-cli#grant-access-to-microsoft-graph

But I can't get it to work from Visual Studio to MS Graph API....

I think I need to make a configuration for using an app reg locally and Managed Identity when deployed to Azure.

Unless you have a good idea...

**Comment by LockTar** [comment] 2023-03-11 10:15
> Yes, correct. What I meant was if you were to specify a different credential such as `AzureCliCredential`, either by using it explicitly or through configuration of `DefaultAzureCredentialOptions`, would you get a similar error?

I finally understood what you meant. I tried the following code now to call the graph:

```C#
DefaultAzureCredentialOptions options = new DefaultAzureCredentialOptions()
{
    ExcludeAzurePowerShellCredential = true,
    ExcludeEnvironmentCredential = true,
    ExcludeInteractiveBrowserCredential = true,
    ExcludeManagedIdentityCredential = true,
    ExcludeSharedTokenCacheCredential = true,
    ExcludeVisualStudioCodeCredential = true,
    ExcludeVisualStudioCredential = true,
    ExcludeAzureCliCredential = false
};

var credential = new DefaultAzureCredential(options);
var tokenResult = await credential.GetTokenAsync(new Azure.Core.TokenRequestContext(new string[] { "https://graph.microsoft.com" }));
```

I logged in with the Azure CLI and I then have the scopes:
`AuditLog.Read.All Directory.AccessAsUser.All email Group.ReadWrite.All openid profile User.ReadWrite.All`

So different scopes but no way to change those scopes...

**Comment by julealgon** [comment] 2023-03-20 13:00
> Hi, we're sending this friendly reminder because we haven't heard back from you in **7 days**. We need more information about this issue to help address it. Please be sure to give us your input. If we don't hear back from you within **14 days** of this comment the issue will be automatically closed. Thank you!

This is still very much a real issue mr bot.

**Comment by christothes** [comment] 2023-03-20 14:59
In general, if you need specific scopes when calling Graph API that are not granted to those 1st party applications (Visual Studio or Azure CLI), you'll need to use a credential where you control which application is being used, such as EnvironmentCredential or InteractiveBrowserCredential. This custom AD application can be granted the scopes needed and tokens requested as this application will have those custom scopes.  [This article](https://learn.microsoft.com/en-us/azure/active-directory/develop/permissions-consent-overview) provides an overview of scopes and permissions.

**Comment by LockTar** [comment] 2023-03-20 15:06
I for now changed it for local development to client credentials authentication because that is the closest to my solution in this case...

**Comment by julealgon** [comment] 2023-03-20 15:14
> I for now changed it for local development to client credentials authentication because that is the closest to my solution in this case...

That's an interesting workaround, but will only work if what you are accessing even allows daemon tokens at all... in my case, the API relies on a user token to do resource-based authorization checks, so it doesn't even make sense for me to consider exposing the same endpoints with the client credentials flow.

**Comment by julealgon** [comment] 2023-04-12 16:07
@christothes could you please clarify where the fix was made? Do I just need to update a specific package and test again?

**Comment by christothes** [comment] 2023-04-12 16:11
Hi @julealgon I don't believe there is a fix to be made - [This previous comment ](https://github.com/Azure/azure-sdk-for-net/issues/28563#issuecomment-1476390947)describes what I believe would resolve the issue. Please let me know if that doesn't work for you.

**Comment by julealgon** [comment] 2023-04-12 16:26
I'm confused @christothes . If I need to change the credential I'm using to debug locally, then that would end up impacting my real application as well. I'm using `DefaultAzureCredential` precisely because I want it to be resolved automatically when actually running the function in AppService.

Are you saying now that I need to have branching code in my project to be able to test this? "if development => EnvironmentCredential, else DefaultAzureCredential"? If that's the case, that makes the local debugging experience vastly worse.

My understanding was that it should be possible to add the necessary permissions to the built-in applications instead (Visual Studio, CLI, etc) like [this post mentioned](https://github.com/Azure/azure-sdk-for-net/issues/28563#issuecomment-1351395834). That approach felt to me like a workaround though so I was still waiting for official confirmation on it.

What you are suggesting now is completely different however and would force code changes either permanently (to allow my whole team to seamlessly debug the function) to the codebase.

**Comment by christothes** [comment] 2023-04-12 22:43
> I'm confused @christothes . If I need to change the credential I'm using to debug locally, then that would end up impacting my real application as well. I'm using `DefaultAzureCredential` precisely because I want it to be resolved automatically when actually running the function in AppService.
> 
> Are you saying now that I need to have branching code in my project to be able to test this? "if development => EnvironmentCredential, else DefaultAzureCredential"? If that's the case, that makes the local debugging experience vastly worse.

Not necessarily. The first credential attempted by `DefaultAzureCredential` is `EnvironmentCredential` (see details [here](https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/identity/Azure.Identity#defaultazurecredential)). Your development app registration can be configured by setting the appropriate environment variables without the need to use a different credential.

> My understanding was that it should be possible to add the necessary permissions to the built-in applications instead (Visual Studio, CLI, etc) like [this post mentioned](https://github.com/Azure/azure-sdk-for-net/issues/28563#issuecomment-1351395834). That approach felt to me like a workaround though so I was still waiting for official confirmation on it.

There is a limit to which scopes can be added. For common Azure services, this should be no problem. However, when Graph is involved there is a very long tail of additional scopes that will probably never be added by default.

**Comment by christothes** [comment] 2023-04-13 19:08
Reading back through the issue again, have you tried adding the VS app Id to your API as described [here](https://github.com/Azure/azure-sdk-for-net/issues/28563#issuecomment-1351395834)?

**Comment by christothes** [comment] 2023-05-04 14:34
@Firoso - Is your application also first-party?

**Comment by Firoso** [comment] 2023-05-04 17:19
@christothes no it is not.

**Comment by christothes** [comment] 2023-05-08 18:44
Discussed offline and setting the application's Application Id ("213a3141-ce9d-4124-bfb5-75b849483e22" in this case) as the scope in the `TokenRequestContext` works.

**Closed** 2023-05-30 01:32 UTC
Labels: Client, needs-author-feedback, Azure.Identity, customer-reported, question, no-recent-activity
