### ISSUE TITLE
[BUG] EventHubProducerClient SendAsync fails with EventHubsException(ClientClosed): Unable to create the items needed to communicate with the Event Hubs service

### ISSUE THREAD

**Issue by vakuras** [Azure/azure-sdk-for-net#24618] opened 2021-10-10 12:32 UTC
**Describe the bug**
We randomly see an exception of EventHubsException(ClientClosed): Unable to create the items needed to communicate with the Event Hubs service being thrown from EventHubProducerClient.SendAsync.

**Expected behavior**
Not to fail with the error...

**Actual behavior (include Exception or Stack Trace)**

```text
EventHubsException(ClientClosed): Unable to create the items needed to communicate with the Event Hubs service
and also - 
Exception while executing function: InventoryToRawEvents
---> System.Net.Sockets.SocketException (10048): Only one usage of each socket address (protocol/network address/port) is normally permitted.
at Azure.Messaging.EventHubs.Amqp.AmqpConnectionScope.CreateAndOpenConnectionAsync(Version amqpVersion, Uri serviceEndpoint, Uri connectionEndpoint, EventHubsTransportType transportType, IWebProxy proxy, Int32 sendBufferSizeBytes, Int32 receiveBufferSizeBytes, RemoteCertificateValidationCallback certificateValidationCallback, String scopeIdentifier, TimeSpan timeout)
at Microsoft.Azure.Amqp.FaultTolerantAmqpObject`1.OnCreateAsync(TimeSpan timeout)
at Microsoft.Azure.Amqp.Singleton`1.GetOrCreateAsync(TimeSpan timeout)
at Microsoft.Azure.Amqp.Singleton`1.GetOrCreateAsync(TimeSpan timeout)
at Azure.Messaging.EventHubs.Amqp.AmqpConnectionScope.OpenProducerLinkAsync(String partitionId, TransportProducerFeatures features, PartitionPublishingOptions options, TimeSpan timeout, CancellationToken cancellationToken)
at Azure.Messaging.EventHubs.Amqp.AmqpProducer.CreateLinkAndEnsureProducerStateAsync(String partitionId, PartitionPublishingOptions partitionOptions, TimeSpan timeout, CancellationToken cancellationToken)
at Azure.Messaging.EventHubs.Amqp.AmqpProducer.CreateLinkAndEnsureProducerStateAsync(String partitionId, PartitionPublishingOptions partitionOptions, TimeSpan timeout, CancellationToken cancellationToken)
at Microsoft.Azure.Amqp.FaultTolerantAmqpObject`1.OnCreateAsync(TimeSpan timeout)
at Microsoft.Azure.Amqp.Singleton`1.GetOrCreateAsync(TimeSpan timeout)
at Microsoft.Azure.Amqp.Singleton`1.GetOrCreateAsync(TimeSpan timeout)
at Azure.Messaging.EventHubs.Amqp.AmqpProducer.CreateBatchAsync(CreateBatchOptions options, CancellationToken cancellationToken)
at Azure.Messaging.EventHubs.Amqp.AmqpProducer.CreateBatchAsync(CreateBatchOptions options, CancellationToken cancellationToken)
at Azure.Messaging.EventHubs.Producer.EventHubProducerClient.CreateBatchAsync(CreateBatchOptions options, CancellationToken cancellationToken)
at Azure.Messaging.EventHubs.Producer.EventHubProducerClient.CreateBatchAsync(CancellationToken cancellationToken)
at Common.EventHub.EventHubSender.SendEventsAsync(IEnumerable`1 events) in C:\__w\1\s\src\Common.EventHub\EventHubSender.cs:line 30
at Processors.Functions.InventoryToRawEventsFunction.InventoryToRawEvents(IReadOnlyList`1 documents) in C:\__w\1\s\src\Processors\Functions\InventoryToRawEventsFunction.cs:line 77
at Microsoft.Azure.WebJobs.Host.Executors.VoidTaskMethodInvoker`2.InvokeAsync(TReflected instance, Object[] arguments) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\VoidTaskMethodInvoker.cs:line 20
at Microsoft.Azure.WebJobs.Host.Executors.FunctionInvoker`2.InvokeAsync(Object instance, Object[] arguments) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionInvoker.cs:line 52
at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.InvokeWithTimeoutAsync(IFunctionInvoker invoker, ParameterHelper parameterHelper, CancellationTokenSource timeoutTokenSource, CancellationTokenSource functionCancellationTokenSource, Boolean throwOnTimeout, TimeSpan timerInterval, IFunctionInstance instance) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 572
at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithWatchersAsync(IFunctionInstanceEx instance, ParameterHelper parameterHelper, ILogger logger, CancellationTokenSource functionCancellationTokenSource) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 518
at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(IFunctionInstanceEx instance, FunctionStartedMessage message, FunctionInstanceLogEntry instanceLogEntry, ParameterHelper parameterHelper, ILogger logger, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 296
```

**To Reproduce**
The client is created and cached within the class - 
```csharp
EventHubProducerClient eventHubProducerClient = eventHubProducerClientFactory.Create(
                options.Value.EventHubFqdn,
                options.Value.EventHubName,
                authenticationHelper.GetDefaultAzureCredential(options.Value.ClientId));

class EventHubProducerClientFactory : IEventHubProducerClientFactory
{
        public EventHubProducerClient Create(string fullyQualifiedNamespace, string eventHubName, TokenCredential credential) =>
            new EventHubProducerClient(fullyQualifiedNamespace, eventHubName, credential);
}
```

**Environment:**
 - Name and version of the Library package used: Azure.Messaging.EventHubs 5.5.0
 - Hosting platform or OS and .NET runtime version: Windows Azure Function, .NET Core 3.1

**Comment by jsquire** [comment] 2021-10-11 13:22
Hi @vakuras.   Thank you for reaching out and we regret that you're experiencing difficulties.  The stack trace indicates a problem at the network level:
`System.Net.Sockets.SocketException (10048): Only one usage of each socket address (protocol/network address/port) is normally permitted.`

 That would seem to indicate something in the host network stack is overloaded or that network resources are not being cleaned up before reuse.   Unfortunately, there's no much context for me to speculate further;  the code that you've shared references a class that is not part of the SDK and there's no indication of how the client is managed.

Are you able to provide more context around the host application,  the `eventHubPProducerClientFactory`,  `authenticationHelper` and how the application is using and managing producers?

**Comment by vakuras** [comment] 2021-10-11 13:36
eventHubProducerClientFactory is a simple singleton factory, it returns an instance of EventHubProducerClient using this constructor - new EventHubProducerClient(fullyQualifiedNamespace, eventHubName, credential).
AuthenticationHelper returns a DefaultTokenCredential and it is passed to the EventHubProducerClient.

The client is cached for the whole lifetime of the class - in this case an Azure Function class.

**Comment by vakuras** [comment] 2021-10-11 13:41
private field within a class.

We use DI for the factory (IEventHubProducerClientFactory), since we use multiple/different EventHubs within the same Azure Function.

**Comment by vakuras** [comment] 2021-10-11 13:46
I added the factory code above.
It is not `static`. It is part of a class which is registered as a Singleton using DI.

**Comment by jsquire** [comment] 2021-10-11 14:10
What it looks like is that you're creating a new producer instance using your factory each time that your Function is invoked and just stashing it in a private field of the Function class.   Assuming that statement is correct, the producer isn't being cached.   It will live for a single function execution and then go out of scope. 

If the application is not explicitly closing or disposing the client, which seems likely, then the connection is being abandoned and will remain active until the idle timeout occurs (~60 seconds).   If your incoming request rate is greater than roughly one per minute, then the application is opening connections faster than they're being closed.  This will lead to socket and port exhaustion - which would agree with the exception in your stack trace.

In addition to the network issues, this usage pattern will also perform very poorly because the application is paying the cost to establish a connection/link for every Function invocation.

Since you indicated that you are using multiple outgoing Event Hub instances, my recommendation would be to enhance your factory such that it it disposable and has a `ConcurrentDictionary` instance that caches/creates producers on demand.   The goal is to ensure that there is a single producer instance created for each Event Hub which is reused across Function invocations.  Since you indicated the factory is registered for DI, this would also allow you to implement `Dispose` and ensure that the clients are closed at that point.

**Comment by jsquire** [comment] 2021-10-11 14:12
I'm going to mark this as addressed, as I believe that we've uncovered the root cause of your inquiry and adjustments that will remediate.   Please feel free to use the "`/unresolve`" command if you'd like to continue the discussion.

**Comment by vakuras** [comment] 2021-11-11 11:33
/unresolve

Hi,

We added an explicit dispose (using a **using**).
Once, or twice we had a "System.Net.Sockets.SocketException (10060): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond." error.

Have an idea what can be the issue?

**Comment by jsquire** [comment] 2021-11-15 15:16
This message indicates that the .NET networking layer was unable to establish a connection within the configured timeout period.  This is most commonly network latency, transient network issues, or contention in the thread pool that is preventing continuations from being scheduled efficiently.

**Closed** 2021-11-22 16:02 UTC
Labels: Event Hubs, Client, customer-reported, question, issue-addressed
