### ISSUE TITLE
[BUG]All authentication failures produce ObjectDisposedException

### ISSUE THREAD

**Issue by blushingpenguin** [Azure/azure-sdk-for-net#22530] opened 2021-07-08 08:04 UTC
**Describe the bug**
Failing to authenticate using ClientSecretCredentials produces ObjectDisposedException instead of a meaningful error message

**Expected behavior**
A meaningful error message is produced

**Actual behavior (include Exception or Stack Trace)**
```
Unhandled exception. System.ObjectDisposedException: Cannot access a closed Stream.
   at System.IO.MemoryStream.Write(ReadOnlySpan`1 buffer)
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at System.IO.StreamWriter.Dispose(Boolean disposing)
   at System.IO.TextWriter.Dispose()
   at System.Xml.XmlTextWriter.Close()
   at System.Xml.XmlWriter.Dispose(Boolean disposing)
   at System.Xml.XmlWriter.Dispose()
   at Azure.Core.XmlWriterContent.Dispose()
   at Azure.Core.Pipeline.HttpClientTransport.PipelineRequest.Dispose()
   at Azure.Core.HttpMessage.Dispose()
   at Azure.Storage.Blobs.ServiceRestClient.GetUserDelegationKeyAsync(KeyInfo keyInfo, Nullable`1 timeout, CancellationToken cancellationToken)
   at Azure.Storage.Blobs.BlobServiceClient.GetUserDelegationKeyInternal(Nullable`1 startsOn, DateTimeOffset expiresOn, Boolean async, CancellationToken cancellationToken)
   at Azure.Storage.Blobs.BlobServiceClient.GetUserDelegationKeyAsync(Nullable`1 startsOn, DateTimeOffset expiresOn, CancellationToken cancellationToken)
   at AzureSdkBadErrorMessage.Program.Main(String[] args) in /home/mark/proto/AzureSdkBadErrorMessage/Program.cs:line 21
   at AzureSdkBadErrorMessage.Program.<Main>(String[] args)
```

**To Reproduce**
Run the code in:
https://github.com/blushingpenguin/AzureSdkBadErrorMessage
This contains "credentials", which don't work and fails with the above stack trace. It also enables the diagnostics which do produce a meaningful error:

```
[Informational] Azure-Identity: ClientSecretCredential.GetToken invoked. Scopes: [ https://storage.azure.com/.default ] ParentRequestId: 8109abc0-218c-43d7-989d-d042441f41f5
[Informational] Azure-Core: Request [7a5a014b-c971-4164-b6ba-a5e15581b832] GET https://login.microsoftonline.com/common/discovery/instance?api-version=REDACTED&authorization_endpoint=REDACTED
x-client-SKU:REDACTED
x-client-Ver:REDACTED
x-client-OS:REDACTED
client-request-id:REDACTED
return-client-request-id:REDACTED
x-app-name:REDACTED
x-app-ver:REDACTED
x-ms-client-request-id:7a5a014b-c971-4164-b6ba-a5e15581b832
x-ms-return-client-request-id:true
User-Agent:azsdk-net-Identity/1.4.0,(.NET 5.0.7; Linux 5.11.0-22-generic #23-Ubuntu SMP Thu Jun 17 00:34:23 UTC 2021)
client assembly: Azure.Identity
[Informational] Azure-Core: Response [7a5a014b-c971-4164-b6ba-a5e15581b832] 200 OK (00.4s)
Cache-Control:max-age=86400, private
Strict-Transport-Security:REDACTED
X-Content-Type-Options:REDACTED
Access-Control-Allow-Origin:REDACTED
Access-Control-Allow-Methods:REDACTED
P3P:REDACTED
client-request-id:REDACTED
x-ms-request-id:a952e285-bc6f-4517-a432-79f8903d1701
x-ms-ests-server:REDACTED
Set-Cookie:REDACTED
Date:Thu, 08 Jul 2021 07:58:27 GMT
Content-Type:application/json; charset=utf-8
Content-Length:980

[Informational] Azure-Core: Request [9b317bf4-49a1-4f5a-b095-7d57561b3491] POST https://login.microsoftonline.com/274d3ec0-04a4-43aa-9db3-7e8b8deaebc3/oauth2/v2.0/token
x-client-SKU:REDACTED
x-client-Ver:REDACTED
x-client-OS:REDACTED
x-client-current-telemetry:REDACTED
x-client-last-telemetry:REDACTED
x-ms-PKeyAuth:REDACTED
x-ms-lib-capability:REDACTED
client-request-id:REDACTED
return-client-request-id:REDACTED
x-app-name:REDACTED
x-app-ver:REDACTED
x-ms-client-request-id:9b317bf4-49a1-4f5a-b095-7d57561b3491
x-ms-return-client-request-id:true
User-Agent:azsdk-net-Identity/1.4.0,(.NET 5.0.7; Linux 5.11.0-22-generic #23-Ubuntu SMP Thu Jun 17 00:34:23 UTC 2021)
Content-Type:application/x-www-form-urlencoded
client assembly: Azure.Identity
[Warning] Azure-Core: Error response [9b317bf4-49a1-4f5a-b095-7d57561b3491] 400 Bad Request (00.0s)
Cache-Control:no-store, no-cache
Pragma:no-cache
Strict-Transport-Security:REDACTED
X-Content-Type-Options:REDACTED
P3P:REDACTED
client-request-id:REDACTED
x-ms-request-id:e76ad7bd-48fe-480e-8097-f4469224bb01
x-ms-ests-server:REDACTED
x-ms-clitelem:REDACTED
Set-Cookie:REDACTED
Date:Thu, 08 Jul 2021 07:58:27 GMT
Content-Type:application/json; charset=utf-8
Expires:-1
Content-Length:652

[Informational] Azure-Identity: ClientSecretCredential.GetToken was unable to retrieve an access token. Scopes: [ https://storage.azure.com/.default ] ParentRequestId: 8109abc0-218c-43d7-989d-d042441f41f5 Exception: Azure.Identity.AuthenticationFailedException (0x80131500): ClientSecretCredential authentication failed: AADSTS90002: Tenant '274d3ec0-04a4-43aa-9db3-7e8b8deaebc3' not found. This may happen if there are no active subscriptions for the tenant. Check to make sure you have the correct tenant ID. Check with your subscription administrator.
Trace ID: e76ad7bd-48fe-480e-8097-f4469224bb01
Correlation ID: a1ad1ff1-137d-4d33-ab94-7f4a61f6b75c
Timestamp: 2021-07-08 07:58:27Z
 ---> Microsoft.Identity.Client.MsalServiceException (0x80131500): AADSTS90002: Tenant '274d3ec0-04a4-43aa-9db3-7e8b8deaebc3' not found. This may happen if there are no active subscriptions for the tenant. Check to make sure you have the correct tenant ID. Check with your subscription administrator.
Trace ID: e76ad7bd-48fe-480e-8097-f4469224bb01
Correlation ID: a1ad1ff1-137d-4d33-ab94-7f4a61f6b75c
Timestamp: 2021-07-08 07:58:27Z
```

**Environment:**
 - Azure.Storage.Blobs 12.9.1, Azure.Identity 1.4.0
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): [e.g. Azure AppService or Windows 10 .NET Framework 4.8]
```
 .NET SDK (reflecting any global.json):
 Version:   5.0.301
 Commit:    cc8c0abb32

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  21.04
 OS Platform: Linux
 RID:         ubuntu.21.04-x64
 Base Path:   /usr/share/dotnet/sdk/5.0.301/

Host (useful for support):
  Version: 5.0.7
  Commit:  556582d964

.NET SDKs installed:
  2.1.816 [/usr/share/dotnet/sdk]
  3.1.410 [/usr/share/dotnet/sdk]
  5.0.301 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.28 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.28 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.16 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.7 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.28 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.16 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.7 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
```

**Comment by amishra-dev** [comment] 2021-07-09 17:24
@schaabs could you take a look at this?
/cc @kasobol-msft fyi

**Comment by christothes** [comment] 2021-07-12 15:25
Looking at this today. This seems to be an issue in Storage or possibly Core. It reproduces without `Azure.Identity` involved at all.

**Comment by tg-msft** [comment] 2021-07-12 20:08
Removing Storage/ServiceAttention while we investigate this from the Azure.Core side

**Comment by christothes** [comment] 2021-07-14 02:38
I isolated this to just `XMLWriterContent` in AutoRest.CSharp. The following reproduces the exception:

```c#
var writer = new XmlWriterContent();
writer.Dispose()
```

```
 System.ObjectDisposedException : Cannot access a closed Stream.
  Stack Trace:
   at System.IO.MemoryStream.Write(ReadOnlySpan`1 buffer)
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at System.IO.StreamWriter.Dispose(Boolean disposing)
   at System.IO.TextWriter.Dispose()
   at System.Xml.XmlTextWriter.Close()
   at System.Xml.XmlWriter.Dispose(Boolean disposing)
   at System.Xml.XmlWriter.Dispose()
   at Azure.Core.XmlWriterContent.Dispose()
```

**Comment by christothes** [comment] 2021-07-14 02:39
https://github.com/Azure/autorest.csharp/issues/1402

**Comment by christothes** [comment] 2021-07-16 19:57
This will be fixed in the next release of Storage (when it picks up the latest dependency on Microsoft.Azure.AutoRest.CSharp)

**Closed** 2021-07-27 22:01 UTC
Labels: Azure.Core, Client, customer-reported, issue-addressed, question
