### ISSUE TITLE
Enable customized code coverage filtering for test projects

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-for-net#17066] opened 2020-11-19 02:26 UTC
Enable customization of filtering (include, exclude) for the code coverage work started for #14427. See https://github.com/dotnet/runtime/blob/d4487b84fa6b597153c74756474803fccae8b837/eng/testing/runsettings.targets for a possibility of one way of doing this. Ideally, it'd be nice if the .runsettings file was either valid and could be used in Visual Studio Test Explorer (in which case, update the root `CONTRIBUTING.md`), or rename it so people don't try to select it (e.g. `.runsettings.templ`).

**Comment by heaths** [comment] 2020-12-04 23:10
After some discussion with @pakrym and @christothes we have decided not to support this for now. `[ExcludeFromCodeCoverage]`, `[GeneratedCode]`, and `[Obsolete]` attributes are already ignored so those can be used (`[CompilerGenerated]` is not filtered out because then async code doesn't get covered) and only code in the service directory (CIs, because an aggregate coverage number is required) or package directory (dev workflow) is covered anyway. Ideally, no code should be excluded, and even in cases where some code should be excluded, `[ExcludeFromCodeCoverage]` should be sufficient. Excluding entire files or directories seems to only serve avoiding coverage given the current state of track 2 code. If there are common patterns we should exclude, we could do that in the eng/CodeCoverage.runsettings file for everyone. Having that file also makes it easy to use in Visual Studio from Test Explore (configure the runsettings file) rather than being tied to MSBuild.

The one problem @jsquire brought up is shared code. For EventHub, there's a significant amount of shared code that is tested separately, but not completely used by the shipping packages that include it. Thus, the packages' code coverage is significantly reduced (compared to Key Vault that also uses shared code, but its largely well-covered by all packages that include it).

Conversely, a lot of projects include source from sdk/core or from autorest.csharp (nupkg) but those are excluded, except for test coverage for sdk/core itself but @pakrym feels that's probably fine for now. For now, we aren't not asserting thresholds. Long-term, it might make sense to get better coverage for those classes in sdk/core so that test coverage is associated with any changes to sdk/core. IMO, that's something to which all client SDK owners could contribute since we all benefit from it. 😉

So then how do we deal problem's like @jsquire's about poor coverage of shared files (per package; overall it's good)? There's a few solutions we discussed in no particular order, though some are clearly better than others:

* Limit coverage data to the package directory for CIs and dev workflows. While we wanted more granular data for devs (and most don't build from eng/service.proj anyway, but an SLN), we could change the .runsettings file to only cover files in the packages' src directory; rather, we could exclude files in `**/tests/**`. Then turn test assembly coverage back on. While this would help with coverage of shared code imported into a test assembly, the lower coverage per-package would still bring numbers down.
* Perhaps in addition to above (or other similar solutions), shared code could be refactored so that less shared code that is uncovered in a particular project is included. Could be done with partial classes or other means. Such granularity may mean maintenance is more difficult.
* Duplicate test code or, rather, share it as well so it's not technically duplicated. Hopefully this doesn't increase test time too much, and even recordings could be shared (though perhaps with some necessary changes to Azure.Core.TestFramework, like passing additional directories to scan for recordings - shouldn't be too hard).
* Ignore it. If the poor coverage of some files isn't too bad, great coverage elsewhere should bring it up. @AlexGhiondea is only looking for >= 70% coverage eventually. That said, that might be a stretch for EventHubs in its current state (i.e. lots of shared source), so maybe some combination of the above options could help even that out.

We can reopen this (or reference it) later shall we need to have something more granular for exclusions. For now, lets try to improve coverage and handle these types of shared-code cases best we can.

**Comment by heaths** [comment] 2020-12-04 23:27
As for solutions should we need to exclude, there are a few I've ordered according to preference:

1. Switch from .runsettings file to generate a command line like https://github.com/dotnet/runtime does. While this eliminates a static file, it's the simpliest, most straight-forward strategy than dealing with file transformations and keeping track of different files (i.e. overriding `VSTestSetting`).
2. Add XML-valid markers, like well-formed comments (e.g. `<!-- PLACEHOLDER: ExcludeByFile -->`) that CodeCoverage.targets copies and replaces as needed (e.g. `ReadLinesFromFile` and `WriteLinesToFile` MSBuild tasks). That file then overrides `VSTestSetting`.
3. Certainly not ideal, but perhaps an option if very few projects need it: duplicate the eng/CodeCoverage.runsettings file into your own service directory or package directory, and override `VSTestSetting`. There's not much "custom" settings in eng/CodeCoverage.runsettings today and likely wouldn't be, so while you lose central management, in the rare case we need to modify that file, we could easily search for any others (PS: `dir sdk -recurse -filter *.runsettings`) and update them accordingly, which should automatically add owners in GitHub for the PR.

I should note that we may not even need to customize the .runsettings (file or respective command line options) since we may be able to exclude the files using reportgenerator, which has a few ways of excluding files or directories. We also already use the command line for that. Ultimately, the reportgenerator tool is used to generate the cobertura.xml file for Azure DevOps anyway, so whether we exclude via .runsettings while testing or later during report generation/aggregation, it really shouldn't matter.

**Comment by paolamvhz** [comment] 2020-12-22 19:41
Hello Team, 

I understand the solution to exclude some file is to add the arguments [ExcludeFromCodeCoverage] but not so sure where this should be added can you please proporcionate an example of where this should be added.

**Comment by heaths** [comment] 2020-12-29 17:12
It's an attribute you can add to classes, struts, or members. It's defined by the .NET BCL. If you want to exclude an entire project (not recommended permanently), add a property to your project with that name and value "true".

**Comment by paolamvhz** [comment] 2021-01-18 20:34
Hello Team, 

We tried using the [ExcludeFromCodeCoverage] but this is not viable as we will need to do the rework on the generated files every time we regenarate the code or if there is a change in the server side. I see a comment from heath but not so sure what will be the best approach so we do not have to rework each time we regenerate the code.

**Comment by jsquire** [comment] 2021-01-19 15:11
Hi @paolamvhz.   So that we can be sure that the right folks see them and they don't get lost,  would you please be so kind as to file a separate issue to track your last comment?   

I'm going to close this out again; this issue was intended to track the work needed to enable the code coverage filtering only.

**Closed by jsquire** 2021-01-19 15:11 UTC
Labels: Client, EngSys, Test Debt
