### ISSUE TITLE
[BUG] Cannot set http headers for a blob with spaces in the name

### ISSUE THREAD

**Issue by nrandell** [Azure/azure-sdk-for-net#8524] opened 2019-10-30 13:17 UTC
**Describe the bug**
I'm trying to set the header for a blob with spaces in the name and it fails saying the blob does not exist.

***Exception or Stack Trace***
Azure.Storage.StorageRequestFailedException: 'The specified blob does not exist.

**To Reproduce**
Given a blob with a space in the name. My example is 'hunt (1).jpg'. You can read properties, but not set the headers.

***Code Snippet***
```
await blobClient.GetPropertiesAsync(cancellationToken: ct);
await blobClient.SetHttpHeadersAsync(httpHeaders: headers, cancellationToken: ct);
```

**Expected behavior**
It should work!

**Screenshots**

**Setup (please complete the following information):**
 - OS: Windows
 - IDE : Visual Studio 2019
 - Azure.Storage.Blobs 12.0.0-preview.4

**Additional context**
Logging out seems to indicate that Uri.EscapeUriString has been called twice.
For the get properties request a subset of the log is
```
[Informational] Azure-Core: Request
method = HEAD
uri = https://XXXX/hunt%2520(1).jpg
```

This returns a 200 ok

For the set headers a subset of the log is
```
[Informational] Azure-Core: Request
requestId = f008d527-3634-4627-b05a-265f976e497d
method = PUT
uri = https://XXX/hunt%2520(1).jpg??omp=REDACTED
```

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x ] Bug Description Added
- [ x] Repro Steps Added
- [ x] Setup information Added

**Comment by AlexGhiondea** [comment] 2019-10-30 14:43
Hi. Thanks for reporting this! This was a known issue that I believed it was fixed.

/cc @tg-msft

**Comment by tg-msft** [comment] 2019-10-30 17:56
Yes - I think this is the same as #7659 which should be fixed in the next release.

**Comment by tg-msft** [comment] 2019-10-31 23:14
I've just verified this works with the latest [12.0.0 release from earlier today on NuGet](https://www.nuget.org/packages/Azure.Storage.Blobs/12.0.0) using the following code:

``` C#
// Get a reference to the blob
string containerName = "test-container";
string blobName = "test      blob";
BlobClient blob = new BlobClient(connectionString, containerName, blobName);

// Check the Content-Type
BlobProperties properties = await blob.GetPropertiesAsync();
Console.WriteLine($"Initial Content-Type: {properties.ContentType}");
            
// Change the Content-Type
await blob.SetHttpHeadersAsync(new BlobHttpHeaders { ContentType = "application/json" });

// Ensure it round-tripped
properties = await blob.GetPropertiesAsync();
Console.WriteLine($"Updated Content-Type: {properties.ContentType}");
```

Thanks for reporting this bug!  I'm going to close it as a duplicate of #7659.

/cc @pakrym to check whether the double escape in the logging output is a known issue or if we should file a bug to track

**Closed by tg-msft** 2019-10-31 23:14 UTC
Labels: Client, Storage
