### ISSUE TITLE
[BUG] [Service Bus] Unauthorized access. 'Listen' claim(s) are required to perform this operation

### ISSUE THREAD

**Issue by zendu** [Azure/azure-sdk-for-net#24289] opened 2021-09-28 21:18 UTC
**Describe the bug**
Unable to peek deadletter messages from subscription.

**Expected behavior**
Should be able to peek messages.

**Actual behavior (include Exception or Stack Trace)**
Exception: Unauthorized access. 'Listen' claim(s) are required to perform this operation. Resource: 'sb://mysbnamespace.servicebus.windows.net/mytopic/Subscriptions/mysubscriptiption/$deadletterqueue/$management'. TrackingId:f46a3a78-ea18-4e98-aa3f-f6202c047029_G18, SystemTracker:NoSystemTracker, Timestamp:2021-09-28T21:06:09

Stack Trace
```
at Azure.Messaging.ServiceBus.Amqp.AmqpReceiver.PeekMessagesInternalAsync(Int64 sequenceNumber, Int32 messageCount, TimeSpan timeout, CancellationToken cancellationToken)
   at Azure.Messaging.ServiceBus.Amqp.AmqpReceiver.<>c.<<PeekMessagesAsync>b__55_0>d.MoveNext()
--- End of stack trace from previous location ---
   at Azure.Messaging.ServiceBus.ServiceBusRetryPolicy.RunOperation[T1,TResult](Func`4 operation, T1 t1, TransportConnectionScope scope, CancellationToken cancellationToken)
   at Azure.Messaging.ServiceBus.ServiceBusRetryPolicy.RunOperation[T1,TResult](Func`4 operation, T1 t1, TransportConnectionScope scope, CancellationToken cancellationToken)
   at Azure.Messaging.ServiceBus.Amqp.AmqpReceiver.PeekMessagesAsync(Nullable`1 sequenceNumber, Int32 messageCount, CancellationToken cancellationToken)
   at Azure.Messaging.ServiceBus.ServiceBusReceiver.PeekMessagesInternalAsync(Nullable`1 sequenceNumber, Int32 maxMessages, CancellationToken cancellationToken)
   at Azure.Messaging.ServiceBus.ServiceBusReceiver.PeekMessageAsync(Nullable`1 fromSequenceNumber, CancellationToken cancellationToken)
   at UserQuery.Main(), line 28
   at UserQuery.Main(), line 62
```
**To Reproduce**
Steps to reproduce the behavior (include a code snippet, screenshot, or any additional information that might help us reproduce the issue)

My organization uses Privileged Identity Management. I elevated my access to Contributor for subscription containing Service Bus resource. I can read/peek message using Service Bus Explorer blade in Azure Portal. But following code keeps on failing.

```C#
var primaryServiceBusNamespace = @"mysbnamespace.servicebus.windows.net";
var subscriptionDeadletterPath = @"mytopic/Subscriptions/mysubscriptiption/$deadletterqueue";

await using var client = new ServiceBusClient(
	primaryServiceBusNamespace,
	new DefaultAzureCredential(new DefaultAzureCredentialOptions
	{
		ExcludeAzureCliCredential = true,
		ExcludeAzurePowerShellCredential = true,
		ExcludeEnvironmentCredential = true,
		ExcludeManagedIdentityCredential = true,
		ExcludeVisualStudioCodeCredential = true,
		ExcludeVisualStudioCredential = true,
		ExcludeSharedTokenCacheCredential = true,

		ExcludeInteractiveBrowserCredential = false,
	})
);

// create a receiver that we can use to receive the message
ServiceBusReceiver receiver = client.CreateReceiver(subscriptionDeadletterPath);

// the received message is a different type as it contains some service set properties
ServiceBusReceivedMessage receivedMessage = await receiver.PeekMessageAsync();
```
**Environment:**
 - Name and version of the Library package used: Azure.Messaging.ServiceBus 7.2.1 
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): .Net Core 5, Windows 10
 - IDE and version : LinqPad 6

**Comment by jsquire** [comment] 2021-09-28 21:35
@christothes:  Would you be so kind as to offer your advice on how to determine which identity `DefaultAzureCredential` is using so that we can confirm permissions?

**Comment by jsquire** [comment] 2021-09-28 21:35
Thank you for your feedback.  Tagging and routing to the team members best able to assist.

**Comment by christothes** [comment] 2021-09-28 21:41
> @christothes: Would you be so kind as to offer your advice on how to determine which identity `DefaultAzureCredential` is using so that we can confirm permissions?

[Enabling logging](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/identity/Azure.Identity/README.md#logging) on the credential is the easiest way to determine which credential was selected.

**Comment by zendu** [comment] 2021-09-28 21:54
I have logs. It has actual Azure resource details that I would like to be visible only to team members. Is there any way send it to limited folks?

**Comment by zendu** [comment] 2021-09-28 21:58
NVM. Find and Replace helped. Here you go:

```
[Informational] Azure-Messaging-ServiceBus: mytopic/Subscriptions/mysubscriptiption/$deadletterqueue-c054b6b6-50b8-400f-8b36-f018acf09c9e: MessagePeekAsync start. SequenceNumber = , MessageCount = 1
[Informational] Azure-Messaging-ServiceBus: Creating management link for Identifier: mytopic/Subscriptions/mysubscriptiption/$deadletterqueue-c054b6b6-50b8-400f-8b36-f018acf09c9e.
[Informational] Azure-Identity: DefaultAzureCredential.GetToken invoked. Scopes: [ https://servicebus.azure.net/.default ] ParentRequestId: 
[Informational] Azure-Identity: InteractiveBrowserCredential.GetToken invoked. Scopes: [ https://servicebus.azure.net/.default ] ParentRequestId: 
[Informational] Azure-Identity: Executing interactive authentication workflow inline.
[Informational] Azure-Identity: (False) MSAL 4.30.1.0 MSAL.NetCore Microsoft Windows 10.0.22000 [09/28/2021 21:49:13 - ] MSAL MSAL.NetCore with assembly version '4.30.1.0'. CorrelationId(55002113-a1e3-44ef-af78-8453eb0dee72)
[Informational] Azure-Identity: (False) MSAL 4.30.1.0 MSAL.NetCore Microsoft Windows 10.0.22000 [09/28/2021 21:49:13 - ] === InteractiveParameters Data ===
LoginHint provided: False
User provided: False
UseEmbeddedWebView: NotSpecified
ExtraScopesToConsent:
Prompt: select_account
HasCustomWebUi: False

[Informational] Azure-Identity: (False) MSAL 4.30.1.0 MSAL.NetCore Microsoft Windows 10.0.22000 [09/28/2021 21:49:13 - ]
=== Request Data ===
Authority Provided? - True
Scopes - https://servicebus.azure.net/.default
Extra Query Params Keys (space separated) -
ApiId - AcquireTokenInteractive
IsConfidentialClient - False
SendX5C - False
LoginHint ? False
IsBrokerConfigured - False
HomeAccountId - False
CorrelationId - 55002113-a1e3-44ef-af78-8453eb0dee72

[Informational] Azure-Identity: (False) MSAL 4.30.1.0 MSAL.NetCore Microsoft Windows 10.0.22000 [09/28/2021 21:49:13 - ] === Token Acquisition (InteractiveRequest) started:
 
  Authority Host: login.microsoftonline.com
[Informational] Azure-Identity: (False) MSAL 4.30.1.0 MSAL.NetCore Microsoft Windows 10.0.22000 [09/28/2021 21:49:13 - ] Azure region was not configured or could not be discovered. Not using a regional authority.
[Informational] Azure-Identity: (False) MSAL 4.30.1.0 MSAL.NetCore Microsoft Windows 10.0.22000 [09/28/2021 21:49:13 - ] Using system browser.
[Informational] Azure-Identity: (False) MSAL 4.30.1.0 MSAL.NetCore Microsoft Windows 10.0.22000 [09/28/2021 21:49:13 - ] Resolving authority endpoints... Already resolved? - TRUE
[Informational] Azure-Identity: (False) MSAL 4.30.1.0 MSAL.NetCore Microsoft Windows 10.0.22000 [09/28/2021 21:49:13 - ] Listening for authorization code on http://localhost:57141/
[Informational] Azure-Identity: (False) MSAL 4.30.1.0 MSAL.NetCore Microsoft Windows 10.0.22000 [09/28/2021 21:49:17 - ] Processing a response message to the browser. HttpStatus:OK
[Informational] Azure-Identity: (False) MSAL 4.30.1.0 MSAL.NetCore Microsoft Windows 10.0.22000 [09/28/2021 21:49:17 - ] An authorization code was retrieved from the /authorize endpoint. 
[Informational] Azure-Identity: (False) MSAL 4.30.1.0 MSAL.NetCore Microsoft Windows 10.0.22000 [09/28/2021 21:49:17 - ] Exchanging the auth code for tokens. 
[Informational] Azure-Identity: (False) MSAL 4.30.1.0 MSAL.NetCore Microsoft Windows 10.0.22000 [09/28/2021 21:49:17 - ] === InteractiveParameters Data ===
LoginHint provided: False
User provided: False
UseEmbeddedWebView: NotSpecified
ExtraScopesToConsent:
Prompt: select_account
HasCustomWebUi: False

[Informational] Azure-Identity: (False) MSAL 4.30.1.0 MSAL.NetCore Microsoft Windows 10.0.22000 [09/28/2021 21:49:17 - ] Resolving authority endpoints... Already resolved? - TRUE
[Informational] Azure-Core: Request [6af7841e-fa67-4fff-95ff-35dba4bc64a3] POST https://login.microsoftonline.com/organizations/oauth2/v2.0/token
x-client-SKU:REDACTED
x-client-Ver:REDACTED
x-client-CPU:REDACTED
x-client-OS:REDACTED
x-client-current-telemetry:REDACTED
x-client-last-telemetry:REDACTED
x-ms-lib-capability:REDACTED
client-request-id:REDACTED
return-client-request-id:REDACTED
x-app-name:REDACTED
x-app-ver:REDACTED
x-ms-client-request-id:6af7841e-fa67-4fff-95ff-35dba4bc64a3
x-ms-return-client-request-id:true
User-Agent:azsdk-net-Identity/1.4.1,(.NET 5.0.10; Microsoft Windows 10.0.22000)
Content-Type:application/x-www-form-urlencoded
client assembly: Azure.Identity
[Informational] Azure-Core: Response [6af7841e-fa67-4fff-95ff-35dba4bc64a3] 200 OK (00.6s)
Cache-Control:no-store, no-cache
Pragma:no-cache
Strict-Transport-Security:REDACTED
X-Content-Type-Options:REDACTED
P3P:REDACTED
client-request-id:REDACTED
x-ms-request-id:c5fda97d-3816-4a37-81ec-cd488d75c000
x-ms-ests-server:REDACTED
x-ms-clitelem:REDACTED
Set-Cookie:REDACTED
Date:Tue, 28 Sep 2021 21:49:17 GMT
Content-Type:application/json; charset=utf-8
Expires:-1
Content-Length:5043

[Informational] Azure-Identity: (False) MSAL 4.30.1.0 MSAL.NetCore Microsoft Windows 10.0.22000 [09/28/2021 21:49:18 - ] Checking client info returned from the server..
[Informational] Azure-Identity: (False) MSAL 4.30.1.0 MSAL.NetCore Microsoft Windows 10.0.22000 [09/28/2021 21:49:18 - ] Saving Token Response to cache..
[Informational] Azure-Identity: (False) MSAL 4.30.1.0 MSAL.NetCore Microsoft Windows 10.0.22000 [09/28/2021 21:49:18 - ] Subject not present in Id token
[Informational] Azure-Identity: (False) MSAL 4.30.1.0 MSAL.NetCore Microsoft Windows 10.0.22000 [09/28/2021 21:49:18 - ] Azure region was not configured or could not be discovered. Not using a regional authority.
[Informational] Azure-Identity: (False) MSAL 4.30.1.0 MSAL.NetCore Microsoft Windows 10.0.22000 [09/28/2021 21:49:18 - ] Saving AT in cache and removing overlapping ATs...
[Informational] Azure-Identity: (False) MSAL 4.30.1.0 MSAL.NetCore Microsoft Windows 10.0.22000 [09/28/2021 21:49:18 - ] Looking for scopes for the authority in the cache which intersect with https://servicebus.azure.net/.default
[Informational] Azure-Identity: (False) MSAL 4.30.1.0 MSAL.NetCore Microsoft Windows 10.0.22000 [09/28/2021 21:49:18 - ] Intersecting scope entries count - 1
[Informational] Azure-Identity: (False) MSAL 4.30.1.0 MSAL.NetCore Microsoft Windows 10.0.22000 [09/28/2021 21:49:18 - ] Matching entries after filtering by user - 1
[Informational] Azure-Identity: (False) MSAL 4.30.1.0 MSAL.NetCore Microsoft Windows 10.0.22000 [09/28/2021 21:49:18 - ] Saving Id Token and Account in cache ...
[Informational] Azure-Identity: (False) MSAL 4.30.1.0 MSAL.NetCore Microsoft Windows 10.0.22000 [09/28/2021 21:49:18 - ] Saving RT in cache...
[Informational] Azure-Identity: (False) MSAL 4.30.1.0 MSAL.NetCore Microsoft Windows 10.0.22000 [09/28/2021 21:49:18] Not writing FRT in ADAL legacy cache. 
[Informational] Azure-Identity: (False) MSAL 4.30.1.0 MSAL.NetCore Microsoft Windows 10.0.22000 [09/28/2021 21:49:18 - ] Fetched access token from host login.microsoftonline.com. 
[Informational] Azure-Identity: (False) MSAL 4.30.1.0 MSAL.NetCore Microsoft Windows 10.0.22000 [09/28/2021 21:49:18 - ] === Token Acquisition finished successfully. An access token was returned with Expiration Time: 09/28/2021 22:49:17 +00:00 and Scopes https://servicebus.azure.net/user_impersonation https://servicebus.azure.net/.default
[Informational] Azure-Identity: InteractiveBrowserCredential.GetToken succeeded. Scopes: [ https://servicebus.azure.net/.default ] ParentRequestId:  ExpiresOn: 2021-09-28T22:49:17.0000000+00:00
[Informational] Azure-Identity: DefaultAzureCredential.GetToken succeeded. Scopes: [ https://servicebus.azure.net/.default ] ParentRequestId:  ExpiresOn: 2021-09-28T22:49:17.0000000+00:00
[Informational] Azure-Messaging-ServiceBus: Management link created for Identifier: mytopic/Subscriptions/mysubscriptiption/$deadletterqueue-c054b6b6-50b8-400f-8b36-f018acf09c9e.
[Warning] Azure-Messaging-ServiceBus: RunOperation encountered an exception and will retry. Exception: System.UnauthorizedAccessException: Unauthorized access. 'Listen' claim(s) are required to perform this operation. Resource: 'sb://mysbnamespace.servicebus.windows.net/mytopic/Subscriptions/mysubscriptiption/$deadletterqueue/$management'. TrackingId:8d9e545d-4cff-4d03-b992-3c20a483428f_G13, SystemTracker:NoSystemTracker, Timestamp:2021-09-28T21:49:18
   at Azure.Messaging.ServiceBus.Amqp.AmqpReceiver.PeekMessagesInternalAsync(Int64 sequenceNumber, Int32 messageCount, TimeSpan timeout, CancellationToken cancellationToken)
   at Azure.Messaging.ServiceBus.Amqp.AmqpReceiver.<>c.<<PeekMessagesAsync>b__55_0>d.MoveNext()
--- End of stack trace from previous location ---
   at Azure.Messaging.ServiceBus.ServiceBusRetryPolicy.RunOperation[T1,TResult](Func`4 operation, T1 t1, TransportConnectionScope scope, CancellationToken cancellationToken)
[Warning] Azure-Messaging-ServiceBus: RunOperation encountered an exception and will retry. Exception: System.UnauthorizedAccessException: Unauthorized access. 'Listen' claim(s) are required to perform this operation. Resource: 'sb://mysbnamespace.servicebus.windows.net/mytopic/Subscriptions/mysubscriptiption/$deadletterqueue/$management'. TrackingId:e4fcb1b7-c189-40b6-844a-c9b5901f971f_G13, SystemTracker:NoSystemTracker, Timestamp:2021-09-28T21:49:20
   at Azure.Messaging.ServiceBus.Amqp.AmqpReceiver.PeekMessagesInternalAsync(Int64 sequenceNumber, Int32 messageCount, TimeSpan timeout, CancellationToken cancellationToken)
   at Azure.Messaging.ServiceBus.Amqp.AmqpReceiver.<>c.<<PeekMessagesAsync>b__55_0>d.MoveNext()
--- End of stack trace from previous location ---
   at Azure.Messaging.ServiceBus.ServiceBusRetryPolicy.RunOperation[T1,TResult](Func`4 operation, T1 t1, TransportConnectionScope scope, CancellationToken cancellationToken)
[Warning] Azure-Messaging-ServiceBus: RunOperation encountered an exception and will retry. Exception: System.UnauthorizedAccessException: Unauthorized access. 'Listen' claim(s) are required to perform this operation. Resource: 'sb://mysbnamespace.servicebus.windows.net/mytopic/Subscriptions/mysubscriptiption/$deadletterqueue/$management'. TrackingId:ee35cedd-e6f2-4f84-b18b-9f80072b3bb7_G13, SystemTracker:NoSystemTracker, Timestamp:2021-09-28T21:49:23
   at Azure.Messaging.ServiceBus.Amqp.AmqpReceiver.PeekMessagesInternalAsync(Int64 sequenceNumber, Int32 messageCount, TimeSpan timeout, CancellationToken cancellationToken)
   at Azure.Messaging.ServiceBus.Amqp.AmqpReceiver.<>c.<<PeekMessagesAsync>b__55_0>d.MoveNext()
--- End of stack trace from previous location ---
   at Azure.Messaging.ServiceBus.ServiceBusRetryPolicy.RunOperation[T1,TResult](Func`4 operation, T1 t1, TransportConnectionScope scope, CancellationToken cancellationToken)
[Error] Azure-Messaging-ServiceBus: mytopic/Subscriptions/mysubscriptiption/$deadletterqueue-c054b6b6-50b8-400f-8b36-f018acf09c9e: MessagePeekAsync Exception: System.UnauthorizedAccessException: Unauthorized access. 'Listen' claim(s) are required to perform this operation. Resource: 'sb://mysbnamespace.servicebus.windows.net/mytopic/Subscriptions/mysubscriptiption/$deadletterqueue/$management'. TrackingId:73602c35-99e4-471a-b790-580598bddbbd_G13, SystemTracker:NoSystemTracker, Timestamp:2021-09-28T21:49:30
   at Azure.Messaging.ServiceBus.Amqp.AmqpReceiver.PeekMessagesInternalAsync(Int64 sequenceNumber, Int32 messageCount, TimeSpan timeout, CancellationToken cancellationToken)
   at Azure.Messaging.ServiceBus.Amqp.AmqpReceiver.<>c.<<PeekMessagesAsync>b__55_0>d.MoveNext()
--- End of stack trace from previous location ---
   at Azure.Messaging.ServiceBus.ServiceBusRetryPolicy.RunOperation[T1,TResult](Func`4 operation, T1 t1, TransportConnectionScope scope, CancellationToken cancellationToken)
   at Azure.Messaging.ServiceBus.ServiceBusRetryPolicy.RunOperation[T1,TResult](Func`4 operation, T1 t1, TransportConnectionScope scope, CancellationToken cancellationToken)
   at Azure.Messaging.ServiceBus.Amqp.AmqpReceiver.PeekMessagesAsync(Nullable`1 sequenceNumber, Int32 messageCount, CancellationToken cancellationToken)
   at Azure.Messaging.ServiceBus.ServiceBusReceiver.PeekMessagesInternalAsync(Nullable`1 sequenceNumber, Int32 maxMessages, CancellationToken cancellationToken).
UnauthorizedAccessException•••
```

**Comment by christothes** [comment] 2021-09-28 22:01
> NVM. Find and Replace helped. Here you go:
> 
> ```
> [Informational] Azure-Messaging-ServiceBus: mytopic/Subscriptions/mysubscriptiption/$deadletterqueue-c054b6b6-50b8-400f-8b36-f018acf09c9e: MessagePeekAsync start. SequenceNumber = , MessageCount = 1
> [Informational] Azure-Messaging-ServiceBus: Creating management link for Identifier: mytopic/Subscriptions/mysubscriptiption/$deadletterqueue-c054b6b6-50b8-400f-8b36-f018acf09c9e.
> [Informational] Azure-Identity: DefaultAzureCredential.GetToken invoked. Scopes: [ https://servicebus.azure.net/.default ] ParentRequestId: 
> [Informational] Azure-Identity: InteractiveBrowserCredential.GetToken invoked. Scopes: [ https://servicebus.azure.net/.default ] ParentRequestId: 
> [Informational] Azure-Identity: Executing interactive authentication workflow inline.
> ```

This seems to indicate that InteractiveBrowserCredential was selected.

**Comment by JoshLove-msft** [comment] 2021-09-28 22:54
You'll want to make sure that you identity is assigned either the Service Bus Data Owner or at least Service Bus Data Receiver role - https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-managed-service-identity#azure-built-in-roles-for-azure-service-bus

**Comment by zendu** [comment] 2021-09-28 23:36
@JoshLove-msft, I have the necessary access. I can peek and read messages in Azure Portal. It's only SDK that is blocking the access.

**Comment by zendu** [comment] 2021-09-28 23:43
Service Bus Data Owner role has 91 permissions. All of them are included in Contributor role.

<img width="379" alt="image" src="https://user-images.githubusercontent.com/4323295/135179845-47c365d4-745e-48af-901d-c3859ef52f80.png">

```JSON
{
  "assignableScopes": [
    "/"
  ],
  "description": "Allows for full access to Azure Service Bus resources.",
  "id": "/subscriptions/{subscriptionId}/providers/Microsoft.Authorization/roleDefinitions/090c5cfd-751d-490a-894a-3ce6f1109419",
  "name": "090c5cfd-751d-490a-894a-3ce6f1109419",
  "permissions": [
    {
      "actions": [
        "Microsoft.ServiceBus/*"
      ],
      "notActions": [],
      "dataActions": [
        "Microsoft.ServiceBus/*"
      ],
      "notDataActions": []
    }
  ],
  "roleName": "Azure Service Bus Data Owner",
  "roleType": "BuiltInRole",
  "type": "Microsoft.Authorization/roleDefinitions"
}
```

Contributor

<img width="400" alt="image" src="https://user-images.githubusercontent.com/4323295/135180007-199dcd21-8ee0-422c-8f23-8da6b06f318d.png">

```JSON
{
  "assignableScopes": [
    "/"
  ],
  "description": "Grants full access to manage all resources, but does not allow you to assign roles in Azure RBAC, manage assignments in Azure Blueprints, or share image galleries.",
  "id": "/subscriptions/{subscriptionId}/providers/Microsoft.Authorization/roleDefinitions/b24988ac-6180-42a0-ab88-20f7382dd24c",
  "name": "b24988ac-6180-42a0-ab88-20f7382dd24c",
  "permissions": [
    {
      "actions": [
        "*"
      ],
      "notActions": [
        "Microsoft.Authorization/*/Delete",
        "Microsoft.Authorization/*/Write",
        "Microsoft.Authorization/elevateAccess/Action",
        "Microsoft.Blueprint/blueprintAssignments/write",
        "Microsoft.Blueprint/blueprintAssignments/delete",
        "Microsoft.Compute/galleries/share/action"
      ],
      "dataActions": [],
      "notDataActions": []
    }
  ],
  "roleName": "Contributor",
  "roleType": "BuiltInRole",
  "type": "Microsoft.Authorization/roleDefinitions"
}
```

**Comment by zendu** [comment] 2021-09-29 00:04
Noticed that Service Bus Data Owner has Data Actions which are missing from Contributor role. While Contributor role works in Azure Portal, SDK needs Service Bus Data Owner role. The exception message about "listen claim" is misleading as there is no way for user to know which action/data action it maps to.

<img width="565" alt="image" src="https://user-images.githubusercontent.com/4323295/135181386-0e7d2c80-b8be-4c42-92b3-a2cdc650171c.png">

<img width="531" alt="image" src="https://user-images.githubusercontent.com/4323295/135181425-1975a0cc-90b1-4f86-9b2c-b509bc94c255.png">

Is there documentation that maps these claims to action(s)/data action(s) of Azure Roles?

**Comment by JoshLove-msft** [comment] 2021-10-01 21:38
Thanks for the feedback @zendu - we will look into what we can do to improve the experience.

Related - https://github.com/Azure/azure-sdk-for-net/issues/23229

**Comment by bbieniek** [comment] 2022-04-11 12:24
It happens that we have this issue occasionally. Out of nowhere, we receive an exception even though the permissions have been correctly set to Receiver/Sender. It seems to have been fixed in JS libraries, but may still occur for .NET?

**Comment by Stordlord** [comment] 2022-04-11 13:01
Used the new project

**Comment by Stordlord** [comment] 2022-04-11 16:39
Done

**Comment by ilmax** [comment] 2022-09-08 06:44
@bbieniek the same happens to me, I granted the App Service `Azure Service Bus Data Receiver` & `Azure Service Bus Data Sender`, I can see the permissions from both the App Service -> Identity blade -> Azure role assignments and from the Service bus IAM blade, but still getting this error. Any suggestion on how to troubleshoot it?

**Comment by bbieniek** [comment] 2022-09-08 10:15
> @bbieniek the same happens to me, I granted the App Service `Azure Service Bus Data Receiver` & `Azure Service Bus Data Sender`, I can see the permissions from both the App Service -> Identity blade -> Azure role assignments and from the Service bus IAM blade, but still getting this error. Any suggestion on how to troubleshoot it?

In our case this was happening because the rollback slot of the function app didn’t have the permissions assigned

**Comment by ilmax** [comment] 2022-09-08 10:44
Thank you for reaching out, I'm not using slots at the moment and I'm assigning the permissions to a security group and adding the App Service Principal (the one auto-generated by managed identity) to the security group.
As of now, the only workaround I found is adding the permissions to the app service itself

**Comment by jsquire** [comment] 2023-07-26 18:23
It looks as if the root cause of the original issue was that an unexpected identity was being selected from the chain which lacked the permissions.   Unsure why it was not resolved, but since it has started to pick up comments unrelated to the original issue.   Each of those also appears to have been resolved.  For those with more recent occurrences, please feel free to open a new issue if you are still experiencing difficulties.

I'm going to close this out and lock discussions.

**Closed by jsquire** 2023-07-26 18:23 UTC
Labels: Service Bus, Client, customer-reported, question, needs-team-attention
