### ISSUE TITLE
[Text Analytics] AnalyzeOperationWithAADTest failing in nightly runs

### ISSUE THREAD

**Issue by Menghua1** [Azure/azure-sdk-for-net#34316] opened 2023-02-17 08:20 UTC
TextAnalytics nightly test runs are failing with:

> Error message
> Azure.RequestFailedException : Internal Server Error.
> Status: 200 (OK)
> ErrorCode: InternalServerError
> 
> Additional Information:
> Target: #/tasks/keyPhraseExtractionTasks/0
> error-0: InternalServerError: Internal Server Error.
> 
> Content:
> {"jobId":"d52d350c-f2a1-4517-8f09-9a7230e0fcd1","lastUpdateDateTime":"2023-02-17T03:06:53Z","createdDateTime":"2023-02-17T03:06:48Z","expirationDateTime":"2023-02-18T03:06:48Z","status":"failed","errors":[{"code":"InternalServerError","message":"Internal Server Error.","target":"#/tasks/keyPhraseExtractionTasks/0"}],"tasks":{"completed":0,"failed":1,"inProgress":0,"total":1,"keyPhraseExtractionTasks":[{"lastUpdateDateTime":"2023-02-17T03:06:53.506098Z","state":"failed"}]}}
> 
> Headers:
> Transfer-Encoding: chunked
> x-envoy-upstream-service-time: 8
> apim-request-id: 15d7d27e-941e-4279-a2a7-212336174b60
> Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
> X-Content-Type-Options: nosniff
> x-ms-region: REDACTED
> Date: Fri, 17 Feb 2023 03:06:53 GMT
> Content-Type: application/json; charset=utf-8
> 
> Data:
> Target: #/tasks/keyPhraseExtractionTasks/0
> error-0: InternalServerError: Internal Server Error.
> 
> 
> Stack trace
>    at Azure.Core.OperationInternal`1.GetResponseFromState(OperationState`1 state) in /mnt/vss/_work/1/s/sdk/core/Azure.Core/src/Shared/OperationInternalOfT.cs:line 289
>    at Azure.Core.OperationInternal`1.UpdateStatusAsync(Boolean async, CancellationToken cancellationToken)
>    at Azure.Core.OperationInternalBase.UpdateStatusAsync(CancellationToken cancellationToken) in /mnt/vss/_work/1/s/sdk/core/Azure.Core/src/Shared/OperationInternalBase.cs:line 87
>    at Azure.Core.OperationPoller.WaitForCompletionAsync(Boolean async, OperationInternalBase operation, Nullable`1 suggestedInterval, CancellationToken cancellationToken) in /mnt/vss/_work/1/s/sdk/core/Azure.Core/src/Shared/OperationPoller.cs:line 79
>    at Azure.Core.OperationInternalBase.WaitForCompletionResponseAsync(Boolean async, Nullable`1 pollingInterval, String scopeName, CancellationToken cancellationToken) in /mnt/vss/_work/1/s/sdk/core/Azure.Core/src/Shared/OperationInternalBase.cs:line 202
>    at Azure.Core.OperationInternal`1.WaitForCompletionAsync(Boolean async, Nullable`1 pollingInterval, CancellationToken cancellationToken) in /mnt/vss/_work/1/s/sdk/core/Azure.Core/src/Shared/OperationInternalOfT.cs:line 242
>    at Azure.Core.OperationInternal`1.WaitForCompletionAsync(CancellationToken cancellationToken) in /mnt/vss/_work/1/s/sdk/core/Azure.Core/src/Shared/OperationInternalOfT.cs:line 177
>    at Azure.AI.TextAnalytics.AnalyzeActionsOperation.WaitForCompletionAsync(CancellationToken cancellationToken) in /mnt/vss/_work/1/s/sdk/textanalytics/Azure.AI.TextAnalytics/src/AnalyzeActionsOperation.cs:line 210
>    at Azure.AI.TextAnalytics.Tests.AnalyzeOperationTests.AnalyzeOperationWithAADTest() in /mnt/vss/_work/1/s/sdk/textanalytics/Azure.AI.TextAnalytics/tests/AnalyzeOperationTests.cs:line 51
>    at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.BlockUntilCompleted()
>    at NUnit.Framework.Internal.MessagePumpStrategy.NoMessagePumpStrategy.WaitForCompletion(AwaitAdapter awaiter)
>    at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.<>c__DisplayClass1_0.<Execute>b__0()
>    at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.RunTestMethodInThreadAbortSafeZone(TestExecutionContext context, Action action)

For more details check here:

- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2197401&view=results

@jsquire for notification.

**Comment by joseharriaga** [comment] 2023-03-16 22:57
This is a duplicate of https://github.com/Azure/azure-sdk-for-net/issues/34970.

**Closed by joseharriaga** 2023-03-16 22:57 UTC
Labels: Client, Cognitive - Text Analytics, test-reliability
