### ISSUE TITLE
TryAdd on EventDataBatch should return false when first EventData exceeds batch's MaxSize.

### ISSUE THREAD

**Issue by bernarden** [Azure/azure-sdk-for-net#18571] opened 2021-02-08 22:53 UTC
After upgrading to the latest's version of EventHubs SDK one of the tests for my helper class is failing. 
The test is trying to add an EventData with a body size larger than the specified MaxMessageSize for an EventDataBatch. The expectation is that TryAdd will return false even when the first EventData exceeds EventDataBatch's size. Is there a reason why 'this.eventDataList.Count > 0' was added to the code?

https://github.com/Azure/azure-sdk-for-net/blob/146189cdadc14cb03fe9d5a70935f9b046071793/sdk/eventhub/Microsoft.Azure.EventHubs/src/EventDataBatch.cs#L84

P.S. I'm happy to create a PR to remove the count check if it shouldn't be there.

**Comment by jsquire** [comment] 2021-02-09 14:55
//cc: @serkantkaraca, @JamesBirdsall

**Comment by jsquire** [comment] 2021-02-09 14:55
Thank you for your feedback.  Tagging and routing to the team members best able to assist.

**Comment by serkantkaraca** [comment] 2021-04-23 03:54
Count check is by design. EventDataBatch allows adding first message to the batch regardless of message size. When check removed, 1MB max message support will be broken and first batch won't be able to send messages larger than 256KB.

**Comment by serkantkaraca** [comment] 2021-04-23 04:26
Closing since this is by design for legacy SDK. Please consider migrating to https://www.nuget.org/packages/Azure.Messaging.EventHubs/

**Closed by serkantkaraca** 2021-04-23 04:26 UTC
Labels: Client, Event Hubs, Service Attention, customer-reported, needs-team-attention, question

**Comment by ramya-rao-a** [comment] 2021-04-23 04:45
@bernarden You can refer to the [migration guide](https://aka.ms/azsdk/net/migrate/eh) for help on moving to the new Azure.Messaging.EventHubs library
