### ISSUE TITLE
Method not found: void Azure.Core.RequestUriBuilder.AppendPath(System.ReadOnlySpan`1<char>,bool)

### ISSUE THREAD

**Issue by mroseberry99** [Azure/azure-sdk-for-net#35638] opened 2023-04-18 16:57 UTC
I'm running a brand new Xamarin.Forms app with Azure.Storage.Blobs 12.15 nuget.  Everything runs fine on an Android device, but fails on an ios device(tried several).  The code that is failing is in the PCL.  

```csharp
byte[] blobBytes = null;

StorageSharedKeyCredential cred = new StorageSharedKeyCredential("<username>", "<password>");
BlobServiceClient blobServiceClient = new BlobServiceClient(new Uri($"https://<StorageAccountName>.blob.core.windows.net"), cred, null);
BlobContainerClient containerClient = blobServiceClient.GetBlobContainerClient("<ContainerName>");
           
BlobClient blob = containerClient.GetBlobClient("<PathToBlob>");

using (MemoryStream ms = new MemoryStream())
{
	Response response = blob.DownloadTo(ms); <-- Failing Here(Error in the subject of this ticket)
	blobBytes = ms.ToArray();
}
```
Please help.  I'm trying to upgrade from the old deprecated WindowsAzure.Storage to the new Azure.Storage.Blobs in our app and ran into this problem.  I'm using a brand new Xamarin.Forms app to remove all other factors.  It works in MAUI on both types of devices, just not Xamarin.

**Comment by navba-MSFT** [comment] 2023-04-19 03:22
@mroseberry99 Thanks for reaching out to us and reporting this issue. 

> Method not found: void Azure.Core.RequestUriBuilder.AppendPath(System.ReadOnlySpan`1<char>,bool)

Looking at the error message it seems like you are seeing indicates that there is a version mismatch between the Azure.Core package and the Azure.Storage.Blobs package in your Xamarin.Forms app. Specifically, the RequestUriBuilder.AppendPath method is not found, which suggests that you are using an older version of the Azure.Core package that does not include this method.

Also you should ensure that you are using the latest version of both the Azure.Core and Azure.Storage.Blobs packages in your Xamarin.Forms app. Check the version of the Azure.Core package: Make sure that the Azure.Core package **(1.31.0)** is installed and that its version is compatible with the Azure.Storage.Blobs package. You can check the Azure.Storage.Blobs package dependencies to find the correct version of Azure.Core. 

You can do this by updating the packages in your project using the NuGet Package Manager in Visual Studio or by manually editing the project file.

Here is an example of how to update the packages using the NuGet Package Manager:
- Right-click on your project in the Solution Explorer and select "Manage NuGet Packages".
- In the "Browse" tab, search for "Azure.Core" and "Azure.Storage.Blobs".
- Select each package and click the "Update" button to update to the latest version.
- Rebuild your project and try running it again.

Also ensure that the minimum required version of Xamarin.Forms is met, as the Azure.Storage.Blobs package may have a minimum requirement that is not met by the Xamarin.Forms version in use.

If the above plan doesn't help, please share the detailed exception that you are receiving.

**Comment by mroseberry99** [comment] 2023-04-19 23:07
Thank you for responding quickly.  Much appreciated.  I can assure you that I had done all of the above prior to my original post.  I am currently using v5.0.0.2578 of Xamarin.Forms.  I added Azure.Storage.Blobs v12.16.0 through nuget which automatically installs Azure.Core v1.31.0.  I encountered the error.  To be on the safe side I then installed Azure.Core v1.31.0 manually.  Same error.  To remove all other factors I then created a new Xamarin.Forms app from Visual Studio's templates, verifying that it was v5.0.0.2578, added Azure.Storage.Blobs 12.16.0, verified that it installed Azure.Core 1.31.0.  This results in the same error.  Now it's important to understand the error only gets thrown when run on an ios device.  I ran the same code(in original post) on Android and even did it on a windows forms app and it works as expected in those cases.  

It was then that I reached out here with my original post.

I then wrote code to see if it would at least be able to upload a blob.

```
StorageSharedKeyCredential cred = new StorageSharedKeyCredential("<username>", "<password>");
BlobServiceClient blobServiceClient = new BlobServiceClient(new Uri($"https://<StorageAccountName>.blob.core.windows.net"), cred, null);
BlobContainerClient containerClient = blobServiceClient.GetBlobContainerClient("<ContainerName>");
        
BlobClient blob = containerClient.GetBlobClient("<PathToBlob>");

string testString = "This is a test where i will turn this into a byte array and try to upload it to azure.";
byte[] bytesString = Encoding.ASCII.GetBytes(testString);
BinaryData bd = new BinaryData(bytesString);
Response<BlobContentInfo> response = blob.Upload(bd);
```

This throws another Method Not Found error only this time it's

System.ReadOnlyMemory`1<byte> Azure.Storage.UploadTransferValidationOptions.get_PrecalculatedChecksum()

Again this only gets thrown when deployed to iOS devices.  This code also works on Android devices and Windows platforms.

I wasn't able to find anything on the original error through searching here and other forums so I tried looking for others that had this error.  I found another having this issue 

https://github.com/Azure/azure-sdk-for-net/issues/32474

Reading through the back and forth on this ticket the respondent there(which is you by the way navba-MSFT, I just noticed this lol) you were able to reproduce this consistently.  I am quite confident in saying that these two issues have the same root cause.     [burrowj](https://github.com/burrowj) commented there that rolling back to Azure.Storage.Blobs 12.13.0 will solve the problem.  I tried that and everything works as expected on my end for both problems.  So it would seem that somewhere between 12.13.0 and 12.16.0 the bug was introduced and needs to be addressed.

You asked me to provide a detailed description of the error if none of what you asked me to do worked.  The following is the error and the StackTrace.  Thanks again for your help and looking into this.

Method not found: void Azure.Core.RequestUriBuilder.AppendPath(System.ReadOnlySpan`1<char>,bool)

    at Azure.Core.RawRequestUriBuilder.AppendRaw (System.String value, System.Boolean escape) [0x00007] in <6666ff19ada74e00bebd119725131a73>:0 \n  at 
    Azure.Storage.Blobs.BlobRestClient.CreateDownloadRequest (System.String snapshot, System.String versionId, System.Nullable`1[T] timeout, System.String range, System.String leaseId, System.Nullable`1[T] rangeGetContentMD5, System.Nullable`1[T] rangeGetContentCRC64, System.String encryptionKey, System.String encryptionKeySha256, System.Nullable`1[T] encryptionAlgorithm, System.Nullable`1[T] ifModifiedSince, System.Nullable`1[T] ifUnmodifiedSince, System.String ifMatch, System.String ifNoneMatch, System.String ifTags) [0x00029] in <6666ff19ada74e00bebd119725131a73>:0 \n  at 
    Azure.Storage.Blobs.BlobRestClient.Download (System.String snapshot, System.String versionId, System.Nullable`1[T] timeout, System.String range, System.String leaseId, System.Nullable`1[T] rangeGetContentMD5, System.Nullable`1[T] rangeGetContentCRC64, System.String encryptionKey, System.String en
    cryptionKeySha256, System.Nullable`1[T] encryptionAlgorithm, System.Nullable`1[T] ifModifiedSince, System.Nullable`1[T] ifUnmodifiedSince, System.String ifMatch, System.String ifNoneMatch, System.String ifTags, System.Threading.CancellationToken cancellationToken) [0x00000] in <6666ff19ada74e00bebd119725131a73>:0 \n  at 
    Azure.Storage.Blobs.Specialized.BlobBaseClient.StartDownloadAsync (Azure.HttpRange range, Azure.Storage.Blobs.Models.BlobRequestConditions conditions, Azure.Storage.DownloadTransferValidationOptions validationOptions, System.Int64 startOffset, System.Boolean async, System.Threading.CancellationToken cancellationToken) [0x0055c] in <6666ff19ada74e00bebd119725131a73>:0 \n  at 
    Azure.Storage.Blobs.Specialized.BlobBaseClient.DownloadStreamingInternal (Azure.HttpRange range, Azure.Storage.Blobs.Models.BlobRequestConditions conditions, Azure.Storage.DownloadTransferValidationOptions transferValidationOverride, System.IProgress`1[T] progressHandler, System.String operationName, System.Boolean async, Sy
    stem.Threading.CancellationToken cancellationToken) [0x003be] in <6666ff19ada74e00bebd119725131a73>:0 \n  at 
    Azure.Core.Pipeline.TaskExtensions.EnsureCompleted[T] (System.Threading.Tasks.ValueTask`1[TResult] task) [0x00008] in <6666ff19ada74e00bebd119725131a73>:0 \n  at 
    Azure.Storage.Blobs.PartitionedDownloader.DownloadTo (System.IO.Stream destination, Azure.Storage.Blobs.Models.BlobRequestConditions conditions, System.Threading.CancellationToken cancellationToken) [0x0023f] in <6666ff19ada74e00bebd119725131a73>:0 \n  at 
    Azure.Storage.Blobs.Specialized.BlobBaseClient.StagedDownloadAsync (System.IO.Stream destination, Azure.Storage.Blobs.Models.BlobRequestConditions conditions, System.IProgress`1[T] progressHandler, Azure.Storage.StorageTransferOptions transferOptions, Azure.Storage.DownloadTransferValidationOptions transferValidationOverride, System.Boolean async, System.Threading.CancellationToken cancellationToken) [0x000d5] in <6666ff19ada74e00bebd119725131a73>:0 \n  at 
    Azure.Core.Pipeline.TaskExtensions.En
    sureCompleted[T] (System.Threading.Tasks.Task`1[TResult] task) [0x00007] in <6666ff19ada74e00bebd119725131a73>:0 \n  at 
    Azure.Storage.Blobs.Specialized.BlobBaseClient.DownloadTo (System.IO.Stream destination, Azure.Storage.Blobs.Models.BlobRequestConditions conditions, Azure.Storage.StorageTransferOptions transferOptions, System.Threading.CancellationToken cancellationToken) [0x0000e] in <6666ff19ada74e00bebd119725131a73>:0 \n  at 
    Azure.Storage.Blobs.Specialized.BlobBaseClient.DownloadTo (System.IO.Stream destination, System.Threading.CancellationToken cancellationToken) [0x00000] in <6666ff19ada74e00bebd119725131a73>:0 \n  at 
    Azure.Storage.Blobs.Specialized.BlobBaseClient.DownloadTo (System.IO.Stream destination) [0x00007] in <6666ff19ada74e00bebd119725131a73>:0 \n  at 
    TestNewXamarin.MainPage.OnAppearing () [0x00056] in C:\\Projects\\NewXamarin\\TestNewXamarin\\TestNewXamarin\\TestNewXamarin\\MainPage.xaml.cs:50

**Comment by navba-MSFT** [comment] 2023-04-20 04:09
@mroseberry99 Thanks for getting back and sharing your findings. I am adding the service team to look into this further.

@xgithubtriage Could you please look into this once you get a chance ?

cc @amnguye @seanmcc-msft

**Comment by zacllewis** [comment] 2023-05-24 06:44
Hi, I've also been using this package and have also come across this bug for iOS. I'm hoping this bug can be fixed soon, as we have currently reverted to version 12.13.1 as that still works.

**Comment by jaschrep-msft** [comment] 2023-07-11 16:11
I think this may be an issue with the Azure.Core package. While the API in the exception has some conditional compilation associated with it, the method should still exist in all targets, so I don't think the Storage package is calling into Core incorrectly.

Retagging for appropriate team followup.

**Comment by jsquire** [comment] 2023-07-27 20:05
Hi @mroseberry99.  I'm unable to reproduce this by creating a new project, adding a reference to `Azure.Storage.Blobs` v12.17.0 and copying your code.   The same is true for versions .15 and .16.   If you are still in need of assistance, are you able to share a small self-contained project that reproduces the issue?

**Comment by zacllewis** [comment] 2023-07-28 14:35
Hi,

I have created a new project that reproduces this error. I was getting the "Method Missing" error on a simlar method "UploadAsync". I have included this in the project.
[TestSynciOS.zip](https://github.com/Azure/azure-sdk-for-net/files/12195492/TestSynciOS.zip)

The project has v12.17.0 of Azure Storage Blobs. When I click the button with either method the App Crashes when the library is called. This is something that only happens when running the iOS project. The app works with v12.13.1 of Azure Storage Blobs.

We currently have an issue with our Dev setups that we can't use breakpoints so are unable to debug/see exceptions.

Hope this helps.

**Comment by jsquire** [comment] 2023-07-31 19:18
@zacllewis:  Thank you for sharing your repro.  Unfortunately, I'm unable to reproduce on Windows or macOS, just loading into Visual Studio.   I can compile on both platforms without errors, though there are warnings about a deprecated overload for the main UI runner.   When running, under the debugger or no, I get a platform exception due to UI elements needing a root - unrelated this issue, but not something that I've been able to resolve with my limited Xamarin knowledge.

**Comment by jsquire** [comment] 2023-08-05 14:27
@zacllewis:  Thank you very much for your help.  _**Please roll the shared keys for your storage account, as the connection string was in the shared code.**_

Your latest project got me past the error and able to click around and debug.  Unfortunately, I'm still not able to repro the error.  The stack trace is quite helpful, though, as it shows that we're seeing two different errors - one for upload and one for download.   The download error looks to be related to cryptography, which is something that does differ between platforms.   Let's leave that one be for now.

The upload error looks to be related to something not finding types from `System.Data` which is a transitive reference that comes through `Azure.Core`.    If you are willing to let me take advantage of your kindness again for a bit more help, I'd like to run a quick test.   Can you try adding a direct reference to `System.Data` v7.0.0 in the `SyncFusion.iOS` project?  That should force the dependency to be available and, I'm hoping, resolve the upload error.

**Comment by zacllewis** [comment] 2023-08-07 13:51
@jsquire Thank you, that was a test storage account used specifically for this test.

I am happy to help as this is something we would like to see fixed. I tried adding a direct reference in SyncFusion.iOS to System.Data v7.0.0 like you suggested, when trying to add this however I was not able to see v7.0.0, I could only see v2.0.5.0. I did try add a direct refernce to the latest version I could, however this changed nothing.
![Syncfusion iOS](https://github.com/Azure/azure-sdk-for-net/assets/71595829/916914fe-ed3e-4be3-aee6-7bb1a226f283)

We were wondering if you would happy to spend 20 mins and teamviewer onto my machine to try get System.Data v7.0.0? 

Since we are both using the same project and you are unable to replicate the error. Below are the versions of the apps on our Dev setups:

1.Windows 11 Pro, Version 22H2, OS build 22621.1992, Experience Windows Feature Experience Pack 1000.22644.1000.0
2. Windows Visual Studio 2022 Version 17.6.5.
3. Mac Visual Studio V17.6.1.452
4. xCode v14.3.1
5. Simulator 
![Simulator V](https://github.com/Azure/azure-sdk-for-net/assets/71595829/1ce6e2a7-5244-490b-a557-e40069cfa4d6)

**Comment by jsquire** [comment] 2023-08-07 14:12
> m happy to help as this is something we would like to see fixed. I tried adding a direct reference in SyncFusion.iOS to System.Data v7.0.0 like you suggested, when trying to add this however I was not able to see v7.0.0, I could only see v2.0.5.0. I did try add a direct refernce to the latest version I could, however this changed n

Apologies for the confusion, that's my error; typo has been fixed in the original post.   You're looking for the [System.Memory](https://www.nuget.org/packages/System.Memory) NuGet package, which is the compatibility shim for `ReadOnlyMemory<T>` and others low-level constructs.

**Comment by mroseberry99** [comment] 2023-08-08 17:39
jsquire,
I would be happy to send you a project however, it needs to use an Azure Blob storage container that requires credentials.  How do we accomplish this so that it isn't public?  Is there a public one that we could use instead of my private one?  Or I could put the project out here and leave the username and password out and send that to you privately?  Also you said that you couldn't reproduce this when you created an app and used my code up above from the April 18th entry on this thread.  Could you possibly upload that project here so that I can verify your code and see if you are perhaps doing something a little different than I?  Thanks.

> Hi @mroseberry99. I'm unable to reproduce this by creating a new project, adding a reference to `Azure.Storage.Blobs` v12.17.0 and copying your code. The same is true for versions .15 and .16. If you are still in need of assistance, are you able to share a small self-contained project that reproduces the issue?

**Comment by jsquire** [comment] 2023-08-08 21:41
> jsquire, I would be happy to send you a project however, it needs to use an Azure Blob storage container that requires credentials. How do we accomplish this so that it isn't public?

I'd suggest just redacting the connection string; we can create a container to test with.   What I haven't been able to do so far is get something to fail in the same way.

**Comment by zacllewis** [comment] 2023-08-15 14:34
@jsquire Apologies for the long response time.

> Apologies for the confusion, that's my error; typo has been fixed in the original post. You're looking for the [System.Memory](https://www.nuget.org/packages/System.Memory) NuGet package, which is the compatibility shim for `ReadOnlyMemory<T>` and others low-level constructs.

I tested the Nuget package "System.Memory" however this had no effect.

> I'm also curious if you're able to repro the error loading the solution into VS Mac directly and the Android / Windows projects.

I have some good news. **I was unable to reproduce the error loading the solution into VS Mac directly.** Which shows that its an error specifically for Visual Studio on Windows.

> Installing TeamViewer isn't something that I can do, but I'd be happy to hop on a call and see if we can't work through things collaboratively. If you're interested in doing so, please let me know and I'll share email contact info so that we can figure out timing.

I would be happy to set up a teams call and see if we can work things through together.

> Yeah, this is confusing me as well. Outside of VS Mac, where I'm a version newer, we're running the same toolset. I skipped the Visual Studio step last week, as I only had the Mac with me, but I don't **think** that should be impactful, as the compilation and running happens on the Mac. I'll loop back around again today or tomorrow and try the full end-to-end.

Did you get around to trying this? If not can you please test this and see if you get the same case as me. The project works on the Mac but not on Visual Studio Windows.

**Comment by jsquire** [comment] 2023-08-17 21:33
Hi @zacllewis.   Many thanks for your continued assistance.  It has been invaluable in working through things.  I was finally able to repro end-to-end with a fresh install of VS 2022 without add-ons and customizations installed.   I'm still unable to explain why I couldn't trigger the behavior before.  

The good news is that I believe that I've got a fix for both "Method Missing" scenarios.  

The upload issue related to not finding `System.ReadOnlyMemory<byte>` appears to be related to conflicts between Xamarin and the project.  Adding the following to `SyncFusionTest.iOS.csproj` to enable automatic binding redirects unblocked that for me:

```xml
<PropertyGroup>
  <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
  <ResolveAssemblyConflicts>true</ResolveAssemblyConflicts>
</PropertyGroup>
```

The download issue related to not finding the overload for `System.IO.Hashing.NonCryptographicHashAlgorithm.Append` appears to be related to conflicts related to `System.Memory` and `System.Buffers` for the `netstandard2.0` target between Xamarin and `System.Text.Json`.    Adding the following to `SyncfusionTest.csproj` will hoist dependencies to the needed version:

```xml
<ItemGroup>
  <PackageReference Include="System.Memory" Version="4.5.5" />
  <PackageReference Include="System.Buffers" Version="4.5.1" />
</ItemGroup>
```

The same references are also needed in `SyncFusionTest.iOS.csproj`:

```xml
<ItemGroup>
  <PackageReference Include="System.Memory" Version="4.5.5">
    <IncludeAssets>none</IncludeAssets>
  </PackageReference>
  <PackageReference Include="System.Buffers" Version="4.5.1">
    <IncludeAssets>none</IncludeAssets>
  </PackageReference>
</ItemGroup>
```

With both sets of references in place, the download works for me.   Could I impose on your kindness one more time and ask you to verify in your environment as well?

**Comment by mroseberry99** [comment] 2023-08-17 22:13
Jsquire, I'm not zacllewis, but I'm the original poster on this thread and I am happy to tell you that after these to the project files that it now works in my app.  Great work!  

A couple questions:

1.  Will this be fixed in a way that we won't have to add these lines to the project files  for subsequent versions of Azure.Storage.Blobs?
2.  How you were able to debug this and find the underlying problem?  I obviously don't need an answer to this, but I am very curious.

Thank you so much for seeing this through!

**Comment by jsquire** [comment] 2023-08-18 11:39
@mroseberry99:  I'm very glad to hear that you're unblocked.  Unfortunately, this isn't something that can be fixed by the Azure SDK packages as it involves the default references used by the Xamarin Visual Studio infrastructure pulling in older versions of common libraries and the Xamarin build system being unable to resolve those conflicts automatically.  

From what I was able to find, these conflicts are not unusual for the Xamarin ecosystem and also impact packages outside the Azure SDK intermittently, typically resolving when Xamarin releases an update.   It seems the most common are conflicts with the transitive dependencies of `System.Text.Json` which is where `System.Memory` and `System.Buffers` come into play.  While we are conservative with our dependency versions in the Azure SDK and update only when we need a critical feature, it seems that Xamarin updates dependencies even more slowly.  

The good news is that any package directly referenced by a project will take precedence, and using a newer package will hoist the version up for all transitive dependencies.  Unless there's a breaking change between versions, this will usually resolve these kinds of issues.

> How you were able to debug this and find the underlying problem? 

Nothing magical, I'm afraid.   A lot of web searches for similar issues, a bunch of tracing dependency graphs on NuGet, and some trial-and-error.  The Xamarin build system is much closer to the legacy .NET Framework than modern .NET (core) - so I went in suspecting that there were binding redirects missing somewhere.   The key was finding a thread for the same method missing for `ReadOnlyMemory` with SignalR and seeing that traced back to `System.Text.Json`.   

With your confirmation that things are working, I'm going to mark this as addressed.  Please feel free to unresolve if you'd like to continue the discussion.

**Closed** 2023-08-25 16:34 UTC
Labels: Client, Azure.Core, customer-reported, question, issue-addressed
