### ISSUE TITLE
[FEATURE REQ] Support for Unity framework

### ISSUE THREAD

**Issue by tomaschladek** [Azure/azure-sdk-for-net#27591] opened 2022-03-16 17:30 UTC
### Library name

Azure.Core

### Please describe the feature.

Azure Communication Services Chat SDK UWP SDK can't run in Unity platform, due to usage of non-supported serializer.

Unity has their own JSON serializer for simple serialization   (https://docs.unity3d.com/Manual/JSONSerialization.html)  For more complex JSON   serialization/deserialization apps typically use Netwonsoft JSON (https://docs.unity3d.com/2019.4/Documentation/Manual/com.unity.nuget.newtonsoft-json.html).

Can Azure.Core use serializer that will be supported also for Unity Framework?

In Unity 2020 You can't use the  .Net scripting backend building for UWP.   Unity only supports the IL2CPP scripting backend for UWP.  The problem appear of result of how Unity IL2CPP compiler handles generics.   As result of some compiler limitation, Unity does not support .Nets JSON serialization.  

 You can find some information here:
- https://github.com/dotnet/runtime/issues/49772
- https://forum.unity.com/threads/please-add-system-text-json-support.1000369/

**Comment by jsquire** [comment] 2022-03-16 19:25
Thank you for your feedback.  Tagging and routing to the team members best able to assist.

**Comment by christothes** [comment] 2022-03-16 19:28
Hi @tomaschladek - If I am understanding correctly, the change would need to be made in Unity to support `System.Text.Json`. I don't think we would be able to change serialization all up to accommodate Unity's restrictions.

**Comment by AMollis** [comment] 2022-04-13 18:06
I believe the Unity limitation can be worked around by providing a custom converter and set it up in the JsonSerializationOptions, for each value type being serialized.    This dotnet issue describes the workaround:

https://github.com/dotnet/runtime/issues/49772

**Comment by tomaschladek** [comment] 2022-04-13 18:21
@christothes sorry for the delay, can we please reopen the bug. Adam have provided more info above in the comment

**Comment by christothes** [comment] 2022-04-13 18:57
> @christothes sorry for the delay, can we please reopen the bug. Adam have provided more info above in the comment

Hi @tomaschladek - If I understand correctly, the workaround mentioned requires that all types being serialized specify custom `JsonSerializerOptions`. However, this would not be possible for internal types, or types where serialization is not controlled by the developer.

This seems like an issue that Unity would need to address holistically, since the workaround would only apply to public types. Please let me know if there is a suggestion you have about how this could be addressed in the SDK.

**Comment by AMollis** [comment] 2022-04-13 21:56
@christothes  I believe the workaround involves writing customer converter for `JwtPayload::ExpiresOnRaw` value type.    This type is part of  the [Azure Communication Chat SDK
](https://github.com/Azure/azure-sdk-for-net/blob/4162f6fa2445b2127468b9cfd080f01c9da88eba/sdk/communication/Azure.Communication.Common/src/JwtTokenParser.cs)

```
        internal class JwtPayload
        {
            [JsonPropertyName("exp")]
            public long ExpiresOnRaw { get; set; }

            [JsonPropertyName("acsScope")]
            public string ScopesRaw { get; set; } = "";

            public DateTimeOffset ExpiresOn => DateTimeOffset.FromUnixTimeSeconds(ExpiresOnRaw);
            public string[] Scopes => ScopesRaw.Split(',');
        }
```

It seems like a custom converter could be specified and used in the Chat SDK, regardless of `JwtPayload` being internal.  Something like:

```
            //Serialization options
            JsonSerializerOptions serializeOptions = new JsonSerializerOptions()
            {
                // ValueTypeConverter described in the issue @ https://github.com/dotnet/runtime/issues/49772
                Converters = { new ValueTypeConverter<long>() }
            };

            JwtPayload myObject = new JwtPayload();

            //Serialize the object
            string theSerializedObject = JsonSerializer.Serialize(myObject, options: serializeOptions);
            Debug.Log(theSerializedObject);

            //Then deserialize again
            JwtPayload myObjectDeserialized = JsonSerializer.Deserialize<JwtPayload>(theSerializedObject, serializeOptions);
```
I'm not sure if there's a more generic to support this for all SDKs, or if this just makes sense in SDKs that want to support Unity (i.e. in the Chat SDK)

**Comment by christothes** [comment] 2022-04-13 22:59
Thanks @AMollis - The issue with being internal is that the developer cannot provide the custom serialization. I don't think we'd want to set this by default or implement custom logic to switch between the custom serialization and the default.

The other thing to note is that this type is just one of many that would encounter this problem. It just happens to be the first one we'll hit because it is related to authentication.

**Comment by AMollis** [comment] 2022-04-13 23:44
Makes sense.  There can easily be many other instances of value type serializations.  Managing all these special cases for Unity is not sustainable.

Do you see any other workaround for a developer, other than forking the Chat SDK and making custom build, or the app developer calling REST APIs directly?

**Comment by christothes** [comment] 2022-04-14 14:50
@RezaJooyandeh Do you have any thoughts here?

**Comment by tomaschladek** [comment] 2022-04-22 07:45
@RezaJooyandeh @DominikMe @petrsvihlik do you have any idea how to resolve it?

**Comment by petrsvihlik** [comment] 2022-04-22 10:35
@christothes @tomaschladek 
If the problem is caused by generics and the Common library is the only place that's causing the problem, we can work around it by replacing 
```csharp
return JsonSerializer.Deserialize<JwtPayload>(Base64Url.DecodeString(tokenParts[1]));
```
with something like
```csharp
// For compatibility with Unity, avoid using JsonSerializer.Deserialize<JwtPayload>
var jsonDoc = JsonDocument.Parse(Base64Url.DecodeString(tokenParts[1]));
jsonDoc.RootElement.TryGetProperty("exp", out var exp);
jsonDoc.RootElement.TryGetProperty("acsScope", out var scp);
exp.TryGetInt64(out var expVal);
var jwt = new JwtPayload()
{
  ExpiresOnRaw = expVal,
  ScopesRaw = scp.ToString()
};
return jwt;
```

A [longer-term solution that we're currently working on](https://microsofteur-my.sharepoint.com/:w:/g/personal/petrsvihlik_microsoft_com/Efs98IbPDkJLhOcHLhpRV-cBlZObnwrt_TnAAoB5TQBkyw?e=dJUccc) for different reasons, would be avoiding any kind of JWT parsing. The goal is to make the token completely opaque to SDKs.

**Comment by petrsvihlik** [comment] 2022-05-03 07:24
@AMollis do you, by any chance, have a testing project at hand that would allow reproducing the issue? I'd like to test the fixes suggested above and possibly include one of them in the Common lib,

**Comment by DominikMe** [comment] 2022-05-05 15:31
What would it help if we work around the Unity compatibility issue in Common and then the credential gets passed into Chat which itself uses JSON serialization that breaks Unity?

**Comment by petrsvihlik** [comment] 2022-05-05 16:58
> What would it help if we work around the Unity compatibility issue in Common and then the credential gets passed into Chat which itself uses JSON serialization that breaks Unity?

Yeah, that's why I'm saying that the fix would make sense only if Common is the only place that's causing the problem. Anyway, I've got access to the sample code so I'm gonna run a couple of tests and see how big of an issue this is.

**Comment by petrsvihlik** [comment] 2022-05-23 12:46
@tomaschladek I was able to reproduce the behavior, [apply a fix](https://github.com/Azure/azure-sdk-for-net/issues/27591#issuecomment-1106360419) and successfully receive a message sent from Teams.

```
UnloadTime: 2,787700 ms
End showing splash screen.
[ACS Test] Status updated: Logging in
[ACS Test] Obtained auth token.
[ACS Test] Status updated: Logged in
[ACS Test] Joining teams meeting (https://teams.microsoft.com/l/meetup-join/19%3SECRET)
[ACS Test] Status updated: Connecting
[ACS Test] Status updated: InLobby
[ACS Test] Status updated: Connected
[ACS Test] Starting teams chat...
[ACS Test] Started teams chat
[ACS Test] (Petr Svihlik) <p>test message</p>
```

It seems that the fix in Common could unlock some scenarios (like Chat). However, there is no guarantee that we won't run into it in the future at a different place. Before we make any changes, here's what I suggest:
- perform a static analysis of the .NET ACS codebase to search for similar problems
- based on the results, decide whether to fix them or not
- if yes, introduce automatic tests for Unity compatibility

I'm on vacation today and the next two weeks. Please let me know your thoughts in the meantime and let's discuss when I get back.

**Comment by tomaschladek** [comment] 2022-05-23 13:52
@petrsvihlik thank you very much for the test. Lets proceed with the proposed process. Can you please track the work with Anitha?

**Comment by petrsvihlik** [comment] 2022-06-07 14:27
@tomaschladek tracking internally as https://skype.visualstudio.com/SPOOL/_workitems/edit/2884882

**Closed** 2022-06-18 10:03 UTC
Labels: Client, Azure.Core, issue-addressed
