### ISSUE TITLE
[BUG] Blob upload doesn't work with FileBufferingReadStream

### ISSUE THREAD

**Issue by Skleni** [Azure/azure-sdk-for-net#17110] opened 2020-11-20 11:56 UTC
**Describe the bug**
Uploading a blob with `BlobClient.UploadAsync(Stream stream)` doesn't seem to work in combination with a `Microsoft.AspNetCore.WebUtilities.FileBufferingReadStream`. The blob is created, but its length is 0.

**Expected behavior**
The blob should be uploaded as with other streams and have the correct length.

**Actual behavior (include Exception or Stack Trace)**
The created blob's length is 0.

**To Reproduce**

The following code shows the behaviour:

```csharp
    class Program
    {
        static async Task Main(string[] args)
        {
            var blobClient = new BlobClient(...);

            var bytes = new byte[1024];
            
            await blobClient.DeleteIfExistsAsync();

            using (var stream = new MemoryStream(bytes))
            {
                await blobClient.UploadAsync(stream);
                var length = (await blobClient.GetPropertiesAsync()).Value.ContentLength;
                Console.WriteLine("MemoryStream: " + length);
            }

            await blobClient.DeleteIfExistsAsync();

            using (var stream = new MemoryStream(bytes))
            using (var buffer = new FileBufferingReadStream(stream, 1024, default, Path.GetTempPath()))
            {
                await blobClient.UploadAsync(buffer);
                var length = (await blobClient.GetPropertiesAsync()).Value.ContentLength;
                Console.WriteLine("FileBufferingReadStream: " + length);
            }
        }
    }
```

The output of this program is:

```
MemoryStream: 1024
FileBufferingReadStream: 0
```

**Environment:**
- Azure.Storage.Blobs 12.7.0 
- Microsoft.AspNetCore.WebUtilities 2.2.0
- .NET Core 3.1 Windows 10
- Visual Studio 16.8.2

**Comment by Skleni** [comment] 2020-11-20 12:19
Using the deprecated `Microsoft.Azure.Storage.Blob` package in Version `11.2.2` works as expected:

```csharp
    class Program
    {
        static async Task Main(string[] args)
        {
            var blobClient = new CloudBlockBlob(...);

            var bytes = new byte[1024];
            
            await blobClient.DeleteIfExistsAsync();

            using (var stream = new MemoryStream(bytes))
            {
                await blobClient.UploadFromStreamAsync(stream);
                Console.WriteLine("MemoryStream: " + blobClient.Properties.Length);
            }

            await blobClient.DeleteIfExistsAsync();

            using (var stream = new MemoryStream(bytes))
            using (var buffer = new FileBufferingReadStream(stream, 1024, default, Path.GetTempPath()))
            {
                await blobClient.UploadFromStreamAsync(buffer);
                var length = blobClient.Properties.Length;
                Console.WriteLine("FileBufferingReadStream: " + length);
            }
        }
    }
```
```
MemoryStream: 1024
FileBufferingReadStream: 1024
```

**Comment by amnguye** [comment] 2020-12-02 00:00
Hi, Looks like there's a problem with opening up and reading the stream. I'm surprised no error was thrown when the stream was not opened. Let me run your code snippet and see what the raw requests look like.

**Comment by amnguye** [comment] 2020-12-03 18:55
Hi I just tried to reproduce your issue.

I'm getting a different issue from your code snippet where this line
`using (var buffer = new FileBufferingReadStream(stream, 1024, default, Path.GetTempPath()))`
converts the buffer to a size 0. I also tried populating the buffer with random values to see if I could populate it and i'm still getting an empty buffer. Which would explain why we're not uploading anything from the stream.

I'm surprised the v11 is working for you, because this line is unrelated to the storage library.

I did test this on our two environments NET 2.1 and NET 5.0, I need to also test on 3.1 (which you are on) but seeing how I tested an older and newer version, I don't think I would be able to reproduce the issue there. I will update the issue once I test on 3.1

**Comment by Skleni** [comment] 2020-12-14 07:05
Is there anything I can do to help investigate this issue?

**Comment by amishra-dev** [comment] 2021-01-29 08:26
@amnguye, Amanda, can we propose a change to the submitted code to make it work? if not, lets retag this as a bug and investigate it as such

**Comment by Skleni** [comment] 2021-03-25 09:54
Any updates?

**Comment by amnguye** [comment] 2021-03-25 15:51
I probably wasn't clear in my previous message but this line of code here

`using (var buffer = new FileBufferingReadStream(stream, 1024, default, Path.GetTempPath()))`

When I go to debug, hands us an empty buffer. This issue is unrelated to the storage library, since I attempted with the v11 code and still got an empty buffer. Obviously if you go and hand Upload an empty buffer, there won't be anything to upload.

I'm not sure what more investigation can be done if this is an issue outside the storage library and with this line.

**Comment by Skleni** [comment] 2021-03-25 16:20
Ah sorry, I misunderstood your previous message indeed.

I just checked it, I do get a (seemingly) empty buffer as well, but the old `Microsoft.Azure.Storage.Blob` package still correctly uploads the blob for some reason:

![image](https://user-images.githubusercontent.com/10420514/112506356-f37ea300-8d8d-11eb-9703-726251352956.png)

![image](https://user-images.githubusercontent.com/10420514/112506529-26c13200-8d8e-11eb-9e8b-ba85d8db2309.png)

**Comment by Henery309** [comment] 2021-04-16 03:33
having same issue I am migrating from dotnet 3.1 to dotnet 5. As part of the migration I had to use the new storage SDK but came across this issue. Any workarounds?

**Comment by Skleni** [comment] 2021-04-16 10:23
A workaround is discussed in the issue linked above.

**Comment by Henery309** [comment] 2021-04-16 11:37
Thanks @Skleni I am following the other issue. It looks like the azure storage team loves making customers wait. This issue has been opened for almost 5 months. It is clear the new SDK has issue the same solution worked with the old SDK so it should be fixed in the new SDK..

**Comment by amishra-dev** [comment] 2021-06-03 00:08
@Henery309 the issue is outside of storage, the earlier library working was probably the result of it maintaining state. Please check https://github.com/Azure/azure-sdk-for-net/issues/17110#issuecomment-806986354 and the next comment on how to resolve.

**Closed by amishra-dev** 2021-06-03 00:08 UTC
Labels: Client, Service Attention, Storage, customer-reported, needs-team-attention, question
