### ISSUE TITLE
[BUG] Unable to get MSI token from local Visual Studio

### ISSUE THREAD

**Issue by seshenoy** [Azure/azure-sdk-for-net#6172] opened 2019-05-07 18:03 UTC
**Describe the bug**
I have a web app deployed on Azure as an App Service. MSI is enabled for that app. I am trying to get an MSI access token from my local visual studio(opened as Admin and signed in using my Microsoft AAD account)  with my target app's app id as the resource. However, it is throwing an error locally... How can I get an MSI token with my target App service's app id as the audience ?

***Exception or Stack Trace***
AzureServiceTokenProviderException: Parameters: Connection String: [No connection string specified], Resource: 078eb22a-6cbe-4eb6-ab5a-cf61aa91e8a9, Authority: . Exception Message: Tried the following 3 methods to get an access token, but none of them worked.
Parameters: Connection String: [No connection string specified], Resource: 078eb22a-6cbe-4eb6-ab5a-cf61aa91e8a9, Authority: . Exception Message: Tried to get token using Managed Service Identity. Unable to connect to the Managed Service Identity (MSI) endpoint. Please check that you are running on an Azure resource that has MSI setup.
**Parameters: Connection String: [No connection string specified], Resource: 078eb22a-6cbe-4eb6-ab5a-cf61aa91e8a9, Authority: . Exception Message: Tried to get token using Visual Studio. Access token could not be acquired.** 
Exception for Visual Studio token provider Microsoft.Asal.TokenService.exe : TS003: Error, TS004: Unable to get access token. 'Failed to refresh access token'

Parameters: Connection String: [No connection string specified], Resource: 078eb22a-6cbe-4eb6-ab5a-cf61aa91e8a9, Authority: . Exception Message: Tried to get token using Azure CLI. Access token could not be acquired. ERROR: Get Token request returned http error: 400 and server response: {"error":"invalid_grant","error_description":"AADSTS65001: The user or administrator has not consented to use the application with ID '04b07795-8ddb-461a-bbee-02f9e1bf7b46' named 'Microsoft Azure CLI'. Send an interactive authorization request for this user and resource.\r\nTrace ID: 7bfd042b-c5a0-4274-ab74-10adffb83300\r\nCorrelation ID: 325090e4-dcc7-4df7-a432-a1704757d3fd\r\nTimestamp: 2019-05-07 18:00:43Z","error_codes":[65001],"timestamp":"2019-05-07 18:00:43Z","trace_id":"7bfd042b-c5a0-4274-ab74-10adffb83300","correlation_id":"325090e4-dcc7-4df7-a432-a1704757d3fd","suberror":"consent_required"}

**To Reproduce**
1. Enable MSI on your target app service
2. Use the code below on your local visual studio 

***Code Snippet***
var azureServiceTokenProvider = new AzureServiceTokenProvider();
            //Request an access token to other Azure services
            var accessToken = await azureServiceTokenProvider.GetAccessTokenAsync("<AppId Of My Target API");

**Expected behavior**
It should provide me with the MSI token

**Screenshots**

**Setup (please complete the following information):**
 - OS: Windows 10
 - IDE : Visual Studio 2019
 - "Microsoft.Azure.Services.AppAuthentication" Version="1.2.0-preview2" 

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by kurtzeborn** [comment] 2019-05-08 18:15
Thank you for opening this issue! We are routing it to the appropriate team for follow up.

**Comment by scale-tone** [comment] 2019-05-14 13:52
Got the same trouble. The goal is to authenticate against a custom resource (an http-triggered azure function) with Managed Identities (from another azure function). This works perfectly in Azure. But not on devboxes. Locally I am able to get an access token for e.g. Key Vault, but not for my custom resource. The exceptions thrown are the same.

Tried different kinds of user-specific connection strings. E.g. with connString="RunAs=CurrentUser" I get the following:

> AzureServiceTokenProviderException: Parameters: Connection String: RunAs=CurrentUser, Resource: api://cf8f**************7cc, Authority: https://login.microsoftonline.com/common. Exception Message: Tried to get token using Active Directory Integrated Authentication. Access token could not be acquired. AADSTS50079: Due to a configuration change made by your administrator, or because you moved to a new location, you must enroll in multi-factor authentication to access 'api://cf8f**************7cc'.
> Trace ID: cbe15ab1-2cc7-4016-b573-e2fd5ace9300
> Correlation ID: 2eaaf7eb-33a1-4445-982b-f3fc0702e06f
> 

The only way it works locally is with "RunAs=App" and freshly created service principal's password (which corrupts the whole idea of not storing any secrets on devboxes).

**Comment by ddeschepper** [comment] 2019-06-22 22:21
@kurtzeborn do you have an update on this issue? We are having the same issue as @scale-tone: getting access tokens for Azure Resources (in our case Event Hub) works perfectly, but custom resources fails.

**Comment by yufeih** [comment] 2019-07-11 08:47
@kurtzeborn , any updates on this issue?

**Comment by corygehr** [comment] 2019-07-19 19:38
Hi folks, just ran into this issue myself in Visual Studio 2019.

Try going to Tools > Options > Azure Service Authentication. Ensure the correct Microsoft Account is listed and that you don't see "Reenter your credentials". This was the issue in my case - I needed to re-authenticate before it would work.

I expect these steps would also work in Visual Studio 2017.

**Comment by scale-tone** [comment] 2019-07-19 20:40
@corygehr , are you saying you're now able to obtain a token for **any arbitrary custom resource** (not only for e.g. KeyVault) on your devbox?

**Comment by CrazyTuna** [comment] 2019-07-23 10:29
@scale-tone, I can still reproduce the issue with VS2017 and VS2019.  It does not work for custom applications. See this SO post also:
[Can't get access token for custom AD Application
](https://stackoverflow.com/questions/53673516/cant-get-access-token-for-custom-ad-application)

**Comment by JamberFX** [comment] 2019-07-23 20:50
I am having the same issue with VS2017 and a VB Web Forms App.  I have tried what @corygehar suggested (actually several times now) and it did not work for me.

**Comment by spplante** [comment] 2019-08-13 18:58
Any update on this?

**Comment by fcavaco** [comment] 2019-08-29 09:24
hi Guys, believe you can always login with az client, the token provider will then pick your own user credentials to request a token. in that case you will have to have permissions against the resource which is normally fine for development environments. being logged in in Visual Studio should also work, but again you will need permissions in the resource against your own azure principal.

**Comment by CrazyTuna** [comment] 2019-08-29 09:37
@fcavaco, we know that... the problem only appears when you try to authenticate to a custom AD app not for azure resources.

**Comment by ddeschepper** [comment] 2019-08-29 09:56
Try adding 872cd9fa-d31f-45e0-9eab-6e460a02d1f1 as an authorized client app (in the portal: AAD->Expose an API->Authorized client applications). That guid is the client id that VS uses when aquiring a token. Make sure to define a scope for the API first on that same page, you'll need it when adding the client id.

**Comment by CrazyTuna** [comment] 2019-08-29 10:15
Thanks @ddeschepper, sounds good for me :-)

**Comment by seshenoy** [comment] 2019-09-11 17:08
Thank you all for contributing towards closing this issue. I believe I have been helped and hopefully so the community as well.

**Comment by scale-tone** [comment] 2019-09-11 18:01
Why is this now closed? It works via Azure CLI, yes, but (at least, for me) it still doesn't work via Visual Studio!

**Comment by seshenoy** [comment] 2019-09-11 18:08
@scale-tone I presumed that's the only recommended way to go for locally.... I'll keep this open for now.

**Comment by ddeschepper** [comment] 2019-09-11 18:25
@scale-tone if you follow the steps in my comment it works from VS. I've been developing like that for a while now.

**Comment by scale-tone** [comment] 2019-09-17 16:56
Thanks, @ddeschepper , it now indeed works via Visual Studio as well!
I was confused by a constant 'Failed to refresh access token' error message when trying to use this mode.
But adding **872cd9fa-d31f-45e0-9eab-6e460a02d1f1** to *Authorized Client Applications* magically fixed this, and now both modes are working for me.

**Comment by seshenoy** [comment] 2019-09-17 17:13
@scale-tone  So have you been helped as well ? Can I close this ? I have got the answer that I was looking for but want to make sure other contributors to this channel have been helped as well...

**Comment by scale-tone** [comment] 2019-09-17 17:15
@seshenoy  
yes, I'm fine now, thanks :) Please, feel free to close it

**Closed** 2019-09-17 17:25 UTC
Labels: Authorization, Mgmt, customer-reported

**Comment by drakeforte5** [comment] 2020-05-20 15:14
The RunAs=Developer; DeveloperTool=VisualStudio is now throwing an exception after updating to VS 2019 16.6.0 (just updated today).

Error is:
Tried to get token using Visual Studio. Access token could not be acquired.

**Comment by maciej-sielski** [comment] 2020-05-29 09:15
I have the same error as @drakeforte5. Cleaning Visual Studio cache does not change anything.

**Comment by Michael-D-Pine** [comment] 2020-06-02 01:21
> Hi folks, just ran into this issue myself in Visual Studio 2019.
> 
> Try going to Tools > Options > Azure Service Authentication. Ensure the correct Microsoft Account is listed and that you don't see "Reenter your credentials". This was the issue in my case - I needed to re-authenticate before it would work.
> 
> I expect these steps would also work in Visual Studio 2017.

Wow, yeah that was the issue for me, that sad thing is Visual Studio said I was signed in, so everything looked ok, until you go into that option and see "Reenter credentials" in which case I didn't need to it just took the re-authenticated credentials and everything worked fine after that, was a bit frustrating.

**Comment by corygehr** [comment] 2020-06-02 01:26
It happens randomly for me. I usually do the steps as @Michael-D-Pine suggested, but even if my account shows in the list I occasionally need to say 'Add an account...' and use the same creds as my account which is already showing.

**Comment by maciej-sielski** [comment] 2020-06-08 08:28
@corygehr you are right. I had to remove the account from VS (not sign out). I've also cleaned files in %userprofile%\AppData\Local\.IdentityService folder

**Comment by rupeshtech** [comment] 2020-07-14 19:51
I encountered the same problem and fixed it by login into Visual Studio (by clicking in right top corner) with the account which has enough rights on Azure resource which you are trying to access.

![image](https://user-images.githubusercontent.com/24852402/87469781-18762000-c61c-11ea-9691-640ed73df4c7.png)

**Comment by ie-zero** [comment] 2020-10-07 12:01
@rupeshtech Thank you very much for sharing the trick with Visual Studio. I never thought it would have any effect to try it but it solved my issue as well.

**Comment by josiahvinson** [comment] 2020-10-08 16:01
Same problem, but I didn't see "Reenter your credentials":
 
> Try going to Tools > Options > Azure Service Authentication. Ensure the correct Microsoft Account is listed and that you don't > see "Reenter your credentials". This was the issue in my case - I needed to re-authenticate before it would work.

Instead, I just chose "Add account" from the account dropdown, and then chose my original account, which did the trick!

**Comment by drdamour** [comment] 2021-05-14 22:15
@scale-tone @ddeschepper when adding the vs guid, do you know what scope needs to be authorized?

**Comment by scale-tone** [comment] 2021-05-14 22:33
@drdamour , it's been a while... :)

I assume, 'https://my-app.azurewebsites.net/user_impersonation' is the required one (since that's what AzureServiceTokenProvider is doing in this scenario - impersonating you as a user). Others I never tried to use or not to use.
Are you having issues with admin's consent for 'user_impersonation'?..

**Comment by drdamour** [comment] 2021-05-21 21:45
@scale-tone weirdly it seems like it doesn't matter the scope granted...if any scope is granted it works
