### ISSUE TITLE
[BUG] BlobServiceClient can't parse connection string with custom domain and not port 11002

### ISSUE THREAD

**Issue by liupeirong** [Azure/azure-sdk-for-net#27126] opened 2022-02-21 03:05 UTC
### Library name and version

Azure.Storage.Blobs 12.10.0

### Describe the bug

When using a custom domain in the blob connection string, for example, https://www.mydomain.com/myaccount, BlobServiceClient(connectionstring) or BlobServiceClient(serviceUri, credential) can't parse the account name correctly. Account name in BlobServiceClient appears empty after the constructor runs.

### Expected behavior

AccountName in BlobServiceClient should be "myaccount" in this example.

### Actual behavior

AccountName in BlobServiceClient is "", causing the subsequent calls to fail.

### Reproduction Steps

```C#
string cxnString = "DefaultEndpointsProtocol=https;AccountName=myaccount;AccountKey=redacted;BlobEndpoint=https://www.mydomain.com/myaccount;"
BlobServiceClient service = new BlobServiceClient(cxnString);
await service.GetPropertiesAsync(); //throws exception because AccountName in service is empty
```
Changing the connection string as following works:
```C#
string cxnString = "DefaultEndpointsProtocol=https;AccountName=myaccount;AccountKey=redacted;BlobEndpoint=https://www.mydomain.com:11002/myaccount;"
BlobServiceClient service = new BlobServiceClient(cxnString);
await service.GetPropertiesAsync(); //AccountName is correctly parsed
```
The following code using a different constructor has the same behaviour:
```C#
Uri uri = new Uri("https://www.mydomain.com/myaccount");
//Uri uri1 = new Uri("https://www.mydomain.com:11002/myaccount");
StorageSharedKeyCredential credential = new StorageSharedKeyCredential("myaccount", "redacted");
BlobServiceClient service = new BlobServiceClient(serviceUri, credential);
await service.GetPropertiesAsync(); // throws exception with uri, works with uri1
```

### Environment

.NET SDK (reflecting any global.json):
 Version:   5.0.405
 Commit:    63325e1c7d

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.405\

Host (useful for support):
  Version: 5.0.14
  Commit:  d5b56c6327

.NET SDKs installed:
  5.0.405 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 5.0.14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

VSCode 1.64.2 C# Extension v1.24.0

**Comment by PramodValavala-MSFT** [comment] 2022-02-22 05:29
@liupeirong Thanks for the feedback! We will look into this and get back.

**Comment by PramodValavala-MSFT** [comment] 2022-02-25 11:18
@liupeirong the custom domain is already mapped to a particular account. You don't need the account name in the URL.

So, a connection string like this should do (which I confirmed to work)

```
DefaultEndpointsProtocol=https;AccountName=myaccount;AccountKey=redacted;BlobEndpoint=https://www.mydomain.com/
```

**Comment by liupeirong** [comment] 2022-02-27 02:35
@PramodValavala-MSFT, can you paste your code please? It doesn't work for me using the exact string you pasted. See screenshot below:
![image](https://user-images.githubusercontent.com/1184120/155865908-4ecc9d56-36cf-48bd-af89-aa1189ec4c2d.png)

**Comment by PramodValavala-MSFT** [comment] 2022-02-28 15:00
@liupeirong I didn't check for the `AccountName` value but ran the code you mentioned didn't work. The following to be exact

```cs
var connString = "DefaultEndpointsProtocol=http;AccountName=<storage-account-name>;AccountKey=<account-key>;BlobEndpoint=http://www.mydomain.com/";
var client = new BlobServiceClient(connString);
var props = await client.GetPropertiesAsync();
```

I did not get an error on the 3rd line like you've mentioned but I do see that 'AccountName` is null. @seanmcc-msft Could you share insights on this?

**Comment by liupeirong** [comment] 2022-03-01 03:13
@PramodValavala-MSFT, if the URL is invalid, you will not see an exception, but it will hang on the third line. If the URL is valid, you will see an exception.

**Comment by PramodValavala-MSFT** [comment] 2022-03-24 16:07
@liupeirong Sorry for not getting back to you on this. The URL is valid. I also tried a simple operation like enumerating blob containers and it worked.

```cs
var connString = "DefaultEndpointsProtocol=https;AccountName=<account-name>;AccountKey=<account-key>;BlobEndpoint=http://<custom-domain>/";
var client = new BlobServiceClient(connString);
var props = await client.GetPropertiesAsync();

await foreach (var container in client.GetBlobContainersAsync())
{
    Console.WriteLine(container.Name);
}
```

Do note that I actually just tested for `http` but I believe it should be the same for `https` too. Either way, I will try to do a quick test for that as well.

**Comment by PramodValavala-MSFT** [comment] 2022-03-25 03:46
@liupeirong I tested with a HTTPS URL and did run into issues with caching, which once bypassed works. Could you share more details about your scenario like how you setup the custom domain, what you scenario is, and why not just use the default domain (assuming you connecting from a backend service since you are using the account key)?

**Comment by liupeirong** [comment] 2022-03-26 03:13
@PramodValavala-MSFT custom domain is required in Azure IoT Edge use cases. Azure IoT Edge supports [Blob Storage at the edge](https://docs.microsoft.com/en-us/azure/iot-edge/how-to-store-data-blob?view=iotedge-2020-11#connect-to-your-blob-storage-module). If you use http and port 11002, everything works. However, in manufacturing industry, Azure IoT Nested Edge is often required. [Nested Edge requires https and it works fine with https and port 11002](https://docs.microsoft.com/en-us/azure/iot-edge/how-to-configure-api-proxy-module?view=iotedge-2020-11#enable-blob-upload), but it doesn't work with https port 443.  Can you elaborate on the issue you ran into with https and how you *bypassed* it?

**Comment by PramodValavala-MSFT** [comment] 2022-04-11 16:17
@liupeirong Apologies again for the delay here! In my case, I was testing on Azure, so with Azure CDN required for HTTPS when using a Custom Domain, I had issues with responses being cached. These should not affect your scenario though.

Assuming the service is setup correctly to listen on port 443, I don't see why just that would be a problem for the SDK. Could you share the full exception that you see and also confirm the storage service is configured to run on port 443 or is perhaps behind a reverse proxy for HTTPS?

**Comment by liupeirong** [comment] 2022-04-20 00:11
> 

I no longer have the nested edge environment to reproduce the exception. In summary, it seems like SAS works well in edge blob storage whereas account name/key doesn't. In our use case, we need account name/key in order to browse the edge blob storage before writing a blob. We'll use other ways to work around it. You can close this case for now.

**Comment by PramodValavala-MSFT** [comment] 2022-11-15 22:13
@marmothonks Yes. Looks like [this list of ports](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/storage/Azure.Storage.Common/src/Shared/Constants.cs#L636) are checked against allowing those endpoints to work. Will investigate further and keep this post updated.

**Comment by PramodValavala-MSFT** [comment] 2022-12-05 22:04
@liupeirong @marmothonks The work to address this will be tracked in the linked feature request above since inference of path style URIs outside of IP-style hosts is currently not supported.

The workaround in the meantime is to use [an alternate constructor](https://learn.microsoft.com/en-us/dotnet/api/azure.storage.blobs.blobclient.-ctor?view=azure-dotnet#azure-storage-blobs-blobclient-ctor(system-uri-azure-azuresascredential-azure-storage-blobs-blobclientoptions)) which doesn't require a connection string. Closing this in favor of the feature request.

**Closed by PramodValavala-MSFT** 2022-12-05 22:04 UTC
Labels: Storage, Client, needs-team-attention, CXP Attention
