### ISSUE TITLE
How to specify preferredregion /currentRegion when using Azure.Data.Tables sdk with Cosmos db tables

### ISSUE THREAD

**Issue by dileepyavan** [Azure/azure-sdk-for-net#28986] opened 2022-05-25 22:45 UTC
### Library name and version

Azure.Data.Tables 12.5.0

### Query/Question

We recently migrated from Azure.Cosmos.Table to Azure.Data.Tables. After migrating we are seeing an increase in latency for database calls. We are assuming that this is happening because services in different regions are hitting only the write region and not read regions. We have a single write and multiple read regions. Previously with Azure.Cosmos.Table sdk , we were specifying the currentRegion property as below
`  _tableClient = storageAccount.CreateCloudTableClient(new TableClientConfiguration
            {
                CosmosExecutorConfiguration = new CosmosExecutorConfiguration
                {
                    CurrentRegion = config.ApplicationRegion
                }
            });`
CurrentRegion property has the location of the service and all the database calls are routed to cosmos db regions(read/write) based on proximity.

Is there a way we can specify the same with Azure.Data.Tables. sdk?

### Environment

OS: Debian 10
.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.25 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.25 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

**Comment by jsquire** [comment] 2022-05-26 12:53
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by christothes** [comment] 2022-05-31 17:48
Hi @dileepyavan  - There is currently no way to set this through the API. @sakash279  Could you comment about whether there is a way to set this via the REST API?

**Comment by sakash279** [comment] 2022-06-01 05:18
There is no way to set these properties via REST API at this point. A workaround to reduce latencies, and read from local regions is to use the regional endpoints by appending the "-regionname" eg. "-eastus" to your account name in the endpoint url. Please realize that in the event of an outage you will have to manually update such endpoints to a different region, and cosmosdb won't be able to do it automatically. 

 @PaulCheng and I are tracking this work to expose this via rest API, but do not have an ETA at the moment.

**Comment by sakash279** [comment] 2022-06-01 05:54
Azure.Cosmos.Table SDK works in 2 modes : Direct and Rest mode. The ability to set CurrentRegion is possible in Direct mode. If the user is configured to using Rest mode, the settings for CurrentRegion was set using Direct mode client, and the normal CRUD requests use Rest mode.

Azure.Data.Tables SDK does not rely on a direct mode (as a matter of fact, it doesn't have one), and only uses the REST mode to make requests to the CosmosDB service. This is by design. 

Hence the question on setting this via REST API is necessary for the azure.data.tables SDK to be able to expose such a property to the customers.

**Comment by christothes** [comment] 2022-09-09 18:33
duplicate of #30943

**Closed by christothes** 2022-09-09 18:33 UTC
Labels: Client, customer-reported, feature-request, Tables, needs-team-attention
