### ISSUE TITLE
Would like to be able to provide a different name for the "x-ms-client-request-id" header

### ISSUE THREAD

**Issue by craigktreasure** [Azure/azure-sdk-for-net#16704] opened 2020-11-06 22:11 UTC
**Library or service name.**

Future Mixed Reality clients.
 
**Is your feature request related to a problem? Please describe.**

Mixed Reality services use a different header name for the client request id. It would be great if we could specify the name of the header used instead of using the default "x-ms-client-request-id" that the SDK sets for us.

Thanks!

@tg-msft

**Comment by tg-msft** [comment] 2020-11-06 22:33
We should see if we can make the name of the header used by [ClientRequestIdPolicy](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/core/Azure.Core/src/Pipeline/Internal/ClientRequestIdPolicy.cs) and [ReadClientRequestIdPolicy](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/core/Azure.Core/src/Pipeline/Internal/ReadClientRequestIdPolicy.cs) configurable.  Mixed Reality is using an older correlation vector header that works identically to `x-ms-client-request-id` with a different name.

/cc @pakrym

**Comment by AlexGhiondea** [comment] 2021-07-07 19:34
Let's see if there is anything we can do here.

**Comment by tg-msft** [comment] 2021-07-20 16:07
I think it's just adding a new `DiagnosticOptions.ClientRequestIdHeaderName { get; set; } = "x-ms-client-request-id";` or similar property that we could reference in `HttpPipelineBuilder.Build` when constructing the `*ClientRequestIdPolicy`s.  This should also automatically work with https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/Azure.Core/samples/Diagnostics.md#setting-x-ms-client-request-id-value-sent-with-requests when implemented. 

ACS is making a similar request to support `MS-CV` so it'd be great to prioritize this if possible. /cc @AlexGhiondea @pakrym

**Comment by pakrym** [comment] 2021-07-20 16:09
I don't think it should go on options. Customers are not supposed to be able to change it. I was planning to turn HttpPipelineBuilder into a non-static class with knobs for client authors for a while. I think it's time.


```C#
var builder = new HttpPipelineBuilder();
builder.ClientRequestIdHeaderName = ...;
builder.SomeOtherFutureStuff = ..;

var pipeline = builder.Build();
```

**Comment by annelo-msft** [comment] 2023-08-11 23:29
Closing as duplicate of https://github.com/Azure/azure-sdk-for-net/issues/37427

**Closed by annelo-msft** 2023-08-11 23:29 UTC
Labels: Client, Azure.Core
