### ISSUE TITLE
Azure Search failing when updating from Microsoft.Rest.ClientRuntime v2.3.12 to v2.3.13

### ISSUE THREAD

**Issue by matthewrwilliams** [Azure/azure-sdk-for-net#4711] opened 2018-08-28 18:26 UTC
Please see this:
https://stackoverflow.com/questions/52012266/azure-search-failing-with-latest-update-of-microsoft-rest-clientruntime

**Comment by brjohnstmsft** [comment] 2018-08-28 21:16
@matthewrwilliams Can you please confirm which version of the Azure Search NuGet packages you're using?

@mhko Please investigate.

**Comment by matthewrwilliams** [comment] 2018-08-28 21:52
Latest stable through NuGet 5.0.2.

**Comment by shahabhijeet** [comment] 2018-09-10 20:37
We will release the fix some time mid next week (week ending 9/21/2018)
https://github.com/Azure/azure-sdk-for-net/pull/4752

**Comment by brjohnstmsft** [comment] 2018-09-10 21:49
@matthewrwilliams The issue is in the `Microsoft.Rest.ClientRuntime` package used by all Azure .NET SDKs. Once the fixed version of ClientRuntime is published, it should be possible to work around the issue by explicitly specifying the new package version in your project settings. Shortly after that we'll publish a new version of the Azure Search SDK that uses the fixed ClientRuntime version.

@shahabhijeet I've temporarily assigned this to you until the ClientRuntime fix is published. After that, feel free to re-assign it to me to update the `Microsoft.Azure.Search` packages.

**Comment by andersjoh** [comment] 2018-09-19 13:53
@brjohnstmsft  When will the updated ClientRuntime be published?

**Comment by brjohnstmsft** [comment] 2018-09-19 16:43
@andersjoh Per @shahabhijeet's update above, it should be published later this week.

**Comment by matthewrwilliams** [comment] 2018-09-26 20:52
Updating to the latest Microsoft.Rest.ClientRuntime 3.3.16 resolves the issue that v2.3.13 was causing with hanging.

**Comment by brjohnstmsft** [comment] 2018-10-01 20:57
@matthewrwilliams I think you mean Microsoft.Rest.ClientRuntime.Azure. There is no 3.3.16 of Microsoft.Rest.ClientRuntime.

Version 2.3.14 of Microsoft.Rest.ClientRuntime is now available. I'll close this issue once the Azure Search SDK has been updated to use it.

**Comment by matthewrwilliams** [comment] 2018-10-01 21:40
Bruce, thanks for the catch!

**Comment by brjohnstmsft** [comment] 2018-11-04 00:40
An updated version of [Microsoft.Azure.Search](https://www.nuget.org/packages/Microsoft.Azure.Search) is now available that uses the updated `ClientRuntime` packages.

**Closed by brjohnstmsft** 2018-11-04 00:40 UTC
