### ISSUE TITLE
[BUG] Incorrectly packaged Sample.zip

### ISSUE THREAD

**Issue by rgamage** [Azure/azure-sdk-for-net#10937] opened 2020-03-30 20:59 UTC
**Describe the bug**
Documentation page for this code base publishes a link to a .zip file for sample code.  This .zip file is incomplete, and therefore will not build or run after downloading and opening.

[https://docs.microsoft.com/en-us/samples/azure/azure-sdk-for-net/azuremessagingeventhubs-samples/](https://docs.microsoft.com/en-us/samples/azure/azure-sdk-for-net/azuremessagingeventhubs-samples/)

**Expected behavior**
Expect to be able to download this .zip file of code, and build and run it as is, without spending hours debugging, documenting failure, reporting failure, etc.

Build and run errors

1. Go to above docs page, download the .zip file and try to build/run

**Comment by jsquire** [comment] 2020-03-30 23:19
Hi @rgamage.  We're sorry that you're experiencing difficulties and appreciate you reaching out to let us know.  The root cause appears to be that the project file in the zip is still attempting to tie into the repository engineering pipeline to understand its target platforms.  While it may be possible to embed them directly in the project file, I believe that we'd prefer to keep them from drifting.

I think the best approach to fix this would be to inquire as to whether the tool that packages things up for the Docs site is able to transform project files for property substitution as part of its process.   @scbedd:  Do you know what tool generates the .zip file for samples or know who I should discuss this with?

**Comment by scbedd** [comment] 2020-04-07 18:30
Understood msftbot @jsquire was waiting for a response from me.

**Comment by jsquire** [comment] 2020-04-08 13:01
After investigation, the attachment created is confirmed to be an unexpected artifact produced by our toolchain.  The tool responsible for packaging samples was not built for use with the engineering system used for the repository and does not currently allow for injecting custom extensions.   Scott was kind enough to log #1193 to track that request.

In the short term, we'll work around this by manually adjusting the tooling output before assets are uploaded into the Docs pipeline, which will enable us to patch up the project file such that it can stand alone.  

At this point, I believe that discussion has dropped off and we have a plan to remediate moving forward.  Thank you, again, to @rgamage for bringing this to our attention.   I'm going to close this out, but please feel free to reopen if further discussion is desired.

**Closed by jsquire** 2020-04-08 13:01 UTC
Labels: Client, Event Hubs, customer-reported, needs-author-feedback, question
