### ISSUE TITLE
Look how FR library will benefit from Custom serialization

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-for-net#17797] opened 2021-01-06 18:42 UTC
Search library currently does this. 
This could be used for managing Tables, and pre-built models

**Comment by kinelski** [comment] 2022-06-21 02:46
Closing as a duplicate of https://github.com/Azure/azure-sdk-for-net/issues/24547.

**Closed by kinelski** 2022-06-21 02:46 UTC
Labels: Client, Cognitive - Form Recognizer
