### ISSUE TITLE
[BUG] Incorrect batch size estimation

### ISSUE THREAD

**Issue by VeselovAndrey** [Azure/azure-sdk-for-net#46381] opened 2024-10-01 05:48 UTC
### Library name and version

Azure.Messaging.ServiceBus 7.18.1

### Describe the bug

There is some error when estimating batch size.
Some batches (with size that almost hit size limit) were created but failed to send.

### Expected behavior

Send created baches.

### Actual behavior

Got the ServiceBusException: The message is larger than is currently allowed (262144 bytes).

### Reproduction Steps

1. Create batch(es)
```cs
ServiceBusSender sender = _serviceBusClient.CreateSender(queueName);
ServiceBusMessageBatch batch = await sender.CreateMessageBatchAsync(ct);
```

2.  Add messages to almost hit the limit (usign TryAddMessage to hit limit)
```cs
ServiceBusMessage sbMessage = GetNextMessage();
while (batch.TryAddMessage(sbMessage)) { sbMessage = GetNextMessage(); }
```
In my case batch.SizeInBytes was 261889 (MaxSizeInBytes == 262144)

3.  Try to send batch
```cs
await sender.SendMessagesAsync(batch, ct);
```

Got an exception:
```
Azure.Messaging.ServiceBus.ServiceBusException: The message (id:redacted, size:263525 bytes) is larger than is currently allowed (262144 bytes). (MessageSizeExceeded). For troubleshooting information, see
https://aka.ms/azsdk/net/servicebus/exceptions/troubleshoot.
```
The message size became 263525 (was 261889)

Workaround: set MaxSizeInBytes when creating batch to 262144 - (2 * 1024) (default max size - 2KB) 

### Environment

Windows 11
.NET 8.0.402 / Console App
Visual Studio 17.11.4

**Comment by jsquire** [comment] 2024-10-01 15:28
@m-redding :  Would you please take a look and coordinate with the Service Bus team?   I'm not sure from context if the batch overhead calculation is off or the service is sending the wrong size limit on a link when opened.

**Comment by m-redding** [comment] 2024-10-04 19:48
@VeselovAndrey Hello! Quick update, I was able to reproduce this error and am currently working on determining the root cause. Hopefully I will have a fix soon!

**Comment by m-redding** [comment] 2024-11-18 15:14
Hello @VeselovAndrey after further investigation I realized that this bug was only reproducible when using the debugger. I think this specific reproduction is the same as what was discussed in https://github.com/Azure/azure-sdk-for-net/issues/3363
I was able to reproduce consistently when using the debugger, however I have not been able to reproduce outside of the debugger. Are you seeing this error in a release configuration?

**Comment by VeselovAndrey** [comment] 2024-12-04 13:47
Hello @m-redding , Sorry for delay with response. I can confirm. I can't reproduce issue when running app from console (not under Visual Studio debugger).  Works for both RELEASE and DEBUG builds. But fails when run under Visual Studio.

**Comment by m-redding** [comment] 2024-12-04 16:45
@VeselovAndrey I just realized I linked the wrong issue - https://github.com/Azure/azure-sdk-for-net/issues/33636 (33636 not 3363...) sorry! 

Ok so just to confirm you're also not able to see this error outside of running the visual studio debugger? Are you seeing this same error pop up in a different context? Or did you notice this when just working in the context of this console app?

**Comment by VeselovAndrey** [comment] 2024-12-04 16:50
@m-redding 
> Ok so just to confirm you're also not able to see this error outside of running the visual studio debugger? 

Yes.

>Are you seeing this same error pop up in a different context? Or did you notice this when just working in the context of this console app?

No, only in this context

**Comment by m-redding** [comment] 2024-12-04 18:09
The outcome of the investigation in https://github.com/Azure/azure-sdk-for-net/issues/33636 was to leave the SDK as-is since this is strictly a side-effect of the debugger. Since this is the same scenario, I am marking this as addressed. Let me know if you have any follow up questions!

**Closed** 2024-12-11 22:37 UTC
Labels: Service Bus, Client, customer-reported, question, issue-addressed
