### ISSUE TITLE
[BUG] Specified File Name of MSAL Cache is Appended with a Suffix in the Latest Azure. Identity

### ISSUE THREAD

**Issue by msJinLei** [Azure/azure-sdk-for-net#38514] opened 2023-09-06 06:28 UTC
### Library name and version

Azure.Identity 1.10.0

### Describe the bug

When integrate the latest Azure.Identity,  Azure Powershell team find the file name of MSAL cache file is changed from **msal.cache** to **msal.cache.cae** or **msal.cache.nocache**, which causes the token obsolete for the existing Azure PowerShell user.
```
DEBUG: 4:13:56 PM - [SilentAuthenticator] Calling SharedTokenCacheCredential.GetTokenAsync - TenantId:'00000000-0000-0000-0000-000000000000', Scopes:'https://management.core.windows.net//.default', AuthorityHost:'https://login.microsoftonline.com/', UserId:'fake@microsoft.com'
DEBUG: SharedTokenCacheCredential.GetToken invoked. Scopes: [ https://management.core.windows.net//.default ] ParentRequestId:
DEBUG: False MSAL 4.54.1.0 MSAL.CoreCLR .NET 7.0.9 Microsoft Windows 10.0.19045 [2023-09-05 08:13:56Z - 0f25773e-494d-4d52-8a35-6bc78f805684] IsLegacyAdalCacheEnabled: yes
DEBUG: False MSAL 4.54.1.0 MSAL.CoreCLR .NET 7.0.9 Microsoft Windows 10.0.19045 [2023-09-05 08:13:56Z - 0f25773e-494d-4d52-8a35-6bc78f805684] [Region discovery] Not using a regional authority.
DEBUG: False MSAL 4.54.1.0 MSAL.CoreCLR .NET 7.0.9 Microsoft Windows 10.0.19045 [2023-09-05 08:13:56Z - 0f25773e-494d-4d52-8a35-6bc78f805684] IsLegacyAdalCacheEnabled: yes
DEBUG: False MSAL 4.54.1.0 MSAL.CoreCLR .NET 7.0.9 Microsoft Windows 10.0.19045 [2023-09-05 08:13:56Z - 0f25773e-494d-4d52-8a35-6bc78f805684] IsLegacyAdalCacheEnabled: yes
DEBUG: False MSAL 4.54.1.0 MSAL.CoreCLR .NET 7.0.9 Microsoft Windows 10.0.19045 [2023-09-05 08:13:56Z] Found 0 cache accounts and 0 broker accounts
DEBUG: False MSAL 4.54.1.0 MSAL.CoreCLR .NET 7.0.9 Microsoft Windows 10.0.19045 [2023-09-05 08:13:56Z] Returning 0 accounts
DEBUG: SharedTokenCacheCredential.GetToken was unable to retrieve an access token. Scopes: [ https://management.core.windows.net//.default ] ParentRequestId:  Exception: Azure.Identity.CredentialUnavailableException (0x80131500): SharedTokenCacheCredential authentication unavailable. No accounts were found in the cache.
```
We would like to workaround it by specifying the cache file name but found we could not specify the whole file name in the latest Azure.Identity.
### Why we need to specify the whole MSAL cache file name
- To avoid cache file migration when the default file name is changed.
- To support SSO. 
   - We are going to share the directory and file name of MSAL cache used by Azure PowerShell to other applications so that we can all use the same token cache for authentication to avoid login repeatedly (We already submit another feature request for customizing the directory). Therefore, we need to stick to one token cache file name which is approved across the teams.
### One more question on Token Cache
- Why Azure. Identity stores CAE token and non-CAE token into 2 different cache files? If they are stored to one, anything will be wrong?

Thanks
  

### Expected behavior

The generated MSAL cache file name should be the same as the `Name` in `TokenCachePersistenceOptions` in `TokenCredentialOptions`  that the API caller specified, such as "**msal.cache**"

### Actual behavior

The generated MSAL cache file name is the specified `Name` + suffix, such as "**msal.cache.cae**" or "**msal.cache.nocae**" 

### Reproduction Steps

- Set `TokenCachePersistenceOptions::Name` of `TokenCredentialOptions`
```CSharp
        var options = new InteractiveBrowserCredentialOptions()
        {
                TokenCachePersistenceOptions = new TokenCachePersistenceOptions
                {
                    UnsafeAllowUnencryptedStorage = true,
                    Name = "msal.cache"
                }
        };
```
-  Acquire token using the `TokenCredentialOptions (InteractiveBrowserCredentialOptions)` above

### Environment

Hosting platform: .net standard 2.0
IDE: Visual Studio Version 17.7.1

**Comment by jsquire** [comment] 2023-09-06 13:55
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by christothes** [comment] 2023-09-06 14:34
Hi @msJinLei This is the expected behavior of the cache files now that CAE is fully supported. When CAE support is enabled in MSAL it is done at construction time rather than request time. This means that if both CAE and non-CAE requests need to be made by the same client, two instances of MSAL are required. In addition, the cache entries may differ between CAE and non CAE tokens for the same resource. Because of this the cache files must be different.

Although the name now contains these suffixes, it should not prevent other applications from predicting the exact file path to these new cache files. Is there a scenario you have in mind where this new behavior is breaking?

**Comment by msJinLei** [comment] 2023-09-07 07:21
Hi @christothes Would there be any issue if a client application with CP1 retrieved a non-CAE token? I tried to send a CAE-token to non-CAE client application. It seemed to work.

>Is there a scenario you have in mind where this new behavior is breaking?

The trouble is Azure.Identity are expected to stick to the current implementation of token cache name, specifiedName + Suffix. If any further changes in a new version, it would be a bigger issue than current after SSO is implemented because more than one modules require to do the migration.  I consider It would be easier to let the API caller to specify the whole file name and tell them to take care of the difference between CAE and non-CAE cases.

**Comment by joshfree** [comment] 2023-09-13 20:10
Discussed in Identity office hours; we're going to "won't fix" this for now since there isn't a safe/elegant way for us to expose these capabilities in a future-proof manner.

**Closed** 2023-09-13 20:11 UTC
Labels: Client, Azure.Identity, customer-reported, question, needs-team-attention
