### ISSUE TITLE
[TABLES] GetEntity/Async should not throw exception on 404

### ISSUE THREAD

**Issue by kieronlanning** [Azure/azure-sdk-for-net#16251] opened 2020-10-25 18:22 UTC
`Azure.Data.Tables`

Is there an option to prevent `GetEntity`/ `GetEntityAsync` from throwing an exception in the case of an entity not existing.

**Comment by jsquire** [comment] 2020-10-26 12:35
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by christothes** [comment] 2020-10-26 13:20
@kieronlanning If such an option existed, could you describe how you'd see it working?

**Comment by kieronlanning** [comment] 2020-10-26 13:33
@christothes I think the best solution would be to add it to the `TableOptions` class in the constructor for the `TableServiceClient` (sorry if these aren't quite correct, I'm remembering the names from memory!).

That way the developer in question can choose the default on creation. But I do think you'd want to set it per-client, rather than per-call.

As for the `GetEntity` method itself, I'd like to see that return a `null` value with the response. So you can check the response for a 404 and return `null` accordingly. More choice. Right now I'm catching the exception and using the when clause to return null on a 404.

**Comment by christothes** [comment] 2020-10-26 14:39
@kieronlanning Thanks. Could you also describe what you'd typically do after this call? For example, is the intent to just check for existence of an entity or would you actually want something like CreateIfNotExists or DeleteIfExists?

**Comment by kieronlanning** [comment] 2020-10-26 15:14
@christothes For `GetEntity` it's always to check if it exists, but not always will we want to create or delete based on the result.

Sometimes it can form part of a `HEAD` request from the client, so it's a quick and easy way of returning some metadata to the client about the state of a resource.

Other times I might want to create it, but that's a rare case for me.

---------------------------------------------------------------------------------------------------

My context is this:

I use Table Storage as the primary store of an event store - where the events are stored in table storage as individual entities. This gives my clients transactions (multiple events, plus additional entities for management of the store) and idempotency, as well as etag based updating where appropriate. Couple that with blob storage for snapshotting and large events and Storage is a really solid platform.

That's why I'm so keen to get this Table API right. I'm close at the moment too - about 50 integration tests failing.

**Comment by christothes** [comment] 2020-10-29 14:20
@kieronlanning Generally, the guideline we follow in the newer "track 2" SDKs is to throw in scenarios like this. I realize this is a change in behavior from the older client, but it would be consistent with the behavior found in other track 2 clients.

Is there any blocking reason your code couldn't handle the exception in the scenario where `GetEntity` throws due to a 404?

**Comment by kieronlanning** [comment] 2020-10-29 14:40
@christothes That's a genuine surprise as the guidelines have always stated that throwing exceptions can be `orders of magnitude slower` (see https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/exceptions-and-performance)

But, as that guidance suggests error code shouldn't be used either - which is problematic, because HTTP responses rely on error codes.

However, the idea behind the `Try-Parse Pattern` could work in this instance?

A `TryGetEntity` and `TryGetEntityAsync` that doesn't throw by default. Would that be acceptable?

**Comment by christothes** [comment] 2020-10-29 14:48
In the general case, you are correct that exceptions should be avoided if possible for performance sensitive code paths. However, in this scenario, we've already incurred the performance hit of a network call, which is much more expensive than throwing an exception. 

For reference, here is the guideline relating to unsuccessful service method calls - https://azure.github.io/azure-sdk/dotnet_introduction.html#dotnet-errors

**Comment by christothes** [comment] 2020-11-02 19:47
@kieronlanning Thank you for the feedback on this issue. I'm going to close this as by design, as it conforms to the guidelines. Please re-open with any additional information if the current behavior would be blocking for you.

**Closed by christothes** 2020-11-02 19:47 UTC
Labels: Client, Tables, customer-reported, question

**Comment by eliashdezr** [comment] 2021-10-04 10:02
This is needed because Application Insights is full of `Failures` when Table Storage returns 404, which is wrong IMO.

**Comment by kieronlanning** [comment] 2021-10-04 11:39
@eliashdezr I'm with you on this.

It's just a PITA. Especially as much all other libraries work like this, and it seems some internal set of guidelines has forced a break from the norm.

**Comment by christothes** [comment] 2021-10-04 13:51
If you want to avoid a 404 when the resource does not exist, you could replace a call to GetEntity with a call to Query that includes the PartionKey and RowKey.

**Comment by kieronlanning** [comment] 2021-10-04 17:06
Feels very much like something the API should do.

**Comment by kieronlanning** [comment] 2021-10-11 14:32
@christothes I think that's the definition everyone here has a problem with. 404 is a perfectly valid response - it doesn't feel like an exceptional circumstance. 

Making the users of the API jump through several ill-fitting hoops to satisfy that document is the wrong way around.

I'm not sure I know of many APIs within the .NET or programming space that actively throw an exception when you try and retrieve a resource that doesn't exist. Null is fine... a response object we can check is ok. Throwing is never ok.

**Comment by christothes** [comment] 2021-10-11 14:57
Hi @kieronlanning - 
While I understand your argument, it conflicts with well established design guidelines that are not unique to this client. 

Just to summarize:
If an application is dealing with a resource that is not expected to exist or when non-existence is not an error condition, what it should be using is the `Query` method. When an application is attempting to fetch a specific resource by Id that it expects to exist, the Get operation is appropriate.

I understand if you disagree with the above statements, but the Tables client will continue to conform to the published design guidelines for Azure services.

Thanks for your passionate engagement with the SDK.

**Comment by longtimedeveloper** [comment] 2021-12-06 04:58
@eliashdezr  @kieronlanning @christothes 

The current behavior is **incorrect**.  I've NEVER used any API that throws under these circumstances.

Please reopen this issue and fix it so I don't have to write up another issue.

Thank you!

**Comment by kieronlanning** [comment] 2021-12-06 21:49
@christothes Is there any chance this can be looked at again? See my screenshot previously... this is having a financial and service impact on us now.

**Comment by christothes** [comment] 2021-12-06 21:59
Hi @kieronlanning - Sorry this is impacting you, but as I mentioned earlier, the current behavior is working according to our design guidelines. There are a handful of workarounds available if you need to avoid the 404. For example, changing the call to `Query` or `QueryAsync` and filtering on the PartitionKey and RowKey will be just as efficient, but return a successful empty result if the entity is not available.

**Comment by kieronlanning** [comment] 2021-12-06 22:03
Sure - just seems counter intuitive. Especially as a single bool on creating the client could make it work like _every other non-Azure-SDK-package_ made...

**Comment by longtimedeveloper** [comment] 2021-12-06 22:09
@christothes and @kieronlanning 

Hate to put my head into the lion's mouth...

Not sure what design guidelines you are referring to.  The book Framework Design Guidelines written by the authors of the .NET Framework frown on throwing exceptions from APIs similar to this.  This is a poor practice and shouldn't be happening.  Go and look at all Microsoft data APIs and you'll not see this.  (ADO, ADO.NET, EntityFramework, etc.)

Why not give developers a choice on the return value when a record is not found.  By default (sigh) an exception is thrown.  If the developer sets a property on the call or on the TableClient say, ReturnNullWhenRecordNotFound = false, but they set it to true, then return null instead of throwing an exception.  Many problems solved.

There are other ways this could easily be fixed.  

I STRONGLY agree with others who have stated that unnecessary exceptions logged to their Azure logs cause a lot of noise for an API that is not implemented correctly or like the rest of all data APIs I've ever used.

**Comment by longtimedeveloper** [comment] 2021-12-06 22:11
@ChrisHMSFT what are your thoughts on this?  Much appreciated, Karl Shifflett

**Comment by christothes** [comment] 2021-12-06 22:20
> Not sure what design guidelines you are referring to. 

https://azure.github.io/azure-sdk/dotnet_introduction.html#dotnet-errors

> Why not give developers a choice on the return value when a record is not found. 

Could you explain why choosing to call Query instead isn't sufficient if throwing isn't desirable when the entity doesn't exist?

**Comment by kieronlanning** [comment] 2021-12-06 22:49
I (firmly) believe it's a standards problem. Someone, somewhere has arbitrarily decided that the existing standard for _though shall not throw needlessly exceptions_ wasn't good enough. Now, for these API, everyone needs dedicated knowledge.

So while there isn't directly a problem in calling Query vs. Get, every single developer now and in the future must _understand_ that the impact of calling a `Get` rather than a `Query`. 

A fundamental, non-industry standard way of calling an API. 

Any mistake, any missed `Get` in a PR/ code review has a financial impact. Especially in high-read system.

**Comment by longtimedeveloper** [comment] 2021-12-06 22:51
@christothes these guidelines are incorrect and I'm so glad the rest of .NET does not do this.  These are in violation of the Framework Design Guidelines book that Microsoft published.  Currently in its third release.  These guidelines are not in line with any other Microsoft data API.  Whoever wrote those Azure guidelines has not read nor followed the Framework Design Guidelines book.  The good news is, this is easily correctable!

When I was a lead, I never allowed any team member to work without first reading the book Framework Design Guidelines.  I required them to bring in questions from each chapter to ask me.  All the code I've ever written follows this book.  Highly recommend this book to any .NET developer.  The authors are splendid developers and individuals.

> Could you explain why choosing to call Query instead isn't sufficient if throwing isn't desirable when the entity doesn't exist?

Honestly, that is not the point; developers should not have to ignore APIs because they have incorrect implementation.

`GetAsync` is super because it is async, and easy to call, and follows other data API for getting a single record.  (except for the exception business)

`QueryAsync` has many powerful features but is overkill to get a single record.  It returns an AsyncPageable that requires extra code to work with (you have to loop through the AsyncPageable collection), compared to the below two functions that use `Query`.  But `Query` is not async.

From a CPU performance standpoint, GetAsync probably uses fewer resources than QueryAsync.  Since Azure is a cloud service, I'm thinking SDK developers would want to ship customers the most performant code possible for common scenarios like getting a single record, correct?

**My TableService for getting single records (Get, GetAsync replacements)**

```
public T QueryFirstOrDefault<T>(Expression<Func<T, Boolean>> predicate) where T : class, ITableEntity, new() {
    return _tableClient.QueryAsync<T>(predicate).FirstOrDefault();
}

public T QuerySingleOrDefault<T>(Expression<Func<T, Boolean>> predicate) where T : class, ITableEntity, new() {
    return _tableClient.Query<T>(predicate).SingleOrDefault();
}
```

You can see I've worked around the poor design of Get and GetAsync.  But these APIs should be fixed.

[Framework Design Guidelines 3rd Edition on Amazon](https://www.amazon.com/Framework-Design-Guidelines-Conventions-Addison-Wesley/dp/0135896460/)

BTW:  I'm very passionate about code, but hope I'm not coming off as disrestful.  If so, I apologize in advance.  Best regards, Karl

**Comment by ChrisHMSFT** [comment] 2021-12-06 23:17
@longtimedeveloper 
> @ChrisHMSFT what are your thoughts on this? Much appreciated, Karl Shifflett

I think I'm the wrong Chris?

**Comment by christothes** [comment] 2021-12-06 23:18
> @christothes these guidelines are incorrect and I'm so glad the rest of .NET does not do this. These are in violation of the Framework Design Guidelines book that Microsoft published. Currently in its third release. These guidelines are not in line with any other Microsoft data API. Whoever wrote those Azure guidelines has not read nor followed the Framework Design Guidelines book. The good news is, this is easily correctable!

Funny you should mention this book - The guidelines I linked to above are based on Framework Design Guidelines 😄.  Please see chapter 7 titled "Exceptions". The chapter starts out with: "Exception handling has many advantages over return-value-based error reporting. Good framework design helps the application realize the benefits of exceptions." 

Please also see this guideline for .NET API design https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/exception-throwing
![image](https://user-images.githubusercontent.com/1279263/144937990-1687c89c-d5f2-4a4f-9dae-b6a872070879.png)


> `QueryAsync` has many powerful features but is overkill to get a single record. It returns an AsyncPageable that requires extra code to work with (you have to loop through the AsyncPageable collection), compared to the below two functions that use `Query`. But `Query` is not async.
> 
> From a CPU performance standpoint, GetAsync probably uses fewer resources than QueryAsync. Since Azure is a cloud service, I'm thinking SDK developers would want to ship customers the most performant code possible for common scenarios like getting a single record, correct?

I would be surprised if there is a significant difference in performance for the success case of either.

Thanks again for your feedback.

**Comment by longtimedeveloper** [comment] 2021-12-06 23:33
@christothes I still strongly disagree.  Not with your above text, but on the premise that a record not found, should cause an exception. 

A record not found is a condition or state, not an error.  It does not warrant being elevated to an exception.  This is a misuse of exceptions.

We can do this all day long, but I can see as the author of the guidelines you've made up your mind.

I recommend you look at all other data APIs, can you find a single data API that throws an exception when a record can't be found?  If not, you should correct your design guidelines to reflect the rest of the world's view on this matter.  If you find one, please send me a link.

**This problem all boils down to deciding if a record not found operation is an error or just a simple state.**  All APIs I've ever used handle this as a state and not a runtime error.

**Comment by kieronlanning** [comment] 2021-12-06 23:42
To voice what @longtimedeveloper has said, it does feel very much like the decision has been made, and actually, if that's the default then it's likely more dangerous to change it, regardless of the discussion here and the merits of either side (you have your hill, we have ours #amirght).

However... what we're (sorry if I'm lumping anyone else into this) proposing is a middle-ground... an option in the client that allows developers to choose...

> Throw exceptions on null for get or not.

It feels like a low impact compromise, and it solves a variety of problems for everyone who is used to non-throwing APIs for get-based operations.

Failing that, a GetOrDefault(Async) much like LINQs First/ SingleOrDefault that **doesn't throw internally** (for high-performance scenarios).

**Comment by longtimedeveloper** [comment] 2021-12-07 00:02
@christothes one other point of pondering, API consistency.

If `Query `doesn't throw when no records are found, then why should Get throw if no records are found.  The two should be consistent.  Obviously, a query that returns no records is a condition or state, not a runtime error.  The same should apply to `Get `and `GetAsync`.

Best regards, Karl

**Comment by longtimedeveloper** [comment] 2021-12-07 00:16
@christothes I just read the docs for the older Azure Table APIs to see if they threw an exception when the record was not found.  The below docs do not state they throw when the record was not found.

[https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.cosmos.table.tablebatchoperation.retrieve?view=azure-dotnet](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.cosmos.table.tablebatchoperation.retrieve?view=azure-dotnet)

Below are from an older Azure app TableService I wrote that gets a single record in two different ways.  This production code never threw an exception for over 4 years even when the record was not found.

Hope this helps, Karl

```
public async Task<T> GetAsync<T>(String partitionKey, String rowKey) where T : class, ITableEntity, new() {
    var retrieveOperation = TableOperation.Retrieve<T>(partitionKey, rowKey);
    var result = await this.CloudTable.ExecuteAsync(retrieveOperation).ConfigureAwait(false);
    this.LastHttpStatusCode = result.HttpStatusCode;
    return result.Result as T;
}

public async Task<T> GetAsync<T>(String partitionKey, String propertyName, String propertyValue) where T : class, ITableEntity, new() {
    var tableQuery = CreateTableQuery<T>(partitionKey, propertyName, propertyValue);
    TableContinuationToken token = null;
    var results = await this.CloudTable.ExecuteQuerySegmentedAsync<T>(tableQuery, token);

    if (results.Results.Count == 1) {
        this.LastHttpStatusCode = StatusCodes.Status200OK;
        return results.Results[0] as T;
    }
    this.LastHttpStatusCode = StatusCodes.Status404NotFound;
    return null;
}
```

**Comment by christothes** [comment] 2021-12-07 00:35
> @christothes one other point of pondering, API consistency.
> 
> If `Query `doesn't throw when no records are found, then why should Get throw if no records are found? The two should be consistent. Obviously, a query that returns no records is a condition or state, not a runtime error. The same should apply to `Get `and `GetAsync`.
> 
> Best regards, Karl

The semantics are different between the two calls. `Query` is asking to return any resources that match the provided filter. One possible outcome is that non match, but that is not an error condition. `GetEntity` is a resource request. It is requesting to fetch a specific known resource by its globally unique identifier. If that is not found, it is an error and a 404 is returned by the service.

**Comment by longtimedeveloper** [comment] 2021-12-07 00:37
@christothes guess we'll have to agree to disagree...

**Comment by longtimedeveloper** [comment] 2021-12-07 00:52
@christothes you've not addressed any comments on this API being different than all other APIs including the previous Azure Table Storage SDK.

Are the rest of the world and all other APIs incorrect with respect to an operation that gets a single record?

**Comment by AlexGhiondea** [comment] 2021-12-07 01:09
Adding @KrzysztofCwalina to this thread as he defined the .NET Azure guidelines @christothes was referring to (and also wrote the FDG). 

@longtimedeveloper there are several APIs in the .NET Framework that throw when a record can't be found. An example of this is the Dictionary look-up which will throw if the key is not found. 

I agree with you and @kieronlanning that there are scenarios where not throwing an exception (even if the service returns 404) might be desirable. We can look into whether or not we can have a method similar to `GetEntityIfExists` that will **not** throw even when the service is returning 404.

However, even if we make this change, it will be a specific case for this library and not a general change in the guidelines as, in general, we throw and exception when we receive a 404 response from the service.

**Comment by longtimedeveloper** [comment] 2021-12-07 01:33
@AlexGhiondea Thank you! 
@KrzysztofCwalina hope all is well with you and your family, been a long time!  Thank you for continuing to update FDG.

This issue boils down to public data API consistency and consistency with data APIs (ADO, ADO.NET, Entity Framework, etc.) that developers have used for years.  Developers don't expect an exception from a data API because the record is not found.  Doesn't happen.

This smells like a leaky abstraction where you're leaking your internal states out into your public API.  Internally you got a 404 from some service, but the public data API should not have to be a victim to internal code.  

> An example of this is the Dictionary look-up which will throw if the key is not found.

Yes, but there are methods you can use like `TryGetValue` that mitigate getting an exception.

If you're insisting on exceptions, why not provide `TryGet` and `TryGetAsync `or similar as you suggested?

The victims of these exceptions are the Azure Logs being littered with noisy useless exceptions, performance, and having to use the `Query `API methods instead of the `Get `API methods.  Forcing developers to use `Query `so they can keep their Azure logs clean seems unnecessary.

Yes, understand this `TryGet` would only be implemented in this library.

If you do this, think of the performance gains and clean Azure logs!

Thank you, best regards, Karl

**Comment by AlexGhiondea** [comment] 2021-12-07 01:53
@longtimedeveloper I don't think the 404 is an internal state though. That 404 is not coming from the library, but from the service. For some customers, it is important to know that an entity they are trying to get does not exist. 

The `TryGet*` pattern is something that we have thought about, however it does not work with async methods as `out` parameters are not supported.

While the logs, in your situation, might be littered with exceptions, that is not necessarily true for all applications. Applications that don't use the `GetEntity` method the same way you do will not have the issue with the logs showing the real exceptions coming from the service 🙂.

And while exceptions are more expensive due to the stack walk they trigger, that is usually only an issue in tight loops. I'd be interested see a perf trace of the scenario that shows significant real world slowdown caused by exceptions!

The `Query` method in this case seems to have a very similar outcome to the proposed `GetEntityIfExists` method and you can use it for now to avoid the exception.

**Comment by longtimedeveloper** [comment] 2021-12-07 02:00
@AlexGhiondea how do you reply to the question, "why is this API different from ADO, ADO.NET, EntityFramework, and the previous APIs for Table Storage?"

This API is the only one throwing on a get single record request.

**Comment by AlexGhiondea** [comment] 2021-12-07 02:22
The Azure Table APIs were designed to follow the Azure SDK Guidelines. According to those guidelines, anytime a service method returns 404, an exception will be thrown.

We are _considering_ adding a method (something like `GetEntityIfExists`) that will not throw on a 404. There are other options we are looking into as well for how to best expose such a functionality in the library.

Thank you for your feedback!

**Comment by longtimedeveloper** [comment] 2021-12-07 20:58
@KrzysztofCwalina thank you for a very quick response!

Your suggestion of adding additional response properties to the `Response<T> Class` so that any internal exception information can be passed back is super.

**Get and GetAsync Question**:  If you added the exception information, would this cause the Azure logs to be impacted if the `Get `or `GetAsync` resulted in an internal 404?  I wouldn't think so because developer code would not have to catch the exceptions anymore like we had to today.  If the internal Get or GetAsyc code does not cause log entries this would rock!  

I understand that the call to `Get `or `GetAsync` would require developers to opt in to the new behavior by passing an options argument.  This would be awesome and would not be a breaking change.

Love the richer `Response<T> ` object idea!!

Thank you for your time and consideration in making this warmly welcomed change to the APIs!

Best to you always, Karl

**Comment by KrzysztofCwalina** [comment] 2021-12-07 21:10
@longtimedeveloper, if you opt-into `ResponseStatusOption.NoThrow` all error logging will be suppressed, i.e. we will treat 404 as a success. 

+ @annelo-msft and @tg-msft who are working on related features.

**Comment by tg-msft** [comment] 2021-12-07 21:20
I'm tracking some of these at https://github.com/Azure/azure-sdk-for-net/issues/25626.  @christothes - consider adding `GetEntity` to the list.

**Comment by longtimedeveloper** [comment] 2021-12-07 21:28
@KrzysztofCwalina splendid.

@tg-msft outstanding.

@christothes can your please add both `GetEntity ` and `GetEntityAsync`?  Thank you!!

Very much looking forward to these outstanding enhancements!

**Comment by kieronlanning** [comment] 2021-12-08 08:11
This is outstanding. Thanks to everyone involved!

**Comment by Wema** [comment] 2022-11-07 16:53
Very nice indeed, any idea when this feature will come out of preview?

**Comment by christothes** [comment] 2022-11-07 16:54
Should be this week.
