### ISSUE TITLE
Samples for version 11.3 need updates

### ISSUE THREAD

**Issue by ThomasPe** [Azure/azure-sdk-for-net#25988] opened 2021-12-17 15:41 UTC
While the title says "Azure Cognitive Search client library for .NET - **Version 11.3.0**" the samples still mention  `--version 11.2.0-beta.1` and there seem to be some API changes as the provided sample code does not work with 11.3, for example the query sample:

```
SearchResults<Hotel> response = client.Search<Hotel>("luxury");
foreach (SearchResult<Hotel> result in response.GetResults())
{
    Hotel doc = result.Document;
    Console.WriteLine($"{doc.Id}: {doc.Name}");
}
```
as `client.Search<Hotel>("luxury")` does return an object of type `Azure.Response` and not directly `SearchResults<Hotel>`.

I'd be happy to contribute an update but it seems this doc is not open source, right?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 458cbf54-fea1-22a5-f289-318cf0d1e345
* Version Independent ID: e7c2e52e-959e-4857-0695-e503a12b6217
* Content: [Azure Cognitive Search client library for .NET - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/overview/azure/search.documents-readme)
* Content Source: [api/overview/azure/search.documents-readme.md](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/api/overview/azure/search.documents-readme.md)
* Service: **search**
* Product: **azure**
* Technology: **azure**
* GitHub Login: @ramya-rao-a
* Microsoft Alias: **ramyar**

**Comment by pallavit** [comment] 2022-06-15 18:25
/cc: @ShivangiReja our last GA release had this issue unfortunately. This either needs manually editing the docs or waiting until the next GA to self correct.

**Comment by ShivangiReja** [comment] 2022-07-06 20:09
@ThomasPe Thank you for reaching out and we regret that you're experiencing difficulties. 

For beta versions, readme doc is updated [here](https://github.com/Azure/azure-docs-sdk-dotnet/blob/main/api/overview/azure/search.documents-readme-pre.md) which is up to date with [Search SDK Readme.md](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/search/Azure.Search.Documents/README.md).

For GA, readme doc is updated [here](https://github.com/Azure/azure-docs-sdk-dotnet/blob/main/api/overview/azure/search.documents-readme.md) which updates https://docs.microsoft.com/en-us/dotnet/api/overview/azure/search.documents-readme doc.

As @pallavit mentioned, our last GA release had this issue unfortunately. [This](https://docs.microsoft.com/en-us/dotnet/api/overview/azure/search.documents-readme) doc will be fixed in next GA release.

**Comment by ShivangiReja** [comment] 2022-07-06 22:11
@ThomasPe Thank you for reaching out and we regret that you're experiencing difficulties. 

For beta versions, readme doc is updated [here](https://github.com/Azure/azure-docs-sdk-dotnet/blob/main/api/overview/azure/search.documents-readme-pre.md) which is up to date with [Search SDK Readme.md](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/search/Azure.Search.Documents/README.md).

For GA, readme doc is updated [here](https://github.com/Azure/azure-docs-sdk-dotnet/blob/main/api/overview/azure/search.documents-readme.md) which updates https://docs.microsoft.com/en-us/dotnet/api/overview/azure/search.documents-readme doc. The issue is that for .NET, we can only refer to a [single readme](https://docs.microsoft.com/en-us/dotnet/api/overview/azure/search.documents-readme) at a given time. This is a pretty well known limitation, and @danieljurek is working on with this work item https://github.com/Azure/azure-sdk/issues/1857.

As @pallavit mentioned, our last GA release had this issue unfortunately. [This](https://docs.microsoft.com/en-us/dotnet/api/overview/azure/search.documents-readme) doc will be fixed in next GA release.

**Comment by ShivangiReja** [comment] 2022-09-12 19:09
Search GA version has been released https://www.nuget.org/packages/Azure.Search.Documents/11.4.0.

Closing this issue as the readme document has been fixed https://docs.microsoft.com/en-us/dotnet/api/overview/azure/search.documents-readme.

**Closed by ShivangiReja** 2022-09-12 19:09 UTC
Labels: Search, Client, customer-reported, question, Docs, needs-team-attention
