### ISSUE TITLE
[BUG] Azure.Search.Documents creates invalid request payload for Semantic searches

### ISSUE THREAD

**Issue by kikaragyozov** [Azure/azure-sdk-for-net#37164] opened 2023-06-22 11:24 UTC
### Library name and version

Azure.Search.Documents 11.5.0-beta.2

### Describe the bug

When passing QueryCaptionsType.None, it gets serialized down to `none|highlight-false`/`none|highlight-true`, which is an invalid response to the service. `none` does not accept any highlight parameters.

Mentioned in: https://github.com/Azure-Samples/azure-search-openai-demo-csharp/issues/113

### Expected behavior

The SDK to properly serialize the value in JSON.

### Actual behavior

The SDK crafts an invalid HTTP request payload which results in a 400 BadRequest response from the service.

### Reproduction Steps

Create a semantic request with options for captioning set to None, for example:

```
new SearchOptions
            {
                Filter = filter,
                QueryType = SearchQueryType.Semantic,
                QueryLanguage = "en-us",
                QuerySpeller = "lexicon",
                SemanticConfigurationName = "default",
                Size = top,
                QueryCaption = QueryCaptionType.None,
                QueryCaptionHighlightEnabled = false
            }
```

It will fail.

### Environment

Off-topic: If you could please link the source of where the exact JSON serialization was done? I tracked the code by debugging into it, but I never found the contract responsible for the custom struct serialization.

Thanks.

**Comment by jsquire** [comment] 2023-06-22 14:03
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by ShivangiReja** [comment] 2023-06-22 19:27
@kikaragyozov, I apologize for any inconvenience caused by this issue, and I want to thank you for your contribution in resolving it. I have added a few comments to your [PR](https://github.com/Azure/azure-sdk-for-net/pull/37165), so please take a moment to review them.

>Off-topic: If you could please link the source of where the exact JSON serialization was done? I tracked the code by debugging into it, but I never found the contract responsible for the custom struct serialization.

The serialization logic can be found [here](https://github.com/Azure/azure-sdk-for-net/blob/b31863abb23140c0ffd6145900cbc11fa4bdfa6c/sdk/search/Azure.Search.Documents/src/Generated/Models/SearchOptions.Serialization.cs#L167-L171).

**Closed** 2023-07-10 16:47 UTC
Labels: Search, Client, customer-reported, question, needs-team-attention
