### ISSUE TITLE
Why Azure storage SDK 4.3 does not work with 5.6.3

### ISSUE THREAD

**Issue by rshirani** [Azure/azure-sdk-for-net#3626] opened 2017-08-25 07:44 UTC
I am in a situation that I do not want to use assembly binding. My question is why having storage sdk 4.3 does not work with Microsoft.Data.OData 5.6.3.0??

I get the following exception when I have OData 5.6.3.

[Exception: Microsoft.WindowsAzure.Storage.StorageException: Could not load file or assembly 'Microsoft.Data.OData, Version=5.6.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies.

In https://www.nuget.org/packages/WindowsAzure.Storage/4.3.0, it mentions Microsoft.Data.OData (>= 5.6.2).

Why does not this work for me?

I have seen a couple of other pages with this question, but none of them I see talk about the root cause but they only use assembly binding to handle this situation.

https://github.com/Azure/azure-storage-net/issues/125

**Comment by shahabhijeet** [comment] 2017-08-25 16:59
@blueww can you direct to the right folks and get back to customer about the reported error.

**Comment by blueww** [comment] 2017-08-28 02:27
@shahabhijeet , the issue should be owned by Michael Roberson and his team, could you please assign to him?
Thanks!

**Comment by blueww** [comment] 2018-05-24 02:16
@rshirani 

Not sure if you have file a new issue for https://github.com/Azure/azure-storage-net, since the issue is for the SDK of that repo.

**Comment by blueww** [comment] 2018-05-24 02:17
@shahabhijeet , would you please help to close the issue as it's not for Azure Management SDK, but for the Azure Storage SDK. And customer has not responds for a long time.

**Comment by dsgouda** [comment] 2019-04-24 21:38
Closing per @blueww 's comments

**Closed by dsgouda** 2019-04-24 21:38 UTC
Labels: Service Attention, Storage
