### ISSUE TITLE
[BUG] The operation_Name field is not getting populated property.

### ISSUE THREAD

**Issue by v-iyamauchi** [Azure/azure-sdk-for-net#41946] opened 2024-02-13 19:59 UTC
### Library name and version

Azure.Monitor.OpenTelemetry.AspNetCore 1.1.0

### Describe the bug

As we are migrating our telemetry/logging to using OpenTelemetry, we've noticed some inconsistencies between the Distro API and the Application Insights API (Microsoft.ApplicationInsights.AspNetCore 2.22.0). Some are trivial while other are not. A difference in the "operation_Name" field is significant and undesirable.

### Expected behavior

The operation_Name field should have the following format, "[method] [controller]/[action]". (e.g. "POST Fhir/Create [typeParameter]")

### Actual behavior

The operation_Name field has the following format, "[method] [route constraint template]". (e.g. "POST {typeParameter:fhirResource}")

### Reproduction Steps

Unfortunately, the easiest way to repro is to run our test locally on your dev box. I believe that the issue is reproducible with an Asp.Net Core service that uses a custom route constraint.  

### Environment

OS: Windows 11
.NET SDK: 8.0.101
VS 2022: 17.8.5

**Comment by v-iyamauchi** [comment] 2024-02-13 20:05
Also, please let us know if we can overwrite the "operation_Name" field in the requests table by implementing an enricher for AspNetCoreTraceInstrumentationOptions or/and OpenTelemetryLoggerOptions.

**Comment by TimothyMothra** [comment] 2024-02-14 18:18
This is a duplicate of #41650

There's a known issue in the OpenTelemetry.Instrumentation.AspNetCore library: https://github.com/open-telemetry/opentelemetry-dotnet/issues/5056. We're working with the other teams to get this addressed.


> we've noticed some inconsistencies between the Distro API and the Application Insights API

Please do open issues for any other inconsistencies. We're working to resolve feature gaps.

**Closed by TimothyMothra** 2024-02-14 18:18 UTC
Labels: Service Attention, customer-reported, question, needs-team-attention, Monitor - Distro

**Comment by v-iyamauchi** [comment] 2024-02-14 20:48
@TimothyMothra , could you please let me know if there is a way to overwrite a value of the "operation_Name" column? When I tried with an enricher, the "operation_Name" value added by the enricher appears under the "customDimensions" column. If we can overwrite the "operation_Name" column, that would suffice our need temporarily. Thank you.
