### ISSUE TITLE
Create route table with multiple routes throws ArgumentException

### ISSUE THREAD

**Issue by jefflill** [Azure/azure-sdk-for-net#3171] opened 2017-05-05 15:27 UTC
The Fluent API incorrectly throws:

&nbsp;&nbsp;&nbsp;&nbsp;`ArgumentException("An` item with the same key has already been added. Key: routes")`

when I attempt to create a route table with more than one route.  The interesting thing is that the table is actually created in Azure and it functions correctly.  I'm guessing that the problem is in the code where the Fluent API constructs the strongly type route table object to be returned.

Here's the repro code:

````
using System;

using Microsoft.Azure.Management.Fluent;
using Microsoft.Azure.Management.ResourceManager.Fluent;
using Microsoft.Azure.Management.ResourceManager.Fluent.Authentication;

namespace AzureMultpleRoutes
{
    class Program
    {
        static void Main(string[] args)
        {
            // NOTE: You'll need to replace these with your own Azure credentials.

            const string clientId       = "****";
            const string clientSecret   = "****";
            const string tenantId       = "****";
            const string subscriptionId = "****";

            const string resourceGroup  = "azure-bug";
            const string region         = "westus2";

            // Login the API.

            var azureCredentials =
                new AzureCredentials(
                    new ServicePrincipalLoginInformation()
                    {
                        ClientId     = clientId,
                        ClientSecret = clientSecret
                    },
                tenantId,
                AzureEnvironment.AzureGlobalCloud);

            var azure = Azure.Configure()
                .Authenticate(azureCredentials)
                .WithSubscription(subscriptionId);

            // Create the resource group if necessary.

            if (!azure.ResourceGroups.CheckExistence(resourceGroup))
            {
                azure.ResourceGroups
                    .Define(resourceGroup)
                    .WithRegion(region)
                    .Create();
            }

            // Create a routing table with two routes.
            //
            // Note that this throws:
            //
            //      ArgumentException("An item with the same key has already been added. Key: routes").
            //
            // but the route table was actually created correctly.

            var vpnRoutesDef = azure.Networks.Manager.RouteTables
                .Define("routes")
                .WithRegion(region)
                .WithExistingResourceGroup(resourceGroup)
                .DefineRoute("route-1")
                    .WithDestinationAddressPrefix("10.0.0.0/24")
                    .WithNextHopToVirtualAppliance("10.1.0.4")
                    .Attach()
                .DefineRoute("route-2")
                    .WithDestinationAddressPrefix("10.0.1.0/24")
                    .WithNextHopToVirtualAppliance("10.1.0.5")
                    .Attach()
                .Create();
        }
    }
}
````

**Comment by martinsawicki** [comment] 2017-05-08 21:51
root cause: it's a combo of two issues:

a) it looks like inside the impls, the semantics of `dictionary.Item[key]=value` was intended, but `dictionary.Add(key, value)` was used - an incorrect port of the Java SDK impl where the equivalent `map.add(key, value)` has the semantics of the former, but the appearance of the latter.  The creation works correctly on the Azure side, the error is getting hit when the returned object from Azure is being processed in the refresh logic.

b) ...but there is also a plain typo in that refresh logic - the name of the parent route table is used as the key, but it should be the route's name. It looks like the typo was introduced while porting from Java, as the Java side has this done correctly.

In any case, the client side fix is trivial. It's [PR'd](https://github.com/Azure/azure-sdk-for-net/pull/3183) now. It will be included in the next release, by early June.

(But I also see a number of places in the SDK where Java's `map.add()` got converted to `dictionary.Add()` which is similarly not quite right and may result in bogus exceptions, so I'll try to scrub them all later.)

**Comment by hovsepm** [comment] 2017-05-10 18:01
Fixed and merged. Will be available in the next release.

**Closed by hovsepm** 2017-05-10 18:01 UTC
Labels: Fluent
