### ISSUE TITLE
[BUG] VisualStudioCredential taking upwards of 10 seconds to retrieve access tokens

### ISSUE THREAD

**Issue by jbelaire-treeline** [Azure/azure-sdk-for-net#38014] opened 2023-08-03 23:34 UTC
### Library name and version

Azure.Identity 1.8

### Describe the bug

When running our .NET Framework 4.8 Web Application locally using Microsoft Data SqlClient 5.0.1 and Active Directory Default authentication, we are seeing frequent "a task was canceled" exceptions with SQL Server database connections. These task exceptions appear to be caused by very slow retrieval of access tokens via VisualStudioCredential.

I stepped through VisualStudioCredential, and it appears access tokens are retrieved via Microsoft.Asal.TokenService.exe using the following command line:
```
.\Microsoft.Asal.TokenService.exe --resource “https://database.windows.net/” --serviceHubConfig “C:\Program Files\Microsoft Visual Studio\2022\Preview\Common7\servicehub.config.json” --verbose --tenant {redacted}
```
When I run this command manually, it takes upwards of 10 seconds to return an access token, which makes local development with Active Directory Default impossible for us.

Here is an example stack trace of the issue we are experiencing:
```
Microsoft.Data.SqlClient.SqlException
HResult=0x80131904
Message=A task was canceled.
Source=Framework Microsoft SqlClient Data Provider
StackTrace:
at Microsoft.Data.SqlClient.SqlInternalConnectionTds.GetFedAuthToken(SqlFedAuthInfo fedAuthInfo)
at Microsoft.Data.SqlClient.SqlInternalConnectionTds.OnFedAuthInfo(SqlFedAuthInfo fedAuthInfo)
at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
at Microsoft.Data.SqlClient.TdsParser.Run(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj)
at Microsoft.Data.SqlClient.SqlInternalConnectionTds.CompleteLogin(Boolean enlistOK)
at Microsoft.Data.SqlClient.SqlInternalConnectionTds.AttemptOneLogin(ServerInfo serverInfo, String newPassword, SecureString newSecurePassword, Boolean ignoreSniOpenTimeout, TimeoutTimer timeout, Boolean withFailover, Boolean isFirstTransparentAttempt, Boolean disableTnir)
at Microsoft.Data.SqlClient.SqlInternalConnectionTds.LoginNoFailover(ServerInfo serverInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString connectionOptions, SqlCredential credential, TimeoutTimer timeout)
at Microsoft.Data.SqlClient.SqlInternalConnectionTds.OpenLoginEnlist(TimeoutTimer timeout, SqlConnectionString connectionOptions, SqlCredential credential, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance)
at Microsoft.Data.SqlClient.SqlInternalConnectionTds…ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, ServerCertificateValidationCallback serverCallback, ClientCertificateRetrievalCallback clientCallback, DbConnectionPool pool, String accessToken, SqlClientOriginalNetworkAddressInfo originalNetworkAddressInfo, Boolean applyTransientFaultHandling)
at Microsoft.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
at Microsoft.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
at Microsoft.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
at Microsoft.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
at Microsoft.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
at Microsoft.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection) at Microsoft.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
at Microsoft.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource1 retry, DbConnectionOptions userOptions) at Microsoft.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource1 retry)
at Microsoft.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource1 retry, SqlConnectionOverrides overrides) at Microsoft.Data.SqlClient.SqlConnection.Open(SqlConnectionOverrides overrides) at TreelineUtilityLibrary.Database.DatabaseManager.GetDataInternal(String sql, String connectionString, IDictionary2 params, IEnumerable`1 outputParams, Int32 timeout, Boolean doReadOnly) in C:\Users\jbelaire\source\repos\AboveTheTreeline.release\treelineutilitylibrary\Database\DatabaseManager.vb:line 745

This exception was originally thrown at this call stack:
Azure.Identity.VisualStudioCredential.RunProcessesAsync(System.Collections.Generic.List<System.Diagnostics.ProcessStartInfo>, bool, System.Threading.CancellationToken)
Azure.Identity.VisualStudioCredential.GetTokenImplAsync(Azure.Core.TokenRequestContext, bool, System.Threading.CancellationToken)
Azure.Identity.CredentialDiagnosticScope.FailWrapAndThrow(System.Exception, string)
Azure.Identity.VisualStudioCredential.GetTokenImplAsync(Azure.Core.TokenRequestContext, bool, System.Threading.CancellationToken)
Azure.Identity.VisualStudioCredential.GetTokenAsync(Azure.Core.TokenRequestContext, System.Threading.CancellationToken)
Azure.Identity.DefaultAzureCredential.GetTokenFromSourcesAsync(Azure.Core.TokenCredential[], Azure.Core.TokenRequestContext, bool, System.Threading.CancellationToken)
Azure.Identity.DefaultAzureCredential.GetTokenImplAsync(bool, Azure.Core.TokenRequestContext, System.Threading.CancellationToken)
Azure.Identity.CredentialDiagnosticScope.FailWrapAndThrow(System.Exception, string)
Azure.Identity.DefaultAzureCredential.GetTokenImplAsync(bool, Azure.Core.TokenRequestContext, System.Threading.CancellationToken)
Azure.Identity.DefaultAzureCredential.GetTokenAsync(Azure.Core.TokenRequestContext, System.Threading.CancellationToken)
…
[Call Stack Truncated]

Inner Exception 1:
TaskCanceledException: A task was canceled.
```

I raised this issue on the Visual Studio Developer Community forums, but I'm not getting any traction there:
https://developercommunity.visualstudio.com/t/Version-1770-Preview-20---WebApp-unab/10409641?port=1025&fsid=3b212c91-74c7-451e-966c-40aed6e28164&scope=follow&sort=recent&ref=native&refTime=1691104580788&refUserId=ca8acc17-6663-46d8-8c13-bc2c608a8318

### Expected behavior

Ideally retrieving access tokens via VisualStudioCredential should only take a few milliseconds.

### Actual behavior

Retreival of access tokens via VisualStudioCredential is taking upwards of 10 seconds.

### Reproduction Steps

I'm not sure if this is a code issue per se, or an environmental/Azure/Visual Studio issue.

### Environment

.NET  Framework 4.8.0
Microsoft Data SqlClient 5.0.1
Azure.Identity 1.8
Version 17.7.0 Preview 6.0

**Comment by jsquire** [comment] 2023-08-04 14:35
Hi @jbelaire-treeline.   Thank you for reaching out and we regret that you're experiencing difficulties.  Based on your insights around direct calls to `Microsoft.Asal.TokenService.exe` taking 10 seconds, we agree that appears to be the root cause of the latency in `VisualStudioCredential` that you're seeing.  We're unable to reproduce this locally or in our test infrastructure; it appears likely that this is related to your local environment or Visual Studio version.

Unfortunately, `Microsoft.Asal.TokenService.exe` is a part of Visual Studio and not something that `Azure.Identity` has any influence over nor insight into.  There's not much help that the Azure SDK for .NET can provide - we'll need to bring this to the attention of the Visual Studio team.  Since Visual Studio is not an open-source product, we're unable to transfer this issue directly on your behalf.  

Your best path forward would be to [Report a problem with Visual Studio](https://learn.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2022).  That will ensure the folks best able to assist are engaged to do so.

I'm going to close this out; if I've misunderstood what you're describing, please let us know in a comment and we'd be happy to assist as we're able.

**Closed by jsquire** 2023-08-04 14:35 UTC
Labels: Client, Azure.Identity, customer-reported, question, needs-team-triage
