### ISSUE TITLE
[BUG] Deadlock in AzureCliCredential when executed concurrently.

### ISSUE THREAD

**Issue by schaabs** [Azure/azure-sdk-for-net#22314] opened 2021-06-29 23:59 UTC
This issue and the following repro was reported by @NeilMacMullen, and appears to be a different deadlock than that described in #14691, as it only reproduces when multiple requests are made in parallels.

Repro:

```c#
  public class SimpleKeyVaultAccess
  {
      public static readonly SimpleKeyVaultAccess Primary = new(KeyVaultNames.SensizePrimary);
      private readonly string _vaultName;
      private SimpleKeyVaultAccess(string vaultName) => _vaultName = vaultName;
      public async Task<string> FetchSecret(string secretName)
      {
          var vault = new Uri(_vaultName);
          var client = new SecretClient(vault,
              new ChainedTokenCredential(new ManagedIdentityCredential(), new AzureCliCredential()));
          var response = await client.GetSecretAsync(secretName);
          return response.Value.Value;
      }
      public async Task DemonstrateTimeout(int n)
      {
          Console.WriteLine($"Running with {n} parallel tasks..");
          var tasks = Enumerable.Range(0, n).Select(_ => FetchSecret(SecretNames.TablesAccount)).ToArray();
          var all = await Task.WhenAll(tasks);
          Console.WriteLine("Succeeded");
      }
  }


  await SimpleKeyVaultAccess.Primary.DemonstrateTimeout(50); 
 ```
 
The code is called from a .net5 console app running on my dev PC in the UK.  The key vault itself is in the West US2 region (so network latency may be relevant).  It reliably throws
 
Azure.Identity.AuthenticationFailedException: The ChainedTokenCredential failed due to an unhandled exception: Azure CLI authentication timed out.
 
after approximately 25 seconds

**Comment by christothes** [comment] 2021-11-01 22:21
I am not able to repro this. Duplicate of #23135

**Closed by christothes** 2021-11-01 22:21 UTC
Labels: Client, Azure.Identity, bug, needs-team-attention
