### ISSUE TITLE
Adopt Azure.Core pipeline strategy for running dependencies

### ISSUE THREAD

**Issue by m-nash** [Azure/azure-sdk-for-net#27703] opened 2022-03-22 22:50 UTC
### Library name

Azure.ResourceManager

### Please describe the feature.

Today each mgmt RP has a path trigger to run when the Azure.ResourceManager package is changed, today this results in 300 jobs kicked off for a PR and will grow to roughly 1500 over time which is not scalable.  Instead for the short term we want to use a similiar mechanism to core ci.yml that sets the service directory to `*` but instead we can set it to something like `*\*ResourceManager*` to run all mgmt plane RPs and remove the path triggers.

In the long term the engineering team will be implementing this https://github.com/Azure/azure-sdk-tools/issues/2951 which will parallelize this to make it more efficient.

**Comment by sima-zhu** [comment] 2022-08-18 19:02
Here is the [commit ](https://github.com/sima-zhu/azure-sdk-for-net/commit/e7fb70bbb72954d976729ce7ac1cfe8b5263c2f2)of my changes. No PR as it will trigger the build storm.

Testing pipeline: https://dev.azure.com/azure-sdk/public/_build/results?buildId=1791504&view=logs&j=8576268d-c0c9-5a70-3189-a330b2678ef6&t=4ae70021-1290-5460-073e-909176275fa1

@m-nash @ArthurMa1978 Could you help merge the commit?

**Comment by sima-zhu** [comment] 2022-08-24 23:20
Here is the PR to install azurite: https://github.com/Azure/azure-sdk-for-net/pull/30676

All commits and PR get checked in. The issue is resolved. 
Please feel free to reopen for anything unresolved.

**Closed by sima-zhu** 2022-08-24 23:20 UTC
Labels: Mgmt-EngSys, Mgmt, EngSys
