### ISSUE TITLE
[BUG] - AAD Guest account with DeveloperTool=VisualStudio - Login failed for user '<token-identified principal>' (Microsoft.Azure.Services.AppAuthentication using AzureServiceTokenProvider )

### ISSUE THREAD

**Issue by felickz** [Azure/azure-sdk-for-net#12773] opened 2020-06-15 16:16 UTC
**Describe the bug**
When using AAD Guest Account (home tenant different then azure subscription tenant) to authenticate to SQL Server using the default constructor **AzureServiceTokenProvider()** or  **AzureServiceTokenProvider("RunAs=Developer; DeveloperTool=VisualStudio")** getting error:
`Login failed for user '<token-identified principal>'.`

When overriding AzureServiceTokenProvider connection string to use **RunAs=Developer; DeveloperTool=AzureCli** - the issue is gone.  Assuming the default constructor is using RunAs=Developer; DeveloperTool=VisualStudio - as this gives same connection problems.

Looking at the access tokens generated for each mechanism, the working token has attributes
- altsecid
- email
- home_oid
- idp
- rh

The non working token is missing all the above and has"uti".  Interesting also, each has different OIDs... the bad token OID doesnt even exist as user in the directory.  The good OID is the proper id for the guest user.

This same issue is not present when using same library to access Azure Keyvault... only reproducable for Azure SQL Server

**Expected behavior**
Authentication works for VisualStudio authentication same as CLI.  Confirmed good using SSMS (using Universal with MFA with same guest user).  NOTE: SSMS v.17 does not work with guest accounts only v18+

**Actual behavior (include Exception or Stack Trace)**
Login failed for user '<token-identified principal>'

**To Reproduce**
Steps to reproduce the behavior (include a code snippet, screenshot, or any additional information that might help us reproduce the issue)

1. Grant group based AAD access to an Azure SQL Server
2. Login to Visual Studio 2019 with Azure Service Authentication 
3. Connect to SQL using Microsoft.Azure.Services.AppAuthentication to get Access Token

**Environment:**
 - Microsoft.Azure.Services.AppAuthentication 1.5.0
 - Windows 10.0.17763 
 - .NET CORE 3.1.3.1
 - Visual Studio 2019 16.6.2 (ASA Service Provider - 1.0)

**Comment by nonik0** [comment] 2020-06-16 18:47
@felickz Thank you for reporting. You are correct that by default Visual Studio authentication is [attempted first](https://github.com/Azure/azure-sdk-for-net/blob/8d4eb178ac47be1c0845165909df613164d0ed8a/sdk/mgmtcommon/AppAuthentication/Azure.Services.AppAuthentication/AzureServiceTokenProvider.cs#L104), which explains why the default case is also failing.

So based off your information that Azure CLI tokens are working for you, this looks like a potential issue with the Visual Studio's token service. Let me follow up on this and I can update once I know more.

**Comment by nonik0** [comment] 2020-06-16 19:25
@felickz Could you try setting tenantId when requesting the access token? E.g:
`azureServiceTokenProvider.GetAccessTokenAsync(<resourceId>, <tenantId>);`

It seems like the guest account would be the cause of those missing claims since its home tenant is different from the tenant you are authenticating against. Explicitly setting the tenantId when using VS auth can resolve that. Please let me know!

**Comment by ericsampson** [comment] 2020-07-01 13:39
@nonik0 our team has been affected by this as well. It does seem to be an issue with the VS token service. Would you be able to help route the ticket to the right place? Thanks!!

**Comment by nonik0** [comment] 2020-07-07 22:58
@ericsampson Does setting the tenantId as described above not work for your scenario, or could you elaborate on the specifics of what isn't working for you?

**Comment by engenb** [comment] 2020-11-17 18:12
any update on this issue?  my company has several contracted developers that we have added to our directory as guest accounts and we've experienced this same issue.  we've worked around this by setting the environment variable `AzureServicesAuthConnectionString` to `RunAs=Developer;DeveloperTool=AzureCli;`

**Comment by anaismiller** [comment] 2020-11-20 02:09
@engenb setting `AzureServicesAuthConnectionString` to `RunAs=Developer;DeveloperTool=VisualStudio;TenantID=<my tenant id>;` is not a considered setting. Settings are [listed here](https://docs.microsoft.com/en-us/azure/key-vault/general/service-to-service-authentication#connection-string-support) and [code here](https://github.com/Azure/azure-sdk-for-net/blob/eae6c13105591ecaaf486c32a98e7e5261ba5c5b/sdk/mgmtcommon/AppAuthentication/Azure.Services.AppAuthentication/AzureServiceTokenProviderFactory.cs#L70-L85) where decoding happens.

Can you try instead 
`AzureServiceTokenProvider("RunAs=Developer; DeveloperTool=VisualStudio").GetAccessTokenAsync(<resourceId>, <tenantId>);` ?

**Comment by ericsampson** [comment] 2020-11-20 03:40
@nonik0 I can try setting the tenant ID and see if that makes it work.

I just really want to avoid doing this, as there are hundreds of places across of our codebases that I would have to go make this fix.
It seems like a bug in the VS auth system, because it works fine when the Azure CLI handles the auth without me having to explicitly set a tenant. So that's why I'm trying to find out if I should file a bug with VS somehow, or here... Thanks!

**Comment by engenb** [comment] 2020-11-29 21:59
Just to follow up, my team has worked around this by having contractor (guest user) developers set a windows environment variable `AzureServicesAuthConnectionString: RunAs=Developer;DeveloperTool=AzureCli;`.

After logging in with Azure CLI and selecting the correct subscription, everything works as expected.

**Comment by anaismiller** [comment] 2020-12-04 00:30
@ericsampson @felickz have you resolved this?

**Comment by ericsampson** [comment] 2020-12-04 14:11
@anaismiller the following workaround is not acceptable for us because it would mean we'd need to make this change in hundreds of repositories where we use AAD tokens:
`AzureServiceTokenProvider("RunAs=Developer; DeveloperTool=VisualStudio").GetAccessTokenAsync(<resourceId>, <tenantId>);`

We need a solution that works OOTB with Visual Studio.

**Comment by engenb** [comment] 2020-12-04 14:25
@ericsampson , take a look at my previous comment.  You don't necessarily need to make changes in each project.  If you set an OS environment variable it will get picked up by the framework and take precedent over other configs.  We develop primarily on Windows so we were able to set the environment variable in Windows (not via VS launchSettings.json) and it worked great with no changes to projects needed.  I will admit there are details about your situation I'm likely not aware of, but maybe this will work for you as well.

**Comment by ericsampson** [comment] 2020-12-04 15:51
@engenb sure I understand how that works, but trying to get every developer in our org to set that env var is a workaround, not a solution. It's a waste of our time for something that just needs to be fixed :)

**Comment by ericsampson** [comment] 2020-12-04 15:57
The reason I say these things are a workaround is that this problem doesn't exist when using the Azure CLI token service. It's just the VS token service that has this issue.

**Comment by anaismiller** [comment] 2020-12-04 17:37
@crmann1 for VS awareness

**Comment by ericsampson** [comment] 2021-03-12 14:59
cc @anaismiller @crmann1 , bumping this so that the bot doesn't close it out. Any updates? Thanks

**Comment by felickz** [comment] 2021-03-14 18:35
> Hi @felickz. Thank you, for your interest in helping to improve the Azure SDK experience and for your contribution. We've noticed that there hasn't been recent engagement on this pull request. If this is still an active work stream, please let us know by pushing some changes or leaving a comment. Otherwise, we'll close this out in 7 days.

Unfortunately I have switched all my teams to use the AzureCli - having hundreds of developers not working was not an option for me :(

**Comment by anaismiller** [comment] 2021-03-25 16:23
@ericsampson Do you also only have this issue when working with Azure SQL and not with Azure KeyVault?

One possible explanation is that with VS auth, if no tenantId is provided, then it uses the [default tenant](https://github.com/Azure/azure-sdk-for-net/blob/875d3c1e65b4b441800ed55f539185d4c6229ebe/sdk/mgmtcommon/AppAuthentication/Azure.Services.AppAuthentication/TokenProviders/VisualStudioAccessTokenProvider.cs#L70-L85) when requesting the token and in this case, it is not the one from the Azure subscription, but the one from the guest account. On the other hand, [AzureCli authentication](https://github.com/Azure/azure-sdk-for-net/blob/875d3c1e65b4b441800ed55f539185d4c6229ebe/sdk/mgmtcommon/AppAuthentication/Azure.Services.AppAuthentication/TokenProviders/AzureCliAccessTokenProvider.cs#L119-L121) does not have this tenant parameter.
However, this does not explain why it works with KV and not SQL.

**Comment by ericsampson** [comment] 2021-03-25 16:45
@anaismiller I believe we experience the same issue with both. I can verify and respond back.

But for sure, the Azure CLI token works flawlessly for us, and the VS (and VSCode) ones do not.

When using Azure Identity, we have to do this everywhere:
```
var azureCredential = new DefaultAzureCredential(new DefaultAzureCredentialOptions
{
    ExcludeVisualStudioCredential = true,
    ExcludeVisualStudioCodeCredential = true
});
```
and the equivalent connection string for ` AzureServiceTokenProvider`

Thank you for continuing investigating!! The difference between the two that you noticed sounds promising.

**Comment by ericsampson** [comment] 2021-03-25 16:54
For us, our default tenant is definitely not where our Azure SaaS resources live, so what VS does isn't going to work for us.

**Comment by engenb** [comment] 2021-03-25 16:59
Yes, this is what I have seen as well.  Visual Studio is picking up the "default" tenant for guest accounts which is not our corporate directory.  I've worked around this with a little helper class
```csharp
public static class TokenCredentialFactory
{
    public static TokenCredential Get(IHostEnvironment env, string tenantId) =>
        env.IsDevelopment()
            ? new DefaultAzureCredential(new DefaultAzureCredentialOptions
            {
                SharedTokenCacheTenantId = tenantId,
                VisualStudioTenantId = tenantId
            })
            : new DefaultAzureCredential();
}
```

**Comment by ericsampson** [comment] 2021-03-25 17:02
For us, the challenge would be adding that kind of workaround to 50 repos (or pulling in a little nuget library to do it, same difference), or trying to get the env var to every dev's workstation.

So if the fix is as easy as changing a couple lines of code in VS and VSCode, that would be awesome.

**Comment by engenb** [comment] 2021-03-25 17:09
yup.  I get it.  you could spend the time updating to use the workaround or you could spend the time waiting for microsoft to fix the issue.  I can bet you which would be faster ;)

**Comment by anaismiller** [comment] 2021-03-25 19:20
Thanks @engenb for the suggestion! However, isn't that basically the same as calling `AzureServiceTokenProvider("RunAs=Developer; DeveloperTool=VisualStudio").GetAccessTokenAsync(<resourceId>, <tenantId>);  ` as you still have to explicitly put in the tenantId when you request the token?

**Comment by ericsampson** [comment] 2021-03-25 19:22
![image](https://user-images.githubusercontent.com/1183853/112531408-8a8b3100-8d75-11eb-8293-4aff01ab7b65.jpeg)

**Comment by ericsampson** [comment] 2021-03-25 19:24
I just like to keep working towards every affected VS/CSCode user benefitting by not having to hit and workaround this :) But yeah

**Comment by anaismiller** [comment] 2021-03-26 01:06
I have created a bug internally on VS to enable all tokens returned for all tenants when requesting a token to have a similar experience as AzureCli.

**Closed by anaismiller** 2021-03-26 01:06 UTC
Labels: AppAuthentication, Client, Service Attention, customer-reported, needs-team-attention, question

**Comment by ericsampson** [comment] 2021-03-26 14:31
@anaismiller thank you very much, but VSCode is affected as well. Can we create a ticket for it too?
