### ISSUE TITLE
[BUG] Blob container's metadata is always empty when listed

### ISSUE THREAD

**Issue by GalPillar** [Azure/azure-sdk-for-net#17717] opened 2020-12-29 19:06 UTC
**Describe the bug**
I'm using the Azure.ResourceManager.Storage sdk and the `StorageManagementClient` client, and calling `client.BlobContainers.ListAsync`. The returned list of `ListContainerItem` has a property called `Metadata`, which is basically the same as tags. The issue is that the Metadata I see on the blob container in the azure portal isn't in the returned `ListContainerItem`, instead it is always an empty `IDictionary`.
On the contrary, when I fetch the blob container with `client.BlobContainers.GetAsync`, the Metadata is returned correctly.

**Expected behavior**
The Metadata will be present in the returned `ListContainerItem`.

**Actual behavior (include Exception or Stack Trace)**
The Metadata property is an empty `IDictionary`.

**To Reproduce**
1. Create a `StorageManagementClient` client.
2. Call `client.BlobContainers.ListAsync`.
3. See that the Metadata is always empty

**Environment:**
 -  Azure.ResourceManager.Storage - 1.0.0-preview.2
 - Windows 10,  .NET Framework 5
 - e.g. Visual Studio 16.8.3

**Comment by AlexGhiondea** [comment] 2020-12-29 21:34
Thank you for your feedback. Tagging and routing to the team member best able to assist.

**Comment by GalPillar** [comment] 2020-12-30 08:48
Just tested it, and this also happens for `client.FileShares.ListAsync`

**Comment by nisha-bhatia** [comment] 2020-12-30 19:48
@GalPillar Could you please provide HTTP request and response?

**Comment by GalPillar** [comment] 2021-01-03 12:05
list request:
request:
GET https://management.azure.com/subscriptions/<subscriptionId>/resourceGroups/<resourceGroupName>/providers/Microsoft.Storage/storageAccounts/<storageAccountName>/blobServices/default/containers?api-version=2019-04-01
Authorization: Bearer <Token>

response is attached
[response.txt](https://github.com/Azure/azure-sdk-for-net/files/5757458/response.txt)

get request:
request: 
GET https://management.azure.com/subscriptions/<subscriptionId>/resourceGroups/<resourceGroupName>/providers/Microsoft.Storage/storageAccounts/<storageAccountName>/blobServices/default/containers/<containerName>?api-version=2019-06-01
Authorization: Bearer <Token>

response is attached
[getResponse.txt](https://github.com/Azure/azure-sdk-for-net/files/5761556/getResponse.txt)

**Comment by blueww** [comment] 2021-01-04 04:14
@zfchen95

This looks a server issue: 
List container from SRP won't return container meta data ( But get single container from SRP will return meta data; list container from dataplane will also return meta data)

Would you please help to look?

**Comment by zfchen95** [comment] 2021-01-05 18:51
We currently don't include metadata in list blob containers in management plane API.  We will add it in a future release. 
For list file shares, we will need to update the swagger. The feature is available at the server level.

**Comment by seanmcc-msft** [comment] 2021-03-26 18:29
@blueww, any updates?

**Comment by blueww** [comment] 2021-03-29 02:50
@seankane-msft 
This is SRP server issue, not SRP .net SDK issue. So only SRP team can fix it.

You can see  @zfchen95  comments above.
@zfchen95, will SRP team fix the issue from SRP server?

**Comment by amnguye** [comment] 2021-07-08 21:39
@zfchen95 can you please answer the above query?

**Comment by dorki** [comment] 2021-07-18 22:43
Hi! any update on this issue ? @amnguye @zfchen95

**Comment by ArthurMa1978** [comment] 2023-01-10 05:33
@blueww can you help to check with service team if there has any updates?

**Comment by blueww** [comment] 2023-01-10 06:30
@ArthurMa1978 
I have pinged service team again and included you.

**Comment by omri-muszkal** [comment] 2023-03-27 12:59
@blueww @ArthurMa1978 Anything? :(

**Comment by blueww** [comment] 2023-03-28 02:47
@omri-muszkal 
Actually, the issue is on server side instead of Client (SDK) side.  (Both Arthur and me works on client side.)
So we will need server team to update server by return the container metadata to fix this issue? 

We have contact server team, and a bug is already opened.
However, it looks the issue is still not fixed on server side.

To make server team understand the importance and priority of this issue, you might can also try to connect to Server team with your channel, such like open a help request from Azure portal. 
![image](https://user-images.githubusercontent.com/6926193/228114271-733f6fba-181d-4022-a4c7-577a493bf769.png)

**Comment by ArthurMa1978** [comment] 2023-05-22 06:20
Close as this is not client-side issue, please file ticket to ask service team to fix it.

**Closed by ArthurMa1978** 2023-05-22 06:20 UTC
Labels: Storage, Service Attention, Mgmt, customer-reported, feature-request, needs-team-attention
