### ISSUE TITLE
Azure Storage Blob v12.10.0 - "Azure.RequestFailedException: The condition specified using HTTP conditional header(s) is not met." exception while trying to download blobs.

### ISSUE THREAD

**Issue by anandnara** [Azure/azure-sdk-for-net#28488] opened 2022-05-02 18:11 UTC
We currently use Azure Storage Blob v12.10.0 which we recently migrated to. And now, we are transiently hitting Azure.RequestFailedExceptions while trying to download blobs. 

**Code:**

```
                try
		{
			StorageTransferOptions options = new StorageTransferOptions
			{
				// Set the maximum number of workers that
				// may be used in a parallel transfer.
				MaximumConcurrency = this.parallelOperationThreadCount
			};
			await blob.DownloadToAsync(stream, new BlobRequestConditions(), options, cancellationToken).ConfigureAwait(false);
			tracer.Succeeded = true;
		}
		catch (Exception e)
		{
			this.eventLogger.LogWarning($"Failed to download with exception:{e}");
			throw;
		}
```

**Error Detials:**

**Azure.RequestFailedException: The condition specified using HTTP conditional header(s) is not met. RequestId:ab1be42c-501e-0007-740d-5cc588000000 Time:2022-04-29T21:07:00.1407329Z Status: 412** (The condition specified using HTTP conditional header(s) is not met.) ErrorCode: ConditionNotMet Content: <?xml version="1.0" encoding="utf-8"?><Error><Code>ConditionNotMet</Code><Message>The condition specified using HTTP conditional header(s) is not met. RequestId:ab1be42c-501e-0007-740d-5cc588000000 Time:2022-04-29T21:07:00.1407329Z</Message></Error> Headers: x-ms-request-id: ab1be42c-501e-0007-740d-5cc588000000 x-ms-client-request-id: eae8ba9d-fe6f-4c4e-8526-2233250ce9c3 x-ms-version: 2020-10-02 x-ms-error-code: ConditionNotMet Date: Fri, 29 Apr 2022 21:06:59 GMT Server: Windows-Azure-Blob/1.0,Microsoft-HTTPAPI/2.0 Content-Length: 252 Content-Type: application/xml at Azure.Storage.Blobs.BlobRestClient.

**Questions:**

_Note: We are currently not adding any Request Conditions but still throws the conditional header(s) is not met error._

1. Found this solution while browsing for a fix: [link](https://stackoverflow.com/questions/62308525/azure-blob-error-storageexception-the-condition-specified-using-http-condition). Would you recommend this fix for Azure Storage Blob v12.10.0 as well? 
2. If we make ifMatch=*, what is the effect on DownloadToAsync operation? And in the scenario where we are updating while trying to download the same blob, what is the effect on both the operations?

**Comment by SatishBoddu-MSFT** [comment] 2022-05-03 16:40
Hello @anandnara 
Thanks for the feedback! We are currently investigating and will update you shortly.

**Comment by SatishBoddu-MSFT** [comment] 2022-05-03 16:48
Hello @anandnara Have you tried the latest version?

![image](https://user-images.githubusercontent.com/62923178/166500910-f705526a-cc65-4251-9bc5-9c5e3a113cd0.png)

**Comment by anandnara** [comment] 2022-05-03 20:34
@SatishBoddu-MSFT, would it be possible to check if this issue is fixed in the latest version on your end? Or if you can check if there were any logical changes to how 412 error is returned? That would be really helpful. There are many dependencies we use with this library and reproducing this issue is not easy on our end since its transient.

**Comment by SatishBoddu-MSFT** [comment] 2022-05-03 20:54
> to check if this issue is fixed in the lates

Thanks for the quick response, we are working on this issue!

**Comment by SatishBoddu-MSFT** [comment] 2022-05-09 18:31
Hello @anandnara 
For a deeper investigation and immediate assistance on this issue, if you have a support plan you may file a support ticket or please let us know if you need further help with the support ticket and we would be happy to help you further!

**Comment by anandnara** [comment] 2022-05-18 06:56
@SatishBoddu-MSFT, I suspect that the ETag value might have changed when DownloadToAsync is in progress. Is it possible to know when and what operation changed the Etag value of that blob using the RequestId: ab1be42c-501e-0007-740d-5cc588000000?

**Comment by SatishBoddu-MSFT** [comment] 2022-05-18 17:41
@anandnara You could first read the ETag via GetpropertiseAsync() and then pass the ETag condition during the DownloadToAsync operation. Ref: [Optimistic concurrency](https://docs.microsoft.com/en-us/azure/storage/blobs/concurrency-manage?tabs=dotnet)


try {
    var existingProperties = await blobClient.GetPropertiesAsync();
    var etagCondition = new BlobRequestConditions() {
        IfMatch = existingProperties.Value.ETag
    };
    Response response = await blobBaseClient.DownloadToAsync(stream, blobRequestConditions);
} catch (RequestFailedException ex) when (ex.ErrorCode == BlobErrorCode.ConditionNotMet) {
    // Todo: You can handle ETag mismatch here!!!
}

**Comment by anandnara** [comment] 2022-05-18 19:18
@SatishBoddu-MSFT, thank you for the suggestion. 

Let me give you more details on the current issue. We are doing a SetMetadataAsync which changes the ETag value while we are doing DownloadToAsync. Looking at the DownloadToAsync code for v12.10, it does two operations: gets the properties including ETag value (First operation) and then downloads the blob (Second operation). 

In my opinion this issue is happening when SetMetadataAsync ran after the first operation in DownloadToAsync and it hence throws "Azure.RequestFailedException: The condition specified using HTTP conditional header(s) is not met.". [Link to code](https://github.com/Azure/azure-sdk-for-net/blob/8b1c549d3adedc855d5b3f47143dc9be7db8b9ec/sdk/storage/Azure.Storage.Blobs/src/PartitionedDownloader.cs#L144).

Providing the ETag value won't fix this issue since there might be a SetMetadataAsync call in the mid of DownloadToAsync which changes the ETag value again.

Questions:

- Could we verify if the cause of this issue is in fact because of the above theory? **If this is true, BlobRequestConditions needs to be set with if-match: ETag.All by default.** (we are currently passing it as default)
- Would passing if-Match: ETag.All be a potential mitigation on our end here? Assuming SetMetadataAsync would not affect the blob contents or DownloadToAsync operation.

**Comment by SatishBoddu-MSFT** [comment] 2022-05-18 19:19
Hello @anandnara We have routed this issue to the Service Team's attention for further action, thanks for the detailed information!

**Comment by anandnara** [comment] 2022-05-24 21:50
Hello, any updates on this?

**Comment by anandnara** [comment] 2022-07-07 17:19
Fixed this by setting IfMatch = ETag.All as part of BlobRequestConditions. This is an optimistic approach as per the [link](https://docs.microsoft.com/en-us/azure/storage/blobs/concurrency-manage?tabs=dotnet). The assumption here is that, setting a property field such as IfMatch does not affect the blob contents and does not interrupt DownloadToAsync operation. Also, according to this [link](https://stackoverflow.com/questions/32981691/is-the-azure-put-blob-operation-atomic), a blob either does not exist or exist with the entire content that was put including metadata.

Code Changes:

```
try
{
	StorageTransferOptions options = new StorageTransferOptions
	{
		// Set the maximum number of workers that
		// may be used in a parallel transfer.
		MaximumConcurrency = this.parallelOperationThreadCount
	};
	
	BlobRequestConditions blobRequestConditions = new BlobRequestConditions
	{
		IfMatch = ETag.All
	};

	await blob.DownloadToAsync(stream, blobRequestConditions, options, cancellationToken).ConfigureAwait(false);
	tracer.Succeeded = true;
}
catch (Exception e)
{
	this.eventLogger.LogWarning($"Failed to download with exception:{e}");
	throw;
}
```

**Comment by anandnara** [comment] 2022-08-02 17:42
The code changes did not help sadly. I still the same issues. @SatishBoddu-MSFT, could you let me know what you see on your end for the Request ID: fcea909d-d01e-0068-0c49-a6ac39000000

Message: BackupManager: Failed to restore backup: Azure.RequestFailedException: The condition specified using HTTP conditional header(s) is not met. RequestId:fcea909d-d01e-0068-0c49-a6ac39000000 Time:2022-08-02T08:27:48.9957211Z Status: 412 (The condition specified using HTTP conditional header(s) is not met.) ErrorCode: ConditionNotMet

**Comment by sarahrbs** [comment] 2023-01-19 09:22
Hi, I would appreciate if you have update on this issue?

My application reads from blob while another program is updating the same blob.
Tried the following as suggested by [anandnara], Still get the same error "Status: 412  - The condition specified using HTTP conditional header(s) is not met." in the stream.Read() line.

            BlobRequestConditions blobRequestConditions = new BlobRequestConditions
            {
                 IfMatch = ETag.All
                 //  IfMatch = new ETag("*")
            };

            try
            {
                using (var stream = await blob.OpenReadAsync(offset, segmentSize, blobRequestConditions)) 
                {    
                    stream.Position = offset;
                    stream.Read(buffer, 0, buffer.Length);      // Error in this line
                    ret.Byte = buffer;             
                }
                …...
            }
            catch (Exception ex)
            {
                 System.Diagnostics.Debug.WriteLine(" Failed to Read");
                 throw;
            }

**Comment by amnguye** [comment] 2023-01-26 21:38
I'm going to close this issue for the reasons below.

The OP made it clear that during a download call, that the blob was being altered.
>In my opinion this issue is happening when SetMetadataAsync ran after the first operation in DownloadToAsync and it hence throws "Azure.RequestFailedException: The condition specified using HTTP conditional header(s) is not met.".

It's by design that the storage service would update the ETag of the blob when the metadata is updated in the blob. That's something out of the control of the SDK. We can't support that scenario by the design of the storage service.

The workaround talked about this in this github issue disables the data integrity feature of the SDK. Which is removing the `If-Match` header from all Download operations puts the destination of the data at risk for data corruption. If another process was added to alter the blob's actual data at the time of the download, the SDK would not be able to catch that and would continue downloading the blob.

We would exercise caution if this approach has to be taken, because this removes the data corruption protection. We do not support disabling this header, the following scenario provided in this github issue also does not warrant doing so either.

**Closed by amnguye** 2023-01-26 21:38 UTC
Labels: Storage, Service Attention, Client, customer-reported, question, needs-team-attention, Support
