### ISSUE TITLE
Create Test Automation for Azure.Identity running in Azure Hosted Environments

### ISSUE THREAD

**Issue by joshfree** [Azure/azure-sdk-for-net#9305] opened 2020-01-03 22:52 UTC
**Epic: Create Test Automation for Azure.Identity running in Azure Hosted Environments**

- [ ] Azure Cloud Shell
  - [x] /sdk/e2e test assets checked-in so that they can be referenced from Vendor Instructions
  - [ ] Language-specific instructions added to https://github.com/Azure/azure-sdk/issues/795
- [ ] Azure VM
  - [x] /sdk/e2e test assets checked-in so that they can be referenced from Vendor Instructions
  - [ ] Language-specific instructions added to https://github.com/Azure/azure-sdk/issues/815
- [ ] Azure Kubernetes
  - [ ] /sdk/e2e test assets checked-in so that they can be referenced from Vendor Instructions
  - [ ] Language-specific instructions added to https://github.com/Azure/azure-sdk/issues/814
- [ ] Azure WebJobs
  - [ ] /sdk/e2e test assets checked-in so that they can be referenced from Vendor Instructions
  - [ ] Language-specific instructions added to https://github.com/Azure/azure-sdk/issues/902

**Comment by joshfree** [comment] 2020-02-10 18:18
Updating issue as Functions and App Services have been moved to the backlog

**Comment by christothes** [comment] 2023-07-21 19:43
dupe of #37471

**Closed by christothes** 2023-07-21 19:43 UTC
Labels: Client, Epic, Azure.Identity
