### ISSUE TITLE
[FEATURE REQ]

### ISSUE THREAD

**Issue by coco1080** [Azure/azure-sdk-for-net#28734] opened 2022-05-12 18:39 UTC
### Library name

AzurePowershellCredentials

### Please describe the feature.

**AzurePowershellCredentials** library should be enhanced in a way the client code can configure timeout parameters depending on their needs and scenarios when generating token requests. The client can experience several transient timeout issues when requesting tokens by not having that option, which is the scenario we are experiencing. (Please see stack trace below for more details)

These are the timeout fixed values that are encapsulated in the following libraries:
 (AzurePowershellCredential 10s, AzureCLICredential 13s, VisualStudioCredential 30s) 

Stack Trace:
   at Azure.Identity.AzurePowerShellCredential.<RequestAzurePowerShellAccessTokenAsync>d__26.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azure.Identity.AzurePowerShellCredential.<GetTokenImplAsync>d__25.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Azure.Identity.CredentialDiagnosticScope.FailWrapAndThrow(Exception ex, String additionalMessage)
   at Azure.Identity.AzurePowerShellCredential.<GetTokenImplAsync>d__25.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azure.Identity.AzurePowerShellCredential.GetToken(TokenRequestContext requestContext, CancellationToken cancellationToken)
   at Azure.Identity.DefaultAzureCredential.<GetTokenFromSourcesAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azure.Identity.DefaultAzureCredential.<GetTokenImplAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Azure.Identity.CredentialDiagnosticScope.FailWrapAndThrow(Exception ex, String additionalMessage)
   at Azure.Identity.DefaultAzureCredential.<GetTokenImplAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

**Comment by jsquire** [comment] 2022-05-12 22:09
//cc: @christothes

**Comment by jsquire** [comment] 2022-05-12 22:09
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by christothes** [comment] 2022-05-12 22:38
duplicate of #23135

**Closed** 2022-10-21 21:22 UTC
Labels: Client, Azure.Identity, customer-reported, question, needs-team-attention
