### ISSUE TITLE
[QUERY] End to end tracing via Azure.Messaging.ServiceBus

### ISSUE THREAD

**Issue by psiservices-dbrink** [Azure/azure-sdk-for-net#18002] opened 2021-01-15 16:03 UTC
**Query/Question**
Should Azure.Messaging.ServiceBus support correlation between pub and sub?  Specifically, when viewing the end-to-end transaction details in Application Insights, should I be able to view the complete code path from sending the message to a topic continuing through processing the messages by subscribers?

I built a simple .NET 5 web application that sends and receives topic/subscription messages using Microsoft.Azure.ServiceBus on one code path and Azure.Messaging.ServiceBus on another.  

Messages processed via Microsoft.Azure.ServiceBus show both pub and sub 
![image](https://user-images.githubusercontent.com/43828739/104748327-99bf8400-571f-11eb-8470-44534b2523b8.png)

Messages processed via Azure.Messaging.ServiceBus show as two different transactions.
one for pub:
![image](https://user-images.githubusercontent.com/43828739/104749926-60881380-5721-11eb-8adf-06135f6886ae.png)

one for sub
![image](https://user-images.githubusercontent.com/43828739/104749655-143cd380-5721-11eb-8032-1b56c54804ee.png)
 

**Environment:**
 - Azure.Messaging.ServiceBus 7.0.1
 - .NET SDK (reflecting any global.json):
 Version:   5.0.101
 Commit:    d05174dc5a

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19041
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.101\

Host (useful for support):
  Version: 5.0.1
  Commit:  b02e13abab

 - Visual Studio 16.8.3

**Comment by psiservices-dbrink** [comment] 2021-01-15 22:13
Quick update based on some additional research.

If I start an activity in my ProcessMessage callback and set the parent id to the Diagnostic-Id I get end to end tracing.

`
            var activity = new Activity("ProcessMessage");
            if (arg.Message.ApplicationProperties.TryGetValue("Diagnostic-Id", out var parentId))
            {
                activity.SetParentId(parentId.ToString());
            }

            activity.Start();

            DoWork();

            activity.Stop();
`

Take this with a grain of salt.  I've only just started poking around the Azure.Messaging.ServiceBus solution.  The parent context appears to be added as a linked diagnostic activity.  The Links property on DiagnosticActivity does not override the Links inherited from Activity and instead creates a "new" Links.  Given that DiagnosticActivity is private it can't easily be referenced directly as a DiagnosticActivity by app insights or other libraries.  I'm assuming it would be referenced as Activity in most situations;, this would result in Links resolving to Activity.Links, not DiagnosticActivity.Links.  The "new" keyword appears to be relatively recent.  Could this have broken the correlation?  

`
        private class DiagnosticActivity : Activity
        {
            private List<Activity>? _links;

            public new IEnumerable<Activity> Links => (IEnumerable<Activity>?)_links ?? Array.Empty<Activity>();
        }
`

**Comment by jsquire** [comment] 2021-01-18 15:38
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by JoshLove-msft** [comment] 2021-01-19 23:56
@psiservices-dbrink thanks for creating this issue. There appears to be work that needs to happen within App Insights to get the end to end tracing to work with the new library. I've created an [issue](https://github.com/microsoft/ApplicationInsights-dotnet/issues/2151) in their repo that links back to this one -

**Comment by sebader** [comment] 2021-05-01 18:31
Any update on this? This works very nicely already with EventHubs. Just switched to ServiceBus and somewhat disappointed that end-to-end tracing doesn't seem to work here OOTP. I can see the Diagnostics-Id message property is getting correctly set by the sender but the processor does not seem to use it at all.

**Comment by JoshLove-msft** [comment] 2021-05-03 05:11
Hi @sebader, 
That PR updates the processor so that the diagnostics-Id from the message is included as the correlation information in the ServiceBusProcessor.ProcessMessage.Start event. Before this PR, the linked activity would not be available as part of the Start event but only as part of the End event as mentioned in https://github.com/Azure/azure-sdk-for-net/issues/20349.

We will plan to release a patch with this in the next week or so.

**Comment by sebader** [comment] 2021-05-03 07:14
ok thanks @JoshLove-msft ! Will watch out for the new version and will give it a try

**Comment by psiservices-dbrink** [comment] 2021-05-03 13:24
@JoshLove-msft , does #20349 actually correct end to end tracing with app insights/service bus or does [this issue](https://github.com/microsoft/ApplicationInsights-dotnet/issues/2151) still need to be fixed?

If the latter, is there any way to get the app insights team engaged?

**Comment by JoshLove-msft** [comment] 2021-05-03 21:57
Hi @psiservices-dbrink, we would still need the app insights work. I've pinged on that issue to try to get an update.

**Comment by ramya-rao-a** [comment] 2021-09-14 19:47
@JoshLove-msft If this is a valid feature request or a bug, can you please add the appropriate label and milestone?

**Comment by JoshLove-msft** [comment] 2021-09-15 01:12
This is a feature request and it is waiting on work by the App Insights team. https://github.com/microsoft/ApplicationInsights-dotnet/issues/2151

**Comment by JoshLove-msft** [comment] 2021-10-06 05:15
Related - https://github.com/Azure/azure-sdk-for-net/issues/17940

**Comment by ncoussemacq** [comment] 2022-01-06 13:42
Hi everyone

I'm using Azure.Messaging.ServiceBus version 7.5.1 and end-to-end tracing seems to work out-of-the box. I even checked that a "Diagnostic-Id" property is available in ApplicationProperties Property of the message on receiver side. (Side note, it seems it's not working for sheduled messages. is that expected ?)

For additional tracing, I wanted to use Correlation-Context header to carry some very specific properties to be attached to the message as well. As explained in[ this page](https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-end-to-end-tracing?tabs=net-standard-sdk-2) of the documentation, the end-to-end tracing implementation is based on [HTTP Correlation protocol](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Diagnostics.DiagnosticSource/src/HttpCorrelationProtocol.md), which can leverage Correlation-Context header to store additional context data. Unfortunately, I don't see this data being carried to ApplicationProperties in the message on the service bus receiver side. Am I doing it wrong ? Or is it part of things still not implemented in Azure.Messaging.ServiceBus SDK ?

**Comment by JoshLove-msft** [comment] 2022-01-06 20:37
@ncoussemacq, if you set a header in the application properties it should still be there when the message is received, regardless of what the header is. We don't have special handling for correlation-context, but I'd expect it to still be on the received message. Are you sure you are looking at the same message?

**Comment by JoshLove-msft** [comment] 2022-01-06 20:40
Regarding the tracing not working for scheduled messages, this is not expected. Can you share a code snippet?

**Comment by lmolkova** [comment] 2022-01-06 21:41
>  I wanted to use Correlation-Context header to carry some very specific properties to be attached to the message as well. 
Unfortunately, Correlation-Context (and  HTTP Correlation protocol) are not supported in any Azure SDK. We use [W3C trace-context](https://www.w3.org/TR/trace-context/) for Diagnostic-Id format but the formal [W3C standard for Baggage](https://www.w3.org/TR/baggage/) (aka Correlation-Context) is still in draft.

The docs seem to be out of date and I'll update them to reflect it.

As @JoshLove-msft mentioned, you can pass anything you want through application properties, but you'd have to populate those properties manually on the telemtery depending on your tracing solution.

**Comment by ncoussemacq** [comment] 2022-01-07 09:39
Thanks for these answers.

I didn't plan to manually set any additional property and was expecting it to be done automagically. I'll check if it's possible to do it on my side. Do you plan to support Baggage header propagation when the standard will be approved ?

About correlation not working on scheduled message, I just figured out why while trying to write a sample to reproduce it. Sorry for that false report.

**Comment by lmolkova** [comment] 2022-01-07 17:42
@ncoussemacq  thanks a lot for the update!

Once the Baggage is approved, we'll gradually adopt it.

**Comment by dlebee** [comment] 2022-02-28 20:33
> Hi everyone
> 
> I'm using Azure.Messaging.ServiceBus version 7.5.1 and end-to-end tracing seems to work out-of-the box. I even checked that a "Diagnostic-Id" property is available in ApplicationProperties Property of the message on receiver side. (Side note, it seems it's not working for sheduled messages. Is it expected ?)
> 
> For additional tracing, I wanted to use Correlation-Context header to carry some very specific properties to be attached to the message as well. As explained in[ this page](https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-end-to-end-tracing?tabs=net-standard-sdk-2) of the documentation, the end-to-end tracing implementation is based on [HTTP Correlation protocol](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Diagnostics.DiagnosticSource/src/HttpCorrelationProtocol.md), which can leverage Correlation-Context header to store additional context data. Unfortunately, I don't see this data being carried to ApplicationProperties in the message on the service bus receiver side. Am I doing it wrong ? Or is it part of things still not implemented in Azure.Messaging.ServiceBus SDK ?

It works out of the box, one issue I noticed is that the library makes use of the old System.Diagnostic.DiagnostiSources and if any projects references the new diagnostic versions it breaks down see.

https://github.com/dlebee/corrolation-function-servicebus

**Comment by lmolkova** [comment] 2022-02-28 20:39
@dlebee Unfortunately Azure Functions doesn't allow to use DiagnosticSource version that's ahead of the host version, Azure SDK are compatible with Function runtime v2+ and can't update DiagnosticSource.

**Comment by dlebee** [comment] 2022-03-01 00:01
> @dlebee Unfortunately Azure Functions doesn't allow to use DiagnosticSource version that's ahead of the host version, Azure SDK are compatible with Function runtime v2+ and can't update DiagnosticSource.

I actually found a way to fix Activity Tags and have a potential hotfix to support it if you are interested using OperationLinks just cleaning it up a bit.

It involves activating the experimental flag of supporting Activity of the library ServiceBus Messaging and a bit of Telemetry Initializers.

**Comment by Bosch-Eli-Black** [comment] 2022-08-02 09:25
Looks like this was fixed in ApplicationInsights 2.21.0: https://github.com/microsoft/ApplicationInsights-dotnet/pull/2593 🙂

**Comment by JoshLove-msft** [comment] 2022-08-08 22:08
Yes, this is now available in https://www.nuget.org/packages/Microsoft.ApplicationInsights/2.21.0

**Closed by JoshLove-msft** 2022-08-08 22:08 UTC
Labels: Service Bus, Monitor, Client, customer-reported, feature-request, Monitor - ApplicationInsights
