### ISSUE TITLE
[Metrics Advisor] test failing in nightly runs

### ISSUE THREAD

**Issue by v-yilinhu** [Azure/azure-sdk-for-net#23316] opened 2021-08-13 07:19 UTC
Metrics Advisor nightly test runs are failing with:

> Error message
> Azure.RequestFailedException : Service request failed.
> Status: 401 (Unauthorized)
> 
> Content:
> {"code":"ERROR_PRIVILEGE_FAILED","message":"You have no permission to do it."}
> 
> Headers:
> X-Request-ID: 4b055afa-7b8c-422b-86e5-dcd5110103e5
> x-envoy-upstream-service-time: 5236
> apim-request-id: 4b055afa-7b8c-422b-86e5-dcd5110103e5
> Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
> X-Content-Type-Options: nosniff
> Date: Mon, 09 Aug 2021 13:35:12 GMT
> Content-Length: 78
> Content-Type: application/json; charset=utf-8
> 
> 
> Stack trace
>    at Azure.AI.MetricsAdvisor.MicrosoftAzureMetricsAdvisorRestAPIOpenAPIV2RestClient.GetMetricSeriesAsync(Guid metricId, MetricSeriesQueryOptions body, Nullable`1 skip, Nullable`1 maxpagesize, CancellationToken cancellationToken) in /_/sdk/metricsadvisor/Azure.AI.MetricsAdvisor/src/Generated/MicrosoftAzureMetricsAdvisorRestAPIOpenAPIV2RestClient.cs:line 2896
>    at Azure.AI.MetricsAdvisor.MetricsAdvisorClient.<>c__DisplayClass9_0.<<GetMetricSeriesDefinitionsAsync>g__FirstPageFunc|0>d.MoveNext() in /_/sdk/metricsadvisor/Azure.AI.MetricsAdvisor/src/MetricsAdvisorClient.cs:line 250
> --- End of stack trace from previous location ---
>    at Azure.Core.PageableHelpers.FuncAsyncPageable`1.AsPages(String continuationToken, Nullable`1 pageSizeHint)+MoveNext() in /_1/microsoft.azure.autorest.csharp/3.0.0-beta.20210805.1/content/Generator.Shared/PageableHelpers.cs:line 56
>    at Azure.Core.PageableHelpers.FuncAsyncPageable`1.AsPages(String continuationToken, Nullable`1 pageSizeHint)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
>    at Azure.Core.TestFramework.DiagnosticScopeValidatingInterceptor.DiagnosticScopeValidatingAsyncEnumerable`1.<>c__DisplayClass6_0.<<AsPages>b__0>d.MoveNext() in /Users/runner/work/1/s/sdk/core/Azure.Core.TestFramework/src/Instrumentation/DiagnosticScopeValidatingInterceptor.cs:line 260
> --- End of stack trace from previous location ---
>    at Azure.Core.TestFramework.DiagnosticScopeValidatingInterceptor.ValidateDiagnosticScope[T](Func`1 action, MethodInfo methodInfo, String source) in /Users/runner/work/1/s/sdk/core/Azure.Core.TestFramework/src/Instrumentation/DiagnosticScopeValidatingInterceptor.cs:line 165
>    at Azure.Core.TestFramework.DiagnosticScopeValidatingInterceptor.DiagnosticScopeValidatingAsyncEnumerable`1.AsPages(String continuationToken, Nullable`1 pageSizeHint)+MoveNext() in /Users/runner/work/1/s/sdk/core/Azure.Core.TestFramework/src/Instrumentation/DiagnosticScopeValidatingInterceptor.cs:line 258
>    at Azure.Core.TestFramework.DiagnosticScopeValidatingInterceptor.DiagnosticScopeValidatingAsyncEnumerable`1.AsPages(String continuationToken, Nullable`1 pageSizeHint)+MoveNext() in /Users/runner/work/1/s/sdk/core/Azure.Core.TestFramework/src/Instrumentation/DiagnosticScopeValidatingInterceptor.cs:line 258
>    at Azure.Core.TestFramework.DiagnosticScopeValidatingInterceptor.DiagnosticScopeValidatingAsyncEnumerable`1.AsPages(String continuationToken, Nullable`1 pageSizeHint)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
>    at Azure.AsyncPageable`1.GetAsyncEnumerator(CancellationToken cancellationToken)+MoveNext() in /_/sdk/core/Azure.Core/src/AsyncPageable.cs:line 103
>    at Azure.AsyncPageable`1.GetAsyncEnumerator(CancellationToken cancellationToken)+MoveNext() in /_/sdk/core/Azure.Core/src/AsyncPageable.cs:line 103
>    at Azure.AsyncPageable`1.GetAsyncEnumerator(CancellationToken cancellationToken)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
>    at Azure.AI.MetricsAdvisor.Tests.TimeSeriesLiveTests.GetMetricSeriesDefinitionsWithMinimumSetup(Boolean useTokenCredential) in /Users/runner/work/1/s/sdk/metricsadvisor/Azure.AI.MetricsAdvisor/tests/MetricsAdvisorClient/TimeSeriesLiveTests.cs:line 83
>    at Azure.AI.MetricsAdvisor.Tests.TimeSeriesLiveTests.GetMetricSeriesDefinitionsWithMinimumSetup(Boolean useTokenCredential) in /Users/runner/work/1/s/sdk/metricsadvisor/Azure.AI.MetricsAdvisor/tests/MetricsAdvisorClient/TimeSeriesLiveTests.cs:line 83
>    at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.BlockUntilCompleted()
>    at NUnit.Framework.Internal.MessagePumpStrategy.NoMessagePumpStrategy.WaitForCompletion(AwaitAdapter awaiter)
>    at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
>    at NUnit.Framewor

For more details check here:

- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1038469&view=results
- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1040565&view=results
- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1042726&view=results

@jsquire for notification.

**Comment by kinelski** [comment] 2021-08-13 08:27
Thank you for reporting it. This has been identified as a service-side issue, and tests have been disabled (https://github.com/Azure/azure-sdk-for-net/pull/23269). We'll enable it once again when the service has fixed the problem. I'll close this as a duplicate of https://github.com/Azure/azure-sdk-for-net/issues/23268.

**Closed by kinelski** 2021-08-13 08:27 UTC
Labels: Client, test-reliability, Cognitive - Metrics Advisor
