### ISSUE TITLE
[BUG] The "computeTravelTimeFor" parameter not available in RouteDirectionOptions class

### ISSUE THREAD

**Issue by jwangga** [Azure/azure-sdk-for-net#47257] opened 2024-11-19 21:32 UTC
### Library name and version

Azure.Map.Routing 1.0.0-beta3

### Describe the bug

I need to use the "computeTravelTimeFor" parameter when requesting for route directions, but I am unable to find it in the RouteDirectionOptions class. is it a missing or exposed somewhere else in the library?

Thanks.

### Expected behavior

Expect to find the option in the RouteDirectionOptions class just like other URL parameters supported by in the Azure Map Route Directions Rest API

### Actual behavior

Not available

### Reproduction Steps

Create an instance of RouteDirectionOption class, and try to set the computeTravelTimeFor property.  It is not available.

**Comment by dubiety** [comment] 2024-11-20 14:12
Hi @jwangga, 
In SDK, it's renamed to `TravelTimeType`, you can use `TravelTimeType.All` and `TravelTimeType.None` to specify `computeTravelTimeFor` value.
I'll close this issue, but feel free to re-open if you have any other questions. Thank you very much!

**Comment by jwangga** [comment] 2024-11-20 19:36
@dubiety Thanks for your quick response.  Yes, I found the TravelTimeType option.  However, when I set it to All, the return object Response<RouteDirections> does not seem to contain:  these values:

"noTrafficTravelTimeInSeconds"
"historicTrafficTravelTimeInSeconds"
"liveTrafficIncidentsTravelTimeInSeconds"

Based on the API, I expect to see these values when TravelTimeType is set to All.  Please advise.

**Comment by dubiety** [comment] 2024-11-21 02:33
Re-open for further investigation.
@jwangga , I'll get back to you soon!

**Comment by dubiety** [comment] 2024-11-21 06:18
Hi @jwangga , we've found the issue. We'll fix this issue in our next release around early Jan. Thank you for your patience!

**Comment by jwangga** [comment] 2024-11-21 18:18
@dubiety Thanks for the update.  Look forward to the next release in Jan. I want to include the integration with Azure Map in our products in the next release scheduled for 1st quarter of 2025.

**Comment by dubiety** [comment] 2024-11-28 16:36
Hi @jwangga ,

Just confirmed with our API team. There are some discrepancy between the response body and API document. As REST SDK follows the behavior of our API document, you can get the "noTrafficTravelTimeInSeconds",  "historicTrafficTravelTimeInSeconds" and "liveTrafficIncidentsTravelTimeInSeconds" from `RouteLegSummary` but not from `RouteSummary`. Please refer to the code samples below:

```csharp
MapsRoutingClient client = new MapsRoutingClient(credential);

// Create origin and destination routing points
List<GeoPosition> routePoints =
[
    new GeoPosition(13.42936, 52.50931),
    new GeoPosition(13.43872, 52.50274)
];

var options = new RouteDirectionOptions()
{
    TravelTimeType = TravelTimeType.All
};

// Create Route direction query object
RouteDirectionQuery query = new RouteDirectionQuery(routePoints, options);

// Route direction result
Response<RouteDirections> result = client.GetDirections(query);

// Print results and also the additional information
Console.WriteLine($"Total {result.Value.Routes.Count} route results");

Console.WriteLine("Route Let Summary:");
var iRoute = 0;
foreach (var route in result.Value.Routes)
{
    var iLeg = 0;
    foreach (var leg in route.Legs)
    {
        Console.WriteLine($"*** Route {iRoute}, leg {iLeg++} ***");
        Console.WriteLine($"NoTrafficTravelTimeInSeconds: {leg.Summary.NoTrafficTravelTimeInSeconds}");
        Console.WriteLine($"HistoricTrafficTravelTimeInSeconds: {leg.Summary.HistoricTrafficTravelTimeInSeconds}");
        Console.WriteLine($"LiveTrafficIncidentsTravelTimeInSeconds: {leg.Summary.LiveTrafficIncidentsTravelTimeInSeconds}");
        Console.WriteLine($"LengthInMeters: {leg.Summary.LengthInMeters}");
        Console.WriteLine($"TravelTimeInSeconds: {leg.Summary.TravelTimeInSeconds}");
        Console.WriteLine($"ArrivalTime: {leg.Summary.ArrivalTime}");
    }
    iRoute++;
}
```

And you'll see the output prints something similar to below (the value is subject to change):
```txt
Total 1 route results
Route Let Summary:
*** Route 0, leg 0 ***
NoTrafficTravelTimeInSeconds: 131
HistoricTrafficTravelTimeInSeconds: 198
LiveTrafficIncidentsTravelTimeInSeconds: 310
LengthInMeters: 1146
TravelTimeInSeconds: 310
```

**Comment by jwangga** [comment] 2024-12-02 18:18
@dubiety Thanks for the update.  It appears that the API documentation on Route Summary does not match the Response returned, which includes the three travel time elements as shown below:

{
    "formatVersion": "0.0.12",
    "routes": [
        {
            "summary": {
                "lengthInMeters": 104300,
                "travelTimeInSeconds": 10448,
                "trafficDelayInSeconds": 0,
                "trafficLengthInMeters": 0,
                "departureTime": "2024-12-03T01:56:15+08:00",
                "arrivalTime": "2024-12-03T04:50:22+08:00",
                **"noTrafficTravelTimeInSeconds": 10448,
                "historicTrafficTravelTimeInSeconds": 10448,
                "liveTrafficIncidentsTravelTimeInSeconds": 10448**
            },
            ... ...

Hence, I expect that the SDK to reflect that.
Here is the URL I used https://atlas.microsoft.com/route/directions/json?subscription-key=<Your key>&api-version=1.0&query=45.9375%2C123.751%3A45.96875%2C123.791%3A45.90625%2C123.767&language=en-US&computeTravelTimeFor=all&travelMode=truck&traffic=false&routeType=shortest

**Comment by dubiety** [comment] 2024-12-03 14:29
I understand our document and the APi response is out of sync, but please honor the document and we don't guarantee for those undocumented returned fields will always stay there. Is it possible to look into the `RouteLegSummary` information instead of the information in `RouteSummary` since we provide the fields in `RouteLegSummary` and it also aligns with our API document.

**Comment by dubiety** [comment] 2024-12-04 02:32
Since no more action item here, I'll close the issue. Let me know if you have any further question. Thank you very much.

**Closed by dubiety** 2024-12-04 02:32 UTC
Labels: Service Attention, Client, customer-reported, question, needs-team-attention, Maps

**Comment by jwangga** [comment] 2024-12-04 02:47
@dubiety It seems that the API document needs to be updated.  It just makes sense to have these elements included in RouteSummary. Thanks.

**Comment by jwangga** [comment] 2024-12-17 03:43
@dubiety   When TravelTimeType is set to All, the RouteLegSummary contains the different types of time for a given leg.  To get, say HistoricTrafficTravelTimeInSeconds, of the route, you would have to loop through all legs to sum them up, while the route summary from the Route Response already includes these values. Therefore, I would strongly believe that the Route summary object in the SDK should expose these values. See the explanation from the API doc, which specifies “all types of traffic information …being included in the summaries in the route response.”  Thanks.

 ![Image](https://github.com/user-attachments/assets/05ac7d5f-88af-470b-8c3b-afe58597638f)

**Comment by dubiety** [comment] 2024-12-17 06:35
Hi @jwangga , I'll bring this topic back to discuss. Let get back to you soon.
