### ISSUE TITLE
[BUG] BlobClient.UploadAsync never completes

### ISSUE THREAD

**Issue by pekspro** [Azure/azure-sdk-for-net#12811] opened 2020-06-16 10:29 UTC
**Describe the bug**
BlobClient.UploadAsync never completes if it is called with a Stream where Position isn't 0.

**Expected behavior**
If should write the stream from the current position, or throw an Exception.

**Actual behavior (include Exception or Stack Trace)**
If never completes

**To Reproduce**
The following code shows the problem:

    var CloudBlobClient = new BlobContainerClient(ConnectionString, "test");

    await CloudBlobClient.CreateIfNotExistsAsync();

    BlobClient cloudBlockBlob = CloudBlobClient.GetBlobClient("myblob");

    MemoryStream stream = new MemoryStream();
    await stream.WriteAsync(new byte[15]);
            
    // If Position is set to 0 UploadAsync will return.
    // stream.Position = 0;
            
    await cloudBlockBlob.UploadAsync(stream, overwrite: true);

**Environment:**
 - Name and version of the Library package used: Azure.Storage.Blobs 12.4.4
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): Microsoft.NETCore.App 3.1.5, Windows 10 19.09
 - IDE and version : Visual Studio 16.6.2

**Comment by seanmcc-msft** [comment] 2020-06-16 19:10
Hi @pekspro, it appears you a mixing V11 and V12 code.

Using only V12 code, I can't repo the issue:
```
using Azure.Storage.Blobs;
using Azure.Storage.Blobs.Specialized;
using System.IO;
using System.Threading.Tasks;

namespace ConsoleApp4
{
    class Program
    {
        static async Task Main(string[] args)
        {
            string connectionString = "";
            BlobContainerClient container = new BlobContainerClient(connectionString, "mycontainer45");
            try
            {
                await container.CreateAsync();
                BlockBlobClient blockBlobClient = container.GetBlockBlobClient("myblockblob");
                MemoryStream stream = new MemoryStream();
                await stream.WriteAsync(new byte[15]);
                stream.Position = 0;
                await blockBlobClient.UploadAsync(stream);
            }
            finally
            {
                await container.DeleteAsync();
            }

        }
    }
}
```

I recommend removing the V11 NuGet dependencies from your project.

**Comment by pekspro** [comment] 2020-06-17 05:22
Thanks for a quick reply @seanmcc-msft. I am using version 12.4.4, my csproj looks like this:
  <Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
      <OutputType>Exe</OutputType>
      <TargetFramework>netcoreapp3.1</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Azure.Storage.Blobs" Version="12.4.4" />
    </ItemGroup>

  </Project>

I get the same problem with your code after this line was removed: 

    stream.Position = 0;

**Comment by seanmcc-msft** [comment] 2020-06-17 17:06
You need to reset the stream.Position to 0 before upload, this is by design.

**Comment by pekspro** [comment] 2020-06-17 18:43
@seanmcc-msft, if that is by design, then `UploadAsync` should verify this and throw an exception if Position is not 0 in my opinion. Now it never completes and that is just bad.

Also, why does position needs to be 0? Why can not it just read the stream from the current position to the end? This works fine when we are working with ordinary files:

    static async Task Main(string[] args)
    {
        using MemoryStream stream = new MemoryStream(
            System.Text.ASCIIEncoding.ASCII.GetBytes("Ignore this! Hello world!")
            );

        stream.Position = 13;

        using FileStream fileStream = new FileStream("myfile.txt", FileMode.OpenOrCreate);

        await stream.CopyToAsync(fileStream);
    }

I agree that is very rare and I can not say this is important to support. I just think this is strange.

**Comment by seanmcc-msft** [comment] 2020-06-17 18:45
@pekspro, I think that's a good suggestion for UploadAsync() to check the stream position.

> Also, why does position needs to be 0? Why can not it just read the stream from the current position to the end?

See https://github.com/Azure/azure-sdk-for-net/issues/10814 for the discussion around this.

**Comment by seanmcc-msft** [comment] 2020-06-17 18:48
I'm going to close this issue, but please free to continue contributing on https://github.com/Azure/azure-sdk-for-net/issues/10814.

**Closed by seanmcc-msft** 2020-06-17 18:48 UTC
Labels: Client, Storage, customer-reported, question
