### ISSUE TITLE
CreateBatchAsync failing with "'Put token failed. status-code: 500..."

### ISSUE THREAD

**Issue by jformacek** [Azure/azure-sdk-for-net#13478] opened 2020-07-15 17:37 UTC
Hello,
using Azure.Messaging.EventHubs v5.1.0 and randomly getting error from CreateBatchAsync():
Message: Put token failed. status-code: 500, status-description: The service was unable to process the request; please retry the operation.  ...
ProblemId: Azure.Messaging.EventHubs.EventHubsException at Azure.Messaging.EventHubs.Amqp.AmqpProducer+<CreateBatchAsync>d__29.MoveNext

Code snippet below; data is produced by multiple worker tasks; all tasks send data to eventhub via single instance of EventHubProducerClient.

I may be able to privately share ID of event hub namespace/event hub, if it helps

```csharp
	EventHubProducerClientOptions ehClientOpts = new EventHubProducerClientOptions()
	{
		RetryOptions = new EventHubsRetryOptions
		{
			MaximumRetries = 10,
			Delay = TimeSpan.FromSeconds(5),
			MaximumDelay = TimeSpan.FromSeconds(10),
			Mode = EventHubsRetryMode.Fixed,
			TryTimeout = TimeSpan.FromSeconds(1)
		}
	};
	await using (EventHubProducerClient ehClient = new EventHubProducerClient(cfg.InfraConfiguration.ehNamespace, cfg.InfraConfiguration.ehName, creds, ehClientOpts))
	{
		List<Task<int>> tasks = new List<Task<int>>();
		foreach(var source in cfg.dataSources)
		{
			var config = new ProcessorConfig()
			{
				//initialize worker configuration
			};
			//run worker
			tasks.Add(Process(ehClient, config));
		}
        int[] recordsProcessed = await Task.WhenAll(tasks);
		
	}
	
	//...
	
	//worker
	private static async Task<int> Process(EventHubProducerClient ehClient, ProcessorConfig config)
	{
		try
		{
			int processed = 0;
			using (DataRequestor rq = new DataRequestor(config.appId, config.apiKey, config.batchSize))
			{
				var processingStart = config.start;
				JToken rsp = await rq.GetEvents(config.start, config.end);
				while (rq.HasMoreData())
				{
					var events = rsp["value"];
					int start = 0;
					int end = events.Count();
					while (start < end)
					{
						using EventDataBatch batch = await ehClient.CreateBatchAsync();
						while (start < end)
						{
							var data = new EventData(Encoding.UTF8.GetBytes(events[start].ToString()));
							if (!batch.TryAdd(data))
								break;
							start++;
						};
						await ehClient.SendAsync(batch);
						processed += batch.Count;
					}
					rsp = await rq.GetEvents(config.start, config.end);
				}
			}
		}
		catch(Azure.Messaging.EventHubs.EventHubsException ex)
		{
			//catch exceptions thrown by event hub producer
		}
		return processed;
	}

```

Seems similar to #10310, however it seems  to be already fixed. Not sure if this is just because exhausted retries, or something else.

Thanks for help

**Comment by jsquire** [comment] 2020-07-16 13:59
Hi @jformacek.  Thanks for moving this over to an issue.  Looking over the message, fragment of the stack trace, and code, there's a couple of thoughts that I've got and some additional information that I'd like to ask for to help.

The underlying error is occurring when the client attempts to authenticate to the Event Hubs service.  Because the service dictates the maximum size of a batch that it will accept, the first time that you create a batch for a given producer, it has to open a connection to the service to query that size.  To so that, it has to send the auth token.   That operation appears to be triggering an exception in the service.

Because the exception is triggered by the service, we may need to enlist some help from the Event Hubs service team; that would potentially be the point where someone will ask about subscriptions and EH instances.  Before we get to that point, tt would be helpful to know:

  - How authentication is being done; you're passing a `TokenCredential`.  Could you help me understand how you're forming that credential?
  - The full stack trace.  The included snippet is enough to confirm the call site, but just in case there's more to this story, it would be good to see.
 - The `Reason` of the exception.  That would help confirm that I'm not misdiagnosing the code path that was followed.
  - How frequently are you seeing the failures?
  - After you see the failures, are there any changes to the token that occur?   _(if the cause is a token issue, I'd expect it to fail consistently)_
  - Am I remembering correctly that your code is running in the context of an Azure Function?

I'm not sure if the code snippet is representative of your application or is just an illustration, but I'd like to offer a couple of thoughts:

  - It is safe to have an `EventHubProducerClient` that is long-lived.  Generally, you'll want to close or dispose (no need to do both) when you're done using it, but if you're publishing events regularly, I'd recommend caching the client rather than recreating it on each call.  If I recall, you mentioned this code running as part of an Azure Function.   If so, you may want to treat it as a "static client" in the same manner as `HttpClient` in [[this]](https://docs.microsoft.com/en-us/azure/azure-functions/manage-connections) guidance.

  - A `TryTimeout` of one second is very low and may cause some issues.  A "try" includes the time for any connections/links to the service to be established, any data transforms to be done, and service communication.   If your function is connecting to an Event Hubs instance in another data center or you're sending more than a very small bit of data, I'd suggest bumping this value up.

**Comment by jformacek** [comment] 2020-07-16 15:39
Hi Jesse,
thanks for taking this.
* How authentication is being done: Via DefaultAzureCredential - FunctionApp has assigned MSI a uses it to get token:
```csharp
                var opts = new DefaultAzureCredentialOptions();
                opts.ExcludeInteractiveBrowserCredential = true;
                var creds = new DefaultAzureCredential(opts);
```
* Stack trace: see below (extracted from appInsights and anonymized a bit; hopefully OK for purpose)
```json
[
	{
		"parsedStack": [
			{
				"assembly": "System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e",
				"method": "System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw",
				"level": 0,
				"line": 0
			},
			{
				"assembly": "Azure.Messaging.EventHubs, Version=5.2.0.0, Culture=neutral, PublicKeyToken=92742159e12e44c8",
				"method": "Azure.Messaging.EventHubs.Amqp.AmqpProducer+<CreateBatchAsync>d__29.MoveNext",
				"level": 1,
				"line": 0
			},
			{
				"assembly": "System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e",
				"method": "System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw",
				"level": 2,
				"line": 0
			},
			{
				"assembly": "System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e",
				"method": "System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess",
				"level": 3,
				"line": 0
			},
			{
				"assembly": "System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e",
				"method": "System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification",
				"level": 4,
				"line": 0
			},
			{
				"assembly": "Azure.Messaging.EventHubs, Version=5.2.0.0, Culture=neutral, PublicKeyToken=92742159e12e44c8",
				"method": "Azure.Messaging.EventHubs.Producer.EventHubProducerClient+<CreateBatchAsync>d__41.MoveNext",
				"level": 5,
				"line": 0
			},
			{
				"assembly": "System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e",
				"method": "System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw",
				"level": 6,
				"line": 0
			},
			{
				"assembly": "System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e",
				"method": "System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess",
				"level": 7,
				"line": 0
			},
			{
				"assembly": "System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e",
				"method": "System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification",
				"level": 8,
				"line": 0
			},
			{
				"assembly": "Azure.Messaging.EventHubs, Version=5.2.0.0, Culture=neutral, PublicKeyToken=92742159e12e44c8",
				"method": "Azure.Messaging.EventHubs.Producer.EventHubProducerClient+<CreateBatchAsync>d__40.MoveNext",
				"level": 9,
				"line": 0
			},
			{
				"assembly": "System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e",
				"method": "System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw",
				"level": 10,
				"line": 0
			},
			{
				"assembly": "System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e",
				"method": "System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess",
				"level": 11,
				"line": 0
			},
			{
				"assembly": "System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e",
				"method": "System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification",
				"level": 12,
				"line": 0
			},
			{
				"assembly": "System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e",
				"method": "System.Threading.Tasks.ValueTask`1.get_Result",
				"level": 13,
				"line": 0
			},
			{
				"assembly": "System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e",
				"method": "System.Runtime.CompilerServices.ValueTaskAwaiter`1.GetResult",
				"level": 14,
				"line": 0
			},
			{
				"assembly": "AiHubStreaming, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null",
				"method": "AiHubStreaming.AiDataProcessor+<Process>d__6.MoveNext",
				"level": 15,
				"line": 171,
				"fileName": "C:\\TFS\\xxxxxxxxxxxx\\EventProcessing\\EventHubStreaming\\AiHubStreaming\\AiDataProcessor.cs"
			}
		],
		"outerId": "0",
		"message": "Put token failed. status-code: 500, status-description: The service was unable to process the request; please retry the operation. For more information on exception types and proper exception handling, please refer to http://go.microsoft.com/fwlink/?LinkId=761101. (xxxxxxxxxx)",
		"type": "Azure.Messaging.EventHubs.EventHubsException",
		"id": "46433824"
	}
]
```
* Reason for exception: which field is it in App Insights exceptions log?
* How often it occurs: it's pretty random: un Tue, it was every few mins (see printscreen), but stopped occurring on Tue evening
![image](https://user-images.githubusercontent.com/13431290/87690925-4ed1ad80-c78a-11ea-9115-667726949c67.png)
* Token change related to failure: I would not say so - I get DefaulAzureCredential at beginning of every run and rely on infrastructure to cache and renew token...
* Runtime: yes, running in Azure Function App

Code is simplified real implementation - thanks for recommendation - I will incorporate and let's see!

Thanks,
Jiri

**Comment by jsquire** [comment] 2020-07-17 14:18
Thank you, Jiri.  The additional context is helpful.

> * Stack trace: see below (extracted from appInsights and anonymized a bit; hopefully OK for purpose)

Yup, this works just fine.  It confirms my initial suspicion; the error is returned by the service and isn't failing in a client path.  

> * Reason for exception: which field is it in App Insights exceptions log?

That, I do not know.  The field is `EventHubsException::Reason` on the object.   I don't recall whether AI walks the properties of the exception and breaks them down or just the message.   Given what we've now confirmed, it's probably not going to be particularly enlightening so I don't think that it's worth trying to capture.

> * How often it occurs: it's pretty random: un Tue, it was every few mins (see printscreen), but stopped occurring on Tue evening

I wonder if this correlates with a service upgrade or other service issue during that period of time?   Absent of that block of instances, have you seen anything that wasn't a single or small set of instances or a prolonged pattern?   When they're random, do you have a general idea of fequency?   Once a day/week/month ?

I'm going to reach out to some folks on the Event Hubs service team to assist and see if there's any light that the service logs can shed.

**Comment by jsquire** [comment] 2020-07-17 20:00
Hi @jformacek.  

Would you say that a good time slice to use for investigation of the incident on Tuesday would be `07/14/2020 10pm -11pm UTC`?  That seems to reflect the log that you shared.   I'd also like to ask for the namespace of your Event Hubs namespace to help with the investigation of service-side logs.  If you're not comfortable sharing that here, please let me know and we'll work out a means to share.

**Comment by jsquire** [comment] 2020-07-17 20:00
//cc: @serkantkaraca, for awareness.

**Comment by jsquire** [comment] 2020-07-18 14:54
@schaabs:  Do you mind offering thoughts about the following use of `DefaultAzureCredential` in an Azure Functions environment?   Is there anything that could potentially result in a malformed JWT or similar intermittently?

```csharp
var opts = new DefaultAzureCredentialOptions();
opts.ExcludeInteractiveBrowserCredential = true;
var creds = new DefaultAzureCredential(opts);
```

**Closed** 2020-08-09 08:00 UTC
Labels: Client, Event Hubs, Investigate, customer-reported, needs-author-feedback, no-recent-activity, question
