### ISSUE TITLE
[BUG] Exists always returns false or throws exception

### ISSUE THREAD

**Issue by cmenzi** [Azure/azure-sdk-for-net#33949] opened 2023-02-07 17:44 UTC
### Library name and version

Azure.ResourceManager.AppService 1.0.0

### Describe the bug

When asking if an AppServicePlan exists, then it return always false. 

After I created a AppServicePlanResource, I ask if this specific resource exists via

```
resourceGroup.GetAppServicePlans().Exists(rid)
```

which always return false. Getting the resource via name or by `rid` works. 

Also this ways does not work and throws an exception, that the `provider` is not known.

```
armClient.GetGenericResources().Exists(rid)
```

### Expected behavior

Both ways allows to check if an AppServicePlan exists.

### Actual behavior

Returns always false, when going via `ResourceGroup.GetAppServicePlans().Exists(rid)`
Throws exception when going via `ArmClient.GetGenericResources().Exists(rid)`

### Reproduction Steps

1. Create ResourceGroup
2. Create an AppServicePlan
3. Ask if the AppServicePlan exists

**Comment by jsquire** [comment] 2023-02-07 18:09
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by fengzhou-msft** [comment] 2023-02-09 06:39
@cmenzi please use resource name instead of id with `resourceGroup.GetAppServicePlans().Exists(name)`. 

The generic resources exception is caused by case sensitive comparison of providers when getting the api version of the resource and is fixed in this PR: #33196. Since the PR is not released, a workaround is to manually set the api version so that generic resource can get it without exception.

``` C#
ArmClientOptions options = new ArmClientOptions();
options.SetApiVersion(AppServicePlanResource.ResourceType, "2021-02-01");
ArmClient client = new ArmClient(cred, subId, options);
```

**Comment by cmenzi** [comment] 2023-02-09 12:22
Thanks @fengzhou-msft! Both ways works! Looking forward to #33196

**Comment by fengzhou-msft** [comment] 2023-02-10 08:25
The generic resource fix is released with `Azure.ResourceManager 1.4.0`.

**Closed by fengzhou-msft** 2023-02-10 08:25 UTC
Labels: App Services, Mgmt, customer-reported, question, issue-addressed
