### ISSUE TITLE
[BUG] Missing functionality in Automation namespace

### ISSUE THREAD

**Issue by nc-mlo** [Azure/azure-sdk-for-net#6428] opened 2019-05-29 06:00 UTC
**Describe the bug**
Azure Automation -> DSC -> Assigned Node to compiled configuration.
This functionality is either missing or hidden outside Automation namespace making the process of  DSC automation quite difficult

***Exception or Stack Trace***
None

**To Reproduce**

***Code Snippet***
There's quite easy to create the configuration and compile:
AutomationClient.Configurations.CreateOrUpdate
AutomationClient.CompilationJobs.Create

Unfortunately, there's missing the functionality like:
AutomationClient.Node.CreateOrUpdate

**Expected behavior**
The functionality AutomationClient.Node.CreateOrUpdate should be implemented and allow clients to assign the Compile Configuration to the Node

The workaround we're using now is Runbook using Register-AzureRmAutomationDscNode but it's just a short-term solution.

**Screenshots**
None

**Setup (please complete the following information):**
 None

**Additional context**
None

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ x ] Bug Description Added
- [ ] Repro Steps Added
- [ ] Setup information Added

**Comment by kurtzeborn** [comment] 2019-05-30 18:09
Thank you for opening this issue! We are routing it to the appropriate team for follow up.

**Comment by mbreakey3** [comment] 2019-11-07 02:16
This is by design. Unfortunately, compiling a configuration and then assigning it to a node is always a two-step process as you described.

**Comment by andyw248** [comment] 2019-12-12 02:06
Closing as per the above comment.

**Closed by andyw248** 2019-12-12 02:06 UTC
Labels: Automation, Mgmt, Service Attention, customer-reported
