### ISSUE TITLE
[QUERY] Support /Microsoft.Management/managementGroups/{groupId}/subscriptions

### ISSUE THREAD

**Issue by havlicekp** [Azure/azure-sdk-for-net#41287] opened 2024-01-16 10:11 UTC
### Library name and version

Azure.ResourceManager 1.9.0

### Query/Question

In the deprecated version of Microsoft.Azure.Management.ManagementGroups it is possible to get list of subscriptions under a managemet group by calling [GetSubscriptionsUnderManagementGroupAsync](https://learn.microsoft.com/en-us/dotnet/api/microsoft.azure.management.managementgroups.managementgroupsubscriptionsoperationsextensions.getsubscriptionsundermanagementgroupasync?view=azure-dotnet-legacy).

The GetSubscriptionsUnderManagementGroupAsync method calls this [Azure REST endpoint](https://learn.microsoft.com/en-us/rest/api/managementgroups/management-group-subscriptions/get-subscriptions-under-management-group?view=rest-managementgroups-2020-05-01&tabs=HTTP). 

Advantage of this endpoint is that the returned subscription details contain also subscription state (Active, Disabled, ..) which can help to save additional requests querying subscription states. 

I could not find any way to do this in the new SDK [Azure.ResourceManager](https://www.nuget.org/packages/Azure.ResourceManager/).

Am I missing something or this does not exist? If it doesn't is there a way to add this to the new version of the SDK?

**Comment by jsquire** [comment] 2024-01-16 13:07
Hi @havlicekp.   Thank you for reaching out and we regret that you're experiencing difficulties.   I'm going to mark this as a duplicate of #36378, which is asking the same question, and close this one out.

**Closed by jsquire** 2024-01-16 13:07 UTC
Labels: ARM, Mgmt, customer-reported, question, duplicate
