### ISSUE TITLE
Microsoft.Azure.Search 5.0.2 high memory usage

### ISSUE THREAD

**Issue by jonasbutt** [Azure/azure-sdk-for-net#4678] opened 2018-08-20 10:52 UTC
We're seeing high web server memory usage when using version _5.0.2_ of the Microsoft.Azure.Search package. Reverting back to _5.0.1_ seems to resolve the issue.  The app in question is deployed to an Azure web app running in an ASEv2. 

Anyone else experiencing this issue?

**Comment by brjohnstmsft** [comment] 2018-08-20 19:54
@jonasbutt There were no code changes in version 5.0.2, just documentation changes. The only material change is that the minimum required versions of `Microsoft.Rest.ClientRuntime` and `Microsoft.Rest.ClientRuntime.Azure` went up (from 2.3.11 to 2.3.12 and from 3.3.12 to 3.3.13, respectively). Are you observing similar issues with other Azure .NET SDKs with the same dependencies?

@shahabhijeet Is there a known issue with high memory usage in the latest version of ClientRuntime?

**Comment by jonasbutt** [comment] 2018-08-21 08:13
This was the first time we experienced such an issue. This was the diff to fix our issue:

![image](https://user-images.githubusercontent.com/11428168/44389316-ce1cbf00-a52a-11e8-84c2-9a0f4d533188.png)

**Comment by jonasbutt** [comment] 2018-08-21 08:14
This was the first time we experienced this type of memory issue with the Azure SDK. 
This was the diff to fix our issue:

![image](https://user-images.githubusercontent.com/11428168/44389316-ce1cbf00-a52a-11e8-84c2-9a0f4d533188.png)

**Comment by shahabhijeet** [comment] 2018-08-21 17:47
@jonasbutt without knowing what your scenario is, it's hard to even recommend/suggest you any workaround.
Can you let me know how can I repro this issue, but in the mean time, can you upgrade your ClientRuntime reference to the latest package version and see if that resolves the issue.

**Comment by KimihikoSaito** [comment] 2018-08-28 01:44
In my Web App with Search SDK, Microsoft.Rest.ClientRuntime 2.3.12 or above shows memory usage increasing constantly, and Private Memory never released.
![2018-08-27_09h56_25](https://user-images.githubusercontent.com/22209921/44695682-4fd29680-aaaf-11e8-98d2-490faeaa26e5.png)

**Comment by brjohnstmsft** [comment] 2018-08-28 04:52
@KimihikoSaito -- Thanks for the data. @shahabhijeet -- Can you please investigate?

**Comment by shahabhijeet** [comment] 2018-08-30 18:10
@jonasbutt @KimihikoSaito I am going to add this to our backlog and will get this investigated and fixed in our next release.
Next release will happen within a month. Will update once I know the exact date.

**Comment by kawazoe** [comment] 2018-09-20 14:18
I have noticed a similar issue in our code.

We dived in using JetBrains dotMemory and noticed that the default `RetryDelegatingHandler` in the client appears to keep a hold of every request and response that goes through the client; quickly inflating the memory usage of the client. From what I saw by decompiling the code, the bug appears to be that inside `RetryDelegatingHandler.SendAsync`, an event is registered on `this.RetryPolicy.Retrying` which I believe is never unregistered. This event handler will capture both the response and the request.

Here's a screenshot of what the memory looks like around those retry policies and what lead me to believe that they are not disposed correctly:

![image](https://user-images.githubusercontent.com/406575/45824646-7eaee780-bcbe-11e8-8b17-d5c00a9175e7.png)

**Comment by brjohnstmsft** [comment] 2018-09-20 18:30
@kawazoe Thanks for this analysis!

@shahabhijeet Does this help? Any ETA on a fix?

**Comment by shahabhijeet** [comment] 2018-10-01 23:37
@brjohnstmsft the fix has been published on nuget.org, you will need the following components
- https://www.nuget.org/packages/Microsoft.Rest.ClientRuntime/2.3.14
- https://www.nuget.org/packages/Microsoft.Rest.ClientRuntime.Azure/3.3.16

**Comment by brjohnstmsft** [comment] 2018-10-01 23:42
@kawazoe @jonasbutt @KimihikoSaito Can you try upgrading to the latest versions of Microsoft.Rest.ClientRuntime and Microsoft.Rest.ClientRuntime.Azure and let us know if that helps?

**Comment by kawazoe** [comment] 2018-10-10 15:49
I just tried the latest version of both packages and it seems to fix our problem. Memory is now GCed as expected.

**Comment by brjohnstmsft** [comment] 2018-10-15 19:47
@kawazoe Thanks for the confirming. We'll release a new version of the Azure Search SDK that references the new ClientRuntime libraries soon.

**Comment by brjohnstmsft** [comment] 2018-11-04 00:41
The new version of [Microsoft.Azure.Search](https://www.nuget.org/packages/Microsoft.Azure.Search) that points to the updated `ClientRuntime` packages is now available on NuGet.

**Closed by brjohnstmsft** 2018-11-04 00:41 UTC

**Comment by maartenoosterhoff** [comment] 2018-11-12 10:07
@brjohnstmsft 
I'm a colleague of @jonasbutt, and we have tried the lastest version of both packages, and indeed, I can confirm the fixes seems to be fixed.

**Comment by fabiomaulo** [comment] 2018-11-25 04:40
We are using the 5.0.3 with restclient 2.3.17 and RestClientAzure 3.3.18 but the memory leak is still there
Last 24hs
![image](https://user-images.githubusercontent.com/125039/48975604-192afe80-f053-11e8-8362-5991b183ba37.png)

**Comment by brijesh1ec** [comment] 2018-11-25 12:07
AZ 200 Certificate? any suggestion on this

**Comment by fabiomaulo** [comment] 2018-11-27 02:49
Ok Bruce, I'll try before with 5.0.1 and then 5.0.3 overriding the version of clientRuntime.
Just give me a few days to organize the "_Fire in the hole_" version of that API.
P.D. For the vNext of the SDK, please, use netstandard2.0 instead of 1.4 (there is a known issue with System.Net.Http when you mix with fullFW).

**Comment by brjohnstmsft** [comment] 2018-11-27 02:57
@fabiomaulo The target framework for all Azure .NET SDKs is managed centrally, so the Search SDK will support netstandard2.0 when the rest of the Azure SDKs do. There's a discussion about this [here](https://github.com/Azure/azure-sdk-for-net/issues/4927).

**Comment by maartenoosterhoff** [comment] 2018-12-13 21:03
@fabiomaulo Any news?
