### ISSUE TITLE
[FEATURE REQ] EventHubsSharedAccessKeyCredential and ServiceBusSharedAccessKeyCredential

### ISSUE THREAD

**Issue by ramya-rao-a** [Azure/azure-sdk-for-net#15887] opened 2020-10-13 00:42 UTC
**Library or service name.**
Azure Service Bus and Azure Event Hubs
 
**Is your feature request related to a problem? Please describe.**

Today, the clients in Azure.Messaging.EventHubs and Azure.Messaging.ServiceBus libraries allow client construction using connection string which can either have the SharedAccessSignature (SAS token) directly in it or have the SharedAccessKey & SharedAccessKeyName in it using which the client can then create the SharedAccessSignature

But this model does not allow the user to rotate their keys or the SAS token once the client is created.
This feature request is to introduce a SharedAccessKeyCredential class to resolve this.

Design requirements:

- Since the SharedAccessSignature generation is very specific to EventHubs and ServiceBus services, the classes should have the service name as a prefix in their name
- New client constructor overload which would be similar to the one that takes the TokenCredential.
- The SharedAccessKeyCredential class is expected to have 2 constructor overloads
    - One that takes the SharedAccessSignature 
    - The other that takes the SharedAccessKeyName and SharedAccessKey
- User must be able to set/get the `SharedAccessSignature` or the `SharedAccessKey` or the `SharedAccessKeyName` after the class has been instantiated to allow the rotation of credential. The next Service Bus and Event Hubs client attempt to renew the access token, would use the updated properties on the credential

Open questions:
- Should the `SharedAccessSignature` property reflect only user provided value and be null if the class was instantiated using the key?
- Should the `SharedAccessSignature` property be settable when the class was instantiated using the key?

**Comment by ramya-rao-a** [comment] 2020-10-13 00:42
cc @jsquire, @JoshLove-msft, @MiYanni

**Comment by jsquire** [comment] 2020-10-13 13:45
Closing as a dupe of #9048.   We'll extend the scope of that to cover service bus as well.

**Closed by jsquire** 2020-10-13 13:45 UTC
Labels: Client, Event Hubs, Service Bus, needs-team-triage
