### ISSUE TITLE
[FEATURE REQ] Event Hubs: Lazy allocation of Properties and System Properties in EventData

### ISSUE THREAD

**Issue by snakefoot** [Azure/azure-sdk-for-net#19832] opened 2021-03-25 18:45 UTC
**Library or service name:**
`Azure.Messaging.EventHubs`
 
**Is your feature request related to a problem?**
Allow publishing EventData-objects without allocating Dictionary for SystemProperties

**Current Workaround:**
```c#
private class EventDataLight : EventData
{
  static readonly IReadOnlyDictionary<string, object> DefaultSystemProperties = new Dictionary<string, object>();

  public EventDataLight(byte[] eventBody, string partitionKey)
    :base(eventBody, null, DefaultSystemProperties, partitionKey: partitionKey)
  {
  }
}
```

**Worked in previous version**
`Microsoft.Azure.EventHubs`

**Comment by jsquire** [comment] 2021-03-25 21:26
Hi @snakefoot.  Thank you for your feedback.  I agree that it would be helpful to make a lazy allocation for the dictionaries rather than the current eager approach.   I'm going put this on the Event Hubs backlog for us to look into.

I also wanted to mention that you're snippet is using a constructor that was intended for mocking support and may not be doing what you believe that it is.   Specifically, the `partitionKey` that you're passing is being used to populate the `PartitionKey` member which is informational for received events and isn't used when publishing.  

https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/eventhub/Azure.Messaging.EventHubs/src/EventData.cs#L118-126

To publish events using a partition key, you'll need to specify the key when creating your `EventDataBatch` or as part of the `SendEventOptions` if publishing without a batch.  [This sample](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/eventhub/Azure.Messaging.EventHubs/samples/Sample04_PublishingEvents.md#publishing-events-with-a-partition-key) illustrates.

**Comment by jsquire** [comment] 2021-03-26 12:45
> Good to know. Was planning to use this method, but I guess you made it as a trap:

Not it all; that method is a valid approach for publishing when you'd prefer to avoid the overhead of creating and managing an explicit batch by taking on the risk that your set of events may be too large and fail with an exception.

Using that overload, the set of events is still packaged and sent as a logical batch in a single service call.   Because of this, when using a partition key, every event must have the same key.  Setting the partition key on each event creates a pit of failure, where it is easy to have events with multiple keys in a set, ensuring that publishing of that set could never succeed. 

If you're using a partition key, you'll want this overload instead.   The [`SendEventOptions`](https://docs.microsoft.comdotnet/api/azure.messaging.eventhubs.producer.sendeventoptions) allows you to specify a partition key (or partition identifier) that gets applied to the entire set being published.

```cs
public virtual async Task SendAsync(IEnumerable<EventData> eventBatch,
                                    SendEventOptions options,
                                    CancellationToken cancellationToken = default);
```

**Comment by snakefoot** [comment] 2021-03-27 11:06
> Setting the partition key on each event would create a pit of failure where it is easy to have events with multiple keys in a set, ensuring that publishing of that set could never succeed.

Since the method can already fail if the batch is too large, then it would also ok if the method failed when having mixed partition-keys. But I guesss it reduces overhead on the receiving side, that one can skip the validation.

Again thank you for the help and directions.

**Comment by snakefoot** [comment] 2021-03-27 16:26
@jsquire I have a bonus question about specifying ContentType (Ex. `application/json`). Would this be the correct way:

```c#
if (!string.IsNullOrEmpty(eventDataContentType))
   eventData.Properties.Add(Microsoft.Azure.Amqp.Framing.Properties.ContentTypeName, eventDataContentType);
```

**Comment by jsquire** [comment] 2021-03-29 14:31
That snippet will add an application property named `content-type` to the AMQP message, but will not set the `content-type` field in the AMQP properties section.   Unfortunately, that's not going to help if you're looking to do any AMQP-based interop, but is historically how Event Hubs has recommended representing the concept.   

We're in the process of finalizing a full model to allow manipulating the AMQP message format for interop and advanced scenarios, but it isn't quite finished yet.   Service Bus has been the test bed for this, and once we have the design finalized across languages, we'll be brining it over to Event Hubs as well.   If you're interested in the current form, which still has some gaps, the Service Bus implementation can be seen:

- [ServiceBusMessage](https://docs.microsoft.com/dotnet/api/azure.messaging.servicebus.servicebusmessage): Note the top-level properties for well-known AMQP message properties
- [ServiceBusMessage::GetRawAmqpMessage](https://docs.microsoft.com/dotnet/api/azure.messaging.servicebus.servicebusmessage.getrawamqpmessage): Allows access to an AMQP representation of the message/event.
- [AmqpAnnotatedMessate](https://docs.microsoft.com/dotnet/api/azure.core.amqp.amqpannotatedmessage): The AMQP message representation of a message/event

**Comment by snakefoot** [comment] 2021-03-29 14:50
When changing from `Microsoft.Azure.EventHubs` to `Azure.Messaging.EventHubs` then it is no longer possible to assign [EventData.ContentType](https://github.com/Azure/azure-sdk-for-net/blob/2b594335737a65cb8f36543ef817deaba5c43f4b/sdk/eventhub/Microsoft.Azure.EventHubs/src/EventData.cs#L80) ?

**Comment by jsquire** [comment] 2021-03-29 14:55
Correct; it is not.  When consuming events published by the legacy library which have that field set, the value will be available via the `SystemProperties` member of `EventData` but does not yet exist in a well-known attribute.

**Comment by snakefoot** [comment] 2021-03-29 14:57
But it is not possible to set the ContentType when being the producer of EventData? Or can it be done by added a SystemProperty ?

**Comment by jsquire** [comment] 2021-03-29 15:00
It is not possible currently.  The system properties are broker-owned; they're not sent to the service when publishing.

**Comment by jsquire** [comment] 2021-03-29 21:28
The enhancement has merged and will be included with our next release.   I'm going to close this out; please feel free to reopen if you believe that further discussion is needed.

**Closed by jsquire** 2021-03-29 21:28 UTC
Labels: Client, Event Hubs, customer-reported, feature-request

**Comment by snakefoot** [comment] 2021-03-30 07:25
No I'm very happy with the implementation of lazy-allocation. Thank you for the fast turn-around.
