### ISSUE TITLE
GetEntityOrNullAsync

### ISSUE THREAD

**Issue by fabiomaulo** [Azure/azure-sdk-for-net#27419] opened 2022-03-08 18:47 UTC
### Library name

Azure.Data.Tables

### Descrption

The matter that we have an `Azure.RequestFailedException` in front of an unexistent entity sounds like a regression to the dawn of Azure SDK.
You already have a 404 but, when I'm trying to read the value you throw me an exception with the status-code 404.
My use-case has some write-once properties so I can´t use Upsert with the merge.
A `GetEntityOrNull`, and its pair `GetEntityOrNullAsync`, would be very useful to avoid the noise of `try-catch` and the performance issue of throwing the exception (and its call-stack).
Thanks

**Comment by fabiomaulo** [comment] 2022-03-08 19:10
An alternative could be an extension method as `TryGetEntity` with the behavior similar to the `IDictionary<T>.TryGetValue`

**Comment by jsquire** [comment] 2022-03-08 20:57
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by christothes** [comment] 2022-03-08 22:23
Duplicate of #25626

**Closed by christothes** 2022-03-08 22:23 UTC
Labels: Client, customer-reported, question, Tables, needs-team-attention
