### ISSUE TITLE
[QUESTION] EventBatch doesn't clear after being sent

### ISSUE THREAD

**Issue by ArmandoLacerda** [Azure/azure-sdk-for-net#16030] opened 2020-10-16 02:31 UTC
**Describe the bug**
When sending multiple messages through the eventBatch helper, it doesn't clear out after the batch is submitted. I have a 5MB payload to send to the hub. I break the payload in many smaller messages and loop through them, adding them up to the eventBatch until it gets close to 1MB. Then I invoke producerClient.SendAsync() to submit the batch and resume the loop for the next collection of messages. eventBatch doesn't zero out and the loop tries to resubmit the same batch. The eventBatch.SizeInBytes still shows the already submitted payload. 

**Expected behavior**
After invoking producerClient.SendAsync(eventBatch) I expect to get a clean batch to start filling up with new messages.

**Actual behavior (include Exception or Stack Trace)**
The eventBatch does not clear out. It is of no use in a loop to send a payload larger than 1MB. 

**To Reproduce**
A slightly modified version of the sample [official sample](https://docs.microsoft.com/en-us/azure/event-hubs/event-hubs-dotnet-standard-getstarted-send#write-code-to-send-messages-to-the-event-hub): 

`
public static void trySendingMultipleBatches()
{
    {
        // Create a producer client that you can use to send events to an event hub
        await using (var producerClient = new EventHubProducerClient(connectionString, eventHubName))
        {
            // Create a batch of events 
            using EventDataBatch eventBatch = await producerClient.CreateBatchAsync();

            // Try 3 batches 
            for (int i = 0; i < 3; i++)
            {

                while (eventBatch.SizeInBytes < 800000)
                {
                    // Add events to the batch. An event is a represented by a collection of bytes and metadata. 
                    eventBatch.TryAdd(new EventData(Encoding.UTF8.GetBytes("First event")));
                    eventBatch.TryAdd(new EventData(Encoding.UTF8.GetBytes("Second event")));
                    eventBatch.TryAdd(new EventData(Encoding.UTF8.GetBytes("Third event")));
                }
                // Use the producer client to send the batch of events to the event hub
                await producerClient.SendAsync(eventBatch);
                Console.WriteLine("A batch of about 1MB has been published.");
            }
        }
    }
}

`

**Environment:**
 - Azure.Messaging.EventHubs 5.2.0

 - Hosting platform or OS and .NET runtime version (`dotnet --info`)
.NET Core SDK (reflecting any global.json):
 Version:   3.1.300
 Commit:    b2475c1295

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.300\

Host (useful for support):
  Version: 3.1.4
  Commit:  0c2e69caa6

.NET Core SDKs installed:
  3.1.300 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.18 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.18 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.18 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

 - Visual Studio Code 
Version: 1.50.1 (user setup)
Commit: d2e414d9e4239a252d1ab117bd7067f125afd80a
Date: 2020-10-13T15:06:15.712Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.18363

**Comment by jsquire** [comment] 2020-10-16 13:49
Hi @ArmandoLacerda, thank you for reaching out and your feedback.   The behavior that you're describing is by-design; `EventDataBatch` instances are intended to be single use for most scenarios, with the notable exception being when you want to resend a set of events.   

For sending multiple batches of distinct events, a new batch should be created after each publish operation.  [This sample](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/eventhub/Azure.Messaging.EventHubs/samples/Sample04_PublishMultipleEventBatches.cs) illustrates one approach for doing so.

In your snippet above, the pattern that you're using isn't ideal for taking advantage of the batch.  Instead of:
```csharp
while (eventBatch.SizeInBytes < 800000)
{
    // ...
}
```
 I'd advise something similar to:

```csharp

var batchOptions = new CreateBatchOptions
{
    MaximumSizeInBytes = 800000
};

for (var count = 0; count < 3; ++count)
{
    using var batch = await producerClient.CreateBatchAsync(batchOptions);

    // --
    // Add events until batch.TryAdd  returns false.
    //-- 
      
    await producerClient.SendAsync(eventBatch);
}
```

That said, I'm not sure of your intent to constraining the batch to a specific size.   By default `CreateBatchAsync` will query the Event Hubs service to understand the size limit for the associated Event Hub.   If you're using a n Event Hubs instance with a 256k limit, the resulting batch will be limited to 256k.   Likewise, if you are using an instance that allows 1mb or 5mb, the resulting batch will allow that size.   By not explicitly specifying the size, your code will automatically adapt to the limit without you needing to track the specifics.

**Comment by ArmandoLacerda** [comment] 2020-10-16 18:28
Thanks for your reply, @jsquire . Please help me to understand this in regards to eventBatch dynamically adjusting the batch size.

If I create a 5MB batch in send it, will SendAsync + eventBatch break the full payload in multiple submissions and get the full payload pushed to the hub? Or will it discard the tail end of the payload that didn't fit in the maxSize? 

I didn't get from the documentation whether it would go one way or another so I coded the size control myself.

**Comment by jsquire** [comment] 2020-10-16 22:04
> If I create a 5MB batch in send it, will SendAsync + eventBatch break the full payload in multiple submissions and get the full payload pushed to the hub? Or will it discard the tail end of the payload that didn't fit in the maxSize?

The `EventDataBatch` is scoped to a single operation.   It won't allow you to add more events to it than can be sent in one `SendAsync` call. The `EventDataBatch` knows the maximum size for a single send operation allowed by the service.  It will not allow that size to be exceeded by returning `false` when you call its `TryAdd` method.   So long as `TryAdd` returns `true`, you know that your event was accepted into the batch and will fit into a single send call.   

The caller has responsibility for honoring the `TryAdd` return value.  If that return is `false`, your event was not accepted into the batch because the size would be exceeded.   That's the signal to send the current batch and create a new one if you have events left to publish.  If you continue to `TryAdd` when the batch is full, the batch will not accept it and will not track it.

**Comment by ArmandoLacerda** [comment] 2020-10-16 22:46
Thanks for the answer, @jsquire. That is what I taught. 
I get it is by design, so flagging it as a bug as I did might have been a mistake. 
I'd turn it into a suggestion, though. The API should support sending multiple batches without requiring to re-acquire or rebuild a new ProducerClient, since I can't get a new eventBatch from the same ProducerClient instance. 
During my tests recreating the ProducerClient consumed some time, introducing some delay. 
Thanks again.

**Comment by jsquire** [comment] 2020-10-17 17:06
> since I can't get a new eventBatch from the same ProducerClient instance.

I'd like to ask about this statement, if you'd be so kind.  There is no need to recreate the client and, in fact, doing so incurs the cost of creating a new connection each time, which is not the pattern that we'd recommend unless there was some reason that the application needed to be very conservative with resource use.

The `EventHubProducerClient` is safe to cache and use for the lifetime of an application, and that is best practice when the application publishes events regularly or semi-regularly.  The producer holds responsibility for efficient resource management, working to keep resource usage low during periods of inactivity and manage health during periods of higher use.  Calling either the `CloseAsync`  or `DisposeAsync` method as the application is shutting down will ensure that network resources and other unmanaged objects are properly cleaned up.

A common question for the `EventHubProducerClient` is why does it implement `IAsyncDisposable` if it is safe to treat as long-lived? This was done partially for convenience in scenarios where publishing is very infrequent and resources are a concern for the application, and partially to mimic the pattern of the `HttpClient`.  To be transparent, I regret that we did so, and until very recently, our documentation around that has been lacking.

**Comment by ArmandoLacerda** [comment] 2020-10-19 17:52
Hi @jsquire, 
I am have to read the documentation again. I might have something wrong. The samples I've found on docs.microsoft.com never test TryAdd() return. I found another sample code in Python that leaves it raise an exception to send the batch, loosing the last message.

Apparently not the best samples.

In any case, I can't see a way to recycle the the batch Once the batch fills up I can submit it, but it doesn't zero out after being sent. I tried the Dispose() method but the batch failed with invalid stated (disposed). 

Could you point me to a good documentation and samples on the best practice on recycling the batch without reestablish the connection, please?

**Comment by jsquire** [comment] 2020-10-20 14:34
I would start with [this sample](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/eventhub/Azure.Messaging.EventHubs/samples/Sample04_PublishMultipleEventBatches.cs) as a basis and hoist the `EventHubProducerClient` instance into a member variable for the class or whatever scope is appropriate for your application.   We also use a variant of this approach in our [test infrastructure](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/eventhub/Azure.Messaging.EventHubs.Shared/src/Testing/EventGenerator.cs#L86) which may offer some additional perspective.

**Comment by ArmandoLacerda** [comment] 2020-10-20 18:16
Thanks for the links, @jsquire . The sample you point to in GitHub, doesn't it miss to send the last event that couldn't be added to the batch? 
I am going to try this again, but last time when I tried something like this the SendAsync() did not accept new messages in itself. I might have done something wrong. I'll keep you posted.

**Comment by jsquire** [comment] 2020-10-20 18:28
There's a [known bug](https://github.com/Azure/azure-sdk-for-net/issues/14095) in that sample where failure to add to a batch could drop an event.  But it will send the last event that is dequeued otherwise.

Our nightly tests send multiple batches using a single client instance, for example [here](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/eventhub/Azure.Messaging.EventHubs/tests/Producer/EventHubProducerClientLiveTests.cs#L819) as do our stress tests.   I'm happy to assist with difficulties, but I'm confident that the scenario is supported and tested.

**Comment by ArmandoLacerda** [comment] 2020-10-22 12:26
Hi @jsquire, some follow up on this:
I changed the code following the samples (best practice?) above. It works as expected most of the times. I don't know what I was doing wrong before when eventBatch as failing with invalid state. But now the code works almost every time.
There is some occasions when I get an exception, though, when calling SendAsync(). It fails saying "invalid object reference". This is just in few times that I am still tracing. Something around 1 in 1,000 function invocations. 
Overall I am in better shape with the code. Thanks for sharing the directions.
And my suggestion stands: I think the documentation and samples (especially the ones Google brings up at the top) should get some more love. :) 
Thanks again.

**Comment by jsquire** [comment] 2020-10-22 12:41
> There is some occasions when I get an exception, though, when calling SendAsync(). It fails saying "invalid object reference". This is just in few times that I am still tracing. Something around 1 in 1,000 function invocations.

I can't do more than speculate without context, but I suspect that's something at the network level.   If you happen to have a stack trace and additional details (like the exception type name) for that, I'd be very interested in taking a look.

**Comment by ArmandoLacerda** [comment] 2020-10-22 13:40
@jsquire , here is the stack trace. The code runs from an Azure Function listening to a storage account queue. At times we have a couple hundred instances of the function running in parallel. All EventHub objects are instance objects (as opposed to static objects).
 
`System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Azure.Amqp.AmqpLink.SendDelivery(Delivery delivery)
   at Microsoft.Azure.Amqp.AmqpLink.<>c.<Microsoft.Azure.Amqp.IWorkDelegate<Microsoft.Azure.Amqp.Delivery>.Invoke>b__67_0(AmqpLink thisPtr, Delivery paramDelivery, Int32 p1, Int32 p2, Int32 p3)
   at Microsoft.Azure.Amqp.AmqpLink.DoActionIfNotClosed[T1,T2,T3,T4](Func`6 action, T1 p1, T2 p2, T3 p3, T4 p4)
   at Microsoft.Azure.Amqp.AmqpLink.Microsoft.Azure.Amqp.IWorkDelegate<Microsoft.Azure.Amqp.Delivery>.Invoke(Delivery delivery)
   at Microsoft.Azure.Amqp.SerializedWorker`1.DoWorkInternal(T work, Boolean fromList)
   at Microsoft.Azure.Amqp.SerializedWorker`1.DoWork(T work)
   at Microsoft.Azure.Amqp.AmqpLink.StartSendDelivery(Delivery delivery)
   at Microsoft.Azure.Amqp.AmqpLink.TrySendDelivery(Delivery delivery)
   at Microsoft.Azure.Amqp.SendingAmqpLink.Microsoft.Azure.Amqp.IWorkDelegate<Microsoft.Azure.Amqp.AmqpMessage>.Invoke(AmqpMessage message)
   at Microsoft.Azure.Amqp.SerializedWorker`1.DoWorkInternal(T work, Boolean fromList)
   at Microsoft.Azure.Amqp.SerializedWorker`1.DoWork(T work)
   at Microsoft.Azure.Amqp.SendingAmqpLink.SendAsyncResult.Start()
   at Microsoft.Azure.Amqp.WorkCollection`3.StartWork(TKey key, TWork work)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Amqp.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at Microsoft.Azure.Amqp.SendingAmqpLink.EndSendMessage(IAsyncResult result)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at Azure.Messaging.EventHubs.Amqp.AmqpProducer.SendAsync(Func`1 messageFactory, String partitionKey, CancellationToken cancellationToken)
   at Azure.Messaging.EventHubs.Amqp.AmqpProducer.SendAsync(Func`1 messageFactory, String partitionKey, CancellationToken cancellationToken)
   at Azure.Messaging.EventHubs.Amqp.AmqpProducer.SendAsync(EventDataBatch eventBatch, CancellationToken cancellationToken)
   at Azure.Messaging.EventHubs.Producer.EventHubProducerClient.SendAsync(EventDataBatch eventBatch, CancellationToken cancellationToken)
   at Azure.Messaging.EventHubs.Producer.EventHubProducerClient.SendAsync(EventDataBatch eventBatch, CancellationToken cancellationToken)`

**Comment by jsquire** [comment] 2020-10-22 15:50
Thanks, @ArmandoLacerda.   That stack trace definitely supports the speculation that something is misbehaving at the network level.   That said, I've never run into that particular error and it's being generated by the transport library that the Event Hubs SDK is built on.   I'm going to pull in some additional folks to help take a look at that.

**Comment by jsquire** [comment] 2020-10-22 15:55
@serkantkaraca,  @hmlam, @xinchen10:   Would you mind taking a look at the stack trace a couple of comments above and offering your thoughts?  I've not seen this issue before, and seems to be down on the lower levels of the AMQP library.

The exception and message are generic enough that I don't see a clean path to detect and transform into a form that we could consider it transient and retry automatically - and I'm not sure that would be a safe option in this particular ase.

Any thoughts that you may have as to prevention within the host application or mitigation within the client library would be welcome.

**Comment by ArmandoLacerda** [comment] 2020-10-22 16:26
@jsquire , chatting about this internally in my team we suspect it may have something to do with how Azure Functions control TCP connections. I've not investigated that in depth yet, though.

**Comment by jsquire** [comment] 2020-10-29 20:14
Hi @ArmandoLacerda.  Apologies for the delay;  I've been working with the folks that own the AMQP transport library to figure out what was making it cranky.   The best repro that we found to match the exception scenario is when an trying to publish an empty batch.   The transport made certain assumptions about message internals without validating them and the client was assuming that the transport was detecting that there was nothing to send.

Coincidentally, we made a change to the client as part of the v5.3.0-beta work to do an empty check and short-circuit to avoid paying the transport cost.   That should serve as a mitigation for what you're seeing, assuming that we've got the right root cause.

**Comment by ArmandoLacerda** [comment] 2020-10-29 21:54
Hi @jsquire , I can definitely give the beta SDK a try. But I can assure you the batch was not empty. The Azure Function logs every send request and it's size in bytes for tracing and auditing. All batches had messages in them.

**Comment by jsquire** [comment] 2020-10-30 13:00
Thanks, @ArmandoLacerda.   I'm going to open an issue in the repo for the AMQP library and share details there.   I'll link it from this thread once it's open.

**Comment by ArmandoLacerda** [comment] 2020-10-30 13:55
@jsquire, meanwhile my technical manager asked me to try the same operation but using the Azure Function's biding feature instead of the SDK. He believes it will manage the network bits better, specially the TCP connection pool. I'll keep this thread updated as I test that.

**Comment by jsquire** [comment] 2020-10-30 16:25
Hi @ArmandoLacerda.   I've opened [#169](https://github.com/Azure/azure-amqp/issues/169) in the repo for the AMQP library.   Please feel free to add any additional thoughts there that I failed to capture or correct me on any misstatements.  In order to avoid bifurcating the conversation, I'm going to close this out.   

Please feel free to reopen if there is anything that you'd like to discuss regarding the batch itself or other bits of the Event Hubs client.

**Closed by jsquire** 2020-10-30 16:25 UTC
Labels: Client, Event Hubs, customer-reported, needs-team-attention, question
