### ISSUE TITLE
[BUG]Azure SDK issues in Xamarin.iOS

### ISSUE THREAD

**Issue by HolguinTech** [Azure/azure-sdk-for-net#19517] opened 2021-03-15 01:36 UTC
**Describe the bug**
I am using Microsoft.AspNetCore.SignalR, in the same project I refer to Azure.Storage.Blods. When the HubConenectionBuilder instance is created an excpcion is generated. It also generates an exception using the HttpClient class
The project in Xamarin.Android works perfectly

**Expected behavior**
Hub created

**Actual behavior (include Exception or Stack Trace)**

```text
Exception: Microsoft.AspNetCore.SignalR.Protocol.JsonHubProtocol

{System.TypeInitializationException: The type initializer for 'Microsoft.AspNetCore.SignalR.Protocol.JsonHubProtocol' threw an exception. ---> System.MissingMethodException: Method not found: int System.Text.Encodings.Web.TextEncoder.FindFirstCharacterToEncodeUtf8(System.ReadOnlySpan`1<byte>)
  at System.Text.Json.JsonEncodedText.EncodeHelper (System.ReadOnlySpan`1[T] utf8Value, System.Text.Encodings.Web.JavaScriptEncoder encoder) [0x00000] in <7e3a59f5e4004edbb4b17c580799cc52>:0 
  at System.Text.Json.JsonEncodedText.TranscodeAndEncode (System.ReadOnlySpan`1[T] value, System.Text.Encodings.Web.JavaScriptEncoder encoder) [0x00033] in <7e3a59f5e4004edbb4b17c580799cc52>:0 
  at System.Text.Json.JsonEncodedText.Encode (System.ReadOnlySpan`1[T] value, System.Text.Encodings.Web.JavaScriptEncoder encoder) [0x00014] in <7e3a59f5e4004edbb4b17c580799cc52>:0 
  at System.Text.Json.JsonEncodedText.Encode (System.String value, System.Text.Encodings.Web.JavaScriptEncoder encoder) [0x00014] in <7e3a59f5e4004edbb4b17c580799cc52>:0 
  at Microsoft.AspNetCore.SignalR.Protocol.JsonHubProtocol..cctor () [0x00000] in <866b002ba1594d309fc3acc36f2aeb50>:0 
   --- End of inner exception stack trace ---
  at (wrapper managed-to-native) System.Reflection.RuntimeConstructorInfo.InternalInvoke(System.Reflection.RuntimeConstructorInfo,object,object[],System.Exception&)
  at System.Reflection.RuntimeConstructorInfo.InternalInvoke (System.Object obj, System.Object[] parameters, System.Boolean wrapExceptions) [0x00005] in /Library/Frameworks/Xamarin.iOS.framework/Versions/Current/src/Xamarin.iOS/mcs/class/corlib/System.Reflection/RuntimeMethodInfo.cs:936 
--- End of stack trace from previous location where exception was thrown ---

  at Framework.Test.Mobile.Services.SignalRService.InitializeAsync () [0x00039] in C:\HolguinTech\repos\Projects Framework\Framework.Test\Framework.Test.Mobile\Framework.Test.Mobile\Services\SignalR\SignalRService.cs:24 
  at Framework.Test.Mobile.App.InitSignlR () [0x00008] in C:\HolguinTech\repos\Projects Framework\Framework.Test\Framework.Test.Mobile\Framework.Test.Mobile\App.xaml.cs:33 
  at Framework.Test.Mobile.App..ctor () [0x0001d] in C:\HolguinTech\repos\Projects Framework\Framework.Test\Framework.Test.Mobile\Framework.Test.Mobile\App.xaml.cs:16 
  at Framework.Test.Mobile.iOS.AppDelegate.FinishedLaunching (UIKit.UIApplication app, Foundation.NSDictionary options) [0x00007] in C:\HolguinTech\repos\Projects Framework\Framework.Test\Framework.Test.Mobile\Framework.Test.Mobile.iOS\AppDelegate.cs:26 
  at (wrapper managed-to-native) UIKit.UIApplication.UIApplicationMain(int,string[],intptr,intptr)
  at UIKit.UIApplication.Main (System.String[] args, System.IntPtr principal, System.IntPtr delegate) [0x00005] in /Users/builder/azdo/_work/1/s/xamarin-macios/src/UIKit/UIApplication.cs:86 
  at UIKit.UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName) [0x0000e] in /Users/builder/azdo/_work/1/s/xamarin-macios/src/UIKit/UIApplication.cs:65 
  at Framework.Test.Mobile.iOS.Application.Main (System.String[] args) [0x00001] in C:\HolguinTech\repos\Projects Framework\Framework.Test\Framework.Test.Mobile\Framework.Test.Mobile.iOS\Main.cs:17 }	System.TypeInitializationException
```

**To Reproduce**
Steps to reproduce the behavior (include a code snippet, screenshot, or any additional information that might help us reproduce the issue)

1. Create a Xamarin project
2. Use Microsoft.AspNetCore.AsignalR.Cliente
```csharp
public Task InitializeAsync() {
            try {
                connection = new HubConnectionBuilder()
                    .WithUrl("https://kjkjkjkjkjkj.azurewebsites.net/talkhub")
                    .Build();
                connection.Closed += async (error) => {
                    await connection.StartAsync();
                };
            } catch (Exception ex) {
                throw ex;
            }
            return Task.FromResult(true);
        }
```

**Environment:**
Microsoft Visual Studio Enterprise 2019
Version 16.9.1
VisualStudio.16.Release/16.9.1+31105.61
Microsoft .NET Framework
Version 4.8.04084

Installed Version: Enterprise

Visual C++ 2019   00433-90000-00004-AA259
Microsoft Visual C++ 2019

ADL Tools Service Provider   1.0
This package contains services used by Data Lake tools

ASA Service Provider   1.0

ASP.NET and Web Tools 2019   16.9.688.6828
ASP.NET and Web Tools 2019

ASP.NET Core Razor Language Services   16.1.0.2112521+5741df381174d72f08e3632bb99f52e8635b6a1a
Provides languages services for ASP.NET Core Razor.

ASP.NET Web Frameworks and Tools 2019   16.9.688.6828
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   16.9.688.6828
Azure App Service Tools v3.0.0

Azure Data Lake Node   1.0
This package contains the Data Lake integration nodes for Server Explorer.

Azure Data Lake Tools for Visual Studio   2.6.1000.0
Microsoft Azure Data Lake Tools for Visual Studio

Azure Functions and Web Jobs Tools   16.9.688.6828
Azure Functions and Web Jobs Tools

Azure Stream Analytics Tools for Visual Studio   2.6.1000.0
Microsoft Azure Stream Analytics Tools for Visual Studio

C# Tools   3.9.0-6.21124.20+db94f4cc8c78a7cd8cf9cfdae091158d2ba9d974
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Cookiecutter   16.9.21026.1
Provides tools for finding, instantiating and customizing templates in cookiecutter format.

Dotfuscator Community Edition   5.42.0.9514-e0e25f754
PreEmptive Protection - Dotfuscator CE

Extensibility Message Bus   1.2.6 (master@34d6af2)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

Fabric.DiagnosticEvents   1.0
Fabric Diagnostic Events

IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info

Microsoft Azure HDInsight Azure Node   2.6.1000.0
HDInsight Node under Azure Node

Microsoft Azure Hive Query Language Service   2.6.1000.0
Language service for Hive query

Microsoft Azure Service Fabric Tools for Visual Studio   16.0
Microsoft Azure Service Fabric Tools for Visual Studio

Microsoft Azure Stream Analytics Language Service   2.6.1000.0
Language service for Azure Stream Analytics

Microsoft Azure Stream Analytics Node   1.0
Azure Stream Analytics Node under Azure Node

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2019 - v2.9.40218.1

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   2.1.113+g422d40002e.RR
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

Mono Debugging for Visual Studio   16.9.7 (df23ba6)
Support for debugging Mono processes with Visual Studio.

Node.js Tools   1.5.21130.2 Commit Hash:dacc0e71a5e060cdcab466a301cacea359c1b6da
Adds support for developing and debugging Node.js apps in Visual Studio

NuGet Package Manager   5.9.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

Progress Telerik UI for Xamarin Extension   2021.1.108.2
Progress® Telerik® UI for Xamarin Extension

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Python   16.9.21026.1
Provides IntelliSense, projects, templates, debugging, interactive windows, and other support for Python developers.

Python - Conda support   16.9.21026.1
Conda support for Python projects.

Python - Django support   16.9.21026.1
Provides templates and integration for the Django web framework.

Python - IronPython support   16.9.21026.1
Provides templates and integration for IronPython-based projects.

Python - Profiling support   16.9.21026.1
Profiling support for Python projects.

Snapshot Debugging Extension   1.0
Snapshot Debugging Visual Studio Extension Detailed Info

SQL Server Data Tools   16.0.62102.01130
Microsoft SQL Server Data Tools

ToolWindowHostedEditor   1.0
Hosting json editor into a tool window

TypeScript Tools   16.0.30201.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   3.9.0-6.21124.20+db94f4cc8c78a7cd8cf9cfdae091158d2ba9d974
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   16.9.0-beta.21102.9+7ce7132f1459095e635194d09d6f73265352029a
Microsoft Visual F# Tools

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Container Tools Extensions   1.0
View, manage, and diagnose containers within Visual Studio.

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

Visual Studio Tools for Kubernetes   1.0
Visual Studio Tools for Kubernetes

Visual Studio Tools for Unity   4.9.1.0
Visual Studio Tools for Unity

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Foo   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   16.9.000.271 (d16-9@863670b)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   16.9.0.316 (remotes/origin/d16-9@fdbf64026)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   16.9.68 (8e9b569)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   11.2.0.21 (d16-9/93eab59)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: 5e9cb6d
    Java.Interop: xamarin/java.interop/d16-9@d6d86b2
    ProGuard: Guardsquare/proguard/v7.0.1@912d149
    SQLite: xamarin/sqlite/3.34.1@daff8f4
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-9@9d8924d

Xamarin.iOS and Xamarin.Mac SDK   14.14.2.5 (3836759d4)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

**Comment by jsquire** [comment] 2021-03-15 12:51
Hi @HolguinTech.  Thank you for reaching out and we regret that you're experiencing difficulties.  Looking over the stack trace of the exception and code snippet that you provided, I'm only seeing references to SignalR and Xamarin framework components.  Can you help me understand why you believe that there is an issue with the `Azure.Storage.Blobs` library?

Have you considered opening an issue in the [ASP.NET Core repository](https://github.com/dotnet/aspnetcore/issues)?  The folks responsible for the SignalR client library would probably be best able to assist.

**Comment by jsquire** [comment] 2021-03-17 13:38
Following-up, this has also been reported to the ASP.NET Core team _( [#30909](https://github.com/dotnet/aspnetcore/issues/30909))_ and confirmed as a known issue for Xamarin iOS _([#9477](https://github.com/dotnet/runtime/issues/49477))_.   A workaround was provided in this [comment](https://github.com/mono/mono/issues/20805#issuecomment-791440473).   I'm going to close this out; please feel free to reopen if you believe that further discussion is needed.

**Comment by HolguinTech** [comment] 2021-03-18 11:31
Hi jesse

I hope that everything goes well.

Jesse I have created a project to exemplify what happens. In the project I have referenced Azure.Storage.Blods. With this reference the exception appears but if that reference is removed from the project everything works correctly. This error only occurs in Xamarin.iOS

I want to understand if Azure.Storage.Blods makes any changes in the use of System.Text.Json

https://github.com/HolguinTech/issues-30909.git

Regards

**Comment by jsquire** [comment] 2021-03-18 13:15
Hi @HolguinTech.   Thank you for the additional context.  The Azure SDKs also make use of `System.Text.Json` as well as `System.Memory` and `System.Buffers` which the [workaround thread](https://github.com/mono/mono/issues/20805#issuecomment-791440473) appear to highlight.  Looking at your project file, that workaround doesn't appear, which likely explains the behavior that you're seeing.

Would you mind trying the adjustments recommended in the Mono thread and see if the issue persists?   It looks like the change would be adding the following to your project file:

```xml
<ItemGroup>
  <PackageReference Include="System.Text.Json" Version="5.0.1">
    <IncludeAssets>none</IncludeAssets>
  </PackageReference>
  <PackageReference Include="System.Memory" Version="4.5.4">
    <IncludeAssets>none</IncludeAssets>
  </PackageReference>
  <PackageReference Include="System.Buffers" Version="4.5.1">
    <IncludeAssets>none</IncludeAssets>
  </PackageReference>
</ItemGroup>
```

**Comment by jsquire** [comment] 2021-03-18 13:15
//cc: @pakrym for awareness.

**Comment by HolguinTech** [comment] 2021-03-19 00:24
Hi @jsquire 

Thank you very much for your interest in this problem, I appreciate it very much.

I have changed and updated in the project all the references that I mention below, but the error persists. The only solution is to remove the Azure.Storage.Blods reference from the project.
**System.Text.Json
System.Memory
System.Buffers
System.Tex.Encodings.Web**

This is a solution that I do not want to do since it should completely change the functionality of an application (the attached project is only for testing).

A clue that I could give you is that this error appeared since I updated to Visual Studio version 16.9.1 and the error only occurs in the Xamarin.iOS project in Xamarin.Android it works wonderfully.

I really don't know what to do, so I ask you for help

Regards

**Comment by jsquire** [comment] 2021-03-22 14:41
Hi @HolguinTech.   We reached out to the Xamarin and .NET teams to discussed this; it has been confirmed as a bug in Xamarin and a PR _([#10928](https://github.com/xamarin/xamarin-macios/pull/10928))_ has been opened to address it.   The team plans on backporting that once it merges so that it can be released as soon as possible.

In the meantime, they confirmed the workaround discussed in [#20805](https://github.com/mono/mono/issues/20805#issuecomment-791440473) and [#6412](https://github.com/xamarin/xamarin-macios/issues/6412#issuecomment-573224773) of referencing the latest `System.Memory` with `IncludeAssets` set to `none`.   The suggestion was that we should be overriding just `System.Memory` and likely should not have to include other packages.

```xml
<ItemGroup>
  <PackageReference Include="System.Memory" Version="4.5.4">
    <IncludeAssets>none</IncludeAssets>
  </PackageReference>
</ItemGroup>
```

**Closed** 2021-04-13 08:00 UTC
Labels: Azure.Core, Client, customer-reported, needs-author-feedback, no-recent-activity, question
