### ISSUE TITLE
[BUG] 'No such host is known' exception when calling KeyVault with high volume in parallel from a single host.

### ISSUE THREAD

**Issue by veleek** [Azure/azure-sdk-for-net#7873] opened 2019-10-02 00:10 UTC
**Describe the bug**
When making large numbers of requests to KeyVault, `KeyVaultClient` occasionally throws 'No such host is known' errors.  Retrying with the exact same secret id succeeds.

Secrets are uploaded to a KeyVault as part of an out-of-band process by the key owner.  All the secrets are enumerated and downloaded to an in-memory cache as part of process startup.  I can consistently enumerate a few thousand secrets in a few minutes without issues, but then it starts slowing down, and then a few of these exceptions start occurring.  The KeyVault I'm testing with has 10030 secrets, and it successfully downloads ~9990 of them.  So it's a significant number of exception hits.

KeyVault requests are performed in parallel using `System.Threading.DataFlows.TransformBlock` with 25-50 requests in parallel.  The same process with 1, 2, or 10 request in parallel doesn't seem to experience this issue.  Haven't found a perfect breakpoint for seeing failures.

***Exception or Stack Trace***
```
[2019-10-01 15:27:26.143T-07:00 INF]{ KeyId: "589", KeySource: "KeyVaultContentKeySource" } Key is new or changed. null, "2019-09-26T22:48:06.0000000Z"
[2019-10-01 15:30:02.264T-07:00 DBG]{ KeyId: "589", KeySource: "KeyVaultContentKeySource" } Loading key vault secret https://preload-keys-test.vault.azure.net/secrets/589
[2019-10-01 15:30:17.359T-07:00 ERR]{ KeyId: "589", KeySource: "KeyVaultContentKeySource" } Failed to load key
System.Net.Http.HttpRequestException: No such host is known.
 ---> System.Net.Sockets.SocketException (11001): No such host is known.
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Microsoft.Rest.RetryDelegatingHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Microsoft.Azure.KeyVault.KeyVaultClient.GetSecretWithHttpMessagesAsync(String vaultBaseUrl, String secretName, String secretVersion, Dictionary`2 customHeaders, CancellationToken cancellationToken)
   at Microsoft.Azure.KeyVault.KeyVaultClientExtensions.GetSecretAsync(IKeyVaultClient operations, String secretIdentifier, CancellationToken cancellationToken)
   at ContentKey.Cli.KeyVaultContentKeySource.LoadKey(String keyId) in E:\src\ContentKey.Cli\KeyVaultContentKeySource.cs:line 70
   at ContentKey.Cli.IContentKeySource.<>c__DisplayClass2_0.<<UpdateKeys>b__0>d.MoveNext() in E:\src\ContentKey.Cli\IContentKeySource.cs:line 49
```

**To Reproduce**
Quickly enumerate all of the secrets in a vault with a large number of secrets, and then in parallel start loading each of the individual secrets.

***Code Snippet***
It's a non-snippet sized chunk of code to enumerate the keys and load them all in parallel.  I can provide a smaller repro (or just the full tool offline if necessary).  

**Expected behavior**
Secrets should be successfully loaded or a more descriptive error should be thrown to indicate the cause of the problem.

**Setup (please complete the following information):**
 - OS: Windows (.NET Core 3.0 Console App)
 - IDE : Visual Studio
 - Version of the Library used: 3.0.4

**Additional context**
I'm able to reproduce this behavior pretty consistently when running with the debugger attached (no breakpoints configured or hit or anything though), but when running from the command line with no debugger it doesn't seem to fail.

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X] Bug Description Added
- [X] Repro Steps Added
- [X] Setup information Added

**Comment by mitchdenny** [comment] 2019-10-02 05:12
@veleek looks like you might be running afoul of KeyVault service limits:

https://docs.microsoft.com/en-us/azure/key-vault/key-vault-service-limits

Specifically it says no more than 2000 transactions per vault per region within 10 seconds. Would you say you are exceeding that threshold?

**Comment by mitchdenny** [comment] 2019-10-02 05:34
One more follow-up on this. We have got a new set of preview libraries that we are shipping at the moment which contain a reworked HTTP request pipeline. You might like to try them out. I just had a quick look through the code and confirmed that we do have exponential back-off logic implemented there.

The package for KeyVault secrets is ```Azure.Security.KeyVault.Secrets```.

**Comment by veleek** [comment] 2019-10-02 05:49
Pretty sure I'm not exceeding the limits.  When running without the debugger attached, it completes faster AND without errors.  Also when getting the throttling errors you should see a 429 back from KeyVault and in this case the request isn't being sent at all.

Happy to try out the preview libraries, but it really doesn't appear to be throttling.  

Each list secrets call returns 25 secrets max so in order to reach the 200 TPS limit, 8 of the list calls would need to compete in a second and the are sequential since its a paged API, and that almost definitely takes more than a second so my ACTUAL concurrent request rate is arbitrarily limited even when I set max parallel reqs to 50.

**Comment by mitchdenny** [comment] 2019-10-02 05:59
Give the new libraries a try and let us know how you go. If you've got a minimal repro that you could share that could help validate what you are seeing on our side.

**Comment by mitchdenny** [comment] 2019-10-02 06:14
Also adding the service attention flag, because its possible that in addition to the rate limiting (and associated throttling signals 429 response code etc) that there could be a situation where the traffic is just blocked.

@veleek you mentioned above in the issue that you were executing 25-50 requests in parallel.

@veleek you mentioned above that you

**Comment by veleek** [comment] 2019-10-05 21:19
@mitchdenny, I've tried out the new libraries but I'm having some trouble getting requests to work.  At the moment I'm just getting `ArgumentOutOfRangeException` get calling `GetSecretsAsync` (using a `ManagedIdentityCredential`).

```
System.ArgumentOutOfRangeException
  HResult=0x80131502
  Message=The added or subtracted value results in an un-representable DateTime. (Parameter 't')
  Source=System.Private.CoreLib
  StackTrace:
   at System.DateTime.op_Subtraction(DateTime d, TimeSpan t)
   at System.DateTimeOffset.op_Subtraction(DateTimeOffset dateTimeOffset, TimeSpan timeSpan)
   at Azure.Security.KeyVault.ChallengeBasedAuthenticationPolicy.<AuthenticateRequestAsync>d__9.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
```

Also, I'm relatively confident that the error that I'm seeing is not related to throttling.  As I said, I see the error when I'm making 25 requests in parallel, but I'm making no where near the 2000req/10sec limit.  I've seen the 429 errors that result from that before, and that's not what I'm getting.  I don't think the traffic is making it to the server at all because that would not result in `No such host known`.  It really seems like it may just be a bug in the current version of the library that occurs during high load.

If the response is just going to be "we're not providing fixes to that library anymore, please switch to the new one" that's totally reasonable, I just need to know so I can do the right thing and move to the appropriate library.

**Comment by veleek** [comment] 2019-10-06 04:34
Okay, I was actually able to get it working using `InteractiveBrowserCredential` and was able to reproduce the error with the new libraries:

```
System.Net.Http.HttpRequestException: No such host is known.
 ---> System.Net.Sockets.SocketException (11001): No such host is known.
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Azure.Core.Pipeline.HttpClientTransport.ProcessAsync(HttpPipelineMessage message)
   at Azure.Core.Pipeline.RequestActivityPolicy.ProcessNextAsync(HttpPipelineMessage message, ReadOnlyMemory`1 pipeline, Boolean isAsync)
   at Azure.Core.Pipeline.RequestActivityPolicy.ProcessAsync(HttpPipelineMessage message, ReadOnlyMemory`1 pipeline, Boolean isAsync)
   at Azure.Core.Pipeline.BufferResponsePolicy.ProcessAsync(HttpPipelineMessage message, ReadOnlyMemory`1 pipeline)
   at Azure.Core.Pipeline.LoggingPolicy.ProcessAsync(HttpPipelineMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
   at Azure.Core.Pipeline.LoggingPolicy.ProcessAsync(HttpPipelineMessage message, ReadOnlyMemory`1 pipeline)
   at Azure.Security.KeyVault.ChallengeBasedAuthenticationPolicy.ProcessCoreAsync(HttpPipelineMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
   at Azure.Core.Pipeline.RetryPolicy.ProcessAsync(HttpPipelineMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
   at Azure.Core.Pipeline.RetryPolicy.ProcessAsync(HttpPipelineMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
   at Azure.Core.Pipeline.SynchronousHttpPipelinePolicy.ProcessAsync(HttpPipelineMessage message, ReadOnlyMemory`1 pipeline)
   at Azure.Core.Pipeline.SynchronousHttpPipelinePolicy.ProcessAsync(HttpPipelineMessage message, ReadOnlyMemory`1 pipeline)
   at Azure.Core.Pipeline.HttpPipeline.SendRequestAsync(Request request, Boolean bufferResponse, CancellationToken cancellationToken)
   at Azure.Security.KeyVault.KeyVaultPipeline.SendRequestAsync(Request request, CancellationToken cancellationToken)
   at Azure.Security.KeyVault.KeyVaultPipeline.SendRequestAsync[TResult](RequestMethod method, Func`1 resultFactory, CancellationToken cancellationToken, String[] path)
   at Azure.Security.KeyVault.Secrets.SecretClient.GetAsync(String name, String version, CancellationToken cancellationToken)
   at ContentKey.KeySource.KeyVaultContentKeySource.LoadKeyAsync(String keyId) in E:\src\ContentKey.Cli\KeySource\KeyVaultContentKeySource.cs:line 65
   at ContentKey.KeySource.IContentKeySource.<>c__DisplayClass5_0.<<UpdateKeys>b__0>d.MoveNext() in E:\src\ContentKey.Cli\KeySource\IContentKeySource.cs:line 49
```

I'm working on creating a minimal repro now, but it usually takes a minute or two to reproduce itself so it's been difficult to isolate it.

**Comment by veleek** [comment] 2019-10-07 15:12
I managed to get a minimal repro that hit the same error: https://gist.github.com/veleek/6751f70081e13d5f8bdf3f0cb09d0a4f

Additional details just so that we're on the same page:
* KeyVault has ~10K keys in it
* This only seems to occur when running under the debugger in Visual Studio
* Visual Studio 2019
* .NET Core 3.0.100
* The problem doesn't reproduce 100%, it is possible to get a completely clean run but the repro rate is high. 
* When one of these errors occur, it almost always occurs a whole bunch of times for the remainder of the run.

**Comment by mitchdenny** [comment] 2019-10-08 00:05
I've downloaded your Gist and setup a repo environment - running the test scenario a few times to see if it crops up. Nothing so far.

**Comment by mitchdenny** [comment] 2019-10-08 01:43
@veleek another thing that springs to mind is another external factor - do you have any anti-virus/anti-malware software running on your machine? Could you try disabling it temporarily and running your tests again. I've heard of this kind of software intercepting network calls occasionally in the IP stack resulting in a failed host lookup.

**Comment by AlexGhiondea** [comment] 2019-10-09 03:23
@schaabs  have you seen these errors before?

They are both errors when using Identity as well as when using KeyVault

**Comment by heaths** [comment] 2019-10-17 23:01
@veleek, are you still able to reproduce this on the latest Key Vault preview 5 packages? If so, are you running anti-virus or other security middleware that you're able to temporarily disable and try again? We've been unable to reproduce this issue.

**Comment by veleek** [comment] 2019-10-18 05:46
@heaths - I spoke with Mitch directly about it and I've been trying to reproduce on some other machines without much luck.  I haven't had a chance to try it again on my work machine with AV disabled.

**Comment by heaths** [comment] 2019-10-18 17:08
Do you mind if we (or you) close this issue for now? If you are able to reproduce and gather more data, you can reopen it and we'd be happy to have another look.

**Closed** 2019-10-21 16:37 UTC
Labels: Client, KeyVault, Service Attention, customer-reported

**Comment by heaths** [comment] 2019-10-21 16:57
Did you try temporarily disabling Windows Defender or any other AV/firewall? We have seen similar issues when jobs queue up quickly. In my former team - the VS Setup team - Defender (more often Device Guard) would regularly block a valid file operation because our new engine was so much faster than Windows Installer. We had to add exponential retries for all file operations to work around it.

**Comment by veleek** [comment] 2019-10-21 21:45
Finally had a chance to fiddle around a bit more.  Took me a few tries to get the initial confirmation repro with the AV enabled but I did eventually.  But then it actually failed on the first attempt and MUCH faster with Defender disabled (only a few hundred keys).  Unfortunately, I'm on Microsoft Corp Net so I can't disable the Firewall on my desktop.

I'm trying again a few times with AV off, but I have at least one confirmed repro with it off.

**Comment by veleek** [comment] 2019-10-21 22:02
FYI: This bug seems to be very similar (high load, unexpected SocketExceptions), so it feels like that should be a good-ish indication that this is not specific to the KeyVault client, but an issue in .NET.

**Comment by heaths** [comment] 2019-10-21 22:31
https://github.com/dotnet/corefx would be a good place to file a more general issue. If you have a repro sans Key Vault, that may help them narrow down the problem faster.

**Comment by aghababyan-gohar** [comment] 2020-06-24 11:39
Hi, I am experiencing similar issue recently. The issue is the same, the difference is that steps of reproduction aren't stable. 
Happening randomly and I can't find how it's fixed again.

There's almost nothing about the issue, and I wanted to understand if it's indeed Microsoft bug or no.

**Comment by heaths** [comment] 2020-06-24 22:28
I recommend checking out dotnet/runtime#31247 and see in which version of .NET it's fixed, or what else they have to say about it.
