### ISSUE TITLE
[BUG] Azure.Storage.Blobs ignoring ClientSideEncryptionOptions when using ConnectionString in ctor

### ISSUE THREAD

**Issue by sebhaub** [Azure/azure-sdk-for-net#27793] opened 2022-03-28 12:44 UTC
### Library name and version

Azure.Storage.Blobs 12.10.0

### Describe the bug

BlobContainerClient has constructor overloads. Using the constructor which expects a ConnectionString does not set the ClientSideEncryptionOptions.
See https://github.com/Azure/azure-sdk-for-net/blob/d80f28049966b80d97634e9c3c83f2ea6daf6c62/sdk/storage/Azure.Storage.Blobs/src/BlobContainerClient.cs#L187-L207

It looks to me like this line of code is missing there.

` _clientSideEncryption = options._clientSideEncryptionOptions?.Clone();`

When using the other constructors (for instance with credentials) it is working as expected.

### Expected behavior

No matter which ctor is used, the ClientSideEncryptionOptions should be set correctly.

### Actual behavior

When using the constructor with the connectionstring as a parameter, there is no ClientSideEncryption configured.

### Reproduction Steps

- Create BlobClientOptions with configured ClientSideEncryption
- Initialize the BlobContainerClient passing the connectionstring, containername and the options

**Comment by SaurabhSharma-MSFT** [comment] 2022-03-28 19:05
@sebhaub Thanks for reporting this.  I could see the same and I am redirecting this to services team to provide details if this is by design or if they need to provide a fix for this.  

Thanks
Saurabh

**Comment by amnguye** [comment] 2022-06-30 18:05
@jaschrep-msft Could you chime in on this?

**Closed** 2024-03-27 18:04 UTC
Labels: Storage, Service Attention, Client, customer-reported, question, needs-team-attention
