### ISSUE TITLE
Migration Guide for Event Hubs

### ISSUE THREAD

**Issue by AlexGhiondea** [Azure/azure-sdk-for-net#16734] opened 2020-11-08 19:10 UTC
Please wait for this issue to be updated with the link to the Migration Guide template.

For Event Hubs, we already have a migration guide. Once the template is ready, this issue is to track the work to get the current guide to follow the template

**Comment by jsquire** [comment] 2020-11-09 13:32
Closing this as a dupe of #15586.  Please use the existing issue for tracking, and update with the template information.

**Closed** 2020-11-09 13:32 UTC
Labels: Client, Docs
