### ISSUE TITLE
[BUG] Service Bus: Unable to set AutoDeleteOnIdle when ForwardDeadLetteredMessagesTo is set

### ISSUE THREAD

**Issue by Bubelgin** [Azure/azure-sdk-for-net#18517] opened 2021-02-08 00:16 UTC
When creating or updating ServiceBus topic subscriptions AutoDeleteOnIdle setting will be ignored if ForwardDeadLetteredMessagesTo property is set.

Expecting the AutoDeleteOnIdle to be set no matter if ForwardDeadLetteredMessagesTo is set or not.

Sample code:

```csharp
using System;
using System.Threading.Tasks;
using Microsoft.Azure.ServiceBus.Management;

namespace AutoDeleteOnIdle
{
    class Program
    {
        static async Task Main(string[] args)
        {
            var connectionString = "your connection string here";
            var managementClient = new ManagementClient(connectionString);
            var topic = await managementClient.CreateTopicAsync("testtopic");
            SubscriptionDescription subDescription = new SubscriptionDescription(topic.Path, "testsubscription")
            {
                AutoDeleteOnIdle = TimeSpan.FromHours(1),
                ForwardDeadLetteredMessagesTo = "deadletterqueue"
            };
            await managementClient.CreateSubscriptionAsync(subDescription);
        }
    }
}
```

If the line with "ForwardDeadLetteredMessagesTo" is removed everything works as expected.

**Environment:**
 - Name and version of the Library package used: Microsoft.Azure.ServiceBus 5.1.1 - older versions seem to have the same behavior.
 - Hosting platform or OS and .NET runtime version: Azure ServiceBus, **test project .net core 3.1 console application**
  dotnet --info
.NET SDK (reflecting any global.json):
 Version:   5.0.101
 Commit:    d05174dc5a

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.101\

Host (useful for support):
  Version: 5.0.1
  Commit:  b02e13abab

.NET SDKs installed:
  2.1.801 [C:\Program Files\dotnet\sdk]
  2.2.401 [C:\Program Files\dotnet\sdk]
  2.2.402 [C:\Program Files\dotnet\sdk]
  3.0.100-preview8-013656 [C:\Program Files\dotnet\sdk]
  3.1.101 [C:\Program Files\dotnet\sdk]
  3.1.201 [C:\Program Files\dotnet\sdk]
  5.0.100 [C:\Program Files\dotnet\sdk]
  5.0.101 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview8.19405.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview8-28405-07 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview8-28405-07 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
 - IDE and version : Visual Studio 16.8.3

**Comment by jsquire** [comment] 2021-02-08 14:00
//cc: @JoshLove-msft:  This may impact the T2 library as well.

**Comment by jsquire** [comment] 2021-02-08 14:01
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by axisc** [comment] 2021-02-08 22:52
@Bubelgin Thanks for raising this issue.

For the forwarding logic to work, the queue/subscription must exist. Hence if you set forwardDeadLetterMessagesTo setting, you can't enable AutoDeleteOnIdle on the same entity. This is by design.

Do let us know if you have any follow up questions.

**Comment by Bubelgin** [comment] 2021-02-08 23:35
In our particular use case, a topic represents a store and each subscription represents a driver, each message on the subscription represents an order. If the order is not picked up by the driver after x minutes the order expires and goes to the dead letter queue where they're processed accordingly so enabling dead letter functionality is necessary.
On the other hand, there can be a lot of unique drivers over time so we want to eventually clear unused subscriptions that have not been active which also requires the AutoDeleteOnIdle to be set.
ForwardDeadLetterMessagesTo does target a particular queue that already exists and AutoDeleteOnIdle is supposed to delete the subscription, not the target queue so I don't exactly understand the reason why both functionalities can't coexist. It's like saying that if you have ForwardDeadLetterMessagesTo set on a subscription then you can't delete the subscription which is not true.
Are we supposed to manually setup scheduled workers to scan and clear each subscription that has not been used for a duration when AutoDeleteOnIdle is meant to do exactly that? Any suggested workarounds or plans to change this?

As a side note, if you're using Service Bus explorer you can set the AutoDeleteOnIdle property correctly even when ForwardDeadLetterMessagesTo is set.

**Comment by axisc** [comment] 2021-02-09 03:36
@Bubelgin the problem in this cases arises when the autoDeleteOnIdle counts down and deletes the subscription while it still has data that was meant to be deadlettered and forwarded to the queue.

Without knowing much about your use-case and architecture, so this is just my guess -
   * why not have each driver simply be a consumer on a subscription (and not a separate subscription)? It seems that the 1:1 mapping between driver and subscription is causing the problem.

   * Perhaps each store needs to be a subscription and each driver can be a receiver application on that subscription?

**Comment by et1975** [comment] 2021-02-09 21:04
I'm seeing the same problem with the `ForwardTo` being set. 

I can see why the receiving  _queue_ must exist for forwarding from a subscription to work, although that doesn't prevent me from deleting the queue or setting up OnIdle deletion of the queue and have it disappear (looking at the subscription the portal gives you no clue that anything is wrong, but that's another issue). 
But I don't understand why setting up subscription forwarding and OnIdle deletion are mutually exclusive. I can delete the subscription any time myself, right?

Another thought is that the pattern doesn't hold for topics - I can make topics delete on idle, regardless of wether there are subscriptions attached to it. Sure, the underlying mechanism is different, but the idea is the same.

If it's just an implementation problem I think this should be addressed. And if not, maybe you could elaborate as to how it is beneficial.

**Comment by Bubelgin** [comment] 2021-02-10 21:13
> 
> 
> @Bubelgin the problem in this cases arises when the autoDeleteOnIdle counts down and deletes the subscription while it still has data that was meant to be deadlettered and forwarded to the queue.
> 
> Without knowing much about your use-case and architecture, so this is just my guess -
> 
>     * why not have each driver simply be a consumer on a subscription (and not a separate subscription)? It seems that the 1:1 mapping between driver and subscription is causing the problem.
> 
>     * Perhaps each store needs to be a subscription and each driver can be a receiver application on that subscription?

Switching the setup would not work in our scenario and having multiple clients for the same subscription introduces way more concurrency and performance problems than it solves. As @et1975 mentioned I don't see why these functionalities should be mutually exclusive. 
As a use case, I just want my messages to be deadlettered and forwarded to a queue if message TTL expired (say 30 minutes).
Unrelated to that I want the subscription to be deleted if it's not been active for 1 day, at that point I don't care if there are any messages in the queue or if they're going to deadletter as it's meant to be deleted anyway.

If it's not currently possible due to some internal way it's written I'd like to raise this as a feature request.

**Comment by axisc** [comment] 2021-02-23 00:28
@Bubelgin  We're investigating this internally and will come back with our findings.

**Comment by yvgopal** [comment] 2021-03-09 04:33
This is not an SDK bug. All SDKs behave the same because ServiceBus service would ignore AutoDeleteOnIdle if ForwardTo or ForwardDeadletterMessagesTo is set on any entity.

It is not a recent change either. Service Bus has always ignored AutoDeleteOnIdle if the entity is set to forward messages to another entity. Having said that, I don't know the exact reason why that decision was made. I see that some of you have a justification why AutoDeleteOnIdle shouldn't be ignored. Please raise a request to the service. Our PM team will either provide an answer or take it up a a feature request.

I am closing this issue as it is not SDK specific issue.

**Closed by yvgopal** 2021-03-09 04:33 UTC
Labels: Client, Service Attention, Service Bus, customer-reported, needs-team-attention, question
