### ISSUE TITLE
[Text Analytics] AnalyzeOperationWithPHIDomain failing intermittently in nightly runs

### ISSUE THREAD

**Issue by v-yilinhu** [Azure/azure-sdk-for-net#26693] opened 2022-01-30 04:56 UTC
Text Analytics nightly test runs are failing with:

> Error message
> Azure.RequestFailedException : Invalid Task Type: Task entities/phi is not supported.
> Status: 500 (Internal Server Error)
> ErrorCode: InternalServerError
> 
> Content:
> {"error":{"code":"InternalServerError","message":"Invalid Task Type: Task entities/phi is not supported."}}
> 
> Headers:
> Transfer-Encoding: chunked
> x-envoy-upstream-service-time: 9
> apim-request-id: 4e958ae2-d647-4a83-b72f-a087853869dc
> Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
> X-Content-Type-Options: nosniff
> Date: Sat, 29 Jan 2022 03:12:58 GMT
> Content-Type: application/json; charset=utf-8
> 
> 
> Stack trace
>    at Azure.AI.TextAnalytics.TextAnalyticsRestClient.AnalyzeStatusAsync(String jobId, Nullable`1 showStats, Nullable`1 top, Nullable`1 skip, CancellationToken cancellationToken) in /Users/runner/work/1/s/sdk/textanalytics/Azure.AI.TextAnalytics/src/Generated/TextAnalyticsRestClient.cs:line 151
>    at Azure.AI.TextAnalytics.AnalyzeActionsOperation.Azure.Core.IOperation<Azure.AsyncPageable<Azure.AI.TextAnalytics.AnalyzeActionsResult>>.UpdateStateAsync(Boolean async, CancellationToken cancellationToken) in /Users/runner/work/1/s/sdk/textanalytics/Azure.AI.TextAnalytics/src/AnalyzeActionsOperation.cs:line 313
>    at Azure.Core.OperationInternal`1.UpdateStateAsync(Boolean async, CancellationToken cancellationToken) in /Users/runner/work/1/s/sdk/core/Azure.Core/src/Shared/OperationInternalOfT.cs:line 186
>    at Azure.Core.OperationInternalBase.UpdateStatusAsync(Boolean async, CancellationToken cancellationToken) in /Users/runner/work/1/s/sdk/core/Azure.Core/src/Shared/OperationInternalBase.cs:line 173
>    at Azure.Core.OperationInternalBase.UpdateStatusAsync(CancellationToken cancellationToken) in /Users/runner/work/1/s/sdk/core/Azure.Core/src/Shared/OperationInternalBase.cs:line 80
>    at Azure.Core.OperationInternalBase.WaitForCompletionResponseAsync(TimeSpan pollingInterval, CancellationToken cancellationToken) in /Users/runner/work/1/s/sdk/core/Azure.Core/src/Shared/OperationInternalBase.cs:line 142
>    at Azure.Core.OperationInternal`1.WaitForCompletionAsync(TimeSpan pollingInterval, CancellationToken cancellationToken) in /Users/runner/work/1/s/sdk/core/Azure.Core/src/Shared/OperationInternalOfT.cs:line 167
>    at Azure.Core.OperationInternal`1.WaitForCompletionAsync(CancellationToken cancellationToken) in /Users/runner/work/1/s/sdk/core/Azure.Core/src/Shared/OperationInternalOfT.cs:line 145
>    at Azure.AI.TextAnalytics.AnalyzeActionsOperation.WaitForCompletionAsync(CancellationToken cancellationToken) in /Users/runner/work/1/s/sdk/textanalytics/Azure.AI.TextAnalytics/src/AnalyzeActionsOperation.cs:line 229
>    at Azure.AI.TextAnalytics.Tests.AnalyzeOperationTests.AnalyzeOperationWithPHIDomain() in /Users/runner/work/1/s/sdk/textanalytics/Azure.AI.TextAnalytics/tests/AnalyzeOperationTests.cs:line 557
>    at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.BlockUntilCompleted()
>    at NUnit.Framework.Internal.MessagePumpStrategy.NoMessagePumpStrategy.WaitForCompletion(AwaitAdapter awaiter)
>    at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.<>c__DisplayClass1_0.<Execute>b__0()
>    at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.RunTestMethodInThreadAbortSafeZone(TestExecutionContext context, Action action)

For more details check here:

- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1334757&view=results

@jsquire for notification.

**Comment by kinelski** [comment] 2022-02-09 20:07
This was caused by a service-side issue. It's already fixed, so closing this.

**Closed by kinelski** 2022-02-09 20:07 UTC
Labels: Client, Cognitive - Text Analytics, test-reliability
