### ISSUE TITLE
[BUG] Microsoft.Azure.EventGrid is released without optimizations

### ISSUE THREAD

**Issue by lukasz-pyrzyk** [Azure/azure-sdk-for-net#18645] opened 2021-02-10 12:44 UTC
**Describe the bug**
`Microsoft.Azure.EventGrid` 3.2.0 is compiled without optimizations. The previous version, 3.1.0 was compiled correctly, with optimizations turned on.

**Expected behavior**
A package should be compiled with optimizations

**Actual behavior (include Exception or Stack Trace)**
The package is compiled without optimizations

**To Reproduce**
1. Reference package with BenchmarkDotNet and execute benchmark

> Assembly XYZ which defines benchmarks references non-optimized Microsoft.Azure.EventGrid
>         If you own this dependency, please, build it in RELEASE.
>         If you don't, you can disable this policy by using 'config.With(ConfigOptions.DisableOptimizationsValidator)

2. Or print dll details
```csharp
private static void PrintInfo(Assembly assembly)
{
    var attribute = assembly.GetCustomAttributes(false).OfType<DebuggableAttribute>().FirstOrDefault();
    Console.WriteLine($"JIT tracking enabled: {attribute.IsJITTrackingEnabled}");
    Console.WriteLine($"JIT optimization disabled: {attribute.IsJITOptimizerDisabled}");
    
    // for 3.2.0
    // JIT tracking enabled: True                                                                                              
    // JIT optimization disabled: True
    
    // for 3.1.0
    // JIT tracking enabled: false
    // JIT optimization disabled: false
}
```

**Environment:**
 **Name and version of the Library package used:** 
 Microsoft.Azure.EventGrid  3.2.0
 
 **Hosting platform or OS and .NET runtime version**
 
 Windows 10 .NET Framework 4.8]
 .NET SDK (reflecting any global.json):
 Version:   5.0.103
 Commit:    72dec52dbd

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.103\

Host (useful for support):
  Version: 5.0.3
  Commit:  c636bbdc8a
  
 **IDE and version:** 
 Visual Studio Version 16.8.5

**Comment by jsquire** [comment] 2021-02-10 14:15
This seems like it may be something related to the build pipelines.  @weshaggard and @mitchdenny,  would you be so kind as to offer your thoughts?

**Comment by jsquire** [comment] 2021-02-10 14:15
Thank you for your feedback.  Tagging and routing to the team members best able to assist.

**Comment by weshaggard** [comment] 2021-02-10 21:23
@jsquire there was a point in time were we were accidently shipping Debug built binaries but that was fixed with https://github.com/Azure/azure-sdk-for-net/pull/6965 which occurred (7/29/2019) a couple months after the 3.2.0 version was shipped (5/23/2019 https://www.nuget.org/packages/Microsoft.Azure.EventGrid/3.2.0) to nuget. To fix this we would need to create a new release. So I'd leave that up to the owners of this library to decide when the best time to ship an update here.

**Comment by jsquire** [comment] 2021-02-10 21:25
Thanks, @weshaggard.   Since we know the root cause has been resolved, routing to the Event Grid service team for consideration of a new release.

**Comment by jfggdl** [comment] 2021-02-11 04:34
Thank you. Assigning to @ahamad-MS .

**Comment by ahamad-MS** [comment] 2021-02-16 03:31
@weshaggard  @jsquire Can you please elaborate on the ask from service team here? Since this is related to EngSys/build pipeline, it is not clear to me what is the ask here.

We are currently in the process of adding new nuget version to include new features. Will this be sufficient to resolve this issue?

**Comment by jsquire** [comment] 2021-02-16 13:41
@ahamad-MS:  There would need to be a new version of the library published to resolve this.  Since you're in the process of releasing for new features, that would cover it.

**Comment by ahamad-MS** [comment] 2021-02-18 21:07
Sweet .. thanks @jsquire  for the clarification. I will close this issue once the new library is published.

**Comment by ahamad-MS** [comment] 2021-03-05 05:01
New nuget is now available and published. 

https://www.nuget.org/packages/Microsoft.Azure.Management.EventGrid/6.1.0-preview

I am closing this issue according to the discussion with @jsquire .. Please let us know if additional info needed. Thanks

**Closed by ahamad-MS** 2021-03-05 05:01 UTC
Labels: Client, Event Grid, Service Attention, customer-reported, needs-team-attention, question
