### ISSUE TITLE
[BUG] No such host is know

### ISSUE THREAD

**Issue by nminhduc** [Azure/azure-sdk-for-net#6707] opened 2019-06-26 03:55 UTC
![image](https://user-images.githubusercontent.com/18206570/60149929-c12ec300-9800-11e9-9173-28bf8b33d744.png). My Azure search still work with postman but with .NET SDK throw exception No such host is know

**Comment by brjohnstmsft** [comment] 2019-06-26 17:39
@nminhduc Can you please share the code you're using to initialize the `SearchServiceClient` or `SearchIndexClient` (whichever is throwing the exception)?

**Comment by brjohnstmsft** [comment] 2019-07-08 00:22
@nminhduc Are you still experiencing this issue? Can you share the code to reproduce it?

**Comment by brjohnstmsft** [comment] 2019-07-11 22:58
Closing this issue since we don't have enough information to reproduce it. @nminhduc, feel free to re-open it if you're still experiencing the issue and can provide more details on how to reproduce it.

**Closed by brjohnstmsft** 2019-07-11 22:58 UTC
Labels: Search
