### ISSUE TITLE
[QUERY] InvalidResourceType error after upgrading to Azure.ResourceManager 1.4.0

### ISSUE THREAD

**Issue by linda-chin** [Azure/azure-sdk-for-net#34568] opened 2023-02-27 05:56 UTC
### Library name and version

Azure.ResourceManager 1.4.0

### Query/Question

After upgrading to Azure.ResourceManager 1.4.0 I get a `RequestFailedException` exception when tagging `SqlDatabaseResource` using `AddTagAsync()`. Is this a known issue?

The full error is:
```
Status: 404 (Not Found)
ErrorCode: InvalidResourceType
Content:
{"error":{"code":"InvalidResourceType","message":"The resource type 'locations/databaseOperationResults' could not be found in the namespace 'Microsoft.Sql' for api version '2022-09-01'. The supported api-versions are '2017-03-01-preview,2017-10-01-preview,2018-06-01-preview,2019-06-01-preview,2020-02-02-preview,2020-08-01-preview,2020-11-01-preview,2021-02-01-preview,2021-05-01-preview,2021-08-01-preview,2021-11-01,2021-11-01-preview,2022-02-01-preview,2022-05-01-preview,2022-08-01-preview'."}}
Source=Azure.ResourceManager
  StackTrace:
   at Azure.Core.OperationInternal`1.GetResponseFromState(OperationState`1 state)
   at Azure.Core.OperationInternal`1.<UpdateStatusAsync>d__20.MoveNext()
   at Azure.Core.OperationInternalBase.<UpdateStatusAsync>d__13.MoveNext()
   at Azure.Core.OperationPoller.<WaitForCompletionAsync>d__11.MoveNext()
   at Azure.Core.OperationInternalBase.<WaitForCompletionResponseAsync>d__19.MoveNext()
   at Azure.Core.OperationInternal`1.<WaitForCompletionAsync>d__19.MoveNext()
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1.ConfiguredValueTaskAwaiter.GetResult()
   at Azure.Core.OperationInternal`1.<WaitForCompletionAsync>d__15.MoveNext()
   at Azure.ResourceManager.Resources.TagResource.<CreateOrUpdateAsync>d__22.MoveNext()
   at Azure.ResourceManager.Sql.SqlDatabaseResource.<AddTagAsync>d__138.MoveNext()
```

**Comment by jsquire** [comment] 2023-02-27 13:58
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by ArcturusZhang** [comment] 2023-03-09 04:19
Duplicate of https://github.com/Azure/azure-sdk-for-net/issues/34796

We close this issue in favor of https://github.com/Azure/azure-sdk-for-net/issues/34796

**Closed by ArcturusZhang** 2023-03-09 04:19 UTC
Labels: SQL, Mgmt, customer-reported, question, needs-team-attention
