### ISSUE TITLE
[Azure Function ServiceBusTrigger] ServiceBusReceiveActions Azure function binding parameter missing PeekMessages method.

### ISSUE THREAD

**Issue by aliqaryan2** [Azure/azure-sdk-for-net#30887] opened 2022-09-01 15:51 UTC
### Library name

Microsoft.Azure.WebJobs.ServiceBus

### Please describe the feature.

the current version of ServiceBusReceiveActions binding parameter has the ability to receive additional messages according to this example:
[ServiceBusReceiveActions](https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/servicebus/Microsoft.Azure.WebJobs.Extensions.ServiceBus#binding-to-receiveactions)

```
// attempt to receive additional messages in this session
await receiveActions.ReceiveMessagesAsync(maxMessages: 10); 
It would be very helpful if we had to PeekMessagesAsync() method that could also check Scheduled messages.
```

**Comment by aliqaryan2** [comment] 2022-09-01 15:52
Related ticket I found: https://github.com/Azure/azure-sdk-for-net/issues/29313

**Comment by jsquire** [comment] 2022-09-01 22:24
Hi @aliqaryan2.  Thank you for your feedback.   As you noted, there's already an open feature request tracking this.   I'm going to close this out as a duplicate of #29313 and we'll continue to track the request there.

**Closed by jsquire** 2022-09-01 22:24 UTC
Labels: Service Bus, Client, customer-reported, question, needs-team-triage
