### ISSUE TITLE
[BUG] Incorrect exception thrown when trying to delete a non-existent Azure role assignment

### ISSUE THREAD

**Issue by gmantri** [Azure/azure-sdk-for-net#35425] opened 2023-04-07 13:31 UTC
### Library name and version

Azure.ResourceManager.Authorization v1.0.1

### Describe the bug

When trying to delete a non-existent Azure role assignment, `NullReferenceException` is thrown by the SDK instead of `RequestFailedException`.

### Expected behavior

SDK should throw `RequestFailedException`.

### Actual behavior

SDK is throwing `NullReferenceException`.

Here's a portion of stack trace:

```
System.NullReferenceException: Object reference not set to an instance of an object.
at Azure.ResourceManager.Authorization.RoleAssignmentResource..ctor(ArmClient client, RoleAssignmentData data)
at Azure.ResourceManager.Authorization.RoleAssignmentResource.DeleteAsync(WaitUntil waitUntil, String tenantId, CancellationToken cancellationToken)
```

### Reproduction Steps

Here's the code that I am using:

```
var armClient = new ArmClient(new DefaultAzureCredential());
var subscriptionId = "<valid subscription id>";
var roleAssignmentName = Guid.NewGuid().ToString();
var roleAssignmentResourceId = $"/subscriptions/{subscriptionId}/providers/Microsoft.Authorization/roleAssignments/{roleAssignmentName}";
var resource = armClient.GetRoleAssignmentResource(new ResourceIdentifier(roleAssignmentResourceId));
await resource.DeleteAsync(WaitUntil.Started);//this line throws the error
```

**Comment by jsquire** [comment] 2023-04-07 14:05
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by ArthurMa1978** [comment] 2023-04-10 06:00
Thank you @gmantri for your great feedback.
This service returns 204 if the role assignment doesn't exist for deletion, so this is not a `RequestFailedException`, so here throws the `NullReferenceException`.

Close this issue as this is by design, please let me know if you have further questions.

**Closed by ArthurMa1978** 2023-04-10 06:00 UTC
Labels: Authorization, Mgmt, customer-reported, question, needs-team-attention

**Comment by ArthurMa1978** [comment] 2023-04-10 08:40
After discussion, we agreed that throw `NullReferenceException` is still not a right way here, since service return `204`, client sdk should not throw, so created another [feature](https://github.com/Azure/autorest.csharp/issues/3255) to improve this.
