### ISSUE TITLE
[FEATURE REQ] Helper method to build a connection string for Event Hubs & Service Bus

### ISSUE THREAD

**Issue by ramya-rao-a** [Azure/azure-sdk-for-net#15893] opened 2020-10-13 02:52 UTC
**Library or service name.**
Azure Service Bus and Azure Event Hubs
 
**Is your feature request related to a problem? Please describe.**

Today, the clients in Azure.Messaging.EventHubs and Azure.Messaging.ServiceBus libraries allow client construction using connection string which can either have the SharedAccessSignature (SAS token) directly in it or have the SharedAccessKey & SharedAccessKeyName in it using which the client can then create the SharedAccessSignature

When having just the `SharedAccessSignature` in hand, one needs to build a connection string with it.
There can also be cases where one has access to the SharedAccessKey and its name, but not the entire connection string.

Once we have #15887, this is not much of a concern as one can create a SharedAccessKeyCredential class using the above information, and then pass it to the new client constructor overload after parsing the namespace & entitypath details from connectionString (#15892) or a configuration system of choice.

But, we still would have a gap where we support a version of the connection string that has to be built by hand.

Therefore, this feature request is to have a helper method in both Event Hubs & Service Bus that would take
- fully qualified namespace
- entity path (optional, could be named "EventHubName" in Event Hubs and "QueueOrTopicName in Service Bus)
- SharedAccessKey & SharedAccessKeyName (optional)
- SharedAccessSignature (optional)

**Comment by ramya-rao-a** [comment] 2020-10-13 02:52
cc @jsquire, @JoshLove-msft, @MiYanni

**Comment by jsquire** [comment] 2020-10-13 13:41
I'm going to close this as a dupe of #12564.  That design would extend to both messaging services.

**Closed by jsquire** 2020-10-13 13:41 UTC
Labels: Client, Event Hubs, Service Bus, needs-team-triage
