### ISSUE TITLE
[BUG] [Search] FieldBuilder.BuildForTypeRecursive Stackoverflow/Stack empty. 

### ISSUE THREAD

**Issue by YouLearnSomethingNewEveryDay** [Azure/azure-sdk-for-net#11114] opened 2020-04-07 13:42 UTC
sdk/search/Microsoft.Azure.Search.Service/src/Customizations/Indexes/FieldBuilder/FieldBuilder.cs
Microsoft.Azure.Search 10.1.0

I'm not sure I'd even call this a bug, more of a bad designed on the users part. But I figured I'd let you guys know. 

Example:
```C#
  public class TestClass
    {
        [Key]
        public string ID { get; set; }

        public Level Level1 { get; set; }
    }

    public class Level
    {
        public Level SubLevel { get; set; }

        public Level SubLevel2 { get; set; }

        [IsRetrievable(true)]
        public string Something { get; set; }
    }
```
Running the above class in the FieldBuilder  `FieldBuilder.BuildForType<TestClass>();` will cause System.StackOverflowException: 'Exception of type 'System.StackOverflowException' was thrown.'

```C#
    public class TestClass
    {
        [Key]
        public string ID { get; set; }

        public Level Level1 { get; set; }

        public Level Level2 { get; set; }

    }

    public class Level
    {
        public Level SubLevel { get; set; }

        [IsRetrievable(true)]
        public string Something { get; set; }
    }
```
Will cause System.InvalidOperationException: 'Stack empty.'

Like I said it's happens if the user has bad designed classes but I figured I'd let you guys know just in case you want to handle the exceptions and since it looks like in the code you guys are trying to skip recursive types (Which works if there is just one).

**Comment by heaths** [comment] 2020-04-08 17:42
Thanks for finding this. We have bug #8738 open on this already and will fix for the newer libraries that replace this - Azure.Search.Documents, currently in preview - soon. Assigning to @brjohnstmsft for the older code if he wants to take a fix currently.

**Comment by brjohnstmsft** [comment] 2020-04-20 20:53
The workaround for this issue is to mark the property of recursive type with `[FieldBuilderIgnore]`. Since there is a workaround and this is going to be fixed in the next major version, we won't be hotfixing this in the older libraries.

Closing this since the issue is tracked elsewhere already.

**Closed by brjohnstmsft** 2020-04-20 20:53 UTC
Labels: Client, Search, customer-reported, needs-attention
