### ISSUE TITLE
[BUG] Servicebus.ManagementClient enters error state during failover

### ISSUE THREAD

**Issue by tollstorff** [Azure/azure-sdk-for-net#7290] opened 2019-08-14 14:03 UTC
An instance of _Microsoft.Azure.ServiceBus.Management.ManagementClient_ pointing to an alias for a Premium Service Bus Geo-Recovery setup, can enter a permanent error state during failover.

The following snippet can be used to reproduce the issue. During a failover, this program will hit the catch-block over and over, and never recover.
```csharp
public static async Task FailsAndNeverRecovers() {
            var client = new ManagementClient(AliasConnectionString);
            var topic = await client.CreateTopicAsync(new TopicDescription("topic"));
            while (true)
            {
                try
                {
                    await client.TopicExistsAsync(topic.Path);
                    Console.WriteLine("Topic exists.");
                }
                catch (Exception ex)
                {
                    Console.WriteLine(ex.Message);
                }
                await Task.Delay((int)TimeSpan.FromSeconds(2).TotalMilliseconds);
            }
}
```

It is possible to recover from the error state, by not interacting with the management client for 2 minutes. This script will hit the catch-block once, but recover.

```csharp
public static async Task FailsButRecovers()
        {
            var client = new ManagementClient(AliasConnectionString);
            var topic = await client.CreateTopicAsync(new TopicDescription("topic"));

            var tryToRecover = false;
            while (true)
            {
                try
                {
                    await client.TopicExistsAsync(topic.Path);
                    Console.WriteLine("Topic exists.");
                }
                catch (Exception ex)
                {
                    trtryToRecover = true;
                    Console.WriteLine(ex.Message);
                }

                if (tryToRecover)
                {
                    tryToRecover = false;
                    await Task.Delay((int)TimeSpan.FromMinutes(2).TotalMilliseconds);
                }
                else
                {
                    await Task.Delay((int)TimeSpan.FromSeconds(2).TotalMilliseconds);
                }
            }
        }
```

The exception is a ServiceBusException ("The namespace x does not exist").

I have not been able to find information about this. Is this a known issue?
Is there a known workaround or best-practice to avoid this issue, besides creating a new ManagementClient each time?

**Comment by axisc** [comment] 2019-08-14 19:13
@tollstorff

Thanks for reporting this issue. I suspect that the amount of time you are seeing the "namespace does not exist" error is the time it takes to flush out the DNS entry and to point your alias from primary to secondary.

This is expected behavior, because at any point in time, your alias will either point to the primary or the secondary.

This is what we refer to as the RTO (Recovery time objective). An RTO of <5 mins is the expected. The only workaround in this case would be to rely on the retry policy of the SDK to automatically reconnect to the secondary once the failover is complete.

Do let us know if you have any other questions.

**Comment by tollstorff** [comment] 2019-08-14 19:25
Hi @axisc , thanks for getting back to me so quickly.

The error persists for a long time and definitely longer than 5 mins. In fact, I have not seen it recover **at all**, when using the first snippet from my original post. When using the second snippet, or when instantiating a new management client in each iteration, it will recover more or less immediately.

**Comment by axisc** [comment] 2019-08-16 18:07
@tollstorff

Thanks for sharing the details. In this case, we will have to investigate in our logs. Could you open a support ticket on Azure support and share the appropriate details about the namespace?

I'll close the issue and we can track this via support.

**Closed by axisc** 2019-08-16 18:07 UTC
Labels: Mgmt, Service Attention, Service Bus, customer-reported, customer-response-expected

**Comment by tollstorff** [comment] 2019-08-20 11:24
Hi @axisc,

I just want to make it clear that to me it seems like a client-side issue in SDK. I just ran something similar to both of the above programs, side-by-side. The first one never recovered, and the second one recovered after the delay (set it to 4 minutes to be safe).

Specifically it seems that if an error occurs within a single instance of a management client, it will somehow cache this error state, and the program needs to wait at least 2 minutes for it to clear the cache. The fact that I can run the other program at the same time against the same service bus alias, and it can recover seems to point towards this also.

Is it possible that you can try to reproduce this? It is not an elaborate setup - I created fresh service buses. The reproduction steps are:

1. Pair two service buses
2. Start the console app from the issue ("FailsAndNeverRecovers") and leave it running for e.g. 30 minutes
3. Trigger failover
4. Observe that it fails and never recovers

If you still want me to track this via support, I can do that, but please reply to this update.
