### ISSUE TITLE
[BUG] Trying to add a tag to a managed disk fails with InvalidResourceType

### ISSUE THREAD

**Issue by x-cubed** [Azure/azure-sdk-for-net#34796] opened 2023-03-09 01:35 UTC
### Library name and version

Azure.ResourceManager 1.4.0

### Describe the bug

Trying to add a tag to a managed disk via the `GenericResource` model using `AddTagAsync` or the `TagResource` model using `UpdateAsync` fails with the following exception:
```
Azure.RequestFailedException: The resource type 'locations/diskoperations' could not be found in the namespace 'Microsoft.Compute' for api version '2022-09-01'. The supported api-versions are '2016-04-30-preview,2017-03-30,2018-04-01,2018-06-01,2018-09-30,2019-03-01,2019-07-01,2019-11-01,2020-05-01,2020-06-30,2020-09-30,2020-12-01,2021-04-01,2021-08-01,2021-12-01,2022-03-02,2022-07-02,2023-01-02'.
Status: 404 (Not Found)
ErrorCode: InvalidResourceType

Content:
{"error":{"code":"InvalidResourceType","message":"The resource type 'locations/diskoperations' could not be found in the namespace 'Microsoft.Compute' for api version '2022-09-01'. The supported api-versions are '2016-04-30-preview,2017-03-30,2018-04-01,2018-06-01,2018-09-30,2019-03-01,2019-07-01,2019-11-01,2020-05-01,2020-06-30,2020-09-30,2020-12-01,2021-04-01,2021-08-01,2021-12-01,2022-03-02,2022-07-02,2023-01-02'."}}

Headers:
Cache-Control: no-cache
Pragma: no-cache
x-ms-failure-cause: REDACTED
x-ms-request-id: 894a79a4-c05b-4cb0-91c0-58fbdd41b169
x-ms-correlation-request-id: REDACTED
x-ms-routing-request-id: REDACTED
Strict-Transport-Security: REDACTED
X-Content-Type-Options: REDACTED
Date: Wed, 08 Mar 2023 05:56:34 GMT
Content-Type: application/json; charset=utf-8
Expires: -1
Content-Length: 423

   at Azure.Core.OperationInternal`1.GetResponseFromState(OperationState`1 state)
   at Azure.Core.OperationInternal`1.UpdateStatusAsync(Boolean async, CancellationToken cancellationToken)
   at Azure.Core.OperationInternalBase.UpdateStatusAsync(CancellationToken cancellationToken)
   at Azure.Core.OperationPoller.WaitForCompletionAsync(Boolean async, OperationInternalBase operation, Nullable`1 suggestedInterval, CancellationToken cancellationToken)
   at Azure.Core.OperationInternalBase.WaitForCompletionResponseAsync(Boolean async, Nullable`1 pollingInterval, String scopeName, CancellationToken cancellationToken)
   at Azure.Core.OperationInternal`1.WaitForCompletionAsync(Boolean async, Nullable`1 pollingInterval, CancellationToken cancellationToken)
   at Azure.Core.OperationInternal`1.WaitForCompletionAsync(CancellationToken cancellationToken)
   at Azure.ResourceManager.Resources.TagResource.CreateOrUpdateAsync(WaitUntil waitUntil, TagResourceData data, CancellationToken cancellationToken)
   at Azure.ResourceManager.Resources.GenericResource.AddTagAsync(String key, String value, CancellationToken cancellationToken)
```

### Expected behavior

The tag should be added successfully

### Actual behavior

The tag doesn't get added and the call fails with the `RequestFailedException` stating `InvalidResourceType` (as shown above)

### Reproduction Steps

1. Create or fetch a `GenericResource` representing an Azure Virtual Machine managed disk
2. Call `AddTagAsync` on the `GenericResource` to add a new tag
3. Call fails with a `RequestFailedException`

### Environment

Azure Function App on Linux, runtime version 4.
Visual Studio 2022 17.5.1

**Comment by x-cubed** [comment] 2023-03-09 01:47
This looks like it's another version of #34568 with a different resource type

**Comment by ArcturusZhang** [comment] 2023-03-09 04:18
Based on the log I have on my side, the SDK is sending these requests:
```
PUT https://management.azure.com/subscriptions/db1ab6f0-4769-4b27-930e-01e2ef9c123c/resourceGroups/dapzhang-test/providers/Microsoft.Compute/disks/test-disk/providers/Microsoft.Resources/tags/default?api-version=2022-09-01
GET https://management.azure.com/subscriptions/db1ab6f0-4769-4b27-930e-01e2ef9c123c/providers/Microsoft.Compute/locations/westus2/DiskOperations/12c8d09a-1b06-419f-a57b-c40462884640?p=REDACTED&monitor=REDACTED&api-version=2022-09-01
```
The first is creating the tag resource for this disk resource with the correct api-version (2022-09-01 for tag resource)
The second is the LRO polling operation for updating the tag resource, based on the resource type in the request, the api-version (2022-09-01) is not correct - api-version for disk rp should be correct (2022-07-02)

This issue might be caused by recent update of resources, in which the tag resource create operation changed to an LRO, and we are replacing the api-version in the pulling request to the api-version on the original request. See here in the header the api-version is actually correct.
![image](https://user-images.githubusercontent.com/10554446/223915645-344e01d8-65fb-4b03-8a60-ac3a05de02c0.png)

We will fix it, sorry for the inconvenience.

**Comment by ArcturusZhang** [comment] 2023-03-09 04:24
Based on the log I have on my side, the SDK is sending these requests:
```
PUT https://management.azure.com/subscriptions/{subsId}/resourceGroups/dapzhang-test/providers/Microsoft.Compute/disks/test-disk/providers/Microsoft.Resources/tags/default?api-version=2022-09-01
GET https://management.azure.com/subscriptions/{subsId}/providers/Microsoft.Compute/locations/westus2/DiskOperations/12c8d09a-1b06-419f-a57b-c40462884640?p=REDACTED&monitor=REDACTED&api-version=2022-09-01
```
The first is creating the tag resource for this disk resource with the correct api-version (2022-09-01 for tag resource)
The second is the LRO polling operation for updating the tag resource, based on the resource type in the request, the api-version (2022-09-01) is not correct - api-version for disk rp should be correct (2022-07-02)

This issue might be caused by recent update of resources, in which the tag resource create operation changed to an LRO, and we are replacing the api-version in the pulling request to the api-version on the original request. See here in the header the api-version is actually correct.
![image](https://user-images.githubusercontent.com/10554446/223916271-64f5aa74-760f-4999-b63e-1c2bcecd45fa.png)


We will fix it, sorry for the inconvenience.

**Comment by ArcturusZhang** [comment] 2023-04-19 00:28
Hi @MikeHook, sorry for the delay of response - this issue will be fixed by the end of next week if everything goes well

**Closed** 2023-05-06 03:30 UTC
Labels: Mgmt, customer-reported, question
