### ISSUE TITLE
Azure.Core 1.44.1 with bug on Dependency System.Memory.Data 6.0.0 for instruction BinaryData.Empty.ToString()

### ISSUE THREAD

**Issue by Riccardonewall1985** [Azure/azure-sdk-for-net#46734] opened 2024-10-21 15:04 UTC
Unable to use NuGet package Azure.Core 1.44.1 with Dependency System.Memory.Data 6.0.0 on .NET 8 Application.
The previous version Azure.Core 1.43.0 with Dependency System.Memory.Data 1.0.2 is working well.

Suggestion: Update Dependency System.Memory.Data to version 8.0.1 for Azure.Core 1.44.1 NuGet package.

Steps to reproduce the bug:
Create a console app with .NET 8
Install NuGet package Azure.Core 1.44.1 (with Dependency System.Memory.Data 6.0.0)
Write this code line: string data = BinaryData.Empty.ToString();
Run...
You get: System.ArgumentNullException: 'Value cannot be null. (Parameter 'bytes')'

**Comment by annelo-msft** [comment] 2024-10-21 15:28
@m-redding, would it be possible to help understand this issue and advise?  Is the reported exception one of the known issues for BinaryData, and do we have a good workaround?  Thanks!

**Comment by m-redding** [comment] 2024-10-21 15:40
This is a duplicate of https://github.com/Azure/azure-sdk-for-net/issues/46444, you can look at the discussion there for more information. This is unfortunately a bug in the System.Memory.Data package, not Azure.Core. You can add a direct reference in your application to hoist the package to 8.0.1 and it will fix this problem

**Closed** 2024-10-28 16:38 UTC
Labels: Client, Azure.Core, customer-reported, question, issue-addressed
