### ISSUE TITLE
[BUG] queues string storing sometimes malformed with SendMessage / SendMessageAsync

### ISSUE THREAD

**Issue by MetzenAsh** [Azure/azure-sdk-for-net#12651] opened 2020-06-09 14:30 UTC
![queues-issue](https://user-images.githubusercontent.com/10828662/84157084-30c5ae80-aa62-11ea-8a9a-6c0eddf76252.png)
Some strings end up malformed in the queue. See the screenshot for a set of strings in my sqlite table (left) and how they end up in my emulator's queue.
- the same behaviour with both azure storage emulator and actual azure cloud account
- the same behaviour with both SendMessage and SendMessageAsync methods
- the same behaviour when sqlite is not involved (just hard-coded literals in REPL (F# Interactive)
- the same behaviour with 12.3.1, 12.3.2 lib versions

**Expected behavior**
The MessageText strings stored in the queue being the same as the strings I passed to the method.

**Actual behavior (include Exception or Stack Trace)**
The MessageText strings stored in the queue are sometimes malformed, not the strings I passed to the method. It seems that the malformed strings always appear for specific input strings, this is not hapenning randomly. the same string, say "Rese" or "Resettlement" will always store the malformed version.

**To Reproduce**
these two lines used in REPL should be enough to reproduce this with the storage. Preceeded with some lib referencing lines and opens, ofc.

let queueClient = QueueClient(myConnString, "myqueue")
Async.AwaitTask(queueClient.SendMessageAsync(address)) |> Async.Catch |> Async.RunSynchronously

**Environment:**
 - Name and version of the Library package used: [e.g. Azure.Storage.Queues 12.3.2] 
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): Microsoft.NETCore.App 3.1.4
Microsoft.WindowsDesktop.App 3.1.4
 - IDE and version : Visual Studio 16.6.1

**Comment by seanmcc-msft** [comment] 2020-06-16 19:40
Hi @MetzenAsh, unfortunately I'm not able to repo the issue.  I think the issue is sqlite is encoding your messages in some way.

```
using Azure;
using Azure.Storage.Queues;
using Azure.Storage.Queues.Models;
using NUnit.Framework;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace ConsoleApp4
{
    class Program
    {
        static async Task Main(string[] args)
        {
            string connectionString = "";

            List<string> messages = new List<string>
            {
                "R",
                "Re",
                "Rese",
                "Reset",
                "Resett",
                "Resettl",
                "Resettle",
                "Resettlem",
                "Resettleme",
                "Resettlemen",
                "Resettlement",
            };

            QueueClient queueClient = new QueueClient(connectionString, "myqueuename4");
            try
            {
                await queueClient.CreateAsync();

                foreach(string message in messages)
                {
                    await queueClient.SendMessageAsync(message);
                }

                Response<QueueMessage[]> response = await queueClient.ReceiveMessagesAsync(maxMessages: messages.Count);

                Assert.AreEqual(messages.Count, response.Value.Length);
                for (int i = 0; i < response.Value.Length; i++)
                {
                    Assert.AreEqual(messages[i], response.Value[i].MessageText);
                }
            }
            finally
            {
                await queueClient.DeleteAsync();
            }
        }
    }
}
```

**Example request and response in Fiddler sending a message:**
```
POST https://seanmcccanary.queue.core.windows.net/myqueuename4/messages HTTP/1.1
Host: seanmcccanary.queue.core.windows.net
x-ms-version: 2018-11-09
x-ms-client-request-id: 8f00b79d-f331-4115-9c91-bb63334e370a
x-ms-return-client-request-id: true
User-Agent: azsdk-net-Storage.Queues/12.3.2 (.NET Core 3.1.4; Microsoft Windows 10.0.18362)
x-ms-date: Tue, 16 Jun 2020 19:33:03 GMT
Authorization: SharedKey seanmcccanary:jqWX4HzRgROsvKns1p8/UgGedIcX7qC2dASyw5QR2lg=
Request-Id: |63ef8dac-418144bea5d8d5fc.
Content-Type: application/xml
Content-Length: 68

<QueueMessage><MessageText>Resettlement</MessageText></QueueMessage>

HTTP/1.1 201 Created
Content-Type: application/xml
Server: Windows-Azure-Queue/1.0 Microsoft-HTTPAPI/2.0
x-ms-request-id: 2a4b4f4f-7003-0051-6c14-44d02c000000
x-ms-version: 2018-11-09
Date: Tue, 16 Jun 2020 19:33:02 GMT
Content-Length: 407

<?xml version="1.0" encoding="utf-8"?><QueueMessagesList><QueueMessage><MessageId>5ad211b1-c414-4dbc-8277-68a7a628c307</MessageId><InsertionTime>Tue, 16 Jun 2020 19:33:03 GMT</InsertionTime><ExpirationTime>Tue, 23 Jun 2020 19:33:03 GMT</ExpirationTime><PopReceipt>AgAAAAMAAAAAAAAAxxGw8xRE1gE=</PopReceipt><TimeNextVisible>Tue, 16 Jun 2020 19:33:03 GMT</TimeNextVisible></QueueMessage></QueueMessagesList>

```
Note that the SDK has not modified the message before it was sent.

**Get Messages request and response:**
```
GET https://seanmcccanary.queue.core.windows.net/myqueuename4/messages?numofmessages=11 HTTP/1.1
Host: seanmcccanary.queue.core.windows.net
x-ms-version: 2018-11-09
x-ms-client-request-id: ac462483-3ed5-4a57-9683-78a30ad9bba3
x-ms-return-client-request-id: true
User-Agent: azsdk-net-Storage.Queues/12.3.2 (.NET Core 3.1.4; Microsoft Windows 10.0.18362)
x-ms-date: Tue, 16 Jun 2020 19:33:03 GMT
Authorization: SharedKey seanmcccanary:efVxyjzfN0/SHGFx8/hD5O/sYhb5ILdcrv+uhsKX6Tc=
Request-Id: |63ef8dad-418144bea5d8d5fc.

<?xml version="1.0" encoding="utf-8"?>
<QueueMessagesList>
	<QueueMessage>
		<MessageId>03c3d829-2193-47c1-8591-51aba440509c</MessageId>
		<InsertionTime>Tue, 16 Jun 2020 19:33:02 GMT</InsertionTime>
		<ExpirationTime>Tue, 23 Jun 2020 19:33:02 GMT</ExpirationTime>
		<PopReceipt>AgAAAAMAAAAAAAAAmYSgBRVE1gE=</PopReceipt>
		<TimeNextVisible>Tue, 16 Jun 2020 19:33:33 GMT</TimeNextVisible>
		<DequeueCount>1</DequeueCount>
		<MessageText>R</MessageText>
	</QueueMessage>
	<QueueMessage>
		<MessageId>4a8f1d40-63dd-46a1-81f3-c252698633e4</MessageId>
		<InsertionTime>Tue, 16 Jun 2020 19:33:02 GMT</InsertionTime>
		<ExpirationTime>Tue, 23 Jun 2020 19:33:02 GMT</ExpirationTime>
		<PopReceipt>AgAAAAMAAAAAAAAAmYSgBRVE1gE=</PopReceipt>
		<TimeNextVisible>Tue, 16 Jun 2020 19:33:33 GMT</TimeNextVisible>
		<DequeueCount>1</DequeueCount>
		<MessageText>Re</MessageText>
	</QueueMessage>
	<QueueMessage>
		<MessageId>a7df886d-1fe2-47ef-9834-cf7f2fd14e0f</MessageId>
		<InsertionTime>Tue, 16 Jun 2020 19:33:02 GMT</InsertionTime>
		<ExpirationTime>Tue, 23 Jun 2020 19:33:02 GMT</ExpirationTime>
		<PopReceipt>AgAAAAMAAAAAAAAAmYSgBRVE1gE=</PopReceipt>
		<TimeNextVisible>Tue, 16 Jun 2020 19:33:33 GMT</TimeNextVisible>
		<DequeueCount>1</DequeueCount>
		<MessageText>Rese</MessageText>
	</QueueMessage>
	<QueueMessage>
		<MessageId>2c7dce6b-5891-4485-b603-21f9895de92c</MessageId>
		<InsertionTime>Tue, 16 Jun 2020 19:33:02 GMT</InsertionTime>
		<ExpirationTime>Tue, 23 Jun 2020 19:33:02 GMT</ExpirationTime>
		<PopReceipt>AgAAAAMAAAAAAAAAmYSgBRVE1gE=</PopReceipt>
		<TimeNextVisible>Tue, 16 Jun 2020 19:33:33 GMT</TimeNextVisible>
		<DequeueCount>1</DequeueCount>
		<MessageText>Reset</MessageText>
	</QueueMessage>
	<QueueMessage>
		<MessageId>cbd483e6-7b9e-4b54-8c47-0a6969835f69</MessageId>
		<InsertionTime>Tue, 16 Jun 2020 19:33:02 GMT</InsertionTime>
		<ExpirationTime>Tue, 23 Jun 2020 19:33:02 GMT</ExpirationTime>
		<PopReceipt>AgAAAAMAAAAAAAAAmYSgBRVE1gE=</PopReceipt>
		<TimeNextVisible>Tue, 16 Jun 2020 19:33:33 GMT</TimeNextVisible>
		<DequeueCount>1</DequeueCount>
		<MessageText>Resett</MessageText>
	</QueueMessage>
	<QueueMessage>
		<MessageId>73ff0717-f96b-483d-8df5-ad8b3feb828b</MessageId>
		<InsertionTime>Tue, 16 Jun 2020 19:33:02 GMT</InsertionTime>
		<ExpirationTime>Tue, 23 Jun 2020 19:33:02 GMT</ExpirationTime>
		<PopReceipt>AgAAAAMAAAAAAAAAmYSgBRVE1gE=</PopReceipt>
		<TimeNextVisible>Tue, 16 Jun 2020 19:33:33 GMT</TimeNextVisible>
		<DequeueCount>1</DequeueCount>
		<MessageText>Resettl</MessageText>
	</QueueMessage>
	<QueueMessage>
		<MessageId>16ac8344-ce1f-43c1-a183-99618c1edef1</MessageId>
		<InsertionTime>Tue, 16 Jun 2020 19:33:02 GMT</InsertionTime>
		<ExpirationTime>Tue, 23 Jun 2020 19:33:02 GMT</ExpirationTime>
		<PopReceipt>AgAAAAMAAAAAAAAAmYSgBRVE1gE=</PopReceipt>
		<TimeNextVisible>Tue, 16 Jun 2020 19:33:33 GMT</TimeNextVisible>
		<DequeueCount>1</DequeueCount>
		<MessageText>Resettle</MessageText>
	</QueueMessage>
	<QueueMessage>
		<MessageId>7f97e5c7-79ce-484a-9aed-f45fdbae78ca</MessageId>
		<InsertionTime>Tue, 16 Jun 2020 19:33:02 GMT</InsertionTime>
		<ExpirationTime>Tue, 23 Jun 2020 19:33:02 GMT</ExpirationTime>
		<PopReceipt>AgAAAAMAAAAAAAAAmYSgBRVE1gE=</PopReceipt>
		<TimeNextVisible>Tue, 16 Jun 2020 19:33:33 GMT</TimeNextVisible>
		<DequeueCount>1</DequeueCount>
		<MessageText>Resettlem</MessageText>
	</QueueMessage>
	<QueueMessage>
		<MessageId>e798f3a8-4cf1-44ce-8eb1-b18bc6120431</MessageId>
		<InsertionTime>Tue, 16 Jun 2020 19:33:03 GMT</InsertionTime>
		<ExpirationTime>Tue, 23 Jun 2020 19:33:03 GMT</ExpirationTime>
		<PopReceipt>AgAAAAMAAAAAAAAAmYSgBRVE1gE=</PopReceipt>
		<TimeNextVisible>Tue, 16 Jun 2020 19:33:33 GMT</TimeNextVisible>
		<DequeueCount>1</DequeueCount>
		<MessageText>Resettleme</MessageText>
	</QueueMessage>
	<QueueMessage>
		<MessageId>5e731453-a815-4edf-b23a-03d581fb2889</MessageId>
		<InsertionTime>Tue, 16 Jun 2020 19:33:03 GMT</InsertionTime>
		<ExpirationTime>Tue, 23 Jun 2020 19:33:03 GMT</ExpirationTime>
		<PopReceipt>AgAAAAMAAAAAAAAAmYSgBRVE1gE=</PopReceipt>
		<TimeNextVisible>Tue, 16 Jun 2020 19:33:33 GMT</TimeNextVisible>
		<DequeueCount>1</DequeueCount>
		<MessageText>Resettlemen</MessageText>
	</QueueMessage>
	<QueueMessage>
		<MessageId>5ad211b1-c414-4dbc-8277-68a7a628c307</MessageId>
		<InsertionTime>Tue, 16 Jun 2020 19:33:03 GMT</InsertionTime>
		<ExpirationTime>Tue, 23 Jun 2020 19:33:03 GMT</ExpirationTime>
		<PopReceipt>AgAAAAMAAAAAAAAAmYSgBRVE1gE=</PopReceipt>
		<TimeNextVisible>Tue, 16 Jun 2020 19:33:33 GMT</TimeNextVisible>
		<DequeueCount>1</DequeueCount>
		<MessageText>Resettlement</MessageText>
	</QueueMessage>
</QueueMessagesList>
```

**Comment by MetzenAsh** [comment] 2020-06-16 20:04
this was happening even without sqlite involved. at that stage (my first azure function project) i was still learning, and often i had weird mixture of libraries of all sorts of versions loaded (queues, tables, cosmos db...). i'm wondering if a particular version mix could be behind this.

**Comment by seanmcc-msft** [comment] 2020-06-16 20:08
Ya something seems to be encoding your text.  I think it might be useful to try with less libraries (and a fresh project) and see if you are still encountering the issue.

**Comment by seanmcc-msft** [comment] 2020-06-24 17:54
I'm going to close this issue, please feel free to re-open if you have any other questions.

**Closed by seanmcc-msft** 2020-06-24 17:54 UTC
Labels: Client, Service Attention, Storage, customer-reported, question
