### ISSUE TITLE
Fluent SDK doesn't run under ASP.NET in .Net 4.5.2

### ISSUE THREAD

**Issue by nicksav** [Azure/azure-sdk-for-net#3238] opened 2017-05-19 03:08 UTC
Guys, I might be doing something wrong, but I can't get anything to work at all. 

```
AzureCredentials azureCredentials = new AzureCredentials(servicePrincipalLoginInformation, TenantId, AzureEnvironment.AzureGlobalCloud);
            Azure azure = Azure.Authenticate(azureCredentials).WithSubscription(SubscriptionId) as Azure;
```

This is my auth code. Doesn't return any error. After I am trying to provision a Resource group and its just stuck without any errors or anything. The same behavior for any api call. Any idea?

```             
message.InnerText = "Resource Group Doesnt Exists " + DateTime.Now.ToShortDateString();

var groupName = SdkContext.RandomResourceName(dealerID + "_" +"rsGroup_", 24);
resourceGroup = azure.ResourceGroups
           .Define(groupName)
           .WithRegion(Region.AustraliaSouthEast)
           .Create();

message.InnerText = "Creating Resource Group " + DateTime.Now.ToShortDateString();
```

**Comment by nicksav** [comment] 2017-05-19 03:57
Sorry, guys, It doesnt work in ASP.NET. Need to put the code into separate Thread, but still an issue.

**Comment by glaidler** [comment] 2017-06-07 10:51
@nicksav - think i've come across same issue, how did you get around it?

**Comment by nicksav** [comment] 2017-06-07 10:52
https://github.com/glaidler, just spin up a new thread and run the code inside.

**Comment by glaidler** [comment] 2017-06-07 11:24
ok - got it working.  thanks, bit of a pain queuing in and out of new thread, but seems to work.

**Comment by pppchris** [comment] 2017-06-08 02:30
Just in case someone else has this issue, using the async methods and async controllers in MVC resolves this problem..

**Comment by xcrover** [comment] 2017-06-21 18:42
Hello Guys,
I tried different types of threading:
- async+await
- Task<T>
- ThreadPool.QueueUserWorkItem
- new Thread()

Nothing worked with MVC.NET 5.2.3) on .NET 4.5.2 with Microsoft.Azure.Management.Fluent 1.0.0.60 that I got from NuGet because of exactly the same problem:
    TokenCache: No matching token was found in the cache

The same code works just fine from desktop application.
Is there any example projects that I can look at?

**Comment by pppchris** [comment] 2017-06-23 01:00
Here is an example I got working as an example but have the same method working for Dns and VMs.

`var vmSet = await Repo.VirtualMachineScaleSets.GetByIdAsync(setId);
var publicLBTask = Task.Run( () => vmSet.GetPrimaryInternetFacingLoadBalancer() );
var internalLBTask = Task.Run(() => vmSet.GetPrimaryInternalLoadBalancer() );  
 `
Using .net 4.5.2, MVC 5.2.3 and Fluent 1.1.1 (but it worked on 1.0 also).

**Comment by glaidler** [comment] 2017-06-23 16:25
This works for me without using async controllers - however I am using ServiceStack, but should(!) work for you too... 

          var q = new ConcurrentQueue<List<AppServicePlan>>();
           var t = new Thread(() =>
            {
                var appServices = _azure.AppServices.AppServicePlans.List();
               q.Enqueue(appServices);
                
            });
            t.Start();
            t.Join();
            return q.First();`

**Comment by xcrover** [comment] 2017-06-23 19:27
Thank you guys! 
The problem was not in my code but in the corporate proxy.
Everything worked when I tried it from another location.

**Comment by carloscds** [comment] 2017-07-04 13:50
@glaidler I have same problem in Windows Form application, and using Thread works for me!

**Comment by brijeshb** [comment] 2017-07-18 08:46
WithDefaultSubscription() was the point of failure (deadlock / non-responsiveness) for me, i got around it, by momentarily running that on a different thread pool thread.

```
var zz = Azure.Authenticate(creds);
IAzure azure = null;
await Task.Run(() =>
                           {
                               // Seems to have thread deadlock bug because of Wait() and await, run this on a different thread to bypass this
                               azure = zz.WithDefaultSubscription();
                           });
```

followed by using async methods wherever possible such as 
`
var accounts = await azure.StorageAccounts.ListAsync();
`
This almost feels like the common deadlock bug that i fixed resolved recently with occurs when one mixes Wait() and await, both of them deadlock the SynchronizationContext in ASP.NET

**Comment by abhi1509** [comment] 2017-07-19 18:46
hitting the same issue in ResourceGroups.CheckExistence(resourceGroupName)

**Comment by hovsepm** [comment] 2017-07-19 23:25
Could anyone share a github ASP.NET project that has the repro steps for this issue? I'm unable to repro on ASP.NET .Net Core App 1.1 project. Following snippet just works fine. 
```
        public async Task<IActionResult> About()
        {
            ViewData["Message"] = "Your application description page.";

            var credentials = SdkContext.AzureCredentialsFactory.FromFile(Environment.GetEnvironmentVariable("AZURE_AUTH_LOCATION"));

            var azure = Azure
                .Configure()
                .WithLogLevel(HttpLoggingDelegatingHandler.Level.None)
                .Authenticate(credentials)
                .WithDefaultSubscription();

            var groupName = SdkContext.RandomResourceName("something" + "_" + "rsGroup_", 24);
            var resourceGroup = await azure.ResourceGroups
                       .Define(groupName)
                       .WithRegion(Region.AustraliaSouthEast)
                       .CreateAsync();

            return View();
        }
```

**Comment by brijeshb** [comment] 2017-07-19 23:35
Please try the same on a traditional ASP.NET app, not a .Net Core app, .Net Core, removed synchronization contexts and that is potentially the reason you're not seeing this repro there.

**Comment by hovsepm** [comment] 2017-07-19 23:46
Thanks @brijeshb . Got repro on 
```
var resourceGroup = azure.ResourceGroups
                       .Define(groupName)
                       .WithRegion(Region.AustraliaSouthEast)
                       .Create();
```
but still no repro for 
```
var azure = Azure
                .Configure()
                .WithLogLevel(HttpLoggingDelegatingHandler.Level.None)
                .Authenticate(credentials)
                .WithDefaultSubscription();
```

**Comment by abhi1509** [comment] 2017-07-20 02:13
@hovsepm  this is also broken:
`azure.ResourceGroups.CheckExistence(resourceGroupName));`

**Comment by hovsepm** [comment] 2017-07-20 17:34
@abhi1509 Thanks for pointing out that one as well.

**Comment by hovsepm** [comment] 2017-07-20 17:46
@abhi1509 - FYI, just verified. CheckExistence hangs while CheckExistenceAsync works fine. here is the code:
```
public async Task<ActionResult> Index()
{
    var credentials = SdkContext.AzureCredentialsFactory.FromFile(Environment.GetEnvironmentVariable("AZURE_AUTH_LOCATION"));

    var azure = Azure
        .Configure()
        .WithLogLevel(HttpLoggingDelegatingHandler.Level.None)
        .Authenticate(credentials)
        .WithDefaultSubscription();

	var result = await azure.ResourceGroups.CheckExistenceAsync("somerandomnamegoeshere");
    ...
}
```
The issue is blocking Create scenarios where we create each dependent resource in parallel.

**Comment by hovsepm** [comment] 2017-07-27 21:53
Fixed. Will be available in next release.

**Comment by jialinjun** [comment] 2017-07-28 00:35
@hovsepm 
That is a good news. But could you give us an expectation of the release date ?

**Comment by hovsepm** [comment] 2017-07-28 17:24
@jialinjun Planning to ship next release in the end of August.

**Comment by fredcicles** [comment] 2017-08-01 19:33
I am getting similar issue with azure.VirtualMachines.Sizes.ListByRegion(region).  I do not see an Async version of this method.

**Comment by hovsepm** [comment] 2017-08-02 17:42
@fredcicles Sync methods should also be fixed in the next release (shipping End Of Month)

**Comment by pjdewaele** [comment] 2017-08-09 12:02
I had the same issues as mentioned above. Thanks for the tricks about tasks, it works for me. 
I want to share the fix too until the packages are updated. 

The code of @brijeshb worked for me except the `List` or `ListAsync` functions which i have bypassed in the same way as the authentication.

**Authentication Class**

```
        public IAzure GetAzure(string client, string secret, string tenant)
        {
            // get credentials
            AzureCredentials credentials = GetCredentials(client,secret,tenant);

            IAzure azure = null;
            var t = Task.Run(() =>
           {
               // Seems to have thread deadlock bug because of Wait() and await, run this on a different thread to bypass this
               var auth = Azure.Authenticate(credentials);
               azure = auth.WithDefaultSubscription();
           });

            t.GetAwaiter().GetResult();
            return azure;
        }
```

**VMClass**

```        
public List<AzureVMDto> getVMs(string resourceGroup)
        {
            _azure = _authRepo.GetAzure(client,secret,tenant);

            List<AzureVMDto> vms = null;
            var t = Task.Run(() =>
            {
                vms = _azure.VirtualMachines.ListByResourceGroup(resourceGroup).Select(x => new AzureVMDto()
                {
                    Name = x.Name,
                    ID = x.Id
                }).ToList();
            });

            t.GetAwaiter().GetResult();

            return vms;
        }
```

**Comment by hovsepm** [comment] 2017-08-28 20:58
[Release 1.2 is published to nuget](https://www.nuget.org/packages/Microsoft.Azure.Management.Fluent/1.2.0). Please upgrade your references.

**Closed by hovsepm** 2017-08-28 20:58 UTC
Labels: Fluent
