### ISSUE TITLE
Consider exposing Storage Account Id and Name from a virtual machine

### ISSUE THREAD

**Issue by awesley** [Azure/azure-sdk-for-net#3211] opened 2017-05-15 17:59 UTC
Hi,

I am using the Azure Fluent SDK.

I am implementing a feature similar to Virtual Scale Sets (but not using them) that will allow my application to provision and de-provision virtual machines based on some demand.  When I build the VM, I will create a new NIC and Storage Account.  When I delete the VM, I delete the associated NIC and Storage Account.

It is convenient to get the NIC, but I was unable to figure out how to associate my VM and its Storage Account through the standard API. 

Placing the ID in a tag works fine and is my current work around, but it seems like  since you can trivially create a storage account when creating a VM, you should be able to trivially retrieve it.

If I simply failed to find the correct documentation, just let me know! 

Thank you,
-awesley

**Comment by martinsawicki** [comment] 2017-06-02 20:39
yes, this sounds like a good idea to me.
@anuchandy what do you think?

**Comment by anuchandy** [comment] 2017-07-07 22:27
@awesley @martinsawicki sorry for the delay.

One issue with implementing this is: There can be different storage accounts associated with a virtual machine through it's child entities, i.e. you can have different storage accounts for OS Disk entity, data disk entities, boot diagnostics entity etc..

If you are really looking for the storage account associated with the OS Disk then it's **name** can be retrieved from VM.OSUnmanagedDiskVhdUri property.

All the above storage accounts instances are associated to the entities using the storage account URL not the ARM resource ID of the storage account,  network resources are referenced using ARM resourceID. Now retrieving the storage account id requires enumerating all the resource groups in the subscription and looking for the storage resource with the given name.

**Comment by martinsawicki** [comment] 2017-10-11 20:28
ok, closing as by design then, given the workaround

**Closed by martinsawicki** 2017-10-11 20:28 UTC
Labels: Fluent
