### ISSUE TITLE
[BUG] Should not have to disable VisualStudioCodeCredential on macOS

### ISSUE THREAD

**Issue by elliotchaim** [Azure/azure-sdk-for-net#19777] opened 2021-03-24 10:45 UTC
Re-open this issue: https://github.com/Azure/azure-sdk-for-net/issues/14362

**Comment by jsquire** [comment] 2021-03-24 13:02
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by christothes** [comment] 2021-03-29 15:42
Thanks @elliotchaim for raising this issue! I've re-opened the linked issue. I'll close this one out as a duplicate of #14362

**Comment by christothes** [comment] 2021-03-29 15:42
Duplicate of #14362

**Closed by christothes** 2021-03-29 15:42 UTC
Labels: Azure.Identity, Client, customer-reported, needs-team-attention, question
