### ISSUE TITLE
[Form Recognizer] The authentication method of weekly pipeline seems to have changed.

### ISSUE THREAD

**Issue by zedy-wj** [Azure/azure-sdk-for-net#46944] opened 2024-11-01 07:36 UTC
We are running live Tests against other clouds like US Gov and Azure China Cloud. The goal is to check whether new azure sdk package work with other clouds or not.

**Error Description:**
The authentication method of weekly pipeline seems to have changed again. The previously modified method of using `Azure***Msft.json` has an error. The error is as follows:
![Image](https://github.com/user-attachments/assets/c6c65008-3d6a-4121-8a7e-55b8b6fbec40)

What the latest authentication method is?

Pipeline status: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=4281458&view=results

**Expected behavior:**
All tests can pass normally.

@kinelski, @benbp for notification.

**Comment by jsquire** [comment] 2024-11-01 15:38
@zedy-wj :  There have been intentional changes to pipeline auth for security initiatives.   @weshaggard would be the best person to speak with about it.

**Comment by weshaggard** [comment] 2024-11-01 17:39
@zedy-wj I just made some suggestions to your PR that will help with some of these. 

Can I also ask why you have a 3 year old PR open?  Why are these not merged into main? If they were I would have updated these as well.

**Comment by benbp** [comment] 2024-11-01 20:16
See my comment at https://github.com/Azure/azure-sdk-for-js/pull/16213/files#r1826255473 for guidance on how to update the config now. We have removed a lot of duplicated config with this update.

@jsquire the old draft PR is primarily used as a vehicle for testing the pipelines, however any live testing changes should be merged into main once confirmed to be working.

@zedy-wj how many of the changes in these PRs are not merged into main? Ideally we should be able to close the draft PRs frequently because changes are landing back into the main branch.

**Comment by zedy-wj** [comment] 2024-11-04 03:10
> [@zedy-wj](https://github.com/zedy-wj) how many of the changes in these PRs are not merged into main? Ideally we should be able to close the draft PRs frequently because changes are landing back into the main branch.

@benbp for now, only the changes related to the `form recognizer` service have not been merged into the main branch. We will open a new draft PR for testing in our regular testing this month.

**Closed** 2024-12-02 03:22 UTC
Labels: EngSys, Central-EngSys

**Comment by zedy-wj** [comment] 2024-12-02 03:28
Closed as completed. Thanks all~
