### ISSUE TITLE
[BUG] Padding is invalid and cannot be removed while doing client side encryption for storage blob data using keyvault key

### ISSUE THREAD

**Issue by PPrabinKumarPatro** [Azure/azure-sdk-for-net#23082] opened 2021-08-03 21:43 UTC
**Describe the bug**
We are doing client side encryption for storage blob data using keyvault key.  This is the bug "https://github.com/Azure/azure-sdk-for-net/issues/16298" i intially filled for SNI. We were able to get it done but we are getting "Padding is invalid and cannot be removed" error now 

**Expected behavior**
Should successfully decrypt and encrypt the data 

**Actual behavior (include Exception or Stack Trace)**
Padding is invalid and cannot be removed error

**To Reproduce**
Steps to reproduce the behavior (include a code snippet, screenshot, or any additional information that might help us reproduce the issue)

code snippet is exactly explained here except we are using SNI 
https://github.com/Azure/azure-sdk-for-net/issues/16298

**Environment:**
 - Name and version of the Library package used: [e.g. Azure.Storage.Blobs 12.2.0] 
 Azure.Storage.Blobs : 12.8.0
 Azure.Identity is 1.4.0-beta.1
 Azure.Security.KeyVault.Keys 4.2.0-beta.2
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): [e.g. Azure AppService or Windows 10 .NET Framework 4.8]
 .Net core
 - IDE and version : [e.g. Visual Studio 16.3]
 Visual Studi 2019

Call stack:
```text
System.Security.Cryptography.CryptographicException:
   at Internal.Cryptography.UniversalCryptoDecryptor.DepadBlock (System.Security.Cryptography.Algorithms, Version=4.3.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a)
   at Internal.Cryptography.UniversalCryptoDecryptor.UncheckedTransformFinalBlock (System.Security.Cryptography.Algorithms, Version=4.3.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a)
   at Internal.Cryptography.UniversalCryptoTransform.TransformFinalBlock (System.Security.Cryptography.Algorithms, Version=4.3.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a)
   at System.Security.Cryptography.CryptoStream+<ReadAsyncCore>d__42.MoveNext (System.Security.Cryptography.Primitives, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Security.Cryptography.CryptoStream+<ReadAsyncInternal>d__37.MoveNext (System.Security.Cryptography.Primitives, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Azure.Storage.Shared.WindowStream+<ReadInternal>d__18.MoveNext (Azure.Storage.Blobs, Version=12.8.0.0, Culture=neutral, PublicKeyToken=92742159e12e44c8)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Azure.Storage.Shared.WindowStream+<ReadAsync>d__17.MoveNext (Azure.Storage.Blobs, Version=12.8.0.0, Culture=neutral, PublicKeyToken=92742159e12e44c8)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.IO.Stream+<CopyToAsyncInternal>d__30.MoveNext (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Azure.Storage.Blobs.PartitionedDownloader+<CopyToAsync>d__9.MoveNext (Azure.Storage.Blobs, Version=12.8.0.0, Culture=neutral, PublicKeyToken=92742159e12e44c8)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Azure.Storage.Blobs.PartitionedDownloader+<DownloadToAsync>d__5.MoveNext (Azure.Storage.Blobs, Version=12.8.0.0, Culture=neutral, PublicKeyToken=92742159e12e44c8)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Azure.Storage.Blobs.Specialized.BlobBaseClient+<StagedDownloadAsync>d__74.MoveNext (Azure.Storage.Blobs, Version=12.8.0.0, Culture=neutral, PublicKeyToken=92742159e12e44c8)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Azure.Storage.Blobs.Specialized.BlobBaseClient+<DownloadToAsync>d__72.MoveNext (Azure.Storage.Blobs, Version=12.8.0.0, Culture=neutral, PublicKeyToken=92742159e12e44c8)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Azure.Storage.Blobs.Specialized.BlobBaseClient+<DownloadToAsync>d__68.MoveNext (Azure.Storage.Blobs, Version=12.8.0.0, Culture=neutral, PublicKeyToken=92742159e12e44c8)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Microsoft.AzureMonitor.Billing.Common.Storage.AzureBlobStorageClient+<**DownloadStreamAsync**>d__11.MoveNext (Common, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null: C:\source\src\Common\Storage\AzureBlobStorageClient.cs:78)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Microsoft.AzureMonitor.Billing.LogAnalyticsCollectorBusiness.BlobHelper+<DownloadEHInfoFromBlobAsync>d__15.MoveNext (LogAnalyticsCollectorService, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null: C:\source\src\LogAnalyticsCollectorService\Business\BlobHelper.cs:244)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Microsoft.AzureMonitor.Billing.LogAnalyticsCollectorBusiness.BlobHelper+<CompareEHInfoWithBlob>d__13.MoveNext (LogAnalyticsCollectorService, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null: C:\source\src\LogAnalyticsCollectorService\Business\BlobHelper.cs:221)
```

**Comment by PPrabinKumarPatro** [comment] 2021-08-03 21:45
@jsquire @schaabs can you help here ? Thanks.

**Comment by jsquire** [comment] 2021-08-04 13:34
Hi @PPrabinKumarPatro.  Thank you for your feedback and we regret that you're experiencing difficulties.   I'm not sure the source of your error - specifically if you're seeing this when acquiring the token as you were with #16298 or if this is being surfaced by the KeyVault or Storage libraries.   If you're able to share a stack trace and any other context that you have, it would be helpful in finding the right people to assist.

For now, I've looped in our `Azure.Identity` experts for their thoughts.

**Comment by PPrabinKumarPatro** [comment] 2021-08-04 15:19
updated with call stack

**Comment by jsquire** [comment] 2021-08-04 15:22
Thank you!   The call stack appears to imply that this is occurring in the Storage SDK.   Rerouting to the storage team for assistance.

**Comment by PPrabinKumarPatro** [comment] 2021-08-05 09:09
HI Storage team, can you help here as we are having issues in most of prod regions including EUS, It would be challenging before it became bigger issue. Thanks.

**Comment by amnguye** [comment] 2021-08-05 17:06
Can you provide a more detailed code snippet where the key is being passed to the `BlobBaseClient`, I can tell you're doing a `DownloadToAsync` but the error "Padding is invalid.." is not included in the stack trace, but you said that this is the error that appears for you.

I wonder what's wrong with the key being passed to the `BlobBaseClient` to be causing this error with the `Cryptography` library.
@jaschrep-msft Feel free to chime in about this.

**Comment by jaschrep-msft** [comment] 2021-08-05 19:39
"Padding is invalid" is the hardest issue to track down. It essentially means that the last 16 byte encryption block was an unexpected value according to the AES specification and so there was some sort of error. Something could have gone wrong during encryption, decryption, key wrapping, key unwrapping, upload, download, or even blob metadata management; some piece of data is incorrect in the whole process.

In the past, this has come up when users are working with their own IKeyEncryptionKey and IKeyEncryptionKeyResolver implementations and they made an error developing them. This doesn't appear to be the case here, though, since you're using KeyVault SDK.

Additionally, you point us to your other issue for code snippets, but there isn't any code in there that uses the storage SDK. That will likely be necessary to figure out what is happening.

**Comment by PPrabinKumarPatro** [comment] 2021-08-24 20:50
Hi, what information do you need here to debug? Also can you ping me over teams for quick fix. We are still having the issue but in different region. The issue auto resolves in some regions by itself.

**Comment by PPrabinKumarPatro** [comment] 2021-08-24 20:54
below is the code and we use storage SDK (            BlobClient blobClient = containerClient.GetBlobClient("test").WithClientSideEncryptionOptions(clientSideOptions);)



//Create CryptographyClient using Key Vault Key
            CryptographyClient cryptographyClient = new CryptographyClient(clientSideKeyVaultKeyUri, credential);


            //Set up Client Side Encryption Options used for Client Side Encryption
            ClientSideEncryptionOptions clientSideOptions = new ClientSideEncryptionOptions(ClientSideEncryptionVersion.V1_0)
            {
                // KeyEncryptionKey = cryptographyClient,
                //KeyWrapAlgorithm = "RS256"
                KeyEncryptionKey = cryptographyClient,
               // KeyResolver = keyResolver,
                // string the storage client will use when calling IKeyEncryptionKey.WrapKey()
                KeyWrapAlgorithm = "RSA1_5"
            };


            //Create Blob Service Client
            BlobServiceClient blobServiceClient = new BlobServiceClient(storageConnectionString);

            BlobContainerClient containerClient = blobServiceClient.GetBlobContainerClient("example");
            //Create BlobClient with Client Side Encryption Options to upload client side encrypted data
            BlobClient blobClient = containerClient.GetBlobClient("test").WithClientSideEncryptionOptions(clientSideOptions);
            blobClient.Upload(stream);

**Comment by PPrabinKumarPatro** [comment] 2021-09-07 16:11
Any update here?

**Comment by jaschrep-msft** [comment] 2021-09-07 17:44
Taken offline. Will update here when conclusions are reached.

**Comment by irinasmt** [comment] 2021-10-07 19:01
@PPrabinKumarPatro Did you find any quick fix for this issue?

**Comment by wonderphil** [comment] 2021-10-11 11:17
Any updates one this please???

**Comment by jaschrep-msft** [comment] 2021-10-11 22:01
@wonderphil thank you! I will look into this with your sample when I have the time. However, at a glance, it looks like you've provided me with code that only does the download, decrypt, reencrypt, and reupload. The initial upload isn't present. Depending on what root cause is, that part may be relevant. If you could convert (or wrap) this sample to cut the queue out of the way and just upload a new blob that will still produce this issue, I can look into this with my own creds and account.

If you can't manage a reproduction that way, or if you don't get a consistent reproduction, that's important! Let me know here. But since you actively have an instance of this issue and I have been unable to reproduce one, you're likely to have the code somewhere that can set this situation up. Otherwise, if this code succeeds in decryption with some blob I upload myself, I won't have an actual reproduction.

**Comment by amishra-dev** [comment] 2022-02-21 01:22
@jaschrep-msft any progress on this?

**Comment by jaschrep-msft** [comment] 2022-02-22 17:55
Closing this issue. Feel free to reopen if the problem persists after eliminating this race condition.

**Closed by jaschrep-msft** 2022-02-22 17:55 UTC
Labels: Storage, Service Attention, Client, customer-reported, bug, needs-team-attention
