### ISSUE TITLE
[Azure.ResourceManager.Batch] TestRecordingMismatch Exceptions Preventing CIs from passing

### ISSUE THREAD

**Issue by annelo-msft** [Azure/azure-sdk-for-net#32733] opened 2022-11-28 23:23 UTC
Tests are failing in Azure.ResourceManager.Batch.Tests due to a TestRecordingMismatch exception.

Example exception:

```
Azure.Core.TestFramework.TestRecordingMismatchException : Unable to find a record for the request PUT https://management.azure.com/subscriptions/65634139-3762-476b-946d-e221f4cdc2bf/resourceGroups/testRG-1416/providers/Microsoft.Storage/storageAccounts/accountforbatch7571?api-version=2022-09-01
Uri doesn't match:
request https://management.azure.com/subscriptions/65634139-3762-476b-946d-e221f4cdc2bf/resourceGroups/testRG-1416/providers/Microsoft.Storage/storageAccounts/accountforbatch7571?api-version=2022-09-01  
record  https://management.azure.com/subscriptions/65634139-3762-476b-946d-e221f4cdc2bf/resourceGroups/testRG-1416/providers/Microsoft.Storage/storageAccounts/accountforbatch7571?api-version=2022-05-01  
Header differences:
Body differences:

 at Azure.Core.TestFramework.ProxyTransport.ProcessResponseAsync(HttpMessage message, Boolean async) in /mnt/vss/_work/1/s/sdk/core/Azure.Core.TestFramework/src/ProxyTransport.cs:line 122
   at Azure.Core.TestFramework.ProxyTransport.ProcessAsyncInternalAsync(HttpMessage message, Boolean async) in /mnt/vss/_work/1/s/sdk/core/Azure.Core.TestFramework/src/ProxyTransport.cs:line 87
   at Azure.Core.Pipeline.TaskExtensions.EnsureCompleted(Task task) in /mnt/vss/_work/1/s/sdk/core/Azure.Core/src/Shared/TaskExtensions.cs:line 43
   at Azure.Core.TestFramework.ProxyTransport.Process(HttpMessage message) in /mnt/vss/_work/1/s/sdk/core/Azure.Core.TestFramework/src/ProxyTransport.cs:line 62
   at Azure.Core.Pipeline.HttpPipelineTransportPolicy.Process(HttpMessage message, ReadOnlyMemory`1 pipeline) in /mnt/vss/_work/1/s/sdk/core/Azure.Core/src/Pipeline/Internal/HttpPipelineTransportPolicy.cs:line 38
   at Azure.Core.Pipeline.HttpPipelinePolicy.ProcessNext(HttpMessage message, ReadOnlyMemory`1 pipeline) in /mnt/vss/_work/1/s/sdk/core/Azure.Core/src/Pipeline/HttpPipelinePolicy.cs:line 49
   at Azure.Core.Pipeline.RequestActivityPolicy.ProcessNextAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async) in /mnt/vss/_work/1/s/sdk/core/Azure.Core/src/Pipeline/Internal/RequestActivityPolicy.cs:line 127
   at Azure.Core.Pipeline.RequestActivityPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async) in /mnt/vss/_work/1/s/sdk/core/Azure.Core/src/Pipeline/Internal/RequestActivityPolicy.cs:line 80
   at Azure.Core.Pipeline.TaskExtensions.EnsureCompleted(ValueTask task) in /mnt/vss/_work/1/s/sdk/core/Azure.Core/src/Shared/TaskExtensions.cs:line 63
   at Azure.Core.Pipeline.RequestActivityPolicy.Process(HttpMessage message, ReadOnlyMemory`1 pipeline) in /mnt/vss/_work/1/s/sdk/core/Azure.Core/src/Pipeline/Internal/RequestActivityPolicy.cs:line 47
   at Azure.Core.Pipeline.HttpPipelinePolicy.ProcessNext(HttpMessage message, ReadOnlyMemory`1 pipeline) in /mnt/vss/_work/1/s/sdk/core/Azure.Core/src/Pipeline/HttpPipelinePolicy.cs:line 49
   at Azure.Core.Pipeline.ResponseBodyPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async) in /mnt/vss/_work/1/s/sdk/core/Azure.Core/src/Pipeline/Internal/ResponseBodyPolicy.cs:line 56
   at Azure.Core.Pipeline.TaskExtensions.EnsureCompleted(ValueTask task) in /mnt/vss/_work/1/s/sdk/core/Azure.Core/src/Shared/TaskExtensions.cs:line 63
   at Azure.Core.Pipeline.ResponseBodyPolicy.Process(HttpMessage message, ReadOnlyMemory`1 pipeline) in /mnt/vss/_work/1/s/sdk/core/Azure.Core/src/Pipeline/Internal/ResponseBodyPolicy.cs:line 32
   at Azure.Core.Pipeline.HttpPipelinePolicy.ProcessNext(HttpMessage message, ReadOnlyMemory`1 pipeline) in /mnt/vss/_work/1/s/sdk/core/Azure.Core/src/Pipeline/HttpPipelinePolicy.cs:line 49
   at Azure.Core.Pipeline.LoggingPolicy.Process(HttpMessage message, ReadOnlyMemory`1 pipeline) in /mnt/vss/_work/1/s/sdk/core/Azure.Core/src/Pipeline/Internal/LoggingPolicy.cs:line 39
   at Azure.Core.Pipeline.HttpPipelinePolicy.ProcessNext(HttpMessage message, ReadOnlyMemory`1 pipeline) in /mnt/vss/_work/1/s/sdk/core/Azure.Core/src/Pipeline/HttpPipelinePolicy.cs:line 49
   at Azure.Core.Pipeline.HttpPipelineSynchronousPolicy.Process(HttpMessage message, ReadOnlyMemory`1 pipeline) in /mnt/vss/_work/1/s/sdk/core/Azure.Core/src/Pipeline/HttpPipelineSynchronousPolicy.cs:line 36
   at Azure.Core.Pipeline.HttpPipelinePolicy.ProcessNext(HttpMessage message, ReadOnlyMemory`1 pipeline) in /mnt/vss/_work/1/s/sdk/core/Azure.Core/src/Pipeline/HttpPipelinePolicy.cs:line 49
   at Azure.Core.Pipeline.BearerTokenAuthenticationPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async) in /mnt/vss/_work/1/s/sdk/core/Azure.Core/src/Pipeline/BearerTokenAuthenticationPolicy.cs:line 128
   at Azure.Core.Pipeline.TaskExtensions.EnsureCompleted(ValueTask task) in /mnt/vss/_work/1/s/sdk/core/Azure.Core/src/Shared/TaskExtensions.cs:line 63
   at
```

See full details in:
https://dev.azure.com/azure-sdk/public/_build/results?buildId=2016895&view=ms.vss-test-web.build-test-results-tab&runId=37391788&resultId=100062&paneView=debug

**Comment by m-nash** [comment] 2022-11-29 17:51
@weshaggard  the issue comes from this PR https://github.com/Azure/azure-sdk-for-net/pull/32588 which went in and passed the CI.  The reason this passed the CI was that Azure.ResourceManager.Batch only ran on the PackageReference variant and never on the ProjectReference variant.

Can we maybe make the sparse matrix less sparse and guarantee that everything is run on at both variants?

**Comment by m-nash** [comment] 2022-11-29 17:54
@Yao725 can we please run your latest version using project reference on all mgmt plane libraries that have a test dependency on Azure.ResourceManager.Storage?  At least Azure.ResourceManager.Batch needs to run.

The command to run using project reference locally is
`dotnet test /p:UseProjectReferenceToAzureClients=true`

**Comment by weshaggard** [comment] 2022-11-29 22:23
>Can we maybe make the sparse matrix less sparse and guarantee that everything is run on at both variants?

We could definitely attempt to do that if needed. I'm not entirely sure how this would break the recorded tests though. In either case if this is a missing scenario we feel is worth covering then please file another specific issue for this work.

**Comment by ArthurMa1978** [comment] 2022-11-30 00:06
This is another case caused by dependence upgrade, we need to exclude record operations from dependences for all RPs.

**Comment by archerzz** [comment] 2022-11-30 03:36
> > Can we maybe make the sparse matrix less sparse and guarantee that everything is run on at both variants?
> 
> We could definitely attempt to do that if needed. I'm not entirely sure how this would break the recorded tests though. In either case if this is a missing scenario we feel is worth covering then please file another specific issue for this work.

@weshaggard `Azure.ResourceManager.Batch` tests depend on `Azure.ResourceManager.Storage` by package reference. The problem is that there are some updates in `Azure.ResourceManager.Storage` (e.g. bump the latest service version), but a new version of package is not released yet. So, if the package reference is replaced by project reference, the `apiVersion` is different. That's why the test recording does not match.

**Comment by archerzz** [comment] 2022-11-30 03:58
Media service is impacted as well, see [here](https://dev.azure.com/azure-sdk/public/_build/results?buildId=2020816&view=logs&j=7e869f6a-bcd2-5520-9c1e-ff2d3950cc69&t=fa80074d-2c1f-51c3-773d-9f25d9720ff7&l=410).

**Comment by Yao725** [comment] 2022-11-30 16:07
This issue should be fixed by https://github.com/Azure/azure-sdk-for-net/pull/32778

**Comment by m-nash** [comment] 2022-11-30 18:54
@weshaggard https://github.com/Azure/azure-sdk-tools/issues/4844

**Closed** 2022-12-01 08:27 UTC
Labels: Batch, Mgmt-EngSys, Mgmt, test-reliability
