### ISSUE TITLE
[BUG]Service Bus QueueClient throws continual stream of exceptions when Queue status set to ReceiveDisabled

### ISSUE THREAD

**Issue by adamkjonesmesh** [Azure/azure-sdk-for-net#12935] opened 2020-06-22 19:32 UTC
**Describe the bug**
Setup a queue client and register a message handler.  This requires you to register an exception handler.  Once active and listening to a service bus queue, set the queue status to ReceiveDisabled.  Once that happens, the service bus queue client starts throwing what is essentially a stream of exceptions with the same exception message.  The message will be something like: "Message handler encountered an exception Microsoft.Azure.ServiceBus.MessagingEntityDisabledException: Messaging entity 'sb://{sbnamespaceurl}.servicebus.windows.net/{somequeuename}' is currently disabled."

The problem here is that when this happens, even if I put **nothing** in the exception handler but a return of Task.Completed, my CPU starts cranking up.  If I have multiple queue listeners (which I do) then it takes my CPU to max levels.

This seems like a bug.  If not a bug then certainly undesired behavior as the queue client becomes unusable and even threatens the server by maxing out the CPU.

**Expected behavior**
I expect that when I set my queue to receivedisabled, the queue client will not continually throw these exceptions.

**Actual behavior (include Exception or Stack Trace)**
Please see my description above.

**To Reproduce**
See description above.

**Environment:**
 - Name and version of the Library package used: Microsoft.Azure.ServiceBus 4.1.3
 - IDE and version : Visual Studio 2019 Enterprise 16.6.2

**Comment by jsquire** [comment] 2020-06-23 12:50
//cc: @JoshLove-msft, @MiYanni

**Comment by nemakam** [comment] 2020-06-23 23:47
@adamkjonesmesh,
Could you provide some more details - 
1. How many concurrent operations are being done in the handler?
2. How long is the queue disabled?

Couple of things you could try - 
1. Put a Task.Delay() in the exception handler when this exception is thrown so that you reduce the number of exceptions thrown.
2. See if you can stop the handler when you run into this issue and then restart it after you think the entity is enabled.

This is by design currently, and throwing exceptions will always use more CPU. Not sure if anything else can be done here. I'm going to close this as by-design. If you think there are other solutions that SDK should provide, let us know and we can reopen it for you.

**Closed by nemakam** 2020-06-23 23:47 UTC
Labels: Client, Service Attention, Service Bus, customer-reported, needs-team-attention, question
