### ISSUE TITLE
[BUG] AI.FormRecognizer SDK not parsing date correctly

### ISSUE THREAD

**Issue by jsiegmund** [Azure/azure-sdk-for-net#19858] opened 2021-03-26 13:09 UTC
**Describe the bug**
Even though the form recognizer service is returning the correct date from a form, the SDK is failing at parsing it. 

**Expected behavior**
I expect the `DateTime` to be parsed in the right format, or at least to have some control over the locale which should be used for parsing. 

**Actual behavior (include Exception or Stack Trace)**
The `ValueData` property holds the string with the correct datetime value (nl-NL locale format), but the operation `FormField.Value.AsDate()` returns the error from line https://github.com/Azure/azure-sdk-for-net/blob/b752803792ebaddad5a4de009857b51f7c3f0399/sdk/formrecognizer/Azure.AI.FormRecognizer/src/FieldValue.cs#L266. This indicates the string value was not correctly parsed to a valid `DateTime` object.

Example: 
![datetime parse](https://user-images.githubusercontent.com/1820644/112636035-d654dd80-8e3c-11eb-814d-1563151b8801.png)

This perfectly valid date will throw the above error when trying to retrieve it using `AsDate()`.

**To Reproduce**
Steps to reproduce the behavior (include a code snippet, screenshot, or any additional information that might help us reproduce the issue)

1. Recognize a document in another locale than en-US
2. Try to exact a `DateTime` field as mentioned

**Environment:**
 - Azure.AI.FormRecognizer
 - Windows 10, .NET SDK 5.0.201, Host version 5.0.4
 - Visual Studio 16.9.2

**Comment by jsquire** [comment] 2021-03-26 13:52
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by maririos** [comment] 2021-03-29 14:10
Thanks for the information @jsiegmund . Which version f the SDK are you targeting? and which endpoint? or do you see this in all endpoints

**Comment by jsiegmund** [comment] 2021-04-01 19:21
Our version of Azure.AI.FormRecognizer is 3.0.0. I'm not entirely sure what you mean by "which endpoint" @maririos? We're targeting the form recognizer instance we've got running in azure. I'm not down sharing the name of that instance here but if you need it I can DM it.

**Comment by maririos** [comment] 2021-04-02 17:04
Oh, good point, I don't need your resource endpoint, my bad. I meant which method in the `FormRecognizerClient` are you calling? Is it `StartRecognizeContent` ?
Also to confirm, the date format and value the document has is `12-03-2021` right?
I am trying different combinations and can't make it fail, so wondering what am I missing

**Comment by jsiegmund** [comment] 2021-07-05 17:57
I'm sorry, I'm currently not working this project so I'll close the issue for now and get back later when it's still there.

**Comment by yowl** [comment] 2022-02-16 16:22
Can we reopen this?  I have the same problem with "05.10.2022".  `AsDate`  throws an exception, but its easy to parse to date if you know the locale.  Can we have `TryAsDate` so we don't have to rely on exceptions?

**Comment by jsiegmund** [comment] 2022-02-17 18:23
@yowl i've reopened it for you. I'm not using FormRecognizer any more but feel free to hijack :).

**Comment by yowl** [comment] 2023-07-13 23:18
I would say yes because with 4.0.0 `DocumentAnalysisModelFactory.DocumentFieldValueWithDateFieldType` cannot accept a string so there is no means to test.

**Comment by kinelski** [comment] 2023-07-17 18:41
> I would say yes because with 4.0.0 `DocumentAnalysisModelFactory.DocumentFieldValueWithDateFieldType` cannot accept a string so there is no means to test.

`DocumentFieldValue.AsDate` does not try to parse the content string. If you get an exception when you try to access it, it means that the service could not parse the date and hasn't returned a value to the SDK. In 4.0.0, when this happens, `DocumentField.FieldType` will be set to `DocumentFieldType.Unknown`, so you don't need to rely on exceptions:
```cs
if (field.FieldType == DocumentFieldType.Date)
{
    date = field.Value.AsDate();
}
else // field.FieldType is DocumentFieldType.Unknown
{
    date = /* parse date manually from DocumentField.Content */;
}
```

To reproduce this behavior with the model factory, you can call the `DocumentFieldValueWithUnknownFieldType` method:
```cs
var fieldValue = DocumentAnalysisModelFactory
    .DocumentFieldValueWithUnknownFieldType(expectedFieldType: DocumentFieldType.Date);
```

Please let me know if this solves your problem.

**Comment by yowl** [comment] 2023-07-18 23:08
@kinelski Thanks, I confirm that works for me.

**Comment by kinelski** [comment] 2023-07-18 23:18
> @kinelski Thanks, I confirm that works for me.

Awesome! Closing the issue as it's solved.

**Closed by kinelski** 2023-07-18 23:18 UTC
Labels: Client, customer-reported, question, Cognitive - Form Recognizer, issue-addressed
