### ISSUE TITLE
[BUG] BlobContainerClient.GetPropertiesAsync() returns BlobContainerProperties with PublicAccess null instead of PublicAccessType.None

### ISSUE THREAD

**Issue by egraff** [Azure/azure-sdk-for-net#33689] opened 2023-01-26 14:44 UTC
### Library name and version

Azure.Storage.Blobs 12.14.1

### Describe the bug

This is a dup of #27242. However, as that issue has been open for almost a year without getting any attention, I'm not sure it has been routed properly, so I'm trying to raise this again.

Using the `BlobContainerClient` to send a [Get Container Properties](https://docs.microsoft.com/en-us/rest/api/storageservices/get-container-properties) request using the `GetPropertiesAsync()` method, i.e.

```csharp
Response<BlobContainerProperties> propertiesResponse = await containerClient.GetPropertiesAsync().ConfigureAwait(false);
```

if the container is configured for _no public access_, the returned `PublicAccess` of the `BlobContainerProperties` is `null`, instead of `PublicAccessType.None`, i.e.

```csharp
propertiesResponse.Value.PublicAccess == null
```

instead of 

```csharp
propertiesResponse.Value.PublicAccess == PublicAccessType.None
```

This is most likely caused by how the `x-ms-blob-public-access` header is being treated when the response is deserialized. According to the [Get Container Properties](https://docs.microsoft.com/en-us/rest/api/storageservices/get-container-properties) documentation for the `x-ms-blob-public-access` header:

> If this header is not returned in the response, the container is private to the account owner.

This is a regression, as this used to work in Azure.Storage.Blobs 12.8.4.

### Expected behavior

The `PublicAccess` of a `BlobContainerProperties` should be set to `PublicAccessType.None` if a Get Container Properties response did not contain an `x-ms-blob-public-access` header.

### Actual behavior

The `PublicAccess` of a `BlobContainerProperties` is set to `null` when a Get Container Properties response does not contain an `x-ms-blob-public-access` header, because the code fails to account for the absence of the header and how that should map to the `PublicAccessType.None` value for the `PublicAccessType` enum.

### Reproduction Steps

This was reproduced using an integration testing regression suite that emulates the Azure Blob Storage API. It can be easily reproduced by simply doing a Get Container Properties request towards real Azure Blob Storage using `BlobContainerClient.GetPropertiesAsync()`.

### Environment

```
> dotnet --info
.NET SDK:
 Version:   7.0.102
 Commit:    4bbdd14480

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19044
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.102\

Host:
  Version:      7.0.2
  Architecture: x64
  Commit:       d037e070eb

.NET SDKs installed:
  7.0.102 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

**Comment by navba-MSFT** [comment] 2023-01-27 02:39
@egraff Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment] 2023-01-27 09:19
@egraff This issue is a duplicate of https://github.com/Azure/azure-sdk-for-net/issues/27242

I am looping in the right folks on that issue to prioritize it and make some progress on that.

**Closed by navba-MSFT** 2023-01-27 09:19 UTC
Labels: Storage, Client, customer-reported, question, needs-team-attention, CXP Attention
