### ISSUE TITLE
[Core] Support for 100-continue flow

### ISSUE THREAD

**Issue by seanmcc-msft** [Azure/azure-sdk-for-net#34917] opened 2023-03-14 16:18 UTC
https://github.com/Azure/azure-sdk/issues/5787

**Comment by jsquire** [comment] 2023-03-14 17:10
Request will be costed and evaluated once archboard discussion for the linked issue has been completed.

**Comment by annelo-msft** [comment] 2023-03-24 16:00
Is this a duplicate of https://github.com/Azure/azure-sdk-for-net/issues/23957?  If so, it would be good to close one of them.

**Comment by jsquire** [comment] 2023-03-24 16:02
Apparently so.   Nice find!   Feel free to kill the one of your choice.  Neither seems to have any critical context.

**Comment by jsquire** [comment] 2023-06-21 19:31
After archboard discussions, this is not a feature that we currently plan on adding.   Closing out for now.

**Closed by jsquire** 2023-06-21 19:31 UTC
Labels: Client, Azure.Core, feature-request
