### ISSUE TITLE
[BUG] ArgumentNullException within Key Vault Certificate SDK

### ISSUE THREAD

**Issue by clairernovotny** [Azure/azure-sdk-for-net#11565] opened 2020-04-24 13:35 UTC
**Describe the bug**
Getting an ArgumentNullException when trying to delete an old CSR in Key Vault

**Expected behavior**
No exceptions

**Actual behavior (include Exception or Stack Trace)**
```
This exception was originally thrown at this call stack:
    System.Uri.Uri(string)
    Azure.Security.KeyVault.Certificates.DeletedCertificate.RecoveryId.get()
    Azure.Security.KeyVault.Certificates.DeleteCertificateOperation.DeleteCertificateOperation(Azure.Security.KeyVault.KeyVaultPipeline, Azure.Response<Azure.Security.KeyVault.Certificates.DeletedCertificate>)
    Azure.Security.KeyVault.Certificates.CertificateClient.StartDeleteCertificateAsync(string, System.Threading.CancellationToken)
    System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
    System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
    System.Runtime.CompilerServices.TaskAwaiter<TResult>.GetResult()
    SignService.Services.KeyVaultAdminService.CancelCsrAsync(string, string) in KeyVaultAdminService.cs

```

**To Reproduce**
Steps to reproduce the behavior (include a code snippet, screenshot, or any additional information that might help us reproduce the issue)

1. Have a key vault with an old CSR pending
2. Call StartDeleteCertificateAsync to remove it.

Not sure what in Key Vault would cause Recovery Id to be null but the library needs to handle it.

**Environment:**
 - Azure.Security.KeyVault.Certificates 4.0.2
 - .NET Core 3.1

**Comment by heaths** [comment] 2020-04-24 23:39
Duplicate of #11258. This will go out in our next preview (targeting June) with a workaround available that we recommend anyway: enable soft delete for your Key Vault. This is very helpful if you or someone else accidentally deletes a resource or even the entire vault. Eventually they are purged, but by default you have 90 days to recover or can purge them manually.

If you need this before then and cannot enable soft delete (enabled by default on new vaults), please let us know.

**Comment by heaths** [comment] 2020-04-25 03:30
I'm assuming the +1 meant the workaround was suitable 😉, so I'm closing the bug as a dup. If you need a fix earlier, please comment and/or reopen.

**Closed by heaths** 2020-04-25 03:30 UTC
Labels: Client, KeyVault, customer-reported, needs-attention, question
