### ISSUE TITLE
[BUG]Higher dependency in SDK than PowerShell

### ISSUE THREAD

**Issue by chidozieononiwu** [Azure/azure-sdk-for-net#25824] opened 2021-12-09 03:08 UTC
### Library name and version

Azure.Monitor.OpenTelemetry.Exporter

### Describe the bug

`Azure.Monitor.OpenTelemetry.Exporter` pull in `System.Diagnostics.DiagnosticSource : 5.0.*` as a transitive dependency which is higher than the version in PowerShell `4.0.*`

Graph
`Azure.Monitor.OpenTelemetry.Exporter` &#8594; `OpenTelemetry : 1.1.0` &#8594; `OpenTelemetry.Api : 1.1.0` &#8594; `System.Diagnostics.DiagnosticSource >= 5.0.1`

https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1237993&view=logs&j=d41e9505-d81b-5b3c-5b50-be71bc9b0ccb&t=1d797300-f2df-5c9f-af88-b93a037bfad7

### Expected behavior

SDKs should not have dependencies higher than those in powershell.

### Actual behavior

`Azure.Monitor.OpenTelemetry.Exporter` pull in a dependency with version higher than present in powershell.

### Reproduction Steps

Run `net - agregate-report` pipeline after removing `Azure.Monitor.OpenTelemetry.Exporter` from the ignoreList in `https://github.com/Azure/azure-sdk-for-net/blob/main/eng/scripts/dependencies/generate-deps.ps1`

**Comment by cijothomas** [comment] 2022-09-09 13:40
> SDKs should not have dependencies higher than those in powershell.

What is the reason for this?

**Comment by reyang** [comment] 2023-02-21 18:30
Closing as by design.

@chidozieononiwu feel free to reopen if you think the decision is wrong with an explanation why you believe "SDKs should not have dependencies higher than those in powershell".

**Closed by reyang** 2023-02-21 18:30 UTC
Labels: Monitor, Client, Monitor - Exporter
