### ISSUE TITLE
Key Vault support for .NET RSA Crypto primitives

### ISSUE THREAD

**Issue by clairernovotny** [Azure/azure-sdk-for-net#3545] opened 2017-08-03 16:33 UTC
Many applications in .NET need an `RSA` derived object for their crypto functions. Today, there is no built-in way of doing this with keys/certificates stored in Key Vault. I have written an implementation for this, but I believe it belongs in this SDK. 

Key Vault does have its own crypto abstractions, but that does not address the need to use Key Vault in places that are not "key vault crypto" aware. 

I'm happy to discuss API names, shapes, parameters, but I have this working already here:
https://github.com/novotnyllc/RSAKeyVaultProvider

The `RSAKeyVault` enables you to use secrets and certificates stored in an 
Azure Key Vault for performing signing and decryption operations. (Encrypt and verify
can be done locally with the public key material.) The type derives from `RSA` so can
be used anywhere an `AsymmetricAlgorithm` can be, including with `SignedXml` types.

I would like to contribute this as a PR into the Key Vault SDK but wanted to start a discussion here before sending a PR.

**Comment by onovotny** [comment] 2017-08-14 13:36
Ping?

**Comment by PinpointTownes** [comment] 2017-08-16 19:40
Definitely something that would be worth having in the Azure SDK :+1:

**Comment by herveyw** [comment] 2017-08-23 22:31
@onovotny Hi Oren, we understand what you need but I think we'd implement this differently than you have. For example, most likely I'd modify the KeyVaultKeyResolver and KeyVaultKey from the AKV Extensions package to return a key that subclasses RSA (and also implements IKey). With this model, we could allow for Secrets that contain either public/private certificate or for direct references to Keys. So, basically:

IKey key = keyResolver.ResolveKeyAsync( keyIdentifier );
RSA rsa  = key as RSA;

We are making some changes to the SDK at the moment and may be able to combine this work. I don't think we'd accept your code as-is because we already have the KeyResolver model.

**Comment by onovotny** [comment] 2017-08-23 22:37
Thanks. Is the work to do this the way you're suggesting something you'd do or is it something I can help with? At the end of the day, however the RSA impl gets done, long as it gets done, is all that counts. 

What I have is just one way it could work.

**Comment by herveyw** [comment] 2017-08-24 19:55
We have some work going on in the SDK at present that this work should either merge with or build on top of. No ETA at present as we are resolving some compatibility issues.

**Comment by heaths** [comment] 2019-09-24 18:41
This should now be implemented with PR #7662 which builds on #7176. Please feel free to reopen if not along with what you feel is missing.

**Comment by onovotny** [comment] 2019-09-24 18:52
@heaths I just looked at the PR/code and it's not clear to me how I'd get an `RSA`-derived object back from the client that I can pass into other API's?

**Comment by heaths** [comment] 2019-09-24 19:36
The private parameters are only necessary if you need the private key, e.g. signing, decrypting, and unwrapping (for RSA). If you just need a raw `RSA` object, you can use `KeyClient` to get one, though the private key wouldn't be returned. For that, there's the new `CryptographyClient` we're introducing in preview 4. Not only does it provide simple methods for signing and encrypting with an RSA private key on Key Vault, for all corresponding public-key operations it can do so locally: better for throughput and controlling costs. Sending every request to the KV could get expensive and will certainly affect performance.

Seems like what you're wanting, then, is a wrapper around `CryptographyClient` that extends `RSA`?

**Comment by onovotny** [comment] 2019-09-24 20:00
> Seems like what you're wanting, then, is a wrapper around CryptographyClient that extends RSA?

Yes, exactly.

**Comment by onovotny** [comment] 2019-09-24 20:04
@heaths that's also what I've already written https://github.com/onovotny/RSAKeyVaultProvider/tree/master/RSAKeyVaultProvider -- with the added support for providing the public certificate and carrying that around efficiently. I think that kind of thing would be best provided by the SDK instead of a 3rd party library like mine.

**Comment by heaths** [comment] 2019-09-24 20:05
Reopening. Apologies for the misunderstanding. I think what would make sense for both performance and cost-savings is to provide a wrapper around `CryptographyClient` that extends `AsymmetricAlgorithm` or `SymmetricAlgorithm` since we support RSA, EC, and - soon - AES.

**Comment by heaths** [comment] 2022-12-24 18:37
@clairernovotny what was the point of taking, as input, either the JWK or a X509 certificate when all that should be in KV already? I'm working on this over the holiday (now that another woodworking project is wrapping up) and want to make sure requirement are met based on your existing code from which you ported.

The `CryptographyClient` will attempt to download the key. It won't be able to download the private key by design*, but as long as the caller has "get" permissions on the key it can perform any public key operations locally; if not - or if requiring the private key - the operations are done remotely.

\* It's actually stored as a secret and one can download a full certificate with `CertificateClient.DownloadCertificate`, but that's not a best practice and not something I'd want to enable in this workflow. Won't work with Managed HSM anyway.

**Comment by heaths** [comment] 2022-12-24 23:00
@clairernovotny does #33186 fit requirements (at least for RSA, but it's still a draft)?

**Closed** 2023-05-11 23:06 UTC
Labels: KeyVault, Client, feature-request
