### ISSUE TITLE
Microsoft.Azure.ConfigurationManager does not work with .NET Core

### ISSUE THREAD

**Issue by csharpfritz** [Azure/azure-sdk-for-net#6677] opened 2019-06-22 20:26 UTC
**Describe the bug**
Attempting to reference Microsoft.Azure.ConfigurationManager.nupkg from a .NET Core 2.1 / 2.2 project throws a fusion error, originally described in #4010 

***Exception or Stack Trace***
Package is restored into the project with this error:

Package 'Microsoft.Azure.ConfigurationManager 4.0.0' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.1'. This package may not be fully compatible with your project.

Compile yields the following error when attempted:
"Unable to load DLL 'fusion.dll' or one of its dependencies: The specified module could not be found. (Exception from HRESULT: 0x8007007E)"

**To Reproduce**
Add package to a new .NET Core 2.1 Azure Functions project and attempt to reference CloudConfigurationManager.GetSetting()

***Code Snippet***
Complete project available at:  https://github.com/csharpfritz/BrokenAzureFunctions

**Expected behavior**
Return the requested setting from Azure Configuration

**Comment by maririos** [comment] 2019-07-08 16:00
@kurtzeborn this isn't related to App Configuration service. 
I removed the tags and added the triage one back as couldn't find the project/owner of the referenced service in the repo.

**Comment by mitchdenny** [comment] 2019-07-10 17:36
Hey @csharpfritz I noticed that this was still sitting in triage. I had a quick look at our repo and I couldn't find the code for this - even though the package clearly points back to our repo for this. Anyway - it turns out it was developed on a branch that appears not have been merged in.

Here it is:

https://github.com/Azure/azure-sdk-for-net/tree/AzureConfigMgr/src/SdkCommon/ConfigManager/ConfigMgr

I'm looping in @shahabhijeet since he looks like the person who committed the code on this branch and might have some insights into whether this code is still being actively supported or should be considered depreciated. I've tagged this with the management plane label for now.

**Comment by csharpfritz** [comment] 2019-07-10 17:54
I don't understand the comments.

My sample project was built with the default templates that ship with Visual Studio and uses the documentation provided for working with configuration in Functions 2.0

**Comment by mitchdenny** [comment] 2019-07-12 20:25
@csharpfritz I understand what you are saying. I'm just trying to help find the owner of this code as an initial step so that they can decide what they want to do about supporting .NET Core.

**Comment by erich-wang** [comment] 2019-08-12 08:54
@shahabhijeet , do you know who is code owner for Microsoft.Azure.ConfigurationManager?

**Comment by erich-wang** [comment] 2019-09-04 08:45
source code is at https://github.com/Azure/azure-sdk-for-net/tree/AzureConfigMgr

**Comment by markcowl** [comment] 2019-09-29 08:38
@Tiberriver256 @csharpfritz What is your scenario for this?  AppConfiguration was designed to read from co nfiguration  for old RDFE Deployments, are you deploying a .NetCore app to a classic VM, or do you have some other scenario?

**Comment by mitchdenny** [comment] 2019-10-02 05:48
I'm closing this issue. The library doesn't look like what @csharpfritz wants to use given he is using an Azure Function and this is for for the classic compute model for Azure Cloud Services.

**Closed by mitchdenny** 2019-10-02 05:48 UTC
Labels: triage
