### ISSUE TITLE
The JsonConvert.Serialize/Deserialize uses the default JsonConvert settings in a few places within Azure Search

### ISSUE THREAD

**Issue by GuCoder** [Azure/azure-sdk-for-net#1438] opened 2015-09-16 17:53 UTC
Within Azure Search, the JsonConvert.SerializeObject/DeserializeObject method calls are not provided with JsonSerializerSettings, and use the default settings, that may have been modified by the user.

Because of this, when the user specifies the ContractResolver to be a CamelCasePropertyNamesContractResolver, internal deserialization of objects such as the IndexResult object (which has a field named 'key' and a property named 'Key') fail with the following exception:

Message: "A member with the name 'key' already exists on 'Microsoft.Azure.Search.Models.IndexResult'. Use the JsonPropertyAttribute to specify another name."       
       Exception: Newtonsoft.Json.JsonSerializationException
       StackTrace: "   at Microsoft.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
                                             at Microsoft.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccess(Task task)
            at Microsoft.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
            at Microsoft.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
            at Microsoft.Azure.Search.DocumentOperationsExtensions.Index[T](IDocumentOperations operations, IndexBatch`1 batch)
           ... work code follows.

The workaround is to set the JsonConvert.DefaultSettings to a method filling it in with empty JsonSerializerSettings, call the Azure Search APIs, and then restore your custom JsonConvert default settings.

**Comment by brjohnstmsft** [comment] 2015-09-16 18:16
Thanks for reporting this. We'll fix it in the next release.

**Comment by brjohnstmsft** [comment] 2015-09-24 02:32
@GuCoder I'm working on this now. There is only one call I can find that doesn't already take `JsonSerializerSettings`: the call to `JsonConvert.DeserializeObject()` on line 147 of `DocumentOperations.Index.Customizations.cs`. This explains exactly the behavior you described. Did you find any others that I'm missing?

**Comment by brjohnstmsft** [comment] 2015-09-24 02:59
Nevermind, I think the problem is deeper than not passing in `JsonSerializerSettings`. It looks like `JsonConvert` is merging default settings with whatever we pass in. It looks like the solution is to use `JsonSerializer` directly. I'll make that change.

**Comment by brjohnstmsft** [comment] 2015-09-25 20:29
The fix has been merged. I'll close this issue once we push a new version of the SDK to NuGet.

**Comment by brjohnstmsft** [comment] 2015-10-02 19:31
This has been fixed in the latest version of the Azure Search .NET SDK. You can find it on NuGet: http://www.nuget.org/packages/Microsoft.Azure.Search/0.13.0-preview

**Closed by brjohnstmsft** 2015-10-02 19:31 UTC
Labels: Search
