### ISSUE TITLE
[ApiManagement] Track 2 code issues

### ISSUE THREAD

**Issue by Yao725** [Azure/azure-sdk-for-net#30572] opened 2022-08-18 02:04 UTC
We have hit couple of the issues during the testing of ApiManagement track 2 mgmt plane code, below are the details:

1. Id of content type is not a resource identifier

    According to the [swagger definition](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/apimanagement/resource-manager/Microsoft.ApiManagement/stable/2021-08-01/definitions.json#L6467-L6481), content type inherits from Resource, which means its Id should be a resource identifier, but the actual backend service doesn't return a resource identifier.
![image](https://user-images.githubusercontent.com/65993944/185275566-f6cd4f42-4ad1-41d2-8d66-952564a2c89e.png)

2. The Uri of PortalSettingsContractData may return empty string

    In the deserialization, we only have the check about null, it means the empty string will pass the check. And when we use the value to instantiate Uri, we will get exception

**Comment by HarveyLink** [comment] 2022-08-18 03:31
### `Invalid resource type` Error while operating `GatewayAPI` and `GroupUser`
## Error Message
Invalid resource type Microsoft.ApiManagement/service/groups/users expected Microsoft.ApiManagement/service/users (Parameter 'id')
Invalid resource type Microsoft.ApiManagement/service/gateways/apis expected Microsoft.ApiManagement/service/apis (Parameter 'id')
## Root cause 
In swagger, those two paths share same response resource:
[/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.ApiManagement/service/{serviceName}/users/{userId}](https://github.com/Azure/azure-rest-api-specs/blob/20b212e1ef41b1d49b83ba82b4cd2d3330e44742/specification/apimanagement/resource-manager/Microsoft.ApiManagement/stable/2021-08-01/apimusers.json#L198)
[/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.ApiManagement/service/{serviceName}/groups/{groupId}/users/{userId}](https://github.com/Azure/azure-rest-api-specs/blob/20b212e1ef41b1d49b83ba82b4cd2d3330e44742/specification/apimanagement/resource-manager/Microsoft.ApiManagement/stable/2021-08-01/apimgroups.json#L488)
 -- ./definitions.json#/definitions/UserContract
[/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.ApiManagement/service/{serviceName}/apis/{apiId}](https://github.com/Azure/azure-rest-api-specs/blob/20b212e1ef41b1d49b83ba82b4cd2d3330e44742/specification/apimanagement/resource-manager/Microsoft.ApiManagement/stable/2021-08-01/apimapis.json#L215)
[/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.ApiManagement/service/{serviceName}/gateways/{gatewayId}/apis/{apiId}](https://github.com/Azure/azure-rest-api-specs/blob/20b212e1ef41b1d49b83ba82b4cd2d3330e44742/specification/apimanagement/resource-manager/Microsoft.ApiManagement/stable/2021-08-01/apimgateways.json#L926)
 -- ./definitions.json#/definitions/ApiContract
**Issue Scenario:**
Create a resource **api/user** under ApiService, then assign it to a **gateway/group**, the resource self not changed but the response id changed, lead us to the `ValidateResourceId` method error

**Closed** 2022-09-01 14:09 UTC
Labels: API Management, Mgmt
