### ISSUE TITLE
[BUG] AzureServiceTokenProvider.GetAccessTokenAsync doesn't respect tenantId when provider is AzureCliAccessTokenProvider

### ISSUE THREAD

**Issue by chpspiir** [Azure/azure-sdk-for-net#6377] opened 2019-05-22 12:47 UTC
**Describe the bug**
I am unable to use AzureCliAccessTokenProvider to generate an access token for another tenant than the CLIs default (when running locally).

**To Reproduce**
1. Use az CLI to log into an account with several tenants available (tenant1, tenant2)
1. Set the default account to be a subscription in tenant1 with the command `az account set --subscription "subscription-in-tenant1"`
1. Try to obtain a token for tenant2 in code with this snippet (as taken from here: https://docs.microsoft.com/en-us/azure/key-vault/service-to-service-authentication#using-the-library)
    ```
    let getOAuthTokenFromEnvironment tenantId =
    let azureServiceTokenProvider = AzureServiceTokenProvider()
    let token = 
        azureServiceTokenProvider.GetAccessTokenAsync("https://management.azure.com/", tenantId) |> Async.AwaitTask |> Async.RunSynchronously
    token
    ```
1. Try to access a resource in tenant2.
1. Request fails with 401 telling that the token is not valid for tenant2:
```
The access token is from the wrong issuer 'https://sts.windows.net/<tenant1>/'. 
It must match the tenant 'https://sts.windows.net/<tenant2>/' associated with this subscription. Please use the authority (URL) 'https://login.windows.net/<tenant2>' to get the token. Note, if the subscription is transferred to another tenant there is no impact to the services, but information about new tenant could take time to propagate (up to an hour). If you just transferred your subscription and see this error message, please try back later."
```
***Code Snippet***
AzureServiceTokenProvider.GetAccessTokenAsync does not respect tenantId as is evident here: https://github.com/Azure/azure-sdk-for-net/blob/9d33bd917df2f249125dddcf3cba72c106e38cc0/src/SdkCommon/AppAuthentication/Azure.Services.AppAuthentication/TokenProviders/AzureCliAccessTokenProvider.cs#L25.

AzureCliAccessTokenProvider executes a shell command to make the CLI generate an access token. The command being run does not take tenantId as a parameter. AzureCliAccessTokenProvider is thus unable to generate tokens for other tenants than the default.

**Expected behavior**
I expected AzureServiceTokenProvider.GetAccessTokenAsync to always respect tenantId.

**Setup (please complete the following information):**
 - Microsoft.Azure.Services.AppAuthentication=1.2.0-preview3

**Additional context**
My use case is that I want to write code locally that can be deployed without changing logic in terms of how access tokens are obtained.

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by kurtzeborn** [comment] 2019-05-24 18:16
Thank you for opening this issue! We are routing it to the appropriate team for follow up.

CC: @shahabhijeet

**Comment by nonik0** [comment] 2019-08-14 22:24
Hi @chpspiir, unfortunately your scenario isn't currently possible. AppAuth relies on the below Azure CLI command to get an access token, however currently there is no option to specify the tenant ID when requesting an access token, but only the subscription:

```
>az account get-access-token -h
...
Arguments
    --resource       : Azure resource endpoints. Default to Azure Resource Manager Use 'az cloud
                       show' command for other Azure resources.
    --subscription -s: Name or ID of subscription.
...
```


If Azure CLI supports specifying the tenant ID when requested an access token in the future, we can update the library to be able to honor the tenant ID specified in the call.

**Comment by varunsh-msft** [comment] 2019-10-07 16:59
Closing as by design

**Closed by varunsh-msft** 2019-10-07 16:59 UTC
Labels: AppAuthentication, Authorization, Mgmt, customer-reported
