### ISSUE TITLE
[BUG][Storage] SetMetadataAsync fails when blob name contains a space character

### ISSUE THREAD

**Issue by kinelski** [Azure/azure-sdk-for-net#7659] opened 2019-09-17 21:35 UTC
**Describe the bug**
`UploadAsync` works properly when there's a space character in the blob name. However, `SetMetadataAsync` throws an exception with a `BlobNotFound` error code.

***Exception***
```
Azure.Storage.StorageRequestFailedException
  HResult=0x80131500
  Message=The specified blob does not exist.
RequestId:fab4e043-601e-0034-729e-6d9909000000
Time:2019-09-17T21:22:29.7182221Z
Status: 404 (The specified blob does not exist.)

ErrorCode: BlobNotFound
```

***Stack Trace***
```
   at Azure.Storage.Blobs.BlobRestClient.Blob.SetMetadataAsync_CreateResponse(Response response)
   at Azure.Storage.Blobs.BlobRestClient.Blob.<SetMetadataAsync>d__24.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azure.Storage.Blobs.Specialized.BlobBaseClient.<SetMetadataInternal>d__60.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azure.Storage.Blobs.Specialized.BlobBaseClient.<SetMetadataAsync>d__59.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Azure.Messaging.EventHubs.CheckpointStore.Blob.Samples.Sample01_HelloWorld.<RunAsync>d__8.MoveNext() in C:\Users\camaiaor\Documents\Repos\azure-sdk-for-net\sdk\eventhub\Azure.Messaging.EventHubs.CheckpointStore.Blob\samples\Sample01_HelloWorld.cs:line 60
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azure.Messaging.EventHubs.CheckpointStore.Blob.Samples.Program.<Main>d__2.MoveNext() in C:\Users\camaiaor\Documents\Repos\azure-sdk-for-net\sdk\eventhub\Azure.Messaging.EventHubs.CheckpointStore.Blob\samples\Program.cs:line 39
```

***Code Snippet***
The following code snippet is enough to make the exception happen:

```
var blob = new BlobClient(StorageAccountConnectionString, ContainerName, "blank space");
var stream = new MemoryStream(Encoding.UTF8.GetBytes("body"));

await blob.UploadAsync(stream);

await blob.SetMetadataAsync(new Dictionary<string, string>());
```

`UploadAsync` doesn't throw and the blob with name `blank space` is uploaded to Azure with no issues. However, `SetMetadataAsync` fails.

The code works if `"blank space"` is changed to `"blank_space"`.

**Comment by amnguye** [comment] 2019-10-08 23:35
This issue will happen when you have a space in the blob name but also send a request that adds a query to the URI.

For example if you're creating a blob, it will convert a space into a '%20' which is expected.
`http://storageaccount.blob.core.windows.net/test-container-name/blob%20name `

If your method requires an added query to it, say for example creating a lease on a blob, it seems that it will re-encode the uri. Same for SetMetadata method and CreateSubDirectory as well. So any method that requires adding a query to the Uri is affected
'http://storageaccount.blob.core.windows.net/test-container-name/blob%2520name?comp=lease'
'http://storageaccount.file.core.windows.net/test-share-lname/test-directory-name/sub%2520dir%2520name?restype=directory'
'http://storageaccount.blob.core.windows.net/test-container-name/blob%2520name?comp=metadata'

Here's the method that appends the query to the uri (AppendQuery from RequestUriBuilder class in Azure.Core.Http.Pipeline). This is called by methods in the BlobRestClient.cs
![image](https://user-images.githubusercontent.com/48961492/66440684-c2b77c00-e9e8-11e9-8df1-1b16dd63bbb6.png)

Here's the SetMedata Test ran to reproduce this issue
`        public async Task SetMetadataAsync_Space()
        {
            using (GetNewContainer(out BlobContainerClient container))
            {
                // Arrange
                BlobBaseClient blob = await GetNewBlobClient(container, "blob name");
                IDictionary<string, string> metadata = BuildMetadata();

                // Act
                try
                {
                    await blob.SetMetadataAsync(metadata);
                }
                catch
                {
                    Console.WriteLine("error");
                }
                // Assert
                Response<BlobProperties> response = await blob.GetPropertiesAsync();
                AssertMetadataEquality(metadata, response.Value.Metadata);
            }
        }`

@tg-msft Could you help us take a look at this, because this seems to be in the Core libraries and we don't know much about what's going on here and why Uris are getting encoded twice.

#7720 is a duplicate of this item as well.

**Comment by tg-msft** [comment] 2019-10-14 23:18
I think #8090 will allow us to fix this once it's merged.

**Closed** 2019-10-15 17:12 UTC
Labels: Bug, Client, Storage, blocking-release
