### ISSUE TITLE
[BUG] Sometimes, after a message sent by service bus client is throttled, all messages are delayed by 10 seconds for an unlimited duration

### ISSUE THREAD

**Issue by FranceyD** [Azure/azure-sdk-for-net#42952] opened 2024-03-25 14:51 UTC
### Library name and version

Azure.Messaging.ServiceBus 7.16.2

### Describe the bug

Sometimes, after a message sent by ServiceBusSender is throttled, the sleep time in case of busy server (10 seconds by default) will be applied to all messages sent with the same ServiceBusSender without time limit, instead of removing the sleep time after the sleep time delay.

I think the problem cause is in the Azure.Messaging.ServiceBus.ServiceBusRetryPolicy class. If the CancellationTaken passed to ServiceSender.SendMessage is cancelled when Task.Delay is waiting for the end of sleep time in ScheduleResetServerBusy, the method ResetServerBusy() will never be called. So, _serverBusyState will be busy forever.

The problem will probably affect all other classes using ServiceBusRetryPolicy.

### Expected behavior

When a service bus message is throttled, the ServerBusyState should only be applied for ServerBusyBaseSleepTime in ServiceBusRetryPolicy.

### Actual behavior

When a service bus message is throttled and the cancellation token of the throttled message is cancelled, the ServerBusyState is applied forever.

### Reproduction Steps

This code should reproduce the problem if it is possible to have a Service Bus server replying with a server busy error for the first message and a success for the following messages:
```
	var connectionString = "";
	var queueName = "queueName";
	
	var	message = new ServiceBusMessage(string.Empty);
	
	// Creates a cancellation token source to cancel tokens after 500ms
	var cts = new CancellationTokenSource(500);
	
	var serviceBusClient = new ServiceBusClient(connectionString);
	var sender = serviceBusClient.CreateSender(queueName);

	try
	{
		// Send a message which should throw a ServiceBusException with Reason ServiceBusFailureReason.ServiceBusy
		await sender.SendMessageAsync(message, cts.Token);
	}
	catch (Exception ex)
	{
	}

	// wait 15 seconds to be sure the servce busy sleep time of 10 seconds is elapsed
	await Task.Delay(15_000);
	
	var stopWatch = Stopwatch.StartNew();

	 // Send a 2nd message which should succeed
	await sender.SendMessageAsync(message, CancellationToken.None);

	// The time to send the 2nd message is longer than 10 seconds because the sender still consider the server as busy:
	Console.WriteLine(stopWatch.Elapsed);
```

### Environment

Azure AppService Windows x64, .Net 6

**Comment by jsquire** [comment] 2024-03-25 19:17
Hi @FranceyD.  Thanks for reaching out and we regret that you're experiencing difficulties.  Thank you for your analysis; looking over the retry policy implementation, we agree that this scenario was overlooked and is a not the intended behavior.  We'll get this patched up.

**Comment by jsquire** [comment] 2024-03-26 20:33
The fix for this has been merged in and will be available in our April release.

**Closed** 2024-04-02 22:33 UTC
Labels: Service Bus, Client, customer-reported, bug, issue-addressed
