### ISSUE TITLE
[BUG] "ManagedIdentityCredential authentication failed: '<' on local debug

### ISSUE THREAD

**Issue by fonbrauzen** [Azure/azure-sdk-for-net#25483] opened 2021-11-23 09:59 UTC
**Describe the bug**
In Visual Studio without environment variables it fails to authenticate me under correct credentials, unless I set new VisualStudioCredential() (therefore [skipping 2 environment and managed](https://raw.githubusercontent.com/Azure/azure-sdk-for-net/main/sdk/identity/Azure.Identity/images/DefaultAzureCredentialAuthenticationFlow.png)). From my knowledge I don't have anywhere set environment variables, so I have no idea on parsing what value it failing...

**Expected behavior**
Use correct credentials from Visual Studio

**Actual behavior (include Exception or Stack Trace)**
Exception:
"ManagedIdentityCredential authentication failed: '<' is an invalid start of a value. LineNumber: 0 | BytePositionInLine: 0.
See the troubleshooting guide for more information. https://aka.ms/azsdk/net/identity/managedidentitycredential/troubleshoot"

**To Reproduce**
Steps to reproduce the behavior (include a code snippet, screenshot, or any additional information that might help us reproduce the issue)

1. Use Account A for VS license
2. Use account B for Azure debug connection (selected from Options)
```C#
public KeyVaultSecretsService()
{
    var keyVaultURL = ConfigurationManager.AppSettings["YourAppSettingsKey"];
    this.client = new SecretClient(new Uri(keyVaultURL), new DefaultAzureCredential() // new VisualStudioCredential() - for replacement during local tests
         );
}
public string GetSecretByName(string secretName)
{
    var secret = this.client.GetSecret(secretName);

    return secret.Value.Value;
} 
```
3. no environment variables try to retrieve secret

**Environment:**
 - Name and version of the Library package used: Azure.Identity 1.5.0, Azure.Security.KeyVault.Secrets 4.2.0
 - Hosting platform or OS and .NET runtime version Win 10 :NET framework 4.7.2
 - IDE and version : Visual Studio 16.11.7

**Comment by jsquire** [comment] 2021-11-23 13:37
Thank you for your feedback.  Tagging and routing to the team members best able to assist.

**Comment by christothes** [comment] 2021-12-06 15:04
The json parsing error sounds like a dupe of https://github.com/Azure/azure-sdk-for-net/issues/24158. 

The reason this error is occurring locally is because there is something on your local network that is responding on the same non-routeable IP address that Managed Identity is expected to listen on. 

https://github.com/Azure/azure-sdk-for-net/blob/40daa335d466fb5284552ca10e6f7854e5e80cf2/sdk/identity/Azure.Identity/src/ImdsManagedIdentitySource.cs#L17-L18

**Comment by fonbrauzen** [comment] 2021-12-06 17:05
@christothes  Is it planned in case of the invalid response move to the next auth method? 
Or it is already there, just not working due to #24158 ?

**Comment by christothes** [comment] 2021-12-06 17:07
If there is a service listening on the IMDS endpoint, the credential chain will stop there because the assumption is that this endpoint will only respond in an Azure environment.

**Comment by fonbrauzen** [comment] 2021-12-06 18:47
hmm, this happens in the Amazon workspace VM of our clients, so here I'm not sure if this Amazon or some network settings of our client... anyway something returns same  404 (as directly from the internet) but also with the HTML body:
```HTML
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
		 "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
 <head>
  <title>404 - Not Found</title>
 </head>
 <body>
  <h1>404 - Not Found</h1>
 </body>
</html>
```
then we have this error, probably because the client try to parse the response body despite 404.
During the test outside this VM, where no body returned on 404 this doesn't happen and this works as expected.

@christothes is it possible to ignore the body if it's 404?

**Comment by christothes** [comment] 2021-12-06 18:55
>  During the test outside this VM, where no body returned on 404 this doesn't happen and this works as expected.
> 
> @christothes is it possible to ignore the body if it's 404?

Do you happen to know if the client is actually getting a 404 response, or if that is some kind of proxy returning a 404 content response? Could you reproduce it with logging enabled on the Credential to see how the endpoint is responding? 

https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/identity/Azure.Identity/README.md#logging

**Comment by fonbrauzen** [comment] 2021-12-06 20:08
The server which responding with 404 seems to belong to AWS infrastructure- EC2ws, with enabled diagnostic logging the picture is the same, 5 404 responses then this error in the code on getting the secret.

**Comment by christothes** [comment] 2021-12-06 20:22
Since this is running in AWS and you never want ManagedIdentity, would it make sense to just disable that with the `ExcludeManagedIdentityCredential` option property? This will make things faster also, since the client doesn't need to probe the endpoint on initialization. 

https://github.com/Azure/azure-sdk-for-net/blob/53f08c606b2e5d0540781f1d44bb0e8189563326/sdk/identity/Azure.Identity/src/DefaultAzureCredentialOptions.cs#L74

**Comment by fonbrauzen** [comment] 2021-12-06 20:49
well, no, the target is actually Azure, so this will be needed at the end, this bug just complicates the local debug from VM which runs in AWS because I have to do changes for the debug. I checked #24158 one more time, and if response parse will happen after a check on 200 my problem wouldn't exist, so yes this is definitely duplication.

**Comment by christothes** [comment] 2021-12-06 21:20
One possible workaround is to set the `IMDS_ENDPOINT` environment variable to some other non-routeable endpoint address where there is nothing listening. That will allow the IMDS endpoint check to fail as expected.

**Comment by fonbrauzen** [comment] 2021-12-09 17:10
Thx, I tried to set in the project settings => Debug => Environment Variables to [127.0.0.1](http://127.0.0.1/metadata/identity/oauth2/token), where definitely will be no body, unfortunately this didn't help.

**Comment by christothes** [comment] 2021-12-09 17:13
> Thx, I tried to set in the project settings => Debug => Environment Variables to [127.0.0.1](http://127.0.0.1/metadata/identity/oauth2/token), where definitely will be no body, unfortunately this didn't help.

Isn't that the one IP that is guaranteed to get a response from the current machine? 😄

**Comment by fonbrauzen** [comment] 2021-12-09 17:32
yes, but the idea was, that the rest of IPs could go via DNS => receive 404 with the body, and 127.0.0.1 return just nothing, because there is no HTTP server running locally, but the result is the same. Seems this setting somehow didn't apply, am I missing something?

**Comment by christothes** [comment] 2021-12-09 18:13
Could you provide the exception, stack, and relevant logging you get with the 127.0.0.1 host?

**Comment by fonbrauzen** [comment] 2021-12-09 18:49
The exception is exactly the same as above in the bug description, I assume that env variable just didn't apply somehow

**Comment by christothes** [comment] 2021-12-09 18:51
> The exception is exactly the same as above in the bug description, I assume that env variable just didn't apply somehow

The logging would confirm - would you mind providing the logging output relevant to the credential discovery?

**Comment by fonbrauzen** [comment] 2022-02-04 11:36
sorry for the long response, long story short - I didn't understand how to make this logging work.  I would just wait for https://github.com/Azure/azure-sdk-for-net/issues/24158 to be solved.

**Comment by christothes** [comment] 2022-02-04 20:09
Assuming you wanted to log output to the console, it should look like this:
```C#
public KeyVaultSecretsService()
{
    using AzureEventSourceListener listener = AzureEventSourceListener.CreateConsoleLogger();
    DefaultAzureCredentialOptions options = new DefaultAzureCredentialOptions()
    {
        Diagnostics =
        {
            LoggedHeaderNames = { "x-ms-request-id" },
            LoggedQueryParameters = { "api-version" },
            IsLoggingContentEnabled = true
        }
    };
    var keyVaultURL = ConfigurationManager.AppSettings["YourAppSettingsKey"];
    // Note: use of options here
    this.client = new SecretClient(new Uri(keyVaultURL), new DefaultAzureCredential(options) // new VisualStudioCredential() - for replacement during local tests
         );
}
public string GetSecretByName(string secretName)
{
    var secret = this.client.GetSecret(secretName);

    return secret.Value.Value;
} 
```

**Closed** 2022-02-26 08:02 UTC
Labels: Client, needs-author-feedback, Azure.Identity, customer-reported, question, no-recent-activity
