### ISSUE TITLE
[BUG] loganalytics Internal Server Error for additional workspaces

### ISSUE THREAD

**Issue by pakrym** [Azure/azure-sdk-for-net#21656] opened 2021-06-07 17:12 UTC
```
POST https://api.loganalytics.io/v1/workspaces/e7bf7412-576d-4978-b47c-2edf669e3e2a/query HTTP/1.1
Accept: application/json
Content-Type: application/json
x-ms-client-request-id: ad92868f-cc08-4309-9f5e-0afd7519230a
x-ms-return-client-request-id: true
User-Agent: azsdk-net-Monitor.Query/1.0.0-alpha.20210607.1 (.NET Framework 4.8.4300.0; Microsoft Windows 10.0.19043 )
Authorization: Bearer xxx
traceparent: 00-e59bd1f167e6b0478e4bef24c6708c4b-e630e3899153794f-00
Host: api.loganalytics.io
Content-Length: 181
Expect: 100-continue

{"query":"TableA1_151_CL | project StringColumn_s | order by StringColumn_s asc","timespan":"2021-05-31T00:00:00.0000000Z/P7D","workspaces":["4f6289fe-fa1f-4e57-86ee-42a1a09a5856"]}
HTTP/1.1 500 Internal Server Error
Date: Mon, 07 Jun 2021 15:49:28 GMT
Content-Type: application/json; charset=utf-8
Content-Length: 289
Connection: keep-alive
Strict-Transport-Security: max-age=15724800; includeSubDomains
via: 1.1 draft-oms-76875b9d69-6xzmj
X-Content-Type-Options: nosniff
Access-Control-Allow-Origin: *
Access-Control-Expose-Headers: Retry-After,Age,WWW-Authenticate,x-resource-identities,x-ms-status-location
Vary: Accept-Encoding

{"error":{"message":"Unexpected error occurred","code":"InternalServerFault","correlationId":"3e6992be-bf1c-40ba-91ae-d11dd4172fdb","innererror":{"code":"InternalServerFault","message":"Something went wrong while running the query","correlationId":"3e6992be-bf1c-40ba-91ae-d11dd4172fdb"}}}
```

**Comment by AlexandreArpin** [comment] 2021-06-08 14:42
@pakrym  sorry for the poke, since sunday, we have been getting the same type of errors from the Container Instances Api "List Logs"

https://docs.microsoft.com/en-us/rest/api/container-instances/containers/list-logs

```
{"error":{"code":"InternalServerError","message":"Encountered an internal server error. The tracking activity id is 'a8ff98cd-d051-40fd-bf58-07b30773e3d2', correlation id is 'b543a2a1-f2e0-4164-be29-48942f24508d'."}}
```

Could this be related? We are about to open a ticket with Azure Support

**Comment by pakrym** [comment] 2021-06-08 15:16
@AlexandreArpin my first guess would be no. The error format and the code name are standard in azure and the service and the message are different in you case.

**Comment by srnagar** [comment] 2021-06-21 23:05
Ido Schreier from the Azure Monitor team confirmed that this was a transient error from the service and shouldn't happen again. We should be able to close this issue if it's no longer reproducible - @pakrym

**Closed** 2021-06-21 23:08 UTC
Labels: Client, Monitor - LogAnalytics, bug
