### ISSUE TITLE
[BUG] Error when CORS is set with multiple methods in the storage account

### ISSUE THREAD

**Issue by Rapol** [Azure/azure-sdk-for-net#12287] opened 2020-05-26 14:39 UTC
This is a duplicate of https://github.com/Azure/azure-storage-net/issues/916. Decided to open a new issue since that repo was abandoned

**Describe the bug**

The storage sdk cannot handle a CORS policy with a rule that has multiple methods. To make this work we would need to create one rule for each method that we want CORS to be enabled

**Expected behavior**
SDK should allow a CORS policy with a rule of comma delimited methods.
ie. Access-Control-Allow-Methods: POST, GET, OPTIONS

**Actual behavior (include Exception or Stack Trace)**
When setting up a function app with a blob trigger, the function host return the following error

```
Microsoft.WindowsAzure.Storage.StorageException : Requested value 'DELETE,GET,POST,PUT,MERGE,HEAD,OPTIONS,PATCH' was not found. ---> System.ArgumentException : Requested value 'DELETE,GET,POST,PUT,MERGE,HEAD,OPTIONS,PATCH' was not found.
   at System.Enum.TryParseEnum(Type enumType,String value,Boolean ignoreCase,EnumResult& parseResult)
   at System.Enum.Parse(Type enumType,String value,Boolean ignoreCase)
   at Microsoft.WindowsAzure.Storage.Shared.Protocol.ServiceProperties.<>c.<ReadCorsPropertiesFromXml>b__67_0(XElement rule)
   at System.Linq.Enumerable.SelectEnumerableIterator`2.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
```

**To Reproduce**

1. Create a storage account and set the following CORS policy
<img width="546" alt="image" src="https://user-images.githubusercontent.com/4079507/82913810-c0387100-9f3c-11ea-98d3-d783a0c2b03b.png">
2. Create a function app with a blob trigger pointing to this storage account
3. Function will never trigger because of the storage sdk error. Should be able to find function host error under kudu

**Environment:**
 - Windows Function App
 - Node 10.14.1

**Comment by amnguye** [comment] 2020-05-27 22:12
Hi,

Could you provide an example how you are trying to set multiple CORS policies from the SDK? I can acknowledge that the Windows Function App you are using is using an older version of our SDK (v11 or below), however I would like to better help you by understanding your needs. If you can provide a reproducable code snippet of what you are trying to achieve and what you are expecting that would help.

**Comment by Rapol** [comment] 2020-05-27 22:24
The function app is set up with a blob trigger to a storage account. We enable CORS in that storage account for other reasons unrelated to the function app. Once we enabled CORS, the function app stopped working out of nowhere. After looking in the Kudu logs, we found the problem to be the underlying function host failing to connect the storage account because the SDK doesnt expect a CORS headers with multiple HTTP methods.

I have not tested the sdk in a standalone environment so I do not have a reproducible code snippet. But if you follow the steps in the To Reproduce section you should be able to see the error.

Also the error has been documented in here since last year with a fix in a PR https://github.com/Azure/azure-storage-net/issues/916

**Comment by amnguye** [comment] 2020-05-27 23:09
Hi,

Hm. Looks like this got slightly mislabeled, since this is specific to the Storage Management SDK. Let me relabel this and see if someone from that team can better help you. The Storage Client library does not manage the CORS policies.

**Comment by verbedr** [comment] 2020-06-06 09:56
This problem existed in v11 of the library and was solved with a PR request from me but totaly ignored.  https://github.com/Azure/azure-storage-net/pull/917

**Comment by philipp-bananaware** [comment] 2020-07-18 22:55
It happend to me today. Any solution`?

**Comment by attrib75** [comment] 2020-08-14 21:47
I think I'm getting this too

**Comment by amishra-dev** [comment] 2020-09-09 05:57
@blueww @vinjiang can you please look

**Comment by blueww** [comment] 2020-09-10 03:36
@amnguye 
I am a little confused, for "this is specific to the Storage Management SDK", which SDK do you mean?
If you mean [Microsoft.Azure.Management.Storage](https://www.nuget.org/packages/Microsoft.Azure.Management.Storage/)? If so, we do have [test case to cover set cors with multiple AllowedMethods](https://github.com/Azure/azure-sdk-for-net/blob/14de71c855113afd938dd3faf033397bff4ac1ee/sdk/storage/Microsoft.Azure.Management.Storage/tests/Tests/BlobServiceTests.cs#L852)

**Comment by amnguye** [comment] 2020-09-10 06:44
@blueww yes I think the customer is referring to the `Microsoft.Azure.Managment.Storage` package.

Could you help the customer resolve their issue? Even though there's a test, the customer has a scenario where they can't set it. After following their steps to reproduce their issue, could you put your findings here (or if you were not able to reproduce it that is also acceptable, that way the customer could provide us more details on how to better reproduce their issue).

Thanks

**Comment by blueww** [comment] 2020-09-10 09:05
@verbedr, @amnguye 
Please point out which code or information point to the `Microsoft.Azure.Managment.Storage`?
From the original message of this issue, the exception type is "Microsoft.WindowsAzure.Storage.StorageException", which should be from dataplane SDK, but not `Microsoft.Azure.Managment.Storage`.

@Rapol
Would you please help to clarify which steps reported the error?
It would better if you could share the code that repro the error (hide credential), or the SDK name that repro the error.

If you mean  `Microsoft.Azure.Managment.Storage` SDK, you can reference [this line](https://github.com/Azure/azure-sdk-for-net/blob/14de71c855113afd938dd3faf033397bff4ac1ee/sdk/storage/Microsoft.Azure.Management.Storage/tests/Tests/BlobServiceTests.cs#L852) for how to set multiple AllowMethods. This SDK code is auto generated from swagger, we are not allowed to manually change it, it can only be updated by change server/swagger behavior.

**Comment by Rapol** [comment] 2020-09-10 14:40
I don't have a code to reproduce since we got this error on the underlying function app host. It may be that the function app environment is running an old version of the storage sdk which doesnt have the fix.

Steps to reproduce:
- Create a node function app with a blob trigger
- Change the CORS policy of the blob container to have a CORS rule with multiple methods
- The function app will no longer trigger
- Going to the function app host logs (kudu) shows the following error:

```
Microsoft.WindowsAzure.Storage.StorageException : Requested value 'DELETE,GET,POST,PUT,MERGE,HEAD,OPTIONS,PATCH' was not found. ---> System.ArgumentException : Requested value 'DELETE,GET,POST,PUT,MERGE,HEAD,OPTIONS,PATCH' was not found.
   at System.Enum.TryParseEnum(Type enumType,String value,Boolean ignoreCase,EnumResult& parseResult)
   at System.Enum.Parse(Type enumType,String value,Boolean ignoreCase)
   at Microsoft.WindowsAzure.Storage.Shared.Protocol.ServiceProperties.<>c.<ReadCorsPropertiesFromXml>b__67_0(XElement rule)
   at System.Linq.Enumerable.SelectEnumerableIterator`2.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
```

Environment:
    Windows Function App
    Node 10.14.1

We have not tried this since we opened the issue so I can't guarantee this is still valid.

**Comment by verbedr** [comment] 2020-09-10 15:44
@blueww see my original message https://github.com/Azure/azure-sdk-for-net/issues/12287#issuecomment-640025892

But the code appears to be moved and you can now find it at https://github.com/Azure/azure-sdk-for-net/blob/f775e1f8b8d33904015800c4d0894115a6d22515/sdk/storage/Azure.ResourceManager.Storage/src/Generated/Models/CorsRules.Serialization.cs#L40. 

As it has been changed since the bug was reported. I can not confirm that you will have the same error as reported. The https://github.com/Azure/azure-sdk-for-net/blob/5dab3a1cca12c705811db62e222974af9b8d8aab/sdk/testcommon/Azure.Management.Storage.2019_06/src/Generated/Models/CorsRuleAllowedMethodsItem.cs#L20 expects a single HttpVerb while Azure can configure multiple verbs per rule. The value will then be a space separated list of the allowed verbs. 

My guess that no single verb will match the configuration any more in case of multiple verbs per rule. And this can cause other hidden issues (not known to me).

Also add Patch as a possible value

**Comment by blueww** [comment] 2020-09-11 03:22
@amnguye
From the exception from the customer, the exception is from dataplane SDK (looks like Track1 SDK) , so the issue with the customer should be still on dataplane SDK, not management plan. 
To resolve the issue of customer, we might still need to track it from dataplane.

@verbedr 
For the Cors rule in management plan .net SDK, I own the track1 SDL `Microsoft.Azure.Managment.Storage` , and Track2 SDK should be owned by OnesdK team @erich-wang .

The following code is from Track1 SDK. It only allows input allowedmethod as string array from the first day it's added . There should be no change (or will be a breaking change). And we can't change it manually since it's autogenerated code. If want to change it, need modify swagger and SRP server behavior.
https://github.com/Azure/azure-sdk-for-net/blob/f775e1f8b8d33904015800c4d0894115a6d22515/sdk/storage/Azure.ResourceManager.Storage/src/Generated/Models/CorsRules.Serialization.cs#L40

The following code should be from Track2 SDK. If you need any change from it, @erich-wang  should can help you.
 https://github.com/Azure/azure-sdk-for-net/blob/5dab3a1cca12c705811db62e222974af9b8d8aab/sdk/testcommon/Azure.Management.Storage.2019_06/src/Generated/Models/CorsRuleAllowedMethodsItem.cs#L20
And the allowed method will be a list of method item, so still allows input multiple allowedmethod.
https://github.com/Azure/azure-sdk-for-net/blob/7804c1535092020e16152215db4a4283112ba51c/sdk/storage/Azure.ResourceManager.Storage/src/Generated/Models/CorsRule.cs#L68

@verbedr , would you please clarify what's the issue, and what change needed?

**Comment by verbedr** [comment] 2020-09-24 10:42
@blueww  sorry for the late reply. I had to verify some things (after 1 1/2 years things could have changed). 

So the issue happens when you use a blob storage trigger in an azure function app. The latest library for this is the Microsoft.Azure.WebJobs.Extensions.Storage version 4.0.2 which references the microsoft.azure.storage.blob version 11.1.7 (and not azure.storage.blobs version 12.6.0. So the bug should be redirected to the Azure function domain and they should first of all use the latest libraries.

In the previous version the blob storage properties are queried and an XML document was parsed. (I assume this is not the case with this version.) With the XML document the CORS values were provided with a single value containing a comma separated list of all selected cors properties (it could be that they changed this by now).  If I now fetch the configuration via the az cli the json clearly separates those values as expected. And thus does will not provide any issues anymore.

@erich-wang one of the verbs is 'PATCH' this is not listed as a static reference value. But I don't think this is a blocking. issue based on who the CorsRuleAllowedMethodsItem works.

I hope this explains the original problem and the history a bit. 

@Rapol I think you should need to clarify what version of the storage library you are currently using. And recheck if the issue is still there.

Kr
Dries

**Comment by blueww** [comment] 2020-09-25 01:58
@verbedr
Thanks for the investigate!
So this issue is reported on the dataplane Track1 SDK, not Management plan SDK.

I see you have redirected it to the Azure function domain.
I owns management plan Track1 SDK, feel free to let me know if anything else I can do to help this.

**Comment by blueww** [comment] 2020-09-30 02:31
As this is for the dataplane storage SDK, add "Client" tag besides "Storage" tag.

**Comment by amnguye** [comment] 2020-10-01 19:15
Thanks for the investigation @blueww ! Since this is a track1 SDK and not management plane SDK problem I will label it with track1 and close this issue as per the original post, this is a duplicate of https://github.com/Azure/azure-storage-net/issues/916. Any issue with the track1 sdk should be kept on this thread. Please reactivate if this is a track2 issue (v12).

**Closed by amnguye** 2020-10-01 19:15 UTC
Labels: Client, Mgmt, Service Attention, Storage, bug, customer-reported, needs-team-attention, track1
