### ISSUE TITLE
[BUG] Error while sending message batches

### ISSUE THREAD

**Issue by arunprakashn** [Azure/azure-sdk-for-net#26109] opened 2021-12-28 13:54 UTC
### Library name and version

Azure.Messaging.Servicebus 7.5.1

### Describe the bug

I am trying to send messages using a batch and it fails stating the batch does not contain any data.

Azure service bus - Premium
Queue - Max message size (in KB) 10240 

### Expected behavior

The message batch is well within the per-message size of the premium azure service bus and the message must be sent to the service bus

### Actual behavior

Exception:
The link 'G3S3:5194339:amqps://arun-poc-premium-delete.servicebus.windows.net/-b48bffd8;0:5:6' is force detached by the broker because publisher(link25) received a batch message with no data in it. Detach origin: Publisher.

### Reproduction Steps

Repro code:

```
using System;
using System.Diagnostics;
using System.Text;
using System.Threading.Tasks;
using Azure.Messaging.ServiceBus;
using BenchmarkDotNet.Running;

// connection string to your Service Bus namespace
string connectionString = "REmoved - Azure premium connection string";

// name of your Service Bus topic
string topicName = "datafeedtest";

// the client that owns the connection and can be used to create senders and receivers
ServiceBusClient client;

// the sender used to publish messages to the topic
ServiceBusSender sender;

// number of messages to be sent to the topic
int numOfMessages = 0;

//byte[] data = new byte[100 * 1024 * 1024];
//Random rng = new Random();
//rng.NextBytes(data);
string strdata = GenerateString();
{
    // The Service Bus client types are safe to cache and use as a singleton for the lifetime
    // of the application, which is best practice when messages are being published or read
    // regularly.
    //
    // Create the clients that we'll use for sending and processing messages.
    client = new ServiceBusClient(connectionString,
     new ServiceBusClientOptions()
     {
         //RetryOptions = new ServiceBusRetryOptions() { TryTimeout = TimeSpan.FromMinutes(5) }

     });

    sender = client.CreateSender(topicName);
    try
    {
        ServiceBusMessage msg = new ServiceBusMessage(strdata);
        ServiceBusMessageBatch batch = await sender.CreateMessageBatchAsync();
        //await sender.SendMessagesAsync(Enumerable.Repeat(msg, 100));
        for (int i = 0; i <= 800; i++)
        {
            batch.TryAddMessage(msg);

        }
        Console.WriteLine($"BatchSizeBytes: { batch.SizeInBytes}");
        Stopwatch stopWatch = new Stopwatch();
        stopWatch.Start();
        await sender.SendMessagesAsync(batch);
        stopWatch.Stop();
        Console.WriteLine($"Time taken to send {stopWatch.ElapsedMilliseconds}");
    }
    catch (Exception ex)
    {
        Console.Write(ex.Message);
    }
    finally
    {
        // Calling DisposeAsync on client types is required to ensure that network
        // resources and other unmanaged objects are properly cleaned up.
        await sender.DisposeAsync();
        await client.DisposeAsync();
    }

    Console.WriteLine("Press any key to end the application");
    Console.ReadKey();


}

String GenerateString()
{
    int length = 10 * 1024 * 1;
    //int length = 200000;
    StringBuilder sb = new StringBuilder();

    for (int i = 0; i < length; i++)
    {
        sb.Append('A');
    }

    return sb.ToString();

}
```
See the image below that the batch contains 801 messages and the total size is well within the max allowed
![image](https://user-images.githubusercontent.com/94539366/147573130-80031da7-7d43-4ab1-9338-7effb179f82b.png)

### Environment

VS 2022
Azure Messaging ServiceBus 7.5.1
.Net core 6

**Comment by jsquire** [comment] 2021-12-28 14:54
Hi @arunprakashn.  I’m sorry to hear that you’re still having difficulty with this, and that there hasn’t been an update on #25381 with feedback from the service team.  

Unfortunately, I don’t have insight on those discussions and will need to defer to @JoshLove-msft who was driving those conversations.  Given the holidays, many folks are out of the office until next week and it’s unlikely that we’ll see an update before then.

In the meantime, I’m going to close this out as a dupe of #25381.

**Closed by jsquire** 2021-12-28 14:54 UTC
Labels: needs-triage, customer-reported, question
