### ISSUE TITLE
ClientRuntime - Microsoft.Rest.ServiceClient : Add support for in-memory client handler Microsoft.Owin.Testing.OwinClientHandler

### ISSUE THREAD

**Issue by vtherry** [Azure/azure-sdk-for-net#2980] opened 2017-03-22 14:05 UTC
Hi,

as of today, we are forced to use an HttpClientHandler as the root handler in the class Microsoft.Rest.ServiceClient<T>.

Since we have a webapi selfhosted in OWIN, we would like to run our integration tests against an in-memory webapi so that our tests run faster. This can be achieve using the package Microsoft.Owin.Testing and using the OwinClientHandler.

We generated our client with AutoRest so the only solution I can think of is inherit from the generated client (that in the end inherits from ServiceClient) and initialize the HttpClient ourselves.

It would be nice if we could provide the OwinClientHandler directly to the ServiceClient so that we do not rewrite the IntializeHttpClient() part.

Thank you

**Comment by markcowl** [comment] 2017-03-24 00:54
@vtherry ServiceClient provides constructor overloads, which allows clients that extend ServiceClient to use any rHttpClient they choose, which should serve the testing needs.

The problem is that the Owin Handler extends HttpMessageHandler, which does not allow setting important Http authentication, proxy, and other properties.  This being the case, using the HttpClient constructor overload seems liek the appropriate mechanism for supporting this.

**Comment by cormacpayne** [comment] 2017-04-07 18:26
@vtherry does the suggested overload constructor fix your issue? Please let us know if it does not.

We are going to close this issue - please feel free to reopen if your issue has not be resolved.

**Closed by cormacpayne** 2017-04-07 18:26 UTC
Labels: Team
