### ISSUE TITLE
FrontDoor FrontendEndpoint update did report MetodNotAllowed

### ISSUE THREAD

**Issue by SergeBerwert** [Azure/azure-sdk-for-net#7050] opened 2019-07-30 18:03 UTC
We are working on a new platform. We wane use FrontDoor but for that, we need to automate the Certification Replace Process. I Downloaded the Preview SDK and try to implement that. Because it's all-new there is now Documentation or Examples available at the moment. I am not sure if I di something wrong or if it’s a bug or not implemented yet. I Would Really appreciate some help.
The following code illustrates what I try to do.

```
var sp = new ServicePrincipalLoginInformation
            {
                ClientId = "xxxxxxx-xxxxxxxxx-xxxxxx",
                ClientSecret = "xxxxxxx-xxxxxxxxx-xxxxxx"
            };
            var credentials = new AzureCredentials(sp, context.Config.Azure.TenantId, AzureEnvironment.AzureGlobalCloud);
            var client = new FrontDoorManagementClient(credentials)
            {
                SubscriptionId = "xxxxxxx-xxxxxxxxx-xxxxxx"
            };

            //Getting all FrontDoor instances
            var list = await client.FrontDoors.ListWithHttpMessagesAsync();

            //Select the FrontDoor instance
            var ff = list.Body.Single(e => e.FriendlyName == frontDoorName);

            //Select the FrontendEndpoint by Hostname 
            var root = ff.FrontendEndpoints.Single(e => e.HostName == domain);

            //KeyVault ResourceID
            var id = "/subscriptions/xxxxxxx-xxxxxxxxx-xxxxxx/resourceGroups/xxxxxxxxx/providers/Microsoft.KeyVault/vaults/xxxxxxxxx";

            //Clone the Endpoint and add KeyVault Certificate config
            var endpoint = new FrontendEndpoint(
                id: root.Id,
                hostName: root.HostName,
                sessionAffinityEnabledState: root.SessionAffinityEnabledState,
                webApplicationFirewallPolicyLink: root.WebApplicationFirewallPolicyLink,
                name: root.Name,
                sessionAffinityTtlSeconds: root.SessionAffinityTtlSeconds,
                customHttpsConfiguration: new CustomHttpsConfiguration
                {
                    CertificateSource = "AzureKeyVault",
                    Vault = new KeyVaultCertificateSourceParametersVault(id: id),
                    SecretName = "XXX",
                    SecretVersion = "XXX"

                });

            //Update -- Call failed: Operation returned an invalid status code 'MethodNotAllowed'
            await client.FrontendEndpoints.CreateOrUpdateAsync(resourceGroup, frontDoorName, root.Name, endpoint);
```

**Comment by kurtzeborn** [comment] 2019-07-30 23:14
Thanks for asking this question.  I'm adding some labels to help route it to someone who can  provide you with a good answer.

**Comment by SergeBerwert** [comment] 2019-07-31 13:47
Hi @kurtzeborn 
Thanks for your help, but I think it should bee FrontDoor not KeyVault

**Comment by delradie** [comment] 2019-08-05 16:32
Just to add my experience, I would back up @SergeBerwert view that the problem is at the FrontDoor level. 
We're currently sandboxing use of the Microsoft.Azure.Management.FrontDoor nuget to programmatically work with FD as part of some new infrastructure. Our sandbox test is a lot simpler, trying to simply add a FrontEndEndpoint at this stage. When the following code is run the ErrorResponse body contains the following message:

"Put" method is not allowed for this "FrontendEndpointEntityKey" entity.

`            FrontDoorManagementClient Interface = await GetClientInstance();

            FrontendEndpoint Parameters = new FrontendEndpoint()
            {
                HostName = hostName,
                Name = endpointName,
                SessionAffinityEnabledState = "Enabled",
                WebApplicationFirewallPolicyLink = null,
            };

            AzureOperationResponse<FrontendEndpoint> Response;

            try
            {
                Response = await Interface.FrontendEndpoints.CreateOrUpdateWithHttpMessagesAsync(resourceGroup, frontDoor, endpointName, Parameters);
            }
            catch (ErrorResponseException exc)
            {
                LastError = exc.Response?.Content;

                if(String.IsNullOrWhiteSpace(LastError))
                {
                    LastError = exc.ToString();
                }

                return false;
            }`

Any help much appreciated as this is stopping work on a major part of our roadmap. TIA

**Comment by loarabia** [comment] 2019-08-15 22:56
Hi @SergeBerwert  and @delradie  I'm reaching out through internal teams to see if I can find someone who can help here and at the same time I'm adding some more tags to get this on a few more people's radar.

**Comment by pichandwork** [comment] 2019-08-15 23:43
Hi @SergeBerwert and @delradie ,
PUT operations are not allowed on frontendendpoints. To enable https on custom domains, please use FrontendEndpointsOperationsExtensions::BeginEnableHttps() or IFrontendEndpointsOperations:EnableHttpsWithHttpMessagesAsync() methods.

**Comment by SergeBerwert** [comment] 2019-08-18 21:57
@pichandwork that did work for me thx.

**Comment by delradie** [comment] 2019-08-21 14:46
Hi @pichandwork. 

Thanks for sharing about the HTTPS side. That will be really important down the line for us (and the information generally helped us get our interim powershell solution to work). 
If you can give any guidance on the initial creation of the endpoint that would be very much appreciated as I've struck out so far trying to route an official support request through our partner account. 

To help make for easier debugging through I've added a single-purpose command line util (AddCustomFrontDoorHostName) to the solution in https://github.com/delradie/AzureManagement/tree/feature/FrontDoor/FrontDoorManagement that should help demonstrate the problem we are having. I'm hoping it's something as silly as we are passing the parameters incorrectly for an initial creation but I'm at a loss on how to get it working
TIA

**Comment by jessicl-ms** [comment] 2019-08-23 21:20
Hi @delradie,

As @pichandwork said, PUT operations are currently not supported for frontend endpoints. 

If your end goal is to update your frontend endpoints, you can still achieve it by making a general call to update your front door where you pass in the new frontend endpoint information. To do this, first retrieve all your frontend endpoints associated with your front door, and modify that list to include your new frontend endpoint information. Finally, pass the whole list to a frontdoor update call. Code snippet example below:

```
// Retrieve frontdoor, which includes retrieving frontend endpoints for your front door
var frontDoor = frontDoorMgmtClient.FrontDoors.Get(resourceGroupName, frontDoorName);

// Add new endpoint
FrontendEndpoint frontendEndpoint2 = new FrontendEndpoint(
    name: "frontendEndpoint2",
    hostName: frontDoorName + ".azurefd.net",
    sessionAffinityEnabledState: "Disabled",
    sessionAffinityTtlSeconds: 10
    );

frontDoor.FrontendEndpoints.Add(frontendEndpoint2);

// Push changes to FD
try
{
    frontDoor = frontDoorMgmtClient.FrontDoors.CreateOrUpdate(resourceGroupName, frontDoorName, frontDoor);
}
catch (Microsoft.Azure.Management.FrontDoor.Models.ErrorResponseException e)
{
    throw;
}
```

**Comment by delradie** [comment] 2019-08-26 10:51
Many thanks. That's worked. I'm presuming the CreateOrUpdate method on the FrontendEndpointsOperations was auto-generated and in fact shouldn't be there?
Either way, the code is working now so that's  win. Thanks for your help @jessicl-ms

**Comment by xenalite** [comment] 2019-09-05 08:48
It's been over a month now. When are you going to fix your API?
The documentation says everything's fine:
https://docs.microsoft.com/en-us/rest/api/frontdoorservice/frontdoor/frontendendpoints/createorupdate

**Comment by xenalite** [comment] 2019-09-10 22:18
Reply from MSFT Support:

> Hello Oskar,
>  
> Yes I’ve spoke with PG and they will update the document to remove this.
>  
> They tell me currently they have no immediate plans to support PUT operations on frontend endpoints, so they will remove from the documentation.

**Comment by Petermarcu** [comment] 2020-07-22 06:13
From my read of this, it looks like this was resolved by fixing the documentation to clarify that it doesn't support PUT. I'm going to close now.

**Comment by lilyjma** [comment] 2021-01-08 00:27
Closing for the reason Peter gave. But if this still presents a problem, please reopen.

**Closed by lilyjma** 2021-01-08 00:27 UTC
Labels: App Services, Mgmt, Service Attention, customer-reported, needs-team-attention, question
