### ISSUE TITLE
Evaluate enabling multi-targeting for track2 Azure SDKs wherever needed.

### ISSUE THREAD

**Issue by pallavit** [Azure/azure-sdk-for-net#30685] opened 2022-08-23 16:50 UTC
We have seen instances where Key Vault, Monitor Ingestion Log behave differently across different frameworks. As of now we have worked around the differences via reflection.

We need to evaluate what parameters should we use to decide whether an SDK should be enabled for multitargeting and which of our SDKs would benefit from this.

**Comment by jsquire** [comment] 2022-08-24 16:08
Can you please provide more context around what "behave differently" means?   There is not enough information to understand what action needs to be taken or how to make the requested evaluation.

**Comment by pallavit** [comment] 2022-08-24 16:19
We have different APIs support between the different frameworks in case of Keyvault. In case of monitor log - some of the Gzipstream methods behave differently in .NetFramework vs .Net Core

There is conversation on the teams channel for it. I created the issue so we do not lose track of it and continue to follow-up. Let me know if you want more details here.

**Comment by annelo-msft** [comment] 2023-06-21 18:21
Closing this issue as duplicate of https://github.com/Azure/azure-sdk-for-net/issues/28577, but @pallavit, feel free to reopen if you feel they're distinct, or add any additional context you'd like to track on https://github.com/Azure/azure-sdk-for-net/issues/28577 for that investigation.

**Closed by annelo-msft** 2023-06-21 18:21 UTC
Labels: Client, Azure.Core, feature-request

**Comment by annelo-msft** [comment] 2023-06-22 00:07
Ah, cool, thanks @pallavit!  Would you mind filling in the thinking behind the decision not to do this, so we can document it here in case we ever decided to revisit the question?
