### ISSUE TITLE
[BUG] `QueueMessage` output binding ignores `ExpirationTime`

### ISSUE THREAD

**Issue by afscrome** [Azure/azure-sdk-for-net#32846] opened 2022-12-02 17:41 UTC
### Library name and version

Microsoft.Azure.WebJobs.Extensions.Storage.Queues 5.0.1

### Describe the bug

When returning a QueueMessage through a function output binding, `QueueMessage.ExpirationTime` is ignored 

### Expected behavior

I'd expect the message expiration time to be set to `QueueMessage.ExpirationTime`

### Actual behavior

The message is queued with an expiration time 1 week into the future, regardless of what is set on `QueueMessage.ExpirationTime`
![image](https://user-images.githubusercontent.com/289860/205353790-2f896808-007d-47ef-b80b-20f07a7e0227.png)

### Reproduction Steps

```cs
    [FunctionName("Sample")]
    [StorageAccount("AzureWebJobsStorage")]
    [return: Queue("SampleQueue")]
    public QueueMessage Sample(
        [TimerTrigger("* * * * * *", UseMonitor = true)] TimerInfo timer,
        ILogger log
    )
    {
        return QueuesModelFactory.QueueMessage(null, null, new BinaryData("Hello World"), 0, expiresOn: DateTime.UtcNow.AddMinutes(30));
    }
```

### Environment

Visual Studio Version 17.3.6

**Comment by navba-MSFT** [comment] 2022-12-05 02:52
@afscrome Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment] 2022-12-05 08:16
@afscrome Could you please use the below sample code ?

 ```
QueueClient queue = new QueueClient("DefaultEndpointsProtocol=https;AccountName=MyStorageAccountName;AccountKey=XXXXXXXXXXXXX;EndpointSuffix=core.windows.net", "SourceQueueName");

queue.SendMessage("helloExpiry", default, TimeSpan.FromSeconds(60), default);
```

Expiration has been set to **60 Seconds**:

![image](https://user-images.githubusercontent.com/57353862/205581714-482ffa3d-6be8-4225-8930-afab7f5bfa60.png)

**Comment by afscrome** [comment] 2022-12-05 10:22
Hi @navba-MSFT - that code probably works, but it's not using the Azure Function output binding which I'm trying to use.  The documentation says that you can bind a `QueueMssage`, so I was expecting this to work.

https://learn.microsoft.com/en-us/azure/azure-functions/functions-bindings-storage-queue-output?tabs=in-process%2Cextensionv5&pivots=programming-language-csharp

![image](https://user-images.githubusercontent.com/289860/205613288-8bfc2075-ba94-41bd-86f0-96c8fdb0d81c.png)

**Comment by navba-MSFT** [comment] 2022-12-06 07:01
@afscrome The same article talks about using [QueueClient](https://learn.microsoft.com/en-us/dotnet/api/azure.storage.queues.queueclient?view=azure-dotnet) too hence I had suggested the above sample code. 

![image](https://user-images.githubusercontent.com/57353862/205843096-2a528852-9496-45b8-aee9-2360107661e0.png)

May I know your feasibility of using QueueClient over QueueMessage ?

**Comment by afscrome** [comment] 2022-12-07 10:53
Hi @navba-MSFT, writing directly to the queue client works, but it adds a lot of complication for my use case.

* Writing unit tests for functions using `QueueClient.Publish` is more complicated as it requires mocking out the queue client and validation.  This is particularly true as some of my functions want to queue up multiple messages (i.e. return `QueueMessage[]`.
* My messages have fixed deadlines,  specifying `QueueMessage.ExpiresAt` fits more cleanly with my use case than having to calculate a time to live.

**Comment by navba-MSFT** [comment] 2022-12-07 10:55
@afscrome Could you please let us know your use case ?

**Comment by navba-MSFT** [comment] 2022-12-12 04:11
@afscrome I am able to reproduce this issue at my end and I am debugging this further. Sharing my findings so far:

I could see that the messagettl query string is not appended to the RequestUrl while sending the message using [QueueMessage](https://learn.microsoft.com/en-us/dotnet/api/azure.storage.queues.models.queuemessage?view=azure-dotnet). However while using QueueClient I see the ttl is being sent in the request url.

Request URL with [QueueMessage](https://learn.microsoft.com/en-us/dotnet/api/azure.storage.queues.models.queuemessage?view=azure-dotnet):    https://MyStorageAccount.queue.core.windows.net/samplequeue/messages    (Since TTL is not sent here, it is using the default 7 days TTL)
Request URL with [QueueClient](https://learn.microsoft.com/en-us/dotnet/api/azure.storage.queues.queueclient?view=azure-dotnet): https://MyStorageAccount.queue.core.windows.net/samplequeue/messages?messagettl=60

**Comment by navba-MSFT** [comment] 2022-12-15 04:25
@afscrome We do plan to address this Bug. Unfortunately, we can’t give an ETA at this time due to other commitments and other priorities. We will update this GitHub thread once we release the fix for this. You can use this GitHub thread for tracking purpose.

**Comment by navba-MSFT** [comment] 2022-12-15 04:27
@xgithubtriage Please update this thread once the fix is released. Thanks in advance.

**Closed** 2024-12-02 18:06 UTC
Labels: Storage, Service Attention, Client, customer-reported, bug, needs-team-attention
