### ISSUE TITLE
Event Grid - Migration guide

### ISSUE THREAD

**Issue by JoshLove-msft** [Azure/azure-sdk-for-net#16688] opened 2020-11-06 18:04 UTC
Create a migration guide for customers transitioning from Track 1 to Track 2 similar to what we have for Service Bus and Event Hubs.

**Comment by ramya-rao-a** [comment] 2020-11-09 07:13
Please wait for this issue to be updated with the link to the Migration Guide template.

**Comment by ramya-rao-a** [comment] 2020-12-08 22:28
Please use the template in this [PR that adds the migration guide to our policies](https://github.com/Azure/azure-sdk/pull/2132)

**Comment by jsquire** [comment] 2021-02-16 14:36
Closing this as a duplicate of #16740

**Closed by jsquire** 2021-02-16 14:36 UTC
Labels: Client, Docs, Event Grid
