### ISSUE TITLE
OutOfMemoryException with Microsoft.Azure.Search

### ISSUE THREAD

**Issue by PhilipDaniels** [Azure/azure-sdk-for-net#5010] opened 2018-11-12 17:03 UTC
I am using the package `<PackageReference Include="Microsoft.Azure.Search" Version="5.0.2" />`

I have written a small program to generate a large number of documents with random properties and upload them to Azure Search using `IndexClient.Documents.Index(batch);`. When run for a long time, the program will eventually fail with an `OutOfMemoryException`. I attach a screenshot from the VS diagnostics. Looks like there is a leak somewhere in the creation of tasks for applying the retry policy? Note the size of the `StringContent`.

![image](https://user-images.githubusercontent.com/1809220/48362849-7f4f7300-e69c-11e8-9242-f10a8f745525.png)

**Comment by brjohnstmsft** [comment] 2018-11-13 07:35
This issue is fixed in Microsoft.Azure.Search 5.0.3.

Closing this since it's a duplicate of https://github.com/Azure/azure-sdk-for-net/issues/4678

**Closed by brjohnstmsft** 2018-11-13 07:35 UTC
