### ISSUE TITLE
[FEATURE REQ] Ensure that Azure.Core can be used with Native AoT 

### ISSUE THREAD

**Issue by jmprieur** [Azure/azure-sdk-for-net#38773] opened 2023-09-17 22:21 UTC
### Library name

Azure.Core

### Please describe the feature.

Today, if you build a shared library with Native AOT, that references the KeyVault SDK (and therefore Azure.Identity, and Azure.Core), and your run it, you'll get this **runtime** exception:

```text
This object cannot be invoked because no code was generated for it: Azure.Core.AzureResourceProviderNamespaceAttribute.ResourceProviderNamespace
```

This is because the type/property is only used by reflection.

[https://github.com/Azure/azure-sdk-for-net/blob/031a2f81a1f067fa2588e177c7325e397144f608/sdk/core/Azure.Core/src/Shared/ClientDiagnostics.cs#L63](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzure%2Fazure-sdk-for-net%2Fblob%2F031a2f81a1f067fa2588e177c7325e397144f608%2Fsdk%2Fcore%2FAzure.Core%2Fsrc%2FShared%2FClientDiagnostics.cs%23L63&data=05%7C01%7CJean-Marc.Prieur%40microsoft.com%7C1474c83430564589e4e108dbb7c5d62a%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638305832642613724%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=roIHONO%2BR4pQ%2F2%2FewAH0KGKAbhpCRw1snb9Bc0cy5W8%3D&reserved=0)

if you try to exclude Azure.Core in the `rd.xml`,
```xml
   <Assembly Name="Azure.Core" Dynamic="Required All">
     <Type Name="Azure.Core.AzureResourceProviderNamespaceAttribute" Dynamic="Required All" />
   </Assembly>
```

You'll get the following **build** error:
```text
Failed to load type 'Azure.Core.AzureResourceProviderNamespaceAttribute' from assembly 'Azure.Core, Version=1.25.0.0, Culture=neutral, PublicKeyToken=92742159e12e44c8'
```
I'm not sure why the type is not found, though. Does the production of Azure.Core involve ILMerge or something like that?

 
This feature request is to ensure that the compiler is aware of the fact that reflection is used and that this property should not be trimmed, and more generally Azure.Core is trimmable

**Comment by jsquire** [comment] 2023-09-18 13:04
Hi @jmprieur.  Thank you for reaching out and we regret that you're experiencing difficulty.   We are currently working to enable AOT compatibility within Azure.Core for certain key scenarios, such as AppInsights, KeyVault, and Storage Blobs use.   The following pull-requests are open for this, should you want to track:

- [Add AOT target for Key Vault SDK (#38721)](https://github.com/Azure/azure-sdk-for-net/pull/38721)
- [[Core] Adding attributes to support Native AOT compiling (#37734)](https://github.com/Azure/azure-sdk-for-net/pull/37734)

**Comment by jsquire** [comment] 2023-09-18 15:33
@jennyf19: There is currently no committed date for release.  Assuming that there are no technical blockers, we would like to ensure that this work is available near the .NET 8 release window.

**Comment by jsquire** [comment] 2023-09-20 19:30
I'm going to close this out as a duplicate of #35572.  Work will continue to be tracked there.

**Closed by jsquire** 2023-09-20 19:30 UTC
Labels: Client, Azure.Core, customer-reported, feature-request, needs-team-attention
