### ISSUE TITLE
[BUG]Breaking change- Fail on DataLakeFileSystemClient.GetPaths when call it on a storage without hierarchical namespace

### ISSUE THREAD

**Issue by LeaShallev** [Azure/azure-sdk-for-net#28825] opened 2022-05-17 06:21 UTC
### Library name and version

Azure.Storage.Files.DataLake 12.10.0

### Describe the bug

Following an update from Azure.Storage.Files.DataLake 12.9.0 to 12.10.0, we start getting an error when trying to call DataLakeFileSystemClient.GetPaths on a storage without hierarchical namespace.
The error:
System.FormatException: 'Input string was not in a correct format.'

We know that datalake clients should be use on storage with hierarchical namespace, but as we already have customers using dfs endpoint for storage without hierarchical namespace and it demands an extra network call to get storage properties so we want to avoid it- it is a breaking change for us.

### Expected behavior

Get paths

### Actual behavior

System.FormatException: 'Input string was not in a correct format.'

### Reproduction Steps

Use the following code with Azure.Storage.Files.DataLake 12.10.0:
            var dataLakeServiceClientOnblob = new DataLakeServiceClient("CONNECTION_STRING_FOR_STORAGE_WITHOUT_HNS");
            var fileSystemOnblob = dataLakeServiceClientOnblob.GetFileSystemClient("FILE_SYSTEM_NAME");
            foreach (var path in fileSystemOnblob.GetPaths(PATH))
            {
                Console.WriteLine(path.Name);
            }

**Comment by navba-MSFT** [comment] 2022-05-19 03:20
@LeaShallev Thanks for reaching out to us and sharing this feedback. I am looking into this issue. I will provide an update once I have more details.

**Comment by navba-MSFT** [comment] 2022-05-19 09:19
@LeaShallev I am able to reproduce this issue. I am doing some more research on this. I will keep you posted on the progress.

**Comment by LeaShallev** [comment] 2022-05-23 05:37
@navba-MSFT  Is there any update? Thanks!

**Comment by navba-MSFT** [comment] 2022-05-23 06:42
@LeaShallev I have reached out to the Product Owners and this is under discussion now. Since you are internal to Microsoft, I am looping you in that email thread if that helps.

**Comment by amnguye** [comment] 2022-05-27 22:16
Just made a PR to look for a fix for this issue. Looking to merge once CI and all approvals are received.

Thanks for your patience.

**Comment by LeaShallev** [comment] 2022-05-29 05:33
Great. Thanks!

**Comment by navba-MSFT** [comment] 2022-06-06 07:24
Thanks @amnguye .

**Closed** 2022-06-06 17:45 UTC
Labels: Client, customer-reported, question, Data Lake Storage Gen2, needs-team-attention, CXP Attention
