### ISSUE TITLE
[FormRecognizer] Consider handling failed status for receipts and content operations

### ISSUE THREAD

**Issue by kinelski** [Azure/azure-sdk-for-net#11474] opened 2020-04-21 18:51 UTC
## Summary

When starting or polling results from a RecognizeCustomForms Operation, it's known that the service may return a successful HTTP status code even when the operation itself has failed. This is already being handled and a `RequestFailedException` is being thrown in these scenarios.

https://github.com/Azure/azure-sdk-for-net/blob/8f5c50cb3b65bfa0544c76867464252b2bd02d1a/sdk/formrecognizer/Azure.AI.FormRecognizer/src/RecognizeCustomFormsOperation.cs#L120-L126

However, there are no known scenarios in which Receipts/Content recognition operations can behave the same way. In case such scenarios exist, they must be handled as well.

## Goals

- Understand the possible error scenarios that can be returned from the service when running Content/Receipts recognition operations.
- If necessary, update the client code so it can handle the aforementioned scenarios.
- Create tests to validate the changes.
- Make sure existing tests still pass reliably.

**Comment by annelo-msft** [comment] 2020-05-07 23:11
Duplicate of: https://github.com/azure/azure-sdk-for-net/issues/11473

**Closed by annelo-msft** 2020-05-07 23:11 UTC
Labels: Client, Cognitive Services, FormRecognizer
