### ISSUE TITLE
Add 'Automation tempate checkness' in CI pipeline

### ISSUE THREAD

**Issue by chunyu3** [Azure/azure-sdk-for-net#26590] opened 2022-01-25 07:34 UTC
add a step in azure-sdk-for-net pipeline to generate a sample sdk to validate the correctness of the automation template and the scipts.

**Comment by annelo-msft** [comment] 2022-03-26 00:41
Duplicate of https://github.com/Azure/azure-sdk-for-net/issues/26345

**Closed by annelo-msft** 2022-03-26 00:41 UTC
Labels: Client, EngSys, LLC
