### ISSUE TITLE
[FEATURE REQ] Improve retry options for Service Bus input binding

### ISSUE THREAD

**Issue by JoostLambregts** [Azure/azure-sdk-for-net#46125] opened 2024-09-23 12:42 UTC
### Library name

Microsoft.Azure.WebJobs.Extensions.ServiceBus

### Please describe the feature.

We have a Javascript Azure Function that uses a Service Bus trigger. Our function then forwards the message a downstream dependency that is frequently unreachable. We would like to retry our function with an exponential backof when the downstream dependency is unavailable. Currently, the Service Bus trigger does not seem to support any retry policy at all for function failures.

Current behavior: When the function fails, the message is immediately abandoned. This leads to the message being immediately retried.

Wanted behavior: When the function fails, the message stays locked for some time determined by a retry policy

For context, we have some events that _must_ be delivered to some IoT devices. We are using Azure Functions for the delivery, and used to use Event Grid to implement the retries, which supports exponential backoff. Recently we moved our functions to an Application Service Environment, and using an Event Grid trigger from an ASE is not supported. We switched to Service Bus for this reason, but we are having trouble to get retries to work.

**Comment by jsquire** [comment] 2024-09-23 15:54
Hi @JoostLambregts.  Thanks for reaching out and we regret that you're experiencing difficulties.  The feature that you're looking for is not something that the client can facilitate alone - it requires the Service Bus service to provide an additional operation (abandon with delay).  This has been a long-standing feature request of the service and is being tracked by [#454](https://github.com/Azure/azure-service-bus/issues/454) in the Service Bus repository.

Once the operation is supported by the service, it will be added to the Azure SDK clients as well.   For now, I'm going to close this out as a duplicate of the linked service feature.  Once the service team completes the service-side feature and deployments, we'll open tracking issues in each of the Azure SDK language repositories for client support.

**Closed by jsquire** 2024-09-23 15:54 UTC
Labels: Client, customer-reported, question, Functions, needs-team-attention
