### ISSUE TITLE
[BUG] [Compute Gallery] ecxeption : Can not delete resource before nested resources are deleted

### ISSUE THREAD

**Issue by yangchengs** [Azure/azure-sdk-for-net#30258] opened 2022-08-02 06:05 UTC
### Library name and version

Microsoft.Azure.Management.Compute 52.0

### Describe the bug

                Console.WriteLine(DateTime.UtcNow.ToLocalTime());
                Console.WriteLine("Delete gallery image version {0} {1}", imageDefinition, versionName);
                resourcesClient.GalleryImageVersions.Delete(rgName, galleryName, imageDefinition, versionName);

                //System.Threading.Thread.Sleep(10000);

                Console.WriteLine(DateTime.UtcNow.ToLocalTime());
                Console.WriteLine("Delete base image definition {0}", imageDefinition);
                resourcesClient.GalleryImages.Delete(rgName, galleryName, imageDefinition);

If I run the code above without sleep, there will be exception:
 Can not delete resource before nested resources are deleted.

It seems that the clean work did not complete gracefully.

### Expected behavior

I can delete gallery image version and gallery image definition in sequence. 

### Actual behavior

I have to call sleep in between.

### Reproduction Steps

See the sample

**Comment by jsquire** [comment] 2022-08-02 12:41
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by yangchengs** [comment] 2022-08-02 13:26
I file a similar issue in python SDK. It could be REST API issue, the first delete did not clean up everything when the sync call returns. It has to wait several seconds.

https://github.com/Azure/azure-sdk-for-python/issues/25506

**Comment by HarveyLink** [comment] 2022-10-20 06:16
Close the issue as service team consider it is by design. https://github.com/Azure/azure-sdk-for-python/issues/25506#issuecomment-1262743403
Please reopen it if you see any concerns.

**Closed by HarveyLink** 2022-10-20 06:16 UTC
Labels: Compute, Mgmt, customer-reported, question, needs-team-attention
