### ISSUE TITLE
Check-Enforcer hangs during CI

### ISSUE THREAD

**Issue by tg-msft** [Azure/azure-sdk-for-net#7892] opened 2019-10-03 00:31 UTC
Creating a tracking bug we can reference for CI restarts when Check-Enforcer hangs (or takes more than a reasonable amount of time).

**Comment by mitchdenny** [comment] 2019-10-03 04:27
Just want to make sure that I'm understanding the scenario here. Are you talking about CI builds that run after PR merge, or are you talking about during the PR process (when you type```/azp run [build name]``).

**Comment by tg-msft** [comment] 2019-10-03 04:29
In the case of #7843, it was during the PR process

**Comment by JoshLove-msft** [comment] 2019-10-03 20:49
This happened again on #7882

**Comment by JoshLove-msft** [comment] 2019-10-03 21:21
Any ideas on how to get this to finish? It appears stuck again.

**Comment by mitchdenny** [comment] 2019-11-12 03:03
I have an issue open with GitHub that I am tracking as part of the overall Check Enforcer work. I'm going to close this one down since its redundant at this point, the issue is known, we are just waiting for a fix.

**Closed by mitchdenny** 2019-11-12 03:03 UTC
Labels: EngSys
