### ISSUE TITLE
SqlServerDatabaseReplicationLinkResource.DeleteAsync throws exception on 202 status code

### ISSUE THREAD

**Issue by jhabkohrs** [Azure/azure-sdk-for-net#30960] opened 2022-09-06 19:52 UTC
Calling SqlServerDatabaseReplicationLinkResource.DeleteAsync generates a response with a http status code of 202, which results in an exception being thrown. When I go to the Azure portal, the link has been removed, so it appears that this operation works, but just incorrectly throws an exception.

```
Azure.RequestFailedException : Service request failed.
Status: 202 (Accepted)

Content:
{"operation":"ForceStopDatabaseCopy","startTime":"2022-09-06T19:47:17.453Z"}

Headers:
Cache-Control: no-cache
Pragma: no-cache
Location: REDACTED
Retry-After: 10
Azure-AsyncOperation: REDACTED
x-ms-request-id: cf62923e-56bc-452c-bd2c-e4ba08fee468
Server: Microsoft-HTTPAPI/2.0
x-ms-ratelimit-remaining-subscription-deletes: REDACTED
x-ms-correlation-request-id: REDACTED
x-ms-routing-request-id: REDACTED
Strict-Transport-Security: REDACTED
X-Content-Type-Options: REDACTED
Date: Tue, 06 Sep 2022 19:47:18 GMT
Content-Length: 76
Content-Type: application/json; charset=utf-8
Expires: -1
```

**Comment by jsquire** [comment] 2022-09-07 12:44
@jhabkohrs:  Would you please let us know the package and version that you're using so that we can triage to the team member best able to assist?

**Comment by jhabkohrs** [comment] 2022-09-07 13:20
I am using the 1.0.0 version of Azure.ResourceManager.Sql.

**Comment by xboxeer** [comment] 2022-09-08 08:58
@jhabkohrs we checked our code and seems can take 202 as a valid response. Would you please share your code and let us know what type of SQL and replicationlink you created so that we can try reproduce on our side?

**Comment by jhabkohrs** [comment] 2022-09-08 16:04
It does appear that this commit (https://github.com/Azure/azure-sdk-for-net/commit/936baab7398867eba11c127294ed5dd2ecbf9467) should fix the issue. However, when I decompile the 1.0.0 version of Azure.ResourceManager.Sql, the 202 case is not there. Is this just a matter of the fix hasn't been pushed in a released NuGet package?

**Comment by xboxeer** [comment] 2022-09-09 03:35
I think https://github.com/Azure/azure-sdk-for-net/commit/936baab7398867eba11c127294ed5dd2ecbf9467#diff-4d50f7c27ae2112b63a1a2708cbef1e62f8b03359a7d47b6bef64acea34c137d this is to fix the 202 response code. @ArcturusZhang is this commit released to nuget?

**Comment by xboxeer** [comment] 2022-09-09 07:04
@jhabkohrs  Yes I believe the current released version does not consider 202 as a valid response that's why there is Service Request Failed exception. 
CC: @ArthurMa1978 , kindly help check and release a new version to address this issue

Any other feedback to Azure SDK, feel free to let us know in this [survey](https://www.surveymonkey.com/r/YSYFMFF)

**Comment by jhabkohrs** [comment] 2022-09-16 18:15
Any update on a potential release with this fix?

**Comment by xboxeer** [comment] 2022-09-19 05:15
@jhabkohrs we are still fixing some other issues regarding this package, ETA of latest version release date in Oct

**Comment by jhabkohrs** [comment] 2022-11-07 14:27
Is there an updated ETA on the package release?

**Comment by xboxeer** [comment] 2022-11-10 06:14
We shall release a fix package by the end of this week, cc @fengzhou-msft and @ArthurMa1978 for awarness

**Comment by fengzhou-msft** [comment] 2022-11-11 15:47
`Azure.ResourceManager.Sql` 1.1.0 is released. Please have a try.

**Comment by xboxeer** [comment] 2022-12-22 03:03
close this issue since we have released new packages to fix it

**Closed by xboxeer** 2022-12-22 03:03 UTC
Labels: SQL, Mgmt, customer-reported, question, needs-team-attention
