### ISSUE TITLE
Instructions for "Creating a Service Principal in Azure" do not work

### ISSUE THREAD

**Issue by GeekActual** [Azure/azure-sdk-for-net#3371] opened 2017-06-14 15:40 UTC
the last instruction given in [Creating a Service Principal in Azure](https://github.com/Azure/azure-sdk-for-net/blob/Fluent/AUTH.md#creating-a-service-principal-in-azure) do not work.

>4. Run the following command to create a service principal authentication file.
>
>`curl -L https://raw.githubusercontent.com/Azure/azure-sdk-for-net/Fluent/tools/authgen.py | python > my.azureauth`
>
>This will save the output of the command into an Azure service principal-based authentication file which can now be used in the Azure Management Libraries for .NET without requiring an interactive login nor the need to manage access tokens.

When run from Bash on Windows I get the following result:

```
xsgeek@XsGeekSurface:/mnt/c/Windows/System32$ curl -L https://raw.githubusercontent.com/Azure/azure-sdk-for-net/Fluent/tools/authgen.py | python > my.azureauth
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1530  100  1530    0     0  21079      0 --:--:-- --:--:-- --:--:-- 21250
Traceback (most recent call last):
  File "<stdin>", line 22, in <module>
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

**Comment by jianghaolu** [comment] 2017-06-14 17:34
Hi @GeekActual Can you verify `az ad sp create-for-rbac` works for you?

**Comment by martinsawicki** [comment] 2017-10-11 20:17
closing due to no reproducible steps. If there is a repro case, pls reopen.

**Closed by martinsawicki** 2017-10-11 20:17 UTC
Labels: Fluent
