### ISSUE TITLE
[QUERY] High cpu usage when upload to blob storage

### ISSUE THREAD

**Issue by jeffhli** [Azure/azure-sdk-for-net#25317] opened 2021-11-15 08:54 UTC
**Query/Question**
When I upload some blobs in parallel to azure blob storage, there are different cpu usage. I want to know what's the difference between two different configurations.

**Environment:**
 -  Azure.Storage.Blobs 12.10.0
 - .net core 3.1
 - IDE and version :  Visual Studio 16.5
 - Upload 4 blobs(10MB) in parallel
 - Parameter1: ```BlobUploadOptions options = new BlobUploadOptions
                    {
                        TransferOptions = new StorageTransferOptions
                        {
                            MaximumConcurrency = 5,
                            MaximumTransferSize = 1024 * 1024
                        }
                    };```
 - Parameter2: ```BlobUploadOptions options = new BlobUploadOptions
                    {
                        TransferOptions = new StorageTransferOptions
                        {
                            MaximumConcurrency = 2,
                            MaximumTransferSize = 4 * 1024 * 1024
                        }
                    };```
![image](https://user-images.githubusercontent.com/60603443/141751234-fd01f634-f397-49f4-9bad-ca37f023654b.png)
![image](https://user-images.githubusercontent.com/60603443/141751406-e94a27b7-465c-4de5-ba88-d677123c760e.png)

**Comment by amnguye** [comment] 2021-11-16 19:17
Parameter 1: Because the maximum concurrency is higher for that upload, but the maximum transfer size is smaller, there are multiple threads reading from memory at the same time, which would mean the RPM would increase due to the higher access to memory, and because the Transfer Block Size is smaller than Parameter 2, it shows this more obviously because the first scenario has to go and access memory more often cause the block size is smaller, and has the ability to because it is allocated more threads.

Parameter 2: Due to the large Maximum Transfer size, less reads are done on memory causing the RPM to be lower over the duration, though because there are less threads this would cause it to take longer. The higher CPU looks mainly due to the larger transactions (transfer size) that needs to occur over less threads. This is probably something to do with the way core has to handle larger request bodies and encrypting them properly.

@pakrym Let me know if there's any other explanation that needs to be added with the way Core handles the transactions with larger/smaller request bodies and/or more threads.

**Comment by jeffhli** [comment] 2021-11-17 06:48
From the RPM comparison picture, we can assume that the 'Parameter1' process consumes 0.4 cpu cores and uploads 220 blobs in one minute. However, the 'Parameter2' process consumes  0.9 cpu cores and uploads 140 blobs in one minute. I can not understand why the 'Parameter1' process can upload more blobs in consuming less CPUs. By the way, I also tried **Parameter3**: `BlobUploadOptions options = new BlobUploadOptions { TransferOptions = new StorageTransferOptions { MaximumConcurrency = 5, MaximumTransferSize = 4 * 1024 * 1024 } };`, the result is the same as **Parameter2**.

**Comment by amnguye** [comment] 2021-11-17 18:17
Sorry if this wasn't obvious from the Parameter 2 explanation. But because the Maximum Transfer Size or Request bodies are larger, there will be higher CPU due to the encryption process in Core that occurs. Increasing concurrency does not affect the encryption process because each request or transfer is done by 1 thread.

**Comment by pakrym** [comment] 2021-11-17 18:25
What's the input to the upload? cryptostream shows up in the profile and high CPU might be caused by CryptoStream using a small block size (https://github.com/Azure/azure-sdk-for-net/issues/21594 is somewhat related)

**Comment by jeffhli** [comment] 2021-11-18 03:23
@pakrym I think you are right. But the #21594 only fixed the high cpu in download feature instead of upload feature. https://github.com/Azure/azure-sdk-for-net/blob/f59a870652dc97f3a3a3fe09dd5ecc8094159901/sdk/storage/Azure.Storage.Common/src/Shared/ClientsideEncryption/ClientSideEncryptor.cs#L56
Our case is uploading a network stream with encryption.

**Comment by amishra-dev** [comment] 2022-03-01 00:59
@kasobol-msft could you work with @jaschrep-msft to see what it will take to fix in upload?

**Comment by jaschrep-msft** [comment] 2022-03-05 00:16
Judging from the referenced issue and PR, it looks like adding a BufferedStream between the provided Stream to upload and CryptoStream and validating the fix is the path forwards. I can take on that work as well as investigation should that not be the solution.

**Comment by jaschrep-msft** [comment] 2022-04-06 17:22
Sorry, this ended up on the backburner for a bit.

@jeffhli are you also setting `InitialTransferSize` in `StorageTransferOptions`? If you aren't, then I don't think we're ever hitting the concurrent path, as `MaximumTransferSize` (perhaps unintuitively) doesn't cap the `InitialTransferSize`. More on that [here](https://devblogs.microsoft.com/azure-sdk/tuning-your-uploads-and-downloads-with-the-azure-storage-client-library-for-net/#storagetransferoptions). So both of these uploads would be a single-block upload with no parallelism.

Regardless of which it is, the `CryptoStream` observation earlier in this thread is still likely the culprit and I am setting up some before/after tests with the fix. I just want to make sure I am accurately representing your own tests to ensure there aren't any strange differences coming into play.

**Comment by jeffhli** [comment] 2022-04-07 02:00
@jaschrep-msft I didn't set `InitialTransferSize` in `StorageTransferOptions`.

**Comment by jaschrep-msft** [comment] 2022-04-07 21:15
@jeffhli hm... are you uploading from an unseekable stream?
Uploads have a threshold they check for before partitioning an upload, and it defaults to 256MB when unspecified. If you gave a file path or a stream the length could be detected from, then neither of these configurations should split when given 10MB files/streams; the SDK would detect the threshold was not hit and one-shot the upload.

I'm unable to reproduce your results, with or without an `InitialTransferSize` matching your `MaximumTransferSize`, and making the theorized fix with a stream buffer like with downloads is making zero impact for me.

Could you please share more about the source of your uploads for these tests? Is it a file stream? Network stream? Are your four parallel tests all reading from the same source? Sync/async? Exactly what API are you calling?

**Comment by jeffhli** [comment] 2022-04-08 04:10
@jaschrep-msft I upload blobs with Network stream. The client is JMeter and our service receives the requests from jmeter then upload the stream to the azure cloud using `BlockBlobClient.UploadAsync' method.

**Comment by jaschrep-msft** [comment] 2022-04-08 16:50
That explains so much and lines up with the cause of the download issue. I will adjust my tests to confirm with this setup and apply appropriate fixes if all succeeds.

**Comment by jaschrep-msft** [comment] 2022-04-08 19:52
I'm very much struggling to reproduce your CPU differences. I always get ~30% cpu, similar to your first test, and I replicate your operation times. If there's something specific about how you obtain your network stream that you can share sample code for then I can try again later with that. Otherwise I can't verify the problem in the first place to confirm a fix.

**Comment by jeffhli** [comment] 2022-04-11 10:28
@jaschrep-msft The service is deployed on Azure Kubernetes cluster, and the memory and cpu you see in the picture are collected from newrelic.

**Comment by jaschrep-msft** [comment] 2022-08-02 14:26
This thread surfaced information about upload behavior and led to performance investigations that were carried through. It did not have an initial problem that required solving. Closing.

**Closed by jaschrep-msft** 2022-08-02 14:26 UTC
Labels: Storage, Service Attention, Client, customer-reported, bug, needs-team-attention
