### ISSUE TITLE
[FEATURE REQ] Conditional package references for Azure.Identity

### ISSUE THREAD

**Issue by thompson-tomo** [Azure/azure-sdk-for-net#41629] opened 2024-01-27 08:54 UTC
### Library name

Azure.Identity

### Please describe the feature.

I want package references to be framework specific so that i am not adding in un-necessary packages when functionality can be and should be provided by the framework reference. An example of such is System.Text.Json which is included in net 6

**Comment by jsquire** [comment] 2024-01-27 16:31
Hi @thompson-tomo.   Thank you for reaching out and we regret that you're experiencing difficulties.  As this is something that we'd look to correct for all packages, I'm going to mark this issue as a duplicate of #41628 and close it out so that we can focus discussion in one place.

**Closed by jsquire** 2024-01-27 16:31 UTC
Labels: Client, EngSys, customer-reported, question, duplicate
