### ISSUE TITLE
[BUG] Intermittent failure in test proxy

### ISSUE THREAD

**Issue by archerzz** [Azure/azure-sdk-for-net#37849] opened 2023-07-26 07:08 UTC
### Library name and version

Azure.Core.TestFramework

### Describe the bug

See [this PR](https://github.com/Azure/cadl-ranch/pull/381) which only updates `autorest.csharp` and doesn't carry over any code change. Its corresponding [build pipeline](https://dev.azure.com/azure-sdk/public/_build/results?buildId=2945079&view=results) failed intermittently.

Here is the error in the [first attempt](https://dev.azure.com/azure-sdk/public/_build/results?buildId=2945079&view=logs&j=f8ff1b27-46db-541d-ba02-bbc74be6cafb&s=6884a131-87da-5381-61f3-d7acc3b91d76&t=fa92498a-7d90-581b-e77a-de56667dc45c&l=227818). It appeared in every failed test case.
```
Error Message:
   Azure.RequestFailedException : Service request failed.
Status: 400 (Bad Request)

Content:
{"Message":"Unable to parse the line taLake_369e19e7ec","Status":"BadRequest"}
```

After re-trying 2 times, the pipeline passed without error.

### Expected behavior

There should not be intermittent failure in test proxy.

### Actual behavior

Intermittent failure appears in test runs. It can be eliminated after several re-try.

### Reproduction Steps

Run the pipeline, check the result. The error will go away after retrying several times.

**Comment by archerzz** [comment] 2023-07-26 07:50
Several users have reported similar issues. Like this: https://github.com/Azure/azure-sdk-for-net/pull/37490

**Comment by jsquire** [comment] 2023-07-26 13:45
@JoshLove-msft :  Would you take a look please?

**Comment by JoshLove-msft** [comment] 2023-07-26 17:33
This is a duplicate of https://github.com/Azure/azure-sdk-tools/issues/6562

**Closed by JoshLove-msft** 2023-07-26 17:33 UTC
Labels: Client, Azure.Core.TestFramework
