### ISSUE TITLE
Remove README exclusions for support packages

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-for-net#15423] opened 2020-09-24 19:55 UTC
Once Azure/azure-sdk-tools#404 is resolved, do whatever configuration is necessary and remove exclusions from eng/.docsettings.yml:

```yaml
  - ['sdk/core/Microsoft.Azure.Core.NewtonsoftJson/README.md', '#15423']
  - ['sdk/search/Microsoft.Spatial.NewtonsoftJson/README.md', '#15423']
```

**Comment by annelo-msft** [comment] 2021-12-15 18:33
Duplicate of: https://github.com/Azure/azure-sdk-for-net/issues/5499

**Closed by annelo-msft** 2021-12-15 18:33 UTC
Labels: Search, Client, test-reliability
