### ISSUE TITLE
[BUG] Insight alert resources with no tags throw exception during deserialization

### ISSUE THREAD

**Issue by jamesstanleystewart** [Azure/azure-sdk-for-net#26182] opened 2022-01-06 04:02 UTC
### Library name and version

Azure.ResourceManager.Insights 1.0.0-preview.1

### Describe the bug

Exception is thrown in `DeserializeActionGroupResource` when calling `property.Value.EnumerateObject()` for tag deserialization.

The error thrown is: `The requested operation requires an element of type 'Object', but the target element has type 'Null'.`

This also happens for ActivityLogAlertResource.Tags and ActivityLogAlertResource.Actions.ActionGroups.WebhookProperties.

### Expected behavior

An empty tags dictionary should be returned rather than null, or the null should be treated as an empty dictionary

### Actual behavior

Exception is thrown

### Reproduction Steps

This code throws
```csharp
            var insightsClient = new InsightsManagementClient("SUB", new DefaultAzureCredential());

            var actionGroup = new ActionGroupResource("global") {
                GroupShortName = "name",
                EmailReceivers = {
                    new EmailReceiver("name", "a@b.c", true)
                },
                Enabled = true
            };
            
            await insightsClient.ActionGroups.CreateOrUpdateAsync("RG", "alert-test", actionGroup);
```

Workaround: add a tag before creation `actionGroup.Tags.Add("a", "a");`

### Environment

Windows, Dotnet Core 6, Rider IDE

**Comment by jsquire** [comment] 2022-01-06 13:07
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by ArthurMa1978** [comment] 2022-01-11 07:14
We made big changes after the preview sdk, but @HarveyLink please help to check how will it be in new sdk.

**Comment by HarveyLink** [comment] 2022-01-11 09:21
@jamesstanleystewart The issue is fixed in new sdk, it will release to support.

**Comment by jamesstanleystewart** [comment] 2022-01-11 19:21
Thanks all, @HarveyLink when will the next version release?

**Comment by HarveyLink** [comment] 2022-01-17 07:35
> Thanks all, @HarveyLink when will the next version release?

Will release before end of this week.

**Comment by HarveyLink** [comment] 2022-06-24 08:40
@jamesstanleystewart  Monitor SDK has been released, please check: https://www.nuget.org/packages/Azure.ResourceManager.Monitor/1.0.0-beta.2

**Closed by HarveyLink** 2022-06-24 08:40 UTC
Labels: Insights, Mgmt, customer-reported, question, needs-team-attention

**Comment by lucasfsvilela** [comment] 2023-01-19 11:22
Isn't InsightsManagementClient part of Azure.ResourceManager.Insights v1.0.0-preview.1 ? I cannot find it at Azure.ResourceManager.Monitor.

**Comment by HarveyLink** [comment] 2023-01-20 01:10
> Isn't InsightsManagementClient part of Azure.ResourceManager.Insights v1.0.0-preview.1 ? I cannot find it at Azure.ResourceManager.Monitor.

The ManagementClient design has been deprecated in new sdk. 
You could refer to those [samples](https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/monitor/Azure.ResourceManager.Monitor/samples/Generated/Samples) to get what you need in new sdk.
If further help is needed, you could open a new issue.
