### ISSUE TITLE
[BUG] GenerateSasUri does not honor  TrimBlobNameSlashes settings while creating SAS URI for the blob. 

### ISSUE THREAD

**Issue by jikuma** [Azure/azure-sdk-for-net#34591] opened 2023-02-28 02:25 UTC
### Library name and version

Azure.Storage.Blobs 12.15.0

### Describe the bug

While generating a SAS URI for the path https://blolbsasurobugdemo.blob.core.windows.net/democontianer//test/file the URI is getting converted to 
https://blolbsasurobugdemo.blob.core.windows.net/democontianer/test/file

Notice that directory with no name is removed. Sample SAS uri looks like 

> https://blolbsasurobugdemo.blob.core.windows.net/democontianer/test/file?sv=2021-12-02&spr=https&st=2023-02-28T02%3A11%3A18Z&se=2023-02-28T02%3A21%3A17Z&sr=b&sp=r&sig="REDACTED"

My code to generate the SAS URI is

```
using Azure.Storage.Blobs;
using Azure.Storage.Sas;

namespace BlobSASGenerator
{
    class Program
    {
        static void Main(string[] args)
        {
            if (args.Length != 3)
            {
                throw new InvalidOperationException("Sample  usecase BlobSASGenerator.exe <connection string> <containerName> <blobName>");
            }

            // Update the values below with your own storage account information and blob details
            string connectionString = args[0];
            string containerName = args[1];
            string blobName = args[2];

            // Create a BlobServiceClient object from the connection string
            BlobServiceClient blobServiceClient = new BlobServiceClient(connectionString, new BlobClientOptions() { TrimBlobNameSlashes = false }); ;

            // Get a reference to the container
            BlobContainerClient containerClient = blobServiceClient.GetBlobContainerClient(containerName);

            // Get a reference to the blob
            BlobClient blobClient = containerClient.GetBlobClient(blobName);


            // Set the expiration time for the SAS token (in this case, 1 hour from now)
            DateTimeOffset sasExpirationTime = DateTimeOffset.UtcNow.AddMinutes(5);

            // Define the permissions you want to grant to clients accessing the SAS URI
            BlobSasBuilder sasBuilder = new BlobSasBuilder()
            {
                BlobContainerName = containerName,
                BlobName = blobName,
                ExpiresOn = sasExpirationTime,
                Protocol = SasProtocol.Https,
                StartsOn = DateTimeOffset.UtcNow.Subtract(TimeSpan.FromMinutes(5)),
                Resource = "b"
            };

            // Set the permissions to allow read access to the blob
            sasBuilder.SetPermissions(BlobSasPermissions.Read);

            // Generate the SAS URI
            Uri sasUri = blobClient.GenerateSasUri(sasBuilder);

            // Output the SAS URI to the console
            Console.WriteLine($"SAS URI for blob '{blobName}': {sasUri}");
        }
    }
}

````

I create the blob with URI 

https://blolbsasurobugdemo.blob.core.windows.net/democontianer//test/file

If I do 

> curl "https://blolbsasurobugdemo.blob.core.windows.net/democontianer/test/file?sv=2021-12-02&spr=https&st=2023-02-28T02%3A11%3A18Z&se=2023-02-28T02%3A21%3A17Z&sr=b&sp=r&sig=f60142Ml5aTlWfiCOgvb05WLtJmiPN1cbadlWSP66HY%3D"

I get below error

> </Message><AuthenticationErrorDetail>Signature did not match.

If I fix the URL in the SAS URI it works. So the below commad works.

> curl "https://blolbsasurobugdemo.blob.core.windows.net/democontianer//test/file?sv=2021-12-02&spr=https&st=2023-02-28T02%3A11%3A18Z&se=2023-02-28T02%3A21%3A17Z&sr=b&sp=r&sig=f60142Ml5aTlWfiCOgvb05WLtJmiPN1cbadlWSP66HY%3D"

### Expected behavior

Returns correct SAS URI with "no name" directory as two slashes. 

https://blolbsasurobugdemo.blob.core.windows.net/**democontianer//test**/file?sv=2021-12-02&spr=https&st=2023-02-28T02%3A11%3A18Z&se=2023-02-28T02%3A21%3A17Z&sr=b&sp=r&sig=f60142Ml5aTlWfiCOgvb05WLtJmiPN1cbadlWSP66HY%3D

### Actual behavior

Directory with no name is trimmed

https://blolbsasurobugdemo.blob.core.windows.net/**democontianer/test**/file?sv=2021-12-02&spr=https&st=2023-02-28T02%3A11%3A18Z&se=2023-02-28T02%3A21%3A17Z&sr=b&sp=r&sig=f60142Ml5aTlWfiCOgvb05WLtJmiPN1cbadlWSP66HY%3D

### Reproduction Steps

Create a blob inside directory with no name. Ans use below code to generate SAS URI.

```
using Azure.Storage.Blobs;
using Azure.Storage.Sas;

namespace BlobSASGenerator
{
    class Program
    {
        static void Main(string[] args)
        {
            if (args.Length != 3)
            {
                throw new InvalidOperationException("Sample  usecase BlobSASGenerator.exe <connection string> <containerName> <blobName>");
            }

            // Update the values below with your own storage account information and blob details
            string connectionString = args[0];
            string containerName = args[1];
            string blobName = args[2];

            // Create a BlobServiceClient object from the connection string
            BlobServiceClient blobServiceClient = new BlobServiceClient(connectionString, new BlobClientOptions() { TrimBlobNameSlashes = false }); ;

            // Get a reference to the container
            BlobContainerClient containerClient = blobServiceClient.GetBlobContainerClient(containerName);

            // Get a reference to the blob
            BlobClient blobClient = containerClient.GetBlobClient(blobName);


            // Set the expiration time for the SAS token (in this case, 1 hour from now)
            DateTimeOffset sasExpirationTime = DateTimeOffset.UtcNow.AddMinutes(5);

            // Define the permissions you want to grant to clients accessing the SAS URI
            BlobSasBuilder sasBuilder = new BlobSasBuilder()
            {
                BlobContainerName = containerName,
                BlobName = blobName,
                ExpiresOn = sasExpirationTime,
                Protocol = SasProtocol.Https,
                StartsOn = DateTimeOffset.UtcNow.Subtract(TimeSpan.FromMinutes(5)),
                Resource = "b"
            };

            // Set the permissions to allow read access to the blob
            sasBuilder.SetPermissions(BlobSasPermissions.Read);

            // Generate the SAS URI
            Uri sasUri = blobClient.GenerateSasUri(sasBuilder);

            // Output the SAS URI to the console
            Console.WriteLine($"SAS URI for blob '{blobName}': {sasUri}");
        }
    }
}
```

### Environment

Dotnet 6.0

**Comment by navba-MSFT** [comment] 2023-03-01 03:06
@jikuma Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment] 2023-03-01 06:35
@jikuma Firstly, there is no concept of Directory (folder) in the Blob Storage, since Blob Storage follows a flat structure. You should [**_enable Hierarchal Namespace_**](https://learn.microsoft.com/en-us/azure/storage/blobs/upgrade-to-data-lake-storage-gen2-how-to?tabs=azure-portal) on your Azure Storage Account and Upgrade this to a Datalake Storage Account. This will provide the File System Semantics on your Storage account. You will then be able to set the SAS at the directory level (test/file).

In a storage account, with a hierarchical namespace enabled, you can create a service SAS for a directory. To create the service SAS, make sure you have installed version 12.5.0 or later of the [Azure.Storage.Files.DataLake](https://www.nuget.org/packages/Azure.Storage.Files.DataLake/) package.

[Here ](https://learn.microsoft.com/en-us/azure/storage/blobs/sas-service-create?tabs=dotnet#create-a-service-sas-for-a-directory)is the sample code to achieve your requirement.

**Comment by jikuma** [comment] 2023-03-03 00:16
@navba-MSFT using "directory" term in the explanation might be confusing. We have a lot of storage accounts and upgrading them is a considerable effort. Let me refrase my problem

I have blob https://blolbsasurobugdemo.blob.core.windows.net/democontianer//test/file 

This is a valid blolb as I can browse the blobl from azure portal and also generate a SAS URI. When I generate a sas URI from the portal it preserves the two slashes in the blob name. It look somthing like 

> https://blolbsasurobugdemo.blob.core.windows.net/democontianer//test/file?sp=r&st=2023-03-03T00:12:13Z&se=2023-03-04T00:15:13Z&spr=https&sv=2021-12-02&sr=b&sig=x1X8iyZEVFVIxu9ok1V%2FwnASFQue2lEZs%2BjHkBprm%2BY%3D

Notice the two slashes before test/file in the URI.

Now I use the blob client to generate the SAS URI I get something like

> https://blolbsasurobugdemo.blob.core.windows.net/democontianer/test/file?sv=2021-12-02&spr=https&st=2023-02-28T02%3A11%3A18Z&se=2023-02-28T02%3A21%3A17Z&sr=b&sp=r&sig=f60142Ml5aTlWfiCOgvb05WLtJmiPN1cbadlWSP66HY%3D

Notice the two slashes in the blob name is trimmed, even though in the sample code I shared earlier you can see I have set TrimBlobNameSlashes  flag as false.

**Comment by navba-MSFT** [comment] 2023-03-03 08:45
@jikuma Thanks for clarifying the ask. I am able to reproduce this issue at my end.

@amnguye @seanmcc-msft Is this an expected behavior ? Do you have any pointers to workaround this issue ?

**Comment by amnguye** [comment] 2023-03-06 22:15
Looks like while implementing TrimBlobNameSlashes we forgot to propagate down the TrimBlobNameSlashes value down the to the `BlobUriBuilder` when the feature was introduced.

Here's the bug:
https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/storage/Azure.Storage.Blobs/src/BlobBaseClient.cs#L6668

Mitigations that can be taken as the fix is being made is either to.
1. Trim the blob names slashes on ]the Uri contained in the BlobClient so that when the SAS is generated the SAS is valid
2.  Manually generate the SAS with the Uri with the slashes.
```
            BlobUriBuilder sasUri = new BlobUriBuilder(BlobUri, false)
            {
                Sas = builder.ToSasQueryParameters(<SharedKeyCredential>)
            };
            return sasUri.ToUri();
```

relabeled as a bug and will resolve the bug once the fix is in.

**Closed** 2023-03-08 18:43 UTC
Labels: Storage, Service Attention, Client, customer-reported, bug, needs-team-attention
