### ISSUE TITLE
Broken link on Azure github landing page

### ISSUE THREAD

**Issue by cdfwork** [Azure/azure-sdk-for-net#4225] opened 2018-04-16 05:36 UTC
The link at the top of this github page (/Azure/azure-sdk-for-net) is broken.  Link is "https://www.visualstudio.com/features/azure-tools-vs" and is a 404.

**Comment by shahabhijeet** [comment] 2018-05-24 05:50
Dupe of #4200

**Closed** 2018-05-24 05:50 UTC
Labels: Team
