### ISSUE TITLE
[BUG] [Service Bus] Can't create session when the connection is closing

### ISSUE THREAD

**Issue by Mortana89** [Azure/azure-sdk-for-net#11066] opened 2020-04-06 11:37 UTC
**Describe the bug**
We get like constant errors (100dreds per hour) in our debugger console and AI about service bus.
One of them is an InvalidOperationException:
Can't create session when the connection is closing.

This is happening when using the built-in message pump mechanism. This message pump uses the following code:

```
 async Task SessionPumpTaskAsync()
        {
            while (!this.pumpCancellationToken.IsCancellationRequested)
            {
                var concurrentSessionSemaphoreAcquired = false;
                try
                {
                    await this.maxConcurrentSessionsSemaphoreSlim.WaitAsync(this.pumpCancellationToken).ConfigureAwait(false);
                    concurrentSessionSemaphoreAcquired = true;

                    await this.maxPendingAcceptSessionsSemaphoreSlim.WaitAsync(this.pumpCancellationToken).ConfigureAwait(false);

// THIS LINE THROWS THE ERROR
                    var session = await this.client.AcceptMessageSessionAsync().ConfigureAwait(false);
                    if (session == null)
                    {
                        await Task.Delay(Constants.NoMessageBackoffTimeSpan, this.pumpCancellationToken).ConfigureAwait(false);
                        continue;
                    }

```
When breaking on that exception, I can see the client's 'IsClosedOrClosing' property is false, while the exception says otherwise:
![image](https://user-images.githubusercontent.com/45714001/78554542-9ea7ec80-780b-11ea-9d16-90502ab67d0a.png)

However, when going deeper, in the SessionClient.AcceptMessageSessionAsync, I can see that the session is closed/closing;
![image](https://user-images.githubusercontent.com/45714001/78554861-34dc1280-780c-11ea-8bbd-6700d9d5031f.png)

Using .NET Core 3.1, and Microsoft.Azure.ServiceBus 4.1.2 version.

**Comment by nemakam** [comment] 2020-04-06 21:22
Duplicate of #9416.

**Comment by nemakam** [comment] 2020-04-06 21:27
@Mortana89 
Are you closing the queueClient/subClient when you get this exception?

**Comment by nemakam** [comment] 2020-04-06 21:30
I'm going to close this issue. Please respond back in the original thread to have a single place for tracking purposes

**Closed by nemakam** 2020-04-06 21:30 UTC
Labels: Client, Service Attention, Service Bus, customer-reported, question
