### ISSUE TITLE
How To Catch Service Bus Connection Retries & Handle Them

### ISSUE THREAD

**Issue by ian-msft** [Azure/azure-sdk-for-net#39733] opened 2023-11-03 16:03 UTC
### Library name and version

Azure.Messaging.ServiceBus 7.16.2
Microsoft.Extensions.Azure 1.7.1

### Query/Question

When my .NET 7 worker service application can not connect to a service bus instance, I want to catch the error, and deal with it /exit. I see an error in the logs:

> [ERR] ErrorHandler invoked with ErrorSource: Receive, FullyQualifiedNamespace: EntityPath, Exception: Azure.Messaging.ServiceBus.ServiceBusException: The requested name is valid, but no data o...

However, no exception is thrown to my code, or I do not know how/where to catch it. And Azure.Messaging.ServiceBus seems to just keep retrying this endlessly instead of exiting:

> [WRN] RunOperation encountered an exception and will retry. Exception: Azure.Messaging.ServiceBus.ServiceBusException: The requested name is valid, but no data of the requested type was found. ErrorCode: NoData (ServiceCommunicationProblem).

I can not find where these logs come from, and I can not intercept/catch the exception.

Question: how can I make my application recognize that this is happening, throw an exception and exit when it can not connect to service bus / when the above happens?

**Implementation details:**

In my application I configure a worker, and my ServiceBusClient in program.cs as follows:

```
services.AddHostedService<ServiceBusWorker>();
services.AddAzureClients(clientsBuilder =>
{
    clientsBuilder.AddServiceBusClient(serviceBusConfiguration?.ConnectionString)
      .WithName(serviceBusConfiguration?.MyQueue);
});
```
Then in my worker I construct as follows::

using Azure.Messaging.ServiceBus;

public ServiceBusWorker(IAzureClientFactory<ServiceBusClient> serviceBusClientFactory)
{
    _serviceBusClientFactory = serviceBusClientFactory;

    var connectionString = serviceBusConfiguration.Value.ConnectionString;

    _requestQueueClient = _serviceBusClientFactory.CreateClient(_requestQueue);
And the worker starts as follows:

```
public async Task StartAsync(CancellationToken cancellationToken)
{
    try
    {
        await using var requestProcessor = _requestQueueClient.CreateProcessor(_requestQueue, _serviceBusProcessorOptions);

        // configure the message and error handler to use
        requestProcessor.ProcessMessageAsync += ProcessMessageAsync;
        requestProcessor.ProcessErrorAsync += ErrorHandler;

        await requestProcessor.StartProcessingAsync(cancellationToken);

        await Task.Delay(-1, cancellationToken); 
    }
    catch (Exception ex)
    {
        _logger.LogError(ex, "Error when starting the request processor");
        throw;
    }
}
```
What I tried

I have tried to configure a retry policy in program.cs as follows, but it doesn't make a difference, I assume because it relates to message retries and not my scenario of failed connection:
```

services.AddAzureClients(clientsBuilder =>
{
    **var serviceBusRetryOptions = new ServiceBusRetryOptions
    {
        MaxRetries = 3,
        Delay = TimeSpan.FromSeconds(2),
        TryTimeout = TimeSpan.FromSeconds(30)
    };**

clientsBuilder
.AddServiceBusClient(serviceBusConfiguration?.ConnectionString)
.ConfigureOptions(options =>
    {
        options.RetryOptions = serviceBusRetryOptions;
    })
.WithName(serviceBusConfiguration?.RequestQueue);

clientsBuilder
.AddServiceBusClient(serviceBusConfiguration?.ConnectionString)
.ConfigureOptions(options =>
    {
        options.RetryOptions = serviceBusRetryOptions;
    })
.WithName(serviceBusConfiguration?.ResponseQueue);
});
```

### Environment

Windows, .NET7. Visual Studio Version 17.7.6

dotnet --info
.NET SDK:
 Version:   8.0.100-preview.3.23178.7
 Commit:    e300b0e1e6

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22621
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.100-preview.3.23178.7\

.NET workloads installed:
There are no installed workloads to display.

Host:
  Version:      8.0.0-preview.3.23174.8
  Architecture: x64
  Commit:       47bad717bd

.NET SDKs installed:
  6.0.319 [C:\Program Files\dotnet\sdk]
  6.0.416 [C:\Program Files\dotnet\sdk]
  7.0.403 [C:\Program Files\dotnet\sdk]
  8.0.100-preview.3.23178.7 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.24 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.0-preview.3.23177.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.24 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.0-preview.3.23174.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.24 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.0-preview.3.23178.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

**Comment by m-redding** [comment] 2023-11-03 17:31
Thank you for your feedback. Tagging and routing to the team member best able to assist.

**Comment by JoshLove-msft** [comment] 2023-11-05 18:15
Hi @ian-msft, thanks for submitting this issue. I am going to close it as a duplicate of https://github.com/Azure/azure-sdk-for-net/issues/31648. Please feel free to comment there or upvote that issue.

**Closed by JoshLove-msft** 2023-11-05 18:15 UTC
Labels: Service Bus, Client, customer-reported, question, needs-team-attention
