### ISSUE TITLE
ServiceBusSender Identifier not set.

### ISSUE THREAD

**Issue by woodylaurence** [Azure/azure-sdk-for-net#46952] opened 2024-11-01 21:51 UTC
### Library name and version

Azure.Messaging.ServiceBus v7.18.0+

### Describe the bug

When creating a ServiceBusSender using ServiceBusClient.CreateSender(<queueOrTopicName>) the returned Sender does not have its Identifier correctly set based off the queue/topic name.
This used to work < 7.18.0.

### Expected behavior

ServiceBusClient.CreateSender(<queueOrTopicName>) should return ServiceBusSender with Identifier set as <queueOrTopicName>-<guid>.

### Actual behavior

Identifier is set as "-<guid>".

### Reproduction Steps

```c#
using Azure.Identity;
using Azure.Messaging.ServiceBus;

namespace ConsoleApp1;

class Program
{
	static void Main(string[] args)
	{
		var serviceBusClient = new ServiceBusClient("service-bus-name.servicebus.windows.net", new DefaultAzureCredential());
		var serviceBusSender = serviceBusClient.CreateSender("queue-name");
	}
}
```

**Comment by jsquire** [comment] 2024-11-01 22:51
Hi @woodylaurence.   Thanks for reaching out and we regret that you're experiencing difficulties.   Confirming that this is a bug that was introduced [this commit](https://github.com/Azure/azure-sdk-for-net/commit/9571e4fe19203b92e6dab454f6f4c3d78ece4c9a#diff-b9dba4e05b9f557d43eb7e47749f16d5a24a5ad1d8abab926cc5f5cae7046ffc), which changed the flow where the identifier is being created.   The code should have been updated to use the `entityPath` parameter instead of `EntityPath` property, which is not yet initialized.   Looks like `ServiceBusClient` is also impacted.   We'll get this fixed up and hope to have it available for our next release in early January.   

In the meantime, mitigation would be to use the options to explicitly set an identifier.  The following will restore the intended behavior:

```csharp
await using var client = new ServiceBusClient"<< Fully Qualified Namespace >>", new DefaultAzureCredential());

var entityPath = "myQueue";
var options = new ServiceBusSenderOptions { Identifier = $"{entityPath}-{Guid.NewGuid()}" };
var sender = client.CreateSender(entityPath, options);
```

**Comment by woodylaurence** [comment] 2024-11-08 11:36
Thanks @jsquire !

Solution will work for us for now and will keep an eye out for the release so that we can revert the temporary fix.

**Comment by jsquire** [comment] 2024-11-27 00:02
fixed by #47346

**Comment by jsquire** [comment] 2024-12-04 16:54
The fix has been merged and will be included in our January release.

**Closed** 2024-12-11 22:37 UTC
Labels: Service Bus, Client, customer-reported, bug, issue-addressed
