### ISSUE TITLE
PartitionReceiver.ReceiveBatchAsync retrieves single event

### ISSUE THREAD

**Issue by jackbond** [Azure/azure-sdk-for-net#15790] opened 2020-10-08 16:18 UTC
I'm using PartitionReceiver from the Azure.Messaging.EventHubs NuGet library and am calling ReceiveBatchAsync with maxEventCount set to 200, and maximumWaitTime to 15 seconds. My telemetry is showing me that I'm repeatedly receiving batches with 1 event after less than a second.

**Expected behavior**
Receive batches up to 200 events after up to 15 seconds

**Actual behavior (include Exception or Stack Trace)**
Receive 1 event after less than a second

**To Reproduce**
```
PartitionReceiverOptions partitionReceiverOptions = new PartitionReceiverOptions
{
    ConnectionOptions = new EventHubConnectionOptions
    {
        TransportType = EventHubsTransportType.AmqpTcp,
    },
    PrefetchCount = 200
};

EventPosition eventPosition = EventPosition.FromSequenceNumber(_LastEventSequenceNumber, false);

_PartitionReceiver = new PartitionReceiver(
    consumerGroup: EventHubConsumerClient.DefaultConsumerGroupName,
    partitionId: _Partition.PartitionId,
    eventPosition: eventPosition,
    connectionString: eventHubConnectionString,
    eventHubName: _Partition.Path,
    options: partitionReceiverOptions);

IEnumerable<EventData> batch = await _PartitionReceiver.ReceiveBatchAsync(
    ReceiveBatchSize,
    TimeSpan.FromSeconds(15),
    _CancellationToken).ConfigureAwait(false);
```

**Environment:**

Azure.Messaging.EventHubs 5.2.0
.netcore

**Comment by jsquire** [comment] 2020-10-08 20:00
Hi @jackbond.  Thank you for reaching out and we regret that you're experiencing difficulties.   I'm not able to reproduce the behavior that you're describing and would appreciate if you could offer a bit more context around your snippet.

In the snippet,  I don't see an indication of how the member `ReceiveBatchSize` is set.   Can you include a bit more context in the snippet to help me better understand what that value is when it's passed in?  Given your description, I wonder if that is not being populated and there's a misunderstanding of the `PrefetchCount` option.   

If we end up determining that `ReceiveBatchSize` is populated, would you be willing to collect some ETW logs using our [`AzureEventListener`](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/core/Azure.Core/samples/Diagnostics.md#logging) to help provide some deeper insight into what the `PartitionReceiver` is seeing internally?

**Comment by jackbond** [comment] 2020-10-08 20:11
Sorry ReceiveBatchSize is a constant int = 200. Meant to change that in my snippet.

More than happy to help collect log info. Currently we're writing trace telemetries to Application Insights. We see this behavior with our code running within Service Fabric. I looked briefly at the AzureEventListener link, can you provide more info on how you would like it configured? I've got my own cluster, so I can setup the receiver however you'd like.

**Comment by jsquire** [comment] 2020-10-08 20:38
Thank you for the additional context, and for your willingness to capture logs.  It would definitely seem that your parameters are reasonable, though having prefetch be roughly 3 times your batch size is recommended for better throughput.  I'd normally ask about how many events are flowing through the partition, but low volume should result in you seeing a delay of ~15 seconds and then a small number of events.

For the ETW logs, what we're after is the flow through [`AmqpConsumer::ReceiveAsync`](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/eventhub/Azure.Messaging.EventHubs/src/Amqp/AmqpConsumer.cs#L197), which is instrumented using the [`EventHubsEventSource`](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/eventhub/Azure.Messaging.EventHubs/src/Amqp/AmqpConsumer.cs#L197) members with ids of 6, 7, and 8.  Those would have levels of `Informational` and `Error` .

The easiest way to screen out the noise would be to have the [`log`](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/core/Azure.Core/src/Diagnostics/AzureEventSourceListener.cs#L37) delegate that you pass the listener filter by [`EventWrittenEventArgs.EventSource`](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.tracing.eventwritteneventargs.eventsource?view=netcore-3.1)  equal `"Azure-Messaging-EventHubs"` and [`EventWrittenEventArgs.EventId`](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.tracing.eventwritteneventargs.eventid?view=netcore-3.1)  equal `6 | 7 | 8`.  So that we catch anything unexpected, it would also be helpful to grab anything with an [`EventWrittenEventArgs.Level`](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.tracing.eventwritteneventargs.level?view=netcore-3.1) of `EventLevel.Error`  - just in case.

Anything else that you think may be interesting about your Event Hubs resource would also be appreciated so that I can try a few more things for local repro.  The number of partitions, estimated size of events, and how many receivers you have listening may prove insightful.

**Comment by jsquire** [comment] 2020-10-08 21:43
Just a quick note that I think that I have local repro and am now seeing behavior similar to what you describe.    We probably don't need to burden you with gathering logs at this point.   I'll dig in a bit and report back once I have a better understanding.

**Comment by jackbond** [comment] 2020-10-08 23:44
Awesome. Funny thing is, I'm pretty sure I've seen this behavior for ages(including older with older NuGets). Just got tired of seeing so many telemetry messages (1 for every batch.)

**Comment by jackbond** [comment] 2020-10-09 18:33
If you guys have never seen this, do you believe the behavior would go away if we tweaked the PrefetchCount to maxevents ratio? Just curious if there's a quick workaround.

**Comment by jsquire** [comment] 2020-10-09 21:52
Hi @jackbond.   I spent some time digging through this today, testing across the different generations of Event Hubs client libraries.   Ultimately, the behavior is consistent between them and can be back to the underlying AMQP library that we use for communication with the service.  After discussing a bit with the folks that own the library, I think that I understand the disconnect.

The notion of `waitTime` has misleading or missing documentation, both internal and external across the different sources, and  tribal knowledge was also inconsistent.  At the end of the day, it doesn't quite work the way that you and I believe that it should.  The difference stems from how the prefetch queue is managed.   The semantics can be expressed as: 

_“Wait for `XX` time to build up a batch, if there are no messages in the prefetch queue.   When messages are available in prefetch, whether we just requested them or they were already cached, return whatever we have immediately without waiting to satisfy the requested batch size.”_   

As you mentioned, adjusting the `PrefetchCount` can potentially help ensure that have full batches.   The thing to be aware of is that the prefetch will fill up gradually, so if your processing is very light and fast and the prefetch hasn't had a chance to fill, you'll still see dribbles.   However, if you have a large enough prefetch and each call to `ReceiveAsync` uses a batch size that doesn't drain it, you'll see more consistently full batches.  

That, by the way, is why my initial attempts at repro failed; I was tweaking an existing test that had a warmed prefetch cache.  When I shifted to a new, stripped down, testing scenario is when I was able to reproduce.   It's difficult to give general advice on the tweaking of prefetch and batch sizes, as it depends heavily on the size of events, the frequency of publishing, and the application.   Generally speaking, we typically recommend that the prefetch be at least 3 times the size of the batch - though if you're processing large events or dispatching quickly, you'll probably want to use a bigger ratio.   

I've got a some changes in flight to clarify the documentation around semantics and make things more clear.   Thanks for calling this out.

**Comment by jackbond** [comment] 2020-10-10 19:53
I know that you guys have just learned of this issue, but do you have a guess in regards to how you plan to address it? Do you plan to make changes such that the actual ReceiveBatchAsync behavior matches the documentation, i.e. it will actually wait until either maximumWaitCount or maximumWaitTime is satisfied?

**Comment by jsquire** [comment] 2020-10-12 14:42
Unfortunately, though I find it unintuitive and misleading, this is the "by-design" behavior of the AMQP transport library.  I've [updated](https://github.com/Azure/azure-sdk-for-net/pull/15843) the documentation to clarify the behavior for callers.  

The `PartitionReceiver` is intended to be the thinnest possible wrapper over the transport and not introduce additional overhead.  It also serves the purpose of mirroring a type from the previous generation of the library used for more advanced scenarios.  We don't feel that it is appropriate to introduce an additional batching layer in the client, as that would both add overhead and change behavior.

**Comment by jsquire** [comment] 2020-10-15 17:25
Hi @jackbond.  It looks like the discussion has tapered off and I've merged the associated doc updates.  I'm going to close this out;  please feel free to reopen if you'd like to discuss further.

**Closed by jsquire** 2020-10-15 17:25 UTC
Labels: Client, Event Hubs, customer-reported, needs-author-feedback, question
