### ISSUE TITLE
Azure.Identity not able to retrieve token in an Azure Arc-Enabled server

### ISSUE THREAD

**Issue by rajagopalan-trimble** [Azure/azure-sdk-for-net#41657] opened 2024-01-30 07:22 UTC
### Library name and version

Azure.Identity 1.10.0

### Describe the bug

I have added an ec2 instance as Azure Arc-enabled server and tried to access the resource groups in my subscription using the Azure.Identity and Azure.Resource.Manager libraries but I get an error as 404 not found.

```c#
using System.Threading.Tasks;
using Azure.Core;
using Azure.Identity;
using Azure.ResourceManager;
using Azure.ResourceManager.Resources;
using Azure.Security.KeyVault.Secrets;

try
{
    ArmClient client = new ArmClient(new DefaultAzureCredential());
    string resourceGroupName = "xxxxxxx";
    SubscriptionResource subscription = await client.GetDefaultSubscriptionAsync();
    ResourceGroupCollection resourceGroups = subscription.GetResourceGroups();
    ResourceGroupResource resourceGroup = await resourceGroups.GetAsync(resourceGroupName);
    Console.WriteLine(resourceGroup);
}
catch(Exception ex)
{
    Console.WriteLine(ex.ToString());
}
```
I believe the IDMS endpoint that it refers in an Azure VM is 'http://169.254.169.254/metadata/identity/oauth2/token?api-version=2018-02-01&resource=https://management.azure.com/' and that the URL referred in an Azure Arc-Enabled server is 'http://127.0.0.1:40342/metadata/identity/oauth2/token?api-version=2019-11-01&resource=https%3A%2F%2Fmanagement.azure.com' and the SDK is not able to fetch the latter.

### Expected behavior

Get the token using the system-assigned Managed Identity and get the resource group details.

### Actual behavior
```
Azure.Identity.AuthenticationFailedException: ManagedIdentityCredential authentication failed: Service request failed.
Status: 404 (Not Found)

Content:
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
                 "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
 <head>
  <title>404 - Not Found</title>
 </head>
 <body>
  <h1>404 - Not Found</h1>
 </body>
</html>
```
### Reproduction Steps

Onboard a server in Azure Arc and run the given code.

### Environment

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  22.04
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /usr/share/dotnet/sdk/8.0.101/

.NET SDKs installed:
  8.0.101 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 8.0.1 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 8.0.1 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

**Comment by jsquire** [comment] 2024-01-30 13:45
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by christothes** [comment] 2024-01-30 18:11
Hi @rajagopalan-trimble  
Would you mind providing the logging output after reproducing this with [logging enabled](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/core/Azure.Core/samples/Diagnostics.md)?

**Comment by rajagopalan-trimble** [comment] 2024-02-09 06:06
Hi @christothes sorry, I couldn't post the details as I got held up. Please find the log details
`[06:04:52:539][Informational] DefaultAzureCredential.GetToken invoked. Scopes: [ https://management.azure.com//.default ] ParentRequestId: 9736494c-e54e-48ab-b33b-bd4913ef44ab
[06:04:52:564][Informational] EnvironmentCredential.GetToken invoked. Scopes: [ https://management.azure.com//.default ] ParentRequestId: 9736494c-e54e-48ab-b33b-bd4913ef44ab
[06:04:52:567][Informational] EnvironmentCredential.GetToken was unable to retrieve an access token. Scopes: [ https://management.azure.com//.default ] ParentRequestId: 9736494c-e54e-48ab-b33b-bd4913ef44ab Exception: Azure.Identity.CredentialUnavailableException (0x80131500): EnvironmentCredential authentication unavailable. Environment variables are not fully configured. See the troubleshooting guide for more information. https://aka.ms/azsdk/net/identity/environmentcredential/troubleshoot
[06:04:52:571][Informational] WorkloadIdentityCredential.GetToken invoked. Scopes: [ https://management.azure.com//.default ] ParentRequestId: 9736494c-e54e-48ab-b33b-bd4913ef44ab
[06:04:52:571][Informational] WorkloadIdentityCredential.GetToken was unable to retrieve an access token. Scopes: [ https://management.azure.com//.default ] ParentRequestId: 9736494c-e54e-48ab-b33b-bd4913ef44ab Exception: Azure.Identity.CredentialUnavailableException (0x80131500): WorkloadIdentityCredential authentication unavailable. The workload options are not fully configured. See the troubleshooting guide for more information. https://aka.ms/azsdk/net/identity/workloadidentitycredential/troubleshoot
[06:04:52:573][Informational] ManagedIdentityCredential.GetToken invoked. Scopes: [ https://management.azure.com//.default ] ParentRequestId: 9736494c-e54e-48ab-b33b-bd4913ef44ab
[06:04:52:612][Informational] False MSAL 4.56.0.0 MSAL.NetCore .NET 8.0.1 Ubuntu 22.04.3 LTS [2024-02-09 06:04:52Z - 9d57bef1-18f3-4a88-9ca4-72cb5070001f] MSAL MSAL.NetCore with assembly version '4.56.0.0'. CorrelationId(9d57bef1-18f3-4a88-9ca4-72cb5070001f)
[06:04:52:619][Informational] False MSAL 4.56.0.0 MSAL.NetCore .NET 8.0.1 Ubuntu 22.04.3 LTS [2024-02-09 06:04:52Z - 9d57bef1-18f3-4a88-9ca4-72cb5070001f] === AcquireTokenForClientParameters ===
SendX5C: False
ForceRefresh: False

[06:04:52:625][Informational] False MSAL 4.56.0.0 MSAL.NetCore .NET 8.0.1 Ubuntu 22.04.3 LTS [2024-02-09 06:04:52Z - 9d57bef1-18f3-4a88-9ca4-72cb5070001f] 
=== Request Data ===
Authority Provided? - True
Scopes - https://management.azure.com//.default
Extra Query Params Keys (space separated) - 
ApiId - AcquireTokenForClient
IsConfidentialClient - True
SendX5C - False
LoginHint ? False
IsBrokerConfigured - False
HomeAccountId - False
CorrelationId - 9d57bef1-18f3-4a88-9ca4-72cb5070001f
UserAssertion set: False
LongRunningOboCacheKey set: False
Region configured: 

[06:04:52:626][Informational] False MSAL 4.56.0.0 MSAL.NetCore .NET 8.0.1 Ubuntu 22.04.3 LTS [2024-02-09 06:04:52Z - 9d57bef1-18f3-4a88-9ca4-72cb5070001f] === Token Acquisition (ClientCredentialRequest) started:
         Scopes: https://management.azure.com//.default
        Authority Host: login.microsoftonline.com
[06:04:52:640][Informational] False MSAL 4.56.0.0 MSAL.NetCore .NET 8.0.1 Ubuntu 22.04.3 LTS [2024-02-09 06:04:52Z - 9d57bef1-18f3-4a88-9ca4-72cb5070001f] [Region discovery] Not using a regional authority. 
[06:04:52:640][Informational] False MSAL 4.56.0.0 MSAL.NetCore .NET 8.0.1 Ubuntu 22.04.3 LTS [2024-02-09 06:04:52Z - 9d57bef1-18f3-4a88-9ca4-72cb5070001f] [Instance Discovery] Skipping Instance discovery because it is disabled. 
[06:04:52:642][Informational] False MSAL 4.56.0.0 MSAL.NetCore .NET 8.0.1 Ubuntu 22.04.3 LTS [2024-02-09 06:04:52Z - 9d57bef1-18f3-4a88-9ca4-72cb5070001f] [ClientCredentialRequest] Sending Token response to client credential request endpoint ...
[06:04:52:655][Informational] Request [ee736ecb-413a-465c-a1ef-a7eca62d8935] GET http://169.254.169.254/metadata/identity/oauth2/token?api-version=2018-02-01&resource=REDACTED
Metadata:REDACTED
x-ms-client-request-id:ee736ecb-413a-465c-a1ef-a7eca62d8935
x-ms-return-client-request-id:true
User-Agent:azsdk-net-Identity/1.10.4 (.NET 8.0.1; Ubuntu 22.04.3 LTS)
client assembly: Azure.Identity
[06:04:52:759][Warning] Error response [ee736ecb-413a-465c-a1ef-a7eca62d8935] 401 Unauthorized (00.1s)
Date:Fri, 09 Feb 2024 06:04:52 GMT
Connection:close
Server:EC2ws
Content-Length:343
Content-Type:text/html

[06:04:52:788][Error] False MSAL 4.56.0.0 MSAL.NetCore .NET 8.0.1 Ubuntu 22.04.3 LTS [2024-02-09 06:04:52Z - 9d57bef1-18f3-4a88-9ca4-72cb5070001f] Exception type: Azure.RequestFailedException

   at Azure.Identity.ManagedIdentitySource.HandleResponseAsync(Boolean async, TokenRequestContext context, Response response, CancellationToken cancellationToken)
   at Azure.Identity.ImdsManagedIdentitySource.HandleResponseAsync(Boolean async, TokenRequestContext context, Response response, CancellationToken cancellationToken)
   at Azure.Identity.ManagedIdentitySource.AuthenticateAsync(Boolean async, TokenRequestContext context, CancellationToken cancellationToken)
   at Azure.Identity.ImdsManagedIdentitySource.AuthenticateAsync(Boolean async, TokenRequestContext context, CancellationToken cancellationToken)
   at Azure.Identity.ManagedIdentityClient.AuthenticateCoreAsync(Boolean async, TokenRequestContext context, CancellationToken cancellationToken)
   at Azure.Identity.ManagedIdentityClient.AppTokenProviderImpl(AppTokenProviderParameters parameters)
   at Microsoft.Identity.Client.Internal.Requests.ClientCredentialRequest.SendTokenRequestToAppTokenProviderAsync(ILoggerAdapter logger, CancellationToken cancellationToken)
   at Microsoft.Identity.Client.Internal.Requests.ClientCredentialRequest.GetAccessTokenAsync(CancellationToken cancellationToken, ILoggerAdapter logger)
   at Microsoft.Identity.Client.Internal.Requests.ClientCredentialRequest.ExecuteAsync(CancellationToken cancellationToken)
   at Microsoft.Identity.Client.Internal.Requests.RequestBase.RunAsync(CancellationToken cancellationToken)
[06:04:52:792][Informational] ManagedIdentityCredential.GetToken was unable to retrieve an access token. Scopes: [ https://management.azure.com//.default ] ParentRequestId: 9736494c-e54e-48ab-b33b-bd4913ef44ab Exception: Azure.Identity.AuthenticationFailedException (0x80131500): ManagedIdentityCredential authentication failed: Service request failed.
Status: 401 (Unauthorized)

Content:
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
 <head>
  <title>401 - Unauthorized</title>
 </head>
 <body>
  <h1>401 - Unauthorized</h1>
 </body>
</html>


Headers:
Date: Fri, 09 Feb 2024 06:04:52 GMT
Connection: close
Server: EC2ws
Content-Length: 343
Content-Type: text/html

See the troubleshooting guide for more information. https://aka.ms/azsdk/net/identity/managedidentitycredential/troubleshoot
 ---> Azure.RequestFailedException (0x80131500): Service request failed.
Status: 401 (Unauthorized)

Content:
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
 <head>
  <title>401 - Unauthorized</title>
 </head>
 <body>
  <h1>401 - Unauthorized</h1>
 </body>
</html>


Headers:
Date: Fri, 09 Feb 2024 06:04:52 GMT
Connection: close
Server: EC2ws
Content-Length: 343
Content-Type: text/html

[06:04:52:796][Informational] DefaultAzureCredential.GetToken was unable to retrieve an access token. Scopes: [ https://management.azure.com//.default ] ParentRequestId: 9736494c-e54e-48ab-b33b-bd4913ef44ab Exception: Azure.Identity.AuthenticationFailedException (0x80131500): ManagedIdentityCredential authentication failed: Service request failed.
Status: 401 (Unauthorized)

Content:
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
 <head>
  <title>401 - Unauthorized</title>
 </head>
 <body>
  <h1>401 - Unauthorized</h1>
 </body>
</html>


Headers:
Date: Fri, 09 Feb 2024 06:04:52 GMT
Connection: close
Server: EC2ws
Content-Length: 343
Content-Type: text/html

See the troubleshooting guide for more information. https://aka.ms/azsdk/net/identity/managedidentitycredential/troubleshoot
 ---> Azure.RequestFailedException (0x80131500): Service request failed.
Status: 401 (Unauthorized)

Content:
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
 <head>
  <title>401 - Unauthorized</title>
 </head>
 <body>
  <h1>401 - Unauthorized</h1>
 </body>
</html>


Headers:
Date: Fri, 09 Feb 2024 06:04:52 GMT
Connection: close
Server: EC2ws
Content-Length: 343
Content-Type: text/html

Azure.Identity.AuthenticationFailedException: ManagedIdentityCredential authentication failed: Service request failed.
Status: 401 (Unauthorized)

Content:
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
 <head>
  <title>401 - Unauthorized</title>
 </head>
 <body>
  <h1>401 - Unauthorized</h1>
 </body>
</html>


Headers:
Date: Fri, 09 Feb 2024 06:04:52 GMT
Connection: close
Server: EC2ws
Content-Length: 343
Content-Type: text/html

See the troubleshooting guide for more information. https://aka.ms/azsdk/net/identity/managedidentitycredential/troubleshoot
 ---> Azure.RequestFailedException: Service request failed.
Status: 401 (Unauthorized)

Content:
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
 <head>
  <title>401 - Unauthorized</title>
 </head>
 <body>
  <h1>401 - Unauthorized</h1>
 </body>
</html>


Headers:
Date: Fri, 09 Feb 2024 06:04:52 GMT
Connection: close
Server: EC2ws
Content-Length: 343
Content-Type: text/html

   at Azure.Identity.ManagedIdentitySource.HandleResponseAsync(Boolean async, TokenRequestContext context, Response response, CancellationToken cancellationToken)
   at Azure.Identity.ImdsManagedIdentitySource.HandleResponseAsync(Boolean async, TokenRequestContext context, Response response, CancellationToken cancellationToken)
   at Azure.Identity.ManagedIdentitySource.AuthenticateAsync(Boolean async, TokenRequestContext context, CancellationToken cancellationToken)
   at Azure.Identity.ImdsManagedIdentitySource.AuthenticateAsync(Boolean async, TokenRequestContext context, CancellationToken cancellationToken)
   at Azure.Identity.ManagedIdentityClient.AuthenticateCoreAsync(Boolean async, TokenRequestContext context, CancellationToken cancellationToken)
   at Azure.Identity.ManagedIdentityClient.AppTokenProviderImpl(AppTokenProviderParameters parameters)
   at Microsoft.Identity.Client.Internal.Requests.ClientCredentialRequest.SendTokenRequestToAppTokenProviderAsync(ILoggerAdapter logger, CancellationToken cancellationToken)
   at Microsoft.Identity.Client.Internal.Requests.ClientCredentialRequest.GetAccessTokenAsync(CancellationToken cancellationToken, ILoggerAdapter logger)
   at Microsoft.Identity.Client.Internal.Requests.ClientCredentialRequest.ExecuteAsync(CancellationToken cancellationToken)
   at Microsoft.Identity.Client.Internal.Requests.RequestBase.RunAsync(CancellationToken cancellationToken)
   at Microsoft.Identity.Client.ApiConfig.Executors.ConfidentialClientExecutor.ExecuteAsync(AcquireTokenCommonParameters commonParameters, AcquireTokenForClientParameters clientParameters, CancellationToken cancellationToken)
   at Azure.Identity.AbstractAcquireTokenParameterBuilderExtensions.ExecuteAsync[T](AbstractAcquireTokenParameterBuilder`1 builder, Boolean async, CancellationToken cancellationToken)
   at Azure.Identity.MsalConfidentialClient.AcquireTokenForClientCoreAsync(String[] scopes, String tenantId, Boolean enableCae, Boolean async, CancellationToken cancellationToken)
   at Azure.Identity.MsalConfidentialClient.AcquireTokenForClientAsync(String[] scopes, String tenantId, Boolean enableCae, Boolean async, CancellationToken cancellationToken)
   at Azure.Identity.ManagedIdentityClient.AuthenticateAsync(Boolean async, TokenRequestContext context, CancellationToken cancellationToken)
   at Azure.Identity.ManagedIdentityCredential.GetTokenImplAsync(Boolean async, TokenRequestContext requestContext, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Azure.Identity.CredentialDiagnosticScope.FailWrapAndThrow(Exception ex, String additionalMessage, Boolean isCredentialUnavailable)
   at Azure.Identity.ManagedIdentityCredential.GetTokenImplAsync(Boolean async, TokenRequestContext requestContext, CancellationToken cancellationToken)
   at Azure.Identity.ManagedIdentityCredential.GetTokenAsync(TokenRequestContext requestContext, CancellationToken cancellationToken)
   at Azure.Identity.DefaultAzureCredential.GetTokenFromSourcesAsync(TokenCredential[] sources, TokenRequestContext requestContext, Boolean async, CancellationToken cancellationToken)
   at Azure.Identity.DefaultAzureCredential.GetTokenImplAsync(Boolean async, TokenRequestContext requestContext, CancellationToken cancellationToken)
   at Azure.Identity.CredentialDiagnosticScope.FailWrapAndThrow(Exception ex, String additionalMessage, Boolean isCredentialUnavailable)
   at Azure.Identity.DefaultAzureCredential.GetTokenImplAsync(Boolean async, TokenRequestContext requestContext, CancellationToken cancellationToken)
   at Azure.Identity.DefaultAzureCredential.GetTokenAsync(TokenRequestContext requestContext, CancellationToken cancellationToken)
   at Azure.Core.Pipeline.BearerTokenAuthenticationPolicy.AccessTokenCache.GetHeaderValueFromCredentialAsync(TokenRequestContext context, Boolean async, CancellationToken cancellationToken)
   at Azure.Core.Pipeline.BearerTokenAuthenticationPolicy.AccessTokenCache.GetHeaderValueAsync(HttpMessage message, TokenRequestContext context, Boolean async)
   at Azure.Core.Pipeline.BearerTokenAuthenticationPolicy.AccessTokenCache.GetHeaderValueAsync(HttpMessage message, TokenRequestContext context, Boolean async)
   at Azure.Core.Pipeline.BearerTokenAuthenticationPolicy.AuthenticateAndAuthorizeRequestAsync(HttpMessage message, TokenRequestContext context)
   at Azure.Core.Pipeline.BearerTokenAuthenticationPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
   at Azure.Core.Pipeline.RedirectPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
   at Azure.Core.Pipeline.RetryPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
   at Azure.Core.Pipeline.RetryPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
   at Azure.Core.PageableHelpers.PageableImplementation`1.GetNextResponseAsync(Nullable`1 pageSizeHint, String nextLink, CancellationToken cancellationToken)
   at Azure.Core.PageableHelpers.PageableImplementation`1.GetAsyncEnumerator(CancellationToken cancellationToken)+MoveNext()
   at Azure.Core.PageableHelpers.PageableImplementation`1.GetAsyncEnumerator(CancellationToken cancellationToken)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at Azure.ResourceManager.SharedExtensions.FirstOrDefaultAsync[TSource](AsyncPageable`1 source, Func`2 predicate, CancellationToken token)
   at Azure.ResourceManager.SharedExtensions.FirstOrDefaultAsync[TSource](AsyncPageable`1 source, Func`2 predicate, CancellationToken token)
   at Azure.ResourceManager.ArmClient.GetDefaultSubscriptionAsync(CancellationToken cancellationToken)
   at ManagedIdentityTestApp.Program.Main(String[] args) in /home/ubuntu/azurerm/Program.cs:line 32`

**Comment by christothes** [comment] 2024-02-09 15:38
Hi @rajagopalan-trimble 
Based on the logging, it seems that the arc enabled server may not be properly configured for managed identity. We should find the environment variables mentioned in [this article](https://learn.microsoft.com/en-us/azure/azure-arc/servers/managed-identity-authentication#security-overview) and use those to find the correct endpoint.

**Comment by rajagopalan-trimble** [comment] 2024-02-14 10:26
@christothes I hope you are aware that the managed identity gets added at the moment a server is onboarded in Azure ARC. By default it is a system assigned identity and in this line, ArmClient client = new ArmClient(new DefaultAzureCredential());, how can I point it to the URL that the IMDS_ENDPOINT environment variable directs to as given in the link that you referred?

**Comment by christothes** [comment] 2024-02-14 18:52
The `DefaultAzureCredential` will probe the environment automatically. However, if the ARC enabled server isn't in place, those environment variables won't be available and we'll fall through to trying other managed identity implementations, including IMDS, which is the `http://169.254.169.254/metadata/identity/oauth2/token?api-version=2018-02-01&resource=REDACTED` address we see in the logging.

**Comment by rajagopalan-trimble** [comment] 2024-02-15 07:26
@christothes the environment variable IDENTITY_ENDPOINT is available only in Windows based ARC server but not in LInux as you can see the output below. In this case, the defaultCredential fall through to trying other managed identity implementations, including IMDS. So, I infer that if the IDENTITY_ENDPOINT is not available, then I should create a one that will point it to http://localhost:40342/metadata/identity/oauth2/token, is that right?
ubuntu@i-0121a96d8d84140d2:~$ pwsh
PowerShell 7.4.1
PS /home/ubuntu> $IDENTITY_ENDPOINT = "IDENTITY_ENDPOINT"
PS /home/ubuntu> (get-item env:$IDENTITY_ENDPOINT).Value
Get-Item: Cannot find path 'Env:/IDENTITY_ENDPOINT' because it does not exist.

**Comment by christothes** [comment] 2024-02-15 15:37
I believe the connected machine agent should do this for you and it looks like it should work on Linux according to the docs. Can you confirm you have configured it correctly and are on a supported OS version? https://learn.microsoft.com/en-us/azure/azure-arc/servers/manage-vm-extensions#connected-machine-agent

**Comment by rajagopalan-trimble** [comment] 2024-02-15 15:43
@christothes I used Ubuntu 22.04, looking at the documentation, I don't see it. I will give a try with 20.04 and post you an update.

**Comment by hopitas** [comment] 2024-02-16 13:50
> @christothes I used Ubuntu 22.04, looking at the documentation, I don't see it. I will give a try with 20.04 and post you an update.

I tried this with ubuntu 20.04. No luck.

**Comment by rajagopalan-trimble** [comment] 2024-02-20 09:47
@christothes I tried in Ubuntu 20.04 and no luck, please find details from my end
20% [==>            ]
  30% [===>           ]  
  INFO    Creating resource in Azure...                 Correlation ID=feaffa07-600c-414b-9781-acd91c0d2be9 Resource ID=/subscriptions/df5df55e-c24d-4549-bc0f-9106426b8fb3/resourceGroups/tcp-TCSREI-1105/providers/Microsoft.HybridCompute/machines/i-04ceec81b0da34f98
  60% [========>      ]  
  80% [===========>   ]  
 100% [===============]  
  INFO    Connected machine to Azure          
INFO    Machine overview page: https://portal.azure.com/#@2f16a741-bc3a-42ec-831e-fda5267388cf/resource/subscriptions/df5df55e-c24d-4549-bc0f-9106426b8fb3/resourceGroups/tcp-TCSREI-1105/providers/Microsoft.HybridCompute/machines/i-04ceec81b0da34f98/overview 
ubuntu@ip-10-23-6-211:~$ echo $IDENTITY_ENDPOINT

ubuntu@ip-10-23-6-211:~$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.6 LTS
Release:        20.04
Codename:       focal
ubuntu@ip-10-23-6-211:~$

**Comment by christothes** [comment] 2024-02-20 15:19
Hi @rajagopalan-trimble - I'm not sure why the ARC extensions are not configuring the host as expected, but this is outside the realm of what I can help with concerning the SDK itself. I'd recommend going through the troubleshooting guide and utilizing the support contacts in that article if it isn't helpful in resolving the issue. https://learn.microsoft.com/en-us/azure/azure-arc/servers/troubleshoot-vm-extensions

**Closed** 2024-03-13 01:26 UTC
Labels: Client, needs-author-feedback, Azure.Identity, customer-reported, question, no-recent-activity
