### ISSUE TITLE
[BUG] Wrong request during the LRO of OperationaIInsights - Cluster - PUT

### ISSUE THREAD

**Issue by HarveyLink** [Azure/azure-sdk-for-net#40606] opened 2023-12-06 09:39 UTC
### Library name and version

Azure.ResourceManager.OperationalInsights

### Describe the bug

During the creation of cluster, one of the LRO request failed with 404 Not Found error response:
```
{"error":{"code":"InvalidResourceType","message":"The resource type 'locations/operationStatuses' could not be found in the namespace 'Microsoft.OperationalInsights' for api version '2021-06-01'. The supported api-versions are '2015-03-20,2015-11-01-preview,2017-01-01-preview,2017-03-03-preview,2017-03-15-preview,2017-04-26-preview,2019-08-01-preview,2020-03-01-preview,2020-08-01,2020-10-01,2021-12-01-preview,2022-10-01,2022-09-01-privatepreview,2023-01-01-preview'."}}
```
Errror reuqest:
```
GET /subscriptions/<SUBID>/providers/Microsoft.OperationalInsights/locations/eastus/operationstatuses/544f39d8-11b2-4dbd-9518-125e3604bae2?api-version=2021-06-01&t=<KEY>
```
Previous success PUT request and it's 202 response:
```
{"identity":{"type":"SystemAssigned"},"sku":{"capacity":1000,"name":"CapacityReservation"},"tags":{},"location":"eastus","properties":{}}
```
```
Location: https://management.azure.com/subscriptions/<SUBID>/resourceGroups/deleteme1110/providers/Microsoft.OperationalInsights/clusters/clusterName/operationresults/544f39d8-11b2-4dbd-9518-125e3604bae2?api-version=2021-06-01&t=<KEY>
Retry-After: 20
x-ms-ratelimit-remaining-subscription-writes: 1199
Access-Control-Allow-Origin: *
Request-Context: appId=cid-v1:e6336c63-aab2-45f0-996a-e5dbab2a1508
X-Content-Type-Options: nosniff
Azure-AsyncOperation: https://management.azure.com/subscriptions/<SUBID>/providers/Microsoft.OperationalInsights/locations/eastus/operationstatuses/544f39d8-11b2-4dbd-9518-125e3604bae2?api-version=2015-11-01-preview&t=<KEY>
api-supported-versions: 2020-08-01, 2020-10-01, 2021-06-01, 2022-10-01
```

### Expected behavior

LRO request completed with no error.

### Actual behavior

LRO stopped with 404 error.

### Reproduction Steps

```
var cluster = (await resourceGroup.GetOperationalInsightsClusters().CreateOrUpdateAsync(WaitUntil.Completed, clusterName, clusterData)).Value;
```

**Comment by archerzz** [comment] 2024-01-05 05:46
Probably a duplicate of https://github.com/Azure/azure-sdk-for-net/issues/39799

**Comment by archerzz** [comment] 2024-01-05 06:00
OK. It's not a duplicate. There is something wrong in the server side. The `api-version` query parameters in `Location` and `Async-Operation` are different.
- api-version=2021-06-01
- api-version=2015-11-01-preview

We need to inform service team to investigate.

**Comment by ArthurMa1978** [comment] 2024-04-11 07:38
Try remove the `Azure-AsyncOperation` by using policy

**Comment by welovej** [comment] 2024-05-30 05:30
#44314

**Comment by welovej** [comment] 2024-05-30 05:31
#44314

**Closed** 2024-06-13 07:04 UTC
Labels: Insights, Mgmt
