### ISSUE TITLE
[QUERY] Recommended approach to setting MD5 checksum for ShareFileClient.UploadAsync

### ISSUE THREAD

**Issue by pborovina** [Azure/azure-sdk-for-net#18774] opened 2021-02-15 05:28 UTC
We've recently upgraded an ASP.NET Core project to the `Azure.Storage.Files.Shares` package and have noticed that calculating MD5 checksums is no longer supported directly in the SDK. Previously, when uploading `Microsoft.Azure.Storage.File.CloudFiles`, we were using the `FileRequestOptions.StoreFileContentMD5` property, but this is no longer exists. When uploading via `ShareFileClient.UploadAsync`, is there a recommended way to calculate the MD5 checksum or a migration path from the old StoreFileContentMD5 approach? We're currently pre-calculating the MD5 and then setting `ShareFileHttpHeaders.ContentHash` property and adding the header when calling `ShareFileClient.CreateAsync` (as per some of the samples).

As an aside, why was MD5 functionality removed?

**Comment by AKlaus** [comment] 2021-02-15 08:09
Cross linking a relevant question on SO - https://stackoverflow.com/q/63279035/968003 (so far with no clear path).

Hey Azure SQK team,

- is it something that's been forgotten (and will be fixed) or done deliberately? 
- If the latter, then does it mean that none of the Azure tools would ever check the MD5? As there are some options in the algorithm implementation, then it'd be nice to align the MD5 implementation with the other tools.

**Comment by jsquire** [comment] 2021-02-15 15:32
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by Lann094** [comment] 2021-03-23 00:14
Sorry for the notification without having an answer, just want to add that we'd really like to know this too. Hopefully my reviving will help show there's demand. 🙂

**Comment by Timothyoverton** [comment] 2021-03-23 01:43
I'm also interested in the outcome here, we have lots of files with no MD5.

**Comment by Delriarh** [comment] 2021-03-26 17:38
Hello, same here, we use the Md5 to check file changes and avoid uploading same files everytime...
Thanks !

**Comment by amishra-dev** [comment] 2021-06-03 00:15
@jaschrep-msft can you respond to this one?

**Comment by jaschrep-msft** [comment] 2021-08-05 22:12
Currently, there is no way to do this for that API, as that API splits your upload into multipart uploads, where each individual UploadRange call needs its own hash. For now, you have to split the upload yourself into 4MB chunks and then compute and set the `transactionalContentHash` for each one.

We are in the process of developing a better solution to this which will allow the SDK to handle this for the user on all upload and download APIs. It will be coming in a future release.

**Closed** 2024-01-31 22:24 UTC
Labels: Storage, Service Attention, Client, customer-reported, feature-request, needs-team-attention

**Comment by AKlaus** [comment] 2024-01-31 23:07
@seanmcc-msft, could please shed some light on what version of the SDK checks the MD5? 
(I guess, the functionality was added, as the issue is marked as "completed", but there's no linked PR)
