### ISSUE TITLE
[FEATURE REQ] Make partition load balancing faster and configurable

### ISSUE THREAD

**Issue by petrformanek** [Azure/azure-sdk-for-net#11989] opened 2020-05-11 13:46 UTC
**Library or service name.**
Azure.Messaging.EventHubs.Processor
 
**Description**
Since version 5 of the library is partition load balancing slow.
Partition load balancing speed in v4 EventHubs SDK was significantly faster. 
Now when starting `EventProcessorClient` on an event hub with 32 partitions it takes 320 seconds (32x10 seconds) to start to handle events on all partitions. It is not acceptable and breaks our SLA.

Please make initial load balancing much faster.
Allow to configure load balancing options (e.g. allow to set `LoadBalancingUpdateInterval`).

**Comment by jsquire** [comment] 2020-05-12 13:01
Hi @petrformanek , thank you for reaching out with feedback. The current load balancing implementation for the processor is tuned for helping multiple processors share the load without a high degree of contention for each partition. That contention results in partitions "bouncing" between processors as they are added/removed or when they experience latency, causing processing for those partitions to slow down.

We recognize that there are scenarios where this isn't an ideal design and those using fewer processors with a higher partition count would see a slower initialization, such as you are. I'm happy to say that we're currently working through a plan to expose the ability to tune configuration of the load balancer to allow for more aggressive claiming of partitions and an adjustable lease duration. It is our hope that these additional options should allow you more control over load balancing so that you can find the right balance for your scenario.

Unfortunately, I don't have any dates that I can share at the moment, but I can confirm that this is something we're working on.   If you'd like to keep tabs, the issues currently tracking this are:  #11769 and #11768.

**Comment by jsquire** [comment] 2020-05-12 13:20
The one other thing that I'd like to mention is that we have a new primitive that has just been released, the [`EventProcessor<TPartition>`](https://docs.microsoft.com/en-us/dotnet/api/azure.messaging.eventhubs.primitives.eventprocessor-1?view=azure-dotnet-preview&viewFallbackFrom=azure-dotnet) which includes some options for tuning load balancing.  Depending on your specific needs, it may be of interest.

Generally speaking, `EventProcessorClient` was designed to provide a familiar API to that of the `EventHubConsumerClient` and offer an intuitive "step-up" experience for developers exploring Event Hubs as they move towards production scenarios.   For a large portion of our library users, that covers their needs well.   There's definitely a point, however, where your application requires more control to handle higher throughput or specialized needs that aren't shared by a large group - that's where the `EventProcessor<TPartition>` is intended to help.

The `EventProcessor<TPartition>` fills a similar role as the `EventProcessorClient`, with cooperative load balancing and resiliency as its core features but offering native batch processing, extension points for influencing load balancing, using different storage providers, and a lighter, less opinionated API.   The caveat is that this comes in the form of an abstract base, which needs to be extended and the core “handler” activities implemented via override.  More on the design and philosophy behind this can be found [[here]](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/eventhub/Azure.Messaging.EventHubs/design/event-processor%7BT%7D-proposal.md).

**Comment by jsquire** [comment] 2020-05-18 19:34
I'm going to close this out as a duplicate of the issues that I mentioned above.   Please feel free to reopen if you believe this requires further discussion.

**Closed by jsquire** 2020-05-18 19:34 UTC
Labels: Client, Event Hubs, customer-reported, feature-request, needs-author-feedback
