### ISSUE TITLE
AppConfig: DefaultAzureCredential doesn't work in ConfigurationClient

### ISSUE THREAD

**Issue by zhenlan** [Azure/azure-sdk-for-net#22223] opened 2021-06-27 18:35 UTC
# Issue Transfer from the AppConfiguration reposiitory, [#530](https://github.com/Azure/AppConfiguration/issues/530)

## Please be aware that @gkarnik-gl is the author of the original issue and be sure to include them on any questions or replies.

While running locally from Visual Studio, DefaultAzureCredential parameter for ConfigurationClient doesn't work whereas it works for SecretClient. VisualStudioCredential parameter works for both.

Success:
```csharp
var secretClient = new SecretClient(new Uri("<KeyVaultUri>"), new DefaultAzureCredential());
```

Fail:
```csharp
var configClient = new ConfigurationClient(new Uri("<AppConfigUri>"), new DefaultAzureCredential());
```

Success:
```csharp
var secretClient = new SecretClient(new Uri("<KeyVaultUri>"), new VisualStudioCredential());
var configClient = new ConfigurationClient(new Uri("<AppConfigUri>"), new VisualStudioCredential());
```

**Comment by jsquire** [comment] 2021-06-27 18:51
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by pakrym** [comment] 2021-06-28 16:11
@gkarnik-gl can you please provide the error you are seeing?

**Comment by gkarnik-gl** [comment] 2021-06-28 16:31
Hi Pavel,

I was getting a forbidden 403 error, but I'm unable to reproduce it now.

Thanks,
Guru Karnik
GlobalLogic
 M +91.9986769548
www.globallogic.com

**Comment by pakrym** [comment] 2021-06-28 16:36
Sometimes role assignments take a while to propagate. Closing, please reopen if it happens again.

**Closed by pakrym** 2021-06-28 16:36 UTC
Labels: App Configuration, Client, needs-team-attention
