### ISSUE TITLE
[BUG] BlobSasBuilder does not accept "d" as value for "Resource"

### ISSUE THREAD

**Issue by davyvanlaere** [Azure/azure-sdk-for-net#35690] opened 2023-04-20 11:45 UTC
### Library name and version

Azure.Storage.Blobs

### Describe the bug

The BlobSasBuilder ignores Resource set to "d"

### Expected behavior

I want to create a sas token for a directory in a blob container using the BlobSasBuilder.

### Actual behavior

Currently, when setting Resource to "d", the resulting sr querystring parameters is still "c". If i look at the github code of BlobSasBuilder, i see that i will never set the value to "d". 

The documentation does list "d" as a valid value:
https://learn.microsoft.com/en-us/rest/api/storageservices/create-service-sas#specify-the-signed-resource-blob-storage-only

### Reproduction Steps

Shortened code:
`
            BlobServiceClient client = new BlobServiceClient("connection string");
            var result = await client.CreateBlobContainerAsync(containername);

            BlobSasBuilder blobSasBuilder = new BlobSasBuilder(
                BlobContainerSasPermissions.Create,
                DateTimeOffset.UtcNow.AddHours(1))
            {
                BlobContainerName = containername,
                Resource = "d"
            };

            var storageSharedKeyCredential = new StorageSharedKeyCredential(
                   "storageaccountname",
                   "storageaccountkey"
               );

            var sasQueryParameters = blobSasBuilder.ToSasQueryParameters(storageSharedKeyCredential);
`

**Comment by SaurabhSharma-MSFT** [comment] 2023-04-20 16:24
@davyvanlaere We are looking into it and get back to you for any additional information.

**Comment by SaurabhSharma-MSFT** [comment] 2023-04-24 21:55
@davyvanlaere I could see the same and redirecting this to services team for further investigation and documentation update if required.

**Comment by davyvanlaere** [comment] 2023-04-26 12:28
Ok. I also noticed that signedDirectoryDepth, which is required if signedResource="d", is not included when constructing the signature string.

**Comment by davyvanlaere** [comment] 2023-06-13 09:05
> Hi @davyvanlaere. Thank you for opening this issue and giving us the opportunity to assist. To help our team better understand your issue and the details of your scenario please provide a response to the question asked above or the information requested above. This will help us more accurately address your issue.

Testing, no success thus far, but is probably user error.

**Comment by amnguye** [comment] 2023-06-13 17:24
Can you provide me a code snippet of how you're attempting to use the `DataLakeSasBuilder` and the error received back?

If there's no error could you provide the SAS generated (with the sig= value redacted) ?

**Comment by yugabe** [comment] 2023-07-28 13:27
Just ran into this issue as well and would like to confirm there is an issue that `BlobSasBuilder` won't accept `"d"` for the `Resource` value. In fact, providing *any* value is essentially useless, because currently (version 12.17.0 of `Azure.Storage.Blobs`) calls `EnsureState()` every time when generating the SAS, and forces `Resource` to be set as follows:

```csharp
// Container
if (string.IsNullOrEmpty(BlobName))
{
    Resource = Constants.Sas.Resource.Container;
}


// Blob or Snapshot
else
{
    // Blob
    if (string.IsNullOrEmpty(Snapshot) && string.IsNullOrEmpty(BlobVersionId))
    {
        Resource = Constants.Sas.Resource.Blob;
    }
    // Snapshot
    else if (string.IsNullOrEmpty(BlobVersionId))
    {
        Resource = Constants.Sas.Resource.BlobSnapshot;
    }
    // Blob Version
    else
    {
        Resource = Constants.Sas.Resource.BlobVersion;
    }
}
```
(See [here](
https://github.com/Azure/azure-sdk-for-net/blob/512832af4a8f435c7cd3ddb2fa751adcf09644ea/sdk/storage/Azure.Storage.Blobs/src/Sas/BlobSasBuilder.cs#L521C1-L545C14))

However, the relevant [docs (Create a user delegation SAS / User delegation SAS support for directory-scoped access)](https://learn.microsoft.com/en-us/rest/api/storageservices/create-user-delegation-sas) state: 
> A user delegation SAS supports directory scope (`sr=d`) when the authorization version (`sv`) is 2020-02-10 or later and a hierarchical namespace (HNS) is enabled. The semantics for directory scope (`sr=d`) are similar to container scope (`sr=c`), except that access is restricted to a directory and any files and subdirectories within it. When `sr=d` is specified, the `sdd` query parameter is also required.
> 
> The string-to-sign format for authorization version 2020-02-10 is unchanged.

It is clearly possible and valid to generate a correct SAS, as it is possible to do so on the Azure portal (I tested it and it does work when HNS is enabled):
![image](https://github.com/Azure/azure-sdk-for-net/assets/14803737/f2467465-bf66-448b-bc06-109a0ad33c9d)

The problem is not just that it doesn't accept `"d"` (or any other value, really, the `Resource` property probably shouldn't even be publicly settable if it's going to get overwritten anyways). It's that there's no clear semantics that can be used when targeting a directory - it's not a blob, nor a container, so the user shouldn't set `BlobName` to target a directory as the SAS. I believe there should probably also be a `Directory` property (which, in logic, should be mutually exclusive with `BlobName`).

Maybe also consider using switch expressions here to imply that the intent here is to supply `Resource` with a value. The logic 

```csharp
Resource = (BlobName, Directory, Snapshot, BlobVersionId) switch
{
    (null or [],       null or [],       null or [],       null or []      ) => Constants.Sas.Resource.Container,
    (null or [],       not (null or []), null or [],       null or []      ) => Constants.Sas.Resource.Directory,
    (not (null or []), null or [],       null or [],       null or []      ) => Constants.Sas.Resource.Blob,
    (not (null or []), null or [],       not (null or []), null or []      ) => Constants.Sas.Resource.BlobSnapshot,
    (not (null or []), null or [],       null or [],       not (null or [])) => Constants.Sas.Resource.BlobVersion,
    _ => throw Errors.Invalid("Invalid configuration set.")
}
```

There's also no way to set the `"sdd"` value. Using `DataLakeSasBuilder` instead is not a proper way to solve the issue at hand.

**Comment by yugabe** [comment] 2023-07-28 14:07
Additionally, after a bit or research, it seems the way forward would be to use `DataLakeSasBuilder`. I managed to get it to work. However, it is VERY confusing, as the documentation almost makes no mention of this, nor does the Azure portal, and nomenclature is different (containers are "file systems", for example). All examples point to using `Azure.Storage.Blobs`, and there is no indication whatsoever as to use `Azure.Storage.Files.DataLake` instead. If one is supposed to be a replacement for the other, then it should be consolidated accordingly.

Should I just switch to using the `DataLake` APIs instead of `Blobs`? Why? Why not? Why the name "change"? Why call "containers" "file systems" instead, for example? Why not just expand the Blob storage APIs accordingly? 

@amnguye maybe could shed some light on this? Thanks.

**Comment by amnguye** [comment] 2023-07-28 18:04
Yes you're correct for storage accounts that have HNS enabled you should be using the `DataLakeSasBuilder`. Essentially you should be using the `Azure.Storage.Files.Datalake` package over `Blobs` if you have HNS enabled on your storage account.

The name difference between Blobs and Datalake is due to the differences of features supported between non-HNS and HNS enabled accounts.

For example the concept of directories exist in HNS enabled accounts, however in a non-HNS accounts the "directories" you see are virtual directories. If you were to delete all the blobs in a "directory" in a non-HNS account, the "directory" would also remove itself.

I believe there's different Billings between non-HNS accounts and HNS accounts (I could be incorrect about this), which is why the REST APIs haven't been fully merged. However you may have to contact Azure Support about this to clear up your confusion on why this is.

Any more general Storage questions please contact Azure Support. 
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

We can answer questions that pertain to the Storage SDK but not general questions on why storage decisions were made.

It might be more appropriate to air concerns regarding documentation on the feedback page of the documentation that is written. Unfortunately here we can only speak to the Storage SDK and the documentation we own. Unfortunately we don't own that documentation that you referenced.

However back to the OP concern regarding "sr=d" and "sdd". We removed the need to specify "sdd" because that can be calculated from the path handed to the `DatalakeSasBuilder`.

If you have any more trouble using `DatalakeSasBuilder` could you provide a code snippet of how you're attempting to generate a SAS here?

Apologies for any confusion and frustration you may be having.

**Comment by yugabe** [comment] 2023-07-31 08:55
Thank you for the clear answers @amnguye. I don't think my confusion (and, looking at the current issue and some related ones, others' as well) stems directly from how the SDK itself is implemented. Sure, there might be pricing or even availability concerns that make comparing the "classic" blob storage service and the HNS enabled one relevant, but that in and of itself doesn't solve the problem of the product being possibly incorrectly positioned. HNS is literally a checkbox when creating a storage account.

That, for a developer, mentally means it's a feature of the corresponding resource to be created. Even though it might be a lot more complicated on the backend, in effect, it should *not* imply that the developer has to use a totally different SDK altogether. In this case, specifically, I believe the `Azure.Storage.Blobs` should support directory level SAS token generation. The SDK's documentation itself doesn't mention otherwise. The `Resource` property is publicly settable, however that setting will be overwritten at runtime when generating the SAS.

I understand there might be issues at other levels like marketing, product positioning and so on. The SDK, however, correlates to the developer experience most closely. And at that point, I have found no indication in the `Blobs` SDK that I should use the `DataLake` SDK at any point. Semantically, I'm not working with big data, nor use any Hadoop workloads, so the thought hadn't even occurred to me.

Seeing as how the issue is still open, I suggest considering either one or more of the following approaches to solve it:
- Support the `d` flag for the resource when generating SAS tokens and the `AgentObjectId` for SAS tokens, maybe by a new `BlobDirectorySasBuilder` type in the `Blobs` SDK as well. Reference the API from relevant documentations online and in-code to aid user discovery. I'd also make `private` the `Resource` property's `set` operation and make it clear in the XML comments that it will be calculated based on the builder's state (just as the `sdd` is elsewhere, as you pointed out). I believe this to be the most "correct" way to solve the issue. 
- Consolidate the `DataLake` and `Blobs` SDKs into one SDK (seeing as how it is surfaced in the Azure Portal, and how the `DataLake` API references the `Blobs` SDK, it seems trivial to consolidate the into the `Blobs` SDK). This will be a breaking change for current users of the `DataLake` SDK, but possibly not the APIs. I think this is supported by how the REST API is organized, [you can see](https://learn.microsoft.com/en-us/rest/api/storageservices/data-lake-storage-gen2) the APIs that are available could be easily consolidated into the blob ones.
- Update the documentations (both for the SDK where needed and the docs owned by other teams) so that it is made clear that there are two different SDKs for similar scenarios, when to use each and how to choose between them. This seems to be the most effort to me.
- Move generating all SAS tokens into its own assembly/SDK, or to `Azure.Storage.Common`. There probably could be some abstraction leakage, however.

Of course, there might be some other solutions I haven't thought of, but leaving things as they are will surely cause confusion for others in the future as well.

**Comment by amnguye** [comment] 2023-07-31 16:42
I know that it's an opinion you hold that because in Portal it's one check mark box, however from a developer's perspective it needs to be known that non-HNS accounts and HNS accounts are different.

You may have different scenarios and workloads you are trying to achieve, however there are other customers with different scenarios and perspectives you need to take into account.

We're not going to do the first suggestion as a Directory is still not a concept in the flat namespace of blobs. That misleads users to thinking that blobs is a hierarchical namespace when it's not.

We are not going to deprecate the Datalake SDK just because you did not find any indications between using either the Blobs or Datalake SDK. This feels more like a documentation issue if anything else.

We are definitely not going to the first bullet point because as said before, the concepts of directories does not exist in blobs. Blobs is a flat namespace and introducing any "Directory" API makes it confusing to users that directories do exist in a flatnamespace when it does not. Customers who do NOT have HNS enabled on their account will attempt to use "d" in the SAS and then when they figure out that they can't generate a SAS they will 100% make a Azure Support ticket due to this confusion.

We are not doing the second bullet point. HNS and non-HNS accounts have separate features, some that are supported in one and not the other. The point of keeping things separate is to show what is exactly supported in what and not confuse customers  with what is supported in an HNS account and what is not.

We can do a better job at updating the documentation again, and you can suggest exactly where in our SDK documentation is lacking to clear up any confusion you may have with that. Again I've stated that some of this documentation outside of the SDK does not belong to us and you are free to click either the "Feedback" button if available on the documentation page (so it is received by the correct team) or submit a Azure Support ticket if not available.

We are not creating a separate package to generate SAS tokens as it we would need to create a package for each and every service to make it clear what is and is not supported based on the respective service.

Seeing as I've already addressed the OP's concerns, and they haven't responded and the issue is resolved by using the `DataLakeSasBuilder` and that `d` is already supported. I will be closing the issue.

Feel free to make a new issue if you find any problems with the SDK documentation, as those issues are outside of this issue.

**Closed by amnguye** 2023-07-31 16:42 UTC
Labels: Storage, Service Attention, Client, needs-author-feedback, customer-reported, question
