### ISSUE TITLE
LLC: Reference docs for protocol methods are not sufficient

### ISSUE THREAD

**Issue by KrzysztofCwalina** [Azure/azure-sdk-for-net#24145] opened 2021-09-21 21:15 UTC
See https://docs.microsoft.com/en-us/dotnet/api/azure.analytics.purview.account.purviewaccountclient.updateaccountproperties?view=azure-dotnet-preview#Azure_Analytics_Purview_Account_PurviewAccountClient_UpdateAccountProperties_Azure_Core_RequestContent_Azure_RequestOptions_

Protocol methods require the caller to know the schema of the body payload. The current docs (link above) are show the schema in a format that is impossible to understand.

**Comment by annelo-msft** [comment] 2022-05-23 16:21
Closing as duplicate of https://github.com/Azure/azure-sdk-for-net/issues/28833

**Closed by annelo-msft** 2022-05-23 16:21 UTC
Labels: Client, Docs, LLC
