### ISSUE TITLE
[QUERY] Is the QueueClient thread safe? Can it be a singleton or should it be scoped?

### ISSUE THREAD

**Issue by PureKrome** [Azure/azure-sdk-for-net#13308] opened 2020-07-08 13:20 UTC
**Query/Question**
I'm learning the new/newer v12 SDK (from the 9.x and older, days). I've noticed that most samples do this:

```
// Instantiate a QueueClient which will be
// used to create and manipulate the queue
QueueClient queueClient = new QueueClient(connectionString, queueName);

// Do stuff .. like ..
// - Create a queue
// - Add a message
// - Delete a message
// etc.
```

Awesome! So .. is this instance of a `QueueClient` thread safe .. meaning, can we create ONE instance of this (a singleton) and then let DI inject this same instance in, whenever required.

-or-

it's totally OK to create a new instance each time or have a scoped instance injected in?

I'm under the impression that it's ok to create a new instance, each time because the class is pretty light (mainly a wrapper for REST calls). I'm just not sure how this works with Authentication and stuff.

**Environment:**
 - Name and version of the Library package used: `Azure.Storage.Queues 12.3.2`]

**Comment by tg-msft** [comment] 2020-07-08 16:42
Yes, the `QueueClient` is thread-safe and generally any of the `*Client` types in an `Azure.*` namespace will be.  We recommend creating a single copy of the client.

Creating a new `QueueClient` won't hold a network connection or anything, but we do enough in our pipeline that it's a non-trivial allocation.  Closing as a duplicate of #8941.

**Closed by tg-msft** 2020-07-08 16:42 UTC
Labels: Client, Service Attention, Storage, customer-reported, needs-team-attention, question

**Comment by PureKrome** [comment] 2020-07-10 05:50
Thanks @tg-msft for the answer - that helps, big time!

I'll be subscribing to #8941 so I can see when the docs get updated. Great to see other people asking a similar question.

Also, thanks for the prompt reply too! 

Keep fighting to the good fight, team MS! 🍰
