### ISSUE TITLE
[EventHub] EventHub_InitialOffsetFromEnqueuedTime failing in nightly runs

### ISSUE THREAD

**Issue by v-yilinhu** [Azure/azure-sdk-for-net#26955] opened 2022-02-11 08:01 UTC
EventHub nightly test runs are failing with:

> Error message
> Microsoft.Azure.WebJobs.Host.Indexers.FunctionIndexingException : Error indexing method 'EventHubTestInitialOffsetFromEnqueuedTimeJobs.ProcessMultipleEvents'
> ----> System.InvalidOperationException : Multiple properties named 'ContentType' found in type 'EventData'.
> 
> 
> Stack trace
>    at Microsoft.Azure.WebJobs.Host.RecoverableException.TryRecover(ILogger logger) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Exceptions\RecoverableException.cs:line 81
>    at Microsoft.Azure.WebJobs.Host.Indexers.FunctionIndexer.IndexTypeAsync(Type type, IFunctionIndexCollector index, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Indexers\FunctionIndexer.cs:line 94
>    at Microsoft.Azure.WebJobs.Host.Indexers.FunctionIndexProvider.CreateAsync(CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Indexers\FunctionIndexProvider.cs:line 97
>    at Microsoft.Azure.WebJobs.Host.Indexers.FunctionIndexProvider.GetAsync(CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Indexers\FunctionIndexProvider.cs:line 69
>    at Microsoft.Azure.WebJobs.Host.Executors.JobHostContextFactory.Create(JobHost host, CancellationToken shutdownToken, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\JobHostContextFactory.cs:line 119
>    at Microsoft.Azure.WebJobs.JobHost.InitializeHostAsync(CancellationToken cancellationToken, TaskCompletionSource`1 initializationTask) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\JobHost.cs:line 347
>    at Microsoft.Azure.WebJobs.JobHost.StartAsyncCore(CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\JobHost.cs:line 95
>    at Microsoft.Azure.WebJobs.Host.EndToEndTests.WebJobsEventHubTestBase.BuildHost[T](Action`1 configurationDelegate, Action`1 preStartCallback) in /Users/runner/work/1/s/sdk/eventhub/Microsoft.Azure.WebJobs.Extensions.EventHubs/tests/WebJobsEventHubTestBase.cs:line 92
>    at Microsoft.Azure.WebJobs.Host.EndToEndTests.EventHubEndToEndTests.EventHub_InitialOffsetFromEnqueuedTime() in /Users/runner/work/1/s/sdk/eventhub/Microsoft.Azure.WebJobs.Extensions.EventHubs/tests/EventHubEndToEndTests.cs:line 411
>    at Microsoft.Azure.WebJobs.Host.EndToEndTests.EventHubEndToEndTests.EventHub_InitialOffsetFromEnqueuedTime() in /Users/runner/work/1/s/sdk/eventhub/Microsoft.Azure.WebJobs.Extensions.EventHubs/tests/EventHubEndToEndTests.cs:line 430
>    at Microsoft.Azure.WebJobs.Host.EndToEndTests.EventHubEndToEndTests.EventHub_InitialOffsetFromEnqueuedTime() in /Users/runner/work/1/s/sdk/eventhub/Microsoft.Azure.WebJobs.Extensions.EventHubs/tests/EventHubEndToEndTests.cs:line 430
>    at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.BlockUntilCompleted()
>    at NUnit.Framework.Internal.MessagePumpStrategy.NoMessagePumpStrategy.WaitForCompletion(AwaitAdapter awaiter)
>    at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.<>c__DisplayClass1_0.<Execute>b__0()
>    at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.RunTestMethodInThreadAbortSafeZone(TestExecutionContext context, Action action)
> --InvalidOperationException
>    at Microsoft.Azure.WebJobs.Host.Bindings.BindingDataProvider.FromType(Type type) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Bindings\BindingDataProvider.cs:line 103
>    at Microsoft.Azure.WebJobs.Host.Triggers.CustomTriggerArgumentBinding`2..ctor(ITriggerBindingStrategy`2 bindingStrategy, IConverterManager converterManager, FuncAsyncConverter converter, Type userType) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Triggers\TriggerArgumentBinding\CustomTriggerArgumentBinding.cs:line 37
>    at Microsoft.Azure.WebJobs.Host.Bindings.BindingFactoryHelpers.GetDirectTriggerBindingWorker[TMessage,TTriggerValue](ITriggerBi

For more details check here:

- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1355409&view=results
- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1351994&view=results

@jsquire for notification.

**Comment by jsquire** [comment] 2022-02-11 13:29
Duplicate of #21298.   Fixed by: #23495

**Closed by jsquire** 2022-02-11 13:29 UTC
Labels: Event Hubs, Client, needs-team-triage, test-reliability
