### ISSUE TITLE
[BUG]: EventHubClient + AAD Token - Put token failed. status-code: 400

### ISSUE THREAD

**Issue by vj-rajeshkumar** [Azure/azure-sdk-for-net#9388] opened 2020-01-08 21:43 UTC
**Describe the bug**

When attempting to make the ReceiveAsync call with a receiver created from the following EventHubClient, the call times out and throws.

Exception Message:
`{"Put token failed. status-code: 400, status-description: Property 'type' in the 'application-properties' section is either missing, has the wrong type, or has an unexpected value.."}`

***Exception or Stack Trace***

{"Put token failed. status-code: 400, status-description: Property 'type' in the 'application-properties' section is either missing, has the wrong type, or has an unexpected value.."}

   at Microsoft.Azure.EventHubs.Amqp.AmqpPartitionReceiver.<OnReceiveAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Azure.EventHubs.Amqp.AmqpPartitionReceiver.<OnReceiveAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.EventHubs.PartitionReceiver.<ReceiveAsync>d__31.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Office.Datacenter.HighAvailability.EventHub.EventHubMessaging.<>c__DisplayClass8_0.<<ReceiveMessagesUsingPartitionReaders>b__0>d.MoveNext() in E:\ControlPlane\ControlPlane\sources\dev\HighAvailability\src\PowerHarvesting\PowerHarvestingManager\EventHub\EventHubMessaging.cs:line 128

**To Reproduce**

TokenFetcher implements ITokenProvider interface:
```
TokenFetcher tokenProvider = new TokenFetcher(this.clientId, this.clientSecret, this.tenantId, $"https://eventhubs.azure.net/");
                this.ehc = EventHubClient.Create(
                    new Uri(string.Format("sb://{0}.servicebus.windows.net/", this.namespaceName)),
                    this.eventHubName,
                    tokenProvider);
```
GetTokenAsync implementation:
```
public Task<SecurityToken> GetTokenAsync(string appliesTo, TimeSpan timeout)
        {
            try
            {
                // Check to see if the token has expired before requesting one.
                // We will go ahead and request a new one if we are within 1 minute of the token expiring.
                if (this.token == null || this.token.ExpiresAtUtc < DateTime.UtcNow.AddMinutes(-1))
                {
                    Console.WriteLine("Renewing token. AppliesTo: {4}, Resource: {0}, clientId: {1}, clientSecretLength: {2}, tenantId: {3}", this.resource, this.clientId, this.clientSecret.Length, this.tenantId, appliesTo);

                    var context = new AuthenticationContext($"https://login.windows.net/{this.tenantId}");
                    var result = context.AcquireTokenAsync(this.resource, new ClientCredential(this.clientId, this.clientSecret)).ConfigureAwait(false).GetAwaiter().GetResult();

                    // If the token isn't a valid string, throw an error.
                    if (string.IsNullOrEmpty(result.AccessToken))
                    {
                        throw new Exception("Token result is empty!");
                    }

                    this.token = new SecurityToken(result.AccessToken, result.ExpiresOn.UtcDateTime, result.Authority, result.AccessTokenType);
                    Console.WriteLine("Token Type: {0}", this.token.TokenType);
                    Console.WriteLine("Token renewed successfully.");
                }

                return Task.FromResult<SecurityToken>(this.token);
            }
            catch (Exception e)
            {
                Console.WriteLine("Could not get a new token...");
                Console.WriteLine(e.Message);
                return null;
            }
        }
```

Call that throws:
```
var receiver = this.GetEventHubClient().CreateReceiver(consumerGroupName, partitionId, EventPosition.FromEnd());
try
                        {
                             events = await receiver.ReceiveAsync(maxMessageCount: 1, waitTime: TimeSpan.FromSeconds(15));
                        }
                        catch (Exception ex)
                        {
                            Console.WriteLine($"Partition Reader Error on Partition {partitionId}: {ex.Message}.");
                        }
```

**Expected behavior**
Receive is expected to succeed and retrieve messages from the given partition.

**Setup (please complete the following information):**
 - OS: Win10
 - IDE : VS2017
 - Microsoft.Azure.EventHubs 3.0.0

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [*] Bug Description Added
- [*] Repro Steps Added
- [*] Setup information Added

**Comment by jsquire** [comment] 2020-01-08 21:58
@serkantkaraca, @sjkwak, and @JamesBirdsall:  Would you be so kind as to offer your thoughts?

**Comment by jsquire** [comment] 2020-01-08 22:04
I'm going to defer to the folks that I looped in as the experts, but it looks to me that your `appliesTo` (aka token scope) isn't fully formed.   You may want to try testing with the following:

```csharp
"https://eventhubs.azure.net/.default"
```

**Comment by vj-rajeshkumar** [comment] 2020-01-08 22:19
That didn't work, this is the error that I get when I try suffixing with .default

> Renewing token. AppliesTo: amqps://[redacted].servicebus.windows.net/, Resource: https://eventhubs.azure.net/.default, clientId: [redacted], clientSecretLength: 32, tenantId: [redacted]
> Could not get a new token...
> AADSTS500011: The resource principal named https://eventhubs.azure.net/.default was not found in the tenant named [redacted]. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You might have sent your authentication request to the wrong tenant.

**Comment by serkantkaraca** [comment] 2020-01-08 22:19
The issue is here. Token type needs to be "jwt".

`this.token` = new SecurityToken(result.AccessToken, result.ExpiresOn.UtcDateTime, result.Authority, `result.AccessTokenType);`

Btw, why are you implementing a custom token provider instead of using built-in one?

**Comment by geektania** [comment] 2020-01-13 21:23
@vj-rajeshkumar we are closing this issue. Please let us know if you have any other question, we would be happy to reopen it

**Closed by geektania** 2020-01-13 21:23 UTC
Labels: Client, Event Hubs, Question, Service Attention, customer-reported
