### ISSUE TITLE
Congnitive Services Newtonsoft.Json assembly error

### ISSUE THREAD

**Issue by gogittossjx** [Azure/azure-sdk-for-net#4829] opened 2018-10-04 16:05 UTC
So i'm trying to use the cognitive services library in azure to do some image processing. The problem is that on run time, I get an error that states
"Could not load file or assembly 'Newtonsoft.Json, Version=9.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)". Ive been looking around and have yet to find an actual solution, can anyone help?

**Comment by shahabhijeet** [comment] 2018-10-05 03:41
@gogittossjx can you provide the following information
1. TargetFramework of your app
2. Full name and the version of the nuget SDK package
3. Any code that will help to reproduce this error.

**Comment by Petermarcu** [comment] 2019-07-30 00:12
Closing because we need more info. Let us know if you are still hitting this by opening a new issue.

**Closed by Petermarcu** 2019-07-30 00:12 UTC
Labels: Team
