### ISSUE TITLE
Search SDK: SDK 3.0.1 not setting suggesterName

### ISSUE THREAD

**Issue by justinhomes** [Azure/azure-sdk-for-net#2641] opened 2016-12-14 20:27 UTC
i have my index and suggester defined as below when creating the index, index is correctly created, suggester is also created by name is left out empty when you look at the azure portal. i am using azure search 3.0.1 sdk
```
i define my index smilar to below
  Definition = new Index()
                {
                    Name = EMRConsts.IndeName,
                    Fields = new[]
                    {
                        new Field("BMIPCSId", DataType.String)
                        {
                            IsKey = true,
                            IsSearchable = true,
                            IsFilterable = true,
                            IsSortable = true,
                            IsFacetable = false,
                            IsRetrievable = true
                        },
                        new Field("BMIPCSName", DataType.String)
                        {
                            IsKey = false,
                            IsSearchable = true,
                            IsFilterable = true,
                            IsSortable = false,
                            IsFacetable = false,
                            IsRetrievable = true
                        },
                        new Field("Id", DataType.Int32)
                        {
                            IsKey = false,
                            IsSearchable = false,
                            IsFilterable = true,
                            IsSortable = false,
                            IsFacetable = false,
                            IsRetrievable = true
                        }
                    },
                    Suggesters = new[]
                    {
                        new Suggester()
                        {
                            Name = EMRConsts.IndeName,
                            SearchMode = SuggesterSearchMode.AnalyzingInfixMatching,
                            SourceFields = new List<string>() {"BMIPCSName", "BMIPCSId"}
                        },
                    }
                }

```

**Comment by justinhomes** [comment] 2016-12-15 14:54
found out that i had to delete the entire search service and recreate it for it to work

**Comment by brjohnstmsft** [comment] 2016-12-15 16:17
@justinhomes I'm unable to reproduce this problem. Can you please clarify a few things?

- When you created the index above with the suggester, did you try retrieving it using the SDK? If so, was the suggester name set in the `Index` object returned by `Indexes.Get`?
- Are you still able to reproduce this problem? If so, please post a screenshot of what you observe in the Azure portal.
- Besides deleting and re-creating your service, did you change anything else about the code that creates the index?
- Did you try deleting and re-creating just the index before you deleted and re-created the service?

Please provide as much info as you can so we can diagnose this problem.

Thanks!

**Comment by brjohnstmsft** [comment] 2017-02-08 19:29
Closing this as we were unable to repro.

**Closed by brjohnstmsft** 2017-02-08 19:29 UTC
Labels: Search
