### ISSUE TITLE
Create Identity e2e tests for running in Azure Service Fabric

### ISSUE THREAD

**Issue by joshfree** [Azure/azure-sdk-for-net#15807] opened 2020-10-08 21:45 UTC
Tracking item to create new /sdk/e2e Azure.Identity smoke tests for running in Azure Service Fabric hosted environment.

1. Add new /sdk/e2e tests for Azure Service Fabric
2. Update Parent issue https://github.com/Azure/azure-sdk/issues/901 with instructions for Test team

**Comment by christothes** [comment] 2023-07-17 17:16
dupe of https://github.com/Azure/azure-sdk-for-net/issues/37471

**Closed by christothes** 2023-07-17 17:16 UTC
Labels: Client, Azure.Identity, test-enhancement
