### ISSUE TITLE
[BUG] Failure in creating MapsSearchClient object when used in the context of COM interop

### ISSUE THREAD

**Issue by jwangga** [Azure/azure-sdk-for-net#45734] opened 2024-08-29 21:51 UTC
### Library name and version

Azure.Maps.Search 2.0.0-beta.2

### Describe the bug

Instantiation of MapSearchClient class leads to this exception:
"Could not load file or assembly
'System.Diagnostics.DiagnosticSource, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its
dependencies. The system cannot find the file specified."
when the code is invoked by a COM client

### Expected behavior

It should work as expected - creating an object of the class

### Actual behavior

An exception is thrown when executing this line:
    var client = new MapsSearchClient(credential);

### Reproduction Steps

1. Create a .NET Framework library class project
2. Create a class and make it COM visible, as following:

namespace AzureMapWrapper
{
    [ClassInterface(ClassInterfaceType.AutoDual)]
    [ComVisible(true)]
    public class AzureMapCOMWrapper
    {
        
        [ComVisible(true)]
        public ArrayList GeocodeSite(string address)
        {
            string subscriptionKey = <AzureMapsKey>;
            var credential = new AzureKeyCredential(subscriptionKey);

            var client = new MapsSearchClient(credential);

            Response<GeocodingResponse> result = client.GetGeocoding(address);

            ArrayList coordinates = new ArrayList();
            var rawResponse = result.GetRawResponse();
            int status = rawResponse.Status;
            if (result.Value.Features.Count > 0)
            {
                coordinates.Add(result.Value.Features[0].Geometry.Coordinates[0]);
                coordinates.Add(result.Value.Features[0].Geometry.Coordinates[1]);
            }
            return coordinates;
        }
    }
}
3. Compile the project
4. Invoke the code in PowerShell like this:
        $obj = New-Object -ComObject "AzureMapWrapper.AzureMapCOMWrapper"
        $result = $obj.GeocodeSite("641 Avenue of the Americas New York, NY 10011")

    

### Environment

Windows Server Standard 2019 (v,1809)
.NET Framework 4.8
Visual Studio 2022 (17.4.3)

**Comment by jsquire** [comment] 2024-08-30 15:46
Hi @jwangga.   Thanks for reaching out and we regret that you're experiencing difficulties.   This problem generally occurs when the runtime is unable to load the needed set of dependencies; normally, this is due to a version mismatch due to an application reference that pins an older version either directly or as a transitive dependency.  Most often, this can be resolved by enabling automatic binding redirects or manually adding an explicit redirect.

Please see [this comment](https://github.com/Azure/azure-sdk-for-net/issues/39798#issuecomment-1811064283) and the following discussion in that issue for additional context.   You may also want to take a look at the discussion in the [.NET Runtime issue #93177](https://github.com/dotnet/runtime/issues/93177).

If a binding redirect does not resolve your issue, please provide a small, stand-alone application that reproduces the issue and we'd be happy to analyze and see if we're able to assist further.

**Comment by jwangga** [comment] 2024-08-30 17:32
Hi @jsquire, thanks for your response to my inquiry.  The auto binding redirect is enabled.  Attach is the test code to help reproduce the issue. The solution includes two projects:  AzureMapWrapper (library dll exposing the functionality vis COM), Test_AzureMap_Framework (console app that uses AzureMapWrapper class directly, that works as expected).
To reproduce the issue, compile AzureMaWrapper project, then invoke it from PowerShell with code like this:

$obj = New-Object -ComObject "AzureMapWrapper.AzureMapCOMWrapper"
$result = $obj.GeocodeSite("641 Avenue of the Americas New York, NY 10011")

[Test_AzureMap_Framework.zip](https://github.com/user-attachments/files/16820361/Test_AzureMap_Framework.zip)

**Comment by jsquire** [comment] 2024-09-09 16:04
Just a quick update, @m-redding is working on capturing the repro and determining the best path for assistance.

**Comment by m-redding** [comment] 2024-09-12 20:50
@jwangga Both repros you provided give the error "New-Object : Retrieving the COM class factory for component with CLSID {00000000-0000-0000-0000-000000000000} failed
due to the following error: 80040154 Class not registered", this might be a user-error because I haven't used COM interop. Are there any other repro steps besides compiling and running the commands?

**Comment by jwangga** [comment] 2024-09-12 21:32
@m-redding  This is the easiest way to reproduce the issue as far as I know. The component should be automatically registered when the project is built. Try these steps:

1. Start Visual Studio 2022 as administrator.
2. Open the solution - Test_AzureMap_Framework.sln.
3. Change line 29 in AzureMapWrapper.cs file with your Azure map key.
4. Build the project.
5. Open PowerShell.
6. Execute these two lines of code
    $obj = New-Object -ComObject "AzureMapWrapper.AzureMapCOMWrapper"
    $result = $obj.GeocodeSite("641 Avenue of the Americas New York, NY 10011")

You should see the error like this:
<img width="835" alt="image" src="https://github.com/user-attachments/assets/4a9f14b1-ed26-46d7-9d0a-4c3e52d963d7">

Thanks for looking into this issue!

**Comment by jsquire** [comment] 2024-09-12 22:10
@jwangga :  Passing thought, but would you please confirm your version of PowerShell?

**Comment by jwangga** [comment] 2024-09-12 22:19
@jsquire Here it is
Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      22621  3958

**Comment by jsquire** [comment] 2024-09-12 22:43
Thanks, @jwangga.   Are you able to repro the error if you install the latest PowerShell via [WinGet](https://learn.microsoft.com/powershell/scripting/install/installing-powershell-on-windows?view=powershell-7.4#install-powershell-using-winget-recommended).  I'm trying to understand if this may be an issue with the old built-in PowerShell not seeing a binding redirect or something COM specific.

**Comment by jwangga** [comment] 2024-09-13 00:14
@jsquire  Yes, the version of PowerShell does not seem to be a factor. See below:

<img width="855" alt="image" src="https://github.com/user-attachments/assets/d5248d55-28ae-40e2-b37c-3d2871bc074a">

**Comment by jsquire** [comment] 2024-09-13 16:23
@jwangga:  Thanks.   That's quite helpful.   That would seem to indicate that there's a binding redirect missing or that they're not being honored in the COM scenario.  We'll continue to investigate.

**Comment by m-redding** [comment] 2024-09-13 16:57
@jwangga I'm still getting the same error even with running as an admin. I will keep trying to debug from my end but if you think of any other things I might need to do let me know.

**Comment by jwangga** [comment] 2024-09-13 19:43
@m-redding A few things to check:
Build the debug version of the project
Run x64 version of PowerShell
If this still does not work, manually register the component.
Open cmd as admin, navigate to C:\Windows\Microsoft.NET\Framework64\v4.0.30319.
Execute this command
    RegAsm.exe /codebase <full-parth to AzureMapWrapper.dll>

**Comment by jwangga** [comment] 2024-09-13 19:46
*Execute this command:
RegAsm.exe /codebase full-path-to AzureMapWrapper.dll

**Comment by richlander** [comment] 2024-09-18 21:09
Why are you creating a COM component? Modern PowerShell uses .NET Core and this library also supports .NET Core. It would be easier to just load a .NET Core component into PowerShell.

**Comment by jwangga** [comment] 2024-09-19 01:23
I use PowerShell just to make it easy to illustrate the issue or reproduce the issue.  The actual application I am working on is a VC++/MFC-based business application. It has been using COM interop of .NET to access many modern services including BIGN Maps. Now, I want to add the support for Azure Map as BING Map is going to retire soon.

**Comment by jwangga** [comment] 2024-10-04 17:11
@jsquire , @m-redding Just want to check if there is any update. We have completed code changes related to support Azure Map in our products and are waiting to conduct end-to-end testing. Eager to have this show stop issue resolved. Thanks.

**Comment by m-redding** [comment] 2024-10-04 17:37
Hi @jwangga!
I was able to manually register the components and see a similar exception to the one you reported here, but with a different library not being loaded. After looking through the app, I believe this is an issue with COM and binding redirects, not the Azure SDK.
@richlander might have a better idea for how to move forward. If not, I'm in the process of finding the right place to transfer this issue.

**Comment by jwangga** [comment] 2024-10-04 20:28
Thanks for the update. Based on the error message, it appears that one of the components that Azure Map SKD uses has a dependency on System.Diagnostics.DiagnosticSource, Version=6.0.0.0. What if to find that component and upgrade it to a newer version? Would that solve the issue?

**Comment by m-redding** [comment] 2024-10-31 15:03
Transferred to the runtime repo. I tried reaching out offline to a few people but wasn't able to find a resolution. Sorry to bump you around @jwangga hopefully you can get a proper fix from someone with more COM-specific experience. https://github.com/dotnet/runtime/issues/109417

**Closed by m-redding** 2024-10-31 15:03 UTC
Labels: Client, customer-reported, question, needs-team-attention, Maps
