### ISSUE TITLE
[BUG] Azure.Monitor.OpenTelemetry.Exporter does not honor x-forwarded-for headers on ACA

### ISSUE THREAD

**Issue by onionhammer** [Azure/azure-sdk-for-net#42850] opened 2024-03-20 20:31 UTC
### Library name and version

Azure.Monitor.OpenTelemetry.Exporter, 1.3.0-beta.1

### Describe the bug

When switching from application insights (Microsoft.ApplicationInsights.AspNetCore) to Aspire's OpenTelemetry model, all requests are logged from the ACA's ingress IP, and the external IP forwarded (x-forwarded-for) by the ingress is no longer honored.

### Expected behavior

X-Forwarded-For should contain the end user's actual IP address, and should appear in application insights as the 'Client IP address'

### Actual behavior

Every `request` in app insights on azure container apps now originates from the same IP per ACA cluster

Client IP address | 172.169.202.11 |  
-- | -- | --
City | Des Moines

### Reproduction Steps

1. Create an aspire app
2. Configure Azure Monitor open telemetry exporter
3. Deploy to azure container apps

If this is not immediately clear what the issue is (to whichever contributor owns this area) please let me know and I can put together a minimal repro in a separate repository.

**Comment by TimothyMothra** [comment] 2024-03-20 20:51
Adding some extra details for context:

This was accomplished via `ClientIpHeaderTelemetryInitializer`.
https://github.com/microsoft/ApplicationInsights-dotnet/blob/bd8b0c25712e6f3c5275ae06b0f0e9331340fee4/NETCORE/src/Microsoft.ApplicationInsights.AspNetCore/TelemetryInitializers/ClientIpHeaderTelemetryInitializer.cs#L17

**Comment by onionhammer** [comment] 2024-03-21 16:53
@TimothyMothra Would it be doable to workaround this with a telemetry processor? Or should I just wait for a fix

**Comment by TimothyMothra** [comment] 2024-03-28 18:25
Hi, sorry for the delay. Our docs aren't up to date on this subject (I will follow up on this) and I went digging for more information.

First, I want to set some context.
Our Exporter doesn't "collect" any data. We only pass along the information provided by the Instrumentation libraries. In this case, that would be [OpenTelemetry.Instrumentation.AspNetCore](https://github.com/open-telemetry/opentelemetry-dotnet/tree/main/src/OpenTelemetry.Instrumentation.AspNetCore). 

That instrumentation library has some customization options, which is documented in their readme.
For your issue specifically, if you set the `client.address` attribute, our Azure Monitor Exporter will pick up this value.
Your config will look something like this:

```csharp
builder.Services.Configure<AspNetCoreTraceInstrumentationOptions>(options =>
{
    options.EnrichWithHttpRequest = (activity, httpRequest) =>
    {
        // get the actual IP from the httpRequest object
        activity.SetTag("client.address", "10.10.10.10");
    };
});
```

As an alternate approach, I was pointed to this article:
https://learn.microsoft.com/aspnet/core/host-and-deploy/proxy-load-balancer#forwarded-headers
If you configure the Forwarded Headers Middleware, this might do the work for you. I haven't personally tested this.

**Comment by onionhammer** [comment] 2024-03-29 15:39
Hi @TimothyMothra 

I would encourage the team here to think about the broader picture - I assume we want good defaults that "just work" out of the box, here;

1. User creates a new 'aspire' app
2. User un-comments / enables the `UseAzureMonitor`
3. User deploys to Azure Container Apps with azd

This scenario should *just work* with very little messing around without writing a ton of code that you just kinda "have to know".

@davidfowl

**Comment by davidfowl** [comment] 2024-03-29 15:45
I agree with you @onionhammer. In the next preview of Aspire, [we automatically turn on the forwarded headers middleware](https://github.com/dotnet/aspire/issues/290) for any web projects with endpoints. That should solve the problem.

**Comment by onionhammer** [comment] 2024-03-29 16:04
> n the next preview of Aspire, [we automatically turn on the forwarded headers middleware](https://github.com/dotnet/aspire/issues/290) for any web projects with endpoints.

This library will also likely have to be updated so it cares about that middleware

**Comment by davidfowl** [comment] 2024-03-29 18:15
Right it seems like we still need to propagate the client IP to the activity. Is that right @TimothyMothra ?

**Comment by TimothyMothra** [comment] 2024-04-04 22:23
Yes, that's correct. But this cannot be done by default as per the specification ([link](https://github.com/open-telemetry/semantic-conventions/blob/main/docs/http/http-spans.md#:~:text=request%20was%20retried.-,http.request.header.%3Ckey%3E,Opt%2DIn,-url.scheme)).
In .NET, users can opt-in via the example I shared above.

**Comment by onionhammer** [comment] 2024-04-04 23:46
The opt-in does not work

**Comment by onionhammer** [comment] 2024-06-06 22:45
Any update on this?

**Comment by davidfowl** [comment] 2024-06-06 22:56
@sampa-msft can you follow up here?

**Comment by davidfowl** [comment] 2024-06-06 22:56
BTW @onionhammer we enable XFF by default in aspire apps during deployment

**Comment by onionhammer** [comment] 2024-06-06 22:59
> BTW @onionhammer we enable XFF by default in aspire apps during deployment

I saw that; the 'ASPNETCORE_FORWARDEDHEADERS_ENABLED' 'true'? Doesn't seem to do much in my testing

**Comment by davidfowl** [comment] 2024-06-06 23:03
What did you test?

**Comment by onionhammer** [comment] 2024-06-07 14:51
> What did you test?

Adding the above header;

```bicep
  { name: 'ASPNETCORE_FORWARDEDHEADERS_ENABLED', value: 'true' }
```

And adding this:
![image](https://github.com/Azure/azure-sdk-for-net/assets/969938/4a267b09-3e52-40fd-8887-f0056356e3b6)

![image](https://github.com/Azure/azure-sdk-for-net/assets/969938/0dc670cb-3163-433c-bdab-39c655d60082)

the result:
![image](https://github.com/Azure/azure-sdk-for-net/assets/969938/33b66f6c-c8af-4b2b-86de-bebbc9afc7fd)

**Comment by davidfowl** [comment] 2024-06-07 15:50
When you enable the forwarded headers, it sets those options by default and enables the middleware.

https://github.com/dotnet/aspnetcore/blob/10517269f40d53eb22cce6b4d520ed27ed1e1b9f/src/DefaultBuilder/src/ForwardedHeadersOptionsSetup.cs#L27

**Comment by onionhammer** [comment] 2024-06-07 18:50
Basically I was just trying to throw the kitchen sink at it, but no matter what I do it always just shows the same internal IP address since switching from app insights to otel

**Comment by davidfowl** [comment] 2024-06-07 20:59
I think the main thing to figure out is where the issue is. If XFF doesn't work, then we should get it fixed.

**Comment by onionhammer** [comment] 2024-06-07 21:20
I don't think it's an ACA issue, since this works OOTB if you use the Application Insights SDK. I think the culprit is this library.

**Comment by onionhammer** [comment] 2024-06-14 19:41
> @sampa-msft can you follow up here?

Bump

**Comment by samsp-msft** [comment] 2024-06-14 22:14
I think @davidfowl tagged the wrong person, so I didn't get notified.

Just to clarify, I believe this application using OTel SDK with the AzureMonitorExporter, rather than the classic ApplicationInsights SDK or OTLP.
Very few Otel attributes are set automatically in ASP.NET Core. Most are set through the OTel ASP.NET instrumentation package. Doing a quick spelunk of that code, the only time we seem to be setting the `client.address` attribute is in the [case of it being a GRPC request](https://github.com/open-telemetry/opentelemetry-dotnet-contrib/blob/c513d144c503f4d61e90686a52bd187a43a11ef7/src/OpenTelemetry.Instrumentation.AspNetCore/Implementation/HttpInListener.cs#L366).

The AzureMonitor exporter seems to have additional setting of the client.address [here](https://github.com/Azure/azure-sdk-for-net/blob/2005968e1c11111e5b3342cfae6e8e9c198b3b0a/sdk/monitor/Azure.Monitor.OpenTelemetry.Exporter/src/Customizations/Models/TelemetryItem.cs#L44) so that is probably where this issue belongs. @vishweshbankwar who changed this code as part of  https://github.com/Azure/azure-sdk-for-net/commit/962ba5081f7a6474a6edac91d72cfed3ff52ed64.

I suspect that the fix needs to be in the latter.

**Comment by onionhammer** [comment] 2024-06-17 13:35
Ok, so inconsistent behavior between gRPC and HTTP?

@TimothyMothra @vishweshbankwar

**Comment by vishweshbankwar** [comment] 2024-06-19 18:32
@onionhammer - 

The workaround you shared [here](https://github.com/Azure/azure-sdk-for-net/issues/42850#issuecomment-2168651866) is correct and also [recommended](https://learn.microsoft.com/en-us/azure/azure-monitor/app/opentelemetry-add-modify?tabs=aspnetcore#set-the-user-ip) one.

> So… this is definitely a bug or is this a wontfix ?

This is by design.

Attributes added by default on activity by the instrumentation libraries is outside the scope of exporter. Exporter simply maps attributes from spans to Application Insights data model fields. There is **no** change that is needed at the exporter level.

[OpenTelemetry.Instrumentation.AspNetCore](https://www.nuget.org/packages/OpenTelemetry.Instrumentation.AspNetCore) only sets the required fields from the [spec](https://github.com/open-telemetry/semantic-conventions/blob/main/docs/http/http-spans.md#http-server). Any additional attributes that are needed can be added via provided [Enrich](https://github.com/open-telemetry/opentelemetry-dotnet-contrib/tree/main/src/OpenTelemetry.Instrumentation.AspNetCore#enrich) APIs or processor. There are ongoing discussions about providing specific controls on the optional fields. https://github.com/dotnet/runtime/issues/103302.

gRPC part is still experimental and may change in future based on the final [spec](https://github.com/open-telemetry/semantic-conventions/blob/main/docs/rpc/rpc-spans.md)

**Comment by onionhammer** [comment] 2024-06-19 19:11
> [OpenTelemetry.Instrumentation.AspNetCore](https://www.nuget.org/packages/OpenTelemetry.Instrumentation.AspNetCore) only sets the required fields from the [spec](https://github.com/open-telemetry/semantic-conventions/blob/main/docs/http/http-spans.md#http-server).

client.address is one of the fields in the spec though?

**Comment by vishweshbankwar** [comment] 2024-06-20 21:55
> > [OpenTelemetry.Instrumentation.AspNetCore](https://www.nuget.org/packages/OpenTelemetry.Instrumentation.AspNetCore) only sets the required fields from the [spec](https://github.com/open-telemetry/semantic-conventions/blob/main/docs/http/http-spans.md#http-server).
> 
> client.address is one of the fields in the spec though?

Yes, but not required. I'd recommend you to open the issue [here](https://github.com/open-telemetry/opentelemetry-dotnet-contrib/issues) with your ask. Closing this issue as exporter is working as intended.

**Closed by vishweshbankwar** 2024-06-20 21:55 UTC
Labels: Service Attention, Client, customer-reported, question, needs-team-attention, Monitor - Exporter

**Comment by vishweshbankwar** [comment] 2024-06-21 00:13
@onionhammer - I have opened a separate issue for tracking this https://github.com/Azure/azure-sdk-for-net/issues/44687. The change could also be done in the distro(Azure.Monitor.OpenTelemetry.AspNetCore)

**Comment by onionhammer** [comment] 2024-06-21 13:40
> @onionhammer - I have opened a separate issue for tracking this #44687. The change could also be done in the distro(Azure.Monitor.OpenTelemetry.AspNetCore)

So should it still be an issue in https://www.nuget.org/packages/OpenTelemetry.Instrumentation.AspNetCore ?

**Comment by vishweshbankwar** [comment] 2024-06-21 17:05
> > @onionhammer - I have opened a separate issue for tracking this #44687. The change could also be done in the distro(Azure.Monitor.OpenTelemetry.AspNetCore)
> 
> So should it still be an issue in https://www.nuget.org/packages/OpenTelemetry.Instrumentation.AspNetCore ?

I checked and there is a similar ask already: https://github.com/open-telemetry/opentelemetry-dotnet-contrib/issues/1786.

Clarifying couple things here

When using `Azure.Monitor.OpenTelemetry.Exporter` along with `OpenTelemetry.Instrumentation.AspNetCore`, the attribute needs to be added either by default(or via some config) by `OpenTelemetry.Instrumentation.AspNetCore` or via `Enrich`/`Processor`.  My previous comments were taking this scenario in consideration(the package mentioned in this issue)

`Azure.Monitor.OpenTelemetry.AspNetCore` is a [Distro](https://opentelemetry.io/docs/concepts/distributions/#what-is-a-distribution) that includes `Azure.Monitor.OpenTelemetry.Exporter` and `OpenTelemetry.Instrumentation.AspNetCore`. This package enables some settings by default and enabling collection of LocationIP by default could be one of them (#44687 covers this). One possible solution is for the distro to simply use the solution from https://github.com/open-telemetry/opentelemetry-dotnet-contrib/issues/1786 (if implemented).

**Comment by onionhammer** [comment] 2024-06-21 19:14
I don't really care about the implementation details; at the end of the day, Aspire's default behavior for newly created apps should be that this client.address is set properly to the source IP address.
