### ISSUE TITLE
[BUG] [Azure.Search.Documents] Scoring profiles with functions creates exception

### ISSUE THREAD

**Issue by pekspro** [Azure/azure-sdk-for-net#16570] opened 2020-11-04 11:15 UTC
**Describe the bug**
I want to create s scoring profile without any functions on an index.

**Expected behavior**
This should work.

**Actual behavior (include Exception or Stack Trace)**
An **ArgumentOutOfRangeException** is thrown with message:

    Unknown ScoringFunctionAggregation value. 

**To Reproduce**
The following code shows the problem:

	public class Document
	{
	    [SimpleField(IsKey = true)]
	    public string ID { get; set; }
	
	    [SearchableField(IsSortable = false, IsFilterable = true)]
	    public string Title { get; set; } = string.Empty;
	}
	
	static async Task Main(string[] args)
	{
	    const string indexname = "testindex";
	    const string profilename = "testprofile";
	
	    var IndexClient = 
	        new SearchIndexClient
	            (
	                new Uri("https://myurl"), 
	                new AzureKeyCredential("mykey")
	            );
	
	
	    FieldBuilder bulder = new FieldBuilder();
	    SearchIndex index = new SearchIndex(indexname, bulder.Build(typeof(Document)));
	
	    index.DefaultScoringProfile = profilename;
	
	    index.ScoringProfiles.Add(new ScoringProfile(profilename)
	    {
	        TextWeights = new TextWeights(new Dictionary<string, double>()
	        {
	            { nameof(Document.Title), 2 },
	        }),
	        // Setting FunctionAggregation seems to solve the problem
	        // but I do not understand why. I do not see any difference in
	        // Azure with this, but the exception goes away.
	        // FunctionAggregation = ScoringFunctionAggregation.Sum
	    });
	
	    // Next line will throw an System.ArgumentOutOfRangeException with the message:
	    // "Unknown ScoringFunctionAggregation value."
	    await IndexClient.CreateIndexAsync(index);
	
	}

**Environment:**
 - Azure.Search.Documents 11.1.1
 - Windows 10, .NET Core 3.1.9
 - Visual Studio 16.

**Comment by jsquire** [comment] 2020-11-04 13:55
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by heaths** [comment] 2020-11-04 18:23
Several attributes in the REST swagger were not properly authored, and the generated code is expecting a value. I fixed a bunch of these issues in https://www.nuget.org/packages/Azure.Search.Documents/11.2.0-beta.1. Do you get the same behavior with 11.2.0-beta.1?

**Comment by heaths** [comment] 2020-11-04 19:45
I'm unable to reproduce this with the latest source (post-11.2.0-beta.1). It would be helpful if you also included the full exception info including message and stack trace.

**Comment by pekspro** [comment] 2020-11-05 06:18
Thanks for the quick response @heaths. I did run the code earlier mentioned with post-11.2.0-beta.1 and I got the same exception.

Here is the stacktrace:

	   at Azure.Search.Documents.Indexes.Models.ScoringFunctionAggregationExtensions.ToScoringFunctionAggregation(String value)
	   at Azure.Search.Documents.Indexes.Models.ScoringProfile.DeserializeScoringProfile(JsonElement element)
	   at Azure.Search.Documents.Indexes.Models.SearchIndex.DeserializeSearchIndex(JsonElement element)
	   at Azure.Search.Documents.IndexesRestClient.<CreateAsync>d__7.MoveNext()
	   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
	   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
	   at Azure.Search.Documents.Indexes.SearchIndexClient.<CreateIndexAsync>d__29.MoveNext()
	   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
	   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
	   at AzureSearchIssueTest.Program.<Main>d__1.MoveNext() in C:\....\Program.cs:line 121
   
   
And here properties from the exception, copied directly from VS and this terrible format ;-)

	-		ex	{"Unknown ScoringFunctionAggregation value. (Parameter 'value')"}	System.Exception {System.ArgumentOutOfRangeException}
			ActualValue	null	object
	+		Data	{System.Collections.ListDictionaryInternal}	System.Collections.IDictionary {System.Collections.ListDictionaryInternal}
			HResult	-2146233086	int
			HelpLink	null	string
	+		InnerException	null	System.Exception
			Message	"Unknown ScoringFunctionAggregation value. (Parameter 'value')"	string
			ParamName	"value"	string
			Source	"Azure.Search.Documents"	string
			StackTrace	"   at Azure.Search.Documents.Indexes.Models.ScoringFunctionAggregationExtensions.ToScoringFunctionAggregation(String value)\r\n   at Azure.Search.Documents.Indexes.Models.ScoringProfile.DeserializeScoringProfile(JsonElement element)\r\n   at Azure.Search.Documents.Indexes.Models.SearchIndex.DeserializeSearchIndex(JsonElement element)\r\n   at Azure.Search.Documents.IndexesRestClient.<CreateAsync>d__7.MoveNext()\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()\r\n   at Azure.Search.Documents.Indexes.SearchIndexClient.<CreateIndexAsync>d__29.MoveNext()\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()\r\n   at AzureSearchIssueTest.Program.<Main>d__1.MoveNext() in C:\\Users\\per-erik.kristensson\\source\\repos\\AzureSearchIssueTest\\AzureSearchIssueTest\\Program.cs:line 121"	string
	+		TargetSite	{Azure.Search.Documents.Indexes.Models.ScoringFunctionAggregation ToScoringFunctionAggregation(System.String)}	System.Reflection.MethodBase {System.Reflection.RuntimeMethodInfo}

**Comment by heaths** [comment] 2020-11-05 19:32
If the value was `null` - which it should be given your code sample - it shouldn't even be deserialized hence never entering that function that is throwing because it doesn't recognize whatever value was passed.

I checked in a change yesterday that doesn't really change that code much - not in release builds anyway. Can you [enable logging content](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/core/Azure.Core/samples/Diagnostics.md#Logging) and paste only the request and response bodies (no headers, which will contain PII):

```c#
async Task Main()
{
  using AzureEventSourceListener listener = AzureEventSourceListener.CreateConsoleLogger();
  SearchClientOptions options = new SearchClientOptions
  {
    Diagnostics =
    {
      IsLoggingContentEnabled = true
    }
  };
  var client = new SearchIndexClient(..., options);
}
```

We'll also have a new beta coming out next week you can try that include my change.

**Comment by pekspro** [comment] 2020-11-06 06:17
Sure. I updated my code to this:

    public class Document
    {
        [SimpleField(IsKey = true)]
        public string ID { get; set; }

        [SearchableField(IsSortable = false, IsFilterable = true)]
        public string Title { get; set; } = string.Empty;
    }

    static async Task Main(string[] args)
    {
        const string indexname = "testindex";
        const string profilename = "testprofile";

        using AzureEventSourceListener listener = AzureEventSourceListener.CreateConsoleLogger(EventLevel.Verbose);
        SearchClientOptions options = new SearchClientOptions
        {
            Diagnostics =
            {
              IsLoggingContentEnabled = true
            }
        };

        var IndexClient =
            new SearchIndexClient
                (
                    new Uri("https://myurl"),
                    new AzureKeyCredential("mykey"),
                    options
                );


        FieldBuilder bulder = new FieldBuilder();
        SearchIndex index = new SearchIndex(indexname, bulder.Build(typeof(Document)));

        index.DefaultScoringProfile = profilename;

        index.ScoringProfiles.Add(new ScoringProfile(profilename)
        {
            TextWeights = new TextWeights(new Dictionary<string, double>()
            {
                { nameof(Document.Title), 2 },
            }),
            // Setting FunctionAggregation seems to solve the problem
            // but I do not understand why. I do not see any difference in
            // Azure with this, but the exception goes away.
            // FunctionAggregation = ScoringFunctionAggregation.Sum
        });

        // Next line will throw an System.ArgumentOutOfRangeException with the message:
        // "Unknown ScoringFunctionAggregation value."
        try
        {
            await IndexClient.CreateIndexAsync(index);
        }
        catch(Exception ex)
        {
            await Task.Delay(2000);
            Console.WriteLine();
            Console.WriteLine("***** Exception " + ex.Message);
            Console.WriteLine(ex.StackTrace);
        }

        Console.ReadKey();
    }

And this is my project file:

	<Project Sdk="Microsoft.NET.Sdk">
	
	  <PropertyGroup>
	    <OutputType>Exe</OutputType>
	    <TargetFramework>netcoreapp3.1</TargetFramework>
	  </PropertyGroup>
	
	  <ItemGroup>
	    <PackageReference Include="Azure.Search.Documents" Version="11.2.0-beta.1" />
	  </ItemGroup>
	
	</Project>
	
And I got this output:

	[Informational] Azure-Core: Request [b6b05098-6b9f-4f07-96ca-c717bc045cb9] POST ....
	(header removed)
	[Verbose] Azure-Core: Request [b6b05098-6b9f-4f07-96ca-c717bc045cb9] content: {"name":"testindex","fields":[{"name":"ID","type":"Edm.String","key":true,"retrievable":true,"searchable":false,"filterable":false,"sortable":false,"facetable":false},{"name":"Title","type":"Edm.String","key":false,"retrievable":true,"searchable":true,"filterable":true,"sortable":false,"facetable":false}],"scoringProfiles":[{"name":"testprofile","text":{"weights":{"Title":2}}}],"defaultScoringProfile":"testprofile"}
	[Informational] Azure-Core: Response [b6b05098-6b9f-4f07-96ca-c717bc045cb9] 201 Created (01.8s)
	(header removed)
	elapsed-time:1060
	OData-Version:4.0
	Preference-Applied:REDACTED
	Strict-Transport-Security:REDACTED
	Date:Fri, 06 Nov 2020 06:07:40 GMT
	Content-Type:application/json; odata.metadata=minimal
	Expires:-1
	Content-Length:965
	
	[Verbose] Azure-Core: Response [b6b05098-6b9f-4f07-96ca-c717bc045cb9] content: {"@odata.context":"https://[servicename].search.windows.net/$metadata#indexes/$entity","@odata.etag":"\"0x8D8821A4541676C\"","name":"testindex","defaultScoringProfile":"testprofile","fields":[{"name":"ID","type":"Edm.String","searchable":false,"filterable":false,"retrievable":true,"sortable":false,"facetable":false,"key":true,"indexAnalyzer":null,"searchAnalyzer":null,"analyzer":null,"synonymMaps":[]},{"name":"Title","type":"Edm.String","searchable":true,"filterable":true,"retrievable":true,"sortable":false,"facetable":false,"key":false,"indexAnalyzer":null,"searchAnalyzer":null,"analyzer":null,"synonymMaps":[]}],"scoringProfiles":[{"name":"testprofile","functionAggregation":null,"text":{"weights":{"Title":2.0}},"functions":[]}],"corsOptions":null,"suggesters":[],"analyzers":[],"tokenizers":[],"tokenFilters":[],"charFilters":[],"encryptionKey":null,"similarity":{"@odata.type":"#Microsoft.Azure.Search.BM25Similarity","k1":null,"b":null}}
	
	***** Exception Unknown ScoringFunctionAggregation value. (Parameter 'value')
	   at Azure.Search.Documents.Indexes.Models.ScoringFunctionAggregationExtensions.ToScoringFunctionAggregation(String value)
	   at Azure.Search.Documents.Indexes.Models.ScoringProfile.DeserializeScoringProfile(JsonElement element)
	   at Azure.Search.Documents.Indexes.Models.SearchIndex.DeserializeSearchIndex(JsonElement element)
	   at Azure.Search.Documents.IndexesRestClient.CreateAsync(SearchIndex index, CancellationToken cancellationToken)
	   at Azure.Search.Documents.Indexes.SearchIndexClient.CreateIndexAsync(SearchIndex index, CancellationToken cancellationToken)
	   at AzureSearchIssueTest.Program.Main(String[] args) in C:\repos\AzureSearchIssueTest\AzureSearchIssueTest\Program.cs:line 134

I will repeat this test next week when the new beta is out.

**Comment by heaths** [comment] 2020-11-06 18:05
> `"functionAggregation":null`

That's almost definitely causing the problem, but during deserialization we should've been skipping it, unless that particular change (our generated code has been through quite a few changes in the last couple months) occured after 11.2.0-beta.1. But for beta 2 next week it should be resolved. Let me know.

**Comment by pekspro** [comment] 2020-11-11 06:44
@heaths, I have now verified to the bug no longer occur in Azure.Search.Documents version 11.2.0-beta.2.

**Closed** 2020-11-11 18:18 UTC
Labels: Client, Search, bug, customer-reported, needs-team-attention
