### ISSUE TITLE
Engineering: Design for Validation of Nuget Packages in the Development Feed

### ISSUE THREAD

**Issue by jsquire** [Azure/azure-sdk-for-net#15584] opened 2020-09-30 20:49 UTC
# Summary

In order to ensure the validity of the Nuget packages produced by the engineering pipeline and ensure that any issues are detected before a public release is performed, some form of automated validation should be performed against the nightly build artifacts published to our development feed.

# Scope of Work

 - Design an approach to automate validation for all packages in the repository that are published to the development feed.

- Once the design has been discussed and solidified, break down the work required and create the issues needed for its implementation.

# Success Criteria

- A design proposal has been created for an approach to validate Nuget packages from our development feed.

- The design has been shared with the engineering team and other stakeholders for feedback;  any tweaks or iterations to the design have been captured and the design has been updated.

- Issues to track any work that results form the design/review have been filed and triaged.

**Comment by kurtzeborn** [comment] 2020-11-11 00:23
What type of validation are we talking about here.  Is it just pull down the packages and determine that they're properly constructed and signed NuGet packages or is it to load the packages in a process as our customers would and exercise them?

For the first type of validation, we already have this issue (https://github.com/Azure/azure-sdk-for-net/issues/16094) tracking some improvements to the validation we already do for our NuGet packages.

For the second type of validation, we already have the smoke tests which run nightly and pull against the dev feed by default.

**Comment by jsquire** [comment] 2020-11-11 13:47
If I recall, this was filed by request from Wes after it was discovered that our release process injected a dependency from an non-public package feed into our NuGet packages, which rendered them unusable by customers, since not all of their dependencies could be resolved.    

I believe the intent for this was to have something download the package, inspect it, and ensure that customers outside of Microsoft would be able to make use of it.

**Comment by kurtzeborn** [comment] 2020-11-24 23:59
Assigning this to @weshaggard to determine if this is a duplicate of work already being tracked elsewhere.

**Comment by weshaggard** [comment] 2020-11-30 22:31
Thanks @jsquire I've added an item for verifying the package dependencies to our overall package checks issue at https://github.com/Azure/azure-sdk-for-net/issues/16094. We also hope to get some of this package verification covered by our smoke testing which should be consume the packages like our customers do.

**Closed by weshaggard** 2020-11-30 22:31 UTC
Labels: Automation, Central-EngSys, EngSys
