### ISSUE TITLE
[Storage] ErrorCode: AuthorizationPermissionMismatch when access azure queue with aad auth

### ISSUE THREAD

**Issue by huliang-microsoft** [Azure/azure-sdk-for-net#15279] opened 2020-09-21 03:08 UTC
Hello, we are trying to use aad auth of a service principal to connect an azure queue.

I am following the sample code using QueueServiceClient.

```     
            // Create a client that can authenticate using our token credential
            QueueServiceClient service = new QueueServiceClient(new Uri("https://speaker0reco0westus0dev2.queue.core.windows.net"), credential);

            // Make a service request to verify we've successfully authenticated
            var response = service.GetProperties();

            var queueClient = service.CreateQueue("testqueue2").Value;
            queueClient.SendMessage("abc");
```

service.GetProperties() returns 200 and CreateQueue() call succeeded, I can see the queue was created in the storage account. but the SendMessage() call failed with 403. "'This request is not authorized to perform this operation using this permission."

I have added the Azure Storage API permission in the service principal and also added the service principal as an owner in the storage account owner list.

Could anyone let me know what I am missing here?

Thanks

Hua

**Comment by jsquire** [comment] 2020-09-21 12:39
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by amnguye** [comment] 2020-09-22 20:23
Do you know what your role is assigned to your aad identity that you are using to access your storage queues?

https://docs.microsoft.com/en-us/azure/storage/common/storage-auth-aad#azure-built-in-roles-for-blobs-and-queues

**Comment by rgrace-puck** [comment] 2023-05-03 20:44
@amnguye @jsquire 
Hello, I'm having the same issue but with blobs. I left a comment on a similar issue in the python repository here:
https://github.com/Azure/azure-sdk-for-python/issues/24282#issuecomment-1533605256 

Part of my comment will be copied from there with some additional C# code and version details.
Note: Some values such as the storage account name and other information have a placeholder value (e.g. "mystaccount")

---
My user account has the "Storage Blob Data Contributor" role assigned to it.

When I run the following command via Azure CLI (logged in with `az login`):
```
az storage blob list --blob-endpoint "https://mystaccount.blob.core.windows.net/" -c "mycontainer" --auth-mode login
```
It returns no errors. I also tested without the role assignment and it gives me an error.

Using `DefaultAzureCredential` in my .NET code, it recognizes the `AzureCliCredential` and selects it.
Then, I attempt the following request to the storage account (via the SDK):
```
AzureCliCredential.GetToken invoked. Scopes: [ https://storage.azure.com/.default ] ParentRequestId: REDACTED
AzureCliCredential.GetToken succeeded. Scopes: [ https://storage.azure.com/.default ] ParentRequestId: REDACTED ExpiresOn: 2023-05-03T20:39:00.0000000+00:00
DefaultAzureCredential credential selected: Azure.Identity.AzureCliCredential
```
```
GET https://mystaccount.blob.core.windows.net/mycontainer?restype=container&comp=list&prefix=MyPrefix&include=Tags
```

Which returns "Status: 403 (This request is not authorized to perform this operation using this permission.)"
Even after adding the "Storage Blob Data Reader" role it still does NOT work.

**Program.cs**
```cs
services.AddAzureClients(builder =>
{
     builder.AddBlobServiceClient(new Uri("https://mystaccount.blob.core.windows.net/"));
                    
     builder.UseCredential(new DefaultAzureCredential());
});
```

**MyBlobService.cs**
```cs
private readonly BlobContainerClient _blobContainerClient;

public MyBlobService(BlobServiceClient blobServiceClient)
{
   _blobContainerClient = blobServiceClient.GetBlobContainerClient("mycontainer");
}

public AsyncPageable<BlobItem> GetBlobsByPrefix(string prefix)
{
    var blobs = _blobContainerClient.GetBlobsAsync(BlobTraits.Tags, BlobStates.None, prefix);
    return blobs;
}
```

When trying to `await foreach` over the `AsyncPageable` is when the error occurs.

.NET version: 6.0
App type: Azure Function App

Installed packages:
Azure.Storage.Blobs - 12.16.0
Microsoft.Extensions.Azure - 1.6.3

Implicitly installed packages:
Azure.Core - 1.31.0
Azure.Identity - 1.7.0

There are more packages in each list and I can provide them if needed.

**Comment by pfesenmeier** [comment] 2023-05-17 21:47
I am experiencing the same error from the `await foreach` as @rgrace-puck. 
I am running  the `dotnet` cli inside WSL2 and logged in to Azure via the `az` cli.
Oddly enough, the code runs without errors when invoked from VSCode.

**Comment by rgrace-puck** [comment] 2023-05-23 19:34
UPDATE: I believe this problem is specific to the function apps but I'm still looking into it.

I created a standalone console app using **Azure.Storage.Blobs** and **Azure.Identity** with the `Storage Blob Data Contributor` role assigned to my account:
```cs
using Azure.Identity;
using Azure.Storage.Blobs;

var serviceClient = new BlobServiceClient(new Uri("https://mystaccount.blob.core.windows.net/"), new DefaultAzureCredential());
var containerClient = serviceClient.GetBlobContainerClient("mycontainer");

await foreach (var blob in containerClient.GetBlobsAsync())
{
    Console.WriteLine(blob.Name);
}
```
...which worked without any errors. Apologies for any confusion caused by this.

**Comment by amnguye** [comment] 2023-05-23 23:24
Issue not caused by the storage SDK. Also the OP did not respond to my first response. Closing issue.

**Closed by amnguye** 2023-05-23 23:24 UTC
Labels: Storage, Service Attention, Client, question

**Comment by rgrace-puck** [comment] 2023-05-25 19:46
For posterity, the 403 error was happening because I'm trying to access tags on the blobs.
This operation requires the "Storage Blob Data Owner" role for some reason. After assigning the role, everything works fine.

https://learn.microsoft.com/en-us/azure/storage/blobs/storage-blob-index-how-to?tabs=azure-portal#get-set-and-update-blob-index-tags
