### ISSUE TITLE
[BUG] Missing UTC timezone issue in case DateTime.MaxValue

### ISSUE THREAD

**Issue by amamounelsayed** [Azure/azure-sdk-for-net#15343] opened 2020-09-22 23:08 UTC
**Describe the bug**
Please provide the description of issue you're seeing.
There is returning inconsistence format regarding the ExpiresAtUtc.
We can see this line does not return time in UTC like line 186.
https://github.com/Azure/azure-sdk-for-net/blob/f83d1822f337c7eb2d8d4014b4932eb81a9b2979/sdk/servicebus/Microsoft.Azure.ServiceBus/src/Message.cs#L183

**Expected behavior**
What is the expected behavior?
DateTime.MaxValue.ToUniversalTime();

**Actual behavior (include Exception or Stack Trace)**
What is the actual behavior?
DateTime.MaxValue

**To Reproduce**
Steps to reproduce the behavior (include a code snippet, screenshot, or any additional information that might help us reproduce the issue)

1. Create service bus using CLI for premium or standard.
2. Time to live is set to DateTime.MaxValue.

**Environment:**
 - Name and version of the Library package used: [e.g. Azure.Storage.Blobs 12.2.0] 
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): [e.g. Azure AppService or Windows 10 .NET Framework 4.8]
 - IDE and version : [e.g. Visual Studio 16.3]

**Comment by axisc** [comment] 2020-09-24 23:53
@amamounelsayed Thanks for raising this issue. Could you elaborate the scenario where this code is impacting?

**Comment by amamounelsayed** [comment] 2020-09-24 23:59
> @amamounelsayed Thanks for raising this issue. Could you elaborate the scenario where this code is impacting?

Thank you so much sir, the contract is to have the value in UTC format, ExpiresAtUtc which includes the time zone, when the user have unbound time to live this value throws exception on Function side.

**Comment by axisc** [comment] 2020-11-11 00:50
@amamounelsayed Thanks for the details. Unfortunately, this may be a breaking change.

We will track this internally and will fix it in the upcoming release with the higher major version.

**Comment by SeanFeldman** [comment] 2020-11-11 01:37
@axisc as the issue is not fixed, may I suggest to keep the public issue opened and reference it internally? When it's fixed it would be the right thing to close this public issue to indicate it's fixed and deployed. Otherwise it gives a wrong impression. Thank you.

**Comment by jsquire** [comment] 2023-07-24 20:14
The `Microsoft.Azure.ServiceBus` package has been deprecated and is only receiving critical security and bug fixes.   Unfortunately, the fix for this does not meet that bar and is not currently planned.  As Josh mentioned, this is not an issue with the current generation package, `Azure.Messaging.ServiceBus`.

Closing this out.

**Closed by jsquire** 2023-07-24 20:14 UTC
Labels: Service Bus, Service Attention, Client, customer-reported, bug
