### ISSUE TITLE
Members in PublicIPAddress of NetworkInterfaceIPConfiguration are 'null' 

### ISSUE THREAD

**Issue by tanmayshete** [Azure/azure-sdk-for-net#2410] opened 2016-09-30 07:39 UTC
I'm trying to fetch PublicIPAddress of an Azure Network Interface. But, all the members are shown as 'null' except 'id' in the object of NetworkInterfaceIPConfiguration.

I'm interested in member PublicIPAddress.IpAddress.

Note that the Azure Portal shows Public IP address of the same network interface. Hence, public IP address is assigned to this interface. 

Package Details:
Microsoft.Azure.Management.Network
Version: 7.1.1-Preview
Date Published on NuGet: 09/21/2016

**Comment by cormacpayne** [comment] 2016-10-04 20:09
@DeepakRajendranMsft Hey Deepak, would you mind taking a look at this issue?

**Comment by MikhailTryakhov** [comment] 2018-07-12 22:35
outdated

**Comment by MikhailTryakhov** [comment] 2018-07-12 22:35
@dsgouda  please close

**Comment by dsgouda** [comment] 2018-07-12 22:38
@MikhailTryakhov please provide details about the issue or link if it has been discussed elsewhere

**Comment by avijitgupta** [comment] 2018-07-13 17:21
This is the general model for all resource references in Microsoft.Network. If you get a nic, only the ID of public IP address is given out. You can get the public IP address using Get-AzureRmPublicIPAddress to get the IP address. This is by design

**Comment by dsgouda** [comment] 2018-07-13 18:02
Thanks @avijitgupta 
please make sure this is fixed in the rest spec moving forward

**Closed by dsgouda** 2018-07-13 18:02 UTC
Labels: Network
