### ISSUE TITLE
Do we support sendX5c parameter while creating AzureCredentials ? 

### ISSUE THREAD

**Issue by asranja** [Azure/azure-sdk-for-net#12864] opened 2020-06-18 06:17 UTC
ADAL currently supports [this](https://docs.microsoft.com/en-us/dotnet/api/microsoft.identitymodel.clients.activedirectory.authenticationcontext.acquiretokenasync?view=azure-dotnet#Microsoft_IdentityModel_Clients_ActiveDirectory_AuthenticationContext_AcquireTokenAsync_System_String_Microsoft_IdentityModel_Clients_ActiveDirectory_IClientAssertionCertificate_System_Boolean_). 

Is there a way we can pass the sendX5c parameter while creating the AzureCredentials ?

**Comment by yungezz** [comment] 2020-06-18 10:12
this is ask in Track1 runtime auth lib.

**Comment by asranja** [comment] 2020-06-18 11:04
Thanks @yungezz Any timelines for the same ? 

Currently is there a way we can fetch access token using ADAL and use it to create the AzureCredentials?

**Comment by yungezz** [comment] 2020-06-18 13:17
HI @AlexGhiondea could you pls help to look at this ask on Track1 runtime auth lib? pls help to redirect if you're not owner. thanks.

**Comment by pharring** [comment] 2020-07-29 00:11
Dupe of #12130 ?

**Comment by AlexGhiondea** [comment] 2020-07-29 00:58
@asranja, @yungezz can you share more information about this? Which auth library are you referring to?

**Comment by pharring** [comment] 2020-08-05 16:21
I presume this is about Azure.Identity. Here's what I came up with for our product:
```csharp
using System;
using System.Security.Cryptography.X509Certificates;
using System.Threading;
using System.Threading.Tasks;
using Azure.Core;
using Azure.Identity;
using Microsoft.Identity.Client;

namespace Microsoft.[REDACTED].Authority
{
    /// <summary>
    /// A <see cref="TokenCredential"/> that uses a client certificate and "Subject Name + Issuer"
    /// to authenticate as a client application. For this to work, the client application (AAD app)
    /// must be configured for SNI using the SNIConfig tool. The certificate's issuer must be one of
    /// the issuers approved for use in the AAD tenant.
    /// </summary>
    /// <remarks>
    /// This class may be replaced when
    /// <see cref="https://github.com/Azure/azure-sdk-for-net/issues/12130"/> is resolved.
    /// </remarks>
    public sealed class ClientCertificateSniCredential : TokenCredential
    {
        private readonly IConfidentialClientApplication _app;

        /// <summary>
        /// Construct a new <see cref="ClientCertificateSniCredential"/> instance.
        /// </summary>
        /// <param name="authority">The authority is a combination of the login
        /// endpoint for the AAD instance and a tenant. e.g. https://login.microsoftonline.com/contoso.onmicrosoft.com
        /// </param>
        /// <param name="clientId">The AAD application's client ID.</param>
        /// <param name="certificate">The certificate to use for authentication. The certificate's
        /// subject name and issuer are validated by the <paramref name="authority"/>.</param>
        public ClientCertificateSniCredential(Uri authority, Guid clientId, X509Certificate2 certificate)
        {
            if (authority is null)
            {
                throw new ArgumentNullException(nameof(authority));
            }

            if (certificate is null)
            {
                throw new ArgumentNullException(nameof(certificate));
            }

            if (!authority.IsAbsoluteUri)
            {
                throw new ArgumentException("The authority must be an absolute URI.", nameof(authority));
            }

            _app = ConfidentialClientApplicationBuilder.Create(clientId.ToString())
                    .WithAuthority(authority)
                    .WithCertificate(certificate)
                    .Build()
            );
        }

        public override AccessToken GetToken(TokenRequestContext requestContext, CancellationToken cancellationToken)
            => FromAuthenticationResult(AcquireTokenAsync(requestContext, cancellationToken).GetAwaiter().GetResult());

        public override async ValueTask<AccessToken> GetTokenAsync(TokenRequestContext requestContext, CancellationToken cancellationToken)
            => FromAuthenticationResult(await AcquireTokenAsync(requestContext, cancellationToken).ConfigureAwait(false));

        private async Task<AuthenticationResult> AcquireTokenAsync(TokenRequestContext requestContext, CancellationToken cancellationToken)
        {
            // WithSendX5C(true) is what enables SNI authentication.
            return await _app.AcquireTokenForClient(requestContext.Scopes).WithSendX5C(true).ExecuteAsync(cancellationToken).ConfigureAwait(false);
        }

        private static AccessToken FromAuthenticationResult(AuthenticationResult result)
            => new AccessToken(result.AccessToken, result.ExpiresOn);
    }
}
```

It's derived from `TokenCredential`, so it can be used in place of `ClientCertificateTokenCredential` -- it's not quite a drop-in replacement since it doesn't use `TokenCredentialOptions` to get the authority, but it should be obvious how to adapt it.

**Closed** 2020-08-27 08:00 UTC
Labels: Authentication, AutoRest Runtime, Mgmt, customer-reported, feature-request, needs-author-feedback, no-recent-activity
