### ISSUE TITLE
Doesn't build with VS 2015 w/ update 3 installed

### ISSUE THREAD

**Issue by gitsparty** [Azure/azure-sdk-for-net#3009] opened 2017-03-30 18:45 UTC
Try to build this project on VS 2015 (IIRC with update 3). I get the following build error. I don't see Microsoft.DotNet.Props install on my machine. 

1>------ Build started: Project: HttpRecorder, Configuration: Debug Any CPU ------
1>  C:\Program Files\dotnet\dotnet.exe build "C:\Users\nagen_000\Source\Repos\azure-sdk-for-net\src\TestFramework\Microsoft.Azure.Test.HttpRecorder" --configuration Debug --no-dependencies
1>  Microsoft (R) Build Engine version 15.1.548.43366
1>  Copyright (C) Microsoft Corporation. All rights reserved.
1>C:\Users\nagen_000\Source\Repos\azure-sdk-for-net\src\TestFramework\Microsoft.Azure.Test.HttpRecorder\HttpRecorder.xproj(7,3): error MSB4019: The imported project "C:\Program Files\dotnet\sdk\1.0.1\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
1>  Build FAILED.
1>C:\Users\nagen_000\Source\Repos\azure-sdk-for-net\src\TestFramework\Microsoft.Azure.Test.HttpRecorder\HttpRecorder.xproj(7,3): error MSB4019: The imported project "C:\Program Files\dotnet\sdk\1.0.1\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
1>      0 Warning(s)
1>      1 Error(s)
1>  Time Elapsed 00:00:00.05
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

**Comment by jaredmoo** [comment] 2017-04-03 18:18
See #2922

**Comment by jaredmoo** [comment] 2017-04-03 18:26
I made a few fixes in my branch https://github.com/jaredmoo/azure-sdk-for-net/tree/globaljson

**Comment by sphibbs** [comment] 2017-04-14 18:47
Duplicate of #2815. Will be completed at the end of this sprint.

**Closed by sphibbs** 2017-04-14 18:47 UTC
