### ISSUE TITLE
90% of the ServiceBusReceiver.CloseAsync() calls throws "System.TimeoutException: The operation did not complete within the allocated time 00:01:00 for object drain"

### ISSUE THREAD

**Issue by zhaomao** [Azure/azure-sdk-for-net#45477] opened 2024-08-12 22:42 UTC
### Library name and version

Azure.Messaging.ServiceBus 7.17.5

### Query/Question

**feel free ping [mazhao@microsoft.com](mailto:mazhao@microsoft.com) on Teams to discuss

90% of the ServiceBusReceiver.CloseAsync() calls throws the following exception, why and how to resolve ?**

System.TimeoutException: The operation did not complete within the allocated time 00:01:00 for object drain.
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Azure.Amqp.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at Microsoft.Azure.Amqp.ReceivingAmqpLink.c.DrainAsync b__35_1(IAsyncResult r)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azure.Messaging.ServiceBus.Amqp.AmqpReceiver.CloseAsync d__74.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azure.Messaging.ServiceBus.ServiceBusReceiver.CloseAsync d__40.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

<img width="569" alt="image" src="https://github.com/user-attachments/assets/870cc0b9-c5a7-455b-8790-eb3871ffa9f0">

        calling code: CloseReceiver(), see below

        private ServiceBusReceiver m_Receiver;
        public async Task CloseReceiverAsync()
        {
            if (m_Receiver != null && m_Receiver.IsClosed == false)
            {
                await m_Receiver.CloseAsync().ConfigureAwait(false);
                m_Receiver = null;
            }
        }

        public void CloseReceiver()
        {
            CloseReceiverAsync().GetAwaiter().GetResult();
        }

### Environment

.NET framework

**Comment by zhaomao** [comment] 2024-08-12 22:44
please ping mazhao@microsoft.com on Teams to discuss

**Comment by zhaomao** [comment] 2024-08-12 22:51
System.TimeoutException: The operation did not complete within the allocated time 00:01:00 for object drain.
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Azure.Amqp.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at Microsoft.Azure.Amqp.ReceivingAmqpLink.<>c.<DrainAsyc>b__35_1(IAsyncResult r)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azure.Messaging.ServiceBus.Amqp.AmqpReceiver.<CloseAsync>d__74.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azure.Messaging.ServiceBus.ServiceBusReceiver.<CloseAsync>d__40.MoveNext()
--- End of stack trace from previous location where exception was thrown ---

**Comment by zhaomao** [comment] 2024-08-12 22:54
the call stack above seems to be missing some info, here is the screen shot

<img width="640" alt="image" src="https://github.com/user-attachments/assets/a8547823-fd7d-4fb1-bbec-58a4c7736b85">

**Comment by zhaomao** [comment] 2024-08-13 01:10
@JoshLove-msft   can you please take a look?

**Comment by jsquire** [comment] 2024-08-13 13:13
Hi @zhaomao.  Thanks for reaching out and we regret that you're experiencing difficulties.  The error that you're seeing indicates that a service operation took longer to complete than your configured `TryTimeout`.    The client has no insight nor influence over this behavior.   

This may be due to application patterns, such as your sync-over-async use in `CloseReceiver` above or other causes of thread pool congestion and resource starvation, such as a higher degree of concurrency than your host can process in the allowed timeout.  It may also be due to slow/unstable network resources or a potential service issue.

As next steps, I'd suggest taking a process dump and analyzing your async stack and thread pool health.  If all looks good there, I'd suggest opening an IcM for the Service Bus team.

**Comment by zhaomao** [comment] 2024-08-14 02:47
@jsquire  I opened IcM to the ServiceBus team, here is the answer:

"When you close the receiver, the client is sending one final receive request as drain. Since your subscription is most of the time throttled for exceeding concurrent requests, that last receive request is also throttled, and the response comes back with some delay. That's why 1 minute is not enough to close the receiver. For your specific case, use a higher timeout to close. something like 5 minutes. closing is the important part. Or retry multiple times or ignore the exception on close call"

- Why close receiver will sending a final receive request? what if that request return a message?
- When I retry, should I check Receiver.IsClosed ? I looked at the code, the first thing CloseAsync() does is set _isClosed = true, which means Receiver.IsClosed == true does not indicate the link is successfully closed?

**Comment by zhaomao** [comment] 2024-08-14 03:56
public override async Task CloseAsync(CancellationToken cancellationToken)
        {
            if (_closed)
            {
                return;
            }

            _closed = true;

            RequestResponseLockedMessages.Dispose();

            if (_receiveLink?.TryGetOpenedObject(out var link) == true)
            {
                cancellationToken.ThrowIfCancellationRequested<TaskCanceledException>();

                // Allow in-flight messages to drain so that they do not remain locked by the service after closing the link.

                if (!_isSessionReceiver && link.LinkCredit > 0)
                {
                    await link.DrainAsyc(cancellationToken).ConfigureAwait(false);
                }

                await _receiveLink.CloseAsync(CancellationToken.None).ConfigureAwait(false);
            }

            if (_managementLink?.TryGetOpenedObject(out var _) == true)
            {
                cancellationToken.ThrowIfCancellationRequested<TaskCanceledException>();
                await _managementLink.CloseAsync(CancellationToken.None).ConfigureAwait(false);
            }

            _receiveLink?.Dispose();
            _managementLink?.Dispose();
        }

**Comment by jsquire** [comment] 2024-08-14 14:16
@zhaomao:  No, there will be no retry in the above scenario.   The drain in this scenario exists to help reset message locks only; it does not return messages to the caller.  In the case that this fails with a timeout or other error, messages will become available to read again once the lock expires.

The root cause here was identified by the service team in your IcM response - you're being throttled.   While the client will respect throttling and apply an additional delay to implicit retries when receiving, the CloseAsync operation has no knowledge that you are being throttled, as the service apparently does not return the expected AMQP condition for a drain scenario.

The timeout in this case is benign, so long as you're not depending on another node being able to pick up the locked messages before the lock expires.   If you are, then the suggested mitigation would be to delay closing when being throttled, if you do need to ensure messages are unlocked.

**Comment by jsquire** [comment] 2024-08-14 14:16
@m-redding, @JoshLove-msft, @conniey:   What are your thoughts on wrapping the drain and ignoring timeouts?

**Comment by zhaomao** [comment] 2024-08-14 16:55
Thank you @jsquire 
Will the Receiver be successfully closed in my case with drain throttled/timeout? Looking at the code, when link.drainasync throws exception, _receiveLink.CloseAsync will not be executed, so I assume the receiver link won't close?

            if (!_isSessionReceiver && link.LinkCredit > 0)
            {
                await link.DrainAsyc(cancellationToken).ConfigureAwait(false);
            }

            await _receiveLink.CloseAsync(CancellationToken.None).ConfigureAwait(false);

**Comment by jsquire** [comment] 2024-08-14 16:57
No, if the Close operation throws, the receiver's AMQP link will remain open until either it idles out (60 seconds by default), the associated ServiceBusClient is closed/disposed, or you call Close again.

**Comment by zhaomao** [comment] 2024-08-14 17:05
@jsquire  
- call ServiceBusClient.DisposeAsync() successfully will close all receiver links ?
- call close again will just return and do nothing, since the initial close call already set _closed = true, retry closeAync will not work, am i right ?
    public override async Task CloseAsync(CancellationToken cancellationToken)
    {
        if (_closed)
        {
            return;
        }

        _closed = true;

- what is considered idle ? no ReceiveMessageAsync() called ?

**Comment by conniey** [comment] 2024-08-14 18:10
> @m-redding, @JoshLove-msft, @conniey: What are your thoughts on wrapping the drain and ignoring timeouts?

I don't know if that is a great idea because the amount of "wait" time is indeterminate.  I don't know what the throttling backoffs are so I can imagine customers thinking their application is hanging on close.

**Comment by zhaomao** [comment] 2024-08-14 18:15
@conniey  should drain block receivelink close ? based on the explanation above, drain only reset message lock. Can i force close the link, I don't really care about drain operation, but I do care about the receive link need to be closed, otherwise, the receive request will stay alive and count for concurrent receive request count while no message available.

**Comment by jsquire** [comment] 2024-08-14 19:39
> * call ServiceBusClient.DisposeAsync() successfully will close all receiver links
Correct.   The client owns the connection for anything spawned from it.  When the client is closed/disposed, the connection is closed which closes any open links using it.

> call close again will just return and do nothing, since the initial close call already set _closed = true, retry closeAync will not work, am i right ?
You're right; that's my bad.   I skipped over the eager flag set.

> what is considered idle ? no ReceiveMessageAsync() called ?
Correct.  Pedantically, this is "no operations on the receiver link" but without the receive call, you have no message to call the settlement operations with.

> if so, if I call ReceiveMessageAsync() again after 5 minutes with the same receiver, will the receiver link automatically re-opened? or my call will fail and I have to re-create receiver ?
Closing a client results in a terminal state.   You cannot use the receiver further.  Any attempt to perform an operation would throw an `ObjectDisposedException`

**Comment by jsquire** [comment] 2024-08-14 19:41
> > @m-redding, @JoshLove-msft, @conniey: What are your thoughts on wrapping the drain and ignoring timeouts?
> 
> I don't know if that is a great idea because the amount of "wait" time is indeterminate. I don't know what the throttling backoffs are so I can imagine customers thinking their application is hanging on close.

That's a fair point.   It would end up looking like a hang with no feedback to tell you that something unexpected happened.    We could, however, capture any exception from drain, ensure the link gets closed, and then bubble the exception.    I like that.

**Comment by zhaomao** [comment] 2024-08-20 17:20
please let me know which package version will have your fix, thanks

**Closed** 2024-08-27 22:35 UTC
Labels: Service Bus, Client, customer-reported, question, issue-addressed
