### ISSUE TITLE
Move generator HttpPipelineExtensions methods to Azure.Core

### ISSUE THREAD

**Issue by ShivangiReja** [Azure/azure-sdk-for-net#27483] opened 2022-03-10 19:55 UTC
### Library name

Azure.Core

### Please describe the feature.

 [HttpPipelineExtensions](https://github.com/Azure/autorest.csharp/blob/feature/v3/src/assets/Generator.Shared/HttpPipelineExtensions.cs) class exists in [Generator.Shared](https://github.com/Azure/autorest.csharp/tree/feature/v3/src/assets/Generator.Shared) and it has ProcessMessage methods which we use in DPG methods. [Here](https://github.com/azure-sdk/azure-sdk-for-net/blob/1de75b8f07a23a7c2dd82361590e0f40e24b5c42/sdk/deviceupdate/Azure.IoT.DeviceUpdate/src/Generated/DeviceUpdateClient.cs#L133) is an example of how do we use these methods in DPG.

I think we should move all the methods from [HttpPipelineExtensions](https://github.com/Azure/autorest.csharp/blob/feature/v3/src/assets/Generator.Shared/HttpPipelineExtensions.cs) to Azure.Core as it can be useful for the cases when someone has to handwrite the DPG methods.

**Comment by ShivangiReja** [comment] 2022-03-10 19:56
CC: @annelo-msft

**Comment by heaths** [comment] 2022-10-25 17:51
Do we make these public extension methods, or as shared source in Core?

**Comment by annelo-msft** [comment] 2023-08-16 21:09
Closing as duplicate of https://github.com/Azure/azure-sdk-for-net/issues/32006

**Closed by annelo-msft** 2023-08-16 21:09 UTC
Labels: Client, Azure.Core, MQ
