### ISSUE TITLE
[BUG] Many abandoned messages in queues/topics

### ISSUE THREAD

**Issue by Alex-Boo** [Azure/azure-sdk-for-net#24639] opened 2021-10-11 12:34 UTC
**Description**
Recently we migrated from WindowsAzure.ServiceBus to Azure.Messaging.ServiceBus. After deployment to production we noticed that processing of messages is slow down and there are many abandoned messages in queue/topics.

There is screenshot of metrics before deployment (WindowsAzure.ServiceBus):
![image](https://user-images.githubusercontent.com/9656679/136792772-1401ec23-aa11-4e79-8e6a-9fdfa8aa9b06.png)

And there is screenshot of current state (Azure.Messaging.ServiceBus):
![image](https://user-images.githubusercontent.com/9656679/136792915-457db06f-967c-444b-9a05-bceba59f7a75.png)

We investigated the issue and found:
1. We do not abandon messages in code, it happens inside of Azure.Messaging.ServiceBus
2. Topics and queues are affected
2. We have the issue only if ServiceBusReceiverOptions.PrefetchCount is not defined. 

**Expected behavior**
No abandoned messages if we do not abandon them directly in code.

**Actual behavior (include Exception or Stack Trace)**
Lot's of abandoned massages came from the library.

**To Reproduce**
I was able to reproduce the problem in console application: 

```csharp
	class Program
	{
		static void Main(string[] args)
		{
			var receiver = new Receiver4();
			receiver.ReadMessages().GetAwaiter().GetResult();			
		}
	}

    class Receiver4
    {
        private const string ConnectionString = "connection string";

        public async Task ReadMessages()
        {
            var sbOptions = new ServiceBusClientOptions()
            {
                RetryOptions = new ServiceBusRetryOptions
                {
                    Mode = ServiceBusRetryMode.Fixed,
                    Delay = TimeSpan.FromSeconds(1),
                    MaxDelay = TimeSpan.FromSeconds(5),
                    MaxRetries = 1,
                    TryTimeout = TimeSpan.FromSeconds(30)
                }
            };

            ServiceBusClient client = new ServiceBusClient(ConnectionString, sbOptions);

            ServiceBusReceiverOptions options = new ServiceBusReceiverOptions
            {
            };

            var receiver = client.CreateReceiver("alex-test", options);

            var receivedMessages = new List<ServiceBusReceivedMessage>();
            while (true)
            {
                Console.WriteLine("Reading");

                var messages = await receiver.ReceiveMessagesAsync(128, TimeSpan.FromSeconds(5)).ConfigureAwait(false);

                Console.WriteLine($"{messages.Count} were received");

                foreach (var message in messages)
                {
                    Console.WriteLine(message.Body.ToString());

                    receivedMessages.Add(message);
                }

                await Task.Delay(100);

                Console.WriteLine("Completing");

                foreach (var message in receivedMessages)
                {
                    try
                    {
                        await receiver.CompleteMessageAsync(message).ConfigureAwait(false);
                    }
                    catch (ServiceBusException ex) when (ex.Reason == ServiceBusFailureReason.MessageLockLost)
                    {
                        Console.WriteLine("MessageLockLost, {0}", message.Body.ToString());
                    }
                }

                receivedMessages.Clear();

                Console.WriteLine("Completed");

                ConsoleKeyInfo key = Console.ReadKey();

                if (key.KeyChar == 's')
                {
                    break;
                }
            }
        }
    }
```

**Environment:**
 - Name and version of the Library package used: Azure.Messaging.ServiceBus 7.3.0 
 - Hosting platform or OS and .NET runtime version Azure Cloud Services
 - IDE and version : Visual Studio 16.11.4

**Comment by JoshLove-msft** [comment] 2021-10-11 20:19
Hi @Alex-Boo,
The SDK won't abandon messages for you when using the ServiceBusReceiver. It seems that the lock is being lost for some of the messages. Are you using the default 30 second lock duration for your queue? If so, I wouldn't expect the lock to be lost when processing 128 messages. Can you include the output from your test console app?

**Comment by Alex-Boo** [comment] 2021-10-13 11:27
What do you mean by "shutting down"? CloseAsync?
No, I am not. I provided example of code above.

**Comment by JoshLove-msft** [comment] 2021-10-13 17:21
Yes, I meant using CloseAsync. The reason I asked is because I didn't see all 128 messages being received. 

However, looking at the output I see that it is taking 14 seconds to complete 46 messages. Can you tell me what kind of namespace you are using (basic, standard, premium)?

**Comment by Alex-Boo** [comment] 2021-10-14 15:14
We use Standard tier for service bus.

There are other settings for queue:
![image](https://user-images.githubusercontent.com/9656679/137346512-3aa03e69-9254-4107-90d0-3365d1c77b9b.png)

**Comment by Alex-Boo** [comment] 2021-10-15 19:28
Exactly, every time when I run the console app there are no exceptions but I can see abandoned messages. Count of such messages is different, usually 2-7. 
We have other queues in the same service bus in production where we use WindowsAzure.ServiceBus library and no abandoned messages there.

**Comment by yvgopal** [comment] 2021-11-05 01:17
@Alex-Boo Could you give me your namespace name, and entity name (queue or topic name) where you reproduced this issue? Also the timestamp.

**Comment by Alex-Boo** [comment] 2021-11-05 16:37
> 
> 
> @Alex-Boo Could you give me your namespace name, and entity name (queue or topic name) where you reproduced this issue? Also the timestamp.

I answered by email.

**Comment by yvgopal** [comment] 2021-11-06 02:27
@Alex-Boo  thanks. I got the email. Upon investigation, I found that no messages were abandoned. But many messages were received and unlocked. Unlock happens when client receives messages when no receiver is waiting for messages. In your case, you are calling receive with message count 128, but receive call doesn't have to wait for all 128 messages to be received. Receive call returns with anywhere between 1 and 128 messages. But messages keep coming to the receiver, and it unlocks them as there is no receive call waiting.
Unlock is a variation of abandon, and our metrics are reporting that operation as abandon. We will fix it in the service. It is not a client issue.
I am closing this issue as it is a service side metrics issue.

**Closed by yvgopal** 2021-11-06 02:27 UTC
Labels: Service Bus, Service Attention, Client, customer-reported, question

**Comment by Alex-Boo** [comment] 2021-11-10 11:55
> Unlock is a variation of abandon, and our metrics are reporting that operation as abandon. We will fix it in the service. It is not a client issue.

@yvgopal, thank you for explanation. 
Can we track somehow fixing this issue on server side?
