### ISSUE TITLE
[Synapse] TestListSparkApplications test is failing in nightly runs

### ISSUE THREAD

**Issue by ShivangiReja** [Azure/azure-sdk-for-net#19151] opened 2021-03-03 00:31 UTC
TestListSparkApplications test is failing with:

> Failed TestListSparkApplications [324 ms]
  
> Error Message:
   System.ArgumentException : Expected: IEnumerable But was: null (Parameter 'actual')
  Stack Trace:
     at NUnit.Framework.Internal.ConstraintUtils.RequireActual[T](Object actual, String paramName, Boolean allowNull)
   at NUnit.Framework.Constraints.CollectionConstraint.ApplyTo[TActual](TActual actual)
   at NUnit.Framework.Constraints.NotConstraint.ApplyTo[TActual](TActual actual)
   at NUnit.Framework.Assert.That[TActual](TActual actual, IResolveConstraint expression, String message, Object[] args)
   at NUnit.Framework.CollectionAssert.IsNotEmpty(IEnumerable collection, String message, Object[] args)
   at NUnit.Framework.CollectionAssert.IsNotEmpty(IEnumerable collection)
   at Azure.Analytics.Synapse.Monitoring.Tests.MonitoringClientLiveTests.TestListSparkApplications() in D:\a\_work\1\s\sdk\synapse\Azure.Analytics.Synapse.Monitoring\tests\MonitoringClientLiveTests.cs:line 43
   at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.BlockUntilCompleted()
   at NUnit.Framework.Internal.MessagePumpStrategy.NoMessagePumpStrategy.WaitForCompletion(AwaitAdapter awaitable)
   at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
   at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.<>c__DisplayClass1_0.<Execute>b__0()

For more details check here:
* https://dev.azure.com/azure-sdk/internal/_build/results?buildId=761217&view=results
* https://dev.azure.com/azure-sdk/internal/_build/results?buildId=758726&view=results
* https://dev.azure.com/azure-sdk/internal/_build/results?buildId=756146&view=results
* https://dev.azure.com/azure-sdk/internal/_build/results?buildId=753892&view=results
* https://dev.azure.com/azure-sdk/internal/_build/results?buildId=751694&view=results

**Comment by chamons** [comment] 2021-03-29 17:21
Duplicate of https://github.com/Azure/azure-sdk-for-net/issues/18957

**Closed by chamons** 2021-03-29 17:21 UTC
Labels: Client, Synapse, test-reliability
