### ISSUE TITLE
[BUG] Newtonsoft.Json.JsonSerializationException when calling MessageSenderAsyncCollector.AddAsync on a ServiceBusMessage object

### ISSUE THREAD

**Issue by hossam-nasr** [Azure/azure-sdk-for-net#29408] opened 2022-06-22 02:39 UTC
### Library name and version

Microsoft.Azure.ServiceBus 5.2.0

### Describe the bug

If you try calling `MessageSenderAsyncCollector.AddAsync()` (ServiceBus output binding), passing in a Service Bus `Message` type object as the argument, you will get the following error:

```
 Newtonsoft.Json.JsonSerializationException : Error getting value from 'ExpiresAtUtc' on 'Microsoft.Azure.ServiceBus.Message'. ---> System.InvalidOperationException : Operation is not valid due to the current state of the object.
   at Microsoft.Azure.ServiceBus.Message.SystemPropertiesCollection.ThrowIfNotReceived()
   at Microsoft.Azure.ServiceBus.Message.get_ExpiresAtUtc()
   at lambda_method1137(Closure ,Object )
   at Newtonsoft.Json.Serialization.ExpressionValueProvider.GetValue(Object target)
   End of inner exception
   at Newtonsoft.Json.Serialization.ExpressionValueProvider.GetValue(Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.CalculatePropertyValues(JsonWriter writer,Object value,JsonContainerContract contract,JsonProperty member,JsonProperty property,JsonContract& memberContract,Object& memberValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer,Object value,JsonObjectContract contract,JsonProperty member,JsonContainerContract collectionContract,JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer,Object value,JsonContract valueContract,JsonProperty member,JsonContainerContract containerContract,JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter,Object value,Type objectType)
   at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter,Object value,Type objectType)
   at Newtonsoft.Json.JsonConvert.SerializeObjectInternal(Object value,Type type,JsonSerializer jsonSerializer)
   at Microsoft.Azure.WebJobs.ServiceBus.Bindings.UserTypeToMessageConverter`1.Convert(TInput input)
   at Microsoft.Azure.WebJobs.ServiceBus.Bindings.MessageSenderAsyncCollector`1.AddAsync(T item,CancellationToken cancellationToken)
   at async Provisioning.Functions.CirrusFunctions.Run(TimerInfo myTimer,IAsyncCollector`1 outputSbMsgs) at C:\__w\1\s\CascadeArmRunner\src\Provisioning.Functions\CirrusFunctions.cs : 89
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Provisioning.Functions.CirrusFunctions.Run(TimerInfo myTimer,IAsyncCollector`1 outputSbMsgs) at C:\__w\1\s\CascadeArmRunner\src\Provisioning.Functions\CirrusFunctions.cs : 104
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Host.Executors.VoidTaskMethodInvoker`2.InvokeAsync[TReflected,TReturnType](TReflected instance,Object[] arguments) at C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\VoidTaskMethodInvoker.cs : 20
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionInvoker`2.InvokeAsync[TReflected,TReturnValue](Object instance,Object[] arguments) at C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionInvoker.cs : 52
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.InvokeWithTimeoutAsync(IFunctionInvoker invoker,ParameterHelper parameterHelper,CancellationTokenSource timeoutTokenSource,CancellationTokenSource functionCancellationTokenSource,Boolean throwOnTimeout,TimeSpan timerInterval,IFunctionInstance instance) at C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs : 581
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithWatchersAsync(IFunctionInstanceEx instance,ParameterHelper parameterHelper,ILogger logger,CancellationTokenSource functionCancellationTokenSource) at C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs : 527
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(IFunctionInstanceEx instance,FunctionStartedMessage message,FunctionInstanceLogEntry instanceLogEntry,ParameterHelper parameterHelper,ILogger logger,CancellationToken cancellationToken) at C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs : 306
   End of inner exception
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(IFunctionInstanceEx instance,FunctionStartedMessage message,FunctionInstanceLogEntry instanceLogEntry,ParameterHelper parameterHelper,ILogger logger,CancellationToken cancellationToken) at C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs : 352
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.TryExecuteAsync(IFunctionInstance functionInstance,CancellationToken cancellationToken) at C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs : 108
```

This is because in the Service Bus extension, `AddAsync` calls `UserTypeToMessageConverter.Conver()` [here](https://github.com/Azure/azure-sdk-for-net/blob/4162f6fa2445b2127468b9cfd080f01c9da88eba/sdk/servicebus/Microsoft.Azure.WebJobs.Extensions.ServiceBus/src/Bindings/MessageSenderAsyncCollector.cs#L37), regardless of the input type. And  `UserTypeToMessageConverter.Convert()` calls `JsonConvert.SerializeObject` [here](https://github.com/Azure/azure-sdk-for-net/blob/4162f6fa2445b2127468b9cfd080f01c9da88eba/sdk/servicebus/Microsoft.Azure.WebJobs.Extensions.ServiceBus/src/Bindings/UserTypeToMessageConverter.cs#L20), which fails to serialize the Service Bus `Message` object.

A simple repro showing this error:

```C#
using Microsoft.Azure.ServiceBus;
using System.Text;
using Newtonsoft.Json;

string msgStr = "My Message Here";

Message msg = new Message(Encoding.UTF8.GetBytes(msgStr));
string text = JsonConvert.SerializeObject(msg);
Console.WriteLine(text);
```

Attempting to run this code will cause the same exception as above.

### Expected behavior

Passing in a `Message` type to the `MessageSenderAsyncCollector.AddAsync()` method should work without exceptions.

### Actual behavior

Fails with exception `Newtonsoft.Json.JsonSerializationException : Error getting value from 'ExpiresAtUtc' on 'Microsoft.Azure.ServiceBus.Message'. ---> System.InvalidOperationException : Operation is not valid due to the current state of the object.`

### Reproduction Steps

Create a Function (e.g. timer trigger) with a Service Bus output binding, then try to call `.AddAsync` on the output binding, passing in a Service Bus `Message` type:

```C#
[FunctionName("TestServiceBusMessageSerialization")]
public async Task
        Run([TimerTrigger("1 * * * * *")] TimerInfo myTimer,
            [ServiceBus("test-sb", Connection = "ServiceBusConnectionString")] IAsyncCollector<Message> outputServiceBus)
{
    string msgStr = "Hello world";
    Message msg = new Message(Encoding.UTF8.GetBytes(msgStr));
    await outputServiceBus.AddAsync(msg);
}
```

Try running the Function. You should see the following error:

```
Microsoft.Azure.WebJobs.Host.FunctionInvocationException : Exception while executing function: TestServiceBusMessageSerialization ---> Newtonsoft.Json.JsonSerializationException : Error getting value from 'ExpiresAtUtc' on 'Microsoft.Azure.ServiceBus.Message'. ---> System.InvalidOperationException : Operation is not valid due to the current state of the object.
   at Microsoft.Azure.ServiceBus.Message.SystemPropertiesCollection.ThrowIfNotReceived()
   at Microsoft.Azure.ServiceBus.Message.get_ExpiresAtUtc()
   at lambda_method1137(Closure ,Object )
   at Newtonsoft.Json.Serialization.ExpressionValueProvider.GetValue(Object target)
   End of inner exception
   at Newtonsoft.Json.Serialization.ExpressionValueProvider.GetValue(Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.CalculatePropertyValues(JsonWriter writer,Object value,JsonContainerContract contract,JsonProperty member,JsonProperty property,JsonContract& memberContract,Object& memberValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer,Object value,JsonObjectContract contract,JsonProperty member,JsonContainerContract collectionContract,JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer,Object value,JsonContract valueContract,JsonProperty member,JsonContainerContract containerContract,JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter,Object value,Type objectType)
   at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter,Object value,Type objectType)
   at Newtonsoft.Json.JsonConvert.SerializeObjectInternal(Object value,Type type,JsonSerializer jsonSerializer)
   at Microsoft.Azure.WebJobs.ServiceBus.Bindings.UserTypeToMessageConverter`1.Convert(TInput input)
   at Microsoft.Azure.WebJobs.ServiceBus.Bindings.MessageSenderAsyncCollector`1.AddAsync(T item,CancellationToken cancellationToken)
   at async Provisioning.Functions.CirrusFunctions.Run(TimerInfo myTimer,IAsyncCollector`1 outputSbMsgs) at C:\__w\1\s\CascadeArmRunner\src\Provisioning.Functions\CirrusFunctions.cs : 89
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Provisioning.Functions.CirrusFunctions.Run(TimerInfo myTimer,IAsyncCollector`1 outputSbMsgs) at C:\__w\1\s\CascadeArmRunner\src\Provisioning.Functions\CirrusFunctions.cs : 104
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Host.Executors.VoidTaskMethodInvoker`2.InvokeAsync[TReflected,TReturnType](TReflected instance,Object[] arguments) at C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\VoidTaskMethodInvoker.cs : 20
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionInvoker`2.InvokeAsync[TReflected,TReturnValue](Object instance,Object[] arguments) at C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionInvoker.cs : 52
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.InvokeWithTimeoutAsync(IFunctionInvoker invoker,ParameterHelper parameterHelper,CancellationTokenSource timeoutTokenSource,CancellationTokenSource functionCancellationTokenSource,Boolean throwOnTimeout,TimeSpan timerInterval,IFunctionInstance instance) at C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs : 581
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithWatchersAsync(IFunctionInstanceEx instance,ParameterHelper parameterHelper,ILogger logger,CancellationTokenSource functionCancellationTokenSource) at C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs : 527
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(IFunctionInstanceEx instance,FunctionStartedMessage message,FunctionInstanceLogEntry instanceLogEntry,ParameterHelper parameterHelper,ILogger logger,CancellationToken cancellationToken) at C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs : 306
   End of inner exception
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(IFunctionInstanceEx instance,FunctionStartedMessage message,FunctionInstanceLogEntry instanceLogEntry,ParameterHelper parameterHelper,ILogger logger,CancellationToken cancellationToken) at C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs : 352
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.TryExecuteAsync(IFunctionInstance functionInstance,CancellationToken cancellationToken) at C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs : 108

```

### Environment

Windows 11 (10.0.22000), .NET SDK 6.0.301

**Comment by JoshLove-msft** [comment] 2022-06-22 04:07
@hossam-nasr, in version 5.x of the extension you need to use the Service Bus types that correspond to the Azure.Messaging.ServiceBus library. So instead of Message, you would use `ServiceBusMessage`.
Examples can be found [here](https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/servicebus/Microsoft.Azure.WebJobs.Extensions.ServiceBus#examples).

**Comment by JoshLove-msft** [comment] 2022-06-22 19:14
Going to close this out as it is working as intended.

**Closed by JoshLove-msft** 2022-06-22 19:14 UTC
Labels: Service Bus, Client, Functions, issue-addressed
