### ISSUE TITLE
[TextAnalytics] Do not use SubCategory in CustomEntity samples

### ISSUE THREAD

**Issue by kinelski** [Azure/azure-sdk-for-net#28982] opened 2022-05-25 20:12 UTC
## Feedback
> We came across something incorrect in the RecognizeCustomEntities .net SDK sample.
>
> In the sample, you refer to entity.SubCategory, which custom entities don’t have.
The thing is, both RecognizeEntities and RecognizeCustomEntities task results use the same [CategorizedEntity](https://github.com/Azure/azure-sdk-for-net/blob/42ce5c7/sdk/textanalytics/Azure.AI.TextAnalytics/src/CategorizedEntity.cs) object.
>
> But in reality, CustomEntity doesn’t have the SubCategory attribute, which makes it confusing for the customers when they’re using the sample.
>
> We’re kindly asking if you can remove this from the current samples.
> And also, for future SDKs (namely TA 3.2GA, and language SDK), can you not use this property in the samples for custom entities?

## Example
One of the affected samples:
https://github.com/Azure/azure-sdk-for-net/blob/42ce5c7a30154249b764370f132854619de08d83/sdk/textanalytics/Azure.AI.TextAnalytics/tests/samples/Sample9_RecognizeCustomEntities.cs#L106

## Action items
- Double check if this distinction between `RecogizeEntities` and `RecognizeCustomEntities` exists in the swagger specification.
- Decide whether we want to keep using the same model for both tasks and check with the service team if they can diverge more in the future. Also, check what other languages do.
- In the four Custom Entities samples, remove the code where the `SubCategory` property is used.

**Comment by jsquire** [comment] 2022-05-25 20:51
Duplicate of #27608; this work is included in the scope there.

**Closed by jsquire** 2022-05-25 20:51 UTC
Labels: Client, Cognitive - Text Analytics
