### ISSUE TITLE
[QUERY] Missing OpenRead/OpenWrite from Clients

### ISSUE THREAD

**Issue by DouglasIsaksson** [Azure/azure-sdk-for-net#9607] opened 2020-01-23 21:14 UTC
**Query/Question**
V11 and prior had support for OpenRead() and OpenWrite() methods that would return a Task<Stream>for the Equivalent classes of ShareFileClient and BlobClient.
Is support for this coming back? Or was this left out for a reason?

***Why is this not a Bug or a feature Request?***
I'm not sure if something else is planned or if this was purposely left out of the SDK.

**Comment by seanmcc-msft** [comment] 2020-01-23 23:28
@tg-msft, @KrzysztofCwalina, what do you think?

**Comment by KrzysztofCwalina** [comment] 2020-01-23 23:41
How would the APIs differ from Download and Upload? Is the only difference that the OpenRead/Write give direct access to Stream?

**Comment by DouglasIsaksson** [comment] 2020-01-24 07:54
@KrzysztofCwalina The exact same way they differed in the old SDKs. I’m integrating between multiple storage providers (FS, Blob, S3, (S)FTP Files.Shares etc.) being able to access the stream is very helpful when having abstractions for all the providers above.

**Comment by KrzysztofCwalina** [comment] 2020-01-24 19:51
> being able to access the stream is very helpful 

Download gives you access to the stream. 

I think I do understand the issue with Upload. There is not really a convenient way to get a writable stream.

**Comment by DouglasIsaksson** [comment] 2020-01-25 10:47
Ahh, I missed being able to access the stream for download. Thanks for pointing that out. That does help a bit. For consistency though, it would be nice if it was possible for upload as well.

**Comment by amishra-dev** [comment] 2020-01-28 03:20
Please triage and assign

**Comment by rongduan-zhu** [comment] 2020-01-28 23:01
I believe the old `OpenRead` API buffer the read. So if the blob is bigger than the amount of RAM available, it will allow us to stream through the file. Does the new `Download` method download the whole blob into a memory stream? If so then can it handle blob bigger than the amount of RAM available? If it can't, then I think we should either create a new parameter to make this available or have a new `OpenRead` equivalent method.

**Comment by macchmie3** [comment] 2020-01-29 10:49
We used the `OpenReadAsync` and `OpenWriteAsync` methods to perform operations on large blobs, to avoid exceeding available memory. It is the only thing stopping us from migrating from old v11 version of the blob library. Are there any plans on implementing this functionality in v12?

**Comment by KrzysztofCwalina** [comment] 2020-01-29 17:11
@macchmie3, are you implying that the new APIs don't stream?

**Comment by macchmie3** [comment] 2020-01-30 08:23
@KrzysztofCwalina 
Is it possible to open write stream to a blob? How should I approach such a problem when I want to apply some changes (delta) to an existing blob. In my cases it is usually that original source can have several GB, while delta is usually small.

```
using (var deltaStream = await deltaBlob.OpenReadAsync().ConfigureAwait(false))
using (var sourceStream = await sourceBlob.OpenReadAsync().ConfigureAwait(false))
using (var newFileStream = await newFileBlob.OpenWriteAsync().ConfigureAwait(false))
{
  // Go through deltaStream which contains data and instructions on how to modify sourceStream
  // For each instruction seek through sourceStream, insert data from deltaStream
  // The result is being streamed to a newFileBlob
}
```

What I cannot find is the functionality to open a write stream which will allow me to feed data to blob over time.

**Comment by igilham** [comment] 2020-02-27 12:14
This functionality is also needed for some simple use cases like iterating over a large number of Blobs and appending them to a zip file while streaming the output to a new Blob to avoid running out of memory.

**Comment by hungyiloo** [comment] 2020-04-17 03:12
> @macchmie3, are you implying that the new APIs don't stream? They do, i.e. you can download/upload payloads larger than than available memory.

If a download payload is larger than both the available memory and the available disk space, the previous OpenRead() method allowed us to gradually stream the file down and process it without ever having to hold the entire file anywhere. 

Is there an equivalent `Download` method with the new APIs that lets us put some kind of 'backpressure' on the incoming payload so we don't get overwhelmed?

**Comment by Boaz101** [comment] 2020-04-17 14:47
For the download stream check out BlobClient.DownloadAsync() which returns a Response<BlobDownloadInfo>. Inside the BlobDownloadInfo is a Stream Content property which you can use to stream the download. 

However, I don't see a similar way to open a Stream for upload. The only way that might work is to wrap a Stream which reads from a resource in chunks and writes the raw bytes to a byte array.  However that is overly complex and hacky for something that should be simple when using http requests. What can be done to get access to the upload Stream?

**Comment by wahyuen** [comment] 2020-04-17 15:36
There appears to be differences in the v11 `OpenRead()` stream and the v12 `Response.Content` stream.

The v11 version seems to not actually stream the whole contents of the file upon request, and only incrementally fetches data. However, our observations thus far with v12 stream, is that upon request of data from the stream, it seems to attempt to download all the data from the source file, resulting in `Stream was too long` exceptions when dealing with very large blobs.

**Comment by seanmcc-msft** [comment] 2020-04-17 17:58
@wahyuen, your analysis is correct.  We're looking into adding OpenRead() and OpenWrite() to v12 in the future.

**Comment by TJH-AIZ** [comment] 2020-04-28 17:32
@seanmcc-msft, is there an estimated timeline on this?

I'm using a PDF library that only has a Save(stream) option to save the output, so I came here trying to find out how to get an upload stream.

Is this something that I can expect "soon™" or do I need to rewrite what I've done so far to use v11, intead?

**Comment by seanmcc-msft** [comment] 2020-04-28 18:05
@TJH-AIZ, I can't promise a firm timeline, but this is the top item in our backlog after we finish the new back-end service features we are currently working on.  We understand this issue is blocking a lot of customers from moving to V12.

**Comment by atrauzzi** [comment] 2020-05-06 01:22
Will the new API be compatible with streams?

**Comment by seanmcc-msft** [comment] 2020-05-06 02:33
Yes!  The plan it for the SDK to implement a Stream for OpenRead() that will download the blob as it is needed.  Same for OpenWrite() with upload.

**Comment by atrauzzi** [comment] 2020-05-06 10:04
Great, this really can't come soon enough! 😁

**Comment by tlenig** [comment] 2020-05-20 22:48
In addition to Open read/write asks being tracked in this thread, please provide ability to allow us to pool smaller writes to a file into one buffer to be written at one time. In addition to supporting the stream itself, we also require additional functionality that provides a buffered pool implementation of these streams. This allows us to reuse the same buffer for multiple streams without needing to allocate a new one for each stream, allowing us to save memory resources.

**Comment by aL3891** [comment] 2020-05-22 10:14
We're also blocked by this :/ 
we're uploading backups that are compressed on the fly (Ionic.Zip.ZipFile.Save > blob stream)

**Comment by seanmcc-msft** [comment] 2020-06-01 19:31
I have a PR out for `OpenRead()` for Blobs, Files, and Data Lake.

**Comment by pakrym** [comment] 2020-06-01 21:20
It doesn't seem that DownloadAsync is eagerly loading the blob content.
By running the following sample you'll see that process memory would never grow higher than some initial value (~50mb on my machine).

``` C#
using System;
using Azure.Storage.Blobs;
using System.Threading.Tasks;
using System.Diagnostics;

namespace azurelogs
{
    class Program
    {
        static async Task Main(string[] args)
        {
            var value = await new BlobClient(new Uri("https://pakrym0test0storage.blob.core.windows.net/myblobcontainer/VS2015 Image Library.zip")).DownloadAsync();
            var stream = value.Value.Content;

            var buffer = new byte[20 * 1024 * 1024];
            int read;
            int total = 0;
            var process = Process.GetCurrentProcess();
            while ((read = await stream.ReadAsync(buffer)) > 0)
            {
                total += read;
                process.Refresh();
                Console.WriteLine("Downloaded "+ total / 1024 / 1024 + "MB, Process memory " + process.PrivateMemorySize64 / 1024 / 1024 + "MB");
            }
        }
    }
}

```

**Comment by seanmcc-msft** [comment] 2020-06-01 21:26
What about Upload()?

**Comment by pakrym** [comment] 2020-06-01 21:27
I didn't try Upload.

**Comment by seanmcc-msft** [comment] 2020-06-01 21:30
If streaming uploads already function correctly, we may not have to do anything for this issue.

**Comment by TJH-AIZ** [comment] 2020-06-02 11:53
Don't forget #7558 (https://github.com/Azure/azure-sdk-for-js/issues/7558) which was closed because it's supposed to be addressed here.

**Comment by Boaz101** [comment] 2020-06-02 14:00
@seanmcc-msft There is no way that I can see to get access to a writable blob stream similar to the previous OpenWriteAsync method.

**Comment by seanmcc-msft** [comment] 2020-06-02 21:15
@Boaz101, I think OpenWrite is still an issue, but it appears we have an existing solution for Open Read.

**Comment by PaulVrugt** [comment] 2020-06-15 09:39
@pakrym 
@seanmcc-msft 
I'm confused. What exactly is the solution for openread, if you need a seekable stream? The example that @pakrym provided https://github.com/Azure/azure-sdk-for-net/issues/9607#issuecomment-637108205) doesn't result in a seekable stream.

Similar to @DouglasIsaksson we have a generic storage implementation for different types of storage, based on streams. We need to be able to return seekable read or write streams from our File layer, which was possible in V11 of this library.

**Comment by seanmcc-msft** [comment] 2020-06-15 15:42
@pakrym, what do you think on the seekablility issue?  Seems like the most straightforward path would be to re-open https://github.com/Azure/azure-sdk-for-net/pull/12400, address the PR comments, and add the functionality to make the stream seekable.

**Comment by pakrym** [comment] 2020-06-15 15:55
I think adding the seekability to `RetryableStream` would be the way to go here.

**Comment by seanmcc-msft** [comment] 2020-06-15 16:00
`RetriableStream` is in Azure.Core, so that will probably need to be addressed by the One SDK team.

**Comment by PaulVrugt** [comment] 2020-06-15 16:00
I'm no expert on this library, but I must say I agree with @seanmcc-msft about the #12400. Having ready-to-use openread and openwrite methods is much more intuitive. If they aren't added, anyone that used to use these methods needs to write the same "wrapper" code to get about the same effect.

**Comment by pakrym** [comment] 2020-06-15 16:04
> RetriableStream is in Azure.Core, so that will probably need to be addressed by the One SDK team.

We are happy to take a pull request. The change shouldn't be too complicated.

#12400 does way more than adding seekability. It also adds another layer of buffering/indirection that would affect performance.

**Comment by PaulVrugt** [comment] 2020-06-15 17:05
Well that doesn't sound very promising now does it? I'm not getting involved in an ethical debate about where the functionality should be implemented. My case is simple: I was able to use streams and seek within them in v11. You want us to upgrade to V12, and I also want to stay up to date, but I can't if we get stuck in this debate on how to add the code, instead of adding it.

**Comment by tg-msft** [comment] 2020-06-15 23:10
Let's discuss this at our next sync and figure out the best path forward.  We'll update this issue when there's a plan here.

**Comment by rhodh** [comment] 2020-06-17 13:05
> I think adding the seekability to `RetryableStream` would be the way to go here.

Just wondering if there any movement on this? We're currently integrating against v12 but not having a seekable stream is really limiting - we're currently having to load the file into memory as a workaround which isn't a viable solution long term.

**Comment by seanmcc-msft** [comment] 2020-07-17 00:54
We have merged non-seekable OpenRead - https://github.com/Azure/azure-sdk-for-net/pull/12400.

Open Write and Seekable OpenRead will come later.

**Comment by hhermas** [comment] 2020-07-29 17:25
Glad to hear that OpenRead/OpenWrite are now committed. Do you happen to know when will they become available?

**Comment by seanmcc-msft** [comment] 2020-07-29 17:28
Open Write has not been committed yet - https://github.com/Azure/azure-sdk-for-net/pull/13344.  We are hoping to release Open Read and Open Write with the next GA release in a few weeks.

**Comment by seanmcc-msft** [comment] 2020-08-12 21:29
Open write has merged! - https://github.com/Azure/azure-sdk-for-net/pull/13344

**Comment by PaulVrugt** [comment] 2020-08-13 07:44
Great! two down, one to go. Now all we need is seekable read streams from `OpenRead`, and we can start using this new package.

**Comment by PaulVrugt** [comment] 2020-08-17 07:39
@seanmcc-msft 
Will the seekable read stream issue also be addressed here, or is there a different issue for that?

**Comment by seanmcc-msft** [comment] 2020-08-17 16:14
I think we will leave this issue open.  We still need to add seekability to `Open Read()`, and `PageBlobClient.OpenWrite()` and `ShareFileClient.OpenWrite()`.  Seekable writes are not possible on Append Blob, Block Blobs, and Data Lake Files.

**Comment by nesterenko-kv** [comment] 2020-08-18 09:07
@seanmcc-msft thanks. Could you please add overload to `OpenWrite/Async` which also takes `BlobHttpHeaders`?

**Comment by PaulVrugt** [comment] 2020-08-18 09:07
@seanmcc-msft Great! We're only looking for seekability in OpenRead for block blobs. Is there any ETA on this functionalitity? 

We're looking to start to migrate some of our customers to Azure later this year, and the V12 version of this component is needed for thread safety (as you mentioned in https://github.com/Azure/azure-storage-net/issues/732#issuecomment-559277954)

Having seekable openread is the last blockage for us migrating to V12

**Comment by seanmcc-msft** [comment] 2020-08-18 15:53
We are currently working on another batch of new service features, I can pivot back to Open Read after that.  Tentatively, I'm thinking I can have Open Read done by end of October.

**Comment by PaulVrugt** [comment] 2020-08-18 16:13
That would be great. Thanks for the openness!

**Comment by seanmcc-msft** [comment] 2020-09-11 19:50
I have a PR out adding seekability to Open Read - https://github.com/Azure/azure-sdk-for-net/pull/15032.  I'm waiting for comments from colleagues, we will hopefully be including it in the next release.

**Comment by seanmcc-msft** [comment] 2020-10-07 23:56
Open Read Seekability has merged, I'm going to close this issue now.

**Closed by seanmcc-msft** 2020-10-07 23:56 UTC
Labels: Client, Service Attention, Storage, customer-reported, feature-request

**Comment by PaulVrugt** [comment] 2020-10-27 10:23
@seanmcc-msft Is there any ETA on an actual release with this feature? The missing seek has now become a blocking issue for our migration to azure. I see there is a 12.7 preview 1 that has this feature, and preview 2 has the "unreleased" tag for a while now.

**Comment by RogerDawson** [comment] 2020-10-27 13:55
> Open Read Seekability has merged, I'm going to close this issue now.

I'm not sure about anyone else out there, but while the preview version 12.5.0-preview.1 of the Azure.Storage.Files.Shares library does appear to return the correct file length now (12.4.0 returned -1) if I call the code below an exception is thrown along with the statement 'Specified method is not supported.':

```
var fs = await fileRef.OpenReadAsync();
fs.Seek(currentIndex, SeekOrigin.Begin);
```

Is this actually fixed or am I doing something wrong here?

**Comment by seanmcc-msft** [comment] 2020-10-27 16:28
@RogerDawson, the change has been merged to our main branch, and will be automatically included in the next release.

**Comment by PaulVrugt** [comment] 2020-11-09 08:57
@seanmcc-msft not sure if your previous comment was meant for me instead of roger, but I understand it will be automatically included in the next release, but it seems to be taking a long time before this release is actually there. Since the missing feature is blocking us from starting the process of migrating hundreds of customers to Azure, I was wondering if there is any ETA on 12.7 of this library. The preview2 has been "unreleased" for weeks now.

**Comment by seanmcc-msft** [comment] 2020-11-09 17:49
The 12.7 GA release is schedule for release tomorrow.  This has been planned for several weeks.

**Comment by RogerDawson** [comment] 2020-11-10 09:44
> @RogerDawson, the change has been merged to our main branch, and will be automatically included in the next release.

Hi Sean, thanks for the reply, but to be clear, the problem I noticed was using the latest preview version. Are you saying that this problem will be fixed and go straight to release without first being released as a preview version? Or are you thinking I was trying this on a release package? Many Thanks, Roger

**Comment by seanmcc-msft** [comment] 2020-11-10 16:04
The fix has not been released yet.  It will be soon.

**Comment by jstutson** [comment] 2021-03-22 03:11
I'm on v12.8.0 of Azure.Storage.Blob and not seeing any BlobClient.OpenWrite() - has this been released?

**Comment by seanmcc-msft** [comment] 2021-03-29 18:25
@jstutson, `OpenRead()` and `OpenWrite()` are featured on `AppendBlobClient`, `BlockBlobClient`, and `PageBlobClient`.  It is not featured on `BlobClient` by design.
