### ISSUE TITLE
Service Bus: System.ObjectDisposedException when opening a receiver link

### ISSUE THREAD

**Issue by kanatgit** [Azure/azure-sdk-for-net#19731] opened 2021-03-23 15:41 UTC
Hi,

![image](https://user-images.githubusercontent.com/43287505/112188242-d3ee4b80-8bd0-11eb-8a98-0f67d295efa7.png)

I am getting thousands of ObjectDisplosedException a day throw out of Azure.Messaging.ServiceBus.Amqp.AmqpConnectionScope.OpenReceiverLinkAsync() at line 312.

![image](https://user-images.githubusercontent.com/43287505/112172388-adc1af00-8bc2-11eb-9206-b9a3f2cdc9c6.png)

By looking into the servicebus source code, the problem is the ActiveConnection was disposed. The version of Azure.Messaging.ServiceBus is 7.1.0.0.  Is this an issue of servicebus code? Any suggestion? My sample code is provided at the end.

Thanks

**Exception Detail:**
{"HResult":-2146232798,"Message":"Cannot access a disposed object.\r\nObject name: 'FaultTolerantAmqpObject`1'.","Source":"Microsoft.Azure.Amqp","ObjectName":"FaultTolerantAmqpObject`1","Type":"System.ObjectDisposedException"}

**Call Stack:**
```text
System.ObjectDisposedException:
   at Microsoft.Azure.Amqp.Singleton`1+<GetOrCreateAsync>d__13.MoveNext (Microsoft.Azure.Amqp, Version=2.4.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter.GetResult (System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Azure.Messaging.ServiceBus.Amqp.AmqpConnectionScope+<OpenReceiverLinkAsync>d__54.MoveNext (Azure.Messaging.ServiceBus, Version=7.1.0.0, Culture=neutral, PublicKeyToken=92742159e12e44c8)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter.GetResult (System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Azure.Messaging.ServiceBus.Amqp.AmqpReceiver+<OpenReceiverLinkAsync>d__30.MoveNext (Azure.Messaging.ServiceBus, Version=7.1.0.0, Culture=neutral, PublicKeyToken=92742159e12e44c8)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter.GetResult (System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Microsoft.Azure.Amqp.FaultTolerantAmqpObject`1+<OnCreateAsync>d__6.MoveNext (Microsoft.Azure.Amqp, Version=2.4.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Microsoft.Azure.Amqp.Singleton`1+<GetOrCreateAsync>d__13.MoveNext (Microsoft.Azure.Amqp, Version=2.4.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Microsoft.Azure.Amqp.Singleton`1+<GetOrCreateAsync>d__13.MoveNext (Microsoft.Azure.Amqp, Version=2.4.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Azure.Messaging.ServiceBus.Amqp.AmqpReceiver+<ReceiveMessagesAsyncInternal>d__34.MoveNext (Azure.Messaging.ServiceBus, Version=7.1.0.0, Culture=neutral, PublicKeyToken=92742159e12e44c8)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Azure.Messaging.ServiceBus.Amqp.AmqpReceiver+<ReceiveMessagesAsyncInternal>d__34.MoveNext (Azure.Messaging.ServiceBus, Version=7.1.0.0, Culture=neutral, PublicKeyToken=92742159e12e44c8)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter.GetResult (System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Azure.Messaging.ServiceBus.Amqp.AmqpReceiver+<>c__DisplayClass33_0+<<ReceiveMessagesAsync>b__0>d.MoveNext (Azure.Messaging.ServiceBus, Version=7.1.0.0, Culture=neutral, PublicKeyToken=92742159e12e44c8)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Azure.Messaging.ServiceBus.ServiceBusRetryPolicy+<RunOperation>d__20.MoveNext (Azure.Messaging.ServiceBus, Version=7.1.0.0, Culture=neutral, PublicKeyToken=92742159e12e44c8)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Azure.Messaging.ServiceBus.ServiceBusRetryPolicy+<RunOperation>d__20.MoveNext (Azure.Messaging.ServiceBus, Version=7.1.0.0, Culture=neutral, PublicKeyToken=92742159e12e44c8)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Azure.Messaging.ServiceBus.Amqp.AmqpReceiver+<ReceiveMessagesAsync>d__33.MoveNext (Azure.Messaging.ServiceBus, Version=7.1.0.0, Culture=neutral, PublicKeyToken=92742159e12e44c8)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter.GetResult (System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Azure.Messaging.ServiceBus.ServiceBusReceiver+<ReceiveMessagesAsync>d__37.MoveNext (Azure.Messaging.ServiceBus, Version=7.1.0.0, Culture=neutral, PublicKeyToken=92742159e12e44c8)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Azure.Messaging.ServiceBus.ServiceBusReceiver+<ReceiveMessageAsync>d__39.MoveNext (Azure.Messaging.ServiceBus, Version=7.1.0.0, Culture=neutral, PublicKeyToken=92742159e12e44c8)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Azure.Messaging.ServiceBus.ReceiverManager+<ReceiveAndProcessMessagesAsync>d__19.MoveNext (Azure.Messaging.ServiceBus, Version=7.1.0.0, Culture=neutral, PublicKeyToken=92742159e12e44c8)
```

**My sample code:**
```csharp
    public class QueueWorker<TMessage> : BackgroundService where TMessage : class
    {
        private readonly IProcessQueueMessages<TMessage> _messageProcessor;

        private readonly ServiceBusClient _serviceBusClient;

        protected ILogger<QueueWorker<TMessage>> Logger { get; }

        public QueueWorker(ILogger<QueueWorker<TMessage>> logger, IProcessQueueMessages<TMessage> messageProcessor, ServiceBusClient serviceBusClient)
        {
            Logger = logger;
            _messageProcessor = messageProcessor;
            _serviceBusClient = serviceBusClient;
        }

        protected override async Task ExecuteAsync(CancellationToken stoppingToken)
        {
            var queueName = _messageProcessor.QueueName;
            if(string.IsNullOrWhiteSpace(queueName))
            {
                Logger.LogWarning(_messageProcessor.QueueNameMissingWarningMessage);
                return;
            }

            var messageProcessor = CreateServiceBusProcessor(queueName);
            messageProcessor.ProcessMessageAsync += HandleMessageAsync;
            messageProcessor.ProcessErrorAsync += HandleReceivedExceptionAsync;

            Logger.LogInformation($"Starting message pump on queue {queueName} in namespace {messageProcessor.FullyQualifiedNamespace}");
            await messageProcessor.StartProcessingAsync(stoppingToken);
            Logger.LogInformation("Message pump started");

            while (!stoppingToken.IsCancellationRequested)
            {
                await Task.Delay(TimeSpan.FromSeconds(1));
            }

            Logger.LogInformation("Closing message pump");

            messageProcessor.ProcessMessageAsync -= HandleMessageAsync;
            messageProcessor.ProcessErrorAsync -= HandleReceivedExceptionAsync;

            await messageProcessor.CloseAsync(cancellationToken: stoppingToken);
            Logger.LogInformation("Message pump closed : {Time}", DateTimeOffset.UtcNow);
        }

        private ServiceBusProcessor CreateServiceBusProcessor(string queueName)
        {
            return _serviceBusClient.CreateProcessor(queueName);
        }

        private async Task HandleMessageAsync(ProcessMessageEventArgs processMessageEventArgs)
        {
            TMessage deserializedMessage = null;
            try
            {
                var rawMessageBody = Encoding.UTF8.GetString(processMessageEventArgs.Message.Body.ToArray());
                Logger.LogInformation("Received message {MessageId} with body {MessageBody}",
                    processMessageEventArgs.Message.MessageId, rawMessageBody);

                deserializedMessage = JsonConvert.DeserializeObject<TMessage>(rawMessageBody);
                if (deserializedMessage != null)
                {
                    await _messageProcessor.ProcessMessage(deserializedMessage, processMessageEventArgs.Message.MessageId,
                        processMessageEventArgs.Message.ApplicationProperties,
                        processMessageEventArgs.CancellationToken);
                }
                else
                {
                    Logger.LogError(
                        "Unable to deserialize to message contract {ContractName} for message {MessageBody}",
                        typeof(TMessage), rawMessageBody);
                }

                Logger.LogInformation("Message {MessageId} processed", processMessageEventArgs.Message.MessageId);

                await processMessageEventArgs.CompleteMessageAsync(processMessageEventArgs.Message);
            }
            catch (Exception ex)
            {
                Logger.LogError(ex, "Unable to handle message: {ProcessMessageEventArgs}", processMessageEventArgs);

                if(!_messageProcessor.CanRetry(ex, processMessageEventArgs.Message?.Body, deserializedMessage))
                {
                    await processMessageEventArgs.DeadLetterMessageAsync(processMessageEventArgs.Message);
                }
            }
        }

        private Task HandleReceivedExceptionAsync(ProcessErrorEventArgs exceptionEvent)
        {
            Logger.LogError(exceptionEvent.Exception, "Unable to process message");
            return Task.CompletedTask;
        }
    }
```

**Comment by jsquire** [comment] 2021-03-23 16:32
Hi @kanatgit.  Thank you for reaching out and we regret that you're experiencing difficulties.  May I ask if you're seeing these exceptions during periods of time when there is no activity on the Service Bus instance or on a recurring basis of around 20 minutes?

**Comment by kanatgit** [comment] 2021-03-23 17:00
@jsquire, Thanks for replay. See the graph for the exception distribution:
![image](https://user-images.githubusercontent.com/43287505/112186563-44946880-8bcf-11eb-9b49-b932d46c20dd.png)

**Comment by JoshLove-msft** [comment] 2021-03-23 22:09
Hi @kanatgit, can you provide more information on how the ServiceBusClient is being managed? Is it possible that the client is being closed while the processor is still running?

**Comment by kanatgit** [comment] 2021-03-23 23:02
In our asp.net core web application Startup.cs file, ServiceBusClient is registered as
 public void ConfigureServices(IServiceCollection services)
{
...
            services.AddHostedService<QueueWorker<AssessmentMessageModel>>();

            services.AddAzureClients(cfg =>
            {
                cfg.AddServiceBusClient(_queueConfiguration.ConnectionString);
            });
...
}

QueueWorker is the only class depends on ServiceBusClient ( ServiceBusClient is instantiated by AutoFac container).

**Comment by JoshLove-msft** [comment] 2021-03-23 23:20
Once these errors are hit, does the app ever process messages again or does it just keep spewing these errors until you shut it down? 
Do you have any logging in your shutdown code? Can you verify that the app is not being shut down unexpectedly?

**Comment by JoshLove-msft** [comment] 2021-03-23 23:28
I think I have an idea of what could be happening. You are removing the event handlers while the processor is still running, which I believe will trigger an exception which would cause the processor to never get closed:
```cs
  Logger.LogInformation("Closing message pump");

  messageProcessor.ProcessMessageAsync -= HandleMessageAsync;
  messageProcessor.ProcessErrorAsync -= HandleReceivedExceptionAsync;

  await messageProcessor.CloseAsync(cancellationToken: stoppingToken);
```

This means when the app is shut down, the processor will still keep running. Instead you can close the processor before attempting to remove the handlers. Also, it may be better to override [StopAsync](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.hosting.backgroundservice.stopasync?view=dotnet-plat-ext-5.0#Microsoft_Extensions_Hosting_BackgroundService_StopAsync_System_Threading_CancellationToken_) to handle the processor shut down rather than putting it in ExecuteAsync.

**Comment by kanatgit** [comment] 2021-03-24 00:43
@JoshLove-msft , the removing handler code wasn't there when the exceptions were observed initially. I added them later just to see if it helps to solve the problem.

**Comment by JoshLove-msft** [comment] 2021-03-24 00:48
> @JoshLove-msft , the removing handler code wasn't there when the exceptions were observed initially. I added them later just to see if it helps to solve the problem.

Ah ok, well the stoppingToken would have prevented the processor from being closed.

**Comment by JoshLove-msft** [comment] 2021-03-24 00:53
Also, I think we can try to fix this in the SDK so that the processor doesn't continually try to process if the client has been closed. Please let us know if it turns out that is what is happening here.

**Comment by kanatgit** [comment] 2021-03-24 01:12
I don't understand why you think the stopppingToken prevents messageProcessor.CloseAsync(cancellationToken: stoppingToken) to succeed. There is while loop to check the stoppingToken.isCanCancellationRequested before this CloseAsync() call. I also checked ServiceBusProcessor.CloseAsync() implementation, which waits the stopppingToken to be triggered, which I think should succeed when app shuts down.

  while (!stoppingToken.IsCancellationRequested)
            {
                await Task.Delay(TimeSpan.FromSeconds(1));
            }

            Logger.LogInformation("Closing message pump");

            messageProcessor.ProcessMessageAsync -= HandleMessageAsync;
            messageProcessor.ProcessErrorAsync -= HandleReceivedExceptionAsync;

            await messageProcessor.CloseAsync(cancellationToken: stoppingToken);


public virtual async Task CloseAsync(
            CancellationToken cancellationToken = default)
        {
            IsClosed = true;

            if (IsProcessing)
            {
                await StopProcessingAsync(cancellationToken).ConfigureAwait(false);
            }
            foreach (ReceiverManager receiverManager in _receiverManagers)
            {
                await receiverManager.CloseReceiverIfNeeded(
                    cancellationToken,
                    forceClose: true)
                    .ConfigureAwait(false);
            }
        }

**Comment by JoshLove-msft** [comment] 2021-03-24 01:14
StopProcessingAsync throws if the cancellationToken is cancelled.

**Comment by kanatgit** [comment] 2021-03-24 01:39
Ah, cancellatinoToken really means to cancel stopProcessing. I misunderstood it. I will remove the cancellationToken parameter to test our web app tomorrow and will keep you updated. Thanks for the help.

**Comment by JoshLove-msft** [comment] 2021-03-30 06:38
Hi @kanatgit, just want to check to see if you were able to test this out.

**Comment by kanatgit** [comment] 2021-03-30 13:13
@JoshLove-msft , I implemented two of your suggestions, 
1. Call the CloseAsync() first, then remove the handlers.
2. Call CloseAsync() without the cancellation token.
![image](https://user-images.githubusercontent.com/43287505/112991669-01854880-912d-11eb-9ded-337defddc592.png)

 Unfortunately, those two changes are not enough to solve the problem, the same exceptions still happened yesterday.
![image](https://user-images.githubusercontent.com/43287505/112992078-79ec0980-912d-11eb-8762-72bd78406e06.png)
![image](https://user-images.githubusercontent.com/43287505/112992146-896b5280-912d-11eb-988b-d23791fab323.png)

As you can see, two messages "closing message pump" and "Message pump closed", one should be logged before CloseAync(), one after CloseAync(). From the AppInsight Logs, you can see that  "Message pump closed" for ProcessId: "24436" is missing, which indicates that CloseAync() never returns. The exceptions also happens right after the timestamp of "closing message pump" message for ProcessId:"24436". I don't know why there were multiple processes, not sure if it is something related to azure environment.

I am implementing your 3rd suggesting to the put the CloseAsync() method in an overriden BackgroudService.StopAsync() method. While testing this on my local machine, I found that ServicebusClient.CloseAsync() now takes 17 seconds to return, which was returned instantly when it was called from ExecuteAsyn(); Do you have any explanation for this behavior change? I will deploy this 3rd change to Azure see how it works and keep you updated.
![image](https://user-images.githubusercontent.com/43287505/112993735-224e9d80-912f-11eb-8c00-eb06f60d70b8.png)

**Comment by JoshLove-msft** [comment] 2021-04-06 04:55
> While testing this on my local machine, I found that ServicebusClient.CloseAsync() now takes 17 seconds to return, which was returned instantly when it was called from ExecuteAsyn(); I stopped the web app by pressing Ctrl+C after the app started, at that point, the servicebus queue should be empty. Do you have any explanation for this time consumption change? I will deploy this 3rd change to Azure see how it works and keep you updated. Thank you for your continuous help.

Do you mean when calling processor.CloseAsync? It is expected that it would take some time while closing due to the processor waiting for any receive calls to complete. We are planning on improving this behavior in an upcoming release (see https://github.com/Azure/azure-sdk-for-net/issues/17734). As for why the call would return immediately when in the Execute method, I'm not sure. Do you have [logging](https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/servicebus/Azure.Messaging.ServiceBus#logging-and-diagnostics) enabled for the Service Bus SDK?

**Comment by kanatgit** [comment] 2021-04-06 12:31
Yes, the processor.CloseAsync() method takes 17 seconds to finish on my local machine. I implemented your 3rd suggestion calling processor.CloseAsnc() in overriden StopAsnc() function and deployed it to azure environment. Good news is that I haven't seen the ObjectDisposedExceptions happened, but it seems that a lot of times processor.CloseAsync() doesn't return because the "Message pump closed" log are missing most of the time when app got redeployed. 
![image](https://user-images.githubusercontent.com/43287505/113711041-153f2a80-96aa-11eb-9934-c15ca601dad3.png)

**Comment by JoshLove-msft** [comment] 2021-04-06 21:58
Interesting.. are you able to enable SDK logs?

**Comment by JoshLove-msft** [comment] 2021-04-15 06:13
@kanatgit just checking in on this. Were you able to enable SDK logging so we can debug further?

**Comment by jsquire** [comment] 2021-04-15 13:02
@JoshLove-msft:  Based on the scenario, I'm reasonably sure this is related to #20255 with the root cause being unexpected behavior by the AMQP library.  We've discussed with the team that maintains the AMQP library and they'll be addressing it in a future update.   I'm working on a mitigation for both Event Hubs and Service Bus in the meantime.

**Comment by jsquire** [comment] 2021-04-15 13:17
@kanagit, the frequency that of this in your logs and the time clustering may be a concern.  Assuming that I'm correct about the root cause, this log pattern would seem to indicate that your application is experiencing network instability which is causing connections/links to fail.  With the forthcoming mitigation in the SDK, it will detect the scenario and try to recover by creating a new connection, but I wonder if you'll continue to experience connectivity difficulties.

Can you help us understand the host environment and application a bit better?

**Comment by kanatgit** [comment] 2021-04-15 13:22
I have been investigating why this problem only happens at azure environment. The screen shots below shows our web app deployment pipelines. As you can see the task of stop app service returns in 1 second, which doesn't wait the servicebus processor.CloseAsync() to return, that's why "Message pump closed" log is missing. Web app is shutdown ungracefully and I don't see any option/configuration is available to change this behavior. 
![image](https://user-images.githubusercontent.com/43287505/114875147-9ee5ab00-9dc2-11eb-903a-0e299522f7ba.png)
![image](https://user-images.githubusercontent.com/43287505/114875972-76aa7c00-9dc3-11eb-9c35-d536945ae4e1.png)

**Comment by jsquire** [comment] 2021-04-15 14:47
@kanatgit.  That makes sense and would trigger the behavior that I was talking about; tearing down the host environment is very likely to cause changes to the state of the network resources, upsetting the AMQP transport.   What I'd expect to see in this case is one instance of the `ObjectDisposedException` for each concurrent receive.   Currently, they should be treated as terminal and the processor should be aware that it is stopping and should not relaunch the faulted task.

Does that match what you're seeing?

**Comment by jsquire** [comment] 2021-04-15 17:36
I talked to @JoshLove-msft offline, and it looks like there are two issues at play.   The gap that I wasn't seeing earlier is that the processor also isn't reacting to the client being closed, so the change in network state was likely first caused by the client closing rather than the AppService shutting down.   Apologies for the confusion.

**Comment by JoshLove-msft** [comment] 2021-04-15 17:47
I think there are a few things going on here. 

In the SDK itself, we have a bug where the receiver/sender/etc does not check if the client was closed before attempting operations. It checks only if the link is closed. A similar gap appears to exist in Event Hubs where closing the connection without closing the Consumer would result in the same behavior.

This bug can be worked around by ensuring that processor.close is called, but there is some odd behavior occurring - it didn't seem to get called when it was in the Execute method.  Moving the processor.close call into the stop method works locally, but it doesn't always return when deployed. The best way to debug further would be to enable [SDK logs](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/extensions/Microsoft.Extensions.Azure/README.md) - I'm not seeing these in the latest screenshot.

**Comment by kanatgit** [comment] 2021-04-15 18:13
@JoshLove-msft, can you tell how do I enable SDK logs? Do you mean add 
  "Logging": {
    "LogLevel": {
      "Default": "Debug"
    } 
to appsettings.json? I have a debug console which shows servicebus debug infomation on my local machine, but I don't know how to enable SDK debug info on azure environment.

**Comment by JoshLove-msft** [comment] 2021-04-15 23:17
Is this an App Service instance? This might help - https://docs.microsoft.com/en-us/azure/app-service/troubleshoot-diagnostic-logs

**Comment by kanatgit** [comment] 2021-04-16 03:50
@JoshLove-msft , Thanks for the app service logs document link. Unfortunately in order to use the app service logs, it requires to install .net core site extention, which is incompatible with our app, causing our app unable to start.  

![image](https://user-images.githubusercontent.com/43287505/114968936-f4f73480-9e3c-11eb-96f4-7d520224fd72.png)

**Comment by kanatgit** [comment] 2021-04-16 03:56
I found a temporary solution is ignoring the ObjectDisposedException in the Handler during shutdown.

   public class QueueWorker<TMessage> : BackgroundService where TMessage : class
    {
        private readonly IProcessQueueMessages<TMessage> _messageProcessor;

        private readonly ServiceBusClient _serviceBusClient;

        private ServiceBusProcessor _serviceBusProcessor;

        private readonly IHostApplicationLifetime _appLifetime;

        private bool _isStopping;



        protected ILogger<QueueWorker<TMessage>> Logger { get; }

        public QueueWorker(ILogger<QueueWorker<TMessage>> logger, IProcessQueueMessages<TMessage> messageProcessor, ServiceBusClient serviceBusClient, IHostApplicationLifetime appLifetime)
        {
            Logger = logger;
            _messageProcessor = messageProcessor;
            _serviceBusClient = serviceBusClient;
            _appLifetime = appLifetime;
            _isStopping = false;
        }

        protected override async Task ExecuteAsync(CancellationToken stoppingToken)
        {
            var queueName = _messageProcessor.QueueName;
            if(string.IsNullOrWhiteSpace(queueName))
            {
                Logger.LogWarning(_messageProcessor.QueueNameMissingWarningMessage);
                return;
            }

            _serviceBusProcessor = CreateServiceBusProcessor(queueName);
            _serviceBusProcessor.ProcessMessageAsync += HandleMessageAsync;
            _serviceBusProcessor.ProcessErrorAsync += HandleReceivedExceptionAsync;

            Logger.LogInformation($"Starting message pump on queue {queueName} in namespace {_serviceBusProcessor.FullyQualifiedNamespace}");
            await _serviceBusProcessor.StartProcessingAsync(stoppingToken);
            _appLifetime.ApplicationStopping.Register(OnStopping);
            Logger.LogInformation("Message pump started");

        }

        private void OnStopping()
        {
            Logger.LogInformation("Closing message pump");
            _isStopping = true;

            _serviceBusProcessor.CloseAsync().GetAwaiter().GetResult();
            _serviceBusProcessor.ProcessErrorAsync -= HandleReceivedExceptionAsync;
            _serviceBusProcessor.ProcessMessageAsync -= HandleMessageAsync;


            Logger.LogInformation("Message pump closed : {Time}", DateTimeOffset.UtcNow);

        }

        private ServiceBusProcessor CreateServiceBusProcessor(string queueName)
        {
            return _serviceBusClient.CreateProcessor(queueName);
        }

        private async Task HandleMessageAsync(ProcessMessageEventArgs processMessageEventArgs)
        {
            TMessage deserializedMessage = null;
            try
            {
                var rawMessageBody = Encoding.UTF8.GetString(processMessageEventArgs.Message.Body.ToArray());
                Logger.LogInformation("Received message {MessageId} with body {MessageBody}",
                    processMessageEventArgs.Message.MessageId, rawMessageBody);

                deserializedMessage = JsonConvert.DeserializeObject<TMessage>(rawMessageBody);
                if (deserializedMessage != null)
                {
                    await _messageProcessor.ProcessMessage(deserializedMessage, processMessageEventArgs.Message.MessageId,
                        processMessageEventArgs.Message.ApplicationProperties,
                        processMessageEventArgs.CancellationToken);
                }
                else
                {
                    Logger.LogError(
                        "Unable to deserialize to message contract {ContractName} for message {MessageBody}",
                        typeof(TMessage), rawMessageBody);
                }

                Logger.LogInformation("Message {MessageId} processed", processMessageEventArgs.Message.MessageId);

                await processMessageEventArgs.CompleteMessageAsync(processMessageEventArgs.Message);
            }
            catch (Exception ex)
            {
                Logger.LogError(ex, "Unable to handle message: {ProcessMessageEventArgs}", processMessageEventArgs);

                if(!_messageProcessor.CanRetry(ex, processMessageEventArgs.Message?.Body, deserializedMessage))
                {
                    await processMessageEventArgs.DeadLetterMessageAsync(processMessageEventArgs.Message);
                }
            }
        }

        private Task HandleReceivedExceptionAsync(ProcessErrorEventArgs exceptionEvent)
        {
            // During application shutdown, microsoft service bus code throws a lot of ObjectDisposedException,
            // We have reported this issue to microsoft, whille microsoft is still working on this issue,
            // we just simply ignore this type of exception during shutdown to prevent it flooding app loggings.
            if (_isStopping && exceptionEvent.Exception is ObjectDisposedException)
            {
                return Task.CompletedTask;
            }

            Logger.LogError(exceptionEvent.Exception, "Unable to process message");
            return Task.CompletedTask;
        }
    }

**Comment by JoshLove-msft** [comment] 2021-04-16 05:21
> @JoshLove-msft , Thanks for the app service logs document link. Unfortunately in order to use the app service logs, it requires to install .net core site extention, which is incompatible with our app, causing our app unable to start.

@pakrym do you know how we can enable SDK logging here?

**Comment by kanatgit** [comment] 2021-04-17 21:04
@JoshLove-msft , I managed to get the logging with debug level enabled.

**Here is a bad logging, servicebusProcessor.CloseAsnc() never return because the  "Message pump closed" is missing", Please pay attention to the  stop error.**

![image](https://user-images.githubusercontent.com/43287505/115126630-0d2e9700-9f96-11eb-8429-ccf0dd3c2207.png)
![image](https://user-images.githubusercontent.com/43287505/115126642-1ddf0d00-9f96-11eb-87a6-67a178f8232f.png)

**Here is a good logging for your reference. (You can see both the "Closing message pump" and "Message pump closed" messages).**

![image](https://user-images.githubusercontent.com/43287505/115126664-4bc45180-9f96-11eb-8312-9f15a9327047.png)
![image](https://user-images.githubusercontent.com/43287505/115126673-626aa880-9f96-11eb-9398-d672cf3c9e05.png)

**Comment by kanatgit** [comment] 2021-04-22 14:25
@jsquire ,Thanks for your continuous efforts bringing the fix. May I ask when this fix will be available in NuGet Repository?

**Comment by jsquire** [comment] 2021-04-23 15:19
@kanatgit.  You're very welcome.  These changes will be part of our next release in early May.  I can't speak to whether that planned as a beta or GA;  I'll need to defer to @JoshLove-msft for insight.

**Comment by jsquire** [comment] 2021-07-03 15:52
Since the fixes needed are now confirmed to have reached GA, I'm going to tag this as having been addressed and close it out.  Please feel free to "`/unresolve`" if you believe that further discussion is needed.

**Closed** 2021-07-03 15:53 UTC
Labels: Client, Service Bus, customer-reported, issue-addressed, question
