### ISSUE TITLE
[BUG] Cannot filter on Timestamp using Azure.Data.Tables SDK (Cosmos backend)

### ISSUE THREAD

**Issue by nheath99** [Azure/azure-sdk-for-net#32468] opened 2022-11-14 08:51 UTC
### Library name and version

Azure.Data.Tables 12.7.0

### Describe the bug

When I apply a filter on the Timestamp field, the query returns zero results.

### Expected behavior

The query should return the results that satisfy the Timestamp query

### Actual behavior

An empty collection is returned. No exception is thrown. Yes there are elements that should satisfy the query. When I run the identical query in Azure Portal, the expected items are returned.

### Reproduction Steps

```
var connectionString = "...";
var table = new TableClient(connectionString, "CommandLogs");

var failureFilter = "UserId eq '76d8bd02-7943-436e-b5a8-d7101a541fd6' and Timestamp ge datetime'2022-10-24T21:50:41Z'";
var successFilter = "UserId eq '76d8bd02-7943-436e-b5a8-d7101a541fd6'";

var failureItems = table.Query<CommandLog>(filter: failureFilter);
var successItems = table.Query<CommandLog>(filter: successFilter);

Console.WriteLine(failureItems.Count());
Console.WriteLine(successItems.Count());
```

### Environment

.NET7 console app

**Comment by jsquire** [comment] 2022-11-14 13:53
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by christothes** [comment] 2022-11-14 15:28
Hi @nheath99 - If you are using Cosmos as your backend, this is expected behavior (documented [here](https://learn.microsoft.com/en-us/azure/cosmos-db/table/tutorial-query#query-by-using-an-odata-filter)). The service team is aware of it. (dupe of #31171)

**Comment by christothes** [comment] 2023-03-23 22:41
documented here: https://learn.microsoft.com/en-us/azure/cosmos-db/table/tutorial-query#query-by-using-an-odata-filter

**Closed by christothes** 2023-03-23 22:41 UTC
Labels: Service Attention, Client, customer-reported, question, Tables
