### ISSUE TITLE
[BUG] GetChatCompletionsAsync() doesn't return result

### ISSUE THREAD

**Issue by mnns** [Azure/azure-sdk-for-net#38053] opened 2023-08-07 10:51 UTC
### Library name and version

Azure.AI.OpenAI 1.0.0-beta.6

### Describe the bug

GetChatCompletionsAsync() doesn't return anything - it is frozen, while GetCompletionsAsync works perfectly.

### Expected behavior

Should return a result.

### Actual behavior

Doesn't return a result - its frozen.

### Reproduction Steps

            Response<ChatCompletions> responseWithoutStream = await openAIClient.GetChatCompletionsAsync(
                "gpt-4",
            new ChatCompletionsOptions(
                new List<ChatMessage>()
                {
                    new ChatMessage(ChatRole.System, prompt.system),
                    new ChatMessage(ChatRole.User, prompt.user),
                }
            )
            {
                Temperature = (float)0.7,
                MaxTokens = 50,
                NucleusSamplingFactor = (float)0.95,
                FrequencyPenalty = 0,
                PresencePenalty = 0,
            });

### Environment

.NET SDK:
 Version:   8.0.100-preview.5.23303.2
 Commit:    3fe444af72

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22000
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.100-preview.5.23303.2\

.NET workloads installed:
There are no installed workloads to display.

Host:
  Version:      8.0.0-preview.5.23280.8
  Architecture: x64
  Commit:       bc78804f5d

**Comment by jsquire** [comment] 2023-08-07 13:49
Closing as a duplicate of #38052

**Closed by jsquire** 2023-08-07 13:49 UTC
Labels: needs-triage, customer-reported, question
