### ISSUE TITLE
Add  Clear() method  for EventDataBatch class

### ISSUE THREAD

**Issue by zaozaoniao** [Azure/azure-sdk-for-net#9217] opened 2019-12-20 08:01 UTC
hi, I  use  the EventhubClient and EventDatabatch as  a singletion.

but  I found the eventdatabatch have no clear method。

---

when i have send the batch data using the EventDataBatch, the EventDataBatch  internal  list is not
clear automatic,  add  a clear method is simple.

**Comment by jsquire** [comment] 2019-12-24 17:16
Hi @zaozaoniao.  Thank you for your feedback.

At present this is a conscious design choice; it is intended that the batch not be reused after being sent due to the unmanaged resources managed by the batch.  Reusing a batch is something that we are tracking and may consider in the future, but is not currently planned.

Closing this out as "by design" for the time being.

**Closed by jsquire** 2019-12-24 17:16 UTC
Labels: Client, Event Hubs, customer-reported
