### ISSUE TITLE
[BUG] Upgrading Microsoft.Azure.WebJobs.Extensions.Storage breaks Azure Function Blob binding

### ISSUE THREAD

**Issue by FourLeggedHead** [Azure/azure-sdk-for-net#35515] opened 2023-04-12 08:24 UTC
### Library name and version

Microsoft.Azure.WebJobs.Extensions.Storage 5.1.1

### Describe the bug

Upgrading Microsoft.Azure.WebJobs.Extensions.Storage package from 4.0.5 to 5.1.1 breaks Azure Function Blob binding. Right after starting debugging the following error message is displayed:
[2023-04-12T08:10:28.597Z] A host error has occurred during startup operation '809fdb2b-6f57-4fb8-b5bf-31ac3341571a'.
[2023-04-12T08:10:28.608Z] Microsoft.Azure.WebJobs.Extensions.Storage.Blobs: Could not load type 'Microsoft.Azure.WebJobs.ParameterBindingData' from assembly 'Microsoft.Azure.WebJobs, Version=3.0.34.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.   
Value cannot be null. (Parameter 'provider')

### Expected behavior

As it does with version 4.0.5 of the same package, I should be able to run and debug my code.

### Actual behavior

I cannot run or debug my code.

### Reproduction Steps

An Azure Function with Blob output binding using package Microsoft.Azure.WebJobs.Extensions.Storage 4.0.5.
Upgrade to Microsoft.Azure.WebJobs.Extensions.Storage 5.1.1 and try to debug.

### Environment

Windows machine, .NET 6.0, Azure Functions v4.
VS Code 1.77.1

**Comment by navba-MSFT** [comment] 2023-04-13 03:33
@FourLeggedHead Thanks for reaching out to us and reporting this issue. The error message you are seeing indicates that there is a compatibility issue between the version of the `Microsoft.Azure.WebJobs.Extensions.Storage` package you are using and the version of the `Microsoft.Azure.WebJobs` package that it depends on.

It seems like the Microsoft.Azure.WebJobs.Extensions.Storage package version 5.1.1 depends on different version of the Microsoft.Azure.WebJobs package. However from the error message, it looks like you have version 3.0.34.0 of the Microsoft.Azure.WebJobs package installed and it is causing a dependencies issues.

Could you please try upgrading the `Microsoft.Azure.WebJobs` package to higher version. You can do this by updating the Microsoft.Azure.WebJobs package in your project's NuGet package manager. 

https://www.nuget.org/packages/Microsoft.Azure.WebJobs

Please let me know if this helps.

**Comment by FourLeggedHead** [comment] 2023-04-13 06:29
Hi @navba-MSFT ;

Upgrade that I did before submitting the bug. And my project has the following packages referenced:
Top-level Package                                     Requested   Resolved
   > Azure.Identity                                      1.8.2       1.8.2   
   > Azure.Security.Keyvault.Secrets                     4.5.0       4.5.0   
   > Microsoft.Azure.WebJobs                             3.0.37      3.0.37  
   > Microsoft.Azure.WebJobs.Extensions.DurableTask      2.9.0       2.9.0   
   > Microsoft.Azure.WebJobs.Extensions.Storage          5.1.1       5.1.1   
   > Microsoft.NET.Sdk.Functions                         4.1.1       4.1.1   
   > Microsoft.TeamFoundationServer.Client               16.170.0    16.170.0
   > Microsoft.VisualStudio.Services.Client              16.170.0    16.170.0
   > morelinq                                            3.3.2       3.3.2   

As you can see I have the latest version (3.0.37) of Microsoft.Azure.WebJobs... And my app still fails at startup, referring to v3.0.34 of the same package.

**Comment by navba-MSFT** [comment] 2023-04-17 04:59
@FourLeggedHead Thanks for your reply. The Microsoft.Azure.WebJobs.Extensions.Storage package version 5.1.1 depends on version 3.0.36 or later of the Microsoft.Azure.WebJobs package, while your app is trying to use version 3.0.34 of the Microsoft.Azure.WebJobs package.

To resolve this issue, you can try updating the Microsoft.Azure.WebJobs package to version 3.0.36 or later. You can do this manually by updating the Microsoft.Azure.WebJobs package in your project's NuGet package manager. And remove all the older references to (v3.0.34) manually from your app. Hope this helps.

**Comment by FourLeggedHead** [comment] 2023-04-17 08:28
Hi @navba-MSFT . I'm a bit surprised by your last message since the steps you are suggesting I have already taken, as I stated in my previous message (upgrade to v3.0.37, clean up and all) with no avail.

Actually found this issues this morning  #34467 that reports the same behavior as I described, the conclusion being, if there is a workaround, some fixing is needed.

**Comment by navba-MSFT** [comment] 2023-04-17 08:32
@FourLeggedHead Thanks for your reply. I am adding the Service team to look into this further.

**Comment by amnguye** [comment] 2023-05-03 17:39
Duplicate of https://github.com/Azure/azure-sdk-for-net/issues/34467

Just to reiterate the above issue, this isn't an issue on the Microsoft.Azure.WebJobs.Extensions.Storage package, rather that you would have to upgrade to the Azure Core Tools to at least [4.0.5030](https://github.com/Azure/azure-functions-core-tools/releases/tag/4.0.5030). There will be no fix pushed out for the Microsoft.Azure.WebJobs.Extensions.Storage package since we made the conclusion that upgrading the Azure Core Tools would be the best way (see https://github.com/Azure/azure-sdk-for-net/issues/34467#issuecomment-1442370186).

I didn't see you list the version of the Azure Core Tools you used so I'm not sure if upgrading resolved your issue or wasn't the issue.

**Comment by amnguye** [comment] 2023-05-03 17:41
Feel free to continue following up on this issue or the main issue, but since this is not an issue on the Microsoft.Azure.WebJobs.Extensions.Storage package but the Azure Core Tools, we are going to close this issue.

**Closed by amnguye** 2023-05-03 17:41 UTC
Labels: Storage, Service Attention, Client, customer-reported, question, needs-team-attention, duplicate
