### ISSUE TITLE
Event Grid SDK works with .NET Core on Windows, but not Mac

### ISSUE THREAD

**Issue by bradygaster** [Azure/azure-sdk-for-net#5484] opened 2019-03-16 08:21 UTC
**Describe the bug**
I tried running the sample code in the [documentation](https://docs.microsoft.com/en-us/dotnet/api/overview/azure/eventgrid?view=azure-dotnet) (which is great, BTW, thanks!) originally under .NET Core 3.0pre4. It didn't work so I recreated the scenario on .NET Core 2.2. The error is the same in both cases on a Mac. 

Whenever this line of code, from the documentation, is executed on a Mac: 

```csharp
EventGridClient client = new EventGridClient(topicCredentials);
```

This exception is thrown: 

***Exception or Stack Trace***
```
`System.FormatException: The format of value 'Darwin18.2.0DarwinKernelVersion18.2.0ThuDec20204653PST2018rootxnu-4903.241.11/RELEASE_X86_64' is invalid.
   at System.Net.Http.Headers.HeaderUtilities.CheckValidToken(String value, String parameterName)
   at System.Net.Http.Headers.ProductHeaderValue..ctor(String name, String version)
   at Microsoft.Rest.ServiceClient`1.UpdateDefaultUserAgentList(String headerName, String headerValue)
   at Microsoft.Rest.ServiceClient`1.get_DefaultUserAgentInfoList()
   at Microsoft.Rest.ServiceClient`1.InitializeHttpClient(HttpClient httpClient, HttpClientHandler httpClientHandler, DelegatingHandler[] handlers)
   at Microsoft.Azure.EventGrid.EventGridClient..ctor(ServiceClientCredentials credentials, DelegatingHandler[] handlers)
   at APIs.Orders.Controllers.OrdersController.Post(Order order) in /Users/bradygaster/source/OrderProcess-2_2/APIs.Orders/Controllers/OrdersController.cs:line 23
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.<>c__DisplayClass33_0.<WrapVoidMethod>b__0(Object target, Object[] parameters)
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.VoidResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

**To Reproduce**
1. Complete the [CLI Quick Start](https://docs.microsoft.com/en-us/azure/event-grid/custom-event-quickstart) to get resources created and to validate the event grid is working. 
1. Clone code that demonstrates this issue from [this repository](https://github.com/bradygaster/DotNetCoreEventGrid). 
1. Open the code using Visual Studio Code or Visual Studio for Mac on a Mac. 
1. Configure `OrdersController.cs` with the proper URL and key. 

   ```
   string topicEndpoint = "url";
   string topicKey = "key";
   ```

1. Debug the project
1. Use postman or curl to send the JSON payload below to `https://localhost:5001/api/orders`. 

```json
{
	"orders" : [
		{
			"productId" : "27980596-6f6c-437f-b9af-81f2bb762d32",
			"quantity" : 2,
			"price" : 5.99
		},
		{
			"productId" : "fc2a9925-c536-416c-b1ce-205a1037ea43",
			"quantity" : 4,
			"price" : 3.99
		}
	]
}
```
1. Note the error. 
1. Run the same code in Visual Studio on Windows.
1. Note there is no error, and the message is sent to Event Grid. 

***Code Snippet***
This code from the doc seems to be when the error occurs. 

```csharp
EventGridClient client = new EventGridClient(topicCredentials);
```

**Expected behavior**
The SDK should work the same way on Windows, Mac, and Linux. There should be no difference in the platform's behavior when using the SDK. 

**Screenshots**

**Setup (please complete the following information):**
 - OS: MacBook
 - IDE : Visual Studio Code, Visual Studio for Mac, `dotnet run`, versions 2.2 and 3.0-preview4 of .NET Core. 
 - Event Grid SDK version 3.0

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by bradygaster** [comment] 2019-03-16 08:33
looks like this is related to #5046

**Comment by bradygaster** [comment] 2019-03-16 08:37
Confirming - by upgrading the `Microsoft.Rest.ClientRuntime` to the latest version (2.3.20) resolved this issue.

**Comment by Petermarcu** [comment] 2019-03-17 02:38
@bradygaster , sounds like we should be shipping an updated EvenGrid package with a reference to the newer ClientRuntime then. Sound right? @AlexGhiondea can you help coordinate that?

**Comment by bradygaster** [comment] 2019-03-20 18:04
@Petermarcu yes i think that's the correct fix here. Given this issue is related to #5046, which seems to indicate the issue is resident in a few other places, it feels like your approach would resolve this [and other] issues. Thanks for the attention!

**Comment by AlexGhiondea** [comment] 2019-04-18 05:02
@bradygaster sorry for the long delay. I'm looking into this now.

**Comment by AlexGhiondea** [comment] 2019-04-18 19:38
@bradygaster we released an updated version of the EventGrid package: https://www.nuget.org/packages/Microsoft.Azure.EventGrid/3.1.0 

Can you give that a try and see if the issue is still reproducing?

**Comment by bradygaster** [comment] 2019-04-18 23:46
@AlexGhiondea your timing is amazing. i was just wondering if this had been fixed. i'm prototyping something atm and EG was my next hurdle, so this is **great**.

**Comment by AlexGhiondea** [comment] 2019-05-09 20:52
@bradygaster it sounds like the updated package worked for you. I am going to close this issue but feel free to reactivate if you are still having issues.

**Closed by AlexGhiondea** 2019-05-09 20:52 UTC
Labels: Client, Event Grid
