### ISSUE TITLE
[Servicebus] MessageDraining_QueueWithSessions_Batch failing in nightly runs

### ISSUE THREAD

**Issue by v-yilinhu** [Azure/azure-sdk-for-net#27352] opened 2022-03-04 09:43 UTC
Servicebus nightly test runs are failing with:

> Error message
> Microsoft.Azure.WebJobs.Host.Indexers.FunctionIndexingException : Error indexing method 'DrainModeTestJobQueueBatch.QueueWithSessionsBatch'
> ----> System.InvalidOperationException : Can't bind parameter 'messageActions' to type 'Microsoft.Azure.WebJobs.ServiceBus.ServiceBusSessionMessageActions'.
> 
> 
> Stack trace
>    at Microsoft.Azure.WebJobs.Host.RecoverableException.TryRecover(ILogger logger) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Exceptions\RecoverableException.cs:line 81
>    at Microsoft.Azure.WebJobs.Host.Indexers.FunctionIndexer.IndexTypeAsync(Type type, IFunctionIndexCollector index, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Indexers\FunctionIndexer.cs:line 94
>    at Microsoft.Azure.WebJobs.Host.Indexers.FunctionIndexProvider.CreateAsync(CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Indexers\FunctionIndexProvider.cs:line 97
>    at Microsoft.Azure.WebJobs.Host.Indexers.FunctionIndexProvider.GetAsync(CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Indexers\FunctionIndexProvider.cs:line 73
>    at Microsoft.Azure.WebJobs.Host.Executors.JobHostContextFactory.Create(JobHost host, CancellationToken shutdownToken, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\JobHostContextFactory.cs:line 119
>    at Microsoft.Azure.WebJobs.JobHost.InitializeHostAsync(CancellationToken cancellationToken, TaskCompletionSource`1 initializationTask) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\JobHost.cs:line 359
>    at Microsoft.Azure.WebJobs.JobHost.StartAsyncCore(CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\JobHost.cs:line 105
>    at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
>    at Microsoft.Azure.WebJobs.Host.EndToEndTests.WebJobsServiceBusTestBase.BuildHost[TJobClass](Action`1 configurationDelegate, Boolean startHost, Boolean useTokenCredential) in /Users/runner/work/1/s/sdk/servicebus/Microsoft.Azure.WebJobs.Extensions.ServiceBus/tests/WebJobsServiceBusTestBase.cs:line 174
>    at Microsoft.Azure.WebJobs.Host.EndToEndTests.ServiceBusSessionsEndToEndTests.BuildSessionHost[T](Boolean addCustomProvider, Boolean autoComplete, Boolean enableCrossEntityTransaction, Nullable`1 maxMessages) in /Users/runner/work/1/s/sdk/servicebus/Microsoft.Azure.WebJobs.Extensions.ServiceBus/tests/ServiceBusSessionsEndToEndTests.cs:line 449
>    at Microsoft.Azure.WebJobs.Host.EndToEndTests.ServiceBusSessionsEndToEndTests.TestMultipleDrainMode[T](Boolean sendToQueue) in /Users/runner/work/1/s/sdk/servicebus/Microsoft.Azure.WebJobs.Extensions.ServiceBus/tests/ServiceBusSessionsEndToEndTests.cs:line 588
>    at Microsoft.Azure.WebJobs.Host.EndToEndTests.ServiceBusSessionsEndToEndTests.MessageDraining_QueueWithSessions_Batch() in /Users/runner/work/1/s/sdk/servicebus/Microsoft.Azure.WebJobs.Extensions.ServiceBus/tests/ServiceBusSessionsEndToEndTests.cs:line 428
>    at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.BlockUntilCompleted()
>    at NUnit.Framework.Internal.MessagePumpStrategy.NoMessagePumpStrategy.WaitForCompletion(AwaitAdapter awaiter)
>    at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.<>c__DisplayClass1_0.<Execute>b__0()
>    at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.RunTestMethodInThreadAbortSafeZone(TestExecutionContext context, Action action)
> --InvalidOperationException
>    at Microsoft.Azure.WebJobs.Host.Bindings.Data.ClassDataBindingProvider`1.TryCreateAsync(BindingProviderContext context) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Bindings\Data\ClassDataBindingProvider.cs:line 35
>    at Microsoft.Azure.WebJobs.Host.Bindings.CompositeBindingProvider.TryCreateAsync(BindingProviderContext context) in C:\projects\a

For more details check here:

- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1406774&view=results

@jsquire for notification.

**Comment by jsquire** [comment] 2022-03-04 14:02
Duplicate of #27352

**Closed by jsquire** 2022-03-04 14:02 UTC
Labels: Service Bus, Client, needs-team-attention
