### ISSUE TITLE
[BUG] ASP.NET 4.7, ServiceBusProcessor.StartProcessingAsync() crashes website (The process was terminated due to an internal error in the .NET Runtime)

### ISSUE THREAD

**Issue by mykhailopylyp** [Azure/azure-sdk-for-net#33517] opened 2023-01-16 18:14 UTC
### Library name and version

Azure.Messaging.ServiceBus 7.12.0

### Describe the bug

We want to integrate ServiceBus into our old ASP.NET 4.7 MVC application. We do not consider upgrading to the newest .NET because of effort considerations. 

The most straightforward integration crashes our application. The same code works for a console application. We get `The process was terminated due to an internal error in the .NET Runtime`. 

[link to a repository where you can test it.](https://github.com/mykhailopylyp/ServiceBusClient)

Here's a sample code:
```
            var fullyQualifiedNamespace = "qcash-concert2-test.servicebus.windows.net";
            var queueName = "TestQueue";
            var credentials = new DefaultAzureCredential(new DefaultAzureCredentialOptions()
            {
                ExcludeAzureCliCredential = false,
                ExcludeEnvironmentCredential = false,
                ExcludeManagedIdentityCredential = false,
                ExcludeSharedTokenCacheCredential = false,
                ExcludeInteractiveBrowserCredential = true,
                ExcludeVisualStudioCodeCredential = false,
                ExcludeVisualStudioCredential = false,
            });

            var serviceBusClient = new ServiceBusClient(fullyQualifiedNamespace, credentials, new ServiceBusClientOptions
            {
                RetryOptions = new ServiceBusRetryOptions
                {
                    MaxRetries = 5,    //The maximum number of retry attempts before giving up
                    Mode = ServiceBusRetryMode.Exponential,        //The approach to use for calculating retry delays
                    MaxDelay = TimeSpan.FromMilliseconds(90000)
                }
            });

            var administartionClient = new ServiceBusAdministrationClient(fullyQualifiedNamespace, credentials);

            if (await administartionClient.QueueExistsAsync(queueName, CancellationToken.None) == false)
            {
                var queueOptions = new CreateQueueOptions(queueName)
                {
                    DeadLetteringOnMessageExpiration = true,
                    EnableBatchedOperations = true,
                    EnablePartitioning = false,
                    MaxSizeInMegabytes = 1024,
                    RequiresDuplicateDetection = false,
                    RequiresSession = false,
                };

                queueOptions.AutoDeleteOnIdle = TimeSpan.FromMinutes(60);

                _ = await administartionClient.CreateQueueAsync(queueOptions, CancellationToken.None);
            }

            var processor = serviceBusClient.CreateProcessor(queueName, new ServiceBusProcessorOptions()
            {
                AutoCompleteMessages = true,
                MaxConcurrentCalls = Environment.ProcessorCount,
                PrefetchCount = Environment.ProcessorCount * 100,
                ReceiveMode = ServiceBusReceiveMode.ReceiveAndDelete
            });

            processor.ProcessMessageAsync += (args) =>
            {
                return Task.Run(() =>
                {
                    Thread.Sleep(1000);
                });
            };

            processor.ProcessErrorAsync += OnMessageProcessingException;
            await processor.StartProcessingAsync(CancellationToken.None);

            await Task.Run(() =>
            {
                Thread.Sleep(5 * 1000);
            });
```

Logs from Event Viewer
```
Application: iisexpress.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an internal error in the .NET Runtime at IP 00007FFC367F3D99 (00007FFC367F0000) with exit code 80131506.

Faulting application name: iisexpress.exe, version: 10.0.25095.1000, time stamp: 0x7d00e3ab
Faulting module name: clr.dll, version: 4.8.4515.0, time stamp: 0x624ce98e
Exception code: 0xc0000005
Fault offset: 0x0000000000003d99
Faulting process id: 0xc584
Faulting application start time: 0x01d929d2fecf87d7
Faulting application path: C:\Program Files\IIS Express\iisexpress.exe
Faulting module path: C:\Windows\Microsoft.NET\Framework64\v4.0.30319\clr.dll
Report Id: 137ef970-d27f-4f0b-b506-0f4879426b6d
Faulting package full name: 
Faulting package-relative application ID: 
```

### Expected behavior

The website doesn't crash

### Actual behavior

The website crashes

### Reproduction Steps

- Clone repository
- Start web application. It's an asp.net MVC template application.
- Open the Contact tab

### Environment

.NET SDK (reflecting any global.json):
 Version:   6.0.401
 Commit:    0906eae6f8

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19044
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.401\

global.json file:
  Not found

Host:
  Version:      6.0.13
  Architecture: x64
  Commit:       1af80ba017

.NET SDKs installed:
  5.0.301 [C:\Program Files\dotnet\sdk]
  5.0.408 [C:\Program Files\dotnet\sdk]
  6.0.101 [C:\Program Files\dotnet\sdk]
  6.0.113 [C:\Program Files\dotnet\sdk]
  6.0.308 [C:\Program Files\dotnet\sdk]
  6.0.401 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.16 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

VS 2022 Version 17.3.5

**Comment by mykhailopylyp** [comment] 2023-01-17 11:27
We tried to run the same code with the latest .NET and it works (doesn't crash). So, it's a .NET framework related issue.

**Comment by jsquire** [comment] 2023-01-17 14:36
Hi @mykhailopylyp.   Thank you for reaching out and we regret that you're experiencing difficulties.   Would you please share the exact version stamp from your .NET Framework environment on the host so that we can    If you are able to capture and share a dump, that would also be very helpful.

I'd also appreciate your perspective on what the application is intended to do.   In your home controller, you're creating and starting a processor and then returning.  After you return your view, the processor and client will go out of scope without being stopped nor the connection closed gracefully.   Depending on the host and its state, the callback to the error handler may cause a fault since the instance of the class itself is out of scope.

**Comment by mykhailopylyp** [comment] 2023-01-17 15:31
Hi @jsquire,

Environment.Version = {4.0.30319.42000}. 

Dump file.
[iisexpress.exe.3444.zip](https://github.com/Azure/azure-sdk-for-net/files/10436524/iisexpress.exe.3444.zip)

We need service bus to integrated with third party service (sending and receiving messages). I tried to make the example as simple as possible to demonstrate the issue (we use service bus instances correctly in our application). 

Have you tried to run the repository I've created? It is reproducible at least on two machines.

**Comment by jsquire** [comment] 2023-01-19 15:28
Hi @mykhailopylyp.   I've had a chance to dig into the memory dump and the sample code that you provided.  The root cause of your crash is how the application is using the processor.   In short, the application code is a race condition which is likely to intermittently reproduce the crash and may manifest more frequently on some hosts than others.  

This isn't something that the SDK can guard against or mitigate, it requires adjustments in the application.  I've provided some mitigation suggestions below.

### Root Cause Details

When the crash manifests, the sequence of events is:

- IIS creates an instance of `HomeController` to service a specific request and routes that request to the `Contact` method.

- The `Contact` method creates an instance of the processor  and configures it to use  instance methods in the controller class as event handler callbacks.

- The `Contact` method then starts the processor, which spins up a set of background tasks responsible for reading messages and invoking the event handlers.

- The `Contact` method  then returns a view without stopping the processor, so those background tasks are still running. 

- The executing instance of `HomeController` goes out of scope, taking the processor it created and the methods assigned to use for handling events with it.  

- When the background task reading Service Bus messages attempts to raise the event, the .NET runtime isn't able to resolve the address of the callback that was registered, which causes an access violation and crashes the process.

The crash manifesting depends on the connection to Service Bus being established and background tasks starting before the controller instance goes out of scope as well as the availability of messages to be read.

### Crash Dump Details

The inability for the runtime to resolve the methods registered as event handlers is represented in the dump when analyzing the exception and the CLR stack.  

Root message:  `Failed to request MethodData, not in JIT code range` 

```text
EXCEPTION_RECORD:  (.exr -1)ExceptionAddress: 00007ffcfb9c3d99 (clr!JIT_IsInstanceOfInterface+0x0000000000000009)
  ExceptionCode: c0000005 (Access violation)
  ExceptionFlags: 00000001
NumberParameters: 2
   Parameter[0]: 0000000000000000
   Parameter[1]: 0000000000000001
Attempt to read from address 0000000000000001

PROCESS_NAME:  iisexpress.exe
READ_ADDRESS:  0000000000000001
ERROR_CODE: (NTSTATUS) 0xc0000005 - The instruction at 0x%p referenced memory at 0x%p. The memory could not be %s.
```

### Mitigation Strategies

The `ServiceBusProcessor` is not a good fit for the pattern in which the application is attempting to use it.  If you need to have a set of messages read as part of the `Contact` call, `ServiceBusReceiver` would be a better fit, the key difference is that it uses a pull-based pattern rather than push.  This allows the application full control over when reads happen and the ability to ensure that processing and clean-up are complete before the view is returned.

If you're looking to have messages being processed continually, I'd suggest looking into using an implementation of [BackgroundService](https://learn.microsoft.com/dotnet/api/microsoft.extensions.hosting.backgroundservice?view=dotnet-plat-ext-7.0) from the hosting extension package.  Though most articles discuss using it in the context of ASP.NET Core, the extensions package supports `net462` as a target and would work with your .NET 4.7.2 environment.

**Comment by mykhailopylyp** [comment] 2023-01-20 10:57
/unresolve

Hi @jsquire,

Thank you for your help! I believe I encountered a different issue that is specified in the root cause.

I've updated an example to demonstrate it. Made ServiceBusClient and ServiceBusProcessor as static members as well as delegates for processing messages and moved initialization to Application_Start. So, now all objects that are potentially needed for message processing have a lifetime of the application. 
```
    public class MvcApplication : System.Web.HttpApplication
    {
        public static ServiceBusClient ServiceBusClient { get; set; }
        public static ServiceBusProcessor Processor { get; set; }

        protected void Application_Start()
        {
            AreaRegistration.RegisterAllAreas();
            FilterConfig.RegisterGlobalFilters(GlobalFilters.Filters);
            RouteConfig.RegisterRoutes(RouteTable.Routes);
            BundleConfig.RegisterBundles(BundleTable.Bundles);

            var fullyQualifiedNamespace = "qcash-concert2-test.servicebus.windows.net";
            var queueName = "TestQueue";
            var credentials = new DefaultAzureCredential(new DefaultAzureCredentialOptions()
            {
                ExcludeAzureCliCredential = false,
                ExcludeEnvironmentCredential = false,
                ExcludeManagedIdentityCredential = false,
                ExcludeSharedTokenCacheCredential = false,
                ExcludeInteractiveBrowserCredential = true,
                ExcludeVisualStudioCodeCredential = false,
                ExcludeVisualStudioCredential = false,
            });

            ServiceBusClient = new ServiceBusClient(fullyQualifiedNamespace, credentials, new ServiceBusClientOptions
            {
                RetryOptions = new ServiceBusRetryOptions
                {
                    MaxRetries = 5,    //The maximum number of retry attempts before giving up
                    Mode = ServiceBusRetryMode.Exponential,        //The approach to use for calculating retry delays
                    MaxDelay = TimeSpan.FromMilliseconds(90000)
                }
            });

            var administartionClient = new ServiceBusAdministrationClient(fullyQualifiedNamespace, credentials);

            if (administartionClient.QueueExistsAsync(queueName, CancellationToken.None).Result == false)
            {
                var queueOptions = new CreateQueueOptions(queueName)
                {
                    DeadLetteringOnMessageExpiration = true,
                    EnableBatchedOperations = true,
                    EnablePartitioning = false,
                    MaxSizeInMegabytes = 1024,
                    RequiresDuplicateDetection = false,
                    RequiresSession = false,
                };

                queueOptions.AutoDeleteOnIdle = TimeSpan.FromMinutes(60);

                var _ = administartionClient.CreateQueueAsync(queueOptions, CancellationToken.None).Result;
            }

            Processor = ServiceBusClient.CreateProcessor(queueName, new ServiceBusProcessorOptions()
            {
                AutoCompleteMessages = true,
                MaxConcurrentCalls = Environment.ProcessorCount,
                PrefetchCount = Environment.ProcessorCount * 100,
                ReceiveMode = ServiceBusReceiveMode.ReceiveAndDelete
            });

            Processor.ProcessMessageAsync += OnMessageProcessingAsync;

            Processor.ProcessErrorAsync += OnMessageProcessingException;
        }

        private static Task OnMessageProcessingAsync(ProcessMessageEventArgs args)
        {
            return Task.Run(() =>
            {
                Thread.Sleep(1000);
            });
        }

        private static async Task OnMessageProcessingException(ProcessErrorEventArgs args)
        {
            if (args == null || args.CancellationToken.IsCancellationRequested)
                return;

            if (args.Exception is ServiceBusException serviceBusException
                && serviceBusException.Reason == ServiceBusFailureReason.MessagingEntityNotFound)
            {
                // await ServiceBusFactory.CreateQueueAsync(_processor.FullyQualifiedNamespace, args.EntityPath, _queueTimeToLive, CancellationToken.None).ConfigureAwait(false);
            }
        }
    }
```

```
        public async Task<ActionResult> Contact()
        {
            await MvcApplication.Processor.StartProcessingAsync(CancellationToken.None);

            await Task.Run(() =>
            {
                Thread.Sleep(5 * 1000);
            });

            ViewBag.Message = "Your contact page.";

            return View();
        }
```

[Updated example.](https://github.com/mykhailopylyp/ServiceBusClient)

New dump file
[iisexpress.exe.26172.zip](https://github.com/Azure/azure-sdk-for-net/files/10465605/iisexpress.exe.26172.zip)

**Comment by jsquire** [comment] 2023-01-20 15:08
@mykhailopylyp.   Can you please detail the exception that you're seeing with your new example?   At a glance with the sample code, you'll throw every time you call your `Contact` method except the first.   You cannot call `StartProcessingAsync` on the processor when it's already running.

I'd suggest that you consider adding some `try/catch` block around the application code and inspect the exceptions rather than allowing the process to crash.  The error details will help you better understand the pattern of exceptions that you're seeing.

**Comment by danielmarbach** [comment] 2023-01-23 08:29
@mykhailopylyp I'm a community member and regular contributor to the Azure .NET SDK. Maybe I can help you with some more guidance around using Azure Service Bus within MVC applications as well as in general setting up messaging infrastructure on top of Azure Service Bus for your PoC. 

Since I could not find your contact details on Github I'm reaching out here. Feel free to send me an email at "daniel dot marbach at particular dot net" or reach out to me over [twitter](https://twitter.com/danielmarbach) or [linkedin](https://www.linkedin.com/in/daniel-marbach-49857939/).

**Comment by jsquire** [comment] 2023-01-23 16:18
Hi @mykhailopylyp.   At this point, I'm confident that this is an application issue and not something with the SDK itself.   The patterns that you're using aren't recommended and are susceptible to the types of issues that you're running into.  There's not much more that we can offer outside of my previous suggestions to mitigate and explore the exception:

- It seems from your scenario like the processor is not the best type for what you're looking to do.  I'd suggest looking into a shared instance of the `[ServiceBusReceiverClient](hhttps://learn.microsoft.com/dotnet/api/azure.messaging.servicebus.servicebusreceiver?view=azure-dotnet)` that will allow you to pull messages on-demand when your `Contact` method runs.

- If you're set on having messages being processed continually in the background, I'd suggest looking into using an implementation of [BackgroundService](https://learn.microsoft.com/dotnet/api/microsoft.extensions.hosting.backgroundservice?view=dotnet-plat-ext-7.0) from the hosting extension package.  Though most articles discuss using it in the context of ASP.NET Core, the extensions package supports `net462` as a target and would work with your .NET 4.7.2 environment.  That is the recommended way to host long-running services.

- I'd strongly suggest following the guidance from [Processing Unhandled Exceptions](https://learn.microsoft.com/aspnet/web-forms/overview/older-versions-getting-started/deploying-web-site-projects/processing-unhandled-exceptions-cs) and implementing the `[Application_Error](https://learn.microsoft.com/aspnet/web-forms/overview/older-versions-getting-started/deploying-web-site-projects/processing-unhandled-exceptions-cs#retrieving-information-about-the-unhandled-exception)` handler to help capture and understand the pattern of exceptions that you're seeing.

- I'd also suggest that you consider adding some try/catch block around the application code to allow you to inspect and understand exceptions rather than allowing the process to crash. 

Since I've already looked over the dump and sample, I'll offer analysis one last time.  The latest implementation still attempts to call `StartProcessingAsync` multiple times, as the `StartedProcessing` variable is never set to `true` - I believe that L42 was meant to do so, but has a typo.  _(see below)_ 

Unfortunately, even if L42 is fixed, the application is still likely to crash as the implementation is not thread-safe and the `Contact` method may be called concurrently.  This would result in intermittent attempts to start the processor twice.  As mentioned in the mitigations, persistent background processing should be performed in a hosted service, and the processor should be managed from there rather than the controller.

![image](https://user-images.githubusercontent.com/913445/214086803-caff9f03-12fd-4c75-9111-bba4abb56059.png)

**Closed** 2023-01-30 22:03 UTC
Labels: Service Bus, Client, customer-reported, question, issue-addressed
