### ISSUE TITLE
[BUG] SubscriptionClient.RegisterSessionHandler throws plenty of timeout exceptions when message no message arrives for certain time

### ISSUE THREAD

**Issue by Pucmaster** [Azure/azure-sdk-for-net#10017] opened 2020-02-18 15:05 UTC
I have these settings which i am putting to constructor and then using for initializing SubscriptionClient 
`
        public ServiceBusDefaultConfiguration(Func<ExceptionReceivedEventArgs, Task> exceptionReceivedHandler)
        {
            this.RetryPolicy = new RetryExponential(TimeSpan.FromSeconds(5), TimeSpan.FromSeconds(30), 10);
            this.ReceiveMode = ReceiveMode.PeekLock;
            this.PrefetchCount = 0;
            this.MessageHandlerOptions = new MessageHandlerOptions(exceptionReceivedHandler)
            {
                MaxConcurrentCalls = 1,
                AutoComplete = false,
                MaxAutoRenewDuration = TimeSpan.FromMinutes(5)
            };
        }
`
`            
subClient = new SubscriptionClient(serviceBusConnection, entityPath, subName, config.ReceiveMode, config.RetryPolicy);

subClient.RegisterSessionHandler(ProcessMessagesInSessionAsync, config.SessionHandlerOptions);
`

**If no message will arrive for a certain time, I will get plenty of exceptions that will not bubble up to application. Is this expected ?** How to handle such a scenario?  
Maybe I dont know how to catch them. ExceptionHandler stored in SessionHandlerOptions is not triggered and other try catch statements anywhere are not triggered either. 

**Exceptions thrown:** 
Exception thrown: 'Microsoft.Azure.Amqp.AmqpException' in System.Private.CoreLib.dll
Exception thrown: 'Microsoft.Azure.Amqp.AmqpException' in System.Private.CoreLib.dll
Exception thrown: 'Microsoft.Azure.ServiceBus.ServiceBusTimeoutException' in Microsoft.Azure.ServiceBus.dll
Exception thrown: 'Microsoft.Azure.ServiceBus.ServiceBusTimeoutException' in System.Private.CoreLib.dll
Exception thrown: 'Microsoft.Azure.ServiceBus.ServiceBusTimeoutException' in System.Private.CoreLib.dll
Exception thrown: 'Microsoft.Azure.ServiceBus.ServiceBusTimeoutException' in System.Private.CoreLib.dll
Exception thrown: 'Microsoft.Azure.ServiceBus.ServiceBusTimeoutException' in System.Private.CoreLib.dll
Exception thrown: 'Microsoft.Azure.ServiceBus.ServiceBusTimeoutException' in System.Private.CoreLib.dll
Exception thrown: 'Microsoft.Azure.ServiceBus.ServiceBusTimeoutException' in System.Private.CoreLib.dll
Exception thrown: 'Microsoft.Azure.ServiceBus.ServiceBusTimeoutException' in System.Private.CoreLib.dll
Exception thrown: 'Microsoft.Azure.ServiceBus.ServiceBusTimeoutException' in System.Private.CoreLib.dll
Exception thrown: 'Microsoft.Azure.ServiceBus.ServiceBusTimeoutException' in Microsoft.Azure.ServiceBus.dll
Exception thrown: 'System.Threading.Tasks.TaskCanceledException' in System.Private.CoreLib.dll
Exception thrown: 'Microsoft.Azure.ServiceBus.ServiceBusTimeoutException' in System.Private.CoreLib.dll

**Comment by nemakam** [comment] 2020-02-18 20:02
@Pucmaster , we will investigate it and let you know. 
This behavior is by design as of now, and I can understand that it might be frustrating. There might not be a straightforward solution as it would become a breaking change in terms of behavior. 
Quick fix from your end would be to ignore timeoutExceptions coming from RegisterSessionHandler. We will try to wrap our heads and see what could be done here.

**Comment by ramya-rao-a** [comment] 2021-08-24 21:17
Thanks for reporting @Pucmaster 

Like @nemakam mentioned there is no solution without a breaking change in behavior.

Furthermore, please note that a newer package [Azure.Messaging.ServiceBus](https://www.nuget.org/packages/Azure.Messaging.ServiceBus) is available as of November 2020. While the older package `Microsoft.Azure.ServiceBus` will continue to receive critical bug fixes, we strongly encourage you to upgrade. Read the migration guide at https://aka.ms/azsdk/net/migrate/sb for more details.

If you continue to see a similar problem after moving to the new package, please do open a new issue and we would be happy to assist

**Closed by ramya-rao-a** 2021-08-24 21:17 UTC
Labels: Service Bus, Service Attention, Client, customer-reported, question, needs-team-attention

**Comment by xbaha** [comment] 2022-01-14 10:55
hi, i am getting this error on the new Azure.Messaging.ServiceBus:

System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() in /_/src/libraries/System.Private.CoreLib/src/System/Runtime/ExceptionServices/ExceptionDispatchInfo.cs:line 56\r\n   
at Azure.Messaging.ServiceBus.Amqp.AmqpConnectionScope.<CreateReceivingLinkAsync>d__74.MoveNext() in /_/sdk/servicebus/Azure.Messaging.ServiceBus/src/Amqp/AmqpConnectionScope.cs:line 714\r\n   
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() in /_/src/libraries/System.Private.CoreLib/src/System/Runtime/ExceptionServices/ExceptionDispatchInfo.cs:line 56\r\n   
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) in /_/src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/TaskAwaiter.cs:line 173\r\n   
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) in /_/src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/TaskAwaiter.cs:line 150\r\n   
at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult() in /_/src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/TaskAwaiter.cs:line 551\r\n   
at Azure.Messaging.ServiceBus.Amqp.AmqpConnectionScope.<OpenReceiverLinkAsync>d__69.MoveNext() in /_/sdk/servicebus/Azure.Messaging.ServiceBus/src/Amqp/AmqpConnectionScope.cs:line 349\r\n   
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() in /_/src/libraries/System.Private.CoreLib/src/System/Runtime/ExceptionServices/ExceptionDispatchInfo.cs:line 56\r\n   
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) in /_/src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/TaskAwaiter.cs:line 173\r\n   
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) in /_/src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/TaskAwaiter.cs:line 150\r\n   
at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult() in /_/src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/TaskAwaiter.cs:line 551\r\n   
at Azure.Messaging.ServiceBus.Amqp.AmqpReceiver.<OpenReceiverLinkAsync>d__35.MoveNext() in /_/sdk/servicebus/Azure.Messaging.ServiceBus/src/Amqp/AmqpReceiver.cs:line 200\r\n   
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() in /_/src/libraries/System.Private.CoreLib/src/System/Runtime/ExceptionServices/ExceptionDispatchInfo.cs:line 56\r\n   
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) in /_/src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/TaskAwaiter.cs:line 173\r\n   
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) in /_/src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/TaskAwaiter.cs:line 150\r\n   
at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult() in /_/src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/TaskAwaiter.cs:line 551\r\n   
at Microsoft.Azure.Amqp.FaultTolerantAmqpObject`1.<OnCreateAsync>d__6.MoveNext()"	string

**Comment by xbaha** [comment] 2022-01-14 10:58
@ramya-rao-a My application stops, and this error usually happens when I put a breakpoint somewhere in my app, then continue. It's still unclear to me on what conditions this error pops up, but it's there and happened multiple times already.

**Comment by ramya-rao-a** [comment] 2022-01-14 19:37
@xbaha, Please open a new GitHub issue for the problems you are seeing along with a code snippet showing how you are using the Service Bus package and the version of the package being used
