### ISSUE TITLE
[BUG] Azure.Messaging.EventHub PartitionReceiver.ReceiveAsync does not always consider CancellationToken

### ISSUE THREAD

**Issue by diverges** [Azure/azure-sdk-for-net#21019] opened 2021-05-12 02:23 UTC
**Describe the bug**
Calling PartitionReceiver.ReceiveAsync(Number, Token) when the token has been canceled and no events are being received. ReceiveAsync will wait the default MaximumWaitTime (60 seconds) before returning. This can cause closing of a receiver to take up to a minute.

**Expected behavior**
PartitionReceiver.ReceiveAsync returns as soon as the token is canceled, or faster than 60 seconds.

**Actual behavior (include Exception or Stack Trace)**
ReceiveAsync takes a minute to return. Issue can be avoided by passing in a MaxWaitTime and overwriting the default of 60. I think this might be [the problematic call](https://github.com/Azure/azure-sdk-for-net/blob/2f3fb5862360ef9ff762072a1540feb84ea89c35/sdk/eventhub/Azure.Messaging.EventHubs/src/Amqp/AmqpConsumer.cs#L240) made by ReceiveAsync internals.

**To Reproduce**
```csharp
while (!this.cts.IsCancellationRequested)
{
    IEnumerable<EventData> batch = await this.partitionReceiver.ReceiveBatchAsync(MaxBatchSize, this.cts.Token);
}
```
**Environment:**
 - Azure.Messaging.EventHubs v5.3.0

**Comment by jsquire** [comment] 2021-05-12 14:55
Hi @diverges.  Thank you for reaching out and we regret that you're experiencing difficulties.  Unfortunately, what you're seeing is the expected behavior.  The transport library that the Azure Messaging SDKs are built on is timeout-based and does not support cancellation.   The `ReceiveBatchAsync` call does it's best to honor cancellation before calling into the transport, at which point the timeout takes precedence.

We've had an open internal request with the folks that own `Microsoft.Azure.Amqp` for cancellation support for a while;  we've  also recently opened a Git Hub issue to allow folks like yourself to add your voice and experiences to (hopefully) raise the priority on that request.   Please feel free to upvote and/or add comments to [#181](https://github.com/Azure/azure-amqp/issues/181) if you'd like.

**Comment by diverges** [comment] 2021-05-12 18:53
Thanks for the explanation. I can mitigate the issue by passing MaxWaitTime to the `ReceiveBatchAsync` call and setting it to something like 1 second.

**Comment by jsquire** [comment] 2021-05-13 13:21
That's probably your best path forward for maintaining responsiveness.  

For what it's worth, that approach also won't change the behavior that you're seeing when events are available;  the transport does not use the wait time to try and accumulate the requested maximum batch size - it will return whatever is available in the prefetch queue as soon as anything is available.   In a scenario where events aren't continually flowing, you're likely to see frequent dispatches of a small number of events regardless of how long the wait time is set for.

**Comment by jsquire** [comment] 2021-05-17 14:39
It looks like we've reached the point where we have a workaround, are blocked on any additional enhancements by an external dependency, and discussion as tapered off.  I'm going to close this out; please feel free to reopen if you'd like to discuss further.

**Closed by jsquire** 2021-05-17 14:39 UTC
Labels: Client, Event Hubs, customer-reported, needs-author-feedback, question
