### ISSUE TITLE
[BUG] Unable to disable function

### ISSUE THREAD

**Issue by andrew-sumner** [Azure/azure-sdk-for-net#40829] opened 2023-12-17 04:24 UTC
### Library name and version

Azure.ResourceManager.AppService 1.0.2

### Describe the bug

Setting the IsDisabled property of FunctionEnvelopeData does disable the function, it does however return true when fetching the current state of the function. 

Should this work, or is there an alternative?

```
var bindings = new { bindings = new[] { new { name = "Timer", type = "timerTrigger", direction = "in", schedule = scheduleDetail.GetAsCron() } } };

var functionEnvelopeData = new FunctionEnvelopeData
{
    Config = BinaryData.FromObjectAsJson(bindings),
    TestData = "",
    IsDisabled = true,
    Language = "powershell"
};

functionEnvelopeData.Files.Add(new KeyValuePair<string, string>("run.ps1", functionCode));

var result = await scheduleFunctions.CreateOrUpdateAsync(WaitUntil.Completed, action.ToString(), functionEnvelopeData);
```

### Expected behavior

Function should be disabled.

### Actual behavior

Function is enabled.

### Reproduction Steps

Use the SDK to create a function on a function app setting the IsDisabled property to true.

**Comment by jsquire** [comment] 2023-12-17 16:42
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by dvbb** [comment] 2024-03-15 07:11
Hi, @andrew-sumner 
I reproduce this issue and it looks like the service side issue. When I update a `SiteSlotFunctionResource` it will always return `isDisabled=False` (whatever the function is disabled or not )
![image](https://github.com/Azure/azure-sdk-for-net/assets/61542202/e21c863a-221a-488a-88f0-ec74cf4d3374)


So we are not able to help you with it. Therefore, we are closing this issue for now. If you need more assistance, please [open an Azure support request](https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request). We apologize for any inconvenience this may cause you.

We value your feedback and we want to make sure that your problem is solved. If you think that we have misunderstood your issue or closed it incorrectly, please feel free to comment on this thread and reopen the issue. We will be happy to assist you further. Thank you for your understanding and cooperation.

**Closed by dvbb** 2024-03-15 07:11 UTC
Labels: App Services, Mgmt, customer-reported, question, needs-team-attention
