### ISSUE TITLE
[QUESTION] Azure.Messaging.EventHubs.Producer.EventDataBatch.TryAdd Throws InvalidOperationException when EventDataBatch is in use

### ISSUE THREAD

**Issue by ericbeaudry** [Azure/azure-sdk-for-net#18157] opened 2021-01-23 19:31 UTC
**Describe the bug**
Calling TryAdd on Azure.Messaging.EventHubs.Producer.EventDataBatch throws InvalidOperationException when EventDataBatch is in use.

**Expected behavior**
Not throwing an InvalidOperationException. As the name suggests the caller is "trying" and expect true/false from the call. It is not Invalid to call TryAdd at any point. If the batch is locked, TryAdd should simply return false which would allow the caller to retry without the overhead of an Exception

**Actual behavior (include Exception or Stack Trace)**
System.InvalidOperationException: The event batch is currently being used in communication with the Event Hubs service; events may not be added until the active operation is complete.
   at Azure.Messaging.EventHubs.Producer.EventDataBatch.AssertNotLocked()
   at Azure.Messaging.EventHubs.Producer.EventDataBatch.TryAdd(EventData eventData)

**Environment:**
 - Name and version of the Library package used: Azure.Messaging.EventHubs 5.2.0
 - Hosting platform or OS and .NET runtime version : dotnet core 3.1.405 
 - IDE and version : Visual Studio Version 16.8.3

**Comment by jsquire** [comment] 2021-01-24 16:46
Hi @ericbeaudry.  Thank you for your feedback.  This behavior is by design.  When `TryAdd` returns `false`, that indicates that either the batch is full or the requested event is too large to fit.  This state is deterministic and idempotent; if you continue to try the result will be the same.   

We chose to surface an event when you attempt to manipulate a batch at the same time you've chosen to publish that batch for two reasons.   It allows us to maintain clear and consistent meaning around the return value for `TryAdd` - you always know it's a size issue.  The error also indicates (via its message) that this is a transient condition;  retrying the addition once publishing has completed will result in different behavior.

This isn't something that we're open to changing.  As part of our public contract, changes to this behavior would potentially break existing applications.

**Comment by ericbeaudry** [comment] 2021-01-24 17:02
Hi @jsquire Thanks for the clarification. Since this is by design and actually hard to reproduce, may I suggest the exception be added to the documentation of TryAdd so that other users don't learn the behavior only once they are running under heavy load? Something like what we can see here:
![image](https://user-images.githubusercontent.com/30331106/105637487-d126e280-5e3b-11eb-80f8-cdac4458bd78.png)

**Comment by jsquire** [comment] 2021-01-25 15:40
That's a good call-out and, honestly, something we should have thought to include.   I've added doc comments covering this in #18165.

**Comment by jsquire** [comment] 2021-01-26 16:07
Closing this out as the associated PR has merged; documentation updates will be included in our next release.

**Closed by jsquire** 2021-01-26 16:07 UTC
Labels: Client, Event Hubs, customer-reported, needs-team-attention, question
