### ISSUE TITLE
[BUG] Missing method in Azure.Core.Amqp after upgrading to Microsoft.Azure.WebJobs.Extensions.ServiceBus 5.0.0-beta.3

### ISSUE THREAD

**Issue by mauve** [Azure/azure-sdk-for-net#21512] opened 2021-06-02 13:01 UTC
**Describe the bug**

`Method not found: 'Boolean Azure.Core.Amqp.AmqpMessageBody.TryGetValue(System.Object ByRef)'.`

**Expected behavior**

I expected the method to be found :)

**Actual behavior (include Exception or Stack Trace)**

```
2021-06-02T12:53:54.320 [Information] Trigger Details: MessageId: 63a529b7dbb4485c97f388bbdbd2828c, SequenceNumber: 770, DeliveryCount: 10, EnqueuedTimeUtc: 2021-06-02T12:53:52.0600000+00:00, LockedUntilUtc: 2021-06-02T12:58:54.3100000+00:00, SessionId: (null)
2021-06-02T12:53:54.321 [Error] Executed 'Device2CloudMessageHandler' (Failed, Id=fb0f43ce-9725-4990-81d6-ac7ab1895e00, Duration=1ms)Method not found: 'Boolean Azure.Core.Amqp.AmqpMessageBody.TryGetValue(System.Object ByRef)'.ingAsync(TMessage eventData) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Triggers\TriggerArgumentBinding\SimpleTriggerArgumentBinding.cs:line 72at Microsoft.Azure.WebJobs.Host.SimpleTriggerArgumentBinding`2.BindAsync(TTriggerValue value, ValueBindingContext context) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Triggers\TriggerArgumentBinding\SimpleTriggerArgumentBinding.cs:line 88at Microsoft.Azure.WebJobs.Host.Triggers.TriggeredFunctionBinding`1.BindCoreAsync(ValueBindingContext context, Object value, IDictionary`2 parameters) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Triggers\TriggeredFunctionBinding.cs:line 56--- End of inner exception stack trace ---at Microsoft.Azure.WebJobs.Host.Executors.DelayedException.Throw() in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\DelayedException.cs:line 27lass1_0`2.<<AsTyped>b__0>d.MoveNext() in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\IConverterManager.cs:line 52--- End of stack trace from previous location where exception was thrown ---at Microsoft.Azure.WebJobs.Host.SimpleTriggerArgumentBinding`2.ConvertToStringAsync(TMessage eventData) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Triggers\TriggerArgumentBinding\SimpleTriggerArgumentBinding.cs:line 72at Microsoft.Azure.WebJobs.Host.SimpleTriggerArgumentBinding`2.BindAsync(TTriggerValue value, ValueBindingContext context) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Triggers\TriggerArgumentBinding\SimpleTriggerArgumentBinding.cs:line 88at Microsoft.Azure.WebJobs.Host.Triggers.TriggeredFunctionBinding`1.BindCoreAsync(ValueBindingContext context, Object value, IDictionary`2 parameters) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Triggers\TriggeredFunctionBinding.cs:line 56--- End of inner exception stack trace ---at Microsoft.Azure.WebJobs.Host.Executors.DelayedException.Throw() in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\DelayedException.cs:line 27at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ParameterHelper.PrepareParametersAsync() in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 888at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithWatchersAsync(IFunctionInstanceEx instance, ParameterHelper parameterHelper, ILogger logger, CancellationTokenSource functionCancellationTokenSource) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 466at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(IFunctionInstanceEx instance, FunctionStartedMessage message, FunctionInstanceLogEntry instanceLogEntry, ParameterHelper parameterHelper, ILogger logger, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 279--- End of inner exception stack trace ---at Microsoft.Azure.WebJobs.ServiceBus.MessageProcessor.CompleteProcessingMessageAsync(ServiceBusMessageActions messageActions, ServiceBusReceivedMessage message, FunctionResult result, CancellationToken cancellationToken)at Microsoft.Azure.WebJobs.ServiceBus.Listeners.ServiceBusListener.ProcessMessageAsync(ProcessMessageEventArgs args)at Azure.Messaging.ServiceBus.ReceiverManager.OnMessageHandler(ServiceBusReceivedMessage message, CancellationToken processorCancellationToken)at Azure.Messaging.ServiceBus.ReceiverManager.ProcessOneMessage(ServiceBusReceivedMessage message, CancellationToken cancellationToken)ceEx instance, FunctionStartedMessage message, FunctionInstanceLogEntry instanceLogEntry, ParameterHelper parameterHelper, ILogger logger, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 279--- End of inner exception stack trace ---at Microsoft.Azure.WebJobs.ServiceBus.MessageProcessor.CompleteProcessingMessageAsync(ServiceBusMessageActions messageActions, ServiceBusReceivedMessage message, FunctionResult result, CancellationToken cancellationToken)at Microsoft.Azure.WebJobs.ServiceBus.Listeners.ServiceBusListener.ProcessMessageAsync(ProcessMessageEventArgs args)at Azure.Messaging.ServiceBus.ReceiverManager.OnMessageHandler(ServiceBusReceivedMessage message, CancellationToken processorCancellationToken)at Azure.Messaging.ServiceBus.ReceiverManager.ProcessOneMessage(ServiceBusReceivedMessage message, CancellationToken cancellationToken)
2021-06-02T12:53:54.396 [Error] Message processing error (Action=ProcessMessageCallback, EntityPath=devicetocloud, Endpoint=REDACTED-servicebus.servicebus.windows.net)Method not found: 'Boolean Azure.Core.Amqp.AmqpMessageBody.TryGetValue(System.Object ByRef)'.--- End of inner exception stack trace ---at Microsoft.Azure.WebJobs.ServiceBus.MessageProcessor.CompleteProcessingMessageAsync(ServiceBusMessageActions messageActions, ServiceBusReceivedMessage message, FunctionResult result, CancellationToken cancellationToken)at Microsoft.Azure.WebJobs.ServiceBus.Listeners.ServiceBusListener.ProcessMessageAsync(ProcessMessageEventArgs args)at Azure.Messaging.ServiceBus.ReceiverManager.OnMessageHandler(ServiceBusReceivedMessage message, CancellationToken processorCancellationToken)at Azure.Messaging.ServiceBus.ReceiverManager.ProcessOneMessage(ServiceBusReceivedMessage message, CancellationToken cancellationToken)
2021-06-02T12:53:54.396 [Error] Message processing error (Action=ProcessMessageCallback, EntityPath=devicetocloud, Endpoint=REDACTED-servicebus.servicebus.windows.net)Method not found: 'Boolean Azure.Core.Amqp.AmqpMessageBody.TryGetValue(System.Object ByRef)'.
```

**To Reproduce**

```csharp
    public async Task Run(
      [ServiceBusTrigger("%DEVICE2CLOUD_QUEUE_NAME%", Connection = "DEVICE2CLOUD")]
      ServiceBusReceivedMessage message,
      ILogger log,
      [DurableClient]
      IDurableClient durableClient,
      CancellationToken cancellationToken)
    {
      ...
    }
```

**Environment:**
 - Microsoft.Azure.WebJobs.Extensions.ServiceBus 5.0.0-beta.3
 - Azure function dotnet core 3.1

all dependencies:

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <AzureFunctionsVersion>V3</AzureFunctionsVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Azure.Identity" Version="1.4.0" />
    <PackageReference Include="Azure.Messaging.ServiceBus" Version="7.2.0-beta.3" />
    <PackageReference Include="Azure.Security.KeyVault.Secrets" Version="4.1.1" />
    <PackageReference Include="Azure.Storage.Blobs" Version="12.9.0-beta.4" />
    <PackageReference Include="Microsoft.Azure.Cosmos" Version="3.19.0" />
    <PackageReference Include="Microsoft.Azure.Devices" Version="1.34.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Extensions" Version="1.1.0" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.DurableTask" Version="2.4.3" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.Storage.Blobs" Version="5.0.0-beta.3" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.ServiceBus" Version="5.0.0-beta.3" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions" Version="4.0.1" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Logging.ApplicationInsights" Version="3.0.27" />
    <PackageReference Include="Microsoft.Azure.WebJobs" Version="3.0.27" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="3.1.11" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="3.1.11" />
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="3.0.12" />
    <PackageReference Include="Microsoft.ApplicationInsights" Version="2.17.0" />
  </ItemGroup>
  <ItemGroup>
    <None Update="host.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="local.settings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>Never</CopyToPublishDirectory>
    </None>
  </ItemGroup>
</Project>
```

**Comment by jsquire** [comment] 2021-06-02 13:28
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by JoshLove-msft** [comment] 2021-06-02 23:52
Hi @mauve, 
Is this occurring locally? If so, can you try cleaning your solution? Based on your dependencies, it should be pulling in the correct version of Azure.Core.Amqp.

**Comment by mauve** [comment] 2021-06-03 07:10
@JoshLove-msft it is failing when deploying to Azure Functions (v3, dotnet core 3.1)

**Comment by JoshLove-msft** [comment] 2021-06-03 23:16
I'm having trouble reproducing this. I used the exact same csproj and function signature, deployed to a Functions app, and did not see this error.

Can you clarify at what point you are seeing the error? Is this while the app is starting up?

**Comment by JoshLove-msft** [comment] 2021-06-03 23:37
It seems like the WebJobs SDK is attempting to Ioad our string converter dynamically and failing.

**Comment by JoshLove-msft** [comment] 2021-06-03 23:39
@mauve are any messages processed by your function or does this happen every time?

**Comment by mauve** [comment] 2021-06-04 06:32
@JoshLove-msft I do not manage to process anything with this setup. The first message fails.


Unsure if it helps but here is my `host.json` file:

**host.json**
```json
{
    "version": "2.0",
    "logging": {
        "applicationInsights": {
            "samplingSettings": {
                "isEnabled": false,
                "excludedTypes": "Request;Exception"
            },
            "enableLiveMetrics": true,
            "enableDependencyTracking": true,
            "httpAutoCollectionOptions": {
                "enableHttpTriggerExtendedInfoCollection": true,
                "enableW3CDistributedTracing": true
            }
        },
        "fileLoggingMode": "always",
        "logLevel": {
            "default": "Information",
            "Host.Results": "Error",
            "Function": "Trace",
            "Host.Aggregator": "Trace",
            "Host.Triggers.DurableTask": "Information"
        },
        "functionTimeout": "00:04:30"
    },
    "extensions": {
        "durableTask": {
            "tracing": {
                "distributedTracingEnabled": true,
                "distributedTracingProtocol": "W3CTraceContext"
            }
        }
    }
}
```

**Comment by mauve** [comment] 2021-06-04 06:51
Is there anything I can supply to make debugging easier? I tried attaching the full `project.assets.json` but GitHub says no  :)

**Comment by JoshLove-msft** [comment] 2021-06-04 07:22
One thing that would be interesting to see is if it repros after deploying to a new function app.

**Comment by mauve** [comment] 2021-06-04 10:07
I will delete my app and redeploy to see what happens

**Comment by JoshLove-msft** [comment] 2021-06-04 17:50
Before deleting the app, could you provide this information:
- does the issue reproduce locally?
- app name
- memory dump when error occurs (Using Collect Memory Dump from Diagnostic Tools in the Portal - which is available if your function app is an App Service function)
- body of the function

**Comment by mauve** [comment] 2021-06-06 10:39
Wdym by the "body of the function"?

I will generate that dump on Monday.

**Comment by JoshLove-msft** [comment] 2021-06-06 21:52
The contents of the function. In the snippet, it has the method signature of the function, but there may be some code in the function that is causing the dependency issue.

**Comment by JoshLove-msft** [comment] 2021-06-11 05:39
Hi @mauve,
Have you had a chance to test this out again?

**Comment by mauve** [comment] 2021-06-14 07:20
No sorry, haven't had the time. Also the body of the function is a bit larger and contains most of our real code :) any chance I can share it via a support ticket instead?

**Comment by JoshLove-msft** [comment] 2021-06-14 17:57
Sure, you can submit it via support ticket.

**Comment by mauve** [comment] 2021-06-17 08:57
I just redeployed this version of the code and now I am getting a different error:

```
2021-06-17T08:53:06.349 [Error] The listener for function 'Device2CloudMessageHandler' was unable to start.Microsoft.Azure.WebJobs.Host.Listeners.FunctionListenerException 👍 

The listener for function 'Device2CloudMessageHandler' was unable to start.
---> System.TypeLoadException 👍 Could not load type 'Azure.AzureSasCredential' from assembly 'Azure.Core, Version=1.3.0.0, Culture=neutral, PublicKeyToken=92742159e12e44c8'.



at Azure.Messaging.ServiceBus.ServiceBusConnection.CreateWithCredential[TCredential](String fullyQualifiedNamespace,TCredential credential,ServiceBusClientOptions options)at Azure.Messaging.ServiceBus.ServiceBusClient..ctor(String fullyQualifiedNamespace,Object credential,ServiceBusClientOptions options)at Microsoft.Azure.WebJobs.ServiceBus.MessagingProvider.<>c__DisplayClass9_0.<CreateClient>b__0(String _)at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key,Func`2 valueFactory)at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication,Boolean useDefaultConstructor)at System.Lazy`1.CreateValue()at Microsoft.Azure.WebJobs.ServiceBus.Listeners.ServiceBusListener.<>c__DisplayClass19_0.<.ctor>b__2()at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()at System.Lazy`1.CreateValue()at async Microsoft.Azure.WebJobs.ServiceBus.Listeners.ServiceBusListener.StartAsync(CancellationToken cancellationToken)at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()at async Microsoft.Azure.WebJobs.Host.Listeners.FunctionListener.StartAsync(??) at C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Listeners\FunctionListener.cs : 68End of inner exception
```

**Comment by mauve** [comment] 2021-06-17 10:12
I cannot do a memory-dump because I cannot enable alwaysOn, I am running on the elasticpremium P3 plan but the documentation around serverFarms and plans is so horrendous that I have already spent the larger part of today on this and still don't know what to do.

**Comment by JoshLove-msft** [comment] 2021-10-06 05:25
@mauve, since we haven't been able to repro this issue, I will close this out for now. Feel free to reopen if you wish to discuss further.

**Closed by JoshLove-msft** 2021-10-06 05:25 UTC
Labels: Service Bus, Client, customer-reported, question, Functions, needs-team-attention
