### ISSUE TITLE
Update the LRO doc

### ISSUE THREAD

**Issue by ArthurMa1978** [Azure/azure-sdk-for-net#27476] opened 2022-03-10 16:35 UTC
https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/Azure.Core/samples/LongRunningOperations.md

**Comment by annelo-msft** [comment] 2022-03-10 18:50
Duplicate of https://github.com/Azure/azure-sdk-for-net/issues/25715

**Closed** 2024-03-11 18:04 UTC
Labels: Mgmt, Docs
