### ISSUE TITLE
pin name can't have a '

### ISSUE THREAD

**Issue by DavidThielen** [Azure/azure-sdk-for-net#40862] opened 2023-12-20 18:57 UTC
### Library name and version

Azure.Maps.Rendering 1.0.0-beta.2

### Describe the bug

If the name passed to `PushpinPosition` has a ' in it, such as "Dave's Home", you get the following:

`{"pins":["Invalid format for location value ''Dave's home'-105.13008 39.98274'. Expected a floating-point longitude between -180 and 180."]}`

### Expected behavior

It can handle names with a '

### Actual behavior

It throws an exception

### Reproduction Steps

[example here](https://stackoverflow.com/questions/77693764/azure-map-rendering-pin-name-cant-have-a)

### Environment

Windows 11 on a desktop. App is Blazor server .NET 8

**Comment by DavidThielen** [comment] 2023-12-20 18:57
**Please** let me know how to escape a ' and if there's any other characters it chokes over.

**Comment by DavidThielen** [comment] 2023-12-20 21:34
Also, if this SDK is open source, please point me to it. I'll fix the 2 bugs I found - should only take 1/2 hour or so.

thanks - dave

**Comment by dubiety** [comment] 2024-01-08 14:05
Hi @DavidThielen,
We're looking into this issue and will get back to you soon. Thank you very much for reporting this issue!

**Comment by jecmenicanikola** [comment] 2024-03-15 12:55
I could reproduce this as described. After investigation, I found that the problem is on the server side. A direct call to the REST API yields the same result.

```
curl --location 'https://atlas.microsoft.com/map/static/png?api-version=2022-08-01&bbox=13.228%2C52.4559%2C13.5794%2C52.629&language=&pins=default%7CcoFF00FF%7Csc0.8%7Clc008000%7Cls10%7C%7C%27Dave%27s%20home%2712.56%2022.56' \
--header 'Accept: "application/json, image/jpeg, image/png, image/pbf, application/vnd.mapbox-vector-tile"' \
--header 'x-ms-client-request-id: REQUEST-ID' \
--header 'x-ms-return-client-request-id: true' \
--header 'subscription-key: KEY'
```

returns:
```
400 Bad Request with message "{
    "pins": [
        "Invalid format for location value ''Dave's home'12.56 22.56'. Expected a floating-point longitude between -180 and 180."
    ]
}"
```

It's possible to work around this by replacing `'` with `\u2019`.

**Comment by jecmenicanikola** [comment] 2024-04-02 11:32
This was fixed on the server side.

**Comment by dubiety** [comment] 2024-05-15 00:11
It's fixed and now it's working. @DavidThielen, please let us know if you still encounter any problem. I'll close this issue now. Thank you again for reporting this issue!

**Closed by dubiety** 2024-05-15 00:11 UTC
Labels: Service Attention, Client, customer-reported, question, needs-team-attention, Maps
