### ISSUE TITLE
[BUG]Azure.Analytics.Synapse.Spark CreateSparkBatchJob fails with ArgumentNullException

### ISSUE THREAD

**Issue by abmo-x** [Azure/azure-sdk-for-net#16843] opened 2020-11-10 22:18 UTC
**Describe the bug**
SparkBatchClient CreateSparkBatchJob throws an exception when parsing the response. Job gets submitted fine and I can see it on the UI. Looks like the client fails parsing fields which may not be required.

**Expected behavior**
Client should not fail to deserialize a response sent by the API on success

**Actual behavior (include Exception or Stack Trace)**
```
System.ArgumentNullException: Value cannot be null. (Parameter 'input')
    at System.DateTimeOffset.Parse(String input, IFormatProvider formatProvider, DateTimeStyles styles)
   at Azure.Core.TypeFormatters.ParseDateTimeOffset(String value, String format)
   at Azure.Core.JsonElementExtensions.GetDateTimeOffset(JsonElement& element, String format)
   at Azure.Analytics.Synapse.Spark.Models.SparkBatchJobState.DeserializeSparkBatchJobState(JsonElement element)
   at Azure.Analytics.Synapse.Spark.Models.SparkBatchJob.DeserializeSparkBatchJob(JsonElement element)
   at Azure.Analytics.Synapse.Spark.SparkBatchRestClient.CreateSparkBatchJobAsync(SparkBatchJobOptions sparkBatchJobOptions,
```

Reponse:

`{
    "RootElement": {
        "livyInfo": {
            "notStartedAt": null,
            "startingAt": null,
            "runningAt": null,
            "deadAt": null,
            "successAt": null,
            "killedAt": null,
            "recoveringAt": null,
            "currentState": "not_started",
            "jobCreationRequest": {
                "name": "REDACTED",
                "file": "REDACTED",
                "className": "REDACTED",
                "args": [
                    "test"
                ],
                "conf": {},
                "driverMemory": "28g",
                "driverCores": 4,
                "executorMemory": "28g",
                "executorCores": 4,
                "numExecutors": 2
            }
        },
        "name": "testSparkJobCreate",
        "workspaceName": "REDACTED",
        "computeName": "REDACTED",
        "sparkPoolName": "REDACTED",
        "submitterId": "REDACTED",
        "artifactId": "Livy",
        "jobType": "SparkBatch",
        "result": "Uncertain",
        "schedulerInfo": {
            "submittedAt": "2020-11-10T22:10:55.9785479+00:00",
            "scheduledAt": null,
            "endedAt": null,
            "cancellationRequestedAt": null,
            "currentState": "Queued"
        },
        "pluginInfo": {
            "preparationStartedAt": null,
            "resourceAcquisitionStartedAt": null,
            "submissionStartedAt": null,
            "monitoringStartedAt": null,
            "cleanupStartedAt": null,
            "currentState": "Preparation"
        },
        "tags": {},
        "id": 3,
        "appId": null,
        "appInfo": null,
        "state": "not_started",
        "log": null
    }
}`

**To Reproduce**
Followed code snippet here: https://github.com/Azure/azure-sdk-for-net/tree/Azure.Analytics.Synapse.Spark_1.0.0-preview.2/sdk/synapse/Azure.Analytics.Synapse.Spark#create-spark-batch-job

**Environment:**
 -Azure.Analytics.Synapse.Spark" Version="1.0.0-preview.2"

**Comment by idear1203** [comment] 2020-11-11 23:54
Thanks! We will fix the issue ASAP

**Comment by idear1203** [comment] 2020-11-23 10:17
The issue is fixed by https://github.com/Azure/azure-sdk-for-net/pull/17146

**Closed by idear1203** 2020-11-23 10:17 UTC
Labels: Client, Service Attention, Synapse, needs-team-triage
