### ISSUE TITLE
KeyVault configuration extension failure

### ISSUE THREAD

**Issue by Peperud** [Azure/azure-sdk-for-net#9155] opened 2019-12-16 17:35 UTC
Application uses ***AzureKeyVaultConfigurationExtensions*** and runs in a containers with user assigned identity. The identity is granted access to the key vault. 
On startup, about ***half*** the time the application fails when creating the configuration. 

From the container logs:
```
Unhandled exception. Microsoft.Azure.Services.AppAuthentication.AzureServiceTokenProviderException: Parameters: Connection String: [No connection string specified], Resource: https://vault.azure.net, Authority: https://login.windows.net/6a7b4a78-8f3a-495c-bfc8-db50c01f115b. Exception Message: Tried the following 3 methods to get an access token, but none of them worked.
Parameters: Connection String: [No connection string specified], Resource: https://vault.azure.net, Authority: https://login.windows.net/6a7b4a78-8f3a-495c-bfc8-db50c01f115b. Exception Message: Tried to get token using Managed Service Identity. Unable to connect to the Managed Service Identity (MSI) endpoint. Please check that you are running on an Azure resource that has MSI setup.
Parameters: Connection String: [No connection string specified], Resource: https://vault.azure.net, Authority: https://login.windows.net/6a7b4a78-8f3a-495c-bfc8-db50c01f115b. Exception Message: Tried to get token using Visual Studio. Access token could not be acquired. Environment variable LOCALAPPDATA not set.
Parameters: Connection String: [No connection string specified], Resource: https://vault.azure.net, Authority: https://login.windows.net/6a7b4a78-8f3a-495c-bfc8-db50c01f115b. Exception Message: Tried to get token using Azure CLI. Access token could not be acquired. /bin/bash: az: No such file or directory


   at Microsoft.Azure.Services.AppAuthentication.AzureServiceTokenProvider.GetAuthResultAsyncImpl(String resource, String authority, CancellationToken cancellationToken)
   at Microsoft.Azure.Services.AppAuthentication.AzureServiceTokenProvider.<get_KeyVaultTokenCallback>b__8_0(String authority, String resource, String scope)
   at Microsoft.Azure.KeyVault.KeyVaultCredential.PostAuthenticate(HttpResponseMessage response)
   at Microsoft.Azure.KeyVault.KeyVaultCredential.ProcessHttpRequestAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Azure.KeyVault.KeyVaultClient.GetSecretsWithHttpMessagesAsync(String vaultBaseUrl, Nullable`1 maxresults, Dictionary`2 customHeaders, CancellationToken cancellationToken)
   at Microsoft.Azure.KeyVault.KeyVaultClientExtensions.GetSecretsAsync(IKeyVaultClient operations, String vaultBaseUrl, Nullable`1 maxresults, CancellationToken cancellationToken)
   at Microsoft.Extensions.Configuration.AzureKeyVault.AzureKeyVaultConfigurationProvider.LoadAsync()
   at Microsoft.Extensions.Configuration.AzureKeyVault.AzureKeyVaultConfigurationProvider.Load()
   at Microsoft.Extensions.Configuration.ConfigurationRoot..ctor(IList`1 providers)
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
   at STCloudAgent.Program.Configure() in /src/STCloudAgent/Program.cs:line 46
   at STCloudAgent.Program.Main() in /src/STCloudAgent/Program.cs:line 55
   at STCloudAgent.Program.<Main>()
```

***Code Snippet***
```csharp
        static void Configure()
        {
            IConfigurationBuilder builder = new ConfigurationBuilder()
                .SetBasePath(Directory.GetCurrentDirectory())
                .AddJsonFile("appsettings.json", optional: false, reloadOnChange: true)
                .AddJsonFile($"appsettings.{Environment.GetEnvironmentVariable("ASPNETCORE_ENVIRONMENT") ?? "Production"}.json", optional: true)
                .AddEnvironmentVariables();

            var tmpConfig = builder.Build();
            if (tmpConfig.GetValue<bool>("UseAzureKeyVault"))
            {
                var azureServiceTokenProvider = new AzureServiceTokenProvider();
                var keyVaultClient = new KeyVaultClient(
                    new KeyVaultClient.AuthenticationCallback(
                        azureServiceTokenProvider.KeyVaultTokenCallback));

                // identity used by the container must have list & get permissions on the Key Vault
                builder.AddAzureKeyVault(
                    new AzureKeyVaultConfigurationOptions
                    {
                        Vault = $"https://{tmpConfig["KeyVaultName"]}.vault.azure.net/",
                        Client = keyVaultClient,
                        ReloadInterval = TimeSpan.FromMinutes(20),
                        Manager = new DefaultKeyVaultSecretManager()
                    });
            }

            Configuration = builder.Build();
        }
```

**Expected behavior**
Building the configuration should work reliably

**Comment by Peperud** [comment] 2019-12-17 02:09
It doesn't seem to make a difference if I use a connection string [like shown here](https://docs.microsoft.com/en-us/azure/key-vault/service-to-service-authentication#connection-string-support) either.
```csharp
var azureServiceTokenProvider = new AzureServiceTokenProvider($"RunAs=App;AppId={tmpConfig["ManagedIdentityClientId"]}")
```

**Comment by heaths** [comment] 2019-12-17 19:54
Does this same behavior reproduce if you use the new Azure.Security.KeyVault.* libraries? These are a complete rewrite to be consistent across languages, faster with less memory allocation, and easier to configure. Is it possible to switch to those, which are under active development?

**Comment by Peperud** [comment] 2019-12-17 22:12
I suppose I can give it a try (though "_under active development_" is not what I'm looking for). On first glance I didn't see an accompanying configuration extension. Is this correct?

**Comment by heaths** [comment] 2019-12-17 23:09
It's in the same package. See https://azuresdkdocs.blob.core.windows.net/$web/dotnet/Azure.Security.KeyVault.Certificates/4.0.0-preview.7/api/Microsoft.Extensions.Azure/Microsoft.Extensions.Azure.CertificateClientBuilderExtensions.html for our latest preview documentation. We are close to GA'ing Certificates. Keys and Secrets have already GA'd and are up on https://docs.microsoft.com/en-us/dotnet/api/overview/azure/keyvault/client?view=azure-dotnet (Azure.Security.KeyVault.*).

**Comment by Peperud** [comment] 2019-12-17 23:40
@heaths Are we talking about the same thing? What I meant was - is there an equivalent for this 
```csharp
                builder.AddAzureKeyVault(
                    new AzureKeyVaultConfigurationOptions
                    {
                        Vault = $"https://{tmpConfig["KeyVaultName"]}.vault.azure.net/",
                        Client = keyVaultClient,
                        ReloadInterval = TimeSpan.FromMinutes(20),
                        Manager = new DefaultKeyVaultSecretManager()
                    });
``` 
that uses the new Azure.Security.KeyVault.* libraries?

**Comment by Peperud** [comment] 2019-12-18 01:50
It seems like a reliability issue. Tried with ```Azure.Security.KeyVault.Secrets.SecretClient``` like this
```csharp
                // 
                var keyVaultName = configuration[KEYVAULT_NAME];
                var vaultUri = new Uri($"https://{keyVaultName}.vault.azure.net/");

                var options = new SecretClientOptions();
                options.Retry.Mode = Azure.Core.RetryMode.Exponential;
                options.Retry.MaxRetries = 5;
                options.Retry.Delay = TimeSpan.FromSeconds(3);
                options.Retry.MaxDelay = TimeSpan.FromMinutes(2);

                var tokenCredentialOptions = new TokenCredentialOptions();
                tokenCredentialOptions.Retry.Mode = Azure.Core.RetryMode.Fixed;
                tokenCredentialOptions.Retry.MaxRetries = 5;
                tokenCredentialOptions.Retry.Delay = TimeSpan.FromSeconds(10);
                tokenCredentialOptions.Retry.MaxDelay = TimeSpan.FromMinutes(2);

                var client = new SecretClient(
                    vaultUri: vaultUri,
                    credential: new ManagedIdentityCredential(configuration["ManagedIdentityClientId"], tokenCredentialOptions),
                    options: options);
                try
                {
                    var secret = await client.GetSecretAsync(STCLOUDCONTROLLER_API_TOKEN);
                    if (secret == null)
                    {
                        Log.Warning($"Did not find secret {STCLOUDCONTROLLER_API_TOKEN}. Did you load it in {vaultUri.AbsoluteUri} ?");
                    }
                    else
                    {
                        lastKeyVaultAccess = DateTime.Now;
                        accessToken = secret.Value.Value;
                    }
                }
                catch (Exception arfe)
                {
                    Exception ex = arfe;
                    int i = 1;
                    while (ex != null)
                    {
                        Log.Error(ex, $"Failed to retrieve secret from Azure KeyVault. Level: {i++}");
                        ex = ex.InnerException;
                    }
                }

```
...and getting errors with it too. 
```
[00:56:42 ERR] Failed to retrieve secret from Azure KeyVault. Level: 1
Azure.Identity.AuthenticationFailedException: The authentication request failed due to an unhandled exception.  See inner exception for details.
 ---> Azure.RequestFailedException: Service request failed.
Status: 500 (Internal Server Error)

Content:
There are currently no websocket connections, please try again.


Headers:
X-Content-Type-Options: nosniff
Date: Wed, 18 Dec 2019 00:56:42 GMT
Content-Type: text/plain; charset=utf-8
Content-Length: 64

   at Azure.Identity.ManagedIdentityClient.AuthenticateAsync(MsiType msiType, String[] scopes, String clientId, CancellationToken cancellationToken)
   at Azure.Identity.ManagedIdentityCredential.GetTokenImplAsync(TokenRequestContext requestContext, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Azure.Identity.ExtendedAccessToken.GetTokenOrThrow()
   at Azure.Identity.ManagedIdentityCredential.GetTokenAsync(TokenRequestContext requestContext, CancellationToken cancellationToken)
   at Azure.Security.KeyVault.ChallengeBasedAuthenticationPolicy.AuthenticateRequestAsync(HttpMessage message, Boolean async)
   at Azure.Security.KeyVault.ChallengeBasedAuthenticationPolicy.ProcessCoreAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
   at Azure.Core.Pipeline.RetryPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
   at Azure.Core.Pipeline.RetryPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
   at Azure.Core.Pipeline.HttpPipelineSynchronousPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline)
   at Azure.Core.Pipeline.HttpPipelineSynchronousPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline)
   at Azure.Core.Pipeline.HttpPipeline.SendRequestAsync(Request request, CancellationToken cancellationToken)
   at Azure.Security.KeyVault.KeyVaultPipeline.SendRequestAsync(Request request, CancellationToken cancellationToken)
   at Azure.Security.KeyVault.KeyVaultPipeline.SendRequestAsync[TResult](RequestMethod method, Func`1 resultFactory, CancellationToken cancellationToken, String[] path)
   at Azure.Security.KeyVault.Secrets.SecretClient.GetSecretAsync(String name, String version, CancellationToken cancellationToken)
   at STCloudAgent.SecretsManager.GetSTCloudControllerAPITokenAsync() in /src/STCloudAgent/SecretsManager.cs:line 74
[00:56:42 ERR] Failed to retrieve secret from Azure KeyVault. Level: 2
Azure.RequestFailedException: Service request failed.
Status: 500 (Internal Server Error)

Content:
There are currently no websocket connections, please try again.


Headers:
X-Content-Type-Options: nosniff
Date: Wed, 18 Dec 2019 00:56:42 GMT
Content-Type: text/plain; charset=utf-8
Content-Length: 64

   at Azure.Identity.ManagedIdentityClient.AuthenticateAsync(MsiType msiType, String[] scopes, String clientId, CancellationToken cancellationToken)
   at Azure.Identity.ManagedIdentityCredential.GetTokenImplAsync(TokenRequestContext requestContext, CancellationToken cancellationToken)
[00:56:42 ERR] Assignment request failed.
System.ApplicationException: Failed to get STCloudControllerAPIToken
   at STCloudAgent.ControllerCommunicator.EnsureAccessTokenAsync() in /src/STCloudAgent/ControllerCommunicator.cs:line 126
   at STCloudAgent.ControllerCommunicator.GetAssignmentAsync() in /src/STCloudAgent/ControllerCommunicator.cs:line 59
``` 
It appears to be a service reliability or timing issue (or both).

In my case this is a worker that periodically polls for work (uses a token stored in the vault to call the work assigner app). 
In my limited testing, if the container is left running, it eventually succeeds in fetching the secret from the vault. How long it's going to take to latch on however seems to be unpredictable. I saw everything from right at container start to several minutes after it. I think the longest I saw was 10 minutes, though I didn't always wait and killed the containers early.

Once I get the secret, I can cache it for (substantial) period of time, but from container start until then, it's basically dead time (with unknown duration) for me.

**Comment by heaths** [comment] 2019-12-19 01:31
If you leave the defaults for the credential, do you still see this delay? @schaabs could you take a look at the Identity issue?

**Comment by Peperud** [comment] 2019-12-19 02:02
@heaths Yes, I was getting errors with ```DefaultAzureCredential``` too. Then tried ```ManagedIdentityCredential``` in an effort to potentially eliminate probing (in case that matters).

**Comment by Peperud** [comment] 2019-12-28 02:07
Very often getting this too. And it doesn't seem to ever recover.
```
Azure.Identity.CredentialUnavailableException: No managed identity endpoint found.
   at Azure.Identity.ExtendedAccessToken.GetTokenOrThrow()
   at Azure.Identity.ManagedIdentityCredential.GetTokenAsync(TokenRequestContext requestContext, CancellationToken cancellationToken)
   at Azure.Security.KeyVault.ChallengeBasedAuthenticationPolicy.AuthenticateRequestAsync(HttpMessage message, Boolean async)
   at Azure.Security.KeyVault.ChallengeBasedAuthenticationPolicy.ProcessCoreAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
   at Azure.Core.Pipeline.RetryPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
   at Azure.Core.Pipeline.RetryPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
   at Azure.Core.Pipeline.HttpPipelineSynchronousPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline)
   at Azure.Core.Pipeline.HttpPipelineSynchronousPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline)
   at Azure.Core.Pipeline.HttpPipeline.SendRequestAsync(Request request, CancellationToken cancellationToken)
   at Azure.Security.KeyVault.KeyVaultPipeline.SendRequestAsync(Request request, CancellationToken cancellationToken)
   at Azure.Security.KeyVault.KeyVaultPipeline.SendRequestAsync[TResult](RequestMethod method, Func`1 resultFactory, CancellationToken cancellationToken, String[] path)
   at Azure.Security.KeyVault.Secrets.SecretClient.GetSecretAsync(String name, String version, CancellationToken cancellationToken)
```

**Comment by schaabs** [comment] 2020-01-06 18:01
Hi @Perperud, sorry for the trouble you're having. Looks like your running into an error with the managed identity endpoint. Could you tell me more about what environment your code is running in? Is this an AppService, Function, Azure Kubernetes Pod, Azure Hosted VM, or some other azure host? Also, does this error only occur on startup, or have you also run into this issue after an initial successful startup?

**Comment by Peperud** [comment] 2020-01-07 18:50
Hi @schaabs, 
These are containers in Azure Container Instances. 
The errors occur on startup, yes. The [first type of issue ](https://github.com/Azure/azure-sdk-for-net/issues/9155#issuecomment-566830016) might go away after awhile, the [second one](https://github.com/Azure/azure-sdk-for-net/issues/9155#issuecomment-569376008) does not. To keep the cost down, I don't leave the containers running all the time, so this might not be 100% accurate.

**Comment by schaabs** [comment] 2020-02-07 18:16
@Peperud I think the root cause of your issues might be a delay in the managed identity being available after the Container instance is started. Adding @chlowell who would have more insight into this.

Also I've made an update in PR https://github.com/Azure/azure-sdk-for-net/pull/9025, which might help the situation. One of the changes here is to make the Managed Identity discovery to be instance based, so we don't statically cache whether the endpoint is available. So if you're creating new credential instances the second issue you mentioned above should go away after some time.

**Comment by chlowell** [comment] 2020-02-07 19:06
It's correct that a container instance can start before the managed identity is available to it. I think you could handle that outside your application code with a [liveness probe](https://docs.microsoft.com/en-us/azure/container-instances/container-instances-liveness-probe) sending requests to the managed identity endpoint. I've done something similar for Kubernetes with wget in an init container:
```yaml
initContainers:
- name: wait-for-imds  # exits successfully when the IMDS endpoint returns 200 when asked for a
  image: busybox:1.31  # token, guaranteeing IMDS is ready before the app container starts
  command: ['sh', '-c', 'wget "http://169.254.169.254/metadata/identity/oauth2/token?resource=https://vault.azure.net&api-version=2018-02-01" --header "Metadata: true" -S --spider -T 6']
```
But liveness probes execute repeatedly, so a simple probe would send needless requests. You could work around that with a more complex probe, e.g. first check existence of a file touched on success. A good solution via liveness probe may be uglier than retry logic in the application 😉

**Comment by heaths** [comment] 2020-02-07 19:21
In that case, wouldn't a readiness probe against the MSI endpoint be more appropriate?

**Comment by chlowell** [comment] 2020-02-07 19:28
Readiness probes also execute repeatedly. The difference is that when a readiness probe fails, the container receives no requests; when a liveness probe fails, the container restarts. I suggested the latter because restarting the container (process) clears static state.

**Comment by graphicsxp** [comment] 2020-06-22 10:12
> @heaths Are we talking about the same thing? What I meant was - is there an equivalent for this
> 
> ```cs
>                 builder.AddAzureKeyVault(
>                     new AzureKeyVaultConfigurationOptions
>                     {
>                         Vault = $"https://{tmpConfig["KeyVaultName"]}.vault.azure.net/",
>                         Client = keyVaultClient,
>                         ReloadInterval = TimeSpan.FromMinutes(20),
>                         Manager = new DefaultKeyVaultSecretManager()
>                     });
> ```
> 
> that uses the new Azure.Security.KeyVault.* libraries?

I am looking for an answer to this question. How do we pass the SecretCient to the configuration ?

**Comment by heaths** [comment] 2020-06-22 20:34
@graphicsxp, I believe you asked and received an answer in https://github.com/Azure/azure-sdk-for-net/issues/12913, yes?

**Comment by graphicsxp** [comment] 2020-06-22 20:36
@heaths ah yes you are right.

**Comment by jsquire** [comment] 2020-10-12 20:08
Closing this out, as it appears that outstanding questions have been answered.   Please feel free to reopen if you feel that further discussion is needed.

**Closed by jsquire** 2020-10-12 20:08 UTC
Labels: Azure.Identity, Client, Managed Identity, customer-reported, needs-team-attention
