### ISSUE TITLE
[BUG] Service Bus SubscriptionClient: Messages are no longer received when connection changes

### ISSUE THREAD

**Issue by SHuygh** [Azure/azure-sdk-for-net#6252] opened 2019-05-13 11:33 UTC
**Describe the bug**
We are using the service bus to receive messages in Xamarin.Android application to receive messages when updates occur. However, we have found an issue with that we no longer receive any messages after the connection has changed without dropping.

***Exception or Stack Trace***
N/A

**To Reproduce**
As it is very difficult to reproduce this issue in the field we have figured out a manner to reproduce this 100% of the time.

Reproducible scenario:
1) Use mobile device as hotspot
2) Connect other device to that wifi
3) Force mobile device to switch between network modes (4g -> 3g, 3g -> 2g, 2g -> 4g,...)
4) The other device will no longer receive messages

Seems same issue when switching between cell towers 

***Code Snippet***
Our implementation:

```
                _subscriptionClient = new SubscriptionClient(_settingsService.PrimaryOutboundEndpoint,
                                                             _settingsService.PrimaryOutboundTopic,
                                                             _settingsService.PrimaryOutboundSubscription,
                                                            TokenProvider.CreateSharedAccessSignatureTokenProvider(_settingsService.PrimaryOutboundSasToken),
                                                             receiveMode: ReceiveMode.PeekLock,
                                                             retryPolicy: _retryPolicy);

            _subscriptionClient.RegisterMessageHandler(
                async (message, cancellationToken1) =>
                {
                    if (_subscriptionClient != null && !_subscriptionClient.IsClosedOrClosing)
                    {
                        await MessageHandler(message, cancellationToken1, _subscriptionClient);
                    }
                },
                new MessageHandlerOptions(LogMessageHandlerException) { AutoComplete = true, MaxConcurrentCalls = MAX_CONCURRENT_CALLS });
```

**Expected behavior**
Subscription client reconnects when there is an issue with the connection

**Setup (please complete the following information):**
- OS platform and version: Android 8.0.0
- .NET Version: Xamarin
- NuGet package version or commit ID: 3.4.0

**Additional context**
Currently we implemented a work around which is far from optimal as the connection will be reset more than needed. The connection is reset every time we do not receive messages within the ReceiveTimeOut. Below the adjustments as they may provide further insight.
Code Changes are specified between
**//Adjusted Part
...
//End Adjusted part**

**_Microsoft.Azure.ServiceBus.Core.MessageReceiver_**  

```
protected virtual async Task<IList<Message>> OnReceiveAsync(int maxMessageCount, TimeSpan serverWaitTime)
        {
            ReceivingAmqpLink receiveLink = null;

            if (this.isSessionReceiver)
            {
                this.ThrowIfSessionLockLost();
            }

            try
            {
                var timeoutHelper = new TimeoutHelper(serverWaitTime, true);
                if(!this.ReceiveLinkManager.TryGetOpenedObject(out receiveLink))
                {
                    MessagingEventSource.Log.CreatingNewLink(this.ClientId, this.isSessionReceiver, this.SessionIdInternal, false, this.LinkException);
                    receiveLink = await this.ReceiveLinkManager.GetOrCreateAsync(timeoutHelper.RemainingTime()).ConfigureAwait(false);
                }

                IList<Message> brokeredMessages = null;
                this.ThrowIfClosed();

                IEnumerable<AmqpMessage> amqpMessages = null;
                var hasMessages = await Task.Factory.FromAsync(
                    (c, s) => receiveLink.BeginReceiveRemoteMessages(maxMessageCount, DefaultBatchFlushInterval, timeoutHelper.RemainingTime(), c, s),
                    a => receiveLink.EndReceiveMessages(a, out amqpMessages),
                    this).ConfigureAwait(false);
                Exception exception;
                if ((exception = receiveLink.GetInnerException()) != null)
                {
                    throw exception;
                }

                if (hasMessages && amqpMessages != null)
                {
                    foreach (var amqpMessage in amqpMessages)
                    {
                        if (this.ReceiveMode == ReceiveMode.ReceiveAndDelete)
                        {
                            receiveLink.DisposeDelivery(amqpMessage, true, AmqpConstants.AcceptedOutcome);
                        }

                        var message = AmqpMessageConverter.AmqpMessageToSBMessage(amqpMessage);
                        if (brokeredMessages == null)
                        {
                            brokeredMessages = new List<Message>();
                        }

                        brokeredMessages.Add(message);
                    }
                }
//Adjusted Part
//Session is closed to ensure that a new AmqpLink is created
                else
                {
                    await receiveLink.Session.CloseAsync(timeoutHelper.RemainingTime());
                }
//End Adjusted part

                return brokeredMessages;
            }
            catch (Exception exception)
            {
                throw AmqpExceptionHelper.GetClientException(exception, receiveLink?.GetTrackingId(), null, receiveLink?.Session.IsClosing() ?? false);
            }
        }
```

**_Microsoft.Azure.ServiceBus.ServiceBusConnection_**  

```
//Adjusted Part
        public void RecreateConnectionManager()
        {
            this.ConnectionManager = new FaultTolerantAmqpObject<AmqpConnection>(this.CreateConnectionAsync, CloseConnection);
        }
//End Adjusted part
```

**_Microsoft.Azure.ServiceBus.Amqp.AmqpLinkCreator_**  

  ```
      public async Task<Tuple<AmqpObject, DateTime>> CreateAndOpenAmqpLinkAsync()
        {
            var timeoutHelper = new TimeoutHelper(this.serviceBusConnection.OperationTimeout);

            MessagingEventSource.Log.AmqpGetOrCreateConnectionStart();
//Adjusted Part
            serviceBusConnection.RecreateConnectionManager();
//End Adjusted part
            var amqpConnection = await this.serviceBusConnection.ConnectionManager.GetOrCreateAsync(timeoutHelper.RemainingTime()).ConfigureAwait(false);
            MessagingEventSource.Log.AmqpGetOrCreateConnectionStop(this.entityPath, amqpConnection.ToString(), amqpConnection.State.ToString());

            // Authenticate over CBS
            var cbsLink = amqpConnection.Extensions.Find<AmqpCbsLink>();
            DateTime cbsTokenExpiresAtUtc = DateTime.MaxValue;

            foreach (var resource in this.audience)
            {
                MessagingEventSource.Log.AmqpSendAuthenticationTokenStart(this.endpointAddress, resource, resource, this.requiredClaims);
                cbsTokenExpiresAtUtc = TimeoutHelper.Min(
                    cbsTokenExpiresAtUtc, 
                    await cbsLink.SendTokenAsync(this.cbsTokenProvider, this.endpointAddress, resource, resource, this.requiredClaims, timeoutHelper.RemainingTime()).ConfigureAwait(false));
                MessagingEventSource.Log.AmqpSendAuthenticationTokenStop(); 
            }

            AmqpSession session = null;
            try
            {
                // Create Session
                var amqpSessionSettings = new AmqpSessionSettings { Properties = new Fields() };
                session = amqpConnection.CreateSession(amqpSessionSettings);
                await session.OpenAsync(timeoutHelper.RemainingTime()).ConfigureAwait(false);
            }
            catch (Exception exception)
            {
                MessagingEventSource.Log.AmqpSessionCreationException(this.entityPath, amqpConnection, exception);
                session?.Abort();
                throw AmqpExceptionHelper.GetClientException(exception, null, session.GetInnerException());
            }

            AmqpObject link = null;
            try
            {
                // Create Link
                link = this.OnCreateAmqpLink(amqpConnection, this.amqpLinkSettings, session);
                await link.OpenAsync(timeoutHelper.RemainingTime()).ConfigureAwait(false);
                return new Tuple<AmqpObject, DateTime>(link, cbsTokenExpiresAtUtc);
            }
            catch (Exception exception)
            {
                MessagingEventSource.Log.AmqpLinkCreationException(
                    this.entityPath,
                    session,
                    amqpConnection,
                    exception);

                session.SafeClose(exception);
                throw AmqpExceptionHelper.GetClientException(exception, null, link?.GetInnerException(), session.IsClosing());
            }
        }
```

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ x ] Bug Description Added
- [ x ] Repro Steps Added
- [ x ] Setup information Added

**Comment by travismartinjones** [comment] 2019-05-14 17:42
@SHuygh I see a lot of similarity between your issue and the issue that I've encountered. https://github.com/Azure/azure-sdk-for-net/issues/6187 My issue is related to .net core web api, but the problem traces down to the same amqp link creation failures. Not a fix, but hopefully useful for the developer that is tasked to fix this bug.

**Comment by kurtzeborn** [comment] 2019-05-15 18:15
Thank you for opening this issue! We are routing it to the appropriate team for follow up.

CC: @AlexGhiondea

**Comment by SHuygh** [comment] 2019-06-06 09:04
Are there any updates regarding this issue, as this is currently blocking the user experience and our application is focussed on real time updates and communication running via the service bus

**Comment by AlexGhiondea** [comment] 2019-06-20 20:31
/cc @binzy @makam 

@SHuygh just speculating -- could this happen because of the time it takes to re-establish the amqp connection when switching the network connection?

**Comment by SHuygh** [comment] 2019-06-24 09:24
@AlexGhiondea We had this problem persist for a period of at least 20 min.
We currently workaround this issue not by the previous mentioned code, as maintaining an up to date fork would require high maintenance. We now close and reopen the subscriptionclient after not receiving a message for 1 minute. This contains the problem to a window of 1 min. However, this results in an increase in app crashes due to the https://github.com/Azure/azure-sdk-for-net/issues/6251 bug.

**Comment by AlexGhiondea** [comment] 2019-06-24 15:58
Thanks for the additional update. I am not sure if the connection would take 20 minutes to be re-established. 

I think it would be useful to look at some of the service logs around that time frame to see if we can piece together what is happening.

@makam is this something you can help with?

**Comment by SHuygh** [comment] 2019-06-24 18:30
Let me know if I can do or deliver anything more to further help resolve this issue

**Comment by axisc** [comment] 2019-06-26 18:52
@SHuygh

Thanks for raising this issue. 

AMQP is the preferred way to connect to the Service Bus namespace. However, AMQP is intensive for setting up the connection and is recommended when you have relatively uninterrupted connectivity to the cloud.

I recommend that you don't connect from the mobile device to the namespace directly and utilize a service to enqueue requests.

Please remember that there are connection limits on the SB namespace, so if you try to scale up your mobile devices, you will hit the limit soon.

Hope this helps. I'm closing this issue for now, please feel free to open if you have more questions.

**Comment by langsweirdt** [comment] 2019-06-26 18:58
@axisc can you please elaborate on "utilize a service to enqueue requests"? Do you allude to using a regular API and a polling-based mechanism from mobile?

**Comment by SHuygh** [comment] 2019-06-28 08:21
@AlexGhiondea @axisc Would it be possible to further elaborate on this.
As I feel that the suggested workaround significantly reduces the efficiency and bypasses the complete use case of the service bus connection.

In general we do not have problems with the connection, and switching between different cell towers or wifi. However, it occurs at some points and persists for a long a period of time.
The problem is that either the connection does not reset automatically or that we do not receive an exception that there is problem with the connection.

Both work arounds (one mentioned in the original post and one in https://github.com/Azure/azure-sdk-for-net/issues/6252#issuecomment-504931787) are only based on not receiving a message after a certain time out and then the connection is reset.

**Comment by axisc** [comment] 2019-07-13 01:00
apologies for the delay in my response. 

we synced on this internally, and agree that the fact that AMQP connection doesn't recover is a bug and we will investigate that internally. Given that the repro is on a mobile app, is there a way for you to share the actual mobile app?

Alternatively, you can send over the trace and memory dump for us to investigate.

Now about the architecture pattern - even though it works in the current form and you see the issue only occasionally, I don't believe that this pattern will scale well given that we have a limit of 5000 brokered (AMQP) connections/namespace. 

I don't know what your scale requirements are, but since you are on the receiver end, you may need some sort of polling mechanism, whether that is using the regular API or directly the service bus namespace. The concern about this architecture scaling still stands, so I'd recommend thinking about those first.

**Comment by travismartinjones** [comment] 2019-07-13 14:52
@axisc I have a different reproduce-able example that doesn't require a mobile application, but instead uses a .net web api project. I'm not 100% certain that these two bugs are caused by the same AMQP issue, but it looks quite probable due to the nature of the errors originating from the same file in the AMQP source code (AmqpLinkCreator). You may find the attached reproduce-able case on the bug https://github.com/Azure/azure-sdk-for-net/issues/6187 to be easier to work with and then try the fix against SHuygh's issue.

**Comment by axisc** [comment] 2019-07-15 05:23
@travismartinjones thanks for the details. we will investigate.

**Comment by nemakam** [comment] 2019-07-17 01:36
@SHuygh  - Is there a way to enable ETL traces and share it with us so that we can see which part is causing issues? Or like axisc responded, a memory dump

**Comment by SHuygh** [comment] 2019-07-17 08:40
@nemakam I am currently starting to work on a demo application which will provide an easy way to be able to reproduce the scenario and to be able to investigate the problem. Once available I will attach it to the issue.

**Comment by SHuygh** [comment] 2019-07-24 13:31
We have uploaded a repo which allows to reproduce the scenario.
https://github.com/ricksecretin/ServiceBusCommunicationBug

In the readme the explanation of what is needed for the setup is explained, together with how to reproduce the scenario.

**Comment by axisc** [comment] 2019-08-02 23:55
@SHuygh thanks for setting up the repo.

In our local testing environment, the AMQP connection is able to recover, so we believe that we need to drill deeper with a subject matter expert in the mobile networking space to better understand the network stack.

Having said that, I'm still not convinced this pattern is the right setup given that network switching is common in mobile phones and the preferred pattern should utilize a stateless protocol.

I did speak with the cloud solution architect working with you, at a Microsoft internal conference, and we synced on a couple of ideas utilizing SignalR that could work around this limitation.

You may have to resort to polling given that since your endpoint (mobile phone app) is not publicly addressable, it can't be pushed to.

**Comment by jfggdl** [comment] 2019-08-09 18:19
@SHuygh, I am closing this issue for now, but please let us know if you have additional questions and we can reopen it for you. Thanks.

**Closed by jfggdl** 2019-08-09 18:19 UTC
Labels: Bug, Client, Service Attention, Service Bus, customer-reported, customer-response-expected

**Comment by msioen** [comment] 2019-12-02 13:11
@axisc @jfggdl 
Can you please let us know the actions we need to take or how we can collect the requested etl traces or memory dump in the format you require?

**Comment by msioen** [comment] 2019-12-05 15:50
I've attached two traces here. Both are created with following command: PerfView.exe /OnlyProviders=*Microsoft-Azure-ServiceBus Collect

Note that I changed the replication sample somewhat to be a WPF sample instead of an Android sample, I don't think the trace would be helfpul otherwise as perfview doesn't run on the Android device. The same issue happens in console. The computer where I'm reproducing uses the same setup, ie it uses the mobile hotspot of a phone as it's wifi.

Log 1 - [PerfViewData.etl.wpf.zip](https://github.com/Azure/azure-sdk-for-net/files/3927745/PerfViewData.etl.wpf.zip)
=> startup app
=> send 3 messages, receive 3 messages back
=> change network type on the phone from 4g to 3g
=> here there are a couple of failed to send messages as the phone hadn't renegotiated it's connection yet
=> after a while I could send messages successfully, no messages received

[PerfViewData.etl.wpf-reset.zip](https://github.com/Azure/azure-sdk-for-net/files/3927746/PerfViewData.etl.wpf-reset.zip)
=> continuation on previous log (app didn't restart)
=> reset connection
=> messages can be sent succesfully / all missed messages from before come through now. ie they were succesfully delivered to the eventhub but not pushed back

Hopefully these can help you clear up the issue.

**Comment by nemakam** [comment] 2019-12-18 03:37
@msioen @SHuygh 
I tried the sample on my machine and it worked as expected. The messages started flowing even after switching from 2g->4g->ethernet->4g.
I am using @msioen's sample code and 4.1.1 service bus sdk (along with latest amqp library).
I am running on visual studio 16.4.2 (latest) and on windows 10. 
When I switch from one network to another, it takes 60 seconds for the connection to go idle, and after that it starts working automatically again.
Could you please try again and see if waiting 60 seconds get it to working (60 seconds fix was done in latest 4.1.1 sdk. So you'll need to download that and try)

**Comment by nemakam** [comment] 2019-12-18 03:40
To keep the uncertainty minimum, waiting for 2 mins is more ideal.
Also, check if you really need azure functions and eventhub to be present in the setup? Why not just send the message directly to service bus topic instead?

**Comment by msioen** [comment] 2019-12-19 12:57
@nemakam 
We just retested with the latest version of this library. We can confirm that with 4.1.1 this issue indeed seems to be fixed. We weren't aware that this fix was planned or taken up.
Thank you for the update.

With regards to the setup question, this was done to match our actual live setup which is a lot more complex.
