### ISSUE TITLE
[BUG] Unable to modify resource identity by GenericResource.Update

### ISSUE THREAD

**Issue by hachiang-msft** [Azure/azure-sdk-for-net#26496] opened 2022-01-20 06:43 UTC
### Library name and version

Azure.ResourceManager 1.0.0-beta.7

### Describe the bug

We are trying to enable/disable system assigned identity for our resource. But got response:
```
{
    "error": {
        "code": "InvalidRequestContent",
        "message": "The request content was invalid and could not be deserialized: 'Could not find member 'identity' on object of type 'ResourceIdentity'. Path 'identity.identity', line 1, position 24.'."
    }
}
```

I checked the request content. It looks like:
```
{
    "identity": {
        "identity": {
            "principalId": "null",
            "tenantId": "null",
            "type": "SystemAssigned"
        }
    },
    "location": "jioindiawest"
}
```

I'm wondering it's caused by duplicated identity object layer.
SDK write identity property twice.
[GenericResourceData.Write](https://github.com/Azure/azure-sdk-for-net/blob/3c0d9168490cee385ffcbc9794e4b9586cc9c3ed/sdk/resourcemanager/Azure.ResourceManager/src/Resources/Generated/Models/GenericResourceData.Serialization.cs#L49)
[ResourceIdentity.Write](https://github.com/Azure/azure-sdk-for-net/blob/ac9c1d3f6a27536428070e7e38be8060a8535d06/sdk/resourcemanager/Azure.ResourceManager/src/Resources/Custom/Models/ResourceIdentity.Serialization.cs#L29)

### Expected behavior

Request content should be 
```
{
   "identity": {
        "principalId": "null",
        "tenantId": "null",
        "type": "SystemAssigned"
    },
    "location": "jioindiawest"
}
```

### Actual behavior

Current request content:
```
{
    "identity": {
        "identity": {
            "principalId": "null",
            "tenantId": "null",
            "type": "SystemAssigned"
        }
    },
    "location": "jioindiawest"
}
```

### Reproduction Steps

Use following code snip to reproduce issue.
```
var resource = subscription.GetGenericResources().Get($"/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.CognitiveServices/accounts/{resourceName}").Value;

var result = resource.Update(new GenericResourceData(region)
{
    Identity = new ResourceIdentity(null, true)
}).WaitForCompletionAsync().Result;
```
Both case of turn on/off would fail ( Identity = new ResourceIdentity(null, false) )

**Comment by jsquire** [comment] 2022-01-20 13:38
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by fengzhou-msft** [comment] 2022-01-24 07:20
The issue is caused by the current serialization bug and will be resolved in https://github.com/Azure/azure-sdk-for-net/pull/26497

**Comment by fengzhou-msft** [comment] 2022-02-21 06:22
The issue shoud be fixed in [Azure.ResourceManager 1.0.0-beta.8](https://www.nuget.org/packages/Azure.ResourceManager/1.0.0-beta.8). Please try it and file new issues if you meet any.

**Closed by fengzhou-msft** 2022-02-21 06:22 UTC
Labels: ARM, Mgmt, customer-reported, needs-team-attention
