### ISSUE TITLE
Add Uri Property to TableServiceClient and TableClient

### ISSUE THREAD

**Issue by wsugarman** [Azure/azure-sdk-for-net#29794] opened 2022-07-12 04:05 UTC
### Library name

Azure.Data.Tables

### Please describe the feature.

Unlike the other Azure Storage service clients, both the `TableServiceClient` and the `TableClient` are missing a `Uri` property whose value is the corresponding endpoint. In addition to parity with the old [`WindowsAzure.Storage`](https://www.nuget.org/packages/WindowsAzure.Storage) package, these properties also allow users to correctly configure their applications to disable the Nagle algorithm as recommended in the [Azure Storage performance documentation](https://docs.microsoft.com/en-us/azure/storage/common/troubleshoot-storage-performance#investigating-client-performance-issues):

> For the table and queue services, the Nagle algorithm can also cause high SuccessE2ELatency as compared to SuccessServerLatency: for more information, see the post [Nagle's Algorithm is Not Friendly towards Small Requests](https://docs.microsoft.com/en-us/archive/blogs/windowsazurestorage/nagles-algorithm-is-not-friendly-towards-small-requests). You can disable the Nagle algorithm in code by using the ServicePointManager class in the System.Net namespace.

While the Azure Table service is mentioned, only the `QueueServiceClient` is used in the example -- presumably because an equivalent API does not exist for the `TableServiceClient`.

This ask was also included in https://github.com/Azure/azure-sdk-for-net/issues/19881

**Comment by jsquire** [comment] 2022-07-12 12:56
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by christothes** [comment] 2022-07-15 21:20
duplicate of #24415

**Closed by christothes** 2022-07-15 21:20 UTC
Labels: Client, customer-reported, question, Tables, needs-team-attention
