### ISSUE TITLE
Investigate failures in Identity on Sovereign Clouds

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-sdk-for-net#14860] opened 2020-09-03 19:18 UTC
Sovereign cloud onboarding has uncovered a few issues in an early run: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=521861&view=ms.vss-test-web.build-test-results-tab&runId=13110980&resultId=100105&paneView=debug

Looking for issues in the underlying library. 

Early investigations have already revealed: 

* SNI is not set up in sovereign clouds so failures relating to SNI are expected
* One secret was improperly transcribed (trailing space) 
* URLs may be hardcoded in the tests or tests may have other problems that make it difficult for them to work in sovereign clouds

@schaabs

**Comment by christothes** [comment] 2021-02-11 16:01
@schaabs is this a dupe of #7932 ?

**Comment by schaabs** [comment] 2021-02-11 18:25
No I closed #7932 as it was completed and never closed. I think this might be out of date as well. @benbp  did work to get these running. Ben do you know if this can be closed or is there still work needed here?

**Comment by benbp** [comment] 2021-02-11 19:03
@schaabs I believe the only outstanding issue is figuring out how to either get the self signed cert set up as a trusted root for sovereign clouds, or having those tests get skipped in these environments. However, the latest e-mail update I see from @tzhanl says they have keyvault passing fully now, so we may be good pending an answer from @tzhanl.

**Comment by tzhanl** [comment] 2021-02-18 02:17
@benbp @schaabs yes, all keyvault tests passed in sovereign clouds. We can close this issue.

**Closed** 2021-02-18 02:26 UTC
Labels: Azure.Identity, Client, needs-team-triage, test-sovereign-cloud
