### ISSUE TITLE
[QUERY] Purview models do not support public serialization

### ISSUE THREAD

**Issue by dsigninfinnium** [Azure/azure-sdk-for-net#39107] opened 2023-10-05 11:13 UTC
### Library name and version

Azure.Analytics.Purview.Catalog

### Query/Question

I want to use Azure.Analytics.Purview.Catalog sdk for microspft purview.
like ex;

1. first i create client .
2. var entities = client.Entities; using this i can access entities in catalog
3. var classifications = entities.GetClassifications("10f8870f-86b6-4ca0-bd24-c3a876100f5d");
4. var value = classifications.Content.ToString();
5. using value how do i see response if i try to use PurviewEntities entityfromResponse = JsonConvert.DeserializeObject<PurviewEntities>(value); 
6. here PurviewEntities is a class of Entities but in this class there is no variables define so how do i get response in entityfromResponse .

**Comment by jsquire** [comment] 2023-10-05 15:27
Hi @dsigninfinnium.  Thanks for reaching out and we regret that you're experiencing difficulties.   By design, arbitrary serialization and deserialization of Azure SDK models It is currently not possible.  We're aware that this is an oft-requested feature and are working on a version-tolerant solution for this across the Azure SDK packages.    Work is being tracked in [#35665](https://github.com/Azure/azure-sdk-for-net/issues/35665).   I'm going to close this out as a duplicate of that tracking issue.

**Closed by jsquire** 2023-10-05 15:27 UTC
Labels: Client, customer-reported, question, Purview
