### ISSUE TITLE
[TextAnalytics] AnalyzeOperationAnalyzeSentimentWithOpinionMining failing in nightly runs

### ISSUE THREAD

**Issue by AFengKK** [Azure/azure-sdk-for-net#32560] opened 2022-11-18 08:21 UTC
TextAnalytics nightly test runs are failing with:

> Error message
> Azure.RequestFailedException : Internal Server Error.
> Status: 200 (OK)
> ErrorCode: InternalServerError
> 
> Additional Information:
> error-0: InternalServerError: Internal Server Error.
> 
> Content:
> 
> Headers:
> x-envoy-upstream-service-time: 14
> apim-request-id: bc894272-59eb-4def-a822-7a7057fc6f9e
> Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
> X-Content-Type-Options: nosniff
> x-ms-region: REDACTED
> Date: Fri, 18 Nov 2022 03:01:10 GMT
> Content-Length: 528
> Content-Type: application/json; charset=utf-8
> 
> Data:
> error-0: InternalServerError: Internal Server Error.
> 
> 
> Stack trace
>    at Azure.Core.OperationInternal`1.GetResponseFromState(OperationState`1 state) in D:\a\_work\1\s\sdk\core\Azure.Core\src\Shared\OperationInternalOfT.cs:line 289
>    at Azure.Core.OperationInternal`1.UpdateStatusAsync(Boolean async, CancellationToken cancellationToken) in D:\a\_work\1\s\sdk\core\Azure.Core\src\Shared\OperationInternalOfT.cs:line 273
>    at Azure.Core.OperationInternalBase.UpdateStatusAsync(CancellationToken cancellationToken) in D:\a\_work\1\s\sdk\core\Azure.Core\src\Shared\OperationInternalBase.cs:line 87
>    at Azure.Core.OperationPoller.WaitForCompletionAsync(Boolean async, OperationInternalBase operation, Nullable`1 suggestedInterval, CancellationToken cancellationToken) in D:\a\_work\1\s\sdk\core\Azure.Core\src\Shared\OperationPoller.cs:line 79
>    at Azure.Core.OperationInternalBase.WaitForCompletionResponseAsync(Boolean async, Nullable`1 pollingInterval, String scopeName, CancellationToken cancellationToken) in D:\a\_work\1\s\sdk\core\Azure.Core\src\Shared\OperationInternalBase.cs:line 202
>    at Azure.Core.OperationInternal`1.WaitForCompletionAsync(Boolean async, Nullable`1 pollingInterval, CancellationToken cancellationToken) in D:\a\_work\1\s\sdk\core\Azure.Core\src\Shared\OperationInternalOfT.cs:line 242
>    at Azure.Core.OperationInternal`1.WaitForCompletionAsync(CancellationToken cancellationToken) in D:\a\_work\1\s\sdk\core\Azure.Core\src\Shared\OperationInternalOfT.cs:line 177
>    at Azure.AI.TextAnalytics.AnalyzeActionsOperation.WaitForCompletionAsync(CancellationToken cancellationToken) in D:\a\_work\1\s\sdk\textanalytics\Azure.AI.TextAnalytics\src\AnalyzeActionsOperation.cs:line 210
>    at Azure.AI.TextAnalytics.Tests.AnalyzeOperationTests.AnalyzeOperationAnalyzeSentimentWithOpinionMining() in D:\a\_work\1\s\sdk\textanalytics\Azure.AI.TextAnalytics\tests\AnalyzeOperationTests.cs:line 730
>    at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.BlockUntilCompleted()
>    at NUnit.Framework.Internal.MessagePumpStrategy.NoMessagePumpStrategy.WaitForCompletion(AwaitAdapter awaiter)
>    at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.<>c__DisplayClass1_0.<Execute>b__0()
>    at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.RunTestMethodInThreadAbortSafeZone(TestExecutionContext context, Action action)

For more details check here:

- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1998246&view=results

@jsquire for notification.

**Comment by joseharriaga** [comment] 2023-03-16 22:53
This is a duplicate of https://github.com/Azure/azure-sdk-for-net/issues/32560.

**Closed by joseharriaga** 2023-03-16 22:53 UTC
Labels: Client, Cognitive - Text Analytics, test-reliability
