### ISSUE TITLE
[QUERY] Using RequestContext with Azure.Data.Tables

### ISSUE THREAD

**Issue by pingzing** [Azure/azure-sdk-for-net#29028] opened 2022-05-29 18:08 UTC
### Library name and version

Azure.Data.Tables v12.5.0

### Query/Question

This sits somewhere between a feature request and a query, I think.

My use case is that I'd like to disable the automatic-throw-on-error-status behavior of the TableClient. The [Azure.Core documentation](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/Azure.Core/samples/RequestContext.md) implies that I should be able to do exactly this by attaching a RequestContext object to a request, but I can't seem to find anything on TableClient or TableServiceClient that would accept one.

Am I missing something, or is this just a hole in the implementation?

If RequestContext is indeed not something that can be used with Azure.Data.Tables, is there another way to disable the auto-throw behavior? I don't really like using exceptions to handle basic HTTP failure states.

**Comment by jsquire** [comment] 2022-05-29 19:08
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by christothes** [comment] 2022-06-03 21:20
Hi @pingzing 
This feature is forthcoming. Currently it only applies to purely code generated clients but will be coming to all clients in the next couple of months. 

duplicate of #25626

**Closed by christothes** 2022-06-03 21:20 UTC
Labels: Client, customer-reported, question, Tables, needs-team-attention
