### ISSUE TITLE
[FEATURE REQ] make serialization and deserialization easier for OpenAI result

### ISSUE THREAD

**Issue by weng5e** [Azure/azure-sdk-for-net#38566] opened 2023-09-07 17:21 UTC
### Library name

Azure.AI.OpenAI 

### Please describe the feature.

There are cases where users would want to move the OpenAI result across different serving tiers / multiple microservices. Like a background service worker may first get results back from OpenAI, then it want to store the result in Azure Blob before passing the blob uri to a web server to serve end customer http requests using a portion of the OpenAI result data. It would be really useful to serialize the whole OpenAI service response and store in Azure blob as a json. Then another microservice can deserialize the json into an object and use it.

`ChatCompletions` is one example that is currently hard to do serialization and deserialization. The [deserilization method call ](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/openai/Azure.AI.OpenAI/src/Generated/ChatCompletions.Serialization.cs#L18C41-L18C67)is non-public. So, the SDK user cannot easily reconstruct the object. Another obstacle is that `ChatCompletions` does not have public empty constructor, so common JSON libraries cannot do automatic deserialization.

Probably adding some public serialization and deserialization method would be really helpful.

**Comment by jsquire** [comment] 2023-09-07 21:10
Hi @weng5e.  Thank you for your feedback.  This is something that we're working on across the Azure SDK currently, tracked by [#35665](https://github.com/Azure/azure-sdk-for-net/issues/35665).    I'm going to close this out as a duplicate of that issue.

**Closed by jsquire** 2023-09-07 21:10 UTC
Labels: Client, customer-reported, feature-request, OpenAI
