### ISSUE TITLE
[Text Analytics]Build & Test failing in nightly runs

### ISSUE THREAD

**Issue by zzhxiaofeng** [Azure/azure-sdk-for-net#33724] opened 2023-01-28 07:52 UTC
Text Analytics nightly test runs are failing with:

> Error message:
> NUnit Adapter 4.3.1.0: Test execution complete
> Data collector 'Blame' message: All tests finished running, Sequence file will not be generated.
>   Passed ExtractSummaryArgumentValidation [3 ms]
>   Passed RecognizeEntitiesArgumentValidation [4 ms]
>   Passed RecognizeLinkedEntitiesArgumentValidation [3 ms]
>   Passed RecognizePiiEntitiesArgumentValidation [3 ms]
>   Passed AnalyzeActionsResult [9 ms]
> Results File: /Users/runner/work/1/s/sdk/textanalytics/Azure.AI.TextAnalytics/tests/TestResults/_Mac-1674873418415_2023-01-28_02_59_19.trx
> 
> Test Run Failed.
> Total tests: 1862
>      Passed: 1411
>      Failed: 1
>     Skipped: 450
>  Total time: 31.1915 Minutes
> ##[error]Bash exited with code '1'.

For more details check here:
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2145454&view=results

@jsquire for notification.

**Comment by joseharriaga** [comment] 2023-03-16 22:56
This is a duplicate of https://github.com/Azure/azure-sdk-for-net/issues/34970.

**Closed by joseharriaga** 2023-03-16 22:56 UTC
Labels: Client, Cognitive - Text Analytics, test-reliability
