### ISSUE TITLE
ServiceBus trigger has null body

### ISSUE THREAD

**Issue by lultimouomo** [Azure/azure-sdk-for-net#6912] opened 2019-07-12 10:18 UTC
**Describe the bug**
The body of a ServiceBus message sent from vert.x AMQP client is always null. Things worked fine with the functions 1.x trigger.

**To Reproduce**
Implement a 2.x azure function using Microsoft.Azure.WebJobs.Extensions.ServiceBus 3.0.6
Send a message from vert.x AMQP client (io.vertx:vertx-amqp-bridge:3.6.3).
Observe that body is null.

***Code Snippet***
I have tried the following ways to retrieve the body:
```
public static async Task Run([ServiceBusTrigger("statuses", Connection = "OldProtocolServiceBus")] string myQueueItem, DateTime enqueuedTimeUtc, ILogger log)
{
    log.LogDebug($"Service bus message received with body: {myQueueItem}");
}
```
```
public static async Task Run([ServiceBusTrigger("statuses", Connection = "OldProtocolServiceBus")] Message msg, ILogger log)
{
    string body = Encoding.UTF8.GetString(msg.Body);
    log.LogDebug($"Service bus message received with body: {body}");
```
```
public static async Task Run([ServiceBusTrigger("statuses", Connection = "OldProtocolServiceBus")] Message msg, ILogger log)
{
    string body = Encoding.UTF8.GetString(msg.GetBody<byte[]>());
    log.LogDebug($"Service bus message received with body: {body}");
}
```

**Expected behavior**
I'd expect to be able to ready the body of the message, like with 1.x functions.

**Setup (please complete the following information):**
 - OS: Azure platform, windows host
 - IDE : VisualStudio, JetBrains Rider, IntelliJ
 - Version of the Library used: Microsoft.Azure.WebJobs.Extensions.ServiceBus 3.0.6

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ x] Bug Description Added
- [ x] Repro Steps Added
- [x ] Setup information Added

**Comment by lultimouomo** [comment] 2019-07-12 11:11
I have managed to find a workaround: sending the AMQP message as Data instead than Amqp Value makes it work (at least for the `string myQueueItem, DateTime enqueuedTimeUtc` signature).
Still I would expect the 2.x functions to preserve compatibility with the 1.x version and work with Amqp Value messages.

**Comment by nemakam** [comment] 2019-07-16 22:56
@lultimouomo , your workaround is right.. And that is exactly how it has been implemented. The new ASB SDK sends message as Data instead of AmqpValue. So Message.Body is going to only retrieve the AmqpData (by design). Use `Microsoft.Azure.ServiceBus.InteropExtensionsMessageInteropExtensions.GetBody<>()` to retrieve non-data bodies (which has been added just for this back-compat purpose). 
2.x functions integration does have this breaking change and hence the bump to a new major version. Sorry for the trouble you have been through debugging this but that's by design.
I'm going to close this issue now. Let me know if you have any other concerns.

**Closed by nemakam** 2019-07-16 22:56 UTC
Labels: Client, Question, Service Attention, Service Bus, customer-reported
