### ISSUE TITLE
[BUG] EventProcessorHost will read the offset from InitialOffsetProvider if can't get the offset from CheckPoint

### ISSUE THREAD

**Issue by yuhaii** [Azure/azure-sdk-for-net#9247] opened 2019-12-25 02:35 UTC
**Describe the bug**
Our customer client is Azure function app. The function app will use the EventProcessorHost to receive message from event hub.

We find that during function app restart, the request to CheckPoint lease file been blocked due to a network issue. The EventProcessorHost  can' read the offset from CheckPoint , so it get the offset from InitialOffsetProvider. 

Can you please help confirm whether it is correct behavior? Thanks!
 
***Code Snippet***
https://github.com/Azure/azure-functions-eventhubs-extension/blob/7ccd930e6d2fdde64ded0ec7f540b08627739619/src/Microsoft.Azure.WebJobs.Extensions.EventHubs/Config/EventHubOptions.cs#L259

**Comment by jsquire** [comment] 2019-12-30 14:02
@serkantkaraca, @JamesBirdsall:  Would you be so kind as to offer your thoughts?

**Comment by JamesBirdsall** [comment] 2019-12-30 18:02
The expected behavior is that EPH falls back to the InitialOffsetProvider if and only if there is no checkpoint for the partition, and determining that requires downloading the blob and checking fields within it. If there is an error trying to retrieve the blob, that should result in some sort of retry behavior.

**Comment by serkantkaraca** [comment] 2019-12-31 01:43
I really don't see any place in the repo where InitialOffsetProvider is set. As James said, storage failures won't cause any kind of 'fallback to initial offset' behavior. Can you elaborate what type of issue you are observing?

**Comment by yuhaii** [comment] 2020-01-01 00:17
Hello @serkantkaraca , customer EventProcessorHost in function app recorded the offset in storage container. And it also set the InitialOffsetProvider as below. 

namespace EventHubOffsetTest
{
    public class Startup : FunctionsStartup
    {
        public override void Configure(IFunctionsHostBuilder builder)
        {
            builder.Services.PostConfigure<EventHubOptions>(o => o.EventProcessorOptions.InitialOffsetProvider = GetInitialOffset);
        }

        private static EventPosition GetInitialOffset(string partitionId)
        {
            return EventPosition.FromEnqueuedTime(DateTime.UtcNow);
        }
    }
}


Customer reported that they lost message when receive message from event hub during function app restart. 
We checked the event hub log and confirm that function app use InitialOffsetProvider , not CheckPoint to receive message and caused message lost.
Then we checked the storage frontend log and confirm that there were not checkpoint file request around function app restart. After about 5 minutes function app fully restarted, storage front end log show it began to read the checkpoint file again
We checked the network status and confirm that there was a network issue during function app restart. 

So it seems like the EventProcessorHost can't access the storage checkpoint lease file and read the offset from InitialOffsetProvider

**Comment by serkantkaraca** [comment] 2020-01-01 19:20
None of the EH SDKs overrides offsets with initial-offset values on a checkpoint store failure. I need to check Azure Functions' host implementation. I wonder if they do something different while handling failures. I will let you know about my findings.

**Comment by KitCheung1** [comment] 2020-01-09 00:39
@serkantkaraca Is there any update on your findings please?  We are still looking for an answer why the InitialOffsetProvider has kicked in in that particular instance.

**Comment by serkantkaraca** [comment] 2020-01-09 00:50
Sorry for the delay. I am still on it.

**Comment by serkantkaraca** [comment] 2020-01-14 19:55
What package version of WebJobs.Extensions are you building with?

**Comment by KitCheung1** [comment] 2020-01-14 20:29
We are using Microsoft.Azure.WebJobs.Extensions v3.0.0 and Microsoft.Azure.WebJobs.Extensions.EventHubs v4.0.1.

**Comment by serkantkaraca** [comment] 2020-01-14 21:57
Any chance you might have set EventHubOptions.BatchCheckpointFrequency to some large value which would result in no checkpoints at all?

**Comment by KitCheung1** [comment] 2020-01-14 22:23
In host.json, we set batchCheckpointFrequency to 1:
{
  "version": "2.0",
  "extensions": {
    "eventHubs": {
      "batchCheckpointFrequency": 1,
      "eventProcessorOptions": {
        "maxBatchSize": 128,
        "prefetchCount": 512
      }
    }
  }
}
We came across this issue only specifically in that occasion where the function host was restarting and at the same time there was also a network issue (according to the finding from Microsoft Support) so the EventProcessorHost was not able to access the checkpoint file from storage.  According to Microsoft Support, the InitialOffsetProvider logic has kicked in in that case, but that doesn't sound like the correct behaviour to me.  The InitialOffsetProvider should only kick in if there was no checkpoint file (i.e. a function subscribing to the event hub for **the very first time**), but not if there was a network issue.

**Comment by serkantkaraca** [comment] 2021-04-23 04:23
Closing the issue since there has not been any activity longer than a year now. Please consider moving to up to date Azure Functions Extension release https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Extensions.EventHubs and reopen the issue if still hit.

**Closed by serkantkaraca** 2021-04-23 04:23 UTC
Labels: Client, Event Hubs, Functions, Service Attention, customer-reported, question
