### ISSUE TITLE
[BUG] Service Bus reconnection not behaving as expected

### ISSUE THREAD

**Issue by hnuguse** [Azure/azure-sdk-for-net#30028] opened 2022-07-20 14:30 UTC
### Library name and version

Azure.Messaging.ServiceBus package 7.8.1

### Describe the bug

We have experienced similar issues to [this ](https://github.com/Azure/azure-sdk-for-net/issues/29043) issue were it presents itself intermittently in a test suite.

Scenario is as follows: We have a resource page that lists the queues belonging to that context. We add messages to the relevant queue and subsequently check that the queue has the correct amount of messages and then we do a peek. This is where we get the following error.

`Bad (Error getting queue status: The link 'G26:RR:304280244:637927926679470000:nfieldpurpleserbus:Queue:aaa-web-driver-test-sb-queue$management:56:sender' is force detached. Code: ServerError. Details: AmqpControlProtocolClient.Fault. TrackingId:10288625-1353-4faa-b78a-54c70e68cec6_B8, SystemTracker:nfieldpurpleserbus:Queue:aaa-web-driver-test-sb-queue, Timestamp:2022-07-07T12:34:35 Reference:276649e8-fb30-4238-a6d6-8def97115a6b, TrackingId:24da0460-4a03-47ca-a90d-fe87584c7a31_G26, SystemTracker:NoSystemTracker, Timestamp:2022-07-07T12:34:35 (GeneralError)`

### Expected behavior

After server failure, client library should reconnect

### Actual behavior

After server failure, client library does not reconnect

### Reproduction Steps

The problem seems intermittent and caused by something server side. 

In our codebase we lazily create the ServiceBusClient and we cache the receiver in order to prevent exhausting the amount of sockets used. We tried to reproduce it in a small test project that represents the code flow, but we haven't managed to reproduce it outside of the particular test suite. 

[Program.txt](https://github.com/Azure/azure-sdk-for-net/files/9150728/Program.txt)

### Environment

Framework net462
Visual Studio 17.2.5

**Comment by JoshLove-msft** [comment] 2022-07-20 17:31
Hi @hnuguse, 
I believe this is a known service issue related to a migration that has since been resolved. Are you still seeing the issue?

**Comment by hnuguse** [comment] 2022-07-20 17:35
Hi @JoshLove-msft, I have seen the service related issue being mentioned in [this ](https://github.com/Azure/azure-sdk-for-net/issues/29043) closed issue that I mentioned in the description as well. However we have seen this error occur over the last couple of weeks as well.

**Comment by hnuguse** [comment] 2022-07-20 17:37
Hi @JoshLove-msft, I have seen the service related issue being mentioned in [this ](https://github.com/Azure/azure-sdk-for-net/issues/29043) closed issue that I mentioned in the description as well. However we have seen this error occur over the last couple of weeks as well. The error description that I shared has a timestamp from July 7th.

**Comment by JoshLove-msft** [comment] 2022-07-20 17:46
I think based on the timestamp and error message this is likely the same issue. Would you be able to file a support ticket so that the service folks can take a look?

**Comment by hnuguse** [comment] 2022-07-21 09:44
I don't think it is related to the same migration/service issue that supposedly was resolved. We have just got the same error message again today as can be seen from the timestamp on the following message `Timestamp:2022-07-21T09:31:51`

` 	Bad (Error getting queue status: The link 'G11:RR:305511047:637939918124530000:nfieldpurpleserbus:Queue:aaa-web-driver-test-sb-queue$management:27:sender' is force detached. Code: ServerError. Details: AmqpControlProtocolClient.Fault. TrackingId:26d5596c-b686-48a5-8a22-2c78b85cdeb6_B16, SystemTracker:nfieldpurpleserbus:Queue:aaa-web-driver-test-sb-queue, Timestamp:2022-07-21T09:31:51 Reference:e8125139-c28c-46c7-a156-5bf2845cdda2, TrackingId:5289ec2d-5210-45a1-84b9-a3dfadbcf4e6_G11, SystemTracker:NoSystemTracker, Timestamp:2022-07-21T09:31:51 (GeneralError))`

**Comment by hnuguse** [comment] 2022-07-21 11:13
We have just been able to find the circumstances under which this error occurs:

1) We create a receiver and cache it (so that we don't exhaust the sockets being used)
2) We create a new queue
3) Add messages to the queue 
4) Peek the queue
5) We delete the queue

Now when we run the scenario again, we check if we have a cached receiver (not null / and not closed) or we create a new receiver and cache it (step 1), we do the same flow as described above and since we already have a cached receiver, we re-use it. This time the scenario fails in step 4 when we Peek the queue using the cached receiver. 

The issue is that the receiver is not invalidated ( marked as closed) when the related queue is deleted. If we do the peek in step 4 with a newly created receiver we don't get this issue.

See the code to reproduce here:
 
[Program.txt](https://github.com/Azure/azure-sdk-for-net/files/9158802/Program.txt)

**Comment by jsquire** [comment] 2022-07-21 13:48
To be sure that I'm following can you confirm:

- You have a receiver that you've used to peek a queue
- You delete the queue
- You attempt to peek using the existing receiver to a queue that no longer exists
- Your expectation is that the client somehow can detect the queue no longer exists and closes itself?

**Comment by hnuguse** [comment] 2022-07-21 14:47
The queue always exists before a peek is done (step 2 as described in previous post) and a message is put on the queue. We ran into this issue in our test suites and the issue is with the cached receiver not being able to read that queue anymore. I managed to reproduce it in the provided sample code that I shared in the previous post. 

If the cached queue is not able to read from the queue (which exists) I would expect it to have a status that it was closed or try to reconnect otherwise as this should be the default behavior as I understand from [this ](https://github.com/Azure/azure-sdk-for-net/issues/29043#issuecomment-1142412750) thread and the docs.

**Comment by jsquire** [comment] 2022-07-21 14:53
> try to reconnect otherwise as

Forgive me, but I'm still unclear on the scenario.  If the queue was deleted, what would the client be reconnecting to?

**Comment by hnuguse** [comment] 2022-07-21 15:02
Let's say we have a queue named "my-queue". 
In a test run it is filled with messages, and then deleted, but then it is immediately recreated and new messages are put on the queue. Eventually the cached receiver tries to read from "my-queue" again, but it fails. So I would expect the client to reconnect to "my-queue" if it fails to connect for some reason since the queue still exists and the receiver is created based on the queue name.

**Comment by hnuguse** [comment] 2022-07-21 15:03
Setup();
var seconds = 5;
while(true)
{
    await GetQueueDetails();
    Thread.Sleep(seconds * 1000);
}

void Setup()
{
    _adminClient = new (() => new ServiceBusAdministrationClient(ConnectionString));
    _client = new Lazy<ServiceBusClient>(() => new ServiceBusClient(ConnectionString));
    _receiverDictionary = new ();
};

async Task GetQueueDetails()
{
    if (!await _adminClient.Value.QueueExistsAsync(QueueName))
    {
        await _adminClient.Value.CreateQueueAsync(QueueName);
    }

    await AddMessage();

    var message = await GetServiceBusReceiver(QueueName).PeekMessageAsync();
    Console.WriteLine($"{DateTime.Now}: {message.Body}");
    await _adminClient.Value.DeleteQueueAsync(QueueName);
}

ServiceBusReceiver GetServiceBusReceiver(string queueName)
{
    // Get from cache
    if(_receiverDictionary.TryGetValue(queueName, out var receiver) && receiver != null && !receiver.IsClosed)
    {
        return receiver;
    }
    
    // Create new receiver
    receiver = _client.Value.CreateReceiver(queueName);
    _receiverDictionary.AddOrUpdate(queueName, receiver, (key, oldValue) => receiver);
    return receiver;
}

async Task AddMessage()
{
    var sender = _client.Value.CreateSender(QueueName);
    await sender.SendMessageAsync(new ServiceBusMessage("Hello world 1"));
}

**Comment by jsquire** [comment] 2022-07-21 15:09
Thank you, @hnuguse.   I now understand the end-to-end scenario.   

The client will attempt to reconnect when a link is closed, or the service detaches it.  What appears to be happening is that the service isn't closing the active link when the queue is deleted.  The next call is using the active link and triggering the service error that you're seeing.

One final clarification, if you'd be so kind - if you attempt to peek again after seeing this exception does the call succeed or does the error persist until the client is closed?

**Comment by hnuguse** [comment] 2022-07-21 15:21
Ok that makes sense @jsquire thanks.

I tried to keep peeking after the exception and the same error is thrown on subsequent tries.

```Exception has occurred: CLR/Azure.Messaging.ServiceBus.ServiceBusException
Exception thrown: 'Azure.Messaging.ServiceBus.ServiceBusException' in System.Private.CoreLib.dll: 'The link 'G1:RR:305572002:637940134893600000:nfieldpurpleserbus:Queue:hn-test4$management:53:sender' is force detached. Code: ServerError. Details: AmqpControlProtocolClient.Fault. TrackingId:5199820f-79fb-4de7-9e69-c4de5c901f07_B5, SystemTracker:nfieldpurpleserbus:Queue:hn-test4, Timestamp:2022-07-21T15:20:09 Reference:b6391470-db83-4d83-93f3-696cef08b0cf, TrackingId:34f94b6b-fe18-44f9-9fb6-1146841cb9fe_G1, SystemTracker:NoSystemTracker, Timestamp:2022-07-21T15:20:09'```

**Comment by jsquire** [comment] 2022-07-21 15:29
Thanks, @hnuguse.   That seems to confirm that the link is left open and active but is in an invalid state.  The client doesn't have insight into the link not being healthy, only that the service is returning with a `GeneralError`.  The fix for this will require service changes.   

We'll need to hand this off to the service team to investigate whether they can either detect/recover on the service side, force-close the link, or send back a specific error code that the client can interpret as "the link is bad, close and reopen."    I'll transfer this issue to Service Attention.   Josh and I will also follow-up internally.   

As Josh suggested, your best path forward would be to [open an Azure support request](https://docs.microsoft.com/azure/azure-portal/supportability/how-to-create-azure-support-request) and refer to this issue as context.

**Comment by hnuguse** [comment] 2022-07-21 15:40
Thanks again for looking into it, we'll create a support request.

**Comment by dantheman999301** [comment] 2022-07-21 16:50
Just want to chime in here and say that we got response about our particular issues (unable to send scheduled messages after a reconnection) and it appears there is an issue on the Azure side that they are going to be resolving.

Here is what they said
> We got an update from our Product group team, As part of a load balancing, the service internally moved the queue from one container to another container. This is one time manual intervention we are doing to handle special circumstances and it shouldn't normally happen.
>
> When we moved the entity, all senders and receivers have been closed and clients automatically reconnected to the new container. But existing request-response links, special links used to send scheduled messages, peek messages, were not closed. In this case, the customer was using the same sender and it was attempting to send scheduled messages to the old container. Recreating a new sender should have mitigated the issue for the customer.
>
> The service should have closed the request-response link too. This is a bug in the service. We are creating a repair item to fix it in the next service upgrade.

**Comment by hnuguse** [comment] 2022-07-22 10:44
Hi @dantheman999301 thanks for your message. The bug being fixed seems to be related to the scenario of service/container migrations. So I assume that the bug fix is related to closing all links in the event of future service migrations. 

The issue that the service doesn't detect that the active link should be closed in other scenarios as outlined in this issue seems slightly different, so I guess we should still open a support ticket for that right?

**Comment by EldertGrootenboer** [comment] 2022-07-27 19:10
Adding @yvgopal to look into this issue.

**Comment by yvgopal** [comment] 2022-07-27 21:58
Even though those are two different issues (queue moved for load balancing, queue deleted and re-created), both of them have the same root cause. Fixing that bug will address both issues. Having said that, I must say both of them are not normal scenarios.
1. Very rarely do we move queues or topics for load balancing. To give some context, we have done that in only one cluster recently in the last 2 years.
2. Deleting and recreating the same queue and still using the cached receiver is not normal, in my opinion. In this case, service is closing send and receive links. So reusing senders and receivers to perform sends and receives will still work fine even after deleting and re-creating. But Peek is a special kind of operation which is impacted by this bug. Also ScheduleMessageAsync method will have the same problem.

We will be fixing this issue in the next service deployment.

**Closed by yvgopal** 2022-07-27 21:58 UTC
Labels: Service Bus, Service Attention, Client, customer-reported, question, needs-team-attention

**Comment by hnuguse** [comment] 2022-08-02 13:14
Ok great, thanks for your response.
