### ISSUE TITLE
[BUG] Service Fabric Management SDK deserialization exception when listing applications

### ISSUE THREAD

**Issue by stefanmsft** [Azure/azure-sdk-for-net#6405] opened 2019-05-23 21:28 UTC
**Describe the bug**

Added Microsoft.Azure.Management.ServiceFabric (v1.1.0) package to a .csproj, tried to ListApplications for a cluster and received a deserialization exception. Seems to be that that the client is trying to hit the Service Fabric resource provider with `api-version=2018-02-01`, but getting a response where the `upgradeReplicaSetCheckTimeout` is a string.

***Exception or Stack Trace***

Exception message:

``{"Error converting value \"00:20:00\" to type 'System.Nullable`1[System.Int64]'. Path 'properties.upgradePolicy.upgradeReplicaSetCheckTimeout', line 32, position 53."}``

Stack Trace:

```
at Microsoft.Azure.Management.ServiceFabric.ApplicationsOperations.ListWithHttpMessagesAsync(String resourceGroupName, String clusterName, Dictionary`2 customHeaders, CancellationToken cancellationToken)
at Microsoft.Azure.Management.ServiceFabric.ApplicationsOperationsExtensions.ListAsync(IApplicationsOperations operations, String resourceGroupName, String clusterName, CancellationToken cancellationToken)
```

**To Reproduce**

Try retrieving applications on a Service Fabric cluster using the Microsoft.Azure.Management.ServiceFabric ( version 1.1.0 ) NuGet package.

***Code Snippet***

```csharp
var armToken = await tokenProvider.GetAccessTokenAsync(Constants.AzureResourceManagementUrl);
serviceFabricManagementClient = new ServiceFabricManagementClient(new TokenCredentials(armToken))
{
    SubscriptionId = options.Value.SubscriptionId.ToString(),
};
var applications = await serviceFabricManagementClient.Applications.ListAsync("myResourceGroupName", "myCluster", cancellationToken);
```

**Expected behavior**

The list of Service Fabric Applications running on the Service Fabric cluster is returned.

**Screenshots**

![image](https://user-images.githubusercontent.com/33465077/58286604-f8bed100-7d63-11e9-84d3-b4c05f45ce5b.png)

**Setup (please complete the following information):**
 - OS: Windows
 - IDE : Visual Studio 2019
 - Version of the Library used : 1.1.0

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ x] Bug Description Added
- [ x] Repro Steps Added
- [ x] Setup information Added

**Comment by kurtzeborn** [comment] 2019-05-24 18:29
CC: @shahabhijeet

**Comment by a-santamaria** [comment] 2019-07-23 22:41
Duplicate of #4510. Thanks for reporting. We have made the fix for version 2019-03-01. We will publish the sdk with this new version shortly.

**Closed by a-santamaria** 2019-07-23 22:41 UTC
Labels: Mgmt, Service Fabric
