### ISSUE TITLE
Microsoft.Azure.EventGrid - Can not send CloudEvent using EventGridClient

### ISSUE THREAD

**Issue by susosuso** [Azure/azure-sdk-for-net#10684] opened 2020-03-18 19:47 UTC
We have a EventGrid Topic setup with CloudEvent as input schema. When trying to send a CloudEvent using EventGridClient, we get the below error.

`Microsoft.Rest.Azure.CloudException: The Content-Type header is either missing or it doesn't have a valid value. The content type header must either be application/cloudevents+json; charset=utf-8 or application/cloudevents-batch+json; charset=UTF-8. 
`
Looks like the client code force content-type to be application/json:
https://github.com/Azure/azure-sdk-for-net/blob/bdc5c7a3d375371c3af4652c2ebfdb85dfdcd945/sdk/eventgrid/Microsoft.Azure.EventGrid/src/Generated/EventGridClient.cs#L350

Not quite sure if this is a bug or feature request... What is the recommended way to send CloudEvent to event grid?

**Comment by ahamad-MS** [comment] 2020-03-20 09:15
Thanks for reporting this issue. We are investigating/triaging it.

**Comment by ahamad-MS** [comment] 2020-04-07 17:42
We added this to our backlog and will address it appropriately. thanks

**Comment by SeanFeldman** [comment] 2020-05-21 21:23
@ahamad-MS is there a service issue associated with this issue?
If not, would it be possible not to close it until the problem is addressed?

**Comment by ahamad-MS** [comment] 2020-05-23 07:12
@SeanFeldman  sure. issue reopened.

**Comment by ahamad-MS** [comment] 2020-07-01 18:10
Update: this issue is under discussion with Azure Data Plane SDK team for proper addressing this for customer. No ETA yet for resolving this issue as it is in the design phase.

**Comment by ppatino** [comment] 2020-07-23 21:55
@ahamad-MS any updates here? Basic usage from [this sample](https://github.com/Azure-Samples/event-grid-dotnet-publish-consume-events/blob/master/EventGridPublisher/DomainPublisher/Program.cs) is failing and I'm not finding a workaround.

**Comment by ahamad-MS** [comment] 2020-07-27 16:28
Hello @ppatino  ..  The only workaround here is using pure http APIs to send your events while getting cloud event support in SDK. The earlier ETA for .NET and JAVA SDKs is mid-end of Sep (provided no blocker issues). Python and Typescript support will hopefully be available earlier on mid-end of Aug (again, provided no blocker issues).

**Comment by ahamad-MS** [comment] 2020-10-06 16:53
@ppatino  The new Event Grid SDK that is currently in beta and is available here: 

https://www.nuget.org/packages/Azure.Messaging.EventGrid/4.0.0-beta.2

Please give it a try and provide us any feedback needed if possible.

**Closed** 2020-10-30 08:00 UTC
Labels: Client, Event Grid, Service Attention, needs-author-feedback, no-recent-activity, question
