### ISSUE TITLE
[BUG] SNAT Port Exhaustion with Azure Service Bus

### ISSUE THREAD

**Issue by mjkent** [Azure/azure-sdk-for-net#24851] opened 2021-10-21 17:45 UTC
**Describe the bug**
I'm using a Linux Web App that connects to an Azure Service Bus to send messages. The web app is causing SNAT port exhaustion connecting to servicebus.windows.net. It seems connections to servicebus.windows.net are not being reused or closed correctly.
Messages are received in another app service.
We send under a few hundred messages per hour.

**Expected behavior**
Service Bus connections are reused or closed after use.

**Actual behavior (include Exception or Stack Trace)**
The app is having issues with SNAT port exhaustion causing crashing.

**To Reproduce**
In `startup.cs`, registration:
```csharp
services.AddAzureClients(clientsBuilder =>
                {
                    clientsBuilder.AddServiceBusClient(Configuration.GetValue<string>("Queue:ServiceBusConnectionString"))
                      // (Optional) Provide name for instance to retrieve by with DI
                      //.WithName("Client1Name")
                      // (Optional) Override ServiceBusClientOptions (e.g. change retry settings)
                      .ConfigureOptions(options =>
                      {
                          //options.RetryOptions.Delay = TimeSpan.FromMilliseconds(50);
                          options.RetryOptions.MaxDelay = TimeSpan.FromSeconds(5);
                          options.RetryOptions.MaxRetries = 3;
                      });
                });
```

All queue message creation goes through this class:
```csharp
    public class QueueService : IQueueService
    {
        private readonly IOptions<AppSettings> options;
        private readonly ILogger<QueueService> logger;
        private readonly ServiceBusClient serviceBusClient;

        public QueueService(IOptions<AppSettings> options, ILogger<QueueService> logger, ServiceBusClient serviceBusClient)
        {
            this.options = options;
            this.logger = logger;
            this.serviceBusClient = serviceBusClient;
        }

        public async Task Enqueue(string queue, string label, string message, bool throwErrors = false)
        {
            if ((options.Value?.Queue?.ServiceBusConnectionString).IsNullOrEmpty())
            {
                logger.LogError($"No service bus connection set for {label}: {message}");
                if (throwErrors)
                {
                    throw new Exception($"No service bus connection set for {label}: {message}");
                }
                return;
            }
            try
            {
                //https://docs.microsoft.com/en-us/dotnet/api/overview/azure/messaging.servicebus-readme-pre
                //Sender should not be disposed
                var sender = serviceBusClient.CreateSender(queue);
                
                var queueMessage = new ServiceBusMessage(Encoding.UTF8.GetBytes(message));
                queueMessage.Subject = label;
                await sender.SendMessageAsync(queueMessage);
            }
            catch (Exception e)
            {
                logger.LogError(e, $"Queue Error for {label}: {message}");
                if (throwErrors)
                {
                    throw;
                }
            }
        }
```

**Environment:**
Assembly Azure.Messaging.ServiceBus, Version=7.4.0.0, Culture=neutral, PublicKeyToken=92742159e12e44c8
Azure Web App on Linux App Service
.NET 5.0

![image](https://user-images.githubusercontent.com/3409178/138329185-06479e2d-fef7-494b-b9ea-67a4917736fa.png)
![image](https://user-images.githubusercontent.com/3409178/138329199-c57ecb33-cf2f-435e-8c88-44b87c46b56b.png)

**Comment by mjkent** [comment] 2021-10-21 18:51
@JoshLove-msft : Thank you for the response!

I'm not finding anything in the documentation around reusing the same sender. If you could send me documentation or an example I'd be happy to try out any pattern that would fix this.

Here is what that gave me on a local Visual Studio run of the application on Windows. I created three messages on the queue. Anything in squiggly brackets is strings I removed. I can send anyone the non-anonymized log privately.
```
Azure.Messaging.ServiceBus: Debug: Creating a ServiceBusSender (Namespace: '{TestingQueueName}.servicebus.windows.net', Entity name: '{QueueName}'
Azure.Messaging.ServiceBus: Debug: A ServiceBusSender has been created (Identifier '{QueueName}-{Guid1}').
Azure.Messaging.ServiceBus: Information: {QueueName}-{Guid1}: SendAsync start. MessageCount = 1
Azure.Messaging.ServiceBus: Information: Creating send link for Identifier: {QueueName}-{Guid1}.
Azure.Messaging.ServiceBus: Debug: {QueueName}-{Guid1}: Requesting authorization to amqps://{TestingQueueName}.servicebus.windows.net/{QueueName}
Azure.Messaging.ServiceBus: Debug: {QueueName}-{Guid1}: Authorization to amqps://{TestingQueueName}.servicebus.windows.net/{QueueName} complete. Expiration time: 10/21/2021 19:04:49
Azure.Messaging.ServiceBus: Information: Send link created for Identifier: {QueueName}-{Guid1}.
Azure.Messaging.ServiceBus: Information: {QueueName}-{Guid1}: SendAsync done.
Azure.Messaging.ServiceBus: Debug: Creating a ServiceBusSender (Namespace: '{TestingQueueName}.servicebus.windows.net', Entity name: '{QueueName}'
Azure.Messaging.ServiceBus: Debug: A ServiceBusSender has been created (Identifier '{QueueName}-{Guid2}').
Azure.Messaging.ServiceBus: Information: {QueueName}-{Guid2}: SendAsync start. MessageCount = 1
Azure.Messaging.ServiceBus: Information: Creating send link for Identifier: {QueueName}-{Guid2}.
Azure.Messaging.ServiceBus: Debug: {QueueName}-{Guid2}: Requesting authorization to amqps://{TestingQueueName}.servicebus.windows.net/{QueueName}
Azure.Messaging.ServiceBus: Debug: {QueueName}-{Guid2}: Authorization to amqps://{TestingQueueName}.servicebus.windows.net/{QueueName} complete. Expiration time: 10/21/2021 19:04:49
Azure.Messaging.ServiceBus: Information: Send link created for Identifier: {QueueName}-{Guid2}.
Azure.Messaging.ServiceBus: Information: {QueueName}-{Guid2}: SendAsync done.
Azure.Messaging.ServiceBus: Debug: Creating a ServiceBusSender (Namespace: '{TestingQueueName}.servicebus.windows.net', Entity name: '{QueueName}'
Azure.Messaging.ServiceBus: Debug: A ServiceBusSender has been created (Identifier '{QueueName}-{Guid3}').
Azure.Messaging.ServiceBus: Information: {QueueName}-{Guid3}: SendAsync start. MessageCount = 1
Azure.Messaging.ServiceBus: Information: Creating send link for Identifier: {QueueName}-{Guid3}.
Azure.Messaging.ServiceBus: Debug: {QueueName}-{Guid3}: Requesting authorization to amqps://{TestingQueueName}.servicebus.windows.net/{QueueName}
Azure.Messaging.ServiceBus: Debug: {QueueName}-{Guid3}: Authorization to amqps://{TestingQueueName}.servicebus.windows.net/{QueueName} complete. Expiration time: 10/21/2021 19:04:49
Azure.Messaging.ServiceBus: Information: Send link created for Identifier: {QueueName}-{Guid3}.
Azure.Messaging.ServiceBus: Information: {QueueName}-{Guid3}: SendAsync done.
```

**Comment by JoshLove-msft** [comment] 2021-10-21 19:01
We don't have full application examples - we should probably add something like this or at least explicitly mention in the docs that we recommend reusing senders.

I think in your code, if you just create the sender in your constructor and store it in a class field that would be the recommended approach. As you can see from the logs, each time a message is being sent a new send link is being created.

**Comment by mjkent** [comment] 2021-10-21 19:16
@JoshLove-msft The docs seem to say that as long as I don't dispose the clients and senders that they are responsible for connection reuse.

I've tried disposing the ServiceBusClient and ServiceBusSender and it seems that the connections don't get cleaned up then either.

Since we pass the queue name into creating the sender, I'll need to keep a sender per queue(there is less than 5 of them). I'm going to create a class that does this and register it as a singleton.

**Comment by JoshLove-msft** [comment] 2021-11-02 03:28
Ok, if the client is only being created once, I think the issue is likely not with the SDK. Is it possible for you to collect a memory dump when the issue occurs? I'm not sure if this is possible with Linux apps, but should be on Windows.

**Comment by JoshLove-msft** [comment] 2021-11-16 19:08
Closing for now as I have not been able to reproduce this. Please reopen if you run into this issue again.

**Closed by JoshLove-msft** 2021-11-16 19:08 UTC
Labels: Service Bus, Client, customer-reported, question, needs-team-attention

**Comment by mjkent** [comment] 2022-02-27 19:17
If someone else stumbles upon this, we found a few ways to fix this:
1. Switch to Windows App Service
2. Switch to NAT Gateway
3. Upgrade to Net 6.0

🤷
