### ISSUE TITLE
[BUG] FrontendIPConfigurations is null after getting cloud service ext. support

### ISSUE THREAD

**Issue by t-sch** [Azure/azure-sdk-for-net#26713] opened 2022-01-31 15:17 UTC
### Library name and version

Azure.ResourceManager.Compute 1.00-beta6

### Describe the bug

I deployed a Cloud Service ext. Support from VS 2022 and it runs fine.
When trying to access the publicIPAddress from a management page in ASP.NET FW 4.8 by calling
`var cs = await rg.GetCloudServices().GetIfExistsAsync(<name>)`
I get a null value in
`cs.Data.Properties.NetworkProfile.LoadBalancerConfigurations[0].Properties.FrontendIPConfigurations`
In consequence I can't update the instance count by using
`rg.GetCloudServices().CreateOrUpdateAsync(cs.Data.Name, cs.Data);`
That call gets me a `NullReferenceException `inside of the `LoadBalancerConfiguration `deserialization.

### Expected behavior

The member should not be null but should contain an object having the ip addresses of the loadbalancer.
The Azure portal show an ip address for he load balancer.

### Actual behavior

The load balancer configuration has a null `FrontendIPConfigurations` member.

### Reproduction Steps

Deploy a Cloud Service Ext. Support to Azure and register a client secret.
Call
```
         var cred = new ClientSecretCredential(Properties.Settings.Default.AzureTenantID, Properties.Settings.Default.AzureAppID, Properties.Settings.Default.ClientSecret);
         armClient = new ArmClient(cred);
         string res = $"/subscriptions/{Properties.Settings.Default.AzureSubscriptionID}/resourceGroups/{Properties.Settings.Default.ResourceGroup}";
         var resId = new ResourceIdentifier(res);
         rg = armClient.GetResourceGroup(resId);
         rg = await rg.GetAsync();

         var cs = await rg.GetCloudServices().GetIfExistsAsync(cs_name);
         if (cs.Value == null)
         {
var ipconfig = cs.Data.Properties.NetworkProfile.LoadBalancerConfigurations[0].Properties.FrontendIPConfigurations;
// will be null
}

```

### Environment

localhost on .NET FW 4.8
VS 17.0.5

**Comment by jsquire** [comment] 2022-01-31 15:44
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by fengzhou-msft** [comment] 2022-05-23 06:47
The property name returned by service is `frontendIpConfigurations` (lower case p in Ip), but it's defined as [frontendIPConfigurations](https://github.com/Azure/azure-rest-api-specs/blob/ac40996ab146d1360a4783665bb6c0b13f345aec/specification/compute/resource-manager/Microsoft.Compute/stable/2021-03-01/cloudService.json#L2104) in swagger. Service team needs to fix swagger definition.

**Comment by fengzhou-msft** [comment] 2022-05-23 06:52
#28922 fixes this issue with a directive to transform the swagger when generating SDK. It will be released in the next Azure.ResourceManager.Compute SDK version.

@t-sch please notice that we have a breaking change to flatten single-property model and the code is changed to:
`var ipconfig = cs.Value.Data.Properties.NetworkProfile.LoadBalancerConfigurations[0].LoadBalancerFrontendIPConfigurations;`

**Comment by jaylabell** [comment] 2022-07-28 19:16
@fengzhou-msft - please provide an update

**Comment by fengzhou-msft** [comment] 2022-07-29 15:50
> @fengzhou-msft - please provide an update

The issue is fixed in the latest version. Please try it.

**Comment by jaylabell** [comment] 2022-08-04 18:29
Thank you!

**Closed by jaylabell** 2022-08-04 18:29 UTC
Labels: Compute, Service Attention, Mgmt, customer-reported, question, needs-team-attention
