### ISSUE TITLE
[BUG] It is not possible to connect Azure Key Vault from the command line via DefaultAzureCredential after 'az login' authentication

### ISSUE THREAD

**Issue by andrewtsw** [Azure/azure-sdk-for-net#16306] opened 2020-10-27 07:35 UTC
**Describe the bug**
I used this sample to connect from the client app (command-line .NET Core or WPF desktop app) to Azure Key Vault,
https://docs.microsoft.com/en-us/azure/key-vault/secrets/quick-create-net

And this sample does not work with DefaultAzureCredential
But It works fine when I replaced DefaultAzureCredential with AzureCliCredential
Is it an issue?

According to this documentation
https://docs.microsoft.com/en-us/dotnet/api/azure.identity.defaultazurecredential?view=azure-dotnet&preserve-view=true
`DefaultAzureCredential` uses `AzureCliCredential`

**Expected behavior**
After `az login` I can use DefaultAzureCredential without additional environment credentials.

**Actual behavior (include Exception or Stack Trace)**
I got an issue when I use DefaultAzureCredential without additional environment variables.

https://docs.microsoft.com/en-us/dotnet/api/azure.identity.defaultazurecredential?view=azure-dotnet
But DefaultAzureCredential works when I use additional environment variables.
I believe DefaultAzureCredential uses EnvironmentCredential in this case.

Exception details:
```cs
Unhandled exception. Azure.Identity.AuthenticationFailedException: SharedTokenCacheCredential authentication failed: A configuration issue is preventing authentication - check the error message from the server for details.You can modify the configuration in the application registration portal. See https://aka.ms/msal-net-invalid-client for details.  Original exception: AADSTS70002: The client does not exist or is not enabled for consumers. If you are the application developer, configure a new application through the App Registrations in the Azure Portal at https://go.microsoft.com/fwlink/?linkid=2083908.
Trace ID: 8fa93464-beb6-4e98-8705-af7617f20d00
Correlation ID: a269eb23-1879-4859-8811-b58af2dd88a0
Timestamp: 2020-10-07 07:17:03Z
 ---> MSAL.NetCore.4.16.1.0.MsalServiceException:
        ErrorCode: invalid_client
Microsoft.Identity.Client.MsalServiceException: A configuration issue is preventing authentication - check the error message from the server for details.You can modify the configuration in the application registration portal. See https://aka.ms/msal-net-invalid-client for details.  Original exception: AADSTS70002: The client does not exist or is not enabled for consumers. If you are the application developer, configure a new application through the App Registrations in the Azure Portal at https://go.microsoft.com/fwlink/?linkid=2083908.
Trace ID: 8fa93464-beb6-4e98-8705-af7617f20d00
Correlation ID: a269eb23-1879-4859-8811-b58af2dd88a0
Timestamp: 2020-10-07 07:17:03Z
   at Microsoft.Identity.Client.OAuth2.OAuth2Client.ThrowServerException(HttpResponse response, RequestContext requestContext)
   at Microsoft.Identity.Client.OAuth2.OAuth2Client.CreateResponse[T](HttpResponse response, RequestContext requestContext)
   at Microsoft.Identity.Client.OAuth2.OAuth2Client.ExecuteRequestAsync[T](Uri endPoint, HttpMethod method, RequestContext requestContext, Boolean expectErrorsOn200OK, Boolean addCommonHeaders)
   at Microsoft.Identity.Client.OAuth2.OAuth2Client.GetTokenAsync(Uri endPoint, RequestContext requestContext, Boolean addCommonHeaders)
   at Microsoft.Identity.Client.OAuth2.TokenClient.SendHttpAndClearTelemetryAsync(String tokenEndpoint)
   at Microsoft.Identity.Client.OAuth2.TokenClient.SendHttpAndClearTelemetryAsync(String tokenEndpoint)
   at Microsoft.Identity.Client.OAuth2.TokenClient.SendTokenRequestAsync(IDictionary`2 additionalBodyParameters, String scopeOverride, String tokenEndpointOverride, CancellationToken cancellationToken)
   at Microsoft.Identity.Client.Internal.Requests.RequestBase.SendTokenRequestAsync(String tokenEndpoint, IDictionary`2 additionalBodyParameters, CancellationToken cancellationToken)
   at Microsoft.Identity.Client.Internal.Requests.Silent.SilentClientAuthStretegy.RefreshAccessTokenAsync(MsalRefreshTokenCacheItem msalRefreshTokenItem, CancellationToken cancellationToken)
   at Microsoft.Identity.Client.Internal.Requests.Silent.SilentClientAuthStretegy.TryGetTokenUsingFociAsync(CancellationToken cancellationToken)
   at Microsoft.Identity.Client.Internal.Requests.Silent.SilentClientAuthStretegy.RefreshRtOrFailAsync(CancellationToken cancellationToken)
   at Microsoft.Identity.Client.Internal.Requests.Silent.SilentClientAuthStretegy.ExecuteAsync(CancellationToken cancellationToken)
   at Microsoft.Identity.Client.Internal.Requests.Silent.SilentClientAuthStretegy.ExecuteAsync(CancellationToken cancellationToken)
   at Microsoft.Identity.Client.Internal.Requests.Silent.SilentRequest.ExecuteAsync(CancellationToken cancellationToken)
   at Microsoft.Identity.Client.Internal.Requests.Silent.SilentRequest.ExecuteAsync(CancellationToken cancellationToken)
   at Microsoft.Identity.Client.Internal.Requests.RequestBase.RunAsync(CancellationToken cancellationToken)
   at Microsoft.Identity.Client.ApiConfig.Executors.ClientApplicationBaseExecutor.ExecuteAsync(AcquireTokenCommonParameters commonParameters, AcquireTokenSilentParameters silentParameters, CancellationToken cancellationToken)
   at Azure.Identity.AbstractAcquireTokenParameterBuilderExtensions.ExecuteAsync[T](AbstractAcquireTokenParameterBuilder`1 builder, Boolean async, CancellationToken cancellationToken)
   at Azure.Identity.MsalPublicClient.AcquireTokenSilentAsync(String[] scopes, IAccount account, Boolean async, CancellationToken cancellationToken)
   at Azure.Identity.SharedTokenCacheCredential.GetTokenImplAsync(Boolean async, TokenRequestContext requestContext, CancellationToken cancellationToken)
        StatusCode: 401
        ResponseBody: {"error":"invalid_client","error_description":"AADSTS70002: The client does not exist or is not enabled for consumers. If you are the application developer, configure a new application through the App Registrations in the Azure Portal at https://go.microsoft.com/fwlink/?linkid=2083908.\r\nTrace ID: 8fa93464-beb6-4e98-8705-af7617f20d00\r\nCorrelation ID: a269eb23-1879-4859-8811-b58af2dd88a0\r\nTimestamp: 2020-10-07 07:17:03Z","error_codes":[70002],"timestamp":"2020-10-07 07:17:03Z","trace_id":"8fa93464-beb6-4e98-8705-af7617f20d00","correlation_id":"a269eb23-1879-4859-8811-b58af2dd88a0","error_uri":"https://login.microsoftonline.com/error?code=70002"}
        Headers: Cache-Control: no-store, no-cache
Pragma: no-cache
Strict-Transport-Security: max-age=31536000; includeSubDomains
X-Content-Type-Options: nosniff
P3P: CP="DSP CUR OTPi IND OTRi ONL FIN"
client-request-id: a269eb23-1879-4859-8811-b58af2dd88a0
x-ms-request-id: 8fa93464-beb6-4e98-8705-af7617f20d00
x-ms-ests-server: 2.1.11086.7 - DUB1 ProdSlices
x-ms-clitelem: 1,70002,0,15681949.0286,
Set-Cookie: fpc=AqNNOvVigMxOrdoogpdMd3Gy_7xbAQAAAG9iD9cOAAAA; expires=Fri, 06-Nov-2020 07:17:03 GMT; path=/; secure; HttpOnly; SameSite=None,x-ms-gateway-slice=prod; path=/; secure; samesite=none; httponly,stsservicecookie=ests; path=/; secure; samesite=none; httponly
Date: Wed, 07 Oct 2020 07:17:02 GMT

   --- End of inner exception stack trace ---
   at Azure.Identity.CredentialDiagnosticScope.FailWrapAndThrow(Exception ex)
   at Azure.Identity.SharedTokenCacheCredential.GetTokenImplAsync(Boolean async, TokenRequestContext requestContext, CancellationToken cancellationToken)
   at Azure.Identity.SharedTokenCacheCredential.GetTokenAsync(TokenRequestContext requestContext, CancellationToken cancellationToken)
   at Azure.Identity.DefaultAzureCredential.GetTokenFromSourcesAsync(TokenCredential[] sources, TokenRequestContext requestContext, Boolean async, CancellationToken cancellationToken)
   at Azure.Identity.DefaultAzureCredential.GetTokenImplAsync(Boolean async, TokenRequestContext requestContext, CancellationToken cancellationToken)
   at Azure.Identity.CredentialDiagnosticScope.FailWrapAndThrow(Exception ex)
   at Azure.Identity.DefaultAzureCredential.GetTokenImplAsync(Boolean async, TokenRequestContext requestContext, CancellationToken cancellationToken)
   at Azure.Identity.DefaultAzureCredential.GetTokenAsync(TokenRequestContext requestContext, CancellationToken cancellationToken)
   at Azure.Security.KeyVault.ChallengeBasedAuthenticationPolicy.AuthenticateRequestAsync(HttpMessage message, Boolean async, AuthenticationChallenge challenge)
   at Azure.Security.KeyVault.ChallengeBasedAuthenticationPolicy.ProcessCoreAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
   at Azure.Core.Pipeline.RetryPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
   at Azure.Core.Pipeline.RetryPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
   at Azure.Core.Pipeline.HttpPipelineSynchronousPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline)
   at Azure.Core.Pipeline.HttpPipelineSynchronousPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline)
   at Azure.Core.Pipeline.HttpPipelineSynchronousPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline)
   at Azure.Core.Pipeline.HttpPipeline.SendRequestAsync(Request request, CancellationToken cancellationToken)
   at Azure.Security.KeyVault.KeyVaultPipeline.SendRequestAsync(Request request, CancellationToken cancellationToken)
   at Azure.Security.KeyVault.KeyVaultPipeline.SendRequestAsync[TResult](RequestMethod method, Func`1 resultFactory, CancellationToken cancellationToken, String[] path)
   at Azure.Security.KeyVault.Secrets.SecretClient.GetSecretAsync(String name, String version, CancellationToken cancellationToken)
   at Program.<Main>(String[] args)
```

**To Reproduce**
Just use this sample
https://docs.microsoft.com/en-us/azure/key-vault/secrets/quick-create-net
without any additional environment variables from 
https://docs.microsoft.com/en-us/dotnet/api/azure.identity.environmentcredential?view=azure-dotnet 
(AZURE_CLIENT_ID, AZURE_CLIENT_SECRET and etc)

**Environment:**
    <PackageReference Include="Azure.Identity" Version="1.2.3" />
    <PackageReference Include="Azure.Security.KeyVault.Keys" Version="4.1.0" />
    <PackageReference Include="Azure.Security.KeyVault.Secrets" Version="4.1.0" />

dotnet info:
 Version:   3.1.403
 Commit:    9e895200cd

Environment:
 OS Name:     Windows
 OS Version:  10.0.19041
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.403\

Host (useful for support):
  Version: 3.1.9
  Commit:  774fc3d6a9

VisualStudioVersion = 16.0.30503.244

**Comment by jsquire** [comment] 2020-10-27 14:30
@schaabs:  Not quite sure if this roots to something in Identity or KeyVault.   Do you mind taking a look and passing off, if needed?

//fyi:  @heaths

**Comment by jsquire** [comment] 2020-10-27 14:30
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by schaabs** [comment] 2020-10-27 17:24
@andrewtsw Thanks for filing this issue. I believe the issue you're running into is an issue with the `SharedTokenCacheCredential` and MSA accounts, i.e. `@hotmail.com`, `@live.com`, `@outlook.com` accounts. To work around it could you try setting the `ExcludeSharedTokenCacheCredential` option to true when constructing the `DefaultAzureCredential`.
```c#
var cred = new DefaultAzureCredential(credFactory, new DefaultAzureCredentialOptions { ExcludeSharedTokenCacheCredential = true });
```
We are currently investigating other mitigations for this issue, and will hopefully have a fix by our next release. Please let me know if you have any trouble with this workaround in the meantime.

**Comment by LayAlex** [comment] 2020-10-28 08:37
I'm working with @andrewtsw . So I've tried your recommendation `ExcludeSharedTokenCacheCredential = true` but we are still facing the issue. 

Our console app is intended to get secrets from KeyVault. 
So when I try to get secrets from 'cmd.exe' It works fine. `az keyvault secret show ...`
When I run our console app using `az login` and with following initialization:

```
new DefaultAzureCredential(new DefaultAzureCredentialOptions 
        {           
            ExcludeSharedTokenCacheCredential = true,
            ExcludeEnvironmentCredential = true,
            ExcludeVisualStudioCodeCredential = true,
            ExcludeVisualStudioCredential = true
        });
```

I get an exception:

```
Unhandled exception. Azure.Identity.AuthenticationFailedException: Azure CLI authentication timed out.
   at Azure.Identity.AzureCliCredential.RequestCliAccessTokenAsync(Boolean async, String[] scopes, CancellationToken cancellationToken)
   at Azure.Identity.AzureCliCredential.GetTokenImplAsync(Boolean async, TokenRequestContext requestContext, CancellationToken cancellationToken)
   at Azure.Identity.CredentialDiagnosticScope.FailWrapAndThrow(Exception ex)
   at Azure.Identity.AzureCliCredential.GetTokenImplAsync(Boolean async, TokenRequestContext requestContext, CancellationToken cancellationToken)
   at Azure.Identity.AzureCliCredential.GetTokenAsync(TokenRequestContext requestContext, CancellationToken cancellationToken)
   at Azure.Identity.DefaultAzureCredential.GetTokenFromSourcesAsync(TokenCredential[] sources, TokenRequestContext requestContext, Boolean async, CancellationToken cancellationToken)
   at Azure.Identity.DefaultAzureCredential.GetTokenImplAsync(Boolean async, TokenRequestContext requestContext, CancellationToken cancellationToken)
   at Azure.Identity.CredentialDiagnosticScope.FailWrapAndThrow(Exception ex)
   at Azure.Identity.DefaultAzureCredential.GetTokenImplAsync(Boolean async, TokenRequestContext requestContext, CancellationToken cancellationToken)
   at Azure.Identity.DefaultAzureCredential.GetTokenAsync(TokenRequestContext requestContext, CancellationToken cancellationToken)
   at Azure.Security.KeyVault.ChallengeBasedAuthenticationPolicy.AuthenticateRequestAsync(HttpMessage message, Boolean async, AuthenticationChallenge challenge)
   at Azure.Security.KeyVault.ChallengeBasedAuthenticationPolicy.ProcessCoreAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
   at Azure.Core.Pipeline.RetryPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
   at Azure.Core.Pipeline.RetryPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
   at Azure.Core.Pipeline.HttpPipelineSynchronousPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline)
   at Azure.Core.Pipeline.HttpPipelineSynchronousPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline)
   at Azure.Core.Pipeline.HttpPipelineSynchronousPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline)
   at Azure.Core.Pipeline.HttpPipeline.SendRequestAsync(Request request, CancellationToken cancellationToken)
   at Azure.Security.KeyVault.KeyVaultPipeline.SendRequestAsync(Request request, CancellationToken cancellationToken)
   at Azure.Security.KeyVault.KeyVaultPipeline.SendRequestAsync[TResult](RequestMethod method, Func`1 resultFactory, CancellationToken cancellationToken, String[] path)
   at Azure.Security.KeyVault.Secrets.SecretClient.GetSecretAsync(String name, String version, CancellationToken cancellationToken)
```

P.S: No environment variables specified. Azure CLI installed.

**Comment by schaabs** [comment] 2020-11-09 18:22
@LayAlex and @andrewtsw  sorry you're continuing to have trouble with this. Unfortunately you have hit a separate bug in this case where the `AzureCliCredential` times out when the token output from the CLI is exceptionally long, https://github.com/Azure/azure-sdk-for-net/issues/14691. This issue has been fixed and the fix will be released in the next couple of weeks in the Azure.Identity 1.3.0 GA release. At that time the workaround I suggested should work for you.

To give more information on the orignal issue you were hitting, the underlying issue here is that MSA accounts which are authenticated via Visual Studio fail to authenticate with the `SharedTokenCacheCredential`. This is because Visual Studio authenticates MSA accounts via the MSA passthrough tenant, a tenant legacy applications used to authenticate MSA accounts prior to the "common" tenant being added. However when the `SharedTokenCacheCredential` attempts to authenticate these accounts it defaults to authenticating them in their home tenant which fails. Unfortunately there is no good way for the `SharedTokenCacheCredential` to identify this scenario and properly authenticate MSA accounts in this case.

For this reason we have decided to disable the `SharedTokenCacheCredential` by default in the `DefaultAzureCredential` so it will authenticate properly via the `VisualStudioCredential`. This basically makes the workaround I specified above the default behavior. Because this is will be a behavioral breaking change, albeit a very minor one with no impact for most users, we want to preview the change to insure we've had ample time to receive feedback and assess the full impact. We plan to release this change after our 1.3.0 GA release in 1.4.0-beta.2 by mid January. Customers impacted by this issue can still use the workaround described above in the meantime, and can upgrade with or without removing this workaround once the fix is released.

**Comment by 928PJY** [comment] 2020-11-23 01:43
@schaabs our user has run into the same error after we upgrade to `Azure.Identity#1.3.0`. Any idea about that?

```
Azure.Identity.AuthenticationFailedException: Azure CLI authentication timed out.
   at Azure.Identity.AzureCliCredential.RequestCliAccessTokenAsync(Boolean async, String[] scopes, CancellationToken cancellationToken)
   at Azure.Identity.AzureCliCredential.GetTokenImplAsync(Boolean async, TokenRequestContext requestContext, CancellationToken cancellationToken)
   at Azure.Identity.CredentialDiagnosticScope.FailWrapAndThrow(Exception ex)
   at Azure.Identity.AzureCliCredential.GetTokenImplAsync(Boolean async, TokenRequestContext requestContext, CancellationToken cancellationToken)
   at Azure.Identity.AzureCliCredential.GetTokenAsync(TokenRequestContext requestContext, CancellationToken cancellationToken)
   at Azure.Identity.DefaultAzureCredential.GetTokenFromSourcesAsync(TokenCredential[] sources, TokenRequestContext requestContext, Boolean async, CancellationToken cancellationToken)
   at Azure.Identity.DefaultAzureCredential.GetTokenImplAsync(Boolean async, TokenRequestContext requestContext, CancellationToken cancellationToken)
   at Azure.Identity.CredentialDiagnosticScope.FailWrapAndThrow(Exception ex)
   at Azure.Identity.DefaultAzureCredential.GetTokenImplAsync(Boolean async, TokenRequestContext requestContext, CancellationToken cancellationToken)
   at Azure.Identity.DefaultAzureCredential.GetTokenAsync(TokenRequestContext requestContext, CancellationToken cancellationToken)
   at Azure.Security.KeyVault.ChallengeBasedAuthenticationPolicy.AuthenticateRequestAsync(HttpMessage message, Boolean async, AuthenticationChallenge challenge)
   at Azure.Security.KeyVault.ChallengeBasedAuthenticationPolicy.ProcessCoreAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
   at Azure.Core.Pipeline.RetryPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
   at Azure.Core.Pipeline.RetryPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
   at Azure.Core.Pipeline.HttpPipelineSynchronousPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline)
   at Azure.Core.Pipeline.HttpPipelineSynchronousPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline)
   at Azure.Core.Pipeline.HttpPipelineSynchronousPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline)
   at Azure.Core.Pipeline.HttpPipeline.SendRequestAsync(Request request, CancellationToken cancellationToken)
   at Azure.Security.KeyVault.KeyVaultPipeline.SendRequestAsync(Request request, CancellationToken cancellationToken)
   at Azure.Security.KeyVault.KeyVaultPipeline.SendRequestAsync[TResult](RequestMethod method, Func`1 resultFactory, CancellationToken cancellationToken, String[] path)
   at Azure.Security.KeyVault.Secrets.SecretClient.GetSecretAsync(String name, String version, CancellationToken cancellationToken)
   at Microsoft.Docs.Build.OpsAccessor.GetSecret(String secret) in D:\a\1\s\src\docfx\config\ops\OpsAccessor.cs:line 314
   at Microsoft.Docs.Build.OpsAccessor.FillOpsToken(String url, HttpRequestMessage request, Nullable`1 environment) in D:\a\1\s\src\docfx\config\ops\OpsAccessor.cs:line 348
```

**Comment by christothes** [comment] 2021-02-18 20:42
@928PJY In the most recent Azure.Identity 1.4.0-beta.3 we increased the CLI process timeout a bit, to help mitigate this issue. Can you test if the problem reproduces for you on that version? If not, how long does it take for you to run the following CLI command in the environment where the issue occurs?

`az account get-access-token --output json --resource https://vault.azure.net`

**Closed** 2021-03-17 14:04 UTC
Labels: Azure.Identity, Client, bug, customer-reported, needs-author-feedback, no-recent-activity
