### ISSUE TITLE
[QUERY] How to migrate to .NET 6 given I ran across an AMQP limitation?

### ISSUE THREAD

**Issue by dzendras** [Azure/azure-sdk-for-net#34205] opened 2023-02-16 06:56 UTC
### Library name and version

Azure.Messaging.ServiceBus 7.12.0

### Query/Question

We have a WebAPI application that targets .NET 4.8 and uses WindowsAzure.ServiceBus. One of the app's core functionalities is to PeekLock a message within the first API call and then complete it within **another** (Complete) API call. You can think of the app as the gateway for a subset of Azure ServiceBus. We do not want our customers to have direct access to Azure Service Bus, hence we created an API that adds extra authorization, logging, throttling, business validation etc.
The app is hosted in Azure and is configured to scale out dynamically, so inherently there is more than one instance of the API running. Even if there was only single instance running, during deployment, it might happen that PeekLock call is made against the "old" instance and Complete against the newly deployed one.
We currently rely on Service Bus Messaging Protocol (SBMP) which supports our PeekLock/Complete scenario just fine. However, our Product Owner asked us to migrate to .NET 6. I have tried migrating our code to use the latest Azure.Messaging.ServiceBus as WindowsAzure.ServiceBus does not target .NET Core/NET 5+.  It seems that I have run across a showstopper described in the [issue](https://github.com/Azure/azure-sdk-for-net/issues/8291).

Since Microsoft decided to drop support for SBMP in the latest SDK, what are our options? 

### Environment

.NET 4.8 & WindowsAzure.ServiceBus 3.3.2
willing to migrate to .NET 6

**Comment by jsquire** [comment] 2023-02-16 14:19
Hi @dzendras.   Thank you for reaching out and we regret that you're experiencing difficulties.  It is not possible to receive a message from one instance and complete it in another.  Service Bus requires that a message be completed on the same link from which it was received.  This is a service limitation and not something that the client has influence over or can work around.  The Service Bus team has acknowledged this limitation and confirmed it is by design.  _(see: [#455](https://github.com/Azure/azure-service-bus/issues/455))_

Unfortunately, this repository is focused on the Azure SDK for .NET - we're unable to assist with other Azure issues.  Since what you're describing is a service behavior and not related to the SDK, your best path forward would be to [share your Service Bus feedback](https://feedback.azure.com/d365community/forum/7c0a897d-2125-ec11-b6e6-000d3a4f0f84) or [open an Azure support request](https://docs.microsoft.com/azure/azure-portal/supportability/how-to-create-azure-support-request).

I'm going to close this out; if I've misunderstood what you're describing, please let us know in a comment and we'd be happy to assist as we're able.

**Closed** 2023-02-16 14:19 UTC
Labels: Service Bus, Client, customer-reported, question, issue-addressed

**Comment by dzendras** [comment] 2023-02-16 14:46
Hi @jsquire. Thank you for the quick reply.
I understand the AMQP limitation. I do not understand why Azure SDK for .NET dropped support for SBMP, leaving clients like me stuck on .NET 4.8, effectively. I am sure that the decision was well thought of, so I would like to learn what the Team suggests in such scenario.
Our product was designed a few years ago with specific capabilities in mind, which are unavailable if we want to keep track with the latest .NET solutions. On one hand, Microsoft gradually obsoletes .NET Framework (e.g. .NET Standard 2.1 not supported), encouraging people to migrate to the latest .NET Core/5+. On the other hand, removes capabilities from .NET Core/5+ SDK leaving its customers in quasi-legacy mode.
I am sorry if you felt like I wanted to ask you for an Azure architecture advice. I just showed you a valid, quite straightforward scenario that uses Microsoft's infrastructure which cannot be implemented using the new SDK.

I believe that the issue can be solved purely by the Azure .NET SDK Team.

**Comment by dzendras** [comment] 2023-02-16 17:31
Thank you for the quick and accurate response, @jsquire ! 
I appreciate the explanation. I know my situation now and can think of potential workarounds.
