### ISSUE TITLE
Consolidate SystemAssignedServiceIdentity into ManagedServiceIdentity in common types of ResourceManager

### ISSUE THREAD

**Issue by fengzhou-msft** [Azure/azure-sdk-for-net#29792] opened 2022-07-12 02:58 UTC
`ManagedServiceIdentity` is a superset of `SystemAssignedServiceIdentity` with an additional optional property `UsersAssignedIdentities`, and more values in the identity type. We can use `ManagedServiceIdentity` to replace the `SystemAssignedServiceIdentity` model in an RP with `UsersAssignedIdentities` always being null for that RP and some of the identity types being invalid (we can make up for this through the right documentation). This would avoid breaking changes in client side when service adds support for user assigned identities on the original SystemAssignedServiceIdentity-like model.

We can then make `SystemAssignedServiceIdentity` EditorBrowsableNever.

**Comment by ArthurMa1978** [comment] 2022-07-15 03:31
The root cause here is from `Azure.Core`, which the `PropertyReferenceTypeAttribute` only using type comparing for skip properties which is incorrect.
Here if fix it from root we need to take very long process, but currently we have tight time box to release new SDKs, so we're going to unblock the sdk release, we will fix this issue by following steps:
1. As the `Azure.ResourceManager.CosmosDB` and `Azure.ResourceManager.WebPubSub` will be released next week, so using customization code to fix them.  https://github.com/Azure/azure-sdk-for-net/pull/29918
2. Change the matching logic in AutoRest.CSharp which is a workaround that can correct the type replacement for `ManagedServiceIdentity` without the `Azure.Core` change, full test and make sure there is no side effect. Then use this new AzutoRest.CSharp to refresh all bath 3 & 4 RPs, correct the type replacement without customization code.
3. Fix the  `PropertyReferenceTypeAttribute` in `Azure.Core`.
4. After new `Azure.Core` released, 
      1). Upgrade the `ManagedServiceIdentity` in `Azure.ResourceManager` which will add `OptionalProperties` properties, release it.
      2). Revert the Step 2 workaround in AutoRest.CSharp.
      3). Refresh all RPs, must have no API changes

**Closed** 2022-08-11 03:55 UTC
Labels: ARM, Client
