### ISSUE TITLE
Linux leg timing out on EventHubs tests

### ISSUE THREAD

**Issue by weshaggard** [Azure/azure-sdk-for-net#8618] opened 2019-11-05 01:11 UTC
For a number of recent runs:

https://dev.azure.com/azure-sdk/public/_build/results?buildId=173892&view=results
https://dev.azure.com/azure-sdk/public/_build/results?buildId=161855&view=results
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=168850&view=logs&s=6884a131-87da-5381-61f3-d7acc3b91d76
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=160314&view=logs&j=ad07b744-5a1a-5d54-7693-fcb02e666633

It looks like at least some set of tests are ran but the process seems to hang after reporting results. I don't know if this is an issue with dotnet or something in the eventhubs test code on linux.

**Comment by pakrym** [comment] 2019-11-05 01:15
Is it a dup of https://github.com/Azure/azure-sdk-for-net/issues/7634?

**Comment by jsquire** [comment] 2019-11-05 14:14
I can't say for sure, but I strongly suspect that the root cause is some bit of non-determinism in the load balancing area of the Event Processor tests; we're working to track that down as time allows but it has proven difficult to reproduce.  I've never seen it outside of Linux, but I have seen it once or twice locally when running tests in a tight loop.

That said, we're also doing almost a complete rewrite of that area under a new design so I don't want to spend much resource time on dead code. Please bear with things as we push over the next couple of weeks. I expect anything Event Hubs related to be fixed before GA.

**Comment by kurtzeborn** [comment] 2019-11-21 17:56
Assigning this and #7634 to you @jsquire for follow up.  If the redesign makes these go away, please close.

**Comment by jsquire** [comment] 2019-11-21 18:01
Closed #7634 as a duplicate, as both are believe to be referring to the same issue and same suspected root cause.    Will evaluate this once the implementation of the recent changes have been completed.

**Comment by jsquire** [comment] 2020-01-02 21:34
I believe that the recent redesign and refactoring will have resolved this, if it was a code problem.  I have not seen it manifest in the last 30-60 days and we've reviewed and ensured that all tests are using a timed cancellation token to guard against hangs.   

Closing this out; please reopen if you see the issue occur again.

**Closed by jsquire** 2020-01-02 21:34 UTC
Labels: Bug, Client, Event Hubs
