### ISSUE TITLE
Duplicate H1s Conflict for microsoft.core.spatial.newtonsoftjson-readme

### ISSUE THREAD

**Issue by v-alje** [Azure/azure-sdk-for-net#29203] opened 2022-06-08 21:48 UTC
The following articles created from readme files are using the same H1 title header. Docs reports warnings when there are two articles with the same H1 text. This is happening because both the preview and release versions of the Docs articles were imported from the same readme: sdk/core/Microsoft.Azure.Core.Spatial.NewtonsoftJson/README.md

https://github.com/Azure/azure-docs-sdk-dotnet/blob/main/api/overview/azure/microsoft.azure.core.spatial.newtonsoftjson-readme-pre.md
https://github.com/Azure/azure-docs-sdk-dotnet/blob/main/api/overview/azure/microsoft.core.spatial.newtonsoftjson-readme-pre.md
https://github.com/Azure/azure-docs-sdk-dotnet/blob/main/api/overview/azure/microsoft.core.spatial.newtonsoftjson-readme.md

Part of a possible solution would be to append something like (Preview) to the end of the H1 for the preview topic when imported to Docs. The third topic H1 needs to be modified to be unique in some other way.

**Comment by jsquire** [comment] 2022-06-09 13:54
Closing as a duplicate of #29199

**Comment by sima-zhu** [comment] 2022-06-10 16:41
Seems like the preview readmes are duplicate. Change readme file content since it is currently linked nowhere

**Closed by sima-zhu** 2022-06-10 16:41 UTC
Labels: Docs, Central-EngSys
