### ISSUE TITLE
[BUG] CultureNotFoundException: Only the invariant culture is supported in globalization-invariant mode

### ISSUE THREAD

**Issue by NirAvailo** [Azure/azure-sdk-for-net#45149] opened 2024-07-23 16:36 UTC
### Library name and version

Azure.Storage.Blobs 12.21.0

### Describe the bug

**Got an exception when trying to upload a content into a blob**
```
InvalidOperationException: Failed to compare two elements in the array. TypeInitializationException: The type initializer for 'Azure.Storage.StorageSharedKeyPipelinePolicy' threw an exception. CultureNotFoundException: Only the invariant culture is supported in globalization-invariant mode. See https://aka.ms/GlobalizationInvariantMode for more information. (Parameter 'name')\nen-US is an invalid culture identifier.
```
I tried to resolve this problem by setting InvariantGlobalization to false in the project file, however, the AKS did not accept it.

### Expected behavior

This error does not happen with Azure.Storage.Blobs version 12.20.0

### Actual behavior

The service get an exception when uploading the content

### Reproduction Steps

`blob = new BlockBlobClient(connectionString, containerName, blobName);`

NOTE:
relevant change is in sdk/storage/Azure.Storage.Common/src/Shared/StorageSharedKeyPipelinePolicy.cs in commit b99cccb

[/sdk/storage/Azure.Storage.Common/src/Shared/StorageSharedKeyPipelinePolicy.cs](https://github.com/Azure/azure-sdk-for-net/blob/b99cccbbe4cd5178bf97a2283138570c2bbd5353/sdk/storage/Azure.Storage.Common/src/Shared/StorageSharedKeyPipelinePolicy.cs#L28)

### Environment

AKS Linux pod 
dotNet6.0

**Comment by seanmcc-msft** [comment] 2024-07-24 17:47
Duplicate of https://github.com/Azure/azure-sdk-for-net/issues/45052

**Closed by seanmcc-msft** 2024-07-24 17:47 UTC
Labels: Storage, Service Attention, Client, customer-reported, question, needs-team-attention
