### ISSUE TITLE
Azure.ResourceManager.Compute System.NotImplemented Exception when starting, stopping or deleting VM

### ISSUE THREAD

**Issue by chandrashekharazad** [Azure/azure-sdk-for-net#31851] opened 2022-10-17 23:07 UTC
### Library name and version

Azure.ResourceManager.Compute

### Describe the bug

Hi,

I am using the following NuGet package "Azure.ResourceManager.Compute" to start, stop and delete VM in Azure.

https://www.nuget.org/packages/Azure.ResourceManager.Compute/1.0.0.

When I run this service I am receiving the following error "Azure.ResourceManager System.NotImplementedException: The method or operation is not implemented."

After running. VM doesn't start or complete and it seems the stop or start operation is returned back without completing the task.

### Expected behavior

To stop, stop or delete VM

### Actual behavior

Returns System.NotImplemented Exception

### Reproduction Steps

public async Task<ArmOperation> StartVM(string vmName)
     {
         ArmClient client = new ArmClient(new DefaultAzureCredential());
         string resourceGroupName = "vm003";
         SubscriptionResource subscription = await client.GetDefaultSubscriptionAsync();
         ResourceGroupCollection resourceGroups = subscription.GetResourceGroups();
         ResourceGroupResource resourceGroup = await resourceGroups.GetAsync(resourceGroupName);
         var vm = resourceGroup.GetVirtualMachine(vmName);
         var result = await vm.Value.PowerOnAsync(WaitUntil.Started);
         return result;
     }
     [HttpPost("StopVM")]
     public async Task<ArmOperation> StopVM(string vmName)
     {
         ArmClient client = new ArmClient(new DefaultAzureCredential());
         string resourceGroupName = "vm003";
         SubscriptionResource subscription = await client.GetDefaultSubscriptionAsync();
         ResourceGroupCollection resourceGroups = subscription.GetResourceGroups();
         ResourceGroupResource resourceGroup = await resourceGroups.GetAsync(resourceGroupName);
         var vm = resourceGroup.GetVirtualMachine(vmName);
         var result = await vm.Value.PowerOffAsync(WaitUntil.Completed);
         return result;
     }
     [HttpPost("DeleteVM")]
     public async Task<ArmOperation> DeleteVM(string vmName)
     {
         ArmClient client = new ArmClient(new DefaultAzureCredential());
         string resourceGroupName = "vm003";
         SubscriptionResource subscription = await client.GetDefaultSubscriptionAsync();
         ResourceGroupCollection resourceGroups = subscription.GetResourceGroups();
         ResourceGroupResource resourceGroup = await resourceGroups.GetAsync(resourceGroupName);
         var vm = resourceGroup.GetVirtualMachine(vmName);
         var result = await vm.Value.DeleteAsync(WaitUntil.Completed);
         return result;
     }

### Environment

OS: Windows 11 Pro.
.Net 6
Visual studio 2022

**Comment by ArcturusZhang** [comment] 2022-11-30 09:20
Assigned this to @fengzhou-msft since this is caused by the `ArmOperation<T>.Id` which will be resolved by the rehydration feature.

Long story short, the `ArmOperation<T>` classes represents an on-going operation which is not suitable to be serialized or passed around between different methods right now. The exception is thrown when accessing the `Id` property, we did not implement that yet. We are working on a feature called `rehydration` which allows you to serialize and deserialize the `ArmOperation` classes to resume the progress of an on-going long-running operation.

But currently for workaround, please avoid to use ArmOperation as return values, especially your framework will try to serialize the return values of methods.

**Comment by fengzhou-msft** [comment] 2023-01-18 12:42
We track the LRO rehydration feature in https://github.com/Azure/autorest.csharp/issues/2158

**Comment by live1206** [comment] 2023-05-22 05:26
This will be resolved in https://github.com/Azure/autorest.csharp/issues/2158, close as duplicated.

**Closed by live1206** 2023-05-22 05:26 UTC
Labels: Compute, Mgmt, customer-reported, question
