### ISSUE TITLE
[BUG] VisualStudioCodeCredential is not returning the correct permissions

### ISSUE THREAD

**Issue by andrew-sumner** [Azure/azure-sdk-for-net#26011] opened 2021-12-20 05:12 UTC
### Library name and version

Azure.Identity 1.5.0

### Describe the bug

I've been migrating from the old AzureServiceTokenProvider and found that I cannot query AD Groups using Graph under visual studio any more as I get this error `Code: Authorization_RequestDenied Message: Insufficient privileges to complete the operation`.

I tracked it down to the VisualStudioCodeCredential provider not returning the scopes I expected. I would have expected the VisualStudioCodeCredential and AzureCliCredential providers to return the same scopes as they're both using the same account to authenticate.

How do I get the VisualStudioCodeCredential provider to return the same scopes as the AzureCliCredential provider?

**VisualStudioCodeCredential**
```
"app_displayname": "Visual Studio",
"appid": "872cd9fa-d31f-45e0-9eab-6e460a02d1f1",
"scp": "Application.ReadWrite.All email openid profile User.ReadWrite.All",
```

**AzureCliCredential**
```
"app_displayname": "Microsoft Azure CLI",
"appid": "04b07795-8ddb-461a-bbee-02f9e1bf7b46",
"scp": "AuditLog.Read.All Directory.AccessAsUser.All Group.ReadWrite.All User.ReadWrite.All",
```

**Code**
```
var serviceClient = new GraphServiceClient(GetManagedIdentityAuthProvider(runAsIdentityId));

private static DelegateAuthenticationProvider GetManagedIdentityAuthProvider(string runAsIdentityId)
{
    DefaultAzureCredentialOptions option = null;

    if (runAsIdentityId != null)
    {
        option = new DefaultAzureCredentialOptions
        {
            ManagedIdentityClientId = runAsIdentityId,
        };
    }

    var credential = new DefaultAzureCredential(option);
    var token = credential.GetToken(new TokenRequestContext(scopes: new[] { "https://graph.microsoft.com/.default" }));
    var accessToken = token.Token;
    
    var authProvider = new DelegateAuthenticationProvider((requestMessage) =>
        {
            requestMessage
            .Headers
            .Authorization = new AuthenticationHeaderValue("bearer", accessToken);

            return Task.CompletedTask;
        });
    
    return authProvider;
}
```
 

### Expected behavior

I would have expected the VisualStudioCodeCredential and AzureCliCredential providers to return the same scopes.

### Actual behavior

No idea where VisualStudioCodeCredential gets the scopes from.

### Reproduction Steps

Execute above code in visual studio and inspect the token.

### Environment

Visual Studio Version 17.0.4

dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.101
 Commit:    ef49f6213a

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.101\

Host (useful for support):
  Version: 6.0.1
  Commit:  3a25a7f1cc

.NET SDKs installed:
  5.0.404 [C:\Program Files\dotnet\sdk]
  6.0.101 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by jsquire** [comment] 2021-12-20 13:53
Thank you for your feedback.  Tagging and routing to the team members best able to assist.

**Comment by christothes** [comment] 2022-01-03 16:03
Hi @andrew-sumner - This same question was asked and discussed in https://github.com/Azure/azure-sdk-for-net/issues/25400 .

**Comment by andrew-sumner** [comment] 2022-01-05 01:05
/unresolve

I didn't see an actual answer, or solution, to my issue in the linked issue #25400.

The issue as I see it: 

- When running from Visual Studio the Azure.Identity AzureCliCredential and VisualStudioCodeCredential providers returns a different set of permissions, with the VisualStudioCodeCredential being more restrictive.

- After migrating from the older AzureServiceTokenProvider to the VisualStudioCodeCredential provider I can no longer execute my code within Visual Studio as I no longer have the permissions to query things I could before (unless I disable VisualStudioCodeCredential and use AzureCliCredential).

_I believe this to be a bug in the behaviour of the VisualStudioCodeCredential and it should work exactly the same as AzureCliCredential._ 

I'd like to know:

1. Can you please explain why the two credential providers return a different set of permissions for the same account?

2. If the VisualStudioCodeCredential provider is working as intended, how are we meant to request the required permissions when executing code in Visual Studio (e.g. Group.Read.All)?

**Comment by christothes** [comment] 2022-01-05 17:38
> _I believe this to be a bug in the behaviour of the VisualStudioCodeCredential and it should work exactly the same as AzureCliCredential._

This is not a bug, it is a reflection of the permissions assigned to the client application used by these various credentials.

> I'd like to know:
> 
> 1. Can you please explain why the two credential providers return a different set of permissions for the same account?

The permissions (scopes) that are returned when a token is requested is related to the permissions consent granted to the client application. [This reference](https://docs.microsoft.com/en-us/graph/security-authorization) explains some of the context. From the page:

"The Azure AD tenant admin must explicitly grant consent to your application. This is required both for application-level authorization and user delegated authorization."

The reason the two credentials are different is because they are using different client application IDs, each having different permissions granted to them. Azure CLI uses application Id 04b07795-8ddb-461a-bbee-02f9e1bf7b46 (a list of first party applications can be found [here](https://docs.microsoft.com/en-us/troubleshoot/azure/active-directory/verify-first-party-apps-sign-in#application-ids-for-commonly-used-microsoft-applications)) and Visual Studio Code uses the application Id aebc6443-996d-45c2-90f0-388ff96faa56. 

> 2. If the VisualStudioCodeCredential provider is working as intended, how are we meant to request the required permissions when executing code in Visual Studio (e.g. Group.Read.All)?

The Graph API is very special in how its permissions work and these credential types use application Ids that have very constrained Graph permissions. In order to control these permissions, you'll need to use a credential where you control which application is being used, such as `EnvironmentCredential` or `InteractiveBrowserCredential`.

**Comment by andrew-sumner** [comment] 2022-01-06 22:25
/unresolve

Is there any reason you cannot grant the Visual Studio App the same rights as the Azure CLI app?

While technically the current behaviour is not a bug as it is working as designed, there is a reduction in permissions so I'd at least classify it as a configuration issue. 

This behaviour makes migrating code from older AzureServiceTokenProvider to Azure.Indentity more painful than it needs to be as I can no longer debug my code in Visual Studio in the same why that I could previously.

**Comment by christothes** [comment] 2022-01-06 23:36
> /unresolve
> 
> Is there any reason you cannot grant the Visual Studio App the same rights as the Azure CLI app?

There are a few reasons - Firstly, the SDK doesn't control which permissions are assigned to those applications. Secondly, these applications are intentionally restricted for security reasons.

The only way to control the Graph API permissions assigned is to control the AAD application being used.

> This behaviour makes migrating code from older AzureServiceTokenProvider to Azure.Indentity more painful than it needs to be as I can no longer debug my code in Visual Studio in the same why that I could previously.

Sorry for this, but unfortunately, there is nothing that can be done within the scope of the credentials mentioned that can be done to improve this. 

Could you talk more about why your debugging is dependent on Visual Studio's credentials? Perhaps there is a viable workaround to this problem.

**Comment by andrew-sumner** [comment] 2022-01-07 00:33
Where ever possible the code we're using for authenticating against Azure resources uses managed identities so that we don't need to manage passwords. 

For debugging within Visual Studio, I have always relied on "VS > Tools > Options > Azure Service Authentication" setting to provide the identity.  The VS identity has worked perfectly for accessing key vault secrets and other azure resources, however after migrating to Azure.Identity this approach falls over when accessing the graph api. 

The only viable work around appears to be disabling the VisualStudioCodeCredential which I find disappointing as developers now need to authenticate outside of Visual Studio, whether that's via the Azure CLI or environment variables.

_I'm still at a loss as to why the Azure CLI and VS apps would give different permissions on the graph api._

**Comment by andrew-sumner** [comment] 2022-01-07 00:47
Expanding on this, when deployed into azure the graph api permissions are provided by a user assigned identity using the RunAs connection parameter. 

I've never tried that running via VS as it's always just worked. Might be worth trying out...

**Comment by andrew-sumner** [comment] 2022-01-07 03:49
Nope, VisualStudioCodeCredential doesn't support this :-(

**Comment by christothes** [comment] 2022-01-20 22:01
Closing as this is a limitation outside the control of the SDK.

**Closed by christothes** 2022-01-20 22:01 UTC
Labels: Client, Azure.Identity, customer-reported, question, needs-team-attention
