### ISSUE TITLE
[BUG] AppCertificateCollection.CreateOrUpdateAsync() throws ArgumentException because of keyVaultId being an empty string in response from Azure, not null

### ISSUE THREAD

**Issue by DanKuz7** [Azure/azure-sdk-for-net#32563] opened 2022-11-18 12:52 UTC
### Library name and version

Azure.ResourceManager.AppService (1.0.0)

### Describe the bug

`AppCertificateCollection.CreateOrUpdateAsync()` throws `ArgumentException` with stack trace:
```
   at Azure.Core.Argument.AssertNotNullOrEmpty(String value, String name)
   at Azure.Core.ResourceIdentifier..ctor(String resourceId)
   at Azure.ResourceManager.AppService.AppCertificateData.DeserializeAppCertificateData(JsonElement element)
   at Azure.ResourceManager.AppService.CertificatesRestOperations.<CreateOrUpdateAsync>d__15.MoveNext()
   at Azure.ResourceManager.AppService.AppCertificateCollection.<CreateOrUpdateAsync>d__5.MoveNext()
```

From my investigation, this error occurs as it tries to deserialize the response from Azure (because the certificate does get uploaded successfully).

I believe the cause is that the `Azure.ResourceManager.AppService.AppCertificateData.DeserializeAppCertificateData(JsonElement element)` method checks if an ID is null - if it is, it will skip to the next property - if it isn't it will create an instance of `ResourceIdentifier` with that ID passed in as a parameter, but the null check does not account for the possibility that the value might not be null and could just be an empty string - and when an empty string is passed in the constructor of `ResourceIdentifier`, it throws an exception.

The ID in particular that might be causing this is `keyVaultId`, as when I send a PUT request to `https://management.azure.com/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Web/certificates/{name}?api-version=2022-03-01` with JSON body:
```json
{
	"location":"UK South",
	"properties": {
		"serverFarmId":"<server farm id>",
                "password":"<pfx password>",
		"pfxBlob":"<pfx blob>"
	}
}
```
the response from Azure returns an empty string ("") for `keyVaultId` property in the JSON response, not null.

### Expected behavior

The `AppCertificateCollection.CreateOrUpdateAsync()` method should:

1. Send a PUT request to the Azure certificates API endpoint with the body from `AppCertificateData`
2. Return an `AppCertificateResource` object with the parsed data from a successful response

### Actual behavior

1. Sends a PUT request to the Azure certificates API endpoint with the body from `AppCertificateData`
2. Throws `ArgumentException` during the deserialization of the response with the stack trace: 
```
   at Azure.Core.Argument.AssertNotNullOrEmpty(String value, String name)
   at Azure.Core.ResourceIdentifier..ctor(String resourceId)
   at Azure.ResourceManager.AppService.AppCertificateData.DeserializeAppCertificateData(JsonElement element)
   at Azure.ResourceManager.AppService.CertificatesRestOperations.<CreateOrUpdateAsync>d__15.MoveNext()
   at Azure.ResourceManager.AppService.AppCertificateCollection.<CreateOrUpdateAsync>d__5.MoveNext()
```

_The certificate was uploaded successfully and shows up in the Azure Portal._

### Reproduction Steps

Send a request to create or update a certificate with these properties in `AppCertificateData` object:
```csharp
var certificates = resourceGroup.GetAppCertificates();
await certificates.CreateOrUpdateAsync(Azure.WaitUntil.Completed, "MyCertificateName", new AppCertificateData(AzureLocation.UKSouth)
{
    PfxBlob = Convert.FromBase64String("<pfx in base64>"),
    Password = "<pfx password>",
    ServerFarmId = new ResourceIdentifier($"<server farm id>")
});
```

Then the exception is thrown

### Environment

Windows 11 .NET 6 - Visual Studio 17.4.1

**Comment by jsquire** [comment] 2022-11-18 14:04
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by xboxeer** [comment] 2022-12-22 03:38
We already have an issue tracking this https://github.com/Azure/autorest.csharp/issues/2802

**Comment by fengzhou-msft** [comment] 2023-02-16 06:10
Duplicate of #31701

**Closed by fengzhou-msft** 2023-02-16 06:10 UTC
Labels: App Services, Mgmt, customer-reported, question, needs-team-attention
