### ISSUE TITLE
Cannot update Data Transparent Data Encryption State

### ISSUE THREAD

**Issue by mungdoan** [Azure/azure-sdk-for-net#33170] opened 2022-12-23 04:08 UTC
### Library name and version

Azure.ResourceManager.Sql 1.1.0

### Describe the bug

I am trying to update data transparent data encryption state from C# code. However, i can not update due to NullReferenceException thrown from inside package:
![image](https://user-images.githubusercontent.com/107232443/209268285-f81f47d4-0481-431a-a162-bd7eb51d019b.png)

My step is only getting it from azure resource and update state property to enable/disable it.

### Expected behavior

Can enable/disable data encryption

### Actual behavior

Throw NullReferenceException 

StackTrace:
   at Azure.ResourceManager.Sql.LogicalDatabaseTransparentDataEncryptionResource.<UpdateAsync>d__16.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()

### Reproduction Steps

1. Retrieve logicalDatabaseTransparentDataEncryption
2. set state = enable/disable
3. Call  logicalDatabaseTransparentDataEncryptionResource.UpdateAsync with data above: logicalDatabaseTransparentDataEncryption

### Environment

NET SDK (reflecting any global.json):
 Version:   6.0.300
 Commit:    8473146e7d

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19044
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.300\

Host (useful for support):
  Version: 6.0.5
  Commit:  70ae3df4a6

.NET SDKs installed:
  2.1.818 [C:\Program Files\dotnet\sdk]
  6.0.300 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by ArthurMa1978** [comment] 2022-12-23 10:25
Thank you for your feedback, we will check it.

**Comment by fengzhou-msft** [comment] 2023-01-18 12:39
The root cause of the issue is that in swagger definition of the [TransparentDataEncryptions_CreateOrUpdate](https://github.com/Azure/azure-rest-api-specs/blob/f3e7c1b20f032a637069d055524549b950830c22/specification/sql/resource-manager/Microsoft.Sql/preview/2021-02-01-preview/TransparentDataEncryptions.json#L82-L161) operation, it's not marked as an LRO (long running operation). Therefore, the SDK code generated based on the wrong swagger does not handle the response correctly. This should be fixed on the service swagger, then we can regenerate the SDK based on fixed swagger.

**Comment by v-bafa** [comment] 2023-02-08 04:15
Seeing same issue.

**Comment by live1206** [comment] 2023-05-29 06:59
As described in https://github.com/Azure/azure-sdk-for-net/issues/33170#issuecomment-1386991512, this needs the service team to fix the swagger.

**Closed** 2023-07-17 10:35 UTC
Labels: SQL, Service Attention, Mgmt, customer-reported, bug, issue-addressed

**Comment by live1206** [comment] 2023-08-03 02:54
SDK team can't do anything here, have created S360 for Sql team to follow up.
