### ISSUE TITLE
[BUG] Azure.Search.Documents V11.2 SDK for .NET

### ISSUE THREAD

**Issue by ssghoda** [Azure/azure-sdk-for-net#20276] opened 2021-04-09 21:05 UTC
Azure.Search.Documents V11.2 SDK for .NET is very different from deprecated Microsoft.Azure.Search SDK for .NET. Some of the differences I noticed are as follows:

- SearchAsync<T> returns Paged results, unlike the previous version which returned all results.
- SearchAsync<T> doesn't deserialize result into T appropriately unlike the previous version. For example, If there is an Azure Index field titled "id" and T has a property titled "Id" then it doesn't get deserialized.
- SearchOptions doesn't let us set properties for Select, SearchFields, OrderByFields, HighlightFields, Facets, ScoringParameters unlike in the previous version.

**Comment by jsquire** [comment] 2021-04-10 17:03
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by Mohit-Chakraborty** [comment] 2021-04-10 17:51
Hi, the client uses paged results to improve the performance of the search queries.

Regarding your 3rd point, collection properties are not settable directly. You set them by adding elements to the collection -
```
var searchOptions = new SearchOptions()
{
  QueryType = SearchQueryType.Full,
};
searchOptions.SearchFields.Add("Description");
searchOptions.SearchFields.Add("Category");
searchOptions.SearchFields.Add("Tags");
```

**Comment by ssghoda** [comment] 2021-04-10 20:19
Yes, but it would be tedious if someone has more Select fields, SearchFields, OrderByFields, HighLightFields, Facets, and so on. It would add more lines to the code. In the previous deprecated version of SDK, we could add many fields in one line itself using a set accessor. Such as follows:

```
var searchOptions = new SearchOptions()
{
  QueryType = SearchQueryType.Full,
  SearchFields = new List<string> { "searcheableField1", "searcheableField2", "searcheableField3" },
  Select = new List<string> { "selectField1", "selectField2", "selectField3", "selectField4", "selectField5", "selectField6", "selectField7", "selectField8", "selectField9", "selectField10" }
};
```

What are your thoughts regarding my 2nd point? SearchAsync doesn't deserialize result into T appropriately unlike the previous version. For example, If there is an Azure Index field titled "id" and T has a property titled "Id" then it doesn't get deserialized.

**Comment by Mohit-Chakraborty** [comment] 2021-04-11 00:53
I agree with you on the usability part. Thanks for your feedback.

For the 2nd point, if you know the index fields, you can [set the `JosnPropertyName` attribute](https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/search/Azure.Search.Documents#use-c-types-for-search-results) on the corresponding strongly typed property so the value gets deserialized properly.
If you don't know the index schema upfront, you can [use `SearchDocument`](https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/search/Azure.Search.Documents#use-searchdocument-like-a-dictionary-for-search-results) to get the properties like dictionary elements and use that to build the index if you so desire.

**Comment by ssghoda** [comment] 2021-04-12 13:32
For the 2nd point, yes I figured that out but my only point was that it was working in deprecated version of SDK without having to use Json attributes. So I was hoping if you were able to provide backward compatibility, a lot of people wouldn't need to add additional lines for serialization.

**Comment by jstclair** [comment] 2021-04-29 08:12
I think the problem is that `IList` /  `IList<T>` doesn't expose an `AddRange` -- otherwise, you could:

```csharp
searchOptions.SearchFields.AddRange(new [] { "field1", "field2", "field3"));
```

**Comment by ssghoda** [comment] 2021-04-29 14:40
Yes, but in the previous versions of this API, all these IList properties such as SearchFields, Select, HighlightFields had a set accessor which is why we were able to assign a list of values in one go. In this version of API, that set accessor has been removed which makes it hard to assign a list of values in one go. It would help a lot if a set accessor is added back again.

**Comment by Mohit-Chakraborty** [comment] 2021-04-29 19:42
Yes, usability will increase if we either -
1. Make the collection properties settable so users can set them as `object.SomeCollectionProperty = new List<>(){ el1, el2 };`
2. Provide an `AddRange()` method on the collection properties.

Personally, I want to see option 1 being available. Option 2 is mostly to reduce the number of similar-looking lines, but the issue of discoverability still remains. Users who are not sure about using `Add()` to add elements will not look for `AddRange()` either.

**Comment by ssghoda** [comment] 2021-04-29 20:00
Yup, option 1 would be better if made possible since a lot of developers who worked with previous versions of SDK would be familiar with that approach. So they don't need to change their way to query Azure Search. Additionally, you can assign fields to SomeCollectionProperty in the same block where you assign values to other properties such as Filter, QueryType, SearchMode, Top, Skip.

**Comment by Mohit-Chakraborty** [comment] 2021-05-05 17:29
The new version of the SDK adheres strongly to framework design guidelines to ensure consistency amongst different services.
The [guideline applicable here](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/guidelines-for-collections#collection-properties-and-return-values) prohibits APIs from providing settable collection properties.

_❌ DO NOT provide settable collection properties.
Users can replace the contents of the collection by clearing the collection first and then adding the new contents. If replacing the whole collection is a common scenario, consider providing the AddRange method on the collection._

So, the improvement here would be to provide `AddRange()` on collection properties wherever missing.

**Comment by ssghoda** [comment] 2021-05-05 20:50
Ah okay. I would have liked settable collection properties as we had discussed but if that's what the guidelines prohibit, then no issues. Adding AddRange method would also help. Thanks a lot for pursuing this.

**Comment by Mohit-Chakraborty** [comment] 2021-05-05 22:13
BTW, another option is to use the list initlializer when constructing the object, which comes very close to the older syntax (of course only applicable when creating the object).

```
new SearchOptions
{
    Select = { "selectField1", "selectField1" }
});
```

which is the common pattern and the one you show above.

**Comment by Mohit-Chakraborty** [comment] 2021-06-04 05:31
I have created [an issue](https://github.com/Azure/autorest.csharp/issues/1296) to track the feature request to provide an `AddRange()` method on collection properties.
Since the other points are resolved, I am going to close this issue.

**Closed** 2021-06-07 21:25 UTC
Labels: Client, Search, customer-reported, needs-team-attention, question
