### ISSUE TITLE
[BUG][Service Bus][Functions] MessageBatch 'TryAddMessage' is not counting with 'diagnostic-id'

### ISSUE THREAD

**Issue by Dilergore** [Azure/azure-sdk-for-net#19127] opened 2021-03-02 14:39 UTC
**Describe the bug**
TryAddMessage is not counting the proper size when it is running in an Azure Function which is having App Insights enabled. Azure Function is adding 'diagnostic-id' custom property to the messages.

**Expected behavior**
TryAddMessage is determining the message size correctly

**Actual behavior (include Exception or Stack Trace)**
The actual message size is bigger than what the 'TryAddMessage' is counting resulting in 'MessageSizeExceeded' exception.

**To Reproduce**
Send multiple small messages as a batch from Azure Functions with App Insights enabled.

**Environment:**
 - Azure Functions 3
 - .Net Core 3.1
 - Azure.Messaging.ServiceBus 7.1.0

**Comment by Dilergore** [comment] 2021-03-02 15:17
The following screenshots were provided by Microsoft Support (Originally I opened a MS case to investigate this issue):
Function run:
![image](https://user-images.githubusercontent.com/14315890/109669531-77b87e80-7b72-11eb-92fe-aa890d0495c8.png)

Local run:
![image](https://user-images.githubusercontent.com/14315890/109669602-8bfc7b80-7b72-11eb-8006-2d80af3a0c1f.png)

**Comment by jsquire** [comment] 2021-03-02 16:00
Hi @Dilergore.  Thank you for your feedback and we regret that you're experiencing difficulties.   There was a fix for this merged yesterday (#19091) which will be included in our next release.

**Comment by Dilergore** [comment] 2021-03-02 17:44
@jsquire is there an ETA on the next release?

**Comment by Dilergore** [comment] 2021-03-02 17:45
never mind, i see there will be a beta release soon.

**Comment by jsquire** [comment] 2021-03-02 17:46
This will be included in the beta release next week.   I'll have to defer to @JoshLove-msft with respect to potential GA plans.

**Comment by jsquire** [comment] 2021-03-08 15:03
Confirming that this will be released in beta form and as a bugfix release at some point this week.  I'm going to close this out as discussion has tapered off and the root cause has been fixed.  Please feel free to reopen if you feel that further discussion is needed.

**Closed** 2021-03-08 15:04 UTC
Labels: Client, Service Bus, customer-reported, needs-author-feedback, question

**Comment by JoshLove-msft** [comment] 2021-03-08 19:31
@Dilergore we will have a beta out tomorrow. Would that work for you or do you need a patch release?

**Comment by Dilergore** [comment] 2021-03-09 06:54
@JoshLove-msft Thanks, I can wait for a few hours until you will come out with the next beta :-)

**Comment by Dilergore** [comment] 2021-03-10 14:03
I can confirm that the fix is working. Thanks!

@JoshLove-msft what is the ETA for a GA version?

**Comment by JoshLove-msft** [comment] 2021-03-10 18:38
7.2.0 would likely GA in May. We can release a patch to 7.1 if you don't want to wait until then.

**Comment by Dilergore** [comment] 2021-03-11 11:41
> 7.2.0 would likely GA in May. We can release a patch to 7.1 if you don't want to wait until then.

May is fine, thanks, we can wait until that. I am unblocked for now with my development and it is unlikely that we will go into production with the app I am working on before end of May.

**Comment by JoshLove-msft** [comment] 2021-03-11 20:14
Ended up releasing a patch after all - https://www.nuget.org/packages/Azure.Messaging.ServiceBus/7.1.1
