### ISSUE TITLE
[Metrics Advisor] test failing in nightly runs

### ISSUE THREAD

**Issue by v-yilinhu** [Azure/azure-sdk-for-net#22037] opened 2021-06-22 08:51 UTC
Metrics Advisor nightly test runs are failing with:

> Error Message
> Azure.RequestFailedException : Service request failed.
> Status: 400 (Bad Request)
> 
> Content:
> {"code":"ERROR_INVALID_PARAMETER","message":"endpoint is invalid."}
> 
> Headers:
> X-Request-ID: 07020cb3-172c-4f53-87b0-20156c6ea613
> x-envoy-upstream-service-time: 5135
> apim-request-id: 07020cb3-172c-4f53-87b0-20156c6ea613
> Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
> X-Content-Type-Options: nosniff
> Date: Tue, 01 Jun 2021 12:57:45 GMT
> Content-Length: 67
> Content-Type: application/json; charset=utf-8
> 
> Stack Trace
> at Azure.AI.MetricsAdvisor.AzureCognitiveServiceMetricsAdvisorRestAPIOpenAPIV2RestClient.CreateHookAsync(NotificationHook body, CancellationToken cancellationToken) in /_/sdk/metricsadvisor/Azure.AI.MetricsAdvisor/src/Generated/AzureCognitiveServiceMetricsAdvisorRestAPIOpenAPIV2RestClient.cs:line 2352
>    at Azure.AI.MetricsAdvisor.Administration.MetricsAdvisorAdministrationClient.CreateHookAsync(NotificationHook hook, CancellationToken cancellationToken) in /_/sdk/metricsadvisor/Azure.AI.MetricsAdvisor/src/MetricsAdvisorAdministrationClient.cs:line 1444
>    at Azure.Core.TestFramework.DiagnosticScopeValidatingInterceptor.<>c__DisplayClass4_0`1.<<WrapAsyncResultCore>g__Await|0>d.MoveNext() in D:\a\_work\1\s\sdk\core\Azure.Core.TestFramework\src\Instrumentation\DiagnosticScopeValidatingInterceptor.cs:line 91
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Threading.Tasks.ValueTask`1.get_Result()
>    at Azure.Core.TestFramework.DiagnosticScopeValidatingInterceptor.<>c__DisplayClass5_0`1.<<ValidateDiagnosticScopeInterceptor>b__0>d.MoveNext() in D:\a\_work\1\s\sdk\core\Azure.Core.TestFramework\src\Instrumentation\DiagnosticScopeValidatingInterceptor.cs:line 142
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Threading.Tasks.ValueTask`1.get_Result()
>    at Azure.Core.TestFramework.DiagnosticScopeValidatingInterceptor.ValidateDiagnosticScope[T](Func`1 action, MethodInfo methodInfo, String source) in D:\a\_work\1\s\sdk\core\Azure.Core.TestFramework\src\Instrumentation\DiagnosticScopeValidatingInterceptor.cs:line 165
>    at Azure.AI.MetricsAdvisor.Tests.DisposableNotificationHook.CreateHookAsync(MetricsAdvisorAdministrationClient adminClient, NotificationHook hook) in D:\a\_work\1\s\sdk\metricsadvisor\Azure.AI.MetricsAdvisor\tests\DisposableNotificationHook.cs:line 50
>    at Azure.AI.MetricsAdvisor.Tests.NotificationHookLiveTests.CreateAndGetWebNotificationHookWithOptionalMembers() in D:\a\_work\1\s\sdk\metricsadvisor\Azure.AI.MetricsAdvisor\tests\MetricsAdvisorAdministrationClient\NotificationHookLiveTests.cs:line 152
>    at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.BlockUntilCompleted()
>    at NUnit.Framework.Internal.MessagePumpStrategy.NoMessagePumpStrategy.WaitForCompletion(AwaitAdapter awaiter)
>    at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.<>c__DisplayClass1_0.<Execute>b__0()
>    at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.RunTestMethodInThreadAbortSafeZone(TestExecutionContext context, Action action)

For more details check here:

- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=921678&view=results
- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=923649&view=results
- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=925458&view=results
- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=929929&view=results

**Comment by kinelski** [comment] 2021-06-22 20:11
Duplicate of https://github.com/Azure/azure-sdk-for-net/issues/21504.

**Closed by kinelski** 2021-06-22 20:11 UTC
Labels: Client, Cognitive - Metrics Advisor, test-reliability
