### ISSUE TITLE
ServiceBusException: 'Transaction hasn't been declared yet, or has already been discharged'

### ISSUE THREAD

**Issue by johnknoop** [Azure/azure-sdk-for-net#14038] opened 2020-08-07 12:19 UTC
This happens when I send messages to more than one queue within the same TransactionScope:

```cs
var queueClient1 = new QueueClient(myConnString, "first_queue");
var queueClient2 = new QueueClient(myConnString, "second_queue");

using (var transaction = new TransactionScope(TransactionScopeAsyncFlowOption.Enabled))
{
	var message1 = new Message(Encoding.UTF8.GetBytes("test"))
	{
		SessionId = "session1"
	};

	await queueClient1.SendAsync(message1);

	var message2 = new Message(Encoding.UTF8.GetBytes("test"))
	{
		SessionId = "session1"
	};

	await queueClient2.SendAsync(message2);

	transaction.Complete();
}
```

The exception is thrown from the line `await queueClient2.SendAsync(message2);`.

The problem seems to be related to using more than one instance of `QueueClient`, rather than the fact that I'm sending messages to two different queues, because I've tried creating two instances of `QueueClient` for the same queue, and that didn't work either.

**Expected behavior**
I would expect it to work. Both clients enlisting with the current transactions.

**Actual behavior (include Exception or Stack Trace)**
See above.

**To Reproduce**
The code I pasted is enough to trigger the exception.

**Environment:**
 - Name and version of the Library package used: Microsoft.Azure.ServiceBus 3.4.0

 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects):
.NET Core SDK (reflecting any global.json):
 Version:   3.1.400
 Commit:    035fb2aa2f

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.400\

Host (useful for support):
  Version: 3.1.6
  Commit:  3acd9b0cd1

.NET Core SDKs installed:
  2.2.402 [C:\Program Files\dotnet\sdk]
  3.0.103 [C:\Program Files\dotnet\sdk]
  3.1.400 [C:\Program Files\dotnet\sdk]

 - IDE and version : VS 16.7.0

**Comment by jsquire** [comment] 2020-08-07 14:01
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by jsquire** [comment] 2020-08-07 14:01
//fyi:  @JoshLove-msft, @MiYanni

**Comment by axisc** [comment] 2020-08-12 00:12
@johnknoop thanks for raising this issue.
Within a transaction scope, all operations must be on a single QueueClient instance.

**Comment by johnknoop** [comment] 2020-08-12 08:12
@axisc yes I can tell :) But is this a bug or by design?

**Comment by axisc** [comment] 2020-08-13 23:55
ha, yes, that is by design :)

Please let me know if there are any other questions, otherwise I can proceed to close this issue.

**Comment by johnknoop** [comment] 2020-08-14 08:10
@axisc 

I see. Is this documented somewhere, so that one might read up on the reasons behind this limitation?

**Comment by axisc** [comment] 2020-09-02 00:15
yes, [here](https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-transactions#transactions-in-service-bus) is the documentation.

**Closed by axisc** 2020-09-02 00:15 UTC
Labels: Client, Service Attention, Service Bus, customer-reported, needs-team-attention, question

**Comment by shankarsama** [comment] 2020-09-16 18:08
Use SendVia feature with transactions.
Here is the example:
            ServiceBusConnection c = new ServiceBusConnection(connectionString);
            var sender2 = new MessageSender(c, "queue2", null);
            var sender3 = new MessageSender(c, "queue3", viaEntityPath: "queue2");

            using (var ts = new TransactionScope(TransactionScopeOption.Required, TransactionScopeAsyncFlowOption.Enabled))
            {

                // Send the message to the Queue2
                string messageBody = $"Message to queue2";
                var message1 = new Message(Encoding.UTF8.GetBytes(messageBody));
                await sender2.SendAsync(message1);

                // Send the message to the Queue3
                string messageBody2 = $"Message to queue3";
                var message2 = new Message(Encoding.UTF8.GetBytes(messageBody));
                await sender3.SendAsync(message2);

                ts.Complete();
            }

**Comment by johnknoop** [comment] 2020-09-16 19:37
@shankarsama thanks for the tip.

Can I use any queue as a "send via", or do I need to create a dedicated queue for that?

For example, if I want to send message M1 to queue Q1 and message M2 to queue Q2 within a transaction, could I then reuse Q1 for both messages, or would I then risk sending M2 to whichever process is subscribing to Q1?

**Comment by axisc** [comment] 2020-09-22 21:44
@johnknoop  the point here is to ensure that the transaction scope is on a single entity. In the example, it's "queue2", so that queue can be used as a send via for all the senders.

**Comment by johnknoop** [comment] 2021-01-16 21:02
Hi @axisc 

> ensure that the transaction scope is on a single entity

I'm not sure I understand what you mean.

I have the following entities:

- Topic: `mytesttopic`, which has one subscription: `input_subscription`
- Topic: `output_1`
- Topic: `output_2`
- Queue: `transferqueue`

I'm trying to receive sessions from `input_subscription` and for each received message:
1. Send a new message to `output_1` (via `transferqueue`)
2. Send another message to `output_2` (via `transferqueue`)
3. Complete the received message

All within one transaction, meaning, if the transaction doesn't complete, then the received message should be restored in the `input_subscription` and no messages should have been send.

Visually: 
```
                                                 ┌⟶ output_1
input_subscription ⟶ Handler ⟶ transferqueue ─┤
                                                 └⟶ output_2
```

This is the code:

```cs
var incomingSubscriptionClient = new SubscriptionClient(connection, "mytesttopic", "input_subscription", ReceiveMode.PeekLock, new NoRetry());
var output1sender = new MessageSender(connection, "output_1", "transferqueue");
var output2sender = new MessageSender(connection, "output_2", "transferqueue");

incomingSubscriptionClient.RegisterSessionHandler(async (receivedMessage, message, cancellation) =>
{
	using (var transaction = new TransactionScope(TransactionScopeAsyncFlowOption.Enabled))
	{
		await output1sender .SendAsync(new Message
		{
			Body = Encoding.UTF8.GetBytes("something"),
			SessionId = "mySessionId"
		});

		await output2sender .SendAsync(new Message
		{
			Body = Encoding.UTF8.GetBytes("something else"),
			SessionId = "mySessionId"
		});

		await session.CompleteAsync(receivedMessage.SystemProperties.LockToken);

		transaction.Complete();
	}
}, new SessionHandlerOptions(exception =>
{
	Console.WriteLine("session Receiver exception: " + exception.Exception.Message);
	return Task.CompletedTask;
}));
```

But I'm now getting this exception when completing the received message:
> System.InvalidOperationException: 'Local transactions cannot span multiple entities or partitions.'

Any ideas what I might be doing wrong? I thought that by sending both outbound messages through `transferqueue` I was doing what's needed to make this work.

**Comment by johnknoop** [comment] 2021-01-19 15:30
@shankarsama do you have any idea why this is happening? ⬆
