### ISSUE TITLE
ServiceBusClient.AcceptNextSessionAsync logs ServiceBusException as "exception" (not as verbose)  after ServiceTimeout

### ISSUE THREAD

**Issue by ulluoink** [Azure/azure-sdk-for-net#46096] opened 2024-09-20 10:18 UTC
@johankson the fix was to reduce the severity of this log message. Are you seeing this logged as Verbose?

_Originally posted by @JoshLove-msft in https://github.com/Azure/azure-sdk-for-net/issues/27976#issuecomment-1258513410_
            
in our case this is still logged as exception. how can we provide the logTimeoutResourceAsVerbose parameter?

whenever we call ServiceBusClient.AcceptNextSessionAsync the expected ServiceBusException with reason ServiceBusFailureReason.ServiceTimeout is logged as an exception to console and application insights.

how can we change this behaviour?

**Comment by jsquire** [comment] 2024-09-20 15:55
Hi @ulluoink.  Thanks for reaching out and we regret that you're experiencing difficulties.   There's not enough context available in the issue to assist at the moment.  Please help us understand:

  - The package and version that you're using.  It isn't clear if this is a Functions-related inquiry or direct SDK use.
  - The scenario that you're asking about.   Including code snippets to demonstrate repro.

**Comment by ulluoink** [comment] 2024-09-20 16:15
- timer triggered Azure Function .net 8 isolated worker
- this function is triggered and then loads via Azure.Messaging.ServiceBus 7.17.5 ServiceBusClient.Acceptnextsession the sessions from a servicebus topic subscription.

we of course expect a ServiceBusException with reason ServiceBusFailureReason.ServiceTimeout if no messages/sessions are available.

but this exception is logged which we do not want because this is an expected exception

**Comment by ulluoink** [comment] 2024-09-23 10:52
The problem seems to be in ServiceBusSessionReceiver.cs in CreateSessionReceiverAsync.

when 
await receiver.OpenLinkAsync(cancellationToken).ConfigureAwait(false);
throws the ServiceBusException because of the ServiceTimeout this is not catched because the "isProcessor" parameter of CreateSessionReceiverAsync is false.

so only the common Exception is catched
catch (Exception ex)
{
    await receiver.CloseAsync(CancellationToken.None).ConfigureAwait(false);
    receiver.Logger.ClientCreateException(typeof(ServiceBusSessionReceiver), receiver.FullyQualifiedNamespace, entityPath, ex);
    throw;
}

and the Logger.ClientCreateException is called which is bad and simply wrong because the client has been succesfully created just before the try catch block

instead this line fails
await receiver.OpenLinkAsync(cancellationToken).ConfigureAwait(false);

with the expected ServiceBusException and the reason ServiceBusFailureReason.ServiceTimeout.

**Comment by ulluoink** [comment] 2024-09-24 08:41
@jsquire did you have the opportunity to look into this?

**Comment by jsquire** [comment] 2024-09-24 19:46
@ulluoink : The client logic is correct in the block that you're highlighting.  For a session receiver to be successfully created, the link must be established.   Otherwise, the client is not viable.  Because you're using the client directly rather than via the trigger or a processor, the error is correct as is the logic path.

That said, one can make the case that a known timeout attempting to create a session receiver should be represented differently in the logs and appear as a known "no available session" at an informational or verbose level rather than a client creation error log.   Before doing so, there's still some additional investigation needed to understand why it was designed this way, which I'm still following-up on.

In the meantime, can you help me understand more about your application?  The timer trigger that you're using is not an Azure SDK client-based trigger.  As such, it does not import the Azure SDK infrastructure or start the process that forwards our ETW logs to the Functions ILogger instance.  There's missing context to explain why logs are being captured, but it would imply that either you're using another WebJobs extension package for an Azure SDK client or you're using the Azure SDK extensions package and starting the forwarder directly.  

Can you share more details and, ideally, the packages section of your `.csproj` file?

**Comment by jsquire** [comment] 2024-09-26 17:26
Thanks, @ulluoink.  I spent some time running down history here and can't find any rationale or justification for why we're treating the processor scenario differently.  After some internal discussions, we're in agreement that the logs are inaccurate in this scenario.   We're going to add an additional timeout clause with a non-processor focused message.  We'll do our best to get this included in the October releases, assuming that we don't encounter any unexpected issues during testing.

I'm still not 100% sure which packages is auto-starting the forwarder, as that will normally only happen when an Azure SDK Functions extension package is providing a trigger.  However, that's orthogonal and more a curiosity than impactful here.

**Comment by jsquire** [comment] 2024-10-01 21:13
fixed by #46388

**Comment by ulluoink** [comment] 2024-10-01 21:24
Thank you @jsquire for your commitment and the quick solution

**Closed** 2024-10-16 22:35 UTC
Labels: Client, customer-reported, bug, Functions, issue-addressed
