### ISSUE TITLE
Specified section doesn't have an equivalent 

### ISSUE THREAD

**Issue by MatthewSteeples** [Azure/azure-sdk-for-net#18090] opened 2021-01-20 21:58 UTC
The middle and bottom `Service principal client certificate` which specifies a certificate based on `CertificateThumbprint` and `CertificateStoreLocation` doesn't have an equivalent in the new system. The options provided do not offer the same functionality.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1f95d1f9-f552-ab33-2cbb-f5bc09f6cf5f
* Version Independent ID: 76c243d5-0e9f-cb8d-8919-a06e75ad2cf5
* Content: [App Authentication to Azure Identity Migration Guidance - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/overview/azure/app-auth-migration)
* Content Source: [api/overview/azure/app-auth-migration.md](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/api/overview/azure/app-auth-migration.md)
* Product: **azure**
* GitHub Login: @jlichwa
* Microsoft Alias: **jalichwa**

**Comment by MatthewSteeples** [comment] 2021-01-20 22:04
This may be better converted into a feature request to support this functionality. My scenario is that I have a certificate in the Store on a VM. Previously I could just specify the hash and the location of the certificate in an environment variable whereas now I need to investigate loading the certificate from the store myself and passing it into in instance of a `ClientCertificateCredential`

**Comment by jsquire** [comment] 2021-01-20 22:06
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by MatthewSteeples** [comment] 2021-01-20 22:10
Thanks @jsquire 

I'll also add that if you're happy accepting a contribution for this then I'm happy to try and put something together

**Comment by christothes** [comment] 2021-02-22 18:06
related to #11804

**Comment by christothes** [comment] 2021-03-19 15:44
duplicate of #11804

**Closed by christothes** 2021-03-19 15:44 UTC
Labels: Azure.Identity, Client, customer-reported, feature-request
