### ISSUE TITLE
Guid type causes KeyNotFoundException in calls to CreateDeserializerOnly<T> or CreateGenericDeserializerOnly

### ISSUE THREAD

**Issue by sokhalsa** [Azure/azure-sdk-for-net#987] opened 2015-03-05 00:49 UTC
When attempting to call AvroSerializer.CreateDeserializerOnly<T> or AvroSerializer.CreateGenericDeserializerOnly with a writer schema for a type that contains a Guid, a KeyNotFoundException ("The given key was not present in the dictionary.") error is thrown in JsonSchemaBuilder.CreatePrimitiveTypeSchema because "System.Guid" is not a key in the PrimitiveRuntimeType dictionary.

The stack trace is:

   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Microsoft.Hadoop.Avro.Schema.JsonSchemaBuilder.CreatePrimitiveTypeSchema(String type, Dictionary`2 attributes) in d:\Git\WindowsAzure\azure-sdk-for-net\src\HDInsight\Microsoft.Hadoop.Avro\Schema\JsonSchemaBuilder.cs:line 410
   at Microsoft.Hadoop.Avro.Schema.JsonSchemaBuilder.ParsePrimitiveTypeFromString(String token) in d:\Git\WindowsAzure\azure-sdk-for-net\src\HDInsight\Microsoft.Hadoop.Avro\Schema\JsonSchemaBuilder.cs:line 382
   at Microsoft.Hadoop.Avro.Schema.JsonSchemaBuilder.Parse(JToken token, NamedSchema parent, Dictionary`2 namedSchemas) in d:\Git\WindowsAzure\azure-sdk-for-net\src\HDInsight\Microsoft.Hadoop.Avro\Schema\JsonSchemaBuilder.cs:line 105
   at Microsoft.Hadoop.Avro.Schema.JsonSchemaBuilder.ParseRecordField(JObject field, NamedSchema parent, Dictionary`2 namedSchemas, Int32 position) in d:\Git\WindowsAzure\azure-sdk-for-net\src\HDInsight\Microsoft.Hadoop.Avro\Schema\JsonSchemaBuilder.cs:line 349
   at Microsoft.Hadoop.Avro.Schema.JsonSchemaBuilder.<>c__DisplayClass3.<ParseRecordType>b__2(JToken field, Int32 index) in d:\Git\WindowsAzure\azure-sdk-for-net\src\HDInsight\Microsoft.Hadoop.Avro\Schema\JsonSchemaBuilder.cs:line 318
   at System.Linq.Enumerable.<SelectIterator>d__7`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Microsoft.Hadoop.Avro.Schema.JsonExtensions.ReadArrayProperty[T](JToken token, String propertyName, Boolean isOptional, Func`3 func) in d:\Git\WindowsAzure\azure-sdk-for-net\src\HDInsight\Microsoft.Hadoop.Avro\Schema\JsonExtensions.cs:line 195
   at Microsoft.Hadoop.Avro.Schema.JsonExtensions.OptionalArrayProperty[T](JToken token, String propertyName, Func`3 func) in d:\Git\WindowsAzure\azure-sdk-for-net\src\HDInsight\Microsoft.Hadoop.Avro\Schema\JsonExtensions.cs:line 78
   at Microsoft.Hadoop.Avro.Schema.JsonSchemaBuilder.ParseRecordType(JObject record, NamedSchema parent, Dictionary`2 namedSchemas) in d:\Git\WindowsAzure\azure-sdk-for-net\src\HDInsight\Microsoft.Hadoop.Avro\Schema\JsonSchemaBuilder.cs:line 309
   at Microsoft.Hadoop.Avro.Schema.JsonSchemaBuilder.ParseJsonObject(JObject token, NamedSchema parent, Dictionary`2 namedSchemas) in d:\Git\WindowsAzure\azure-sdk-for-net\src\HDInsight\Microsoft.Hadoop.Avro\Schema\JsonSchemaBuilder.cs:line 140
   at Microsoft.Hadoop.Avro.Schema.JsonSchemaBuilder.Parse(JToken token, NamedSchema parent, Dictionary`2 namedSchemas) in d:\Git\WindowsAzure\azure-sdk-for-net\src\HDInsight\Microsoft.Hadoop.Avro\Schema\JsonSchemaBuilder.cs:line 88
   at Microsoft.Hadoop.Avro.Schema.JsonSchemaBuilder.BuildSchema(String schema) in d:\Git\WindowsAzure\azure-sdk-for-net\src\HDInsight\Microsoft.Hadoop.Avro\Schema\JsonSchemaBuilder.cs:line 71
   at Microsoft.Hadoop.Avro.AvroSerializer.CreateForCore[T](String writerSchema, AvroSerializerSettings settings) in d:\Git\WindowsAzure\azure-sdk-for-net\src\HDInsight\Microsoft.Hadoop.Avro\AvroSerializer.Static.cs:line 177
   at Microsoft.Hadoop.Avro.AvroSerializer.CreateDeserializerOnly[T](String writerSchema, AvroSerializerSettings settings) in d:\Git\WindowsAzure\azure-sdk-for-net\src\HDInsight\Microsoft.Hadoop.Avro\AvroSerializer.Static.cs:line 98

**Comment by sokhalsa** [comment] 2015-03-05 17:46
It looks like it has to do with multiple Guid members in a class causing JsonSchemaBuilder to the schema incorrectly.

Given the following class:

    [System.Runtime.Serialization.DataContract]
        public class ClassOfGuid
        {
            [System.Runtime.Serialization.DataMember]
            public Guid PrimitiveGuid;

            [System.Runtime.Serialization.DataMember]
            public Guid AnotherPrimitiveGuid;
        }

A call to AvroSerializer.CreateDeserializerOnly<T> will fail with a KeyNotFoundException. The following test case demonstrates that:

        [TestMethod]
        [TestCategory("CheckIn")]
        public void JsonSchemaBuilder_ClassOfGuidWriterSchema()
        {
            var settings = new Microsoft.Hadoop.Avro.AvroSerializerSettings();
            Microsoft.Hadoop.Avro.IAvroSerializer<ClassOfGuid> serializer = Microsoft.Hadoop.Avro.AvroSerializer.Create<ClassOfGuid>(settings);
            Microsoft.Hadoop.Avro.AvroSerializer.CreateDeserializerOnly<ClassOfGuid>(serializer.WriterSchema.ToString(), settings);
        }

**Comment by markcowl** [comment] 2015-03-13 21:34
@sokhalsa Thank you for the feedback.  Assigned to the appropriate team

**Comment by jholovacs** [comment] 2017-03-31 12:57
Was anything ever done with this?  It's still open 2 years later.

**Comment by shahabhijeet** [comment] 2018-03-15 20:41
please reopen if this is still an issue.

**Closed by shahabhijeet** 2018-03-15 20:41 UTC
Labels: HDInsight

**Comment by IvanDeev** [comment] 2020-11-26 11:26
Looks like it wasn't fixed. Reproduces in Microsoft.Hadoop.Avro2 1.2.1 and microsoft.hadoop.avro-core 1.1.19. And I don't see Microsoft.Hadoop.Avro in azure-sdk-for-net now.
