### ISSUE TITLE
Address spellchecker errors

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-for-net#23000] opened 2021-07-30 18:19 UTC
Errors: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1024662&view=logs&j=10327055-d4d6-50a6-a312-3d2cd4bd9cb9&t=65f0e4aa-f456-5911-deca-bd807ca3354c&l=68

To run the tool locally, run `eng\scripts\Export-API.ps1 -SpellCheckPublicApiSurface <service>`

If there are errors, please fix them.
If there are false positives, add them to https://github.com/Azure/azure-sdk-for-net/blob/main/.vscode/cspell.json#L68

**Comment by danieljurek** [comment] 2021-08-06 23:03
Duplicate of https://github.com/Azure/azure-sdk-for-net/issues/23175

**Closed by danieljurek** 2021-08-06 23:03 UTC
Labels: Container Registry, Client
