### ISSUE TITLE
Consider adding GetRawResponse to RequestFailedException

### ISSUE THREAD

**Issue by christothes** [Azure/azure-sdk-for-net#34941] opened 2023-03-15 19:35 UTC
For some scenarios it may be important to see the raw error response rather than the parsed error details offered by RFE. 

Presumably, any response content that comes back as an error would not be large, and this is an error scenario, so I don't think perf would be a concern.

One scenario where this could be beneficial is in Identity where we don't want to parse potentially sensitive information by default, but should allow developers to easily inspect the error response details for troubleshooting.

**Comment by heaths** [comment] 2023-04-13 17:52
This is also blocking any customers who need to parse error details to otherwise condition their service.

**Comment by annelo-msft** [comment] 2023-04-17 17:02
Is this a duplicate of https://github.com/Azure/azure-sdk-for-net/issues/10922?

(i.e. would we close https://github.com/Azure/azure-sdk-for-net/issues/10922 if we implemented this?)

**Comment by heaths** [comment] 2023-04-17 18:55
> Is this a duplicate of #10922?
> 
> (i.e. would we close #10922 if we implemented this?)

Seems like a dup, yes. Or at least close enough. If we implemented this, as long as we expose headers (which we would if we expose the whole response like other tier 1 languages are all doing), we should close #10922 as well.

**Comment by annelo-msft** [comment] 2023-05-11 19:17
Completed with https://github.com/Azure/azure-sdk-for-net/pull/35716

**Closed by annelo-msft** 2023-05-11 19:17 UTC
Labels: Client, Azure.Core, feature-request
