### ISSUE TITLE
[BUG] TableClient query does not filter nullable DateTimeOffset properties correctly using LINQ

### ISSUE THREAD

**Issue by EM15** [Azure/azure-sdk-for-net#38590] opened 2023-09-08 13:01 UTC
### Library name and version

Azure.Data.Tables 12.8.1

### Describe the bug

I'm using the TableClient to get records of a table and some records are not returned even though they meet the conditions defined on the filter. Behaviour is different for CosmosDB and for Table Storage. It happens with `DateTimeOffset?` but I noticed a the same behaviour with `Guid?`.

Let's say I have two records, one with a date and another one with no date.

```
var notAnonymizedRecords = await tableClient
    .QueryAsync<SomeRecord>(x => x.AnonymizedAt == null)
    .ToListAsync();

var anonymizedRecords = await tableClient
    .QueryAsync<SomeRecord>(x => x.AnonymizedAt != null)
    .ToListAsync();

Console.WriteLine($"NotAnonymized records: {notAnonymizedRecords.Count}");
Console.WriteLine($"Anonymized records: {anonymizedRecords.Count}");
```

### Expected behavior

```
NotAnonymized records: 1
Anonymized records: 1
```

### Actual behavior

In Cosmos:
```
NotAnonymized records: 0
Anonymized records: 1
```

In Table Storage
```
NotAnonymized records: 1
Anonymized records: 0
```

### Reproduction Steps

You can try both Cosmos/Table storage using a console app. 
Table connection string is the default for the emulator.
Cosmos connection string is the default for the emulator if you start it with the table api: https://learn.microsoft.com/en-us/azure/cosmos-db/local-emulator?tabs=ssl-netstd21#api-for-table

```
using Azure;
using Azure.Data.Tables;

// Cosmos emulator connectionString
//var connectionString = "DefaultEndpointsProtocol=http;AccountName=localhost;AccountKey=C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw==;TableEndpoint=http://localhost:8902/;";

// Table connectionString
var connectionString = "DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;TableEndpoint=http://localhost:10002/devstoreaccount1;";

var tableServiceClient = new TableServiceClient(connectionString);
await tableServiceClient.DeleteTableAsync("SomeTable");

var tableClient = tableServiceClient.GetTableClient("SomeTable");
await tableClient.CreateIfNotExistsAsync();

var someNotAnonymizedRecord = new SomeRecord
{
    PartitionKey = Guid.NewGuid().ToString(),
    RowKey = Guid.NewGuid().ToString()
};
var someAnonymizedRecord = new SomeRecord
{
    PartitionKey = Guid.NewGuid().ToString(),
    RowKey = Guid.NewGuid().ToString(),
    AnonymizedAt = DateTimeOffset.Now
};

await tableClient.AddEntityAsync(someNotAnonymizedRecord);
await tableClient.AddEntityAsync(someAnonymizedRecord);

var records = await tableClient
    .QueryAsync<SomeRecord>()
    .ToListAsync();
var notAnonymizedRecords = await tableClient
    .QueryAsync<SomeRecord>(x => x.AnonymizedAt == null)
    .ToListAsync();
var anonymizedRecords = await tableClient
    .QueryAsync<SomeRecord>(x => x.AnonymizedAt != null)
    .ToListAsync();

Console.WriteLine($"Total records: {records.Count}");
Console.WriteLine($"NotAnonymized records: {notAnonymizedRecords.Count}");
Console.WriteLine($"Anonymized records: {anonymizedRecords.Count}");
Console.ReadKey();

class SomeRecord : ITableEntity
{
    public string PartitionKey { get; set; }
    public string RowKey { get; set; }
    public DateTimeOffset? Timestamp { get; set; }
    public ETag ETag { get; set; }
    public DateTimeOffset? AnonymizedAt { get; set; }
};

static class Extensions
{
    public static async Task<List<SomeRecord>> ToListAsync(this AsyncPageable<SomeRecord> records)
    {
        var list = new List<SomeRecord>();
        await foreach (var record in records)
        {
            list.Add(record);
        }
        return list;
    }
}
```

### Environment

.NET SDK (reflecting any global.json):
 Version:   6.0.413
 Commit:    10710f7d8e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22621
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.413\

Host:
  Version:      7.0.10
  Architecture: x64
  Commit:       a6dbb800a4

.NET SDKs installed:
  6.0.413 [C:\Program Files\dotnet\sdk]
  7.0.100-rc.2.22477.23 [C:\Program Files\dotnet\sdk]
  7.0.100 [C:\Program Files\dotnet\sdk]
  7.0.307 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.31 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.0-rc.2.22476.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.31 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.21 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.0-rc.2.22472.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.31 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.21 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.0-rc.2.22472.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  C:\Repos\Roomz\dotnet-monorepo\global.json

**Comment by EM15** [comment] 2023-09-08 13:55
I was trying a bit with Table Storage Explorer and Cosmos Explorer and it works by executing the queries like this:

```
TableStorage valid queries:
- Anonymized: AnonymizedAt ne ''
- Not Anonymized: AnonymizedAt eq null

Cosmos valid queries:
- Anonymized: 
	* SELECT * FROM c WHERE c.AnonymizedAt <> ''
	* SELECT * FROM c WHERE c.AnonymizedAt <> null
        * SELECT * FROM c WHERE IS_DEFINED(c.AnonymizedAt)
- Not Anonymized: SELECT * FROM c WHERE NOT IS_DEFINED(c.AnonymizedAt)
```

**Comment by jsquire** [comment] 2023-09-08 21:10
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by christothes** [comment] 2023-09-08 22:16
Hi @EM15 
This is a known limitation of the Cosmos backend for Tables and is documented [here](https://learn.microsoft.com/azure/cosmos-db/table/tutorial-query#query-by-using-an-odata-filter). The service team is aware of it, but I don't think there are any plans to change this behavior currently. 

( duplicate of #32468)

**Closed** 2023-09-15 22:33 UTC
Labels: Client, customer-reported, question, Tables, issue-addressed
